Repository kubermatic/kubermatic, pull requests merged in 2020-12, with the labels that each got.

#6230 update controller-runtime to 0.6.4
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6232 update Zap to 1.16.0
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6229 fix annotation overflow fix
  pkg/clusterdeletion/lb.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS, team/lifecycle

#6217 Implement new expose types in EnvoyManager
  pkg/controller/nodeport-proxy/envoymanager/controller.go
  pkg/controller/nodeport-proxy/envoymanager/controller_test.go
  pkg/controller/nodeport-proxy/envoymanager/resources.go
  pkg/controller/nodeport-proxy/envoymanager/utils.go
  pkg/controller/nodeport-proxy/envoymanager/utils_test.go
  pkg/test/builder.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL, team/lifecycle

#6233 Update to Masterminds/semver/v3
  cmd/conformance-tests/main.go
  cmd/image-loader/helm.go
  cmd/image-loader/main.go
  cmd/image-loader/operator.go
  cmd/kubermatic-api/swagger.json
  cmd/kubermatic-installer/cmd_deploy.go
  go.mod
  go.sum
  pkg/addon/template.go
  pkg/api/v1/types.go
  pkg/controller/nodeport-proxy/envoymanager/controller.go
  pkg/controller/operator/common/defaults.go
  pkg/crd/operator/v1alpha1/configuration.go
  pkg/crd/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/handler/common/machine.go
  pkg/handler/common/upgrade.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/upgrade.go
  pkg/handler/v1/cluster/upgrade_test.go
  pkg/handler/v1/common/version_skew.go
  pkg/handler/v2/cluster/upgrade_test.go
  pkg/install/helm/cli.go
  pkg/install/helm/interface.go
  pkg/install/helm/types.go
  pkg/provider/kubernetes/admission_plugin.go
  pkg/resources/machine/machinedeployment.go
  pkg/resources/test/load_files_test.go
  pkg/semver/semver.go
  pkg/test/e2e/api/runner.go
  pkg/test/e2e/api/util.go
  pkg/userdata/openshift/openshift.go
  pkg/validation/nodeupdate/nodeupdate.go
  pkg/version/manager.go
  pkg/version/manager_test.go
  pkg/version/version_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle, team/ui

#6228 v2 endpoints list GCP sizes, disk types, zones, networks, subnetworks
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/provider/gcp.go
  pkg/handler/v1/provider/gcp.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/provider/gcp.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/gcp/gcp_client.go
  pkg/test/e2e/api/utils/apiclient/client/gcp/list_g_c_p_disk_types_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/gcp/list_g_c_p_disk_types_no_credentials_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/gcp/list_g_c_p_networks_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/gcp/list_g_c_p_networks_no_credentials_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/gcp/list_g_c_p_sizes_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/gcp/list_g_c_p_sizes_no_credentials_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/gcp/list_g_c_p_subnetworks_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/gcp/list_g_c_p_subnetworks_no_credentials_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/gcp/list_g_c_p_zones_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/gcp/list_g_c_p_zones_no_credentials_v2_responses.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL, team/ui

#6236 Fix field indexer used to index services to be exposed by nodeport-proxy
  pkg/controller/nodeport-proxy/envoymanager/controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6237 Fix nodeport proxy e2e tests
  OWNERS_ALIASES
  cmd/nodeport-proxy/OWNERS
  pkg/controller/nodeport-proxy/OWNERS
  pkg/test/e2e/nodeport-proxy/network.go
  pkg/test/e2e/nodeport-proxy/nodeport_proxy_test.go
  pkg/test/e2e/nodeport-proxy/services.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6238 v2 revoke cluster kubeconfig tokens
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/api/utils/apiclient/client/project/revoke_cluster_admin_token_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/revoke_cluster_admin_token_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/revoke_cluster_viewer_token_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/revoke_cluster_viewer_token_v2_responses.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#6241 Create RBAC role to allow kubeadm to get nodes
  addons/rbac/allow-kubeadm-get-nodes.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#6064 Improve initial node deployment creation
  .gitignore
  cmd/seed-controller-manager/controllers.go
  pkg/api/v1/time.go
  pkg/api/v1/types.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller_test.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/doc.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/handler/common/cluster.go
  pkg/handler/routes_v1.go
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/constraint_template/constraint_template.go
  pkg/handler/v2/routes_v2.go
  pkg/handler/websocket/user_test.go
  pkg/provider/cloud/gcp/provider.go
  pkg/resources/cloudconfig/configmap.go
Labels: approved, dco-signoff: yes, lgtm, priority/normal, release-note, size/XL, team/lifecycle, team/ui

#6235 Add flags for new expose types and update lb-updater
  Makefile
  cmd/image-loader/main.go
  cmd/nodeport-proxy/envoy-manager/main.go
  cmd/nodeport-proxy/lb-updater/main.go
  cmd/nodeport-proxy/lb-updater/main_test.go
  pkg/controller/nodeport-proxy/envoymanager/controller.go
  pkg/controller/nodeport-proxy/envoymanager/resources.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/operator/seed/resources/nodeportproxy/deployments.go
  pkg/features/features.go
  pkg/test/e2e/nodeport-proxy/deployer.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6240 update aliyun/alibaba-cloud-sdk-go to v1.61.733
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6243 update digitalocean/godo to v1.54.0
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6249 update hetznercloud/hcloud to 1.23.1
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6242 update ec2-instances-info to 2020-11-10
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6251 Add changelogs for 2.14.9 and 2.15.5
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6239 Update to sprig v3
  cmd/node-resource-documenter/main.go
  codegen/reconcile/main.go
  go.mod
  go.sum
  pkg/addon/template.go
  pkg/controller/seed-controller-manager/openshift/resources/controlplane_configmap.go
  pkg/controller/seed-controller-manager/openshift/resources/kube_controller_manager.go
  pkg/controller/seed-controller-manager/openshift/resources/oauth.go
  pkg/controller/seed-controller-manager/openshift/resources/openshift_controller_manager.go
  pkg/resources/etcd/cronjob.go
  pkg/resources/etcd/statefulset.go
  pkg/resources/prometheus/configmap.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6060 Add explicit context handling in conformance-tests
  .prow.yaml
  cmd/conformance-tests/cleanup.go
  cmd/conformance-tests/custom_tests.go
  cmd/conformance-tests/main.go
  cmd/conformance-tests/runner.go
  cmd/conformance-tests/scenarios_alibaba.go
  cmd/conformance-tests/scenarios_aws.go
  cmd/conformance-tests/scenarios_azure.go
  cmd/conformance-tests/scenarios_digitalocean.go
  cmd/conformance-tests/scenarios_gcp.go
  cmd/conformance-tests/scenarios_hetzner.go
  cmd/conformance-tests/scenarios_kubevirt.go
  cmd/conformance-tests/scenarios_openstack.go
  cmd/conformance-tests/scenarios_packet.go
  cmd/conformance-tests/scenarios_vsphere.go
  cmd/conformance-tests/usercluster_controller_tests.go
  hack/images/integration-tests/Dockerfile
  hack/images/integration-tests/release.sh
  pkg/cluster/client/client.go
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/controller/seed-controller-manager/addon/addon_controller_test.go
  pkg/controller/seed-controller-manager/constraint-template-controller/controller.go
  pkg/controller/seed-controller-manager/constraint-template-controller/controller_test.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller_test.go
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/controller/seed-controller-manager/kubernetes/launching.go
  pkg/controller/seed-controller-manager/monitoring/monitoring_controller.go
  pkg/controller/seed-controller-manager/openshift/openshift_controller.go
  pkg/controller/seed-controller-manager/rancher/controller.go
  pkg/controller/seed-controller-manager/update/update_controller.go
  pkg/handler/common/cluster.go
  pkg/handler/common/machine.go
  pkg/handler/common/role.go
  pkg/handler/common/upgrade.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/role.go
  pkg/handler/v1/common/common.go
  pkg/handler/v1/kubernetes-dashboard/dashboard.go
  pkg/handler/v1/project/project_test.go
  pkg/provider/kubernetes/cluster.go
  pkg/provider/kubernetes/cluster_internal_test.go
  pkg/provider/types.go
Labels: approved, dco-signoff: yes, lgtm, priority/low, release-note-none, size/L, team/lifecycle, team/ui

#6261 Update minor Go dependencies
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6224 Constraint controller
  cmd/user-cluster-controller-manager/main.go
  pkg/api/v1/types.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller_test.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/doc.go
  pkg/handler/test/fake_schema.go
  pkg/handler/test/helper.go
  pkg/handler/v2/constraint/constraint_test.go
  pkg/resources/test/fixtures/deployment-aws-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-apiserver.yaml
  pkg/resources/usercluster/rbac.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/lifecycle, team/ui

#6262 v2 endpoints to get Hetzner and Digitalocean instance sizes
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/provider/digitalocean.go
  pkg/handler/common/provider/hetzner.go
  pkg/handler/v1/provider/digitalocean.go
  pkg/handler/v1/provider/hetzner.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/provider/digitalocean.go
  pkg/handler/v2/provider/hetzner.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/digitalocean/digitalocean_client.go
  pkg/test/e2e/api/utils/apiclient/client/digitalocean/list_digitalocean_sizes_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/digitalocean/list_digitalocean_sizes_no_credentials_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/hetzner/hetzner_client.go
  pkg/test/e2e/api/utils/apiclient/client/hetzner/list_hetzner_sizes_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/hetzner/list_hetzner_sizes_no_credentials_v2_responses.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#6256 Add Tunneling strategy to the data model
  cmd/kubermatic-api/options.go
  cmd/kubermatic-api/swagger.json
  cmd/nodeport-proxy/envoy-manager/main.go
  cmd/nodeport-proxy/lb-updater/main.go
  cmd/nodeport-proxy/lb-updater/main_test.go
  pkg/api/v1/types.go
  pkg/controller/master-controller-manager/seed-sync/reconciler.go
  pkg/controller/master-controller-manager/seed-sync/reconciler_test.go
  pkg/controller/nodeport-proxy/envoymanager/controller.go
  pkg/controller/nodeport-proxy/envoymanager/controller_test.go
  pkg/controller/nodeport-proxy/envoymanager/resources.go
  pkg/controller/nodeport-proxy/envoymanager/utils.go
  pkg/controller/nodeport-proxy/envoymanager/utils_test.go
  pkg/controller/operator/common/defaults.go
  pkg/controller/operator/seed/resources/nodeportproxy/deployments.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/seed-controller-manager/kubernetes/resources_test.go
  pkg/controller/seed-controller-manager/openshift/openshift_controller.go
  pkg/controller/seed-controller-manager/openshift/openshift_controller_test.go
  pkg/controller/seed-controller-manager/openshift/resources.go
  pkg/controller/seed-controller-manager/openshift/resources/oauth.go
  pkg/controller/seed-controller-manager/openshift/resources_test.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/common.go
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/crd/kubermatic/v1/utils.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/operator/v1alpha1/configuration.go
  pkg/ee/conversion/helm.go
  pkg/handler/common/cluster.go
  pkg/handler/routing.go
  pkg/handler/test/hack/hack.go
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/routing.go
  pkg/resources/address/address.go
  pkg/resources/address/address_test.go
  pkg/resources/apiserver/service.go
  pkg/resources/apiserver/service_test.go
  pkg/resources/openvpn/service.go
  pkg/resources/rancherserver/service.go
  pkg/resources/test/load_files_test.go
  pkg/test/e2e/api/utils/apiclient/models/expose_strategy.go
  pkg/test/e2e/api/utils/apiclient/models/seed.go
  pkg/test/e2e/api/utils/apiclient/models/seed_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6271 Update login background in Dex
  charts/oauth/Chart.yaml
  charts/oauth/theme/bg.svg
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#6272 Default to the latest available OpenStack CCM version
  docs/adding-kubernetes-versions.md
  pkg/resources/cloudcontroller/openstack.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#6255 added proper gatekeeper namespace
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/namespace.go
  pkg/resources/gatekeeper/deployment.go
  pkg/resources/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6273 Fix OpenStack CCM supported version validation
  pkg/resources/cloudcontroller/openstack.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6264 v2 endpoints to list OpenStack resources
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/provider/openstack.go
  pkg/handler/v1/provider/openstack.go
  pkg/handler/v1/provider/openstack_test.go
  pkg/handler/v2/provider/openstack.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/openstack/list_openstack_availability_zones_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/openstack/list_openstack_availability_zones_no_credentials_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/openstack/list_openstack_networks_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/openstack/list_openstack_networks_no_credentials_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/openstack/list_openstack_security_groups_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/openstack/list_openstack_security_groups_no_credentials_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/openstack/list_openstack_sizes_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/openstack/list_openstack_sizes_no_credentials_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/openstack/list_openstack_subnets_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/openstack/list_openstack_subnets_no_credentials_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/openstack/list_openstack_tenants_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/openstack/list_openstack_tenants_no_credentials_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/openstack/openstack_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#6275 v2 to list azure resources
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/provider/azure.go
  pkg/handler/v1/provider/azure.go
  pkg/handler/v1/provider/azure_test.go
  pkg/handler/v2/provider/azure.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/azure/azure_client.go
  pkg/test/e2e/api/utils/apiclient/client/azure/list_azure_availability_zones_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/azure/list_azure_availability_zones_no_credentials_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/azure/list_azure_sizes_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/azure/list_azure_sizes_no_credentials_v2_responses.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#6282 Do not require cert-manager CRDs for oauth chart
  charts/oauth/Chart.yaml
  charts/oauth/templates/_helpers.tpl
  charts/oauth/templates/certificate.yaml
  charts/oauth/templates/cluster-role-binding.yaml
  charts/oauth/templates/cluster-role.yaml
  charts/oauth/templates/ingress.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#6284 [release/v2.15] do not require cert-manager CRDs for oauth chart (#6282)
  charts/oauth/Chart.yaml
  charts/oauth/templates/_helpers.tpl
  charts/oauth/templates/certificate.yaml
  charts/oauth/templates/cluster-role-binding.yaml
  charts/oauth/templates/cluster-role.yaml
  charts/oauth/templates/ingress.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#6285 add 2.15.6 changelog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6286 Opa config endpoints
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/swagger.json
  go.mod
  go.sum
  pkg/api/v2/types.go
  pkg/handler/test/helper.go
  pkg/handler/v2/gatekeeperconfig/gatekeeperconfig.go
  pkg/handler/v2/gatekeeperconfig/gatekeeperconfig_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/create_gatekeeper_config_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/create_gatekeeper_config_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/delete_gatekeeper_config_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/delete_gatekeeper_config_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_gatekeeper_config_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_gatekeeper_config_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/api/utils/apiclient/models/g_v_k.go
  pkg/test/e2e/api/utils/apiclient/models/gatekeeper_config.go
  pkg/test/e2e/api/utils/apiclient/models/gatekeeper_config_spec.go
  pkg/test/e2e/api/utils/apiclient/models/match_entry.go
  pkg/test/e2e/api/utils/apiclient/models/readiness_spec.go
  pkg/test/e2e/api/utils/apiclient/models/sync.go
  pkg/test/e2e/api/utils/apiclient/models/trace.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#6289 only enable password-logins in Dex if passwords are configured
  charts/oauth/Chart.yaml
  charts/oauth/templates/configmap.yaml
  charts/oauth/templates/secrets.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#6290 Prometheus 2.23 / Thanos 0.17.2
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/rules/general-thanos.yaml
  charts/monitoring/prometheus/rules/src/general/thanos.yaml
  charts/monitoring/prometheus/values.yaml
  pkg/resources/prometheus/statefulset.go
  pkg/resources/test/fixtures/statefulset-aws-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.19.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.19.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.19.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.19.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.19.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.19.0-prometheus.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#6292 migrate to networking.k8s.io/v1beta1 for Ingresses
  charts/certs/Chart.yaml
  charts/certs/templates/acme-challenge-ingress.yaml
  charts/iap/Chart.yaml
  charts/iap/templates/ingresses.yaml
  charts/kubermatic/Chart.yaml
  charts/kubermatic/templates/ingress.yaml
  charts/oauth/Chart.yaml
  charts/oauth/templates/ingress.yaml
  codegen/reconcile/main.go
  pkg/controller/operator/master/controller.go
  pkg/controller/operator/master/resources/kubermatic/common.go
  pkg/controller/operator/master/resources/kubermatic/common_test.go
  pkg/controller/user-cluster-controller-manager/rbac/mapper.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#6294 [release/v2.15] Update login background in Dex (#6271)
  charts/oauth/Chart.yaml
  charts/oauth/theme/bg.svg
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#6287 v2 to list Packet, Vsphere and Alibaba resources
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/provider/alibaba.go
  pkg/handler/common/provider/packet.go
  pkg/handler/common/provider/vsphere.go
  pkg/handler/v1/provider/alibaba.go
  pkg/handler/v1/provider/packet.go
  pkg/handler/v1/provider/vsphere.go
  pkg/handler/v2/provider/alibaba.go
  pkg/handler/v2/provider/packet.go
  pkg/handler/v2/provider/vsphere.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/alibaba/alibaba_client.go
  pkg/test/e2e/api/utils/apiclient/client/alibaba/list_alibaba_instance_types_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/alibaba/list_alibaba_instance_types_no_credentials_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/alibaba/list_alibaba_zones_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/alibaba/list_alibaba_zones_no_credentials_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/packet/list_packet_sizes_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/packet/list_packet_sizes_no_credentials_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/packet/packet_client.go
  pkg/test/e2e/api/utils/apiclient/client/vsphere/list_v_sphere_folders_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/vsphere/list_v_sphere_folders_no_credentials_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/vsphere/list_v_sphere_networks_no_credentials_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/vsphere/list_v_sphere_networks_no_credentials_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/vsphere/vsphere_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#6296 Fix Thanos UI
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/templates/thanos-ui-deployment.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6299 v2 dashboard proxy
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/kubernetes-dashboard/dashboard.go
  pkg/handler/v2/routes_v2.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#6298 Fix envoymanager flag
  cmd/nodeport-proxy/envoy-manager/main.go
  hack/run-nodeport-proxy-e2e-test-in-kind.sh
  pkg/controller/operator/seed/resources/nodeportproxy/deployments.go
  pkg/test/e2e/nodeport-proxy/deployer.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6300 [release/v2.15] Default to the latest available OpenStack CCM version
  docs/adding-kubernetes-versions.md
  pkg/resources/cloudcontroller/openstack.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#6222 Nodeport-proxy e2e extensions for the new expose strategy.
  pkg/controller/nodeport-proxy/envoymanager/resources.go
  pkg/controller/operator/seed/resources/nodeportproxy/deployments.go
  pkg/test/builder.go
  pkg/test/e2e/nodeport-proxy/deployer.go
  pkg/test/e2e/nodeport-proxy/network.go
  pkg/test/e2e/nodeport-proxy/nodeport_proxy_test.go
  pkg/test/e2e/nodeport-proxy/services.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6254 Extend retry parameters in http framework for e2e tests
  pkg/test/e2e/api/credentials_test.go
  pkg/test/e2e/api/runner.go
  pkg/test/e2e/api/utils/http.go
  pkg/test/e2e/api/utils/http_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6303 fix v2 for Alibaba resources
  pkg/handler/v2/routes_v2.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6274 Add support for tunneling expose strategy in control plane components
  cmd/nodeport-proxy/envoy-manager/main.go
  cmd/nodeport-proxy/lb-updater/main.go
  cmd/nodeport-proxy/lb-updater/main_test.go
  pkg/controller/nodeport-proxy/envoymanager/controller_test.go
  pkg/controller/nodeport-proxy/envoymanager/resources.go
  pkg/controller/nodeport-proxy/envoymanager/utils.go
  pkg/controller/nodeport-proxy/envoymanager/utils_test.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/seed-controller-manager/openshift/openshift_controller.go
  pkg/resources/address/address.go
  pkg/resources/apiserver/service.go
  pkg/resources/apiserver/service_test.go
  pkg/resources/nodeportproxy/nodeportproxy.go
  pkg/resources/openvpn/service.go
  pkg/test/e2e/nodeport-proxy/nodeport_proxy_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6305 add PodNodeSelector admission plugin configuration to the cluster CRD
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#6306 Opa gatekeeper config patch
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/gatekeeperconfig/gatekeeperconfig.go
  pkg/handler/v2/gatekeeperconfig/gatekeeperconfig_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/patch_gatekeeper_config_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/patch_gatekeeper_config_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#6317 fix v2 for dashboard proxy
  pkg/handler/v2/kubernetes-dashboard/dashboard.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6308 add admission control configuration for the user cluster API deployment
  cmd/image-loader/main.go
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/apiserver/admission-control.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/cluster/cluster.go
  pkg/resources/resources.go
  pkg/resources/test/fixtures/configmap-aws-1.17.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-aws-1.18.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-aws-1.19.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-azure-1.17.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-azure-1.18.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-azure-1.19.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.17.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.18.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.19.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.17.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.18.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.19.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.17.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.18.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.19.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.17.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.18.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.19.0-adm-control.yaml
  pkg/resources/test/fixtures/deployment-aws-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-apiserver.yaml
  pkg/resources/test/load_files_test.go
  pkg/test/e2e/api/utils/apiclient/models/cluster_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#6320 fix AdmissionPluginConfiguration for deprecated API version
  pkg/resources/apiserver/admission-control.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6319 OPA rbac for users in user cluster
  pkg/controller/user-cluster-controller-manager/rbac/mapper.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6324 add PodNodeSelectorAdmissionPluginConfig for cluster patch endpoint
  pkg/handler/common/cluster.go
  pkg/handler/v2/cluster/cluster_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6297 Add tests for etcd-launcher
  cmd/conformance-tests/etcdlauncher.go
  cmd/conformance-tests/runner.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6329 Prevent container orphans when using apiserver.IsRunningWrapper
  Makefile
  pkg/controller/seed-controller-manager/openshift/resources/cloud_credential_operator.go
  pkg/controller/seed-controller-manager/openshift/resources/console.go
  pkg/controller/seed-controller-manager/openshift/resources/dns_operator.go
  pkg/controller/seed-controller-manager/openshift/resources/kube_controller_manager.go
  pkg/controller/seed-controller-manager/openshift/resources/kube_scheduler.go
  pkg/controller/seed-controller-manager/openshift/resources/oauth.go
  pkg/controller/seed-controller-manager/openshift/resources/openshift_apiserver_deployment.go
  pkg/controller/seed-controller-manager/openshift/resources/openshift_controller_manager.go
  pkg/controller/seed-controller-manager/openshift/resources/openshift_network_operator.go
  pkg/controller/seed-controller-manager/openshift/resources/registry_operator.go
  pkg/resources/clusterautoscaler/clusterautoscaler.go
  pkg/resources/controllermanager/deployment.go
  pkg/resources/gatekeeper/deployment.go
  pkg/resources/kubernetes-dashboard/deployment.go
  pkg/resources/kubestatemetrics/deployment.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/machinecontroller/webhook.go
  pkg/resources/metrics-server/deployment.go
  pkg/resources/scheduler/deployment.go
  pkg/resources/usercluster/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#6326 Prevent SA for cluster creation
  pkg/handler/v1/project/project.go
  pkg/handler/v1/project/project_test.go
  pkg/test/e2e/api/sa_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
