Repository kubermatic/kubermatic, pull requests merged in 2020-08, with the labels that each got.

#5725 Add tolerations to usersshkeys daemonset
  pkg/controller/user-cluster-controller-manager/resources/resources/usersshkeys/daemonset.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/S, team/lifecycle

#5705 add KubermaticAddonTakesTooLongToReconcile alert
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/rules/kubermatic-seed-kubermatic.yaml
  charts/monitoring/prometheus/rules/src/kubermatic-seed/kubermatic.yaml
  pkg/collectors/addon.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/M

#5726 fix typo in prometheus chart
  config/monitoring/prometheus/Chart.yaml
  config/monitoring/prometheus/templates/thanos-secret.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#5729 docs: document current Kubernetes version policy
  docs/release-process.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5730 implement Seed.Spec.NodeportProxy.Annotation syncing to created servi…
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/operator/seed/reconciler_test.go
  pkg/controller/operator/seed/resources/nodeportproxy/service.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#5731 Use Athens instead of homegrown go cache
  .gitignore
  .prow.yaml
  Makefile
  go.mod
  go.sum
  hack/ci/ci-download-gocache.sh
  hack/ci/ci-setup-kubermatic-in-kind.sh
  hack/ci/ci-upload-gocache.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5737 Fix prometheus alertmanager queries for KubeClientCertificateExpiration
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/rules/general-kube-apiserver.yaml
  charts/monitoring/prometheus/rules/src/general/kube-apiserver.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/S

#5732 Move etcd cluster's initialState to etcd-launcher
  cmd/etcd-launcher/main.go
  pkg/controller/master-controller-manager/rbac/mapper.go
  pkg/controller/master-controller-manager/rbac/sync_resource.go
  pkg/controller/master-controller-manager/rbac/sync_resource_test.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/etcd/serviceaccount.go
  pkg/resources/etcd/statefulset.go
  pkg/resources/test/fixtures/statefulset-aws-1.15.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.18.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.15.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.18.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.15.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.18.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.15.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.18.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.15.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.18.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.15.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.18.0-etcd.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle, team/ui

#5720 create external cluster endpoint
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/options.go
  cmd/kubermatic-api/swagger.json
  pkg/handler/routing.go
  pkg/handler/test/fake_provider.go
  pkg/handler/test/hack/hack.go
  pkg/handler/test/helper.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/routing.go
  pkg/provider/kubernetes/external_cluster.go
  pkg/provider/kubernetes/external_cluster_test.go
  pkg/provider/types.go
  pkg/resources/resources.go
  pkg/test/e2e/api/utils/apiclient/client/project/create_external_cluster_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/create_external_cluster_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL, team/ui

#5751 fix listing projects after project deletion
  pkg/handler/v1/project/project.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/ui

#5744 fix duplicated LoadBalancer IDs in annotations during cluster deletion
  pkg/clusterdeletion/lb.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#5753 new endpoint to delete external cluster
  cmd/kubermatic-api/swagger.json
  pkg/handler/test/fake_provider.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/external_cluster.go
  pkg/provider/types.go
  pkg/test/e2e/api/utils/apiclient/client/project/delete_external_cluster_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/delete_external_cluster_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5754 fix ExternalClusterList object
  pkg/crd/kubermatic/v1/external_cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#5755 fix owning project not being set on credential secrets
  pkg/handler/common/cluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle, team/ui

#5740 fix iap example value for grafana: suppress iap auth header
  charts/iap/Chart.yaml
  charts/iap/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5764 Added v2.14.4 to the CHANGELOG.md
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5765 Added PR links in v2.14.4 in CHANGELOG.md
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5750 do not log an rbac-related error when a project is deleted
  pkg/controller/master-controller-manager/rbac/sync_project.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/ui

#5532 convert the resource RBAC controller to controller-runtime
  pkg/controller/master-controller-manager/rbac/cluster_provider.go
  pkg/controller/master-controller-manager/rbac/rbac_controller_aggregator.go
  pkg/controller/master-controller-manager/rbac/rbac_project_controller.go
  pkg/controller/master-controller-manager/rbac/rbac_resource_controller.go
  pkg/controller/master-controller-manager/rbac/sync_project.go
  pkg/controller/master-controller-manager/rbac/sync_project_test.go
  pkg/controller/master-controller-manager/rbac/sync_resource.go
  pkg/controller/master-controller-manager/rbac/sync_resource_test.go
  pkg/controller/util/predicate/predicate.go
  pkg/test/e2e/api/cluster_rbac_test.go
  pkg/test/e2e/api/user_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL, team/lifecycle, team/ui

#5766 bring back the gocache
  Makefile
  hack/ci/ci-download-gocache.sh
  hack/ci/ci-setup-kubermatic-in-kind.sh
  hack/ci/ci-upload-gocache.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5741 Add support for codegen when the repository is out of GOPATH
  Makefile
  README.md
  hack/ci/ci-github-release.sh
  hack/lib.sh
  hack/update-codegen.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5757 list endpoint for external cluster
  cmd/kubermatic-api/swagger.json
  pkg/handler/test/fake_provider.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/external_cluster.go
  pkg/provider/types.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_external_clusters_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_external_clusters_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5761 etcd launcher: identify unwanted members even if the cluster size is right
  cmd/etcd-launcher/main.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/S, team/lifecycle

#5770 fix uploading gocache
  Makefile
  hack/ci/ci-upload-gocache.sh
  hack/lib.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5774 Add lsviben to owners file
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5772 get external cluster endpoint
  cmd/kubermatic-api/swagger.json
  pkg/handler/test/fake_provider.go
  pkg/handler/test/helper.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/external_cluster.go
  pkg/provider/types.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_external_cluster_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_external_cluster_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5746 Initial etcd volume recovery support
  cmd/seed-controller-manager/controllers.go
  pkg/controller/seed-controller-manager/pvwatcher/doc.go
  pkg/controller/seed-controller-manager/pvwatcher/pvwatcher_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#5782 update owners file
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5775 Update Velero to 1.4.2
  charts/backup/velero/Chart.yaml
  charts/backup/velero/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#5779 Update Loki to 1.6.1
  charts/logging/loki/Chart.yaml
  charts/logging/loki/values.yaml
  charts/logging/promtail/Chart.yaml
  charts/logging/promtail/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#5780 Update nginx-ingress-controller to 0.34.1
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#5777 Migrate from Keycloak-Gatekeeper to OAuth2-Proxy
  charts/iap/Chart.yaml
  charts/iap/templates/configmaps.yaml
  charts/iap/templates/deployments.yaml
  charts/iap/templates/ingresses.yaml
  charts/iap/templates/secrets.yaml
  charts/iap/values.yaml
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/config/grafana.ini
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5783 update external cluster endpoint
  cmd/kubermatic-api/swagger.json
  download-gocache
  pkg/handler/test/fake_provider.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/external_cluster.go
  pkg/provider/kubernetes/external_cluster_test.go
  pkg/provider/types.go
  pkg/test/e2e/api/utils/apiclient/client/project/create_external_cluster_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/create_external_cluster_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/api/utils/apiclient/client/project/update_external_cluster_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/update_external_cluster_responses.go
  pkg/test/e2e/api/utils/apiclient/models/body.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5776 Update cert-manager to 0.16.1
  charts/cert-manager/Chart.yaml
  charts/cert-manager/crd/cert-manager.crds.yaml
  charts/cert-manager/values.yaml
  hack/update-cert-manager-crds.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#5781 Update Prometheus to 2.20.1
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/values.yaml
  pkg/resources/prometheus/statefulset.go
  pkg/resources/test/fixtures/statefulset-aws-1.15.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.16.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.15.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.16.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.15.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.16.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.15.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.16.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.15.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.16.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.15.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.16.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.18.0-prometheus.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-action-required, size/M

#5785 Fix retag-images script for 'exotic' Docker registries
  hack/retag-images.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5787 Update Blackbox Exporter to 0.17.0
  charts/monitoring/blackbox-exporter/Chart.yaml
  charts/monitoring/blackbox-exporter/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#5788 Update Grafana to 7.1.5
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#5786 Update Alertmanager to 0.21.0
  charts/monitoring/alertmanager/Chart.yaml
  charts/monitoring/alertmanager/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#5789 Update Karma to v0.68
  charts/monitoring/karma/Chart.yaml
  charts/monitoring/karma/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#5790 update kube-state-metrics to 1.9.7
  charts/monitoring/kube-state-metrics/Chart.yaml
  charts/monitoring/kube-state-metrics/values.yaml
  pkg/resources/kubestatemetrics/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.15.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.16.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.17.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.15.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.16.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.15.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.16.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.15.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.16.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.15.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.16.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.15.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.16.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-kube-state-metrics.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#5791 Update node-exporter to 1.0.1
  addons/node-exporter/daemonset.yaml
  charts/monitoring/node-exporter/Chart.yaml
  charts/monitoring/node-exporter/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#5793 gitignore download-gocache
  .gitignore
  download-gocache
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5685 Add current WIP for the installer
  cmd/kubermatic-installer/cmd_deploy.go
  cmd/kubermatic-installer/cmd_version.go
  cmd/kubermatic-installer/main.go
  cmd/kubermatic-installer/shared.go
  docs/proposals/kubermatic-installer.md
  go.mod
  go.sum
  pkg/crd/util/crd.go
  pkg/install/helm/cli.go
  pkg/install/helm/interface.go
  pkg/install/helm/status.go
  pkg/install/helm/types.go
  pkg/install/stack/kubermatic/stack.go
  pkg/install/stack/kubermatic/storageclass.go
  pkg/install/stack/kubermatic/validation.go
  pkg/install/util/crd.go
  pkg/install/util/helm.go
  pkg/install/util/kubernetes.go
  pkg/log/logrus.go
  pkg/util/yamled/document.go
  pkg/util/yamled/document_test.go
  pkg/util/yamled/path.go
  pkg/util/yamled/path_test.go
  pkg/util/yamled/testcases/append-existing-array.yaml
  pkg/util/yamled/testcases/append-new-array.yaml
  pkg/util/yamled/testcases/document.yaml
  pkg/util/yamled/testcases/fill-complex.yaml
  pkg/util/yamled/testcases/fill-existing-root-key.yaml
  pkg/util/yamled/testcases/fill-into-array.yaml
  pkg/util/yamled/testcases/fill-new-root-key.yaml
  pkg/util/yamled/testcases/fill-two-new-root-keys.yaml
  pkg/util/yamled/testcases/remove-existing-array-item.yaml
  pkg/util/yamled/testcases/remove-existing-root-key.yaml
  pkg/util/yamled/testcases/remove-existing-sub-key.yaml
  pkg/util/yamled/testcases/remove-nonexisting-array-item.yaml
  pkg/util/yamled/testcases/remove-nonexisting-root-key.yaml
  pkg/util/yamled/testcases/set-existing-array-item.yaml
  pkg/util/yamled/testcases/set-existing-root-key.yaml
  pkg/util/yamled/testcases/set-new-array-item.yaml
  pkg/util/yamled/testcases/set-new-far-array-item.yaml
  pkg/util/yamled/testcases/set-new-root-key.yaml
  pkg/util/yamled/testcases/set-new-sub-key.yaml
  pkg/util/yamled/testcases/set-new-sub-sub-key.yaml
  pkg/util/yamled/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL, team/lifecycle

#5778 Fallback to in-tree cloud provider for OTC
  pkg/handler/common/cluster.go
  pkg/resources/cloudcontroller/openstack.go
  pkg/resources/cloudcontroller/openstack_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/ui

#5796 get nodes for external cluster
  cmd/kubermatic-api/swagger.json
  pkg/handler/test/fake_provider.go
  pkg/handler/test/helper.go
  pkg/handler/v2/external_cluster/node.go
  pkg/handler/v2/external_cluster/node_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/external_cluster.go
  pkg/provider/types.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_external_cluster_nodes_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_external_cluster_nodes_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5797 [release/v2.14] Fallback to in-tree cloud provider for OTC (#5778)
  api/pkg/handler/v1/cluster/cluster.go
  api/pkg/resources/cloudcontroller/openstack.go
  api/pkg/resources/cloudcontroller/openstack_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/ui

#5798 get external cluster node endpoint
  cmd/kubermatic-api/swagger.json
  pkg/handler/test/fake_provider.go
  pkg/handler/test/helper.go
  pkg/handler/v2/external_cluster/node.go
  pkg/handler/v2/external_cluster/node_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/external_cluster.go
  pkg/provider/types.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_external_cluster_node_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_external_cluster_node_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui
