Repository kubermatic/kubermatic, pull requests merged in 2020-07, with the labels that each got.

#5559 e2e logout method
  hack/ci/ci_run_api_e2e.sh
  pkg/test/e2e/api/logout_test.go
  pkg/test/e2e/api/runner.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5584 make wwhrd less verbose
  hack/verify-licenses.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5566 [release/v2.14] [EE] switch Docker repository logic for Kubermatic (#5470)
  api/Makefile
  api/hack/ci/ci-run-offline-test.sh
  api/hack/ci/ci-setup-kubermatic-in-kind.sh
  api/hack/push_image.sh
  api/pkg/resources/resources_ce.go
  api/pkg/resources/resources_ee.go
  api/pkg/resources/test/fixtures/deployment-aws-1.15.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.16.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.17.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.18.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.15.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.16.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.17.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.18.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.15.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.16.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.15.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.16.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.15.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.16.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.17.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.18.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.15.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.16.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.17.0-usercluster-controller.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.18.0-usercluster-controller.yaml
  api/pkg/resources/test/load_files_test.go
  config/kubermatic-operator/Chart.yaml
  config/kubermatic-operator/values.yaml
  config/kubermatic/Chart.yaml
  config/kubermatic/values.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5579 Add option to limit project creation
  cmd/kubermatic-api/swagger.json
  pkg/crd/kubermatic/v1/settings.go
  pkg/handler/v1/admin/settings_test.go
  pkg/provider/kubernetes/settings.go
  pkg/test/e2e/api/settings_test.go
  pkg/test/e2e/api/utils/apiclient/models/setting_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S, team/lifecycle, team/ui

#5586 Shrink down Docker image size
  Dockerfile
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#5569 [release/v2.13] fix editing cluster credential secret
  api/pkg/handler/routes_v1.go
  api/pkg/handler/v1/cluster/cluster.go
  api/pkg/provider/kubernetes/credentials.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/ui

#5590 limit number of project creation
  pkg/handler/routes_v1.go
  pkg/handler/test/helper.go
  pkg/handler/v1/admin/settings_test.go
  pkg/handler/v1/project/project.go
  pkg/handler/v1/project/project_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/ui

#5591 bump machine-controller to v1.15.0
  Gopkg.lock
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.15.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.15.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.15.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.15.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.15.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.15.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.15.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.15.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.15.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.15.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.15.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.15.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller.yaml
  vendor/github.com/kubermatic/machine-controller/pkg/userdata/centos/provider.go
  vendor/github.com/kubermatic/machine-controller/pkg/userdata/coreos/provider.go
  vendor/github.com/kubermatic/machine-controller/pkg/userdata/flatcar/provider.go
  vendor/github.com/kubermatic/machine-controller/pkg/userdata/helper/helper.go
  vendor/github.com/kubermatic/machine-controller/pkg/userdata/helper/kubelet.go
  vendor/github.com/kubermatic/machine-controller/pkg/userdata/rhel/provider.go
  vendor/github.com/kubermatic/machine-controller/pkg/userdata/sles/provider.go
  vendor/github.com/kubermatic/machine-controller/pkg/userdata/ubuntu/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5593 add option to restrict project creation
  cmd/kubermatic-api/swagger.json
  pkg/crd/kubermatic/v1/settings.go
  pkg/handler/v1/admin/settings_test.go
  pkg/provider/kubernetes/settings.go
  pkg/test/e2e/api/settings_test.go
  pkg/test/e2e/api/utils/apiclient/models/setting_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle, team/ui

#5606 updated changelog for v2.14.1
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5608 updated changelog for v2.13.6
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5609 Fix label for nodeport-proxy when deployed with the operator
  pkg/controller/operator/seed/resources/nodeportproxy/service.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#5602 add e2e tests for user projects limit
  pkg/test/e2e/api/runner.go
  pkg/test/e2e/api/settings_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5605 fix s3 secrect location
  charts/minio/Chart.yaml
  charts/minio/templates/secret-kube-system.yaml
  charts/minio/values.yaml
  charts/s3-exporter/Chart.yaml
  charts/s3-exporter/templates/clusterrole.yaml
  charts/s3-exporter/templates/clusterrolebinding.yaml
  charts/s3-exporter/templates/deployment.yaml
  charts/s3-exporter/templates/serviceaccount.yaml
  charts/s3-exporter/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5612 backport nodeport-proxy fix to v2.14
  api/pkg/controller/operator/seed/resources/nodeportproxy/service.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#5611 Fix seed validation
  cmd/master-controller-manager/wrappers_ce.go
  cmd/seed-controller-manager/main.go
  pkg/ee/cmd/master-controller-manager/wrappers.go
  pkg/provider/datacenter.go
  pkg/provider/datacenter_test.go
  pkg/validation/seed/seed.go
  pkg/validation/seed/seed_test.go
  pkg/validation/seed/server.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle, team/ui

#5619 Backport fix seed validation to 2.14
  api/cmd/master-controller-manager/wrappers_ce.go
  api/cmd/seed-controller-manager/main.go
  api/pkg/ee/cmd/master-controller-manager/wrappers.go
  api/pkg/provider/datacenter.go
  api/pkg/provider/datacenter_test.go
  api/pkg/validation/seed/seed.go
  api/pkg/validation/seed/seed_test.go
  api/pkg/validation/seed/server.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle, team/ui

#5620 Backport fix seed validation flackiness to 2.14
  api/pkg/controller/operator/common/defaults.go
  docs/zz_generated.kubermaticConfiguration.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS, team/lifecycle

#5610 Remove empty Docker secret for Kubermatic Operator CE Helm chart
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/templates/dockercfg.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5616 Fix seed validation flackiness
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#5618 Apply the Kubermatic Operator Helm change to 2.14
  config/kubermatic-operator/Chart.yaml
  config/kubermatic-operator/templates/dockercfg.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5562 Seed dc cleanup
  api/pkg/test/e2e/api/utils/apiclient/models/datacenter_meta.go
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/v1/admin/seed.go
  pkg/handler/v1/dc/datacenter.go
  pkg/handler/v1/dc/datacenter_test.go
  pkg/test/e2e/api/dc_test.go
  pkg/test/e2e/api/utils/apiclient/models/datacenter.go
  pkg/test/e2e/api/utils/apiclient/models/datacenter_meta.go
  pkg/test/e2e/api/utils/apiclient/models/legacy_object_meta.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/ui

#5613 restrict project creation
  pkg/handler/v1/project/project.go
  pkg/handler/v1/project/project_test.go
  pkg/test/e2e/api/settings_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/ui

#5624 Backport fix seed validation to v2.14
  api/pkg/provider/datacenter.go
  api/pkg/provider/datacenter_test.go
  api/pkg/validation/seed/seed.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5623 Fix seed validation
  pkg/provider/datacenter.go
  pkg/provider/datacenter_test.go
  pkg/validation/seed/seed.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5604 added user watch endpoint
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/options.go
  pkg/handler/routes_v1_websocket.go
  pkg/handler/routing.go
  pkg/handler/test/hack/hack.go
  pkg/handler/test/helper.go
  pkg/handler/v1/project/project_test.go
  pkg/handler/websocket/user.go
  pkg/handler/websocket/user_test.go
  pkg/provider/kubernetes/user.go
  pkg/provider/kubernetes/user_test.go
  pkg/provider/types.go
  pkg/watcher/kubernetes/user.go
  pkg/watcher/kubernetes/user_test.go
  pkg/watcher/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5580 add script to create GitHub releases
  hack/ci/ci-github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5628 Revert "fix s3 secrect location (#5605)"
  charts/minio/Chart.yaml
  charts/minio/templates/secret-kube-system.yaml
  charts/minio/values.yaml
  charts/s3-exporter/Chart.yaml
  charts/s3-exporter/templates/clusterrole.yaml
  charts/s3-exporter/templates/clusterrolebinding.yaml
  charts/s3-exporter/templates/deployment.yaml
  charts/s3-exporter/templates/serviceaccount.yaml
  charts/s3-exporter/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5629 Remove file committed by mistake in api directory
  api/pkg/test/e2e/api/utils/apiclient/models/datacenter_meta.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5627 Fix Subnetworks for GCP
  pkg/handler/v1/provider/gcp.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/ui

#5632 [release/2.14] Fix Subnetworks for GCP
  api/pkg/handler/v1/provider/gcp.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/ui

#5639 Backport github release tarball script to 2.14
  api/hack/ci/ci-github-release.sh
  config/test/kubermatic.example.ce.yaml
  config/test/kubermatic.example.ee.yaml
  config/test/seed.example.yaml
  config/values.example.ce.yaml
  config/values.example.ee.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5638 Fix user watch websocket to produce api user instead of internal kubermatic
  pkg/api/v1/types.go
  pkg/handler/routes_v1_websocket.go
  pkg/handler/v1/user/user.go
  pkg/handler/websocket/user.go
  pkg/handler/websocket/user_test.go
  pkg/watcher/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/ui

#5642 skipping flaky user watch test until solution is found
  pkg/handler/websocket/user_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/ui

#5645 Added changelog for new release v2.14.2
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5643 fix displaying AZ for OpenStack
  pkg/machine/convert.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5630 Improve release tarball script
  charts/test/kubermatic.example.ce.yaml
  charts/test/kubermatic.example.ee.yaml
  charts/test/seed.example.yaml
  charts/values.example.ce.yaml
  charts/values.example.ee.yaml
  hack/ci/ci-github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5560 Add expose strategy proposal based on HTTP tunneling and SNI
  docs/proposals/http-tunnel-expose-strategy.md
  docs/proposals/images/http-tunnel-expose-strategy-full-tunneling.png
  docs/proposals/images/http-tunnel-expose-strategy-sni.png
  docs/proposals/images/http-tunnel-expose-strategy-tunneling.png
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5650 add Kubernetes v1.15.12 to default versions
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/versions.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS, team/lifecycle

#5657 fix DisableAutoUpdate for coreos
  pkg/resources/machine/common.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5647 [release/2.14] Add path to gcp subnetworks
  api/cmd/kubermatic-api/swagger.json
  api/pkg/api/v1/types.go
  api/pkg/handler/v1/provider/gcp.go
  api/pkg/test/e2e/api/utils/apiclient/models/g_c_p_subnetwork.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/ui

#5652 v2 endpoints to get/list cluster for the project
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/common/cluster.go
  pkg/handler/middleware/middleware.go
  pkg/handler/test/helper.go
  pkg/handler/v1/addon/addon.go
  pkg/handler/v1/cluster/binding.go
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v1/cluster/kubeconfig.go
  pkg/handler/v1/cluster/upgrade.go
  pkg/handler/v1/common/request.go
  pkg/handler/v1/node/legacy.go
  pkg/handler/v1/node/node.go
  pkg/handler/v1/provider/alibaba.go
  pkg/handler/v1/provider/aws.go
  pkg/handler/v1/provider/azure.go
  pkg/handler/v1/provider/digitalocean.go
  pkg/handler/v1/provider/gcp.go
  pkg/handler/v1/provider/hetzner.go
  pkg/handler/v1/provider/openstack.go
  pkg/handler/v1/provider/packet.go
  pkg/handler/v1/provider/vsphere.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_cluster_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_cluster_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_clusters_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_clusters_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL, team/ui

#5649 Put back nodeport proxy
  hack/ci/ci-github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5646 Add path to gcp subnetworks
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/v1/provider/gcp.go
  pkg/test/e2e/api/utils/apiclient/models/g_c_p_subnetwork.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/ui

#5656 add Kubernetes v1.16.13 to default versions and remove earlier versions of 1.16
  .prow.yaml
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/updates.yaml
  charts/kubermatic/static/master/versions.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#5659 [release/v2.14] add Kubernetes v1.16.13 to default versions and remove earlier versions of 1.16
  .prow.yaml
  api/pkg/controller/operator/common/defaults.go
  config/kubermatic/Chart.yaml
  config/kubermatic/static/master/updates.yaml
  config/kubermatic/static/master/versions.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#5662 [release/v2.12] add Kubernetes v1.16.13 to default versions and remove earlier versions of 1.16
  .prow.yaml
  config/kubermatic/Chart.yaml
  config/kubermatic/static/master/updates.yaml
  config/kubermatic/static/master/versions.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#5661 [release/v2.13] add Kubernetes v1.16.13 to default versions and remove earlier versions of 1.16
  .prow.yaml
  api/pkg/controller/operator/common/defaults.go
  config/kubermatic/Chart.yaml
  config/kubermatic/static/master/updates.yaml
  config/kubermatic/static/master/versions.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#5667 [release/v2.13] add Kubernetes v1.17.9 to default versions and remove earlier versions of 1.17
  .prow.yaml
  api/pkg/controller/operator/common/defaults.go
  config/kubermatic/Chart.yaml
  config/kubermatic/static/master/updates.yaml
  config/kubermatic/static/master/versions.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#5658 add Kubernetes v1.17.9 to default versions and remove earlier versions of 1.17
  .prow.yaml
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/updates.yaml
  charts/kubermatic/static/master/versions.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#5664 [release/v2.14] add Kubernetes v1.17.9 to default versions and remove earlier versions of 1.17
  .prow.yaml
  api/pkg/controller/operator/common/defaults.go
  config/kubermatic/Chart.yaml
  config/kubermatic/static/master/updates.yaml
  config/kubermatic/static/master/versions.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#5669 Add Kubernetes v1.18.6 to default versions and remove earlier versions of 1.18
  .prow.yaml
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/updates.yaml
  charts/kubermatic/static/master/versions.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#5666 v2 endpoint, delete cluster
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/cluster.go
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/delete_cluster_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/delete_cluster_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5670 fix GetUpgradesEndpoint to return list instead object
  pkg/handler/v1/cluster/upgrade.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/ui

#5673 [release/v2.14] add Kubernetes v1.18.6 to default versions and remove earlier versions of 1.18
  .prow.yaml
  api/pkg/controller/operator/common/defaults.go
  config/kubermatic/Chart.yaml
  config/kubermatic/static/master/updates.yaml
  config/kubermatic/static/master/versions.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#5671 unsubscribe the pubsub on user watch websocket close
  pkg/handler/websocket/settings.go
  pkg/handler/websocket/user.go
  pkg/handler/websocket/user_test.go
  pkg/watcher/kubernetes/settings.go
  pkg/watcher/kubernetes/user.go
  pkg/watcher/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/ui

#5626 Fix incorrect error handling in collectAddon function
  pkg/collectors/addon.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#5678 add GNU tar to util image, bump dependencies
  .prow.yaml
  charts/kubermatic/Chart.yaml
  charts/kubermatic/values.yaml
  charts/logging/kibana/Chart.yaml
  charts/logging/kibana/values.yaml
  charts/minio/Chart.yaml
  charts/minio/values.yaml
  charts/monitoring/alertmanager/Chart.yaml
  charts/monitoring/alertmanager/values.yaml
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/values.yaml
  charts/monitoring/karma/Chart.yaml
  charts/monitoring/karma/values.yaml
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/values.yaml
  containers/util/Dockerfile
  containers/util/release.sh
  hack/ci/ci-github-release.sh
  pkg/controller/master-controller-manager/seed-proxy/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#5675 Update conformance test with latest k8s versions
  cmd/conformance-tests/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#5677 new endpoint v2 to patch cluster
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/cluster.go
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/patch_cluster_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/patch_cluster_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5682 changelog for v2.12.9, v2.13.7, v2.14.3
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4835 docs/release-process.md: merge Kamil's checklist
  docs/release-process.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5681 Fix for panic when user/settings watch connection closes
  pkg/handler/websocket/common.go
  pkg/handler/websocket/settings.go
  pkg/handler/websocket/user.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/ui

#5596 Define basic create-only e2e tests for the CE
  .prow.yaml
  hack/ci/ci-setup-kubermatic-in-kind.sh
  pkg/test/e2e/api/admin_test.go
  pkg/test/e2e/api/cluster_rbac_test.go
  pkg/test/e2e/api/dc_test.go
  pkg/test/e2e/api/digitalocean_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5676 Improved stability of dc e2e tests
  pkg/test/e2e/api/cluster_rbac_test.go
  pkg/test/e2e/api/dc_test.go
  pkg/test/e2e/api/runner.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5692 fix flaky TestGCPDiskTypes
  pkg/test/e2e/api/gcp_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5686 Use dedicated etcd-launcher image
  cmd/etcd-launcher/Dockerfile
  hack/ci/ci-setup-kubermatic-in-kind.sh
  hack/lib.sh
  hack/push_image.sh
  pkg/resources/etcd/statefulset.go
  pkg/resources/test/fixtures/statefulset-aws-1.15.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.18.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.15.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.18.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.15.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.18.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.15.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.18.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.15.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.18.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.15.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.18.0-etcd.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL, team/lifecycle

#5697 Update Logging Stack
  charts/logging/loki/Chart.yaml
  charts/logging/loki/values.yaml
  charts/logging/promtail/Chart.yaml
  charts/logging/promtail/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#5698 addons/csi: add nodeplugin for flatcar linux
  addons/csi/nodeplugin.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5690 fix GCP cloud spec validation
  pkg/handler/v2/cluster/cluster.go
  pkg/provider/cloud/gcp/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle, team/ui

#5702 fix componentsOverride affecting default values when reconciling clusters
  pkg/resources/resources.go
  pkg/resources/resources_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#5707 fix promtail config
  charts/logging/promtail/Chart.yaml
  charts/logging/promtail/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5696 Update Prometheus to 2.19.2
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/values.yaml
  pkg/resources/prometheus/statefulset.go
  pkg/resources/test/fixtures/statefulset-aws-1.15.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.16.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.15.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.16.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.15.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.16.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.15.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.16.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.15.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.16.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.15.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.16.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.18.0-prometheus.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#5708 allow admin to get any datacenter from the seed
  pkg/provider/conversions.go
  pkg/provider/conversions_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5689 add external cluster CRD and controller to cleanup finalizers
  charts/kubermatic/Chart.yaml
  charts/kubermatic/crd/crd-external-clusters.yaml
  cmd/master-controller-manager/controllers.go
  pkg/api/v1/types.go
  pkg/controller/master-controller-manager/external-cluster/OWNERS
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/controller/master-controller-manager/external-cluster/cluster_controller_test.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/externalcluster.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/fake/fake_externalcluster.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/fake/fake_kubermatic_client.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/generated_expansion.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/kubermatic_client.go
  pkg/crd/client/informers/externalversions/generic.go
  pkg/crd/client/informers/externalversions/kubermatic/v1/externalcluster.go
  pkg/crd/client/informers/externalversions/kubermatic/v1/interface.go
  pkg/crd/client/listers/kubermatic/v1/expansion_generated.go
  pkg/crd/client/listers/kubermatic/v1/externalcluster.go
  pkg/crd/kubermatic/v1/external_cluster.go
  pkg/crd/kubermatic/v1/register.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/lifecycle, team/ui

#5710 make etcd launcher image name overridable
  charts/kubermatic/Chart.yaml
  charts/kubermatic/templates/kubermatic-controller-manager-dep.yaml
  charts/kubermatic/values.yaml
  cmd/image-loader/main.go
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/options.go
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/seed-controller-manager/monitoring/resources.go
  pkg/controller/seed-controller-manager/openshift/data.go
  pkg/controller/seed-controller-manager/openshift/openshift_controller.go
  pkg/controller/seed-controller-manager/openshift/resources.go
  pkg/resources/data.go
  pkg/resources/etcd/statefulset.go
  pkg/resources/resources_ce.go
  pkg/resources/resources_ee.go
  pkg/resources/test/load_files_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/M, team/lifecycle

#5715 register external cluster to RBAC controller
  pkg/controller/master-controller-manager/rbac/rbac_controller_aggregator.go
  pkg/controller/master-controller-manager/rbac/sync_project_test.go
  pkg/controller/master-controller-manager/rbac/sync_resource_test.go
  pkg/crd/kubermatic/v1/external_cluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle, team/ui

#5718 Allow to configure Velero plugin InitContainers
  charts/backup/velero/Chart.yaml
  charts/backup/velero/templates/deployment.yaml
  charts/backup/velero/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#5719 [release/v2.14] Allow to configure Velero plugin InitContainers (#5718)
  config/backup/velero/Chart.yaml
  config/backup/velero/templates/deployment.yaml
  config/backup/velero/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#5716 Improve image push script for local usage
  Makefile
  cmd/user-ssh-keys-agent/Dockerfile
  cmd/user-ssh-keys-agent/Makefile
  hack/push_image.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#5683 Refactor seed and master controller manager start-up logic
  Gopkg.lock
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/options.go
  cmd/kubermatic-api/wrappers_ee.go
  cmd/kubermatic-operator/main.go
  cmd/master-controller-manager/main.go
  cmd/master-controller-manager/wrappers_ce.go
  cmd/master-controller-manager/wrappers_ee.go
  cmd/seed-controller-manager/main.go
  cmd/seed-controller-manager/options.go
  hack/run-master-controller-manager.sh
  hack/run-seed-controller-manager.sh
  pkg/controller/master-controller-manager/rbac/sync_resource.go
  pkg/crd/migrations/seed/migrations.go
  pkg/crd/migrations/seed/migrations_test.go
  pkg/ee/cmd/kubermatic-api/wrappers.go
  pkg/ee/cmd/master-controller-manager/wrappers.go
  pkg/ee/crd/migrations/master/migrations.go
  pkg/ee/crd/migrations/master/migrations_test.go
  pkg/ee/provider/datacenter.go
  pkg/validation/seed/server.go
  vendor/go.uber.org/zap/internal/ztest/doc.go
  vendor/go.uber.org/zap/internal/ztest/timeout.go
  vendor/go.uber.org/zap/internal/ztest/writer.go
  vendor/go.uber.org/zap/zaptest/doc.go
  vendor/go.uber.org/zap/zaptest/logger.go
  vendor/go.uber.org/zap/zaptest/testingt.go
  vendor/go.uber.org/zap/zaptest/timeout.go
  vendor/go.uber.org/zap/zaptest/writer.go
  vendor/sigs.k8s.io/controller-runtime/alias.go
  vendor/sigs.k8s.io/controller-runtime/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/conversion/conversion.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/conversion.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/decoder.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL, team/lifecycle, team/ui

#5399 Add datastore and datastore cluster configs on cluster level
  .prow.yaml
  cmd/conformance-tests/main.go
  cmd/conformance-tests/scenarios_vsphere.go
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.seed.yaml
  pkg/api/v1/types_test.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/crd/kubermatic/v1/preset.go
  pkg/handler/v1/provider/vsphere_test.go
  pkg/provider/cloud/vsphere/provider.go
  pkg/provider/kubernetes/preset.go
  pkg/resources/cloudconfig/configmap.go
  pkg/resources/machine/common.go
  pkg/resources/machine/common_test.go
  pkg/resources/test/load_files_test.go
  pkg/test/e2e/api/utils/apiclient/models/datacenter_spec_v_sphere.go
  pkg/test/e2e/api/utils/apiclient/models/v_sphere_cloud_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle, team/ui
