Repository kubermatic/kubermatic, pull requests merged in 2020-06, with the labels that each got.

#5522 validate cluster version
  api/pkg/handler/routes_v1.go
  api/pkg/handler/test/helper.go
  api/pkg/handler/v1/cluster/cluster.go
  api/pkg/handler/v1/cluster/cluster_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/ui

#5530 Remove Openstack MultiAZ feature flag
  api/pkg/crd/kubermatic/v1/cluster.go
  api/pkg/resources/machine/common.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#5531 add token blacklist for the user
  api/pkg/crd/kubermatic/v1/user.go
  api/pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#5534 Fix license validation job
  .prow.yaml
  api/Makefile
  api/hack/verify-licenses.sh
  containers/wwhrd/Dockerfile
  containers/wwhrd/release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5529 publish kubermatic-operator chart in installer repo
  api/hack/ci/ci-sync-charts.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5539 Fix Google icon size in Dex
  config/oauth/Chart.yaml
  config/oauth/theme/styles.css
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5536 Add etcd-launcher
  api/cmd/etcd-launcher/Dockerfile
  api/cmd/etcd-launcher/main.go
  api/hack/lib.sh
  api/hack/push_image.sh
  api/pkg/controller/seed-controller-manager/openshift/data.go
  api/pkg/controller/seed-controller-manager/openshift/resources/interfaces.go
  api/pkg/resources/data.go
  api/pkg/resources/etcd/statefulset.go
  api/pkg/resources/etcd/statefulset_test.go
  api/pkg/resources/test/fixtures/statefulset-aws-1.15.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-aws-1.16.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-aws-1.17.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-aws-1.18.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-azure-1.15.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-azure-1.16.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-azure-1.17.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-azure-1.18.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-bringyourown-1.15.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-bringyourown-1.16.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-bringyourown-1.17.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-bringyourown-1.18.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-digitalocean-1.15.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-digitalocean-1.16.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-digitalocean-1.17.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-digitalocean-1.18.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-openstack-1.15.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-openstack-1.16.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-openstack-1.17.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-openstack-1.18.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-vsphere-1.15.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-vsphere-1.16.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-vsphere-1.17.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-vsphere-1.18.0-etcd.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL, team/lifecycle

#5548 fix typo in prometheus chart
  config/monitoring/prometheus/Chart.yaml
  config/monitoring/prometheus/templates/thanos-secret.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5513 Remove outdated and misleading config/README
  config/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5547 build scripts target repo configurable
  api/cmd/kubeletdnat-controller/Makefile
  api/cmd/nodeport-proxy/Makefile
  api/cmd/user-ssh-keys-agent/Makefile
  api/hack/push_image.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/M, team/lifecycle

#5556 build etcd-launcher during e2e tests
  api/hack/ci/ci-setup-kubermatic-in-kind.sh
  api/hack/lib.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5558 Revert pull policy for etcd-launcher
  api/pkg/resources/etcd/statefulset.go
  api/pkg/resources/test/fixtures/statefulset-aws-1.15.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-aws-1.16.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-aws-1.17.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-aws-1.18.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-azure-1.15.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-azure-1.16.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-azure-1.17.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-azure-1.18.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-bringyourown-1.15.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-bringyourown-1.16.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-bringyourown-1.17.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-bringyourown-1.18.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-digitalocean-1.15.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-digitalocean-1.16.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-digitalocean-1.17.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-digitalocean-1.18.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-openstack-1.15.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-openstack-1.16.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-openstack-1.17.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-openstack-1.18.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-vsphere-1.15.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-vsphere-1.16.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-vsphere-1.17.0-etcd.yaml
  api/pkg/resources/test/fixtures/statefulset-vsphere-1.18.0-etcd.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5535 Add endpoint to list openstack availability zones
  api/Gopkg.lock
  api/cmd/kubermatic-api/swagger.json
  api/pkg/api/v1/types.go
  api/pkg/handler/routes_v1.go
  api/pkg/handler/v1/provider/openstack.go
  api/pkg/provider/cloud/openstack/helper.go
  api/pkg/provider/cloud/openstack/provider.go
  api/pkg/test/e2e/api/utils/apiclient/client/openstack/list_openstack_availability_zones_no_credentials_parameters.go
  api/pkg/test/e2e/api/utils/apiclient/client/openstack/list_openstack_availability_zones_no_credentials_responses.go
  api/pkg/test/e2e/api/utils/apiclient/client/openstack/list_openstack_availability_zones_parameters.go
  api/pkg/test/e2e/api/utils/apiclient/client/openstack/list_openstack_availability_zones_responses.go
  api/pkg/test/e2e/api/utils/apiclient/client/openstack/openstack_client.go
  api/pkg/test/e2e/api/utils/apiclient/models/openstack_availability_zone.go
  api/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/availabilityzones/doc.go
  api/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/availabilityzones/requests.go
  api/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/availabilityzones/results.go
  api/vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/availabilityzones/urls.go
  api/vendor/k8s.io/test-infra/gubernator/github/secrets.py
  api/vendor/k8s.io/test-infra/images/krte/variants.yaml
  api/vendor/k8s.io/test-infra/prow/crier/README.md
  api/vendor/k8s.io/test-infra/prow/plank/README.md
  api/vendor/k8s.io/test-infra/prow/tide/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL, team/lifecycle, team/ui

#5540 add logout endpoint
  api/cmd/kubermatic-api/swagger.json
  api/pkg/handler/auth/oidc.go
  api/pkg/handler/auth/plugin.go
  api/pkg/handler/middleware/middleware.go
  api/pkg/handler/routes_v1.go
  api/pkg/handler/routes_v1_admin.go
  api/pkg/handler/routes_v1_legacy.go
  api/pkg/handler/test/helper.go
  api/pkg/handler/v1/user/user.go
  api/pkg/handler/v1/user/user_test.go
  api/pkg/provider/kubernetes/user.go
  api/pkg/provider/kubernetes/user_test.go
  api/pkg/provider/types.go
  api/pkg/resources/resources.go
  api/pkg/test/e2e/api/utils/apiclient/client/users/logout_current_user_parameters.go
  api/pkg/test/e2e/api/utils/apiclient/client/users/logout_current_user_responses.go
  api/pkg/test/e2e/api/utils/apiclient/client/users/users_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL, team/ui

#5439 Go Modules Proposal
  docs/proposals/go-modules.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5551 added seed name list endpoint
  api/cmd/kubermatic-api/swagger.json
  api/pkg/api/v1/types.go
  api/pkg/handler/routes_v1.go
  api/pkg/handler/v1/seed/seed.go
  api/pkg/handler/v1/seed/seed_test.go
  api/pkg/test/e2e/api/utils/apiclient/client/kubermatic_client.go
  api/pkg/test/e2e/api/utils/apiclient/client/seed/list_seed_names_parameters.go
  api/pkg/test/e2e/api/utils/apiclient/client/seed/list_seed_names_responses.go
  api/pkg/test/e2e/api/utils/apiclient/client/seed/seed_client.go
  api/pkg/test/e2e/api/utils/apiclient/models/seed_names_list.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/ui

#5533 add pod and node depoyment metrics e2e
  api/cmd/conformance-tests/custom_tests.go
  api/cmd/conformance-tests/main.go
  api/cmd/conformance-tests/runner.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#5538 [Doc]:FIx the bad URL of the code of conduct file
  CODE_OF_CONDUCT.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#5565 fix changing user/password for OpenStack cluster credentials
  api/pkg/provider/kubernetes/credentials.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/ui

#5552 Update cert-manager to 0.15.1
  api/hack/ci/ci-setup-kubermatic-in-kind.sh
  api/hack/deploy.sh
  api/hack/update-cert-manager-crds.sh
  config/cert-manager/Chart.yaml
  config/cert-manager/crd/cert-manager.crds.yaml
  config/cert-manager/templates/cainjector-rbac.yaml
  config/cert-manager/templates/cert-manager-deployment.yaml
  config/cert-manager/templates/cert-manager-rbac.yaml
  config/cert-manager/templates/webhook-deployment.yaml
  config/cert-manager/templates/webhook-mutating-webhook.yaml
  config/cert-manager/templates/webhook-rbac.yaml
  config/cert-manager/templates/webhook-validating-webhook.yaml
  config/cert-manager/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-action-required, size/XXL

#5432 addon installer controller: update existing addons if needed
  api/pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller.go
  api/pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/L, team/lifecycle

#5572 bump machine-controller to v1.14.2
  api/Gopkg.lock
  api/pkg/resources/machinecontroller/deployment.go
  api/pkg/resources/test/fixtures/deployment-aws-1.15.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.15.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.16.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.16.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.15.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.15.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.16.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.16.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.15.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.15.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.16.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.16.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.15.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.15.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.16.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.16.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.15.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.15.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.16.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.16.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.15.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.15.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.16.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.16.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5573 make run-* scripts more user friendly, remove dependency on secrets repo
  hack/lib.sh
  hack/run-all.sh
  hack/run-api.sh
  hack/run-dashboard-and-api.sh
  hack/run-machine-controller.sh
  hack/run-master-controller-manager.sh
  hack/run-operator.sh
  hack/run-seed-controller-manager.sh
  hack/run-user-cluster-controller-manager.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5574 fix lib.sh being incompatible with Alpine's shell by just using bash
  hack/ci/ci-sync-apiclient.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5576 fix typo in allowed_licensed filename by using default wwhrd file
  .wwhrd.yml
  hack/lib.sh
  hack/verify-licenses.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
