Repository kubermatic/kubermatic, pull requests merged in 2020-10, with the labels that each got.

#5978 Fix path changing in e2e tests
  hack/ci/run-api-e2e.sh
  hack/ci/setup-kubermatic-in-kind.sh
  hack/ci/setup-legacy-kubermatic-in-kind.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5969 Allow disabling Certificate creation in Operator
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/master/resources/kubermatic/common.go
  pkg/controller/operator/master/resources/kubermatic/common_test.go
  pkg/crd/operator/v1alpha1/configuration.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#5973 Etcd-launcher feature flag
  cmd/etcd-launcher/main.go
  hack/verify-boilerplate.sh
  pkg/controller/seed-controller-manager/pvwatcher/pvwatcher_controller.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/resources/etcd/statefulset.go
  pkg/resources/etcd/statefulset_test.go
  pkg/resources/etcd/testdata/etcd-command-with-corruption-flags.golden.sh
  pkg/resources/etcd/testdata/etcd-command-with-launcher.golden.sh
  pkg/resources/etcd/tls-serving-certificate.go
  pkg/resources/test/fixtures/statefulset-aws-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.18.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.19.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.18.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.19.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.18.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.19.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.18.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.19.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.18.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.19.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.16.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.17.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.18.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.19.0-etcd.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL, team/lifecycle

#5982 Add v2.15.0-rc.3 changelog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5981 Fix canary release refering to non-existing dashboard revisions
  hack/ci/canary-github-release.sh
  hack/ci/github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5983 make canary release compatible with jq 1.5
  hack/ci/github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5984 Fix GitHub release again
  hack/ci/github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5988 fix paths in periodic tests again
  hack/ci/setup-kubermatic-in-kind.sh
  hack/ci/setup-legacy-kubermatic-in-kind.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5991 fix error message for PVs on cluster deletion
  pkg/clusterdeletion/deletion.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/XS, team/lifecycle

#5997 Add seed-controller feature gate for etcd-launcher
  cmd/seed-controller-manager/controllers.go
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/controller/seed-controller-manager/kubernetes/pending.go
  pkg/controller/seed-controller-manager/kubernetes/pending_test.go
  pkg/features/features.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#6004 create a new V2 endpoint to list the cluster namespaces
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/cluster.go
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_namespace_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_namespace_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#6002 Add MaximumParallelReconciles option to KubermaticConfiguration
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
  pkg/controller/operator/seed/resources/kubermatic/seed-controller-manager.go
  pkg/crd/operator/v1alpha1/configuration.go
  pkg/ee/conversion/helm.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#5990 [release/v2.14] Finish migration to the k8s.gcr.io Docker registry
  addons/kube-proxy/daemonset.yaml
  addons/metrics-server/metrics-server-deployment.yaml
  addons/nodelocal-dns-cache/dns.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, team/lifecycle

#5968 Make caBundle available to kubermatic-api when it is configured but n…
  charts/kubermatic/Chart.yaml
  charts/kubermatic/templates/kubermatic-api-dep.yaml
  pkg/controller/operator/master/resources/kubermatic/api.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#6005 create a new V2 endpoint for cluster SSH keys management
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/cluster.go
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v1/common/request.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/assign_ssh_key_to_cluster_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/assign_ssh_key_to_cluster_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/detach_ssh_key_from_cluster_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/detach_ssh_key_from_cluster_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_ssh_keys_assigned_to_cluster_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_ssh_keys_assigned_to_cluster_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL, team/ui

#5869 Add the cluster-autoscaler addon
  addons/cluster-autoscaler/cluster-autoscaler.yaml
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/accessible-addons.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#6013 fix RBAC Binding for OIDC kubeconfig
  pkg/controller/user-cluster-controller-manager/cluster-role-labeler/cluster_role_labeler.go
  pkg/controller/user-cluster-controller-manager/owner-binding-creator/owner_binding_creator.go
  pkg/controller/user-cluster-controller-manager/owner-binding-creator/owner_binding_creator_test.go
  pkg/test/e2e/api/cluster_rbac_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#6026 Fix UserCluster dashboard showing inflated numbers
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/dashboards/kubermatic/user-clusters.json
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#6021 create v2 endpoint for getting cluster updates
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/upgrade.go
  pkg/handler/v1/cluster/upgrade.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/cluster/upgrade.go
  pkg/handler/v2/cluster/upgrade_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_cluster_upgrades_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_cluster_upgrades_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL, team/ui

#6030 create V2 endpoint to upgrade node deployments version
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/upgrade.go
  pkg/handler/v1/cluster/upgrade.go
  pkg/handler/v2/cluster/upgrade.go
  pkg/handler/v2/cluster/upgrade_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/api/utils/apiclient/client/project/upgrade_cluster_node_deployments_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/upgrade_cluster_node_deployments_v2_responses.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5987 [release/v2.13] Add configurable default addon enforce option
  .prow.yaml
  api/cmd/seed-controller-manager/controllers.go
  api/cmd/seed-controller-manager/options.go
  api/pkg/controller/operator/common/defaults.go
  api/pkg/controller/seed-controller-manager/addon/addon_controller.go
  api/pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller.go
  api/pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller_test.go
  api/pkg/crd/client/clientset/versioned/typed/kubermatic/v1/addon.go
  api/pkg/crd/client/clientset/versioned/typed/kubermatic/v1/fake/fake_addon.go
  api/pkg/crd/kubermatic/v1/addon.go
  api/pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  api/pkg/resources/address/address_test.go
  config/kubermatic/Chart.yaml
  config/kubermatic/templates/kubermatic-controller-manager-dep.yaml
  config/kubermatic/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#6031 remove deprecated v1/nodes endpoints
  cmd/kubermatic-api/swagger.json
  pkg/handler/routes_v1_legacy.go
  pkg/handler/v1/node/legacy.go
  pkg/handler/v1/node/node_test.go
  pkg/test/e2e/api/utils/apiclient/client/project/create_node_for_cluster_legacy_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/create_node_for_cluster_legacy_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_node_for_cluster_legacy_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_node_for_cluster_legacy_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_nodes_for_cluster_legacy_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_nodes_for_cluster_legacy_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL, team/ui

#6033 Add EtcdLauncher feature gate to the chart
  charts/kubermatic/Chart.yaml
  charts/kubermatic/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6029 [vSphere] Improve datastore handling
  .prow.yaml
  cmd/conformance-tests/scenarios_vsphere.go
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.seed.yaml
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/provider/cloud/vsphere/provider.go
  pkg/provider/cloud/vsphere/provider_test.go
  pkg/resources/cloudconfig/configmap.go
  pkg/resources/cloudconfig/configmap_test.go
  pkg/test/e2e/api/utils/apiclient/models/datacenter_spec_v_sphere.go
  pkg/test/e2e/api/utils/apiclient/models/v_sphere_cloud_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle, team/ui

#5977 bump version of oauth2-proxy, add flag to add custom prover CA
  charts/iap/Chart.yaml
  charts/iap/templates/deployments.yaml
  charts/iap/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6037 Fix IAP chart
  charts/iap/Chart.yaml
  charts/iap/templates/deployments.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6038 add changelog for 2.13.9
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6039 add 2.14.7 changelog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6043 fix tag-check in github release script
  hack/ci/github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6041 [release/v2.15] Add EtcdLauncher feature gate to the chart
  charts/kubermatic/Chart.yaml
  charts/kubermatic/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6046 [release/v2.14] fix tag-check in github release
  api/hack/ci/ci-github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6045 improve code clarity
  hack/ci/github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6044 [release/v2.15] fix tag-check in github release script
  hack/ci/ci-github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6047 fix blackbox exporter module http version syntax
  charts/monitoring/blackbox-exporter/Chart.yaml
  charts/monitoring/blackbox-exporter/values.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#6050 Bump machine-controller to v1.19.0
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-machine-controller.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#6051 Fix bug where cluster in deletion kills controller
  api/pkg/crd/migrations/seed/migrations.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS, team/lifecycle

#6052 fix typo in Prometheus runbook
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/rules/general-prometheus.yaml
  charts/monitoring/prometheus/rules/src/general/prometheus.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6056 [release/v2.14] fix typo in Prometheus runbook (#6052)
  config/monitoring/prometheus/Chart.yaml
  config/monitoring/prometheus/rules/general-prometheus.yaml
  config/monitoring/prometheus/rules/src/general/prometheus.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6057 [release/v2.13] fix typo in Prometheus runbook (#6052)
  config/monitoring/prometheus/Chart.yaml
  config/monitoring/prometheus/rules/general-prometheus.yaml
  config/monitoring/prometheus/rules/src/general/prometheus.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6058 Add 2.15.0 Changelog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6049 move cmd/util to pkg/util/cli
  cmd/conformance-tests/main.go
  cmd/kubeletdnat-controller/main.go
  cmd/kubermatic-api/main.go
  cmd/master-controller-manager/main.go
  cmd/nodeport-proxy/envoy-manager/main.go
  cmd/nodeport-proxy/lb-updater/main.go
  cmd/seed-controller-manager/main.go
  cmd/user-cluster-controller-manager/main.go
  cmd/user-ssh-keys-agent/main.go
  pkg/util/cli/hello.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle, team/ui

#6055 [release/v2.15] fix typo in Prometheus runbook (#6052)
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/rules/general-prometheus.yaml
  charts/monitoring/prometheus/rules/src/general/prometheus.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5996 Allow to run conformance-tests locally again
  .prow.yaml
  cmd/conformance-tests/README.md
  cmd/conformance-tests/cleanup.go
  cmd/conformance-tests/custom_tests.go
  cmd/conformance-tests/main.go
  cmd/conformance-tests/metrics.go
  cmd/conformance-tests/run.sh
  cmd/conformance-tests/runner.go
  cmd/conformance-tests/scenarios_aws.go
  hack/ci/run-conformance-tests.sh
  hack/ci/run-e2e-tests.sh
  hack/ci/setup-kubermatic-in-kind.sh
  hack/ci/setup-legacy-kubermatic-in-kind.sh
  hack/lib.sh
  hack/run-conformance-tests.sh
  pkg/crd/kubermatic/v1/helper/helper.go
  pkg/crd/kubermatic/v1/helper/helper_test.go
  pkg/test/e2e/api/credentials_test.go
  pkg/test/e2e/api/oidc.go
  pkg/test/e2e/api/runner.go
  pkg/test/e2e/api/util.go
  pkg/test/e2e/api/utils/dex/client.go
  pkg/test/e2e/api/utils/http.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL, team/lifecycle

#6017 Don't deploy cluster-autoscaler on unsupported clusters
  addons/cluster-autoscaler/cluster-autoscaler.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6059 Fix cluster-autoscaler addon template error and addons templating tests
  addons/cluster-autoscaler/cluster-autoscaler.yaml
  pkg/addon/template_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6063 Support KubermaticConfiguration in image-loader
  cmd/image-loader/README.md
  cmd/image-loader/main.go
  cmd/image-loader/main_test.go
  hack/ci/deploy-offline.sh
  hack/ci/run-offline-test.sh
  pkg/docker/docker.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#6068 create a new v2 endpoint to create machine deployment
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/machine.go
  pkg/handler/v1/node/node.go
  pkg/handler/v2/machine/machine.go
  pkg/handler/v2/machine/machine_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/create_machine_deployment_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/create_machine_deployment_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#6065 Support addons Docker image in image-loader
  cmd/image-loader/main.go
  pkg/docker/docker.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#6072 [release/v2.13] cleanup image-loader (#6063)
  api/cmd/image-loader/README.md
  api/cmd/image-loader/main.go
  api/cmd/image-loader/main_test.go
  api/pkg/docker/docker.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#6071 [release/v2.14] Support KubermaticConfiguration in image-loader (#6063)
  api/cmd/image-loader/README.md
  api/cmd/image-loader/main.go
  api/cmd/image-loader/main_test.go
  api/pkg/docker/docker.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#6080 IAP - Improve custom CA handling
  charts/iap/Chart.yaml
  charts/iap/templates/deployments.yaml
  charts/iap/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6074 v2 endpoint to delete machine node
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/machine.go
  pkg/handler/test/helper.go
  pkg/handler/v1/node/legacy.go
  pkg/handler/v2/machine/machine.go
  pkg/handler/v2/machine/machine_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/delete_machine_node_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/delete_machine_node_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#6082 add datacenter and cloud spec models for anexia provider
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.seed.yaml
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/test/e2e/api/utils/apiclient/models/anexia_cloud_spec.go
  pkg/test/e2e/api/utils/apiclient/models/cloud_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle, team/ui

#6076 Handle warnings/errors in Helm CLI client
  pkg/install/helm/cli.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#6066 Add Helm Support to image-loader
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/templates/_helpers.tpl
  charts/kubernetes-dashboard/templates/dashboard-csrf-secret.yaml
  charts/kubernetes-dashboard/templates/oauth-proxy-secret.yaml
  cmd/image-loader/addons.go
  cmd/image-loader/helm.go
  cmd/image-loader/main.go
  cmd/image-loader/main_test.go
  cmd/image-loader/operator.go
  hack/ci/deploy-offline.sh
  pkg/addon/template.go
  pkg/install/helm/cli.go
  pkg/install/helm/interface.go
  pkg/util/yaml/parse.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL, team/lifecycle, team/ui

#6069 Remove hard dependency on cert-manager from Operator
  cmd/kubermatic-installer/cmd_deploy.go
  cmd/kubermatic-operator/main.go
  pkg/controller/operator/master/controller.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/master/resources/kubermatic/common.go
  pkg/install/stack/kubermatic/stack.go
  pkg/install/stack/kubermatic/validation.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#6085 add presets for anexia provider
  pkg/crd/kubermatic/v1/preset.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#6087 Fix CI offline deployment
  charts/iap/Chart.yaml
  charts/iap/values.yaml
  cmd/image-loader/main.go
  hack/ci/deploy-offline.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#6091 do not use already mirrored values.yaml when mirroring images
  hack/ci/deploy-offline.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6088 [release/v2.15] Backport image-loader improvements (#6066, #6067)
  charts/iap/Chart.yaml
  charts/iap/values.yaml
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/templates/_helpers.tpl
  charts/kubernetes-dashboard/templates/dashboard-csrf-secret.yaml
  charts/kubernetes-dashboard/templates/oauth-proxy-secret.yaml
  cmd/image-loader/addons.go
  cmd/image-loader/helm.go
  cmd/image-loader/main.go
  cmd/image-loader/main_test.go
  cmd/image-loader/operator.go
  hack/ci/ci-deploy-offline.sh
  pkg/addon/template.go
  pkg/install/helm/cli.go
  pkg/install/helm/interface.go
  pkg/util/yaml/parse.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL, team/lifecycle, team/ui

#6092 ship image-loader as new archive for each GitHub release
  hack/ci/github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#6089 [release/v2.14] Backport image-loader Improvements (#6066, #6067)
  api/Gopkg.lock
  api/cmd/image-loader/addons.go
  api/cmd/image-loader/helm.go
  api/cmd/image-loader/main.go
  api/cmd/image-loader/main_test.go
  api/cmd/image-loader/operator.go
  api/hack/ci/ci-deploy-offline.sh
  api/pkg/addon/template.go
  api/pkg/docker/docker.go
  api/pkg/install/helm/cli.go
  api/pkg/install/helm/interface.go
  api/pkg/install/helm/status.go
  api/pkg/install/helm/types.go
  api/pkg/util/yaml/parse.go
  config/kubernetes-dashboard/Chart.yaml
  config/kubernetes-dashboard/templates/_helpers.tpl
  config/kubernetes-dashboard/templates/dashboard-csrf-secret.yaml
  config/kubernetes-dashboard/templates/oauth-proxy-secret.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL, team/lifecycle, team/ui

#6090 [release/v2.13] Backport image-loader Improvements (#6066, #6067)
  api/Gopkg.lock
  api/cmd/image-loader/addons.go
  api/cmd/image-loader/helm.go
  api/cmd/image-loader/main.go
  api/cmd/image-loader/main_test.go
  api/hack/ci/ci-deploy-offline.sh
  api/pkg/addon/template.go
  api/pkg/docker/docker.go
  api/pkg/install/helm/cli.go
  api/pkg/install/helm/interface.go
  api/pkg/install/helm/status.go
  api/pkg/install/helm/types.go
  api/pkg/util/yaml/parse.go
  config/kubernetes-dashboard/Chart.yaml
  config/kubernetes-dashboard/templates/_helpers.tpl
  config/kubernetes-dashboard/templates/dashboard-csrf-secret.yaml
  config/kubernetes-dashboard/templates/oauth-proxy-secret.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL, team/lifecycle, team/ui

#6095 fix typo in github release script
  hack/ci/github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6093 Add changelogs for 2.15.1, 2.14.8 and 2.13.10
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6084 Cache Roles and RoleBindings for addon roles
  api/pkg/controller/master-controller-manager/rbac/cluster_provider.go
  api/pkg/controller/master-controller-manager/rbac/sync_resource.go
  api/pkg/controller/master-controller-manager/rbac/sync_resource_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S, team/ui

#6098 add anexia provider type
  pkg/provider/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6096 [release/v2.14] ship image-loader as new archive for each GitHub release (#6092)
  api/hack/ci/ci-github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#6099 add anexia provider interface
  pkg/provider/cloud/anexia/provider.go
  pkg/provider/cloud/provider.go
  pkg/resources/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#6100 Fix GitHub Release
  api/hack/ci/ci-github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6003 Add convert-kubeconfig command to installer
  cmd/kubermatic-installer/cmd_convert_kubeconfig.go
  cmd/kubermatic-installer/main_ce.go
  cmd/kubermatic-installer/main_ee.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#6027 Split kind/Kubermatic logic during CI
  hack/ci/run-api-e2e.sh
  hack/ci/run-conformance-tests.sh
  hack/ci/run-e2e-tests.sh
  hack/ci/setup-kind-cluster.sh
  hack/ci/setup-kubermatic-in-kind.sh
  hack/ci/setup-legacy-kubermatic-in-kind.sh
  hack/ci/testdata/kubermatic.yaml
  hack/ci/testdata/seed.yaml
  hack/run-user-cluster-controller-manager.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL, team/lifecycle

#6104 add 2.15.2 changelog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6102 Allow to adjust the Docker image tag for addons
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/seed/resources/kubermatic/seed-controller-manager.go
  pkg/crd/operator/v1alpha1/configuration.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#6107 create v2 endpoint to list machine deployments
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/machine.go
  pkg/handler/test/fake_wrapper.go
  pkg/handler/v1/node/node.go
  pkg/handler/v1/node/node_test.go
  pkg/handler/v2/machine/machine.go
  pkg/handler/v2/machine/machine_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_machine_deployments_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_machine_deployments_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#6108 Delete k8s dashboard helm chart
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/OWNERS
  charts/kubernetes-dashboard/templates/_helpers.tpl
  charts/kubernetes-dashboard/templates/dashboard-clusterrole.yaml
  charts/kubernetes-dashboard/templates/dashboard-clusterrolebinding.yaml
  charts/kubernetes-dashboard/templates/dashboard-csrf-secret.yaml
  charts/kubernetes-dashboard/templates/dashboard-deployment.yaml
  charts/kubernetes-dashboard/templates/dashboard-ingress.yaml
  charts/kubernetes-dashboard/templates/dashboard-key-holder-secret.yaml
  charts/kubernetes-dashboard/templates/dashboard-role.yaml
  charts/kubernetes-dashboard/templates/dashboard-rolebinding.yaml
  charts/kubernetes-dashboard/templates/dashboard-service.yaml
  charts/kubernetes-dashboard/templates/dashboard-serviceaccount.yaml
  charts/kubernetes-dashboard/templates/dashboard-settings-configmap.yaml
  charts/kubernetes-dashboard/templates/oauth-proxy-deployment.yaml
  charts/kubernetes-dashboard/templates/oauth-proxy-ingress.yaml
  charts/kubernetes-dashboard/templates/oauth-proxy-secret.yaml
  charts/kubernetes-dashboard/templates/oauth-proxy-service.yaml
  charts/kubernetes-dashboard/templates/scraper-deployment.yaml
  charts/kubernetes-dashboard/templates/scraper-service.yaml
  charts/kubernetes-dashboard/values.yaml
  hack/ci/github-release.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/XL, team/ui
