Repository kubermatic/kubermatic, pull requests merged in 2020-09, with the labels that each got.

#5769 cleanup after RBAC controller refactoring
  cmd/master-controller-manager/controllers.go
  pkg/controller/master-controller-manager/rbac/rbac_controller_aggregator.go
  pkg/controller/master-controller-manager/rbac/rbac_project_controller.go
  pkg/controller/master-controller-manager/rbac/rbac_resource_controller.go
  pkg/controller/master-controller-manager/rbac/sync_project.go
  pkg/controller/master-controller-manager/rbac/sync_project_test.go
  pkg/controller/master-controller-manager/rbac/sync_resource.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/ui

#5800 Update changelog for 2.14.5
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#5802 get metrics endpoint for external cluster
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/cluster.go
  pkg/handler/test/fake_provider.go
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/external_cluster.go
  pkg/provider/types.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_external_cluster_metrics_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_external_cluster_metrics_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5813 update changelog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#5809 get nodes metrics for external cluster
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/node.go
  pkg/handler/v1/node/node.go
  pkg/handler/v2/external_cluster/node.go
  pkg/handler/v2/external_cluster/node_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_external_cluster_nodes_metrics_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_external_cluster_nodes_metrics_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5819 get external cluster events
  cmd/kubermatic-api/swagger.json
  pkg/handler/v1/common/event.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_external_cluster_events_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/list_external_cluster_events_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5827 fix get kubeconfig endpoint
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/routes_v1.go
  pkg/handler/v1/cluster/kubeconfig.go
  pkg/test/e2e/api/digitalocean_test.go
  pkg/test/e2e/api/runner.go
  pkg/test/e2e/api/utils/apiclient/client/operations/create_o_id_c_kubeconfig_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_cluster_kubeconfig_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_oidc_cluster_kubeconfig_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/api/utils/apiclient/models/auth_info.go
  pkg/test/e2e/api/utils/apiclient/models/auth_provider_config.go
  pkg/test/e2e/api/utils/apiclient/models/config.go
  pkg/test/e2e/api/utils/apiclient/models/context.go
  pkg/test/e2e/api/utils/apiclient/models/exec_config.go
  pkg/test/e2e/api/utils/apiclient/models/exec_env_var.go
  pkg/test/e2e/api/utils/apiclient/models/named_auth_info.go
  pkg/test/e2e/api/utils/apiclient/models/named_cluster.go
  pkg/test/e2e/api/utils/apiclient/models/named_context.go
  pkg/test/e2e/api/utils/apiclient/models/named_extension.go
  pkg/test/e2e/api/utils/apiclient/models/preferences.go
  pkg/test/e2e/api/utils/apiclient/models/raw_extension.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL, team/ui

#5820 Update Kubernetes Dashboard to v2.0.4
  pkg/resources/kubernetes-dashboard/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.16.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-aws-1.17.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.16.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.16.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.16.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.16.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.16.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-kubernetes-dashboard.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#5824 Package Installer and Charts
  Dockerfile
  cmd/kubermatic-installer/cmd_deploy.go
  cmd/kubermatic-installer/cmd_version.go
  cmd/kubermatic-installer/main.go
  hack/ci/ci-github-release.sh
  hack/ci/ci-push-images.sh
  hack/ci/ci-run-offline-test.sh
  hack/push_image.sh
  hack/release-docker-images.sh
  pkg/install/helm/cli.go
  pkg/install/helm/interface.go
  pkg/install/stack/kubermatic/stack.go
  pkg/install/util/crd.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL, team/lifecycle

#5832 Bump k8s Go dependencies to v0.19.0
  go.mod
  go.sum
  hack/verify-licenses.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5833 add continuouslyReconcile flag for addons
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/v1/addon/addon.go
  pkg/handler/v1/addon/addon_test.go
  pkg/provider/kubernetes/addon.go
  pkg/provider/types.go
  pkg/test/e2e/api/utils/apiclient/models/addon_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/ui

#5823 Update e2e tests to kind 0.8.1
  .prow.yaml
  hack/ci/ci-setup-kubermatic-in-kind.sh
  hack/ci/ci-setup-legacy-kubermatic-in-kind.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5834 Use Go 1.15 for CI jobs
  .prow.yaml
  Makefile
  containers/integration-tests/Dockerfile
  pkg/log/logrus.go
  pkg/test/e2e/api/cluster_test.go
  pkg/validation/cluster_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#5831 define optional presubmit to test the github release code
  .gitignore
  .prow.yaml
  hack/ci/ci-github-release.sh
  hack/ci/ci-test-github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5830 Provide quickstart infos for DNS settings in Kubermatic Installer
  cmd/kubermatic-installer/cmd_deploy.go
  cmd/kubermatic-installer/main.go
  pkg/install/stack/kubermatic/stack.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#5835 remove the unused test
  pkg/test/e2e/api/cluster_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5836 fix error handling for getting metrics
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v1/node/node.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/ui

#5795 Refactor clients for etcd-launcher
  .prow.yaml
  cmd/etcd-launcher/main.go
  go.sum
  pkg/crd/kubermatic/v1/cluster.go
  pkg/resources/etcd/statefulset.go
  pkg/resources/etcd/tls-serving-certificate.go
  pkg/resources/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#5829 allow custom envvar definitions for dex to be passed via the oauth chart
  charts/oauth/Chart.yaml
  charts/oauth/templates/deployment.yaml
  charts/oauth/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#5847 [release/v2.14] custom dex envvars
  config/oauth/Chart.yaml
  config/oauth/templates/deployment.yaml
  config/oauth/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#5841 refactor fake external cluster provider
  pkg/handler/test/fake_provider.go
  pkg/handler/v1/node/node_test.go
  pkg/handler/v2/external_cluster/node_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/ui

#5851 do not deploy nodeport-proxy chart on dev anymore
  hack/ci/ci-deploy-dev-asia.sh
  hack/ci/ci-deploy-dev.sh
  pkg/resources/address/address_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5853 set vpa-webhook Service explicitly so we don't end up in a reconcile loop
  pkg/controller/operator/common/vpa/admissionctrl.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS, team/lifecycle

#5846 Take into account DOCKER_REPO environment variable for image release
  Makefile
  cmd/kubeletdnat-controller/Makefile
  cmd/nodeport-proxy/Makefile
  cmd/user-ssh-keys-agent/Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#5843 Finish basic StorageClass creation support
  cmd/kubermatic-installer/cmd_deploy.go
  hack/ci/ci-setup-kubermatic-in-kind.sh
  pkg/install/stack/kubermatic/stack.go
  pkg/install/stack/kubermatic/storageclass.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#5855 Fix GitHub Release Script
  hack/ci/ci-github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5854 Update Minio to RELEASE.2020-09-10T22-02-45 / bump utilities
  .prow.yaml
  charts/kubermatic/Chart.yaml
  charts/kubermatic/values.yaml
  charts/logging/kibana/Chart.yaml
  charts/logging/kibana/values.yaml
  charts/minio/Chart.yaml
  charts/minio/values.yaml
  charts/monitoring/alertmanager/Chart.yaml
  charts/monitoring/alertmanager/values.yaml
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/values.yaml
  charts/monitoring/karma/Chart.yaml
  charts/monitoring/karma/values.yaml
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/rules/general-blackbox-exporter.yaml
  charts/monitoring/prometheus/rules/general-cadvisor.yaml
  charts/monitoring/prometheus/rules/general-cert-manager.yaml
  charts/monitoring/prometheus/rules/general-elasticsearch-exporter.yaml
  charts/monitoring/prometheus/rules/general-fluentbit.yaml
  charts/monitoring/prometheus/rules/general-helm-exporter.yaml
  charts/monitoring/prometheus/rules/general-kube-apiserver.yaml
  charts/monitoring/prometheus/rules/general-kube-kubelet.yaml
  charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/general-node-exporter.yaml
  charts/monitoring/prometheus/rules/general-prometheus.yaml
  charts/monitoring/prometheus/rules/general-thanos.yaml
  charts/monitoring/prometheus/rules/general-velero.yaml
  charts/monitoring/prometheus/rules/general-vertical-pod-autoscaler.yaml
  charts/monitoring/prometheus/rules/kubermatic-master-kubermatic.yaml
  charts/monitoring/prometheus/rules/kubermatic-seed-kubermatic.yaml
  charts/monitoring/prometheus/rules/managed-kube-controller-manager.yaml
  charts/monitoring/prometheus/rules/managed-kube-scheduler.yaml
  charts/monitoring/prometheus/values.yaml
  containers/util/Dockerfile
  containers/util/release.sh
  pkg/controller/master-controller-manager/seed-proxy/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL, team/lifecycle

#5856 Validate serviceAccountKey in the installer
  pkg/install/stack/kubermatic/validation.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5842 Added Support for imagepullsecrets in cert-manager chart
  charts/cert-manager/Chart.yaml
  charts/cert-manager/templates/cert-manager-serviceaccount.yaml
  charts/cert-manager/values.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#5862 get events for cluster V2 endpoint
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/cluster.go
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_cluster_events_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_cluster_events_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5864 Make sure that the entries in nginx cm data are quoted
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/templates/configmaps.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5695 add a proposal for cluster import
  docs/proposals/import-cluster.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5863 Add script to perform canary releases
  hack/ci/ci-canary-github-release.sh
  hack/ci/ci-github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5865 Fix canary release
  hack/ci/ci-canary-github-release.sh
  hack/ci/ci-github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5868 [release/v2.14] Make sure that the entries in nginx cm data are quoted
  config/nginx-ingress-controller/Chart.yaml
  config/nginx-ingress-controller/templates/configmaps.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5867 support for continuouslyReconcile during addon update
  pkg/handler/v1/addon/addon.go
  pkg/handler/v1/addon/addon_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/ui

#5857 Provide warnings about potentially invalid Dex config
  pkg/install/stack/kubermatic/validation.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M, team/lifecycle

#5858 Add conversion commands to installer
  cmd/example-yaml-generator/main.go
  cmd/kubermatic-installer/cmd_deploy.go
  cmd/kubermatic-installer/main.go
  cmd/kubermatic-installer/main_ce.go
  cmd/kubermatic-installer/main_ee.go
  cmd/kubermatic-installer/shared.go
  cmd/kubermatic-operator-util/main.go
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/crd/kubermatic/v1/datacenter_test.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/ee/cmd/kubermatic-installer/cmd_convert_datacenters.go
  pkg/ee/cmd/kubermatic-installer/cmd_convert_helm.go
  pkg/ee/cmd/kubermatic-installer/shared.go
  pkg/ee/conversion/helm.go
  pkg/ee/provider/conversions.go
  pkg/ee/provider/conversions_test.go
  pkg/ee/provider/datacenter.go
  pkg/handler/test/helper.go
  pkg/handler/v1/dc/datacenter.go
  pkg/provider/conversions_test.go
  pkg/provider/datacenter_test.go
  pkg/resources/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL, team/lifecycle, team/ui

#5872 v2 health endpoint
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/cluster.go
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_cluster_health_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_cluster_health_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5873 Fix peerURL upgrade issues
  cmd/etcd-launcher/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S, team/lifecycle

#5879 cleanup docs/ a bit
  docs/README.md
  docs/datacenters.md
  docs/release-process.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5768 OPA integration proposal
  docs/proposals/opa-integration.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5880 Support override etcd launcher image
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
  pkg/controller/operator/seed/resources/kubermatic/seed-controller-manager.go
  pkg/crd/operator/v1alpha1/configuration.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S, team/lifecycle

#5874 Make imagePullSecret optional in KubermaticConfiguration
  charts/test/kubermatic.example.ce.yaml
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/main.go
  cmd/seed-controller-manager/options.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/master/resources/kubermatic/api.go
  pkg/controller/operator/master/resources/kubermatic/master-controller-manager.go
  pkg/controller/operator/master/resources/kubermatic/ui.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/operator/seed/reconciler_test.go
  pkg/controller/operator/seed/resources/kubermatic/seed-controller-manager.go
  pkg/controller/operator/seed/resources/nodeportproxy/deployments.go
  pkg/resources/reconciling/wrapper.go
  pkg/resources/reconciling/wrapper_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#5889 Fix RBAC controller spamming logs
  pkg/controller/master-controller-manager/rbac/sync_project.go
  pkg/controller/master-controller-manager/rbac/sync_resource.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS, team/ui

#5887 Fix gocache accidentally interpreting random headers as HTTP 404
  hack/ci/ci-download-gocache.sh
  hack/ci/ci-upload-gocache.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5881 kubeconfig endpoints for V2
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/kubeconfig.go
  pkg/handler/middleware/middleware.go
  pkg/handler/v1/cluster/kubeconfig.go
  pkg/handler/v1/cluster/kubeconfig_test.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/cluster/kubeconfig.go
  pkg/handler/v2/cluster/kubeconfig_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/cluster.go
  pkg/provider/types.go
  pkg/test/e2e/api/utils/apiclient/client/operations/create_o_id_c_kubeconfig_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_cluster_kubeconfig_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_cluster_kubeconfig_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_oidc_cluster_kubeconfig_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_oidc_cluster_kubeconfig_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL, team/ui

#5709 Cleanup API e2e Tests / The Unflakaning
  .prow.yaml
  go.mod
  hack/ci/ci-run-api-e2e.sh
  hack/ci/ci-setup-kubermatic-in-kind.sh
  hack/ci/ci-setup-legacy-kubermatic-in-kind.sh
  hack/lib.sh
  pkg/test/e2e/api/admin_test.go
  pkg/test/e2e/api/client.go
  pkg/test/e2e/api/cluster_rbac_test.go
  pkg/test/e2e/api/credentials_test.go
  pkg/test/e2e/api/dc_test.go
  pkg/test/e2e/api/digitalocean_test.go
  pkg/test/e2e/api/gcp_test.go
  pkg/test/e2e/api/logout_test.go
  pkg/test/e2e/api/oidc.go
  pkg/test/e2e/api/runner.go
  pkg/test/e2e/api/sa_test.go
  pkg/test/e2e/api/settings_test.go
  pkg/test/e2e/api/ssh_test.go
  pkg/test/e2e/api/user_test.go
  pkg/test/e2e/api/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL, team/ui

#5908 metrics endpoint for V2
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/cluster.go
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_cluster_metrics_v2_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/project/get_cluster_metrics_v2_responses.go
  pkg/test/e2e/api/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5912 Add external cluster option to the global settings
  cmd/kubermatic-api/swagger.json
  pkg/crd/kubermatic/v1/settings.go
  pkg/handler/test/helper.go
  pkg/handler/v1/admin/settings_test.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/node.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/settings.go
  pkg/test/e2e/api/settings_test.go
  pkg/test/e2e/api/utils/apiclient/models/setting_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle, team/ui

#5886 Fix comment on cluster field of vSphere datacenter spec
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.seed.yaml
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/test/e2e/api/utils/apiclient/models/datacenter_spec_v_sphere.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle, team/ui

#5919 Make unit-test independent from actual DNS resolution
  pkg/controller/seed-controller-manager/kubernetes/address.go
  pkg/controller/seed-controller-manager/openshift/openshift_controller.go
  pkg/resources/address/address.go
  pkg/resources/address/address_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#5913 Change backup job restart policy to "Never"
  pkg/controller/seed-controller-manager/backup/backup_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS, team/lifecycle

#5883 Add operator.kubermatic.io/skip-reconciling annotation for Seeds
  pkg/controller/operator/common/resources.go
  pkg/controller/operator/seed/reconciler.go
  pkg/ee/cmd/kubermatic-installer/cmd_convert_datacenters.go
  pkg/ee/cmd/kubermatic-installer/cmd_convert_helm.go
  pkg/ee/cmd/kubermatic-installer/shared.go
  pkg/ee/conversion/helm.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#5923 [release/v2.14] Make unit-test independent from actual DNS resolution
  api/pkg/controller/seed-controller-manager/kubernetes/address.go
  api/pkg/controller/seed-controller-manager/openshift/openshift_controller.go
  api/pkg/resources/address/address.go
  api/pkg/resources/address/address_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, team/lifecycle

#5930 Use Flatcar for base k8s conformance tests
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5934 Makefile improvements
  Makefile
  go.mod
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5937 Remove unused scripts
  hack/download_images.sh
  hack/run-all.sh
  hack/run-kubermatic-kind-upgrade-test.sh
  hack/verify-addon-version.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5943 Bump jobs to Go 1.15
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5933 Makefile: better support for compiling with debug symbols
  Makefile
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/XS

#5925 Update changelog for 2.15.0-rc.1
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5941 Move the CI-related scripts to hack/ci
  .prow.yaml
  hack/ci/ci-deploy-ci-kubermatic-io.sh
  hack/ci/ci-deploy-dev-asia.sh
  hack/ci/ci-deploy-dev.sh
  hack/ci/ci-deploy-offline.sh
  hack/ci/ci-deploy-run-2-lab-alpha.sh
  hack/ci/ci-deploy-run-lab-stable.sh
  hack/ci/ci-deploy-run.sh
  hack/ci/ci-deploy.sh
  hack/ci/ci-verify-chart-versions.sh
  hack/ci/ci-verify-user-cluster-prometheus-configs.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5929 Handle more flaky status codes in API e2e tests
  pkg/test/e2e/api/runner.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5940 Fix Cover.sh
  hack/coverage.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5939 Deleted obsolete hack/gen-api-docs.sh
  docs/api-docs.md
  hack/gen-api-docs.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5950 Upgrade machine-controller tag to fix RHEL8 machines creation
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.16.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.16.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-machine-controller.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#5953 Fix flaky unit test
  pkg/util/yamled/document_test.go
  pkg/util/yamled/testcases/fill-two-new-root-keys.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5927 Add Kuberentes 1.16.15, 1.17.12, 1.19.2
  .prow.yaml
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/versions.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M, team/lifecycle

#5932 [release/v2.14] use Flatcar for base k8s conformance tests (#5930)
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5951 [v2.14] Upgrade machine-controller tag to fix RHEL8 machines creation
  api/pkg/resources/machinecontroller/deployment.go
  api/pkg/resources/test/fixtures/deployment-aws-1.15.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.15.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.16.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.16.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.15.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.15.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.16.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.16.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.15.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.15.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.16.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.16.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.15.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.15.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.16.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.16.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.15.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.15.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.16.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.16.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.15.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.15.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.16.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.16.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller-webhook.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#5890 [release/v2.14] Make sure that tag placeholder is replaced for all charts when preparing release tarball
  api/hack/ci/ci-github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5915 Fix operator ingress compatibility
  pkg/controller/operator/master/resources/kubermatic/common.go
  pkg/controller/operator/master/resources/kubermatic/common_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#5917 Constraint template create endpoint
  cmd/kubermatic-api/swagger.json
  pkg/handler/test/fake_provider.go
  pkg/handler/v2/constraint_template/constraint_template.go
  pkg/handler/v2/constraint_template/constraint_template_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/constraint_template.go
  pkg/provider/kubernetes/constraint_template_test.go
  pkg/provider/types.go
  pkg/test/e2e/api/utils/apiclient/client/constrainttemplates/constrainttemplates_client.go
  pkg/test/e2e/api/utils/apiclient/client/constrainttemplates/create_constraint_template_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/constrainttemplates/create_constraint_template_responses.go
  pkg/test/e2e/api/utils/apiclient/models/ct_body.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5957 Prepare 2.15.0-rc.2 changelog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5936 Run scripts in containers
  Makefile
  charts/backup/velero/Chart.yaml
  charts/backup/velero/crd/backups.yaml
  charts/backup/velero/crd/backupstoragelocations.yaml
  charts/backup/velero/crd/deletebackuprequests.yaml
  charts/backup/velero/crd/downloadrequests.yaml
  charts/backup/velero/crd/podvolumebackups.yaml
  charts/backup/velero/crd/podvolumerestores.yaml
  charts/backup/velero/crd/resticrepositories.yaml
  charts/backup/velero/crd/restores.yaml
  charts/backup/velero/crd/schedules.yaml
  charts/backup/velero/crd/serverstatusrequests.yaml
  charts/backup/velero/crd/volumesnapshotlocations.yaml
  charts/monitoring/prometheus/Chart.yaml
  hack/lib.sh
  hack/update-cert-manager-crds.sh
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-grafana-dashboards.sh
  hack/update-kubermatic-chart.sh
  hack/update-prometheus-rules.sh
  hack/update-swagger.sh
  hack/update-velero-crds.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5961 Remove ci- prefix from scripts in hack/ci/
  .prow.yaml
  Makefile
  hack/README.md
  hack/ci/canary-github-release.sh
  hack/ci/deploy-ci-kubermatic-io.sh
  hack/ci/deploy-dev-asia.sh
  hack/ci/deploy-dev.sh
  hack/ci/deploy-offline.sh
  hack/ci/deploy-run-2-lab-alpha.sh
  hack/ci/deploy-run-lab-stable.sh
  hack/ci/deploy-run.sh
  hack/ci/deploy.sh
  hack/ci/download-gocache.sh
  hack/ci/github-release.sh
  hack/ci/push-images.sh
  hack/ci/run-api-e2e.sh
  hack/ci/run-conformance-tester.sh
  hack/ci/run-e2e-tests.sh
  hack/ci/run-lint.sh
  hack/ci/run-offline-test.sh
  hack/ci/setup-kubermatic-in-kind.sh
  hack/ci/setup-legacy-kubermatic-in-kind.sh
  hack/ci/sync-apiclient.sh
  hack/ci/sync-charts.sh
  hack/ci/test-github-release.sh
  hack/ci/update-docs.sh
  hack/ci/upload-gocache.sh
  hack/ci/verify-chart-versions.sh
  hack/ci/verify-user-cluster-prometheus-configs.sh
  hack/meta.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5963 Move to k8s.gcr.io Docker registry for CoreDNS, metrics-server, and NodeLocalDNSCache
  addons/metrics-server/metrics-server-deployment.yaml
  addons/nodelocal-dns-cache/dns.yaml
  pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/deamonset.go
  pkg/resources/dns/dns.go
  pkg/resources/metrics-server/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.16.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.16.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.17.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.17.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.16.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.16.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.16.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.16.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.16.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.16.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.16.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.16.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.16.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.16.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-metrics-server.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L, team/lifecycle

#5959 Constraint template patch endpoint
  cmd/kubermatic-api/swagger.json
  pkg/handler/test/fake_provider.go
  pkg/handler/v2/constraint_template/constraint_template.go
  pkg/handler/v2/constraint_template/constraint_template_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/constraint_template.go
  pkg/provider/kubernetes/constraint_template_test.go
  pkg/provider/types.go
  pkg/test/e2e/api/utils/apiclient/client/constrainttemplates/constrainttemplates_client.go
  pkg/test/e2e/api/utils/apiclient/client/constrainttemplates/patch_constraint_template_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/constrainttemplates/patch_constraint_template_responses.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5962 Provide way to skip certificate CR creation
  charts/kubermatic/Chart.yaml
  charts/kubermatic/templates/certificate.yaml
  charts/kubermatic/values.yaml
  charts/oauth/Chart.yaml
  charts/oauth/templates/certificate.yaml
  charts/oauth/values.yaml
  charts/values.example.ce.yaml
  charts/values.example.ee.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S, team/lifecycle

#5964 Add more Documentation for hack/
  hack/README.md
  hack/ci/README.md
  hack/ci/canary-github-release.sh
  hack/ci/deploy-ci-kubermatic-io.sh
  hack/ci/deploy-dev-asia.sh
  hack/ci/deploy-dev.sh
  hack/ci/deploy-offline.sh
  hack/ci/deploy.sh
  hack/ci/download-gocache.sh
  hack/ci/github-release.sh
  hack/ci/push-images.sh
  hack/ci/run-api-e2e.sh
  hack/ci/run-conformance-tester.sh
  hack/ci/run-e2e-tests.sh
  hack/ci/run-lint.sh
  hack/ci/run-offline-test.sh
  hack/ci/setup-kubermatic-in-kind.sh
  hack/ci/setup-legacy-kubermatic-in-kind.sh
  hack/ci/sync-apiclient.sh
  hack/ci/sync-charts.sh
  hack/ci/test-github-release.sh
  hack/ci/update-docs.sh
  hack/ci/upload-gocache.sh
  hack/ci/verify-chart-versions.sh
  hack/ci/verify-user-cluster-prometheus-configs.sh
  hack/gen-api-client.sh
  hack/lib.sh
  hack/meta.sh
  hack/publish-s3-exporter.sh
  hack/release-docker-images.sh
  hack/retag-images.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#5972 [v2.14] Provide way to skip certificate CR creation
  config/kubermatic/Chart.yaml
  config/kubermatic/templates/certificate.yaml
  config/kubermatic/values.yaml
  config/oauth/Chart.yaml
  config/oauth/templates/certificate.yaml
  config/oauth/values.yaml
  config/values.example.ce.yaml
  config/values.example.ee.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#5966 Constraint templates delete endpoint
  cmd/kubermatic-api/swagger.json
  pkg/handler/test/fake_provider.go
  pkg/handler/v2/constraint_template/constraint_template.go
  pkg/handler/v2/constraint_template/constraint_template_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/constraint_template.go
  pkg/provider/kubernetes/constraint_template_test.go
  pkg/provider/types.go
  pkg/test/e2e/api/utils/apiclient/client/constrainttemplates/constrainttemplates_client.go
  pkg/test/e2e/api/utils/apiclient/client/constrainttemplates/delete_constraint_template_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/constrainttemplates/delete_constraint_template_responses.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL, team/ui

#5974 Add 2.14.6 changelog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5975 [release/v2.14] Fix GitHub Release Script (#5855)
  api/hack/ci/ci-github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5976 Add 2.13.8 changelog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
