Repository kubermatic/kubermatic, pull requests merged in 2021-11, with the labels that each got.

#8118 set defaultComponentSettings for defaultingTemplate
  cmd/seed-controller-manager/main.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8121 add api endpoint to get feature gates
  .golangci.yml
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/options.go
  cmd/kubermatic-api/swagger.json
  hack/run-api.sh
  pkg/api/v2/types.go
  pkg/handler/routing.go
  pkg/handler/test/hack/hack.go
  pkg/handler/test/helper.go
  pkg/handler/v2/feature_gates/feature_gates.go
  pkg/handler/v2/feature_gates/feature_gates_test.go
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/routing.go
  pkg/provider/kubernetes/featuregates.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/get/gates_parameters.go
  pkg/test/e2e/utils/apiclient/client/get/gates_responses.go
  pkg/test/e2e/utils/apiclient/client/get/get_client.go
  pkg/test/e2e/utils/apiclient/client/kubermatic_kubernetes_platform_api_client.go
  pkg/test/e2e/utils/apiclient/models/feature_gates.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8127 Fix linter complaints for DeletePreset
  pkg/provider/kubernetes/preset.go
Labels: needs-ok-to-test, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#8128 MLA Alertmanager Health Status
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/controller/seed-controller-manager/mla/alertmanager_controller.go
  pkg/controller/seed-controller-manager/mla/alertmanager_controller_test.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/alertmanager.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/fake/fake_alertmanager.go
  pkg/crd/kubermatic/v1/alertmanager.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/common/cluster.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/test/e2e/utils/apiclient/models/cluster_health.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, sig/crd

#8103 Change KonnectivityEnabled flag to a pointer to make defaulting easier
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/resources/data.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/crd

#8055 Respect userCluster.overwriteRegistry from k8c config in user cluster controllers and addon manifests
  addons/aws-node-termination-handler/aws-node-termination-handler.yaml
  addons/canal/canal.yaml
  addons/canal/canal_v3.19.yaml
  addons/cilium/cilium.yaml
  addons/cluster-autoscaler/cluster-autoscaler.yaml
  addons/csi/openstack/controllerplugin.yaml
  addons/csi/openstack/nodeplugin.yaml
  addons/csi/vsphere/csiAdmissionWebhook.yaml
  addons/csi/vsphere/csiController.yaml
  addons/csi/vsphere/csiNode-ds.yaml
  addons/multus/daemonset.yaml
  cmd/user-cluster-controller-manager/main.go
  pkg/controller/user-cluster-controller-manager/flatcar/flatcar_controller.go
  pkg/controller/user-cluster-controller-manager/flatcar/resources/update_agent.go
  pkg/controller/user-cluster-controller-manager/flatcar/resources/update_operator.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/core-dns/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/envoy-agent/daemonset.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/kubernetes-dashboard/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/promtail/daemonset.go
  pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/deamonset.go
  pkg/resources/registry/registry.go
  pkg/test/e2e/expose-strategy/agent.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#8077 UserCluster MLA Test Grafana user
  pkg/controller/seed-controller-manager/mla/grafana.go
  pkg/test/e2e/mla/mla_test.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#8112 Rollout RuleGroups from mla namespace to user cluster namespaces
  codegen/reconcile/main.go
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller_test.go
  pkg/controller/seed-controller-manager/mla/rulegroup_sync_controller.go
  pkg/controller/seed-controller-manager/mla/rulegroup_sync_controller_test.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#8133 Allow patching Konnectivity status
  pkg/handler/common/cluster.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#7993 Proposal: extension API server alternative to kubermatic-api
  docs/proposals/images/kubermatic-aggregated-api.png
  docs/proposals/kubermatic-api-aggregation.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#8149 Set apiVersion of kubeadm-config based on Kubernetes version
  addons/kubeadm-configmap/kubeadm-configmap.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#8153 MLA Gateway health status
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/handler/common/cluster.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/test/e2e/utils/apiclient/models/cluster_health.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, sig/crd

#8161 Add auditLogging.policyPreset that allows selecting from several audit policies
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/cluster.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/install/crdmigration/clones.go
  pkg/resources/apiserver/audit.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/test/fixtures/configmap-aws-1.19.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-aws-1.20.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-aws-1.21.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-aws-1.22.1-audit-config.yaml
  pkg/resources/test/fixtures/configmap-azure-1.19.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-azure-1.20.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-azure-1.21.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-azure-1.22.1-audit-config.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.19.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.20.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.21.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.22.1-audit-config.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.19.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.20.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.21.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.22.1-audit-config.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.19.0-audit-config-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.19.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.20.0-audit-config-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.20.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.21.0-audit-config-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.21.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.22.1-audit-config-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.22.1-audit-config.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.19.0-audit-config-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.19.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.20.0-audit-config-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.20.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.21.0-audit-config-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.21.0-audit-config.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-audit-config-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-audit-config.yaml
  pkg/test/e2e/utils/apiclient/models/audit_logging_settings.go
  pkg/test/e2e/utils/apiclient/models/audit_policy_preset.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8150 Allow CNI version upgrades
  pkg/webhook/cluster/validation/validation.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes

#8160 Remove double implementation of registry override function
  pkg/addon/template.go
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/resources/data.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8135 add PATCH endpoint for external cluster
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/project/patch_external_cluster_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/patch_external_cluster_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/utils/apiclient/client/project/update_external_cluster_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/update_external_cluster_responses.go
  pkg/test/e2e/utils/apiclient/models/external_cluster.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#8171 Sync pkg/crd/kubermatic/v1 to pkg/apis/kubermatic/v1
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_alertmanagers.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/apis/kubermatic/v1/alertmanager.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/cluster_templates.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/seed-controller-manager/mla/alertmanager_controller_test.go
  pkg/crd/kubermatic/v1/alertmanager.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/install/crdmigration/clones.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/crd

#8172 Update Kubernetes Dashboard to v2.4.0
  pkg/controller/user-cluster-controller-manager/resources/resources/kubernetes-dashboard/deployment.go
  pkg/resources/kubernetes-dashboard/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kubernetes-dashboard.yaml
Labels: needs-ok-to-test, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#8174 Do not reconcile audit policy ConfigMap if policyPreset is empty
  pkg/resources/apiserver/audit.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8169 Fix setting of nodeport-proxy resource requests/limits, relax default envoy limits
  docs/zz_generated.seed.yaml
  pkg/controller/operator/defaults/defaults.go
  pkg/controller/operator/seed/resources/nodeportproxy/deployments.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8193 Group alerts in Alertmanager and support multiple alerts in template
  charts/monitoring/alertmanager/Chart.yaml
  charts/monitoring/alertmanager/kubermatic.tmpl
  charts/monitoring/alertmanager/values.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#8178 Upgrade User Cluster MLA components
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/promtail/daemonset.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#8176 Remove Optional MLA Health status when feature is disabled
  pkg/api/v1/types.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/seed-controller-manager/mla/alertmanager_controller.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/install/crdmigration/clones.go
  pkg/test/e2e/utils/client.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, sig/crd

#8206 Fix wrong status 0 for MLA Health Status
  pkg/controller/seed-controller-manager/mla/alertmanager_controller.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#8165 hack/local/run-kkp-in-kind.sh: fix to be able to run on macOS
  hack/lib.sh
  hack/local/run-kubermatic-kind.sh
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#8198 Fix reconciliation of Konnectivity resources
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/deployment.go
  pkg/resources/konnectivity/seedagent.go
  pkg/resources/konnectivity/sidecar.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8200 new endpoint to list external cluster machine deployments
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/external_cluster/node.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/project/list_external_cluster_machine_deployments_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/list_external_cluster_machine_deployments_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/utils/apiclient/models/external_cluster_machine_deployment.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#8207 upgrade eks cluster master version
  pkg/apis/kubermatic/v1/external_cluster.go
  pkg/crd/kubermatic/v1/external_cluster.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/provider/cloud/aws/provider.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8209 Add embik (Marvin Beckers) to SIG cluster-management OWNERS alias
  OWNERS_ALIASES
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8210 ensure clusters are deleted after CCM migration e2e tests
  hack/run-ccm-migration-e2e-test-in-kind.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8021 Extend backups for destinations
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_etcdbackupconfigs.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.seed.yaml
  pkg/apis/kubermatic/v1/configuration.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/etcd_backup_config.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/crd/kubermatic/v1/etcd_backup_config.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/install/crdmigration/clones.go
  pkg/test/e2e/utils/apiclient/models/seed_backup_restore_configuration.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8203 Allow registry override on user-ssh-keys-agent ds
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/usersshkeys/daemonset.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8189 HA Prometheus
  hack/ci/setup-mla.sh
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/configmap.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/deployment.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#8130 Get eks nodegroup endpoint
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/node.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#8218 endpoint to get external clusters machine deployment nodes
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/external_cluster/node.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/project/list_external_cluster_machine_deployment_nodes_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/list_external_cluster_machine_deployment_nodes_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8222 endpoint to delete external cluster MD
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/external_cluster/node.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/project/delete_external_cluster_machine_deployment_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/delete_external_cluster_machine_deployment_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8223 Make user cluster Prometheus replicas configurable via API
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/deployment.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/test/e2e/utils/apiclient/models/m_l_a_settings.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, sig/crd, sig/crd/synced

#8228 Backup destinations API for multiple destinations
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/api/v2/types.go
  pkg/handler/v1/admin/seed.go
  pkg/handler/v1/admin/seed_test.go
  pkg/handler/v2/etcdbackupconfig/etcdbackupconfig.go
  pkg/handler/v2/etcdbackupconfig/etcdbackupconfig_test.go
  pkg/test/e2e/utils/apiclient/models/backup_destination.go
  pkg/test/e2e/utils/apiclient/models/etcd_backup_config_spec.go
  pkg/test/e2e/utils/apiclient/models/etcd_backup_restore.go
  pkg/test/e2e/utils/apiclient/models/seed.go
  pkg/test/e2e/utils/apiclient/models/seed_spec.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/api

#8232 Change backup dest credentials type
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/v1/admin/seed_test.go
  pkg/test/e2e/utils/apiclient/models/backup_destination.go
  pkg/test/e2e/utils/apiclient/models/secret_reference.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd, sig/crd/synced

#8202 Pull dependencies for helm charts during installation.
  pkg/install/helm/cli.go
  pkg/install/helm/interface.go
  pkg/install/helm/types.go
  pkg/install/util/helm.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#8234 Fix variable name for certificate secrets in minio chart
  charts/minio/Chart.yaml
  charts/minio/templates/deployment.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#8237 Make minio.certificateSecret optional by not setting it by default
  charts/minio/Chart.yaml
  charts/minio/values.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#8233 Bump machine controller 1.36.2
  go.mod
  go.sum
  pkg/resources/cloudconfig/configmap.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#8104 Handle charts with dependencies in CI
  hack/README.md
  hack/ci/README.md
  hack/ci/fetch-chart-dependencies.sh
  hack/test-chart-rendering.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8224 GET and PATCH eks machinedeployments
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/node.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/project/get_external_cluster_machine_deployment_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/get_external_cluster_machine_deployment_responses.go
  pkg/test/e2e/utils/apiclient/client/project/patch_external_cluster_machine_deployments_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/patch_external_cluster_machine_deployments_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#8231 Fix reconciliation of Konnectivity Agent in user cluster
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/deployment.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#8211 handle Openstack project auth variable
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.addondata.go.txt
  hack/ci/run-api-e2e.sh
  hack/local/run-api-e2e.sh
  pkg/api/v1/types.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/preset.go
  pkg/crd/kubermatic/v1/preset_test.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v1/provider/openstack.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/install/crdmigration/clones.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/openstack/provider_test.go
  pkg/provider/kubernetes/credentials.go
  pkg/provider/kubernetes/preset.go
  pkg/provider/kubernetes/preset_test.go
  pkg/resources/cloudconfig/configmap.go
  pkg/resources/credentials.go
  pkg/resources/credentials_test.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/resources.go
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/globalsecretkeyselector_helper.go
  pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_availability_zones_parameters.go
  pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_networks_parameters.go
  pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_security_groups_parameters.go
  pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_sizes_parameters.go
  pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_subnets_parameters.go
  pkg/test/e2e/utils/apiclient/models/openstack_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/public_openstack_cloud_spec.go
  pkg/validation/cluster.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd, sig/crd/synced

#8239 new endpoint endpoint to list External MD Metrics
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/node.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/project/list_external_cluster_machine_deployment_metrics_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/list_external_cluster_machine_deployment_metrics_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#8242 Credentials for backup destinations
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/options.go
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/routing.go
  pkg/handler/test/hack/hack.go
  pkg/handler/test/helper.go
  pkg/handler/v2/backupcredentials/backupcredentials.go
  pkg/handler/v2/backupcredentials/backupcredentials_test.go
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/routing.go
  pkg/provider/kubernetes/seed.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/models/backup_credentials.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/api

#8190 [release/v2.18] Update Kubernetes Dashboard to v2.4.0 (#8172)
  pkg/controller/user-cluster-controller-manager/resources/resources/kubernetes-dashboard/deployment.go
  pkg/resources/kubernetes-dashboard/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.19.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kubernetes-dashboard.yaml
Labels: ok-to-test, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#8236 UserCluster MLA e2e test for Loki ruler
  hack/ci/setup-mla.sh
  pkg/controller/seed-controller-manager/mla/alertmanager_controller.go
  pkg/controller/seed-controller-manager/mla/alertmanager_controller_test.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller_test.go
  pkg/test/e2e/mla/mla_test.go
  pkg/test/e2e/utils/client.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#8044 Use upstream promtail Helm chart
  charts/logging/promtail/.helmignore
  charts/logging/promtail/Chart.yaml
  charts/logging/promtail/requirements.lock
  charts/logging/promtail/templates/_helpers.tpl
  charts/logging/promtail/templates/clusterrole.yaml
  charts/logging/promtail/templates/clusterrolebinding.yaml
  charts/logging/promtail/templates/configmap.yaml
  charts/logging/promtail/templates/daemonset.yaml
  charts/logging/promtail/templates/role.yaml
  charts/logging/promtail/templates/rolebinding.yaml
  charts/logging/promtail/test/default.yaml
  charts/logging/promtail/test/default.yaml.out
  charts/logging/promtail/test/kubermatic.example.ce.yaml
  charts/logging/promtail/test/kubermatic.example.ce.yaml.out
  charts/logging/promtail/test/kubermatic.example.ee.yaml
  charts/logging/promtail/test/kubermatic.example.ee.yaml.out
  charts/logging/promtail/test/test.sh
  charts/logging/promtail/values.yaml
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#8168 [release/v2.18] Add support to update Preset requiredEmails/EmailDomain via REST-API
  pkg/handler/v2/preset/preset.go
  pkg/handler/v2/preset/preset_test.go
  pkg/provider/kubernetes/preset.go
Labels: size/L, ok-to-test, lgtm, approved, release-note, dco-signoff: yes, sig/api

#8245 Upgrade eks nodegroup version
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/node.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#8244 Create AKS external cluster
  .codespell.exclude
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/crd/kubermatic/v1/external_cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/provider/kubernetes/external_cluster.go
  pkg/provider/kubernetes/external_cluster_test.go
  pkg/resources/resources.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/external_cluster_cloud_spec.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8250 patch GKE machine deployment version and size
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/external_cluster/node.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8262 Add additionalPrinterColumns to new API
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_allowedregistries.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplateinstances.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_etcdbackupconfigs.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_etcdrestores.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_projects.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_rulegroups.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_userprojectbindings.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_users.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_usersshkeys.yaml
  hack/ci/testdata/crdmigration/master/01-setup.yaml
  hack/ci/testdata/crdmigration/master/04-project-contents.yaml
  hack/ci/testdata/crdmigration/seed/04-project-contents.yaml
  hack/ci/testdata/crdmigration/seed/06-cluster-contents.yaml
  pkg/apis/kubermatic/v1/allowed_registry.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/cluster_template_instance.go
  pkg/apis/kubermatic/v1/cluster_templates.go
  pkg/apis/kubermatic/v1/etcd_backup_config.go
  pkg/apis/kubermatic/v1/etcd_restore.go
  pkg/apis/kubermatic/v1/external_cluster.go
  pkg/apis/kubermatic/v1/project.go
  pkg/apis/kubermatic/v1/rulegroup.go
  pkg/apis/kubermatic/v1/sshkeys.go
  pkg/apis/kubermatic/v1/user.go
  pkg/apis/kubermatic/v1/user_project_binding.go
  pkg/install/crdmigration/clones.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#8264 Add apiserver network policy to allow traffic to OIDC issuer
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/apiserver/networkpolicy.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#8274 [release/v2.18] Add apiserver network policy to allow traffic to OIDC issuer
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/apiserver/networkpolicy.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#8273 Fetch chart dependencies on dev before installing logging and monitoring
  hack/ci/deploy.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#8265 fix GKE get upgrades method
  pkg/handler/common/provider/gcp.go
  pkg/handler/v2/external_cluster/upgrade.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#8280 Add PratikDeoghare to sig-networking
  OWNERS_ALIASES
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8065 Support TLS peer connections and live migration in etcd-launcher
  cmd/etcd-launcher/main.go
  cmd/image-loader/main.go
  hack/ci/run-etcd-launcher-tests.sh
  hack/ci/setup-kubermatic-backups-in-kind.sh
  hack/ci/testdata/backup_s3_creds.yaml
  hack/ci/testdata/kubermatic_backup.yaml
  hack/ci/testdata/minio.cnf
  hack/ci/testdata/minio_bucket_job.yaml
  hack/ci/testdata/seed_backup.yaml
  pkg/controller/seed-controller-manager/kubernetes/health.go
  pkg/controller/seed-controller-manager/kubernetes/launching.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/etcd/etcdservices.go
  pkg/resources/etcd/pdb.go
  pkg/resources/etcd/statefulset.go
  pkg/resources/resources.go
  pkg/resources/test/fixtures/service-aws-1.20.0-etcd.yaml
  pkg/resources/test/fixtures/service-aws-1.21.0-etcd.yaml
  pkg/resources/test/fixtures/service-aws-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/service-azure-1.20.0-etcd.yaml
  pkg/resources/test/fixtures/service-azure-1.21.0-etcd.yaml
  pkg/resources/test/fixtures/service-azure-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/service-bringyourown-1.20.0-etcd.yaml
  pkg/resources/test/fixtures/service-bringyourown-1.21.0-etcd.yaml
  pkg/resources/test/fixtures/service-bringyourown-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/service-digitalocean-1.20.0-etcd.yaml
  pkg/resources/test/fixtures/service-digitalocean-1.21.0-etcd.yaml
  pkg/resources/test/fixtures/service-digitalocean-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/service-openstack-1.20.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/service-openstack-1.20.0-etcd.yaml
  pkg/resources/test/fixtures/service-openstack-1.21.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/service-openstack-1.21.0-etcd.yaml
  pkg/resources/test/fixtures/service-openstack-1.22.1-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/service-openstack-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/service-vsphere-1.20.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/service-vsphere-1.20.0-etcd.yaml
  pkg/resources/test/fixtures/service-vsphere-1.21.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/service-vsphere-1.21.0-etcd.yaml
  pkg/resources/test/fixtures/service-vsphere-1.22.1-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/service-vsphere-1.22.1-etcd.yaml
  pkg/resources/test/load_files_test.go
  pkg/test/e2e/etcd-launcher/etcd_test.go
  pkg/webhook/cluster/validation/validation.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8286 Create AKS Kubeconfig secret
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/apis/kubermatic/v1/external_cluster.go
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/crd/kubermatic/v1/external_cluster.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/provider/cloud/azure/provider.go
  pkg/resources/credentials.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_cloud_spec.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8277 Use upstream chart for ingress-nginx
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/requirements.lock
  charts/nginx-ingress-controller/templates/clusterrole.yaml
  charts/nginx-ingress-controller/templates/clusterrolebinding.yaml
  charts/nginx-ingress-controller/templates/configmaps.yaml
  charts/nginx-ingress-controller/templates/nginx-ds-dep.yaml
  charts/nginx-ingress-controller/templates/role.yaml
  charts/nginx-ingress-controller/templates/rolebinding.yaml
  charts/nginx-ingress-controller/templates/service.yaml
  charts/nginx-ingress-controller/test/default.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/test.sh
  charts/nginx-ingress-controller/test/values.example.ce.yaml
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
  charts/nginx-ingress-controller/values.yaml
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#8296 ingress-nginx: Disable validation webhook
  charts/nginx-ingress-controller/.helmignore
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
  charts/nginx-ingress-controller/values.yaml
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#8270 Update metering image and remove old annotations/port settings
  pkg/ee/metering/deployment.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes

#8284 new endpoint to get external cluster machine deployments upgrades
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/provider/gcp.go
  pkg/handler/v2/external_cluster/node.go
  pkg/handler/v2/external_cluster/upgrade.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/project/get_external_cluster_machine_deployment_upgrades_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/get_external_cluster_machine_deployment_upgrades_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8297 Fix OpenStack cloud initialization for subnets that are already attached to router
  pkg/provider/cloud/aws/role_test.go
  pkg/provider/cloud/openstack/provider.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#8268 [release/v2.18] Update to Kubernetes v1.20.13, v1.21.7, v1.22.4
  .prow.yaml
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/updates.yaml
  charts/kubermatic/static/master/versions.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/addon/template_test.go
  pkg/controller/operator/common/defaults.go
  pkg/controller/seed-controller-manager/backup/backup_controller_test.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller_test.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/test/e2e/ccm-migration/ccm_migration_suite_test.go
  pkg/test/e2e/expose-strategy/expose_strategy_suite_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#8292 sync old pkg/crd/kubermatic to new pkg/apis/kubermatic
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/external_cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/install/crdmigration/clones.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#8288 fixes the user-deletion issue
  pkg/controller/master-controller-manager/user-synchronizer/controller.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#8294 Fix escaping of dots in user cluster dashboard
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/dashboards/kubermatic/user-clusters.json
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#8302 Extend DNS lookup timeout in apiserver network policy creator
  pkg/resources/apiserver/networkpolicy.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#8307 Etcd restore CRD support multiple destinations
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_etcdrestores.yaml
  pkg/apis/kubermatic/v1/etcd_restore.go
  pkg/crd/kubermatic/v1/etcd_restore.go
  pkg/install/crdmigration/clones.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd, sig/crd/synced

#8314 add missing map initialization
  pkg/controller/seed-controller-manager/mla/ratelimit_cortex_controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#8317 [release/v2.18] Fix OpenStack cloud initialization for subnets created ahead.
  pkg/provider/cloud/openstack/provider.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#8319 Fix IDP icons in Dex theme
  charts/oauth/Chart.yaml
  charts/oauth/theme/styles.css
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#8318 [release v2.17] Fix OpenStack cloud initialization for subnets created ahead.
  pkg/provider/cloud/openstack/provider.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#8310 create external cluster machine deployment
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/external_cluster/node.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/project/create_external_cluster_machine_deployment_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/create_external_cluster_machine_deployment_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/utils/apiclient/models/external_cluster_machine_deployment.go
  pkg/test/e2e/utils/apiclient/models/external_cluster_machine_deployment_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_machine_deployment_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_node_config.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_node_management.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_node_pool_autoscaling.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8316 etcd restore controller support for multiple destinations
  cmd/etcd-launcher/main.go
  cmd/seed-controller-manager/controllers.go
  pkg/controller/seed-controller-manager/etcdrestore/etcd_restore_controller.go
  pkg/resources/resources.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#8306 Reduce scope for user-ssh-keys-agent Role to name of secret
  pkg/controller/user-cluster-controller-manager/resources/resources/usersshkeys/serviceaccount.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#8291 Add EventRateLimit admission plugin configuration
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/common/cluster.go
  pkg/install/crdmigration/clones.go
  pkg/resources/apiserver/admission-control.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/resources.go
  pkg/test/e2e/utils/apiclient/models/cluster_spec.go
  pkg/test/e2e/utils/apiclient/models/event_rate_limit_config.go
  pkg/test/e2e/utils/apiclient/models/event_rate_limit_config_item.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd, sig/crd/synced

#8267 UserCluster MLA e2e test rate limit
  pkg/controller/seed-controller-manager/mla/ratelimit_cortex_controller.go
  pkg/controller/seed-controller-manager/mla/ratelimit_cortex_controller_test.go
  pkg/test/e2e/mla/mla_test.go
  pkg/test/e2e/utils/client.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#8325 Remove jiachengxu from OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8330 add presets for GKE, AKS and EKS providers
  pkg/crd/kubermatic/v1/preset.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#8329 Provide custom cache to user-ssh-keys-agent manager to fix cache RBAC issues
  cmd/user-ssh-keys-agent/main.go
  pkg/controller/usersshkeysagent/usersshkeys_controller.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8038 Add support for AWS AssumeRole in user clusters
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.addondata.go.txt
  pkg/api/v1/types.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/preset.go
  pkg/handler/common/provider/aws.go
  pkg/handler/v1/provider/aws.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/provider/aws.go
  pkg/install/crdmigration/clones.go
  pkg/machine/convert.go
  pkg/provider/cloud/aws/api.go
  pkg/provider/cloud/aws/client.go
  pkg/provider/cloud/aws/provider.go
  pkg/provider/cloud/aws/util_test.go
  pkg/provider/kubernetes/preset.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/controllermanager/deployment.go
  pkg/resources/credentials.go
  pkg/resources/machine/common.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.20.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/load_files_test.go
  pkg/test/e2e/utils/apiclient/client/aws/list_a_w_s_security_groups_parameters.go
  pkg/test/e2e/utils/apiclient/client/aws/list_a_w_s_subnets_parameters.go
  pkg/test/e2e/utils/apiclient/client/aws/list_a_w_s_v_p_c_s_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_clusters_parameters.go
  pkg/test/e2e/utils/apiclient/models/a_w_s_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/a_w_s_node_spec.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8321 Support multi-arch builds for kubeletdnat-controller
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  hack/release-docker-images.sh
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes
