Repository kubermatic/kubermatic, pull requests merged in 2021-03, with the labels that each got.

#6605 add GPU support for Azure provider
  cmd/kubermatic-api/swagger.json
  go.mod
  go.sum
  pkg/api/v1/types.go
  pkg/handler/common/provider/azure.go
  pkg/handler/v1/provider/azure_test.go
  pkg/test/e2e/utils/apiclient/models/azure_size.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/M

#6616 update controller-runtime to 0.8.2
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6588 Add support for Hetzner CCM
  cmd/conformance-tests/custom_tests.go
  cmd/conformance-tests/runner.go
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.seed.yaml
  hack/ci/testdata/seed.yaml
  hack/run-user-cluster-controller-manager.sh
  pkg/api/v1/types.go
  pkg/api/v1/types_test.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller_test.go
  pkg/controller/seed-controller-manager/kubernetes/pending.go
  pkg/controller/seed-controller-manager/kubernetes/resources_test.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/crd/kubermatic/v1/preset.go
  pkg/machine/convert.go
  pkg/provider/cloud/hetzner/provider.go
  pkg/provider/kubernetes/preset.go
  pkg/provider/kubernetes/preset_test.go
  pkg/resources/cloudcontroller/deployment.go
  pkg/resources/cloudcontroller/hetzner.go
  pkg/resources/cloudcontroller/openstack.go
  pkg/resources/cloudcontroller/util.go
  pkg/resources/data.go
  pkg/resources/machine/common.go
  pkg/test/e2e/utils/apiclient/models/datacenter_spec_hetzner.go
  pkg/test/e2e/utils/apiclient/models/hetzner_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/hetzner_node_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/XL

#6615 Cleanup CSI addon, update Hetzner CSI
  addons/csi/hetzner/hcloud-csi.yaml
  addons/csi/openstack/controllerplugin-rbac.yaml
  addons/csi/openstack/controllerplugin.yaml
  addons/csi/openstack/driver.yaml
  addons/csi/openstack/nodeplugin-rbac.yaml
  addons/csi/openstack/nodeplugin.yaml
  addons/default-storage-class/storage-class.yaml
  cmd/conformance-tests/runner.go
  pkg/addon/template.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/XL

#6619 [release/v2.16] Add support for Hetzner CCM (#6588)
  cmd/conformance-tests/custom_tests.go
  cmd/conformance-tests/runner.go
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.seed.yaml
  hack/ci/testdata/seed.yaml
  hack/run-user-cluster-controller-manager.sh
  pkg/api/v1/types.go
  pkg/api/v1/types_test.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller_test.go
  pkg/controller/seed-controller-manager/kubernetes/pending.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/crd/kubermatic/v1/preset.go
  pkg/machine/convert.go
  pkg/provider/cloud/hetzner/provider.go
  pkg/provider/kubernetes/preset.go
  pkg/provider/kubernetes/preset_test.go
  pkg/resources/cloudcontroller/deployment.go
  pkg/resources/cloudcontroller/hetzner.go
  pkg/resources/cloudcontroller/openstack.go
  pkg/resources/cloudcontroller/util.go
  pkg/resources/data.go
  pkg/resources/machine/common.go
  pkg/test/e2e/utils/apiclient/models/datacenter_spec_hetzner.go
  pkg/test/e2e/utils/apiclient/models/hetzner_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/hetzner_node_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/XL

#6622 Fix typo in HCloud CSI driver
  addons/csi/hetzner/hcloud-csi.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/XS

#6620 [release/v2.16] Update Hetzner CSI (#6615)
  addons/default-storage-class/aws.yaml
  addons/default-storage-class/azure.yaml
  addons/default-storage-class/gcp.yaml
  addons/default-storage-class/hetzner.yaml
  addons/default-storage-class/openstack.yaml
  addons/default-storage-class/vsphere.yaml
  cmd/conformance-tests/runner.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/L

#6621 shfmt
  .prow.yaml
  Makefile
  hack/changelog-gen.sh
  hack/ci/deploy-ci-kubermatic-io.sh
  hack/ci/deploy-dev-asia.sh
  hack/ci/deploy-dev.sh
  hack/ci/deploy-offline.sh
  hack/ci/deploy-run-2-lab-alpha.sh
  hack/ci/deploy-run-lab-stable.sh
  hack/ci/deploy.sh
  hack/ci/download-gocache.sh
  hack/ci/github-release.sh
  hack/ci/run-api-e2e.sh
  hack/ci/run-etcd-launcher-tests.sh
  hack/ci/run-offline-test.sh
  hack/ci/setup-kind-cluster.sh
  hack/ci/setup-kubermatic-in-kind.sh
  hack/ci/setup-legacy-kubermatic-in-kind.sh
  hack/ci/upload-gocache.sh
  hack/coverage.sh
  hack/images/startup-script/manage-startup-script.sh
  hack/lib.sh
  hack/meta.sh
  hack/release-docker-images.sh
  hack/retag-images.sh
  hack/run-conformance-tests.sh
  hack/run-machine-controller.sh
  hack/run-master-controller-manager.sh
  hack/run-nodeport-proxy-e2e-test-in-kind.sh
  hack/run-user-cluster-controller-manager.sh
  hack/update-fixtures.sh
  hack/update-prometheus-rules.sh
  hack/update-velero-crds.sh
  hack/verify-prometheus-rules.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/XL

#6625 Do not enable external CCM if hetzner dc is improperly configured
  pkg/resources/cloudcontroller/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/XS

#6629 2.16.3 changelog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6627 Move webhook related files to the pkg/webhook package
  cmd/master-controller-manager/main.go
  cmd/master-controller-manager/wrappers_ce.go
  cmd/master-controller-manager/wrappers_ee.go
  cmd/seed-controller-manager/main.go
  cmd/seed-controller-manager/options.go
  cmd/seed-controller-manager/wrappers_ce.go
  cmd/seed-controller-manager/wrappers_ee.go
  pkg/webhook/cluster/handler.go
  pkg/webhook/cluster/handler_test.go
  pkg/webhook/flags.go
  pkg/webhook/seed/builder.go
  pkg/webhook/seed/builder_test.go
  pkg/webhook/seed/handler.go
  pkg/webhook/seed/handler_test.go
  pkg/webhook/seed/validator.go
  pkg/webhook/seed/validator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6635 Implement the MutatingWebhook for the Cluster objects
  cmd/seed-controller-manager/main.go
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
  pkg/webhook/cluster/validation/validation.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6638 Make operator deploy the MutatingWebhookConfig for Clusters
  cmd/seed-controller-manager/main.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/operator/seed/resources/kubermatic/admission.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/M

#6639 Fix operator failing to reconcile admission configs
  pkg/controller/operator/seed/resources/kubermatic/admission.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XS

#6640 Fix operator failing to reconcile MutatingWebhookConfiguration
  pkg/controller/operator/seed/resources/kubermatic/admission.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/XS

#6612 Add openstack flavor restriction
  cmd/example-yaml-generator/main.go
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.seed.yaml
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/common/provider/openstack.go
  pkg/handler/v1/provider/openstack_test.go
  pkg/test/e2e/utils/apiclient/models/datacenter_spec_openstack.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, sig/api, sig/cluster-management, size/M

#6641 Leader election config in ComponentSettings
  cmd/seed-controller-manager/controllers.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/resources/controllermanager/deployment.go
  pkg/resources/scheduler/deployment.go
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
  pkg/webhook/cluster/validation/validation.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/L

#6648 update Dex to 2.27.0
  charts/oauth/Chart.yaml
  charts/oauth/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/XS

#6649 update Minio to 2021-03-04
  charts/minio/Chart.yaml
  charts/minio/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/XS

#6650 update Loki to 2.1, use boltdb-shipper starting June 1st
  charts/logging/loki/Chart.yaml
  charts/logging/loki/values.yaml
  charts/logging/promtail/Chart.yaml
  charts/logging/promtail/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/S

#6651 update nginx-ingress-controller to 0.44.0
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/templates/service.yaml
  charts/nginx-ingress-controller/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/S

#6652 update blackbox-exporter to 0.18
  charts/monitoring/blackbox-exporter/Chart.yaml
  charts/monitoring/blackbox-exporter/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/XS

#6653 update node-exporter to 1.1.2
  charts/monitoring/node-exporter/Chart.yaml
  charts/monitoring/node-exporter/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/XS

#6654 update Karma to 0.80
  charts/monitoring/karma/Chart.yaml
  charts/monitoring/karma/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/XS

#6656 remove unused deprecated certs chart
  charts/certs/Chart.yaml
  charts/certs/templates/acme-challenge-ingress.yaml
  charts/certs/templates/certificates.yaml
  charts/certs/templates/dns-secret.yaml
  charts/certs/templates/issuer.yaml
  charts/certs/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/L

#6657 update oauth2-proxy to 7.0.1
  charts/iap/Chart.yaml
  charts/iap/templates/certificates.yaml
  charts/iap/templates/ingresses.yaml
  charts/iap/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/M

#6659 fix Dex image repository
  charts/oauth/Chart.yaml
  charts/oauth/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/XS

#6646 Fix the nodeport-proxy role to have permissions on endpoints
  pkg/resources/nodeportproxy/nodeportproxy.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XS

#6647 update Prometheus to 0.25.0
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/values.yaml
  pkg/resources/prometheus/statefulset.go
  pkg/resources/test/fixtures/statefulset-aws-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.19.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.19.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.19.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.19.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.19.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.19.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.20.0-prometheus.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, sig/cluster-management, size/M

#6661 fix Loki config
  charts/logging/loki/Chart.yaml
  charts/logging/loki/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/S

#6662 fix kube-rbac-proxy
  charts/monitoring/node-exporter/Chart.yaml
  charts/monitoring/node-exporter/templates/daemonset.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/XS

#6655 update Grafana to 7.4.3
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/values.yaml
  hack/images/grafana-plugins/Dockerfile
  hack/images/grafana-plugins/release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/S

#6660 fix license check, update to wwhrd 0.4
  .prow.yaml
  .wwhrd.yml
  hack/images/util/Dockerfile
  hack/images/wwhrd/Dockerfile
  hack/images/wwhrd/release.sh
  hack/lib.sh
  hack/verify-licenses.sh
Labels: approved, dco-signoff: yes, lgtm, lifecycle/blocked, release-note-none, size/M

#6668 Make the externalCloudProvider feature gate immutable (impossible to disable)
  pkg/webhook/cluster/validation/validation.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#6667 add registry_mirrors to seed node settings
  cmd/example-yaml-generator/main.go
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.seed.yaml
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/test/helper.go
  pkg/handler/v1/admin/seed_test.go
  pkg/handler/v1/dc/datacenter_test.go
  pkg/provider/conversions_test.go
  pkg/resources/machinecontroller/deployment.go
  pkg/test/e2e/utils/apiclient/models/node_settings.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/M

#6664 [release/v2.15] Leader election config in ComponentSettings (#6641)
  cmd/seed-controller-manager/controllers.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/resources/controllermanager/deployment.go
  pkg/resources/scheduler/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#6673 remove CE binaries before building EE binaries, or else Make does nothing
  hack/ci/github-release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XS

#6672 2.16.4, 2.16.5 and 2.15.8 changelogs
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6679 add endpoint to create main service account
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/swagger.json
  pkg/handler/test/helper.go
  pkg/handler/v1/project/project.go
  pkg/handler/v1/project/project_test.go
  pkg/handler/v1/serviceaccount/sa.go
  pkg/handler/v1/serviceaccount/sa_test.go
  pkg/handler/v1/serviceaccount/token_test.go
  pkg/handler/v1/user/user_test.go
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/serviceaccount/sa.go
  pkg/handler/v2/serviceaccount/sa_test.go
  pkg/provider/kubernetes/member_test.go
  pkg/provider/kubernetes/sa.go
  pkg/provider/kubernetes/sa_test.go
  pkg/provider/kubernetes/sa_token_test.go
  pkg/provider/kubernetes/util_test.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/kubermatic_api_client.go
  pkg/test/e2e/utils/apiclient/client/mainserviceaccounts/create_main_service_account_parameters.go
  pkg/test/e2e/utils/apiclient/client/mainserviceaccounts/create_main_service_account_responses.go
  pkg/test/e2e/utils/apiclient/client/mainserviceaccounts/mainserviceaccounts_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/XXL

#6665 [release/v2.14] Leader election config in ComponentSettings (#6641)
  api/cmd/seed-controller-manager/controllers.go
  api/pkg/crd/kubermatic/v1/cluster.go
  api/pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  api/pkg/resources/controllermanager/deployment.go
  api/pkg/resources/scheduler/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#6684 Update to Go 1.16.1
  .prow.yaml
  Makefile
  go.sum
  hack/images/integration-tests/Dockerfile
  hack/images/integration-tests/release.sh
  hack/images/wwhrd/Dockerfile
  hack/images/wwhrd/release.sh
  hack/run-conformance-tests.sh
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-chart.sh
  hack/update-swagger.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#6686 add 2.14.11 changelog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6693 add 2.15.9 changelog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6687 add endpoint to list main service accounts
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/serviceaccount/sa.go
  pkg/handler/v2/serviceaccount/sa_test.go
  pkg/provider/kubernetes/sa.go
  pkg/test/e2e/utils/apiclient/client/mainserviceaccounts/list_main_service_accounts_parameters.go
  pkg/test/e2e/utils/apiclient/client/mainserviceaccounts/list_main_service_accounts_responses.go
  pkg/test/e2e/utils/apiclient/client/mainserviceaccounts/mainserviceaccounts_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/L

#6698 [release/v2.16] Fix operator failing to reconcile admission configs (#6639)
  pkg/controller/operator/seed/resources/kubermatic/admission.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XS

#6701 update Velero to 1.5.3
  charts/backup/velero/Chart.yaml
  charts/backup/velero/crd/backups.yaml
  charts/backup/velero/crd/backupstoragelocations.yaml
  charts/backup/velero/crd/deletebackuprequests.yaml
  charts/backup/velero/crd/downloadrequests.yaml
  charts/backup/velero/crd/podvolumebackups.yaml
  charts/backup/velero/crd/podvolumerestores.yaml
  charts/backup/velero/crd/resticrepositories.yaml
  charts/backup/velero/crd/restores.yaml
  charts/backup/velero/crd/schedules.yaml
  charts/backup/velero/crd/serverstatusrequests.yaml
  charts/backup/velero/crd/volumesnapshotlocations.yaml
  charts/backup/velero/values.yaml
  hack/update-velero-crds.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/M

#6703 Add exception to the github.com/ajeddeloh/go-json
  .wwhrd.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6634 extend SA controller for new SA type
  pkg/controller/master-controller-manager/service-account/service_account_binding_controller.go
  pkg/controller/master-controller-manager/service-account/service_account_binding_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/security, size/L

#6709 decreased default opa webhook timeout from 10 to 3 sec
  cmd/user-cluster-controller-manager/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#6695 Update machine-controller to v1.27.1
  docs/zz_generated.seed.yaml
  go.mod
  go.sum
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/machinecontroller/webhook.go
  pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/L

#6617 Add User-Cluster MLA (Monitoring, Logging, and Alerting) Proposal
  docs/proposals/images/mla-alertmanager.png
  docs/proposals/images/mla-centralized.png
  docs/proposals/images/mla-cortex.png
  docs/proposals/images/mla-distributed.png
  docs/proposals/images/mla-loki.png
  docs/proposals/user-cluster-mla.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6700 Add V2 endpoint to edit main service accounts
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/serviceaccount/sa.go
  pkg/handler/v2/serviceaccount/sa_test.go
  pkg/provider/kubernetes/sa.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/mainserviceaccounts/mainserviceaccounts_client.go
  pkg/test/e2e/utils/apiclient/client/mainserviceaccounts/update_main_service_account_parameters.go
  pkg/test/e2e/utils/apiclient/client/mainserviceaccounts/update_main_service_account_responses.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/XL

#6708 Implement Project-Sync Controller
  cmd/master-controller-manager/controllers.go
  codegen/reconcile/main.go
  pkg/api/v1/types.go
  pkg/controller/master-controller-manager/project-sync/OWNERS
  pkg/controller/master-controller-manager/project-sync/controller.go
  pkg/controller/master-controller-manager/project-sync/controller_test.go
  pkg/controller/master-controller-manager/project-sync/doc.go
  pkg/controller/master-controller-manager/project-sync/resources.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, sig/cluster-management, size/L

#6726 support aws spot instancee in the KKP API
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/api/v1/types_test.go
  pkg/machine/convert.go
  pkg/resources/machine/common.go
  pkg/test/e2e/utils/apiclient/models/a_w_s_node_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/S

#6682 Add Kubernetes 1.19.8
  .prow.yaml
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/versions.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  hack/ci/setup-kubermatic-in-kind.sh
  hack/ci/testdata/kubermatic.yaml
  hack/lib.sh
  pkg/controller/operator/common/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/S

#6717 add endpoint to delete main service account
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/serviceaccount/sa.go
  pkg/handler/v2/serviceaccount/sa_test.go
  pkg/provider/kubernetes/sa.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/mainserviceaccounts/delete_main_service_account_parameters.go
  pkg/test/e2e/utils/apiclient/client/mainserviceaccounts/delete_main_service_account_responses.go
  pkg/test/e2e/utils/apiclient/client/mainserviceaccounts/mainserviceaccounts_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/XL

#6732 Fix broken s3 storeuploader and broken cluster creation
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/cleanup-container.yaml
  charts/kubermatic/static/store-container.yaml
  cmd/s3-storeuploader/README.md
  cmd/s3-storeuploader/main.go
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/S

#6734 endpoint to add token for main SA
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/serviceaccount/token.go
  pkg/handler/v2/serviceaccount/token_test.go
  pkg/provider/kubernetes/sa_token.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/tokens/add_token_to_main_service_account_parameters.go
  pkg/test/e2e/utils/apiclient/client/tokens/add_token_to_main_service_account_responses.go
  pkg/test/e2e/utils/apiclient/client/tokens/tokens_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/XL

#6741 [release/v2.16] fix cert-manager validating webhook
  charts/cert-manager/Chart.yaml
  charts/cert-manager/templates/webhook-validating-webhook.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/XS

#6743 [release/v2.14] fix cert-manager validating webhook
  config/cert-manager/Chart.yaml
  config/cert-manager/templates/webhook-validating-webhook.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#6744 add 2.14.12, 2.15.10 and 2.16.6 changelogs
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6731 Add Multus-CNI to accessible addons
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/accessible-addons.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/XS

#6706 Gatekeeper upgrade to 3.1.3
  pkg/controller/seed-controller-manager/kubernetes/health.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/crds.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/rbac.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/removal.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/secret.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/service.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/webhook.go
  pkg/resources/gatekeeper/rbac.go
  pkg/resources/gatekeeper/removal.go
  pkg/resources/resources.go
  pkg/resources/usercluster/rbac.go
  pkg/test/e2e/opa/opa_test.go
  pkg/test/e2e/utils/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XL

#6740 list main service account tokens
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/serviceaccount/sa.go
  pkg/handler/v2/serviceaccount/sa_test.go
  pkg/handler/v2/serviceaccount/token.go
  pkg/handler/v2/serviceaccount/token_test.go
  pkg/provider/kubernetes/sa.go
  pkg/test/e2e/utils/apiclient/client/tokens/list_main_service_account_tokens_parameters.go
  pkg/test/e2e/utils/apiclient/client/tokens/list_main_service_account_tokens_responses.go
  pkg/test/e2e/utils/apiclient/client/tokens/tokens_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/XL

#6718 Add CRD namespace migration draft proposal
  docs/proposals/crd-namespace-migration.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6754 [release/v2.16] Implement Project-Sync Controller
  cmd/master-controller-manager/controllers.go
  codegen/reconcile/main.go
  pkg/api/v1/types.go
  pkg/controller/master-controller-manager/project-sync/OWNERS
  pkg/controller/master-controller-manager/project-sync/controller.go
  pkg/controller/master-controller-manager/project-sync/controller_test.go
  pkg/controller/master-controller-manager/project-sync/doc.go
  pkg/controller/master-controller-manager/project-sync/resources.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/L

#6747 Add MLA controller scaffolding
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/options.go
  pkg/controller/seed-controller-manager/mla/doc.go
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/features/features.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/M

#6756 Fixed clusters clusterrolebinding naming and added cleanup
  pkg/api/v1/types.go
  pkg/clusterdeletion/clusterrolebindings.go
  pkg/clusterdeletion/deletion.go
  pkg/controller/seed-controller-manager/kubernetes/pending.go
  pkg/resources/usercluster/rbac.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, sig/cluster-management, size/M

#6757 added removal of old gatekeeper resources on seed cluster
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/gatekeeper/removal.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/M

#6758 Handle apiextensions/v1 CRDs
  cmd/kubermatic-installer/cmd_deploy.go
  pkg/crd/util/crd.go
  pkg/install/util/crd.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/M

#6760 allow to disable Minio's s3-credentials Secret
  charts/minio/Chart.yaml
  charts/minio/templates/secret-external.yaml
  charts/minio/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/S

#6763 [release/v2.16] allow to disable Minio's s3-credentials Secret (#6760)
  charts/minio/Chart.yaml
  charts/minio/templates/secret-external.yaml
  charts/minio/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/S

#6761 fix test certificate for KKP installer
  pkg/install/stack/kubermatic-master/certmanager.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XS

#6765 2.16.7 changleog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6755 add endpoint to revoke main service account token
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/serviceaccount/token.go
  pkg/handler/v2/serviceaccount/token_test.go
  pkg/provider/kubernetes/sa_token.go
  pkg/test/e2e/utils/apiclient/client/tokens/tokens_client.go
  pkg/test/e2e/utils/apiclient/client/tokens/update_main_service_account_token_parameters.go
  pkg/test/e2e/utils/apiclient/client/tokens/update_main_service_account_token_responses.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/XL

#6739 Update cert-manager to 1.2.0
  .prow.yaml
  charts/cert-manager/Chart.yaml
  charts/cert-manager/crd/cert-manager.crds.yaml
  charts/cert-manager/templates/cainjector-rbac.yaml
  charts/cert-manager/templates/cert-manager-rbac.yaml
  charts/cert-manager/templates/clusterissuer.yaml
  charts/cert-manager/templates/webhook-mutating-webhook.yaml
  charts/cert-manager/templates/webhook-rbac.yaml
  charts/cert-manager/templates/webhook-validating-webhook.yaml
  charts/cert-manager/test/certificate.yaml
  charts/cert-manager/test/test.sh
  charts/cert-manager/values.yaml
  charts/kubermatic/Chart.yaml
  charts/kubermatic/templates/ingress.yaml
  hack/ci/setup-kind-cluster.sh
  hack/ci/test-helm-charts.sh
  hack/lib.sh
  hack/update-cert-manager-crds.sh
  hack/verify-spelling.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-action-required, sig/app-management, sig/cluster-management, size/XXL

#6776 Use GetConfig instead of GetConfigOrDie in seed-controller-manager
  cmd/seed-controller-manager/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6773 Update to kind 0.10
  .prow.yaml
  hack/ci/setup-kind-cluster.sh
  hack/run-nodeport-proxy-e2e-test-in-kind.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/M

#6768 add endpoint to patch main service account token
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/serviceaccount/token.go
  pkg/handler/v2/serviceaccount/token_test.go
  pkg/test/e2e/utils/apiclient/client/tokens/patch_main_service_account_token_parameters.go
  pkg/test/e2e/utils/apiclient/client/tokens/patch_main_service_account_token_responses.go
  pkg/test/e2e/utils/apiclient/client/tokens/tokens_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/XL

#6788 do not require port 8080 to be available to run the installer
  cmd/kubermatic-installer/cmd_deploy.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XS

#6785 Fix CoreDNS upgrade issue
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/controller/user-cluster-controller-manager/resources/resources/core-dns/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6789 endpoint to delete main service account token
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/swagger.json
  pkg/handler/test/helper.go
  pkg/handler/v1/project/project_test.go
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/serviceaccount/token.go
  pkg/handler/v2/serviceaccount/token_test.go
  pkg/provider/kubernetes/member_test.go
  pkg/provider/kubernetes/sa.go
  pkg/test/e2e/api/cluster_rbac_test.go
  pkg/test/e2e/utils/apiclient/client/tokens/delete_main_service_account_token_parameters.go
  pkg/test/e2e/utils/apiclient/client/tokens/delete_main_service_account_token_responses.go
  pkg/test/e2e/utils/apiclient/client/tokens/tokens_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/XL
