Repository kubermatic/kubermatic, pull requests merged in 2021-05, with the labels that each got.

#6972 Put back load test coverage for external CCM
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-openstack-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-openstack-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-openstack-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-openstack-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-openstack-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/load_files_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/XL

#6952 Etcd backups: limit number of simultaneously running delete jobs
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, sig/cluster-management, size/L

#6967 Add Seed level MLA settings
  cmd/kubermatic-api/swagger.json
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/options.go
  docs/zz_generated.seed.yaml
  pkg/api/v1/types.go
  pkg/controller/operator/seed/resources/kubermatic/seed-controller-manager.go
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/v1/admin/seed.go
  pkg/resources/data.go
  pkg/resources/test/fixtures/deployment-aws-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-usercluster-controller.yaml
  pkg/resources/test/load_files_test.go
  pkg/resources/usercluster/deployment.go
  pkg/test/e2e/utils/apiclient/models/seed.go
  pkg/test/e2e/utils/apiclient/models/seed_m_l_a_settings.go
  pkg/test/e2e/utils/apiclient/models/seed_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/L

#6936 Enable HTTPS with mTLS between MLA Gateway and user-cluster MLA components
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/deletion.go
  pkg/controller/seed-controller-manager/mla/resources.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/configmap.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/deletion.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/secret.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/promtail/daemonset.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/promtail/deletion.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/promtail/secret.go
  pkg/resources/data.go
  pkg/resources/resources.go
  pkg/resources/test/fixtures/deployment-aws-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-usercluster-controller.yaml
  pkg/resources/usercluster/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, sig/cluster-management, size/XL

#6979 Verify API server certificate in user cluster Prometheus
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/configmap.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/XS

#6927 filter AWS machine types by architecture
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/common/architecture.go
  pkg/handler/common/provider/aws.go
  pkg/handler/common/provider/aws_test.go
  pkg/handler/v1/provider/aws.go
  pkg/handler/v2/provider/aws.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/aws/list_a_w_s_sizes_no_credentials_v2_parameters.go
  pkg/test/e2e/utils/apiclient/client/aws/list_a_w_s_sizes_parameters.go
  pkg/test/e2e/utils/apiclient/models/a_w_s_size.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, size/L

#6977 Disable conformance tests based on KKP chart-based installation
  .prow.yaml
  charts/kubermatic/Chart.yaml
  hack/ci/README.md
  hack/ci/run-e2e-tests.sh
  hack/ci/setup-legacy-kubermatic-in-kind.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/L

#6991 Fix race in Grafana datasorce reconciler
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/mla.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/M

#6996 Use X-Forwarded-Email header by default in Grafana user controller
  cmd/seed-controller-manager/options.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#7008 Add a GET endpoint to get Seed settings
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/seedsettings/seedsettings.go
  pkg/handler/v2/seedsettings/seedsettings_test.go
  pkg/test/e2e/utils/apiclient/client/seed/get_seed_settings_parameters.go
  pkg/test/e2e/utils/apiclient/client/seed/get_seed_settings_responses.go
  pkg/test/e2e/utils/apiclient/client/seed/seed_client.go
  pkg/test/e2e/utils/apiclient/models/m_l_a.go
  pkg/test/e2e/utils/apiclient/models/seed_settings.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/XL

#7012 Do not assign admin role in Grafana for project owners
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/XS

#7022 Add changelogs for 2.16.9 and 2.15.12
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6942 add rbac for constraints owners,editors,viewers
  pkg/controller/master-controller-manager/rbac/mapper.go
  pkg/controller/master-controller-manager/rbac/rbac_resource_controller.go
  pkg/controller/master-controller-manager/rbac/sync_resource.go
  pkg/controller/master-controller-manager/rbac/sync_resource_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/security, size/XL

#6990 [OpenStack] Fix cluster finalizers race condition
  pkg/controller/seed-controller-manager/cloud/cloud_controller.go
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/controller/seed-controller-manager/kubernetes/pending.go
  pkg/provider/cloud/openstack/helper.go
  pkg/provider/cloud/openstack/internal/testing/fixtures.go
  pkg/provider/cloud/openstack/internal/testing/simulator.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/openstack/provider_test.go
  pkg/provider/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/XXL

#7017 Use grafana orgid header
  go.mod
  go.sum
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/L

#7038 Add sig virtualization to owners
  OWNERS
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6970 Add network configuration for user clusters in API
  cmd/kubermatic-api/swagger.json
  cmd/seed-controller-manager/main.go
  go.mod
  pkg/api/v1/types.go
  pkg/controller/operator/seed/resources/kubermatic/admission.go
  pkg/controller/seed-controller-manager/kubernetes/pending.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/crd/kubermatic/v1/utils.go
  pkg/resources/cluster/cluster.go
  pkg/test/e2e/utils/apiclient/models/cluster_networking_config.go
  pkg/test/e2e/utils/apiclient/models/cluster_spec.go
  pkg/test/e2e/utils/apiclient/models/network_ranges.go
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
  pkg/webhook/cluster/validation/validation.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/XXL

#7016 extend RBAC controller for projectmanagers group
  pkg/controller/master-controller-manager/rbac/mapper.go
  pkg/controller/master-controller-manager/rbac/mapper_test.go
  pkg/controller/master-controller-manager/rbac/sync_project_test.go
  pkg/controller/master-controller-manager/rbac/sync_resource_test.go
  pkg/handler/v1/serviceaccount/sa.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/security, size/XL

#7029 prevent null node size for providers
  pkg/handler/common/provider/digitalocean.go
  pkg/handler/common/provider/hetzner.go
  pkg/handler/common/provider/openstack.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, size/S

#7032 Multiarch image for user-ssh-keys-agent
  cmd/user-ssh-keys-agent/Makefile
  hack/release-docker-images.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/S

#7042 Duplicate buildx builder fix
  cmd/user-ssh-keys-agent/Makefile
  hack/release-docker-images.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#7044 Revert buildx
  cmd/user-ssh-keys-agent/Makefile
  hack/release-docker-images.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#7030 Add CSIDriver data migration to the kubermatic-installer
  cmd/kubermatic-installer/cmd_deploy.go
  pkg/install/stack/kubermatic-seed/migrations.go
  pkg/install/stack/kubermatic-seed/stack.go
  pkg/install/stack/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/L

#7043 allow service account create projects
  cmd/kubermatic-api/swagger.json
  pkg/handler/routes_v1.go
  pkg/handler/test/fake_provider.go
  pkg/handler/v1/project/project.go
  pkg/handler/v1/project/project_test.go
  pkg/provider/kubernetes/member.go
  pkg/provider/kubernetes/project.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/project/create_project_responses.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/L

#7041 Add Alertmanager authorization server
  cmd/alertmanager-authorization-server/Dockerfile
  cmd/alertmanager-authorization-server/OWNERS
  cmd/alertmanager-authorization-server/README.md
  cmd/alertmanager-authorization-server/main.go
  cmd/alertmanager-authorization-server/main_test.go
  go.mod
  hack/release-alertmanager-authorization-server-image.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#7052 cleanup MLA resources when userClusterMLA disabled
  cmd/seed-controller-manager/controllers.go
  pkg/controller/seed-controller-manager/mla/alertmanager_controller.go
  pkg/controller/seed-controller-manager/mla/alertmanager_controller_test.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/M

#7054 project creation supports multiple owners as owner references
  pkg/controller/master-controller-manager/rbac/sync_project.go
  pkg/controller/master-controller-manager/rbac/sync_project_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/security, size/L

#7065 Update kubelet-configmap to use the systemd cgroupDriver
  addons/kubelet-configmap/kubelet-configmap.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/XS

#7036 Allow to override Machine Controller version
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/options.go
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/seed/resources/kubermatic/seed-controller-manager.go
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/crd/operator/v1alpha1/configuration.go
  pkg/crd/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/resources/data.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/machinecontroller/webhook.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/L

#7075 Re-enable NodeLocal DNS Cache in user clusters
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/options.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#7077 fix vsphere TLS client config overwrite
  pkg/provider/cloud/vsphere/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/XS

#7079 [release/v2.16] Re-enable NodeLocal DNS Cache in user clusters
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/options.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#7063 Implement User synchronizer controller
  cmd/master-controller-manager/controllers.go
  codegen/reconcile/main.go
  pkg/api/v1/types.go
  pkg/controller/master-controller-manager/user-synchronizer/OWNERS
  pkg/controller/master-controller-manager/user-synchronizer/controller.go
  pkg/controller/master-controller-manager/user-synchronizer/controller_test.go
  pkg/controller/master-controller-manager/user-synchronizer/doc.go
  pkg/controller/master-controller-manager/user-synchronizer/resources.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, sig/cluster-management, size/L

#7040 Use optimistic lock to add finalizers to cluster resources
  pkg/controller/master-controller-manager/usersshkeyssynchronizer/controller.go
  pkg/controller/seed-controller-manager/backup/backup_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XS

#7089 Add changelog for 2.16.10
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#7067 add e2e test for SA in projectmanagers group
  pkg/test/e2e/api/sa_test.go
  pkg/test/e2e/utils/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#7034 Adds Constraint master controller
  cmd/master-controller-manager/controllers.go
  codegen/reconcile/main.go
  pkg/api/v1/types.go
  pkg/controller/master-controller-manager/master-constraint-controller/controller.go
  pkg/controller/master-controller-manager/master-constraint-controller/controller_test.go
  pkg/controller/master-controller-manager/master-constraint-controller/doc.go
  pkg/controller/master-controller-manager/master-constraint-template-controller/controller_test.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, sig/cluster-management, size/L

#7076 add grafana user controller
  go.mod
  go.sum
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/org_user_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/org_user_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/resources.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/XL

#7090 Don't Sync User and UserProjectBinding objects of service accounts
  pkg/controller/master-controller-manager/user-project-binding-sync/controller.go
  pkg/controller/master-controller-manager/user-synchronizer/controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#7095 Filter out UserProjectBindings of service account users in Seed watch
  pkg/controller/master-controller-manager/user-project-binding-sync/controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#7091 Add NodeLocal DNS Cache configuration to Cluster API
  cmd/image-loader/main.go
  cmd/kubermatic-api/swagger.json
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/options.go
  cmd/user-cluster-controller-manager/main.go
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/resources/data.go
  pkg/resources/test/fixtures/deployment-aws-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-usercluster-controller.yaml
  pkg/resources/test/load_files_test.go
  pkg/resources/usercluster/deployment.go
  pkg/test/e2e/utils/apiclient/models/cluster_networking_config.go
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
  pkg/webhook/cluster/validation/validation.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/L

#7099 Allow nil for nodeLocalDNSCacheEnabled
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#7081 Open NodePort range in openstack
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/options.go
  pkg/controller/seed-controller-manager/cloud/cloud_controller.go
  pkg/provider/cloud/openstack/helper.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/openstack/provider_test.go
  pkg/provider/cloud/provider.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/cluster/cluster.go
  pkg/resources/data.go
  pkg/resources/resources.go
  pkg/validation/cluster.go
  pkg/webhook/cluster/mutation/mutation_test.go
  pkg/webhook/cluster/validation/validation.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/L

#7106 add cluster template CRD
  charts/kubermatic/Chart.yaml
  charts/kubermatic/crd/crd-cluster-templates.yaml
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/clustertemplate.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/fake/fake_clustertemplate.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/fake/fake_kubermatic_client.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/generated_expansion.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/kubermatic_client.go
  pkg/crd/client/informers/externalversions/generic.go
  pkg/crd/client/informers/externalversions/kubermatic/v1/clustertemplate.go
  pkg/crd/client/informers/externalversions/kubermatic/v1/interface.go
  pkg/crd/client/listers/kubermatic/v1/clustertemplate.go
  pkg/crd/client/listers/kubermatic/v1/expansion_generated.go
  pkg/crd/kubermatic/v1/cluster_templates.go
  pkg/crd/kubermatic/v1/register.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/XL

#6980 Proposal for Konnectivity implementation
  docs/proposals/konnectivity-openvpn.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/networking, size/L

#7102 Add proposal for user cluster templates
  docs/proposals/cluster-templates.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#7109 Revert "Open NodePort range in openstack"
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/options.go
  pkg/controller/seed-controller-manager/cloud/cloud_controller.go
  pkg/provider/cloud/openstack/helper.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/openstack/provider_test.go
  pkg/provider/cloud/provider.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/cluster/cluster.go
  pkg/resources/data.go
  pkg/resources/resources.go
  pkg/validation/cluster.go
  pkg/webhook/cluster/mutation/mutation_test.go
  pkg/webhook/cluster/validation/validation.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/L

#7066 Support regular parameters for Kubermatic constraints Constraint
  cmd/kubermatic-api/swagger.json
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller_test.go
  pkg/crd/kubermatic/v1/constraint.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/test/helper.go
  pkg/handler/v2/constraint/constraint_test.go
  pkg/provider/kubernetes/constraint_test.go
  pkg/test/e2e/opa/opa_test.go
  pkg/test/e2e/utils/apiclient/models/constraint_spec.go
  pkg/test/e2e/utils/apiclient/models/parameters.go
  pkg/util/deepcopy/deepcopy.go
  pkg/util/deepcopy/deepcopy_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/L

#7100 add mla cleanup controller
  pkg/controller/seed-controller-manager/mla/alertmanager_controller.go
  pkg/controller/seed-controller-manager/mla/alertmanager_controller_test.go
  pkg/controller/seed-controller-manager/mla/cleanup_controller.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/org_user_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/org_user_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/XL

#7121 Open NodePort range in openstack
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/options.go
  pkg/controller/seed-controller-manager/cloud/cloud_controller.go
  pkg/provider/cloud/openstack/helper.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/openstack/provider_test.go
  pkg/provider/cloud/provider.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/cluster/cluster.go
  pkg/resources/data.go
  pkg/resources/resources.go
  pkg/validation/cluster.go
  pkg/webhook/cluster/mutation/mutation_test.go
  pkg/webhook/cluster/validation/validation.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/L

#7129 Added validation for constraint parameters
  pkg/handler/test/helper.go
  pkg/handler/v2/constraint/constraint.go
  pkg/handler/v2/constraint/constraint_test.go
  pkg/handler/v2/constraint_template/constraint_template_test.go
  pkg/handler/v2/routes_v2.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, size/L

#7094 Adds seedconstraintsynchronizer controller
  cmd/seed-controller-manager/controllers.go
  pkg/api/v1/types.go
  pkg/controller/seed-controller-manager/constraint-controller/controller.go
  pkg/controller/seed-controller-manager/constraint-controller/controller_test.go
  pkg/controller/seed-controller-manager/constraint-controller/doc.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, sig/cluster-management, size/XL

#7131 [release/v2.17] Open NodePort range in openstack
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/options.go
  pkg/controller/seed-controller-manager/cloud/cloud_controller.go
  pkg/provider/cloud/openstack/helper.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/provider.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/cluster/cluster.go
  pkg/resources/data.go
  pkg/resources/resources.go
  pkg/validation/cluster.go
  pkg/webhook/cluster/validation/validation.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/L

#7135 rerun of cloud initialization duplicates finalizers
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/openstack/provider_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, sig/cluster-management, size/S

#7073 add aws-node-termination-handler as an addon
  addons/aws-node-termination-handler/aws-node-termination-handler.yaml
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/kubernetes-addons.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/app-management, sig/cluster-management, size/L

#7082 Default cluster component settings using webhook
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/main.go
  pkg/controller/seed-controller-manager/cloud/cloud_controller.go
  pkg/controller/seed-controller-manager/clustercomponentdefaulter/clustercomponentdefaulter.go
  pkg/controller/seed-controller-manager/clustercomponentdefaulter/clustercomponentdefaulter_test.go
  pkg/controller/seed-controller-manager/clustercomponentdefaulter/doc.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/provider.go
  pkg/resources/cluster/cluster.go
  pkg/validation/cluster.go
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/validation/validation.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XL

#7151 Increase memory limits for ip-fixup
  pkg/resources/openvpn/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-openvpn-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-openvpn-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-openvpn-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-openvpn-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-openvpn-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-openvpn-server.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, sig/cluster-management, size/M

#7120 Remove unused nodelocal-dns-cache addon, ensure nodelocal-dns stays enabled for existing clusters
  addons/nodelocal-dns-cache/dns.yaml
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/resources/data.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, sig/cluster-management, size/L
