Repository kubermatic/kubermatic, pull requests merged in 2021-06, with the labels that each got.

#7107 Implement rule group controller
  charts/kubermatic/Chart.yaml
  charts/kubermatic/crd/crd-rulegroups.yaml
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/options.go
  pkg/controller/seed-controller-manager/mla/alertmanager_controller.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/org_user_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller_test.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller_test.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/fake/fake_kubermatic_client.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/fake/fake_rulegroup.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/generated_expansion.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/kubermatic_client.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/rulegroup.go
  pkg/crd/client/informers/externalversions/generic.go
  pkg/crd/client/informers/externalversions/kubermatic/v1/interface.go
  pkg/crd/client/informers/externalversions/kubermatic/v1/rulegroup.go
  pkg/crd/client/listers/kubermatic/v1/expansion_generated.go
  pkg/crd/client/listers/kubermatic/v1/rulegroup.go
  pkg/crd/kubermatic/v1/register.go
  pkg/crd/kubermatic/v1/rulegroup.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, sig/cluster-management, size/XXL

#7033 [release/v2.17] add rbac for constraints owners,editors,viewers (#6942)
  pkg/controller/master-controller-manager/rbac/mapper.go
  pkg/controller/master-controller-manager/rbac/rbac_resource_controller.go
  pkg/controller/master-controller-manager/rbac/sync_resource.go
  pkg/controller/master-controller-manager/rbac/sync_resource_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/security, size/XL

#7154 Bump Gatekeeper version to 3.2.3
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XS

#7157 Fix cluster validation to tolerate empty nodeport range
  pkg/webhook/cluster/validation/validation.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#7150 create endpoint for cluster templates
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/options.go
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/crd/kubermatic/v1/cluster_templates.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/common/cluster.go
  pkg/handler/routing.go
  pkg/handler/test/hack/hack.go
  pkg/handler/test/helper.go
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/routing.go
  pkg/provider/kubernetes/cluster_template.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/project/create_cluster_template_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/create_cluster_template_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/utils/apiclient/models/cluster_template.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/XXL

#7153 [release/v2.17] Backport fix for finalizers race condition
  pkg/controller/master-controller-manager/usersshkeyssynchronizer/controller.go
  pkg/controller/seed-controller-manager/backup/backup_controller.go
  pkg/controller/seed-controller-manager/cloud/cloud_controller.go
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/controller/seed-controller-manager/kubernetes/pending.go
  pkg/provider/cloud/openstack/helper.go
  pkg/provider/cloud/openstack/internal/testing/fixtures.go
  pkg/provider/cloud/openstack/internal/testing/simulator.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/openstack/provider_test.go
  pkg/provider/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/XXL

#7169 Set kube-system as a namespace for aws-node-termination-handler role-binding
  addons/aws-node-termination-handler/aws-node-termination-handler.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/XS

#7159 Be explicit about the need of the NET_RAW capability for OpenVPN Init…
  pkg/resources/openvpn/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-openvpn-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-openvpn-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-openvpn-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-openvpn-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-openvpn-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-openvpn-server.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, sig/cluster-management, size/M

#7165 [release/v2.16] Upgrade machinecontroller to v1.24.5
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/L

#7134 Add admin to all orgs
  go.mod
  go.sum
  pkg/controller/seed-controller-manager/mla/alertmanager_controller.go
  pkg/controller/seed-controller-manager/mla/cleanup_controller.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/grafana.go
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/org_user_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/resources.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/XL

#7178 use vNet RG for subnet and vnet name when specified for azure
  pkg/provider/cloud/azure/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/S

#7182 Add predicate functions to filer out Users and UserProjectBindings of service accounts
  pkg/controller/seed-controller-manager/mla/alertmanager_controller.go
  pkg/controller/seed-controller-manager/mla/org_user_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/S

#7186 Do not return an error if MLA is disabled and not installed in Seed
  pkg/controller/seed-controller-manager/mla/mla.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/XS

#7179 add vnet rg in azure ccm cloud config
  pkg/resources/cloudconfig/configmap.go
  pkg/resources/test/fixtures/configmap-azure-1.17.0-cloud-config.yaml
  pkg/resources/test/fixtures/configmap-azure-1.18.0-cloud-config.yaml
  pkg/resources/test/fixtures/configmap-azure-1.19.0-cloud-config.yaml
  pkg/resources/test/fixtures/configmap-azure-1.20.0-cloud-config.yaml
  pkg/resources/test/fixtures/configmap-azure-1.21.0-cloud-config.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/S

#7183 Handle deletion of RuleGroup if the Cluster object is gone
  pkg/controller/seed-controller-manager/mla/rulegroup_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/S

#7158 Logrotate removal
  addons/logrotate/daemonset.yaml
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/kubernetes-addons.yaml
  cmd/kubermatic-installer/cmd_deploy.go
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
  pkg/install/stack/kubermatic-seed/migrations.go
  pkg/install/stack/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, sig/cluster-management, size/L

#7168 get/list cluster templates
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/test/fake_wrapper.go
  pkg/handler/test/helper.go
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/cluster_template.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/project/get_cluster_template_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/get_cluster_template_responses.go
  pkg/test/e2e/utils/apiclient/client/project/list_cluster_templates_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/list_cluster_templates_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/utils/apiclient/models/cluster_template_list.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/XXL

#7162 Implement the RuleGroup CRUD endpoints
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/options.go
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/controller/master-controller-manager/rbac/mapper.go
  pkg/controller/master-controller-manager/rbac/sync_resource.go
  pkg/controller/master-controller-manager/rbac/sync_resource_test.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller_test.go
  pkg/handler/middleware/middleware.go
  pkg/handler/routing.go
  pkg/handler/test/fake_wrapper.go
  pkg/handler/test/hack/hack.go
  pkg/handler/test/helper.go
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/routing.go
  pkg/handler/v2/rulegroup/request.go
  pkg/handler/v2/rulegroup/rulegroup.go
  pkg/handler/v2/rulegroup/rulegroup_test.go
  pkg/handler/v2/seedsettings/seedsettings_test.go
  pkg/provider/datacenter.go
  pkg/provider/kubernetes/rulegroup.go
  pkg/provider/kubernetes/rulegroup_test.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/kubermatic_api_client.go
  pkg/test/e2e/utils/apiclient/client/rulegroup/create_rule_group_parameters.go
  pkg/test/e2e/utils/apiclient/client/rulegroup/create_rule_group_responses.go
  pkg/test/e2e/utils/apiclient/client/rulegroup/delete_rule_group_parameters.go
  pkg/test/e2e/utils/apiclient/client/rulegroup/delete_rule_group_responses.go
  pkg/test/e2e/utils/apiclient/client/rulegroup/get_rule_group_parameters.go
  pkg/test/e2e/utils/apiclient/client/rulegroup/get_rule_group_responses.go
  pkg/test/e2e/utils/apiclient/client/rulegroup/list_rule_groups_parameters.go
  pkg/test/e2e/utils/apiclient/client/rulegroup/list_rule_groups_responses.go
  pkg/test/e2e/utils/apiclient/client/rulegroup/rulegroup_client.go
  pkg/test/e2e/utils/apiclient/client/rulegroup/update_rule_group_parameters.go
  pkg/test/e2e/utils/apiclient/client/rulegroup/update_rule_group_responses.go
  pkg/test/e2e/utils/apiclient/models/rule_group.go
  pkg/test/e2e/utils/apiclient/models/rule_group_type.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/app-management, sig/security, size/XXL

#7192 Fixed openstack client ca bundle handling
  pkg/provider/cloud/openstack/provider.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XS

#7197 delete endpoint for cluster templates
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/cluster_template.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/project/delete_cluster_template_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/delete_cluster_template_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/XL

#7200 Add Log type support in RuleGroup controller
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/options.go
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/M

#7202 Add Logs Type to RuleGroup list option
  pkg/handler/v2/rulegroup/request.go
  pkg/handler/v2/rulegroup/rulegroup_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/app-management, size/S

#7164 [release/v2.15] Upgrade machinecontroller to v1.19.2
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-machine-controller.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#7210 Allow to configure Alertmanager and Alert Rule Groups when MLA logging is enabled.
  pkg/controller/master-controller-manager/rbac/sync_resource.go
  pkg/controller/master-controller-manager/rbac/sync_resource_test.go
  pkg/controller/seed-controller-manager/mla/alertmanager_controller.go
  pkg/controller/seed-controller-manager/mla/alertmanager_controller_test.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, sig/security, size/L

#7149 [ee] Adds Constraint cluster filtering
  cmd/kubermatic-api/swagger.json
  pkg/controller/seed-controller-manager/constraint-controller/controller.go
  pkg/controller/seed-controller-manager/constraint-controller/controller_test.go
  pkg/controller/seed-controller-manager/constraint-controller/wrappers_ce.go
  pkg/controller/seed-controller-manager/constraint-controller/wrappers_ee.go
  pkg/crd/kubermatic/v1/constraint.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/ee/constraint-controller/util.go
  pkg/ee/constraint-controller/util_test.go
  pkg/handler/test/helper.go
  pkg/handler/v2/constraint/constraint_test.go
  pkg/test/e2e/utils/apiclient/models/constraint_selector.go
  pkg/test/e2e/utils/apiclient/models/constraint_spec.go
Labels: approved, dco-signoff: yes, ee, lgtm, release-note-none, sig/api, sig/cluster-management, size/XL

#7193 Fix user ssh key agent migration
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/common/cluster.go
  pkg/handler/test/helper.go
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/resources/cluster/cluster.go
  pkg/resources/test/fixtures/deployment-aws-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-usercluster-controller.yaml
  pkg/resources/usercluster/deployment.go
  pkg/test/e2e/expose-strategy/cluster.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/L

#7224 [release/v2.17] Fix user ssh key agent migration (#7193)
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/common/cluster.go
  pkg/handler/test/helper.go
  pkg/resources/cluster/cluster.go
  pkg/resources/test/fixtures/deployment-aws-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-usercluster-controller.yaml
  pkg/resources/usercluster/deployment.go
  pkg/test/e2e/expose-strategy/cluster.go
  pkg/webhook/cluster/validation/validation.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/L

#7228 Add changelog for 2.17.1
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#7174 Upgrade canal
  addons/canal/canal.yaml
  addons/canal/canal_v3.19.yaml
  docs/zz_generated.addondata.go.txt
  pkg/addon/template.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
  pkg/webhook/cluster/validation/validation.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, sig/cluster-management, size/XXL

#7225 Add container runtime to cluster spec
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/handler/common/cluster.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/resources/cluster/cluster.go
  pkg/test/e2e/utils/apiclient/models/cluster_spec.go
  pkg/validation/cluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/M

#7189 Cluster deletion to leave dynamic PVs cleanup to provisioner
  pkg/clusterdeletion/volumes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/S

#7213 Adds constraint finalizer removal
  pkg/clusterdeletion/constraints.go
  pkg/controller/seed-controller-manager/constraint-controller/controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/S

#7217 Proposal for registry whitelisting enforcement
  docs/proposals/whitelisted-registries.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#7220 cluster template sync controller
  cmd/master-controller-manager/controllers.go
  codegen/reconcile/main.go
  pkg/api/v1/types.go
  pkg/controller/master-controller-manager/cluster-template-synchronizer/OWNERS
  pkg/controller/master-controller-manager/cluster-template-synchronizer/controller.go
  pkg/controller/master-controller-manager/cluster-template-synchronizer/controller_test.go
  pkg/controller/master-controller-manager/cluster-template-synchronizer/doc.go
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/resources/reconciling/compare.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, sig/cluster-management, size/L

#7232 create a new type for cluster template instances
  charts/kubermatic/Chart.yaml
  charts/kubermatic/crd/crd-cluster-template-instances.yaml
  pkg/controller/master-controller-manager/rbac/rbac_controller_aggregator.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/clustertemplateinstance.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/fake/fake_clustertemplateinstance.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/fake/fake_kubermatic_client.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/generated_expansion.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/kubermatic_client.go
  pkg/crd/client/informers/externalversions/generic.go
  pkg/crd/client/informers/externalversions/kubermatic/v1/clustertemplateinstance.go
  pkg/crd/client/informers/externalversions/kubermatic/v1/interface.go
  pkg/crd/client/listers/kubermatic/v1/clustertemplateinstance.go
  pkg/crd/client/listers/kubermatic/v1/expansion_generated.go
  pkg/crd/kubermatic/v1/cluster_template_instance.go
  pkg/crd/kubermatic/v1/register.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, sig/security, size/XL

#7242 disable opa e2e tests temporarily
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#7244 Add exclusion for envoyagent interface for Calico IP discovery
  addons/canal/canal_v3.19.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/XS

#7238 Fix KubeVirt cluster network collision
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#7208 added option for Azure Load Balancer SKU in KKP API
  cmd/kubermatic-api/swagger.json
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/preset.go
  pkg/resources/test/load_files_test.go
  pkg/test/e2e/utils/apiclient/models/azure_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/l_b_s_k_u.go
  pkg/validation/cluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/M

#7230 Fix verify-swagger flakiness
  .prow.yaml
  hack/verify-swagger.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#7248 add container runtime interface to the machine controller deployment
  pkg/resources/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/XS

#7249 Add feature gate to enable Konnectivity service deployment.
  pkg/features/features.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#7233 Stabilize opa e2e tests
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/secret.go
  pkg/controller/user-cluster-controller-manager/resources/resources/kubernetes-dashboard/secret.go
  pkg/controller/user-cluster-controller-manager/resources/resources/usersshkeys/secrets.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/S

#7216 Production-ready Kubevirt proposal
  docs/proposals/images/kubevirt-architecture.png
  docs/proposals/images/kubevirt-dv.png
  docs/proposals/images/kubevirt-host-clone.png
  docs/proposals/images/kubevirt-network-isolation.png
  docs/proposals/images/kubevirt-pre-dv.png
  docs/proposals/images/kubevirt-smart-clone.png
  docs/proposals/images/kubevirt-vm-presets.png
  docs/proposals/kubevirt-production-proposal.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/virtualization, size/L

#7258 Move environment variable to skip envoyagent interface to right container
  addons/canal/canal_v3.19.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/S

#7221 add application credentials and OIDC token for OpenStack
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.addondata.go.txt
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/preset.go
  pkg/handler/common/provider/openstack.go
  pkg/handler/v1/provider/openstack.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/kubernetes/credentials.go
  pkg/provider/kubernetes/preset.go
  pkg/resources/credentials.go
  pkg/resources/resources.go
  pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_availability_zones_parameters.go
  pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_networks_parameters.go
  pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_security_groups_parameters.go
  pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_sizes_parameters.go
  pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_subnets_parameters.go
  pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_tenants_parameters.go
  pkg/test/e2e/utils/apiclient/models/openstack_cloud_spec.go
  pkg/validation/cluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/XL

#7204 [ee] Adds constraints active flip
  cmd/kubermatic-api/swagger.json
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller_test.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/wrappers_ce.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/wrappers_ee.go
  pkg/crd/kubermatic/v1/constraint.go
  pkg/handler/test/helper.go
  pkg/handler/v2/constraint/constraint_test.go
  pkg/test/e2e/utils/apiclient/models/constraint_spec.go
Labels: approved, dco-signoff: yes, ee, lgtm, release-note-none, sig/api, sig/cluster-management, size/L

#7259 set seed destination for ClusterTemplateInstance
  pkg/controller/master-controller-manager/rbac/mapper.go
  pkg/controller/master-controller-manager/rbac/rbac_controller_aggregator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/security, size/XS

#7264 change KKP admin grafana role to Editor
  pkg/controller/seed-controller-manager/mla/org_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/XS

#7263 [release/v2.17] extend RBAC controller for `projectmanagers` group.
  pkg/controller/master-controller-manager/rbac/mapper.go
  pkg/controller/master-controller-manager/rbac/mapper_test.go
  pkg/controller/master-controller-manager/rbac/sync_project_test.go
  pkg/controller/master-controller-manager/rbac/sync_resource_test.go
  pkg/handler/v1/serviceaccount/sa.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/security, size/XL

#7271 add loadBalancerSku in azure cloud config
  go.mod
  go.sum
  pkg/resources/cloudconfig/configmap.go
  pkg/resources/test/fixtures/configmap-azure-1.17.0-cloud-config.yaml
  pkg/resources/test/fixtures/configmap-azure-1.18.0-cloud-config.yaml
  pkg/resources/test/fixtures/configmap-azure-1.19.0-cloud-config.yaml
  pkg/resources/test/fixtures/configmap-azure-1.20.0-cloud-config.yaml
  pkg/resources/test/fixtures/configmap-azure-1.21.0-cloud-config.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/L

#7199 CCM-CSI-migration controller
  cmd/user-cluster-controller-manager/main.go
  hack/run-user-cluster-controller-manager.sh
  pkg/controller/user-cluster-controller-manager/ccm-csi-migrator/controller.go
  pkg/controller/user-cluster-controller-manager/ccm-csi-migrator/controller_test.go
  pkg/controller/user-cluster-controller-manager/ccm-csi-migrator/doc.go
  pkg/crd/kubermatic/v1/helper/helper.go
  pkg/resources/usercluster/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/L

#7256 Create default constraint endpoint
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/options.go
  cmd/kubermatic-api/swagger.json
  pkg/handler/routing.go
  pkg/handler/test/fake_provider.go
  pkg/handler/test/hack/hack.go
  pkg/handler/test/helper.go
  pkg/handler/v2/constraint/constraint.go
  pkg/handler/v2/constraint/constraint_test.go
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/routing.go
  pkg/provider/kubernetes/cluster_template.go
  pkg/provider/kubernetes/constraint.go
  pkg/provider/kubernetes/constraint_test.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/constraint/constraint_client.go
  pkg/test/e2e/utils/apiclient/client/constraint/create_default_constraint_parameters.go
  pkg/test/e2e/utils/apiclient/client/constraint/create_default_constraint_responses.go
  pkg/test/e2e/utils/apiclient/client/kubermatic_api_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/XL

#7243 Automated rollout of Grafana Dashboards
  go.mod
  go.sum
  pkg/controller/seed-controller-manager/mla/grafana.go
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/L

#7273 add application credentials for machine controller deployment
  pkg/provider/cloud/openstack/provider.go
  pkg/resources/cloudconfig/configmap.go
  pkg/resources/credentials.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/M

#7275 [ee] Adds constraint disabled flag
  .prow.yaml
  cmd/kubermatic-api/swagger.json
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller_test.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/wrappers_ee.go
  pkg/crd/kubermatic/v1/constraint.go
  pkg/handler/test/helper.go
  pkg/handler/v2/constraint/constraint_test.go
  pkg/test/e2e/utils/apiclient/models/constraint_spec.go
Labels: approved, dco-signoff: yes, ee, lgtm, release-note-none, sig/api, sig/cluster-management, size/M

#7288 Allow configuring remote_write in Prometheus Helm chart
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/config/prometheus.yaml
  charts/monitoring/prometheus/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/S

#7286 GET endpoint for cluster template instances
  cmd/kubermatic-api/swagger.json
  pkg/handler/test/helper.go
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/cluster_template_instance.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/project/get_cluster_template_instance_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/get_cluster_template_instance_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/XL

#7287 Default to DockerRegistry only if provided repo has less than 3 parts
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/resources/data.go
  pkg/resources/data_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/L

#7289 [release/v2.17] added option for Azure Load Balancer SKU in KKP API
  cmd/kubermatic-api/swagger.json
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/preset.go
  pkg/resources/test/load_files_test.go
  pkg/test/e2e/utils/apiclient/models/azure_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/l_b_s_k_u.go
  pkg/validation/cluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/M

#7281 support resource pool for vSphere
  cmd/kubermatic-api/swagger.json
  pkg/crd/kubermatic/v1/cluster.go
  pkg/provider/cloud/vsphere/provider.go
  pkg/resources/machine/common.go
  pkg/test/e2e/utils/apiclient/models/v_sphere_cloud_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/S

#7251 added WhitelistedRegistry CRD
  charts/kubermatic/Chart.yaml
  charts/kubermatic/crd/crd-whitelisted-registries.yaml
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/fake/fake_kubermatic_client.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/fake/fake_whitelistedregistry.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/generated_expansion.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/kubermatic_client.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/whitelistedregistry.go
  pkg/crd/client/informers/externalversions/generic.go
  pkg/crd/client/informers/externalversions/kubermatic/v1/interface.go
  pkg/crd/client/informers/externalversions/kubermatic/v1/whitelistedregistry.go
  pkg/crd/client/listers/kubermatic/v1/expansion_generated.go
  pkg/crd/client/listers/kubermatic/v1/whitelistedregistry.go
  pkg/crd/kubermatic/v1/register.go
  pkg/crd/kubermatic/v1/whitelisted_registry.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/XL

#7284 Fixes network not found issue
  pkg/provider/cloud/openstack/helper.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/S

#7297 Exclude user ssh key nil value in the validation webhook
  pkg/webhook/cluster/validation/validation.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#7308 [release/v2.17] add loadBalancerSku in azure cloud config
  go.mod
  go.sum
  pkg/resources/cloudconfig/configmap.go
  pkg/resources/test/fixtures/configmap-azure-1.17.0-cloud-config.yaml
  pkg/resources/test/fixtures/configmap-azure-1.18.0-cloud-config.yaml
  pkg/resources/test/fixtures/configmap-azure-1.19.0-cloud-config.yaml
  pkg/resources/test/fixtures/configmap-azure-1.20.0-cloud-config.yaml
  pkg/resources/test/fixtures/configmap-azure-1.21.0-cloud-config.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/S

#7298 List endpoint for cluster template instances
  cmd/kubermatic-api/swagger.json
  pkg/handler/test/helper.go
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/project/list_cluster_template_instances_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/list_cluster_template_instances_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/XL

#7185 ExternalCloudProvider migration endpoint
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/common/cluster.go
  pkg/handler/routes_v1.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/operations/migrate_cluster_to_external_c_c_m_parameters.go
  pkg/test/e2e/utils/apiclient/client/operations/migrate_cluster_to_external_c_c_m_responses.go
  pkg/test/e2e/utils/apiclient/client/operations/operations_client.go
  pkg/test/e2e/utils/apiclient/models/cluster_status.go
  pkg/test/e2e/utils/apiclient/models/external_c_c_m_status.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, sig/cluster-management, size/XL

#7307 Adds get and list default constraint endpoints
  cmd/kubermatic-api/swagger.json
  pkg/handler/test/fake_provider.go
  pkg/handler/v2/constraint/constraint.go
  pkg/handler/v2/constraint/constraint_test.go
  pkg/handler/v2/constraint_template/constraint_template_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/constraint.go
  pkg/provider/kubernetes/constraint_test.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/constraint/constraint_client.go
  pkg/test/e2e/utils/apiclient/client/constraint/create_default_constraint_parameters.go
  pkg/test/e2e/utils/apiclient/client/constraint/get_default_constraint_parameters.go
  pkg/test/e2e/utils/apiclient/client/constraint/get_default_constraint_responses.go
  pkg/test/e2e/utils/apiclient/client/constraint/list_default_constraint_parameters.go
  pkg/test/e2e/utils/apiclient/client/constraint/list_default_constraint_responses.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/XXL

#7302 check if resource quantity is set before apply defaults
  pkg/controller/operator/common/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XS

#7239 Allow preset filtering by domains and emails
  pkg/crd/kubermatic/v1/preset.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/provider/kubernetes/preset.go
  pkg/provider/kubernetes/preset_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, sig/api, sig/cluster-management, size/L
