Repository kubermatic/kubermatic, pull requests merged in 2021-02, with the labels that each got.

#6478 bump controller runtime to 0.6.5
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6483 go mod tidy
  .prow.yaml
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6468 enable VM resource quota for AWS provider
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/common/filter.go
  pkg/handler/common/provider/aws.go
  pkg/handler/routes_v1.go
  pkg/handler/v1/provider/aws.go
  pkg/handler/v2/provider/aws.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/models/a_w_s_size.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/L

#6484 increase resources for go mod verify
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6482 fix confusing clusterexposer error messages
  pkg/test/clusterexposer/cmd/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6473 enable VM resource quota for Azure provider
  pkg/handler/common/provider/azure.go
  pkg/handler/routes_v1.go
  pkg/handler/v1/provider/azure.go
  pkg/handler/v1/provider/azure_test.go
  pkg/handler/v2/provider/azure.go
  pkg/handler/v2/routes_v2.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, size/M

#6465 Remove CoreOS support in KKP
  addons/csi/nodeplugin.yaml
  cmd/conformance-tests/main.go
  cmd/conformance-tests/os.go
  cmd/conformance-tests/runner.go
  cmd/conformance-tests/scenarios_aws.go
  cmd/conformance-tests/scenarios_azure.go
  cmd/conformance-tests/scenarios_digitalocean.go
  cmd/conformance-tests/scenarios_gcp.go
  cmd/conformance-tests/scenarios_openstack.go
  cmd/conformance-tests/scenarios_packet.go
  cmd/conformance-tests/scenarios_vsphere.go
  cmd/image-loader/main.go
  cmd/kubermatic-api/swagger.json
  cmd/user-cluster-controller-manager/main.go
  docs/zz_generated.seed.yaml
  hack/ci/deploy.sh
  pkg/api/v1/types.go
  pkg/controller/user-cluster-controller-manager/container-linux/container_linux_controller.go
  pkg/controller/user-cluster-controller-manager/container-linux/doc.go
  pkg/controller/user-cluster-controller-manager/container-linux/resources/clusterrole.go
  pkg/controller/user-cluster-controller-manager/container-linux/resources/clusterrolebinding.go
  pkg/controller/user-cluster-controller-manager/container-linux/resources/daemonset.go
  pkg/controller/user-cluster-controller-manager/container-linux/resources/deployment.go
  pkg/controller/user-cluster-controller-manager/container-linux/resources/serviceaccount.go
  pkg/controller/user-cluster-controller-manager/node-labeler/api/api.go
  pkg/controller/user-cluster-controller-manager/node-labeler/doc.go
  pkg/controller/user-cluster-controller-manager/node-labeler/node_labeleler_test.go
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/ee/provider/datacenter_test.go
  pkg/machine/convert.go
  pkg/machine/util_test.go
  pkg/resources/machine/common.go
  pkg/resources/machine/machinedeployment.go
  pkg/resources/test/load_files_test.go
  pkg/test/e2e/utils/apiclient/models/container_linux_spec.go
  pkg/test/e2e/utils/apiclient/models/node_settings.go
  pkg/test/e2e/utils/apiclient/models/operating_system_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/app-management, sig/cluster-management, size/XXL

#6449 [Installer] Update Helm releases when values have changed
  Makefile
  hack/ci/README.md
  hack/ci/run-lint.sh
  pkg/install/helm/cli.go
  pkg/install/helm/interface.go
  pkg/install/util/helm.go
  pkg/util/yamled/document.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/M

#6499 Fix cluster GET not returning OPA integration details
  pkg/api/v1/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, size/XS

#6461 Added gatekeeper health status
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/controller/seed-controller-manager/kubernetes/health.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/handler/common/cluster.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/test/e2e/utils/apiclient/models/cluster_health.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/M

#6501 Compute CoreDNS version based on Kubernetes version
  cmd/etcd-launcher/Dockerfile
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/core-dns/configmap.go
  pkg/controller/user-cluster-controller-manager/resources/resources/core-dns/deployment.go
  pkg/resources/dns/dns.go
  pkg/resources/test/fixtures/deployment-aws-1.17.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-dns-resolver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-dns-resolver.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/L

#6476 Proposal for constraint template filters
  docs/proposals/constraint-template-filter.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6519 Kubermatic Constraints removal on cluster delete
  pkg/api/v1/types.go
  pkg/clusterdeletion/constraints.go
  pkg/clusterdeletion/deletion.go
  pkg/controller/seed-controller-manager/kubernetes/pending.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, sig/cluster-management, size/M

#6511 omit gatekeeper health status when its disabled
  pkg/api/v1/types.go
  pkg/controller/seed-controller-manager/kubernetes/health.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, sig/cluster-management, size/M

#6522 Add Multi-Cluster IPAM proposal
  docs/proposals/multi-cluster-ipam.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, sig/networking, size/L

#6504 add resource quota for Digital Ocean provider
  pkg/handler/common/provider/digitalocean.go
  pkg/handler/routes_v1.go
  pkg/handler/v1/provider/digitalocean.go
  pkg/handler/v2/provider/digitalocean.go
  pkg/handler/v2/routes_v2.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, size/M

#6525 use kubermatic spec for kubermatic CT to make it easier for extension
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/controller/master-controller-manager/master-constraint-template-controller/controller_test.go
  pkg/controller/seed-controller-manager/constraint-template-controller/controller.go
  pkg/controller/seed-controller-manager/constraint-template-controller/controller_test.go
  pkg/crd/kubermatic/v1/constraint_template.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/test/helper.go
  pkg/handler/v2/constraint_template/constraint_template.go
  pkg/handler/v2/constraint_template/constraint_template_test.go
  pkg/provider/kubernetes/util_test.go
  pkg/test/e2e/utils/apiclient/models/constraint_template_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, sig/cluster-management, size/M

#6110 Proposal for KubeLB
  docs/proposals/images/kubelb-l4.png
  docs/proposals/images/kubelb-l7.png
  docs/proposals/kubelb.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6435 [Installer] Support setting up seed clusters
  cmd/kubermatic-installer/cmd_deploy.go
  pkg/install/stack/common/storageclass.go
  pkg/install/stack/common/validation.go
  pkg/install/stack/kubermatic-master/certmanager.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/stack/kubermatic-master/validation.go
  pkg/install/stack/kubermatic-seed/stack.go
  pkg/install/stack/kubermatic-seed/validation.go
  pkg/install/stack/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XL

#6524 add resource quota for GCP provider
  pkg/handler/common/provider/gcp.go
  pkg/handler/routes_v1.go
  pkg/handler/v1/provider/gcp.go
  pkg/handler/v2/provider/gcp.go
  pkg/handler/v2/routes_v2.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, size/M

#6532 Add changelog related user settings
  cmd/kubermatic-api/swagger.json
  pkg/crd/kubermatic/v1/user.go
  pkg/test/e2e/utils/apiclient/models/user_settings.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, sig/cluster-management, size/XS

#6542 fix user ssh keys indenting
  cmd/user-ssh-keys-agent/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6534 Constraint template selector
  cmd/kubermatic-api/swagger.json
  pkg/crd/kubermatic/v1/constraint_template.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/test/helper.go
  pkg/handler/v2/constraint_template/constraint_template_test.go
  pkg/provider/kubernetes/util_test.go
  pkg/test/e2e/utils/apiclient/models/constraint_template_selector.go
  pkg/test/e2e/utils/apiclient/models/constraint_template_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/L

#6398 user cluster coredns pdb label fix
  pkg/controller/user-cluster-controller-manager/resources/resources/core-dns/deployment.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, sig/cluster-management, size/XS

#6547 remove canary-ci-deployment job
  .prow.yaml
  hack/ci/deploy.sh
  hack/ci/push-images.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/M

#6544 fixed gatekeeper deployment annotations being overwritten
  pkg/resources/gatekeeper/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/S

#6550 changed gatekeeper webhook admission version to v1beta1
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/webhook.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XS

#6537 introduce resource quota for Hetzner
  pkg/handler/common/provider/hetzner.go
  pkg/handler/routes_v1.go
  pkg/handler/v1/provider/hetzner.go
  pkg/handler/v2/provider/hetzner.go
  pkg/handler/v2/routes_v2.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, size/M

#6559 add changelog for 2.16.0 and 2.16.1
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6529 Add support for use-octavia in openstack-providerspecs
  cmd/example-yaml-generator/main.go
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.seed.yaml
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/resources/cloudconfig/configmap.go
  pkg/test/e2e/utils/apiclient/models/datacenter_spec_openstack.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, sig/api, sig/cluster-management, size/S

#6566 Fix race condition in unit test
  pkg/test/e2e/utils/http_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6568 sync docs files into the correct directory
  hack/ci/update-docs.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/XS

#6565 Add UseOctavia flag in Cluster cloud spec
  cmd/kubermatic-api/swagger.json
  go.mod
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/resources/cloudconfig/configmap.go
  pkg/resources/cloudconfig/configmap_test.go
  pkg/test/e2e/utils/apiclient/models/openstack_cloud_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/L

#6569 Fix KAS service port in tunneling agent config
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XS

#6573 2.16.2 changelog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6142 Improve Openstack swagger doc
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/test/e2e/utils/apiclient/models/openstack_node_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, sig/ui, size/S

#6561 add resource quota for OpenStack provider
  pkg/handler/common/provider/openstack.go
  pkg/handler/routes_v1.go
  pkg/handler/v1/provider/openstack.go
  pkg/handler/v1/provider/openstack_test.go
  pkg/handler/v2/provider/openstack.go
  pkg/handler/v2/routes_v2.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, size/M

#6580 Fixed CT seed controller issues with cluster enqueue and deletion
  pkg/controller/seed-controller-manager/constraint-template-controller/controller.go
  pkg/controller/seed-controller-manager/constraint-template-controller/controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/M

#6582 [release/v2.16] CT controller queue and deletion fix backport
  pkg/controller/seed-controller-manager/constraint-template-controller/controller.go
  pkg/controller/seed-controller-manager/constraint-template-controller/controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/M

#6581 enable GPU instances for Alibaba provider
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/common/provider/alibaba.go
  pkg/test/e2e/utils/apiclient/models/alibaba_instance_type.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, size/S

#6535 Add CCM/CSI migration logic
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/controller/seed-controller-manager/kubernetes/resources_test.go
  pkg/controller/seed-controller-manager/monitoring/resources.go
  pkg/controller/seed-controller-manager/openshift/data.go
  pkg/controller/seed-controller-manager/openshift/resources/interfaces.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/helper/helper.go
  pkg/kubernetes/helper.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/cloudcontroller/deployment.go
  pkg/resources/cloudcontroller/openstack.go
  pkg/resources/controllermanager/deployment.go
  pkg/resources/data.go
  pkg/resources/data_test.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/load_files_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XXL

#6477 Add Multus-CNI for user clusters.
  addons/multus/clusterrole.yaml
  addons/multus/clusterrolebinding.yaml
  addons/multus/crds.yaml
  addons/multus/daemonset.yaml
  addons/multus/serviceaccount.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, sig/cluster-management, sig/networking, size/L

#6533 Add components override field to set nodeportrange for apiserver
  pkg/crd/kubermatic/v1/cluster.go
  pkg/resources/apiserver/deployment.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note, sig/cluster-management, sig/networking, size/M

#6589 add a proposal for service account V2
  docs/proposals/service-account-v2.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6489 credential-xxx-clusterid (sometimes) have empty "project-id" label
  pkg/provider/kubernetes/credentials.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, sig/api, size/XS

#6567 Constraint template filters
  cmd/kubermatic-api/swagger.json
  pkg/controller/seed-controller-manager/constraint-template-controller/controller.go
  pkg/controller/seed-controller-manager/constraint-template-controller/wrappers_ce.go
  pkg/controller/seed-controller-manager/constraint-template-controller/wrappers_ee.go
  pkg/crd/kubermatic/v1/constraint_template.go
  pkg/ee/constraint-template-controller/util.go
  pkg/ee/constraint-template-controller/util_test.go
  pkg/handler/v2/constraint_template/constraint_template_test.go
  pkg/test/e2e/utils/apiclient/models/constraint_template_selector.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/L

#6598 fixed issue with kubermatic constraints delete failing when user cluster constraint is missing
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/S

#6590 Gatekeeper webhook timeout
  cmd/kubermatic-api/swagger.json
  cmd/user-cluster-controller-manager/main.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/webhook.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/test/helper.go
  pkg/resources/usercluster/deployment.go
  pkg/test/e2e/utils/apiclient/models/o_p_a_integration_settings.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/M

#6574 add resource quota for Packet
  pkg/handler/common/provider/packet.go
  pkg/handler/routes_v1.go
  pkg/handler/v1/provider/packet.go
  pkg/handler/v2/provider/packet.go
  pkg/handler/v2/routes_v2.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, size/M

#6603 [release/v2.16] Gatekeeper webhook timeout
  cmd/kubermatic-api/swagger.json
  cmd/user-cluster-controller-manager/main.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/webhook.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/test/helper.go
  pkg/resources/usercluster/deployment.go
  pkg/test/e2e/utils/apiclient/models/o_p_a_integration_settings.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/M

#6606 remove Procfile
  Procfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6594 Update CSI driver
  addons/csi/controllerplugin-rbac.yaml
  addons/csi/controllerplugin.yaml
  addons/csi/driver.yaml
  addons/csi/nodeplugin-rbac.yaml
  addons/csi/nodeplugin.yaml
  cmd/conformance-tests/runner.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/L

#6604 [release/v2.16] fixed issue with kubermatic constraints delete failing because user cluster constraint is missing
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/S

#6607 [release/v2.16] Update CSI driver
  addons/csi/controllerplugin-rbac.yaml
  addons/csi/controllerplugin.yaml
  addons/csi/driver.yaml
  addons/csi/nodeplugin-rbac.yaml
  addons/csi/nodeplugin.yaml
  cmd/conformance-tests/runner.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/L
