Repository kubermatic/kubermatic, pull requests merged in 2021-01, with the labels that each got.

#6331 Add endpoint to list AWS Security Groups
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/routes_v1.go
  pkg/handler/v1/provider/aws.go
  pkg/provider/cloud/aws/provider.go
  pkg/test/e2e/api/utils/apiclient/client/aws/aws_client.go
  pkg/test/e2e/api/utils/apiclient/client/aws/list_a_w_s_security_groups_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/aws/list_a_w_s_security_groups_responses.go
  pkg/test/e2e/api/utils/apiclient/models/a_w_s_security_group.go
  pkg/test/e2e/api/utils/apiclient/models/a_w_s_security_group_list.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#6335 [release/v2.14] Prevent container orphans when using apiserver.IsRunningWrapper
  api/pkg/controller/seed-controller-manager/openshift/resources/cloud_credential_operator.go
  api/pkg/controller/seed-controller-manager/openshift/resources/console.go
  api/pkg/controller/seed-controller-manager/openshift/resources/dns_operator.go
  api/pkg/controller/seed-controller-manager/openshift/resources/kube_controller_manager.go
  api/pkg/controller/seed-controller-manager/openshift/resources/kube_scheduler.go
  api/pkg/controller/seed-controller-manager/openshift/resources/oauth.go
  api/pkg/controller/seed-controller-manager/openshift/resources/openshift_apiserver_deployment.go
  api/pkg/controller/seed-controller-manager/openshift/resources/openshift_controller_manager.go
  api/pkg/controller/seed-controller-manager/openshift/resources/openshift_network_operator.go
  api/pkg/controller/seed-controller-manager/openshift/resources/registry_operator.go
  api/pkg/resources/clusterautoscaler/clusterautoscaler.go
  api/pkg/resources/controllermanager/deployment.go
  api/pkg/resources/kubernetes-dashboard/deployment.go
  api/pkg/resources/kubestatemetrics/deployment.go
  api/pkg/resources/machinecontroller/deployment.go
  api/pkg/resources/machinecontroller/webhook.go
  api/pkg/resources/metrics-server/deployment.go
  api/pkg/resources/scheduler/deployment.go
  api/pkg/resources/usercluster/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S, team/lifecycle

#6336 [release/v2.15] Prevent container orphans when using apiserver.IsRunningWrapper
  pkg/controller/seed-controller-manager/openshift/resources/cloud_credential_operator.go
  pkg/controller/seed-controller-manager/openshift/resources/console.go
  pkg/controller/seed-controller-manager/openshift/resources/dns_operator.go
  pkg/controller/seed-controller-manager/openshift/resources/kube_controller_manager.go
  pkg/controller/seed-controller-manager/openshift/resources/oauth.go
  pkg/controller/seed-controller-manager/openshift/resources/openshift_apiserver_deployment.go
  pkg/controller/seed-controller-manager/openshift/resources/openshift_controller_manager.go
  pkg/controller/seed-controller-manager/openshift/resources/openshift_network_operator.go
  pkg/controller/seed-controller-manager/openshift/resources/registry_operator.go
  pkg/resources/clusterautoscaler/clusterautoscaler.go
  pkg/resources/controllermanager/deployment.go
  pkg/resources/kubernetes-dashboard/deployment.go
  pkg/resources/kubestatemetrics/deployment.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/machinecontroller/webhook.go
  pkg/resources/metrics-server/deployment.go
  pkg/resources/scheduler/deployment.go
  pkg/resources/usercluster/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S, team/lifecycle

#6340 azure endpoints to list resource and security groups
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/common/provider/azure.go
  pkg/handler/v1/provider/azure_test.go
  pkg/handler/v2/provider/azure.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/azure/azure_client.go
  pkg/test/e2e/api/utils/apiclient/client/azure/list_azure_resource_groups_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/azure/list_azure_resource_groups_responses.go
  pkg/test/e2e/api/utils/apiclient/client/azure/list_azure_security_groups_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/azure/list_azure_security_groups_responses.go
  pkg/test/e2e/api/utils/apiclient/models/azure_resource_groups_list.go
  pkg/test/e2e/api/utils/apiclient/models/azure_security_groups_list.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#6353 Add Service Account Token Volume Projection Support Proposal
  docs/proposals/sa-token-volume-projection.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6377 shrank response for aws security group ids
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/v1/provider/aws.go
  pkg/test/e2e/api/utils/apiclient/client/aws/list_a_w_s_security_groups_responses.go
  pkg/test/e2e/api/utils/apiclient/models/a_w_s_security_group.go
  pkg/test/e2e/api/utils/apiclient/models/a_w_s_security_group_list.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6363 add endpoint to get Azure route tables
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/common/provider/azure.go
  pkg/handler/v1/provider/azure_test.go
  pkg/handler/v2/provider/azure.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/api/utils/apiclient/client/azure/azure_client.go
  pkg/test/e2e/api/utils/apiclient/client/azure/list_azure_route_tables_parameters.go
  pkg/test/e2e/api/utils/apiclient/client/azure/list_azure_route_tables_responses.go
  pkg/test/e2e/api/utils/apiclient/models/azure_route_tables_list.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#6376 Update conformance-test image to use Helm 2.17
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6338 Ct master controller
  cmd/master-controller-manager/controllers.go
  codegen/reconcile/main.go
  pkg/api/v1/types.go
  pkg/controller/master-controller-manager/master-constraint-template-controller/controller.go
  pkg/controller/master-controller-manager/master-constraint-template-controller/controller_test.go
  pkg/controller/master-controller-manager/master-constraint-template-controller/doc.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/XL

#6405 Use cloud init for flatcar on aws
  pkg/resources/machine/common.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XS

#6395 add azure endpoints for vnets and subnets
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/common/provider/azure.go
  pkg/handler/v1/provider/azure_test.go
  pkg/handler/v2/provider/azure.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/azure/azure_client.go
  pkg/test/e2e/utils/apiclient/client/azure/list_azure_subnets_parameters.go
  pkg/test/e2e/utils/apiclient/client/azure/list_azure_subnets_responses.go
  pkg/test/e2e/utils/apiclient/client/azure/list_azure_vnets_parameters.go
  pkg/test/e2e/utils/apiclient/client/azure/list_azure_vnets_responses.go
  pkg/test/e2e/utils/apiclient/models/azure_subnets_list.go
  pkg/test/e2e/utils/apiclient/models/azure_virtual_networks_list.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#6208 Add presets management API
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/crd/kubermatic/v1/preset.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v1/presets/credentials_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/machine/machine_test.go
  pkg/handler/v2/preset/preset.go
  pkg/handler/v2/preset/preset_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/preset.go
  pkg/provider/kubernetes/preset_test.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/kubermatic_api_client.go
  pkg/test/e2e/utils/apiclient/client/preset/create_preset_parameters.go
  pkg/test/e2e/utils/apiclient/client/preset/create_preset_responses.go
  pkg/test/e2e/utils/apiclient/client/preset/list_presets_parameters.go
  pkg/test/e2e/utils/apiclient/client/preset/list_presets_responses.go
  pkg/test/e2e/utils/apiclient/client/preset/list_provider_presets_parameters.go
  pkg/test/e2e/utils/apiclient/client/preset/list_provider_presets_responses.go
  pkg/test/e2e/utils/apiclient/client/preset/preset_client.go
  pkg/test/e2e/utils/apiclient/client/preset/update_preset_parameters.go
  pkg/test/e2e/utils/apiclient/client/preset/update_preset_responses.go
  pkg/test/e2e/utils/apiclient/client/preset/update_preset_status_parameters.go
  pkg/test/e2e/utils/apiclient/client/preset/update_preset_status_responses.go
  pkg/test/e2e/utils/apiclient/models/preset.go
  pkg/test/e2e/utils/apiclient/models/preset_list.go
  pkg/test/e2e/utils/apiclient/models/preset_provider.go
  pkg/test/e2e/utils/apiclient/models/provider_type.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XXL, team/lifecycle, team/ui

#6420 remove kubermatic-operator-util
  Dockerfile
  cmd/kubermatic-operator-util/README.md
  cmd/kubermatic-operator-util/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6387 machine-controller 1.23.1
  codegen/reconcile/main.go
  go.mod
  go.sum
  pkg/clusterdeletion/creation_preventing_webhook.go
  pkg/controller/operator/common/resources.go
  pkg/controller/operator/master/controller.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/seed/controller.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/operator/seed/reconciler_test.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/webhook.go
  pkg/controller/user-cluster-controller-manager/resources/resources/machine-controller/role.go
  pkg/controller/user-cluster-controller-manager/resources/resources/machine-controller/webhook.go
  pkg/resources/cloudconfig/configmap.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/machinecontroller/webhook.go
  pkg/resources/reconciling/zz_generated_reconcile.go
  pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-machine-controller.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XL

#6382 Add service account token volume projection options for user clusters
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-apiserver.yaml
  pkg/resources/test/load_files_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/L

#6301 Enforce TunnelingExposeStrategy feature gate
  cmd/kubermatic-api/options.go
  cmd/master-controller-manager/main.go
  cmd/master-controller-manager/wrappers_ce.go
  cmd/master-controller-manager/wrappers_ee.go
  cmd/seed-controller-manager/main.go
  cmd/seed-controller-manager/options.go
  cmd/seed-controller-manager/wrappers_ce.go
  cmd/seed-controller-manager/wrappers_ee.go
  pkg/controller/operator/common/resources.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/master/resources/kubermatic/master-controller-manager.go
  pkg/controller/operator/seed/reconciler.go
  pkg/crd/kubermatic/v1/utils.go
  pkg/features/features.go
  pkg/validation/cluster/handler.go
  pkg/validation/cluster/handler_test.go
  pkg/validation/seed/builder.go
  pkg/validation/seed/validator.go
  pkg/validation/seed/validator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, sig/networking, size/L

#6349 Add proposal for Openstack in-tree cloud provider to CCM/CSI migration.
  docs/proposals/images/openstack-ccm-migration.jpg
  docs/proposals/openstack-ccm-migration.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6418 [release/v2.14] add admission control configuration for the user cluster API deployment
  api/cmd/image-loader/main.go
  api/cmd/kubermatic-api/swagger.json
  api/pkg/api/v1/types.go
  api/pkg/controller/seed-controller-manager/kubernetes/resources.go
  api/pkg/handler/v1/cluster/cluster.go
  api/pkg/resources/apiserver/admission-control.go
  api/pkg/resources/apiserver/deployment.go
  api/pkg/resources/cluster/cluster.go
  api/pkg/resources/resources.go
  api/pkg/resources/test/fixtures/configmap-aws-1.15.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-aws-1.16.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-aws-1.17.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-aws-1.18.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-azure-1.15.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-azure-1.16.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-azure-1.17.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-azure-1.18.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-bringyourown-1.15.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-bringyourown-1.16.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-bringyourown-1.17.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-bringyourown-1.18.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-digitalocean-1.15.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-digitalocean-1.16.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-digitalocean-1.17.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-digitalocean-1.18.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-openstack-1.15.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-openstack-1.16.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-openstack-1.17.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-openstack-1.18.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-vsphere-1.15.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-vsphere-1.16.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-vsphere-1.17.0-adm-control.yaml
  api/pkg/resources/test/fixtures/configmap-vsphere-1.18.0-adm-control.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.15.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.16.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.17.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-aws-1.18.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.15.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.16.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.17.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-azure-1.18.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.15.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.16.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.15.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.16.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.15.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.16.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.17.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-openstack-1.18.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.15.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.16.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.17.0-apiserver.yaml
  api/pkg/resources/test/fixtures/deployment-vsphere-1.18.0-apiserver.yaml
  api/pkg/resources/test/load_files_test.go
  api/pkg/test/e2e/api/utils/apiclient/models/cluster_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, sig/ui, size/XL

#6423 Expose ServiceAccountSettings in cluster API object
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/common/cluster.go
  pkg/resources/cluster/cluster.go
  pkg/test/e2e/utils/apiclient/models/cluster_spec.go
  pkg/test/e2e/utils/apiclient/models/service_account_settings.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/L

#6426 Disable/Enable UserSSHKey agent in user clusters
  cmd/kubermatic-api/swagger.json
  cmd/user-cluster-controller-manager/main.go
  pkg/api/v1/types.go
  pkg/controller/seed-controller-manager/openshift/testdata/Kubermatic_API_image_is_overwritten-usercluster-controller.golden.yaml
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler_test.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/handler/common/cluster.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/resources/cluster/cluster.go
  pkg/resources/test/fixtures/deployment-aws-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-usercluster-controller.yaml
  pkg/resources/usercluster/deployment.go
  pkg/test/e2e/utils/apiclient/models/cluster_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/L

#6431 [release/v2.15] add admission control configuration for the user cluster API deployment
  cmd/image-loader/main.go
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/handler/common/cluster.go
  pkg/resources/apiserver/admission-control.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/cluster/cluster.go
  pkg/resources/resources.go
  pkg/resources/test/fixtures/configmap-aws-1.17.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-aws-1.18.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-aws-1.19.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-azure-1.17.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-azure-1.18.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-azure-1.19.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.17.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.18.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.19.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.17.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.18.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.19.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.17.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.18.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.19.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.17.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.18.0-adm-control.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.19.0-adm-control.yaml
  pkg/resources/test/fixtures/deployment-aws-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-apiserver.yaml
  pkg/resources/test/load_files_test.go
  pkg/test/e2e/api/utils/apiclient/models/cluster_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#6432 Add provider-level validation to provider NodeSpec
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/api/v1/types_test.go
  pkg/handler/v1/node/node_test.go
  pkg/handler/v2/machine/machine_test.go
  pkg/test/e2e/utils/apiclient/models/azure_node_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, size/XXL

#6440 Add changelogs for 2.14.10 and 2.15.7
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6438 Fix Cluster Admission Webhook
  charts/kubermatic/Chart.yaml
  charts/kubermatic/templates/kubermatic-controller-manager-dep.yaml
  charts/kubermatic/templates/master-controller-manager-dep.yaml
  cmd/master-controller-manager/main.go
  cmd/seed-controller-manager/main.go
  cmd/seed-controller-manager/options.go
  pkg/controller/operator/common/resources.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/master/resources/kubermatic/master-controller-manager.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/operator/seed/resources/kubermatic/admission.go
  pkg/controller/operator/seed/resources/kubermatic/seed-controller-manager.go
  pkg/validation/flags.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/L

#6425 Gatekeeper removal
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/operator/seed/resources/gatekeeper/rbac.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/removal.go
  pkg/resources/gatekeeper/rbac.go
  pkg/resources/gatekeeper/removal.go
  pkg/resources/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/cluster-management, size/L

#6443 Validating ssh key agent deployment
  cmd/seed-controller-manager/main.go
  pkg/validation/cluster/handler.go
  pkg/validation/cluster/handler_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#6221 [etcd] start as a fresh member if data dir is empty
  cmd/etcd-launcher/main.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, sig/cluster-management

#6448 Extend global settings for resource quota
  cmd/kubermatic-api/swagger.json
  pkg/crd/kubermatic/v1/settings.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/v1/admin/settings_test.go
  pkg/provider/kubernetes/settings.go
  pkg/test/e2e/api/settings_test.go
  pkg/test/e2e/utils/apiclient/models/machine_deployment_vm_resource_quota.go
  pkg/test/e2e/utils/apiclient/models/setting_spec.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/L

#6444 documenting the user ssh key agent
  cmd/user-ssh-keys-agent/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#6455 Update the default value of service account token issuer to the URL of apiserver
  cmd/kubermatic-api/swagger.json
  pkg/crd/kubermatic/v1/cluster.go
  pkg/test/e2e/utils/apiclient/models/service_account_settings.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, sig/cluster-management, size/XS

#6445 Deploy envoy-agent for tunneling expose strategy
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/options.go
  cmd/user-cluster-controller-manager/main.go
  pkg/controller/seed-controller-manager/kubernetes/address.go
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/envoy-agent/configmap.go
  pkg/controller/user-cluster-controller-manager/resources/resources/envoy-agent/daemonset.go
  pkg/controller/user-cluster-controller-manager/resources/resources/openvpn/configmap.go
  pkg/resources/address/address.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/apiserver/service.go
  pkg/resources/apiserver/tls-serving-certificate.go
  pkg/resources/data.go
  pkg/resources/resources.go
  pkg/resources/usercluster/deployment.go
  pkg/test/builder.go
  pkg/util/flagopts/ip_flag.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/XL

#6458 introduce resource quota for Alibaba provider
  pkg/handler/common/filter.go
  pkg/handler/common/provider/alibaba.go
  pkg/handler/routes_v1.go
  pkg/handler/v1/provider/alibaba.go
  pkg/handler/v2/provider/alibaba.go
  pkg/handler/v2/routes_v2.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, size/L

#6442 add endpoint to list Vsphere datastores
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/common/provider/vsphere.go
  pkg/handler/v2/provider/vsphere.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/cloud/vsphere/provider.go
  pkg/test/e2e/utils/apiclient/client/vsphere/list_v_sphere_datastores_parameters.go
  pkg/test/e2e/utils/apiclient/client/vsphere/list_v_sphere_datastores_responses.go
  pkg/test/e2e/utils/apiclient/client/vsphere/vsphere_client.go
  pkg/test/e2e/utils/apiclient/models/v_sphere_datastore_list.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/api, sig/cluster-management, size/XL

#6467 Relax memory limit for openvpn container
  pkg/resources/openvpn/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-openvpn-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-openvpn-server.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/cluster-management, size/L

#6470 add 2.16 changelog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
