Repository kubermatic/kubermatic, pull requests merged in 2021-12, with the labels that each got.

#8283 added support for multiple destinations for etcd backups controller
  cmd/seed-controller-manager/controllers.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8334 AKS upgrades
  pkg/handler/common/provider/azure.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/upgrade.go
  pkg/handler/v2/provider/azure.go
  pkg/provider/cloud/azure/provider.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#8305 Deploy metrics-server in user cluster if Konnectivity is enabled
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/metrics-server/clusterrolebinding.go
  pkg/controller/user-cluster-controller-manager/resources/resources/metrics-server/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/metrics-server/rolebinding.go
  pkg/controller/user-cluster-controller-manager/resources/resources/metrics-server/service.go
  pkg/controller/user-cluster-controller-manager/resources/resources/metrics-server/serviceaccount.go
  pkg/resources/konnectivity/secrets.go
  pkg/resources/konnectivity/seedagent.go
  pkg/resources/resources.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8300 enable cortex and loki monitoring
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/dashboards/mla/mla-components.json
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/rules/src/usercluster-mla/cortex.yaml
  charts/monitoring/prometheus/rules/src/usercluster-mla/loki-distributed.yaml
  charts/monitoring/prometheus/rules/usercluster-mla-cortex.yaml
  charts/monitoring/prometheus/rules/usercluster-mla-loki-distributed.yaml
  charts/monitoring/prometheus/values.yaml
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#8331 add endpoints for GKE resources
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/common/provider/gcp.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/provider/gcp.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/gke/gke_client.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_cluster_disk_types_parameters.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_cluster_disk_types_responses.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_cluster_images_parameters.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_cluster_images_responses.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_cluster_sizes_parameters.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_cluster_sizes_responses.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_cluster_zones_parameters.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_cluster_zones_responses.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_images_parameters.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_images_responses.go
  pkg/test/e2e/utils/apiclient/client/gke/validate_g_k_e_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/gke/validate_g_k_e_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/project/list_g_k_e_clusters_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/list_g_k_e_clusters_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_image.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_image_list.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_zone.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_zone_list.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8339 Add SeedDNSOverwrite to seedsettings
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/seedsettings/seedsettings.go
  pkg/test/e2e/utils/apiclient/models/seed_settings.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8332 Update kubermatic-operator chart
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_presets.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8276 Convert Addon Proposal to Application Proposal
  docs/proposals/images/improveaddons-architecture.png
  docs/proposals/images/improveaddons-user-flows.png
  docs/proposals/images/introduceapps-architecture.png
  docs/proposals/images/introduceapps-user-flows.png
  docs/proposals/improve-addons.md
  docs/proposals/introduce-apps.md
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes

#8266 Proposal for encryption-at-rest (etcd data encryption)
  docs/proposals/encryption-at-rest.md
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes

#8341 Seed backup destination list API endpoint
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/test/helper.go
  pkg/handler/v1/project/project_test.go
  pkg/handler/v2/backupdestinations/backupdestinations.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/cluster.go
  pkg/provider/kubernetes/cluster_test.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/project/get_backup_destination_names_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/get_backup_destination_names_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/utils/apiclient/models/backup_destination_names.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#8213 Azure Cloud Provider Reconciliation
  pkg/provider/cloud/azure/availability_set.go
  pkg/provider/cloud/azure/availability_set_test.go
  pkg/provider/cloud/azure/client.go
  pkg/provider/cloud/azure/provider.go
  pkg/provider/cloud/azure/resource_group.go
  pkg/provider/cloud/azure/resource_group_test.go
  pkg/provider/cloud/azure/route_table.go
  pkg/provider/cloud/azure/security_group.go
  pkg/provider/cloud/azure/subnet.go
  pkg/provider/cloud/azure/utils.go
  pkg/provider/cloud/azure/utils_test.go
  pkg/provider/cloud/azure/vnet.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8333 Enable nginx-ingress chart migration in the installer, re-enable validating webhooks
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
  charts/nginx-ingress-controller/values.yaml
  cmd/kubermatic-installer/cmd_deploy.go
  pkg/install/stack/kubermatic-master/nginxingress.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/stack/types.go
Labels: size/XXL, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/cluster-management, sig/app-management

#8343 Rename kubermaticv1.PresetProvider to ProviderPreset
  cmd/kubermatic-api/main.go
  pkg/controller/operator/defaults/defaults.go
  pkg/controller/seed-controller-manager/cloud/cloud_controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/crd/kubermatic/v1/helper/preset.go
  pkg/crd/kubermatic/v1/preset.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/common/cluster.go
  pkg/handler/common/upgrade.go
  pkg/handler/routes_v1.go
  pkg/handler/routing.go
  pkg/handler/test/hack/hack.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v1/cluster/upgrade_test.go
  pkg/handler/v1/common/common.go
  pkg/handler/v1/dc/datacenter.go
  pkg/handler/v1/presets/credentials.go
  pkg/handler/v1/presets/credentials_test.go
  pkg/handler/v1/provider/alibaba.go
  pkg/handler/v1/provider/anexia.go
  pkg/handler/v1/provider/aws.go
  pkg/handler/v1/provider/azure.go
  pkg/handler/v1/provider/digitalocean.go
  pkg/handler/v1/provider/gcp.go
  pkg/handler/v1/provider/hetzner.go
  pkg/handler/v1/provider/openstack.go
  pkg/handler/v1/provider/packet.go
  pkg/handler/v1/provider/vsphere.go
  pkg/handler/v2/cluster/upgrade_test.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/preset/preset.go
  pkg/handler/v2/preset/preset_test.go
  pkg/handler/v2/provider/aws.go
  pkg/handler/v2/provider/azure.go
  pkg/handler/v2/provider/gcp.go
  pkg/handler/v2/provider/vsphere.go
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/routing.go
  pkg/handler/v2/version/version.go
  pkg/handler/v2/version/version_test.go
  pkg/install/crdmigration/clones.go
  pkg/provider/kubernetes/external_cluster_test.go
  pkg/provider/kubernetes/preset.go
  pkg/provider/kubernetes/preset_test.go
  pkg/provider/types.go
  pkg/resources/cloudcontroller/util.go
  pkg/resources/data.go
  pkg/version/version_test.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8345 Explicitly set metrics-server service type to ClusterIP in Konnectivity setup
  pkg/controller/user-cluster-controller-manager/resources/resources/metrics-server/service.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#8323 Update lastSeen and user watcher handling
  pkg/api/v1/types.go
  pkg/controller/master-controller-manager/user-synchronizer/controller_test.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/fake/fake_user.go
  pkg/crd/client/clientset/versioned/typed/kubermatic/v1/user.go
  pkg/crd/kubermatic/v1/user.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/middleware/middleware.go
  pkg/handler/test/helper.go
  pkg/watcher/kubernetes/user.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8326 Seccomp profiles for user cluster pods
  addons/aws-node-termination-handler/aws-node-termination-handler.yaml
  addons/canal/canal_v3.19.yaml
  addons/canal/canal_v3.20.yaml
  addons/cilium/cilium.yaml
  addons/cluster-autoscaler/cluster-autoscaler.yaml
  addons/node-exporter/daemonset.yaml
  cmd/conformance-tests/runner.go
  cmd/conformance-tests/usercluster_controller_tests.go
  pkg/controller/user-cluster-controller-manager/resources/resources/core-dns/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/envoy-agent/daemonset.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/kubernetes-dashboard/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/metrics-server/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/promtail/daemonset.go
  pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/deamonset.go
  pkg/controller/user-cluster-controller-manager/resources/resources/usersshkeys/daemonset.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#8351 List AKS nodepool upgrades
  pkg/handler/common/provider/azure.go
  pkg/handler/v2/external_cluster/upgrade.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#8359 add changelog for 2.17.5
  CHANGELOG.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#8358 Fix missing CNIPlugin in api MarshalJSON
  pkg/api/v1/types.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/api

#8340 Fix Konnectivity with NodePort / LB expose strategy
  cmd/user-cluster-controller-manager/main.go
  hack/run-user-cluster-controller-manager.sh
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/deployment.go
  pkg/resources/data.go
  pkg/resources/konnectivity/tls-cert.go
  pkg/resources/test/fixtures/deployment-aws-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-usercluster-controller.yaml
  pkg/resources/usercluster/deployment.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8354 fix typo providers/gke/validatecredentials
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/routes_v2.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#8349 get and update nodepool replicas
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/node.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/api

#8360 Add Kubevirt client
  go.mod
  go.sum
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/clientset.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/doc.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/fake/clientset_generated.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/fake/doc.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/fake/register.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/scheme/doc.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/scheme/register.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/core_client.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/doc.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/fake/doc.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/fake/fake_core_client.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/fake/fake_kubevirt.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/fake/fake_virtualmachine.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/fake/fake_virtualmachineinstance.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/fake/fake_virtualmachineinstancemigration.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/fake/fake_virtualmachineinstancepreset.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/fake/fake_virtualmachineinstancereplicaset.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/generated_expansion.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/kubevirt.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/virtualmachine.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/virtualmachineinstance.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/virtualmachineinstancemigration.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/virtualmachineinstancepreset.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/virtualmachineinstancereplicaset.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/virtualization

#8370 fix presets for gke, aks and eks providers
  pkg/crd/kubermatic/v1/preset.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#8327 Making source IP addresses configurable
  .golangci.yml
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/install/crdmigration/clones.go
  pkg/provider/cloud/aws/security_group.go
  pkg/provider/cloud/aws/security_group_test.go
  pkg/provider/cloud/azure/security_group.go
  pkg/provider/cloud/gcp/provider.go
  pkg/provider/cloud/openstack/helper.go
  pkg/provider/cloud/openstack/provider.go
  pkg/test/e2e/utils/apiclient/models/a_w_s_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/azure_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/g_c_p_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/openstack_cloud_spec.go
  pkg/validation/cluster.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd, sig/crd/synced

#8395 Another CRD sync
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_users.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/helper/preset.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/apis/kubermatic/v1/user.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/install/crdmigration/clones.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#8252 Use upstream helm chart for loki as a dependency
  charts/logging/loki/Chart.yaml
  charts/logging/loki/requirements.lock
  charts/logging/loki/templates/_helpers.tpl
  charts/logging/loki/templates/role.yaml
  charts/logging/loki/templates/secret.yaml
  charts/logging/loki/templates/service.yaml
  charts/logging/loki/templates/serviceaccount.yaml
  charts/logging/loki/templates/statefulset.yaml
  charts/logging/loki/test/default.yaml
  charts/logging/loki/test/default.yaml.out
  charts/logging/loki/test/test.sh
  charts/logging/loki/test/values.example.ce.yaml
  charts/logging/loki/test/values.example.ce.yaml.out
  charts/logging/loki/test/values.example.ee.yaml
  charts/logging/loki/test/values.example.ee.yaml.out
  charts/logging/loki/values.yaml
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#8344 Default service account token mount
  pkg/controller/seed-controller-manager/update/update_controller.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/resources/machine/machinedeployment.go
  pkg/resources/resources.go
Labels: release-note-action-required, lgtm, approved, size/M, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8394 [release/v2.18] Fix CNI reconciliation issue after upgrade to k8s 1.22
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/validation/validation.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes

#8406 Fix typos in import endpoint
  pkg/handler/v2/external_cluster/external_cluster.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#8398 figure out weather to use https or http for minio access
  pkg/ee/metering/report_handler.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#8361 Run Konnectivity agent in HA mode + misc Konnectivity improvements
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/deployment.go
  pkg/resources/konnectivity/sidecar.go
  pkg/resources/resources.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8417 AKS,EKS credential validity
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/provider/aws.go
  pkg/handler/common/provider/azure.go
  pkg/handler/v2/provider/aws.go
  pkg/handler/v2/provider/azure.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/aks/aks_client.go
  pkg/test/e2e/utils/apiclient/client/aks/validate_a_k_s_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/aks/validate_a_k_s_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/eks_client.go
  pkg/test/e2e/utils/apiclient/client/eks/validate_e_k_s_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/validate_e_k_s_credentials_responses.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8414 Add additional seccomp profiles to CSI addons
  addons/csi/hetzner/hcloud-csi-1.6.0.yaml
  addons/csi/openstack/controllerplugin.yaml
  addons/csi/openstack/nodeplugin.yaml
  addons/csi/vsphere/csiController.yaml
  addons/csi/vsphere/csiNode-ds.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#8337 Add anti-affinity for nodeport proxy envoy
  cmd/image-loader/main.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/operator/seed/resources/nodeportproxy/deployments.go
  pkg/resources/antiaffinity.go
  pkg/resources/etcd/statefulset.go
  pkg/resources/nodeportproxy/nodeportproxy.go
  pkg/test/e2e/nodeport-proxy/deployer.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#8422 Enable annotations for metrics scraping in nginx-ingress
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
  charts/nginx-ingress-controller/values.yaml
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#8419 Fix apiserver NetworkPolicy for OIDC issuer - allow local path & IP address in URL
  pkg/resources/apiserver/networkpolicy.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#8423 Modify AKS, EKS Cluster List endpoint path
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/provider/aws.go
  pkg/handler/common/provider/azure.go
  pkg/handler/v2/provider/aws.go
  pkg/handler/v2/provider/azure.go
  pkg/handler/v2/provider/gcp.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/aks/aks_client.go
  pkg/test/e2e/utils/apiclient/client/aks/validate_a_k_s_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/eks_client.go
  pkg/test/e2e/utils/apiclient/client/eks/validate_e_k_s_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/list_a_k_s_clusters_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/list_a_k_s_clusters_responses.go
  pkg/test/e2e/utils/apiclient/client/project/list_e_k_s_clusters_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/list_e_k_s_clusters_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#8425 add tolerations to user-cluster system components
  pkg/controller/user-cluster-controller-manager/resources/resources/envoy-agent/daemonset.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/promtail/daemonset.go
  pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/deamonset.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#8404 Fix flaky admin api e2e test
  pkg/controller/master-controller-manager/project-synchronizer/controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#8396 Fix CNI reconciliation issue after upgrade to k8s 1.22
  pkg/webhook/cluster/mutation/mutation.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes

#8399 Create AKS nodepool
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/node.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_machine_deployment_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/agent_pool_basics.go
  pkg/test/e2e/utils/apiclient/models/agent_pool_optional_settings.go
  pkg/test/e2e/utils/apiclient/models/agent_pool_upgrade_settings.go
  pkg/test/e2e/utils/apiclient/models/external_cluster_machine_deployment_cloud_spec.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#8449 Add missing CNIPlugin bolierplate into PatchEndpoint
  pkg/handler/common/cluster.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#8454 add external cluster status
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/test/e2e/utils/apiclient/models/external_cluster.go
  pkg/test/e2e/utils/apiclient/models/external_cluster_spec.go
  pkg/test/e2e/utils/apiclient/models/external_cluster_state.go
  pkg/test/e2e/utils/apiclient/models/external_cluster_status.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8416 Kubevirt csi driver integration
  addons/csi/kubevirt/csi-driver-operator.yaml
  charts/kubermatic/Chart.yaml
  docs/zz_generated.addondata.go.txt
  pkg/provider/cloud/kubevirt/client.go
  pkg/provider/cloud/kubevirt/reconciler.go
  pkg/provider/cloud/kubevirt/storage.go
  pkg/provider/kubernetes/credentials.go
  pkg/resources/credentials.go
  pkg/resources/resources.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, sig/crd

#8456 Etcd restore update api
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/test/helper.go
  pkg/handler/v2/etcdrestore/etcdrestore.go
  pkg/test/e2e/utils/apiclient/models/etcd_restore_spec.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8397 Gatekeeper adjustable resource limits
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/deployment.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/test/e2e/utils/apiclient/models/o_p_a_integration_settings.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd, sig/crd/synced

#8457 Extend eks preset for region
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/crd/kubermatic/v1/preset.go
  pkg/handler/common/provider/aws.go
  pkg/handler/common/provider/azure.go
  pkg/handler/v2/provider/aws.go
  pkg/handler/v2/provider/azure.go
  pkg/test/e2e/utils/apiclient/client/eks/validate_e_k_s_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/list_e_k_s_clusters_parameters.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_cluster.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8415 extend endpoint to create native GKE cluster
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_autoprovisioning_node_pool_defaults.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_cluster_autoscaling.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_cluster_spec.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_node_config.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_resource_limit.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_shielded_instance_config.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_upgrade_settings.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8460 fix AKS credentials from preset
  pkg/handler/v2/provider/azure.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#8420 [release/v2.18] Fix variable name for certificate secrets in minio chart
  charts/minio/Chart.yaml
  charts/minio/templates/deployment.yaml
  charts/minio/values.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#8446 [release/v2.18] add tolerations to user-cluster system components
  pkg/controller/user-cluster-controller-manager/resources/resources/envoy-agent/daemonset.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/promtail/daemonset.go
  pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/deamonset.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#8450 Update cilium
  addons/cilium/cilium.yaml
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
  pkg/webhook/cluster/validation/validation.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#8467 add prometheus scraping if minio is running with TLS
  charts/minio/Chart.yaml
  charts/minio/values.yaml
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/config/scraping/minio.yaml
  charts/monitoring/prometheus/config/scraping/pods.yaml
  charts/monitoring/prometheus/values.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management

#8470 Fix cilium indentation
  addons/cilium/cilium.yaml
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#8471 handle external cluster status
  pkg/api/v2/types.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/routes_v2.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8461 Add application definition cr
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  hack/update-codegen.sh
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/apis/apps.kubermatic/v1/doc.go
  pkg/apis/apps.kubermatic/v1/register.go
  pkg/apis/apps.kubermatic/v1/types.go
  pkg/apis/apps.kubermatic/v1/zz_generated.deepcopy.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd, sig/crd/synced

#8466 fix isImport externalcluster
  pkg/handler/common/provider/aws.go
  pkg/handler/common/provider/azure.go
  pkg/handler/common/provider/gcp.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8477 Add Waleed to sig-cluster-management
  OWNERS_ALIASES
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8473 Add the basic deployment for osm
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/operatingsystemmanager/common.go
  pkg/resources/operatingsystemmanager/deployment.go
  pkg/resources/resources.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8282 network policies for user cluster kube-system namespace
  addons/canal/canal.yaml
  addons/canal/canal_v3.19.yaml
  addons/canal/canal_v3.20.yaml
  addons/cilium/cilium.yaml
  addons/csi/hetzner/hcloud-csi-1.6.0.yaml
  addons/csi/openstack/controllerplugin.yaml
  addons/csi/vsphere/csiAdmissionWebhook.yaml
  addons/csi/vsphere/csiController.yaml
  addons/kube-proxy/configmap.yaml
  addons/kube-state-metrics/networkpolicy.yaml
  addons/node-exporter/networkpolicy.yaml
  addons/openvpn/networkpolicy.yaml
  cmd/user-cluster-controller-manager/main.go
  docs/zz_generated.addondata.go.txt
  pkg/addon/template.go
  pkg/controller/operator/common/resources.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/core-dns/networkpolicy.go
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/networkpolicy.go
  pkg/controller/user-cluster-controller-manager/resources/resources/kubesystem/networkpolicy.go
  pkg/controller/user-cluster-controller-manager/resources/resources/metrics-server/networkpolicy.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/namespace.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/promtail/daemonset.go
  pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/deamonset.go
  pkg/controller/user-cluster-controller-manager/resources/resources/usersshkeys/networkpolicy.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/resources/resources.go
  pkg/resources/usercluster/deployment.go
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/crd

#8479 [release/v2.18] Bump Flannel version in Canal to v0.15.1
  addons/canal/canal_v3.19.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#8478 Bump Flannel version in Canal to v0.15.1
  addons/canal/canal_v3.19.yaml
  addons/canal/canal_v3.20.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#8472 Add Kubernetes 1.22.5, 1.21.8, 1.20.14 and update to Go 1.17.5
  .prow.yaml
  Makefile
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  docs/adding-kubernetes-versions.md
  docs/zz_generated.kubermaticConfiguration.yaml
  go.mod
  go.sum
  hack/ci/testdata/crdmigration/seed/05-cluster.yaml
  hack/gen-api-client.sh
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/update-kubermatic-chart.sh
  hack/update-swagger.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
  pkg/addon/template_test.go
  pkg/controller/operator/defaults/defaults.go
  pkg/controller/seed-controller-manager/backup/backup_controller_test.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller_test.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/test/e2e/ccm-migration/ccm_migration_suite_test.go
  pkg/test/e2e/expose-strategy/expose_strategy_suite_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#8481 [release/v2.18] Bump Kubernetes versions to 1.20.14, 1.21.8, 1.22.5 and use Go 1.16.12
  .prow.yaml
  Makefile
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/updates.yaml
  charts/kubermatic/static/master/versions.yaml
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  docs/zz_generated.kubermaticConfiguration.yaml
  go.mod
  go.sum
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/update-kubermatic-chart.sh
  hack/update-swagger.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
  pkg/addon/template_test.go
  pkg/controller/operator/common/defaults.go
  pkg/controller/seed-controller-manager/backup/backup_controller_test.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller_test.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#8458 fix flaky API e2e tests
  pkg/controller/master-controller-manager/project-synchronizer/controller.go
  pkg/controller/master-controller-manager/project-synchronizer/controller_test.go
  pkg/test/e2e/utils/client.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#8346 Refactor Cluster Defaulting & Validation
  cmd/example-yaml-generator/main.go
  cmd/image-loader/main.go
  cmd/kubermatic-api/swagger.json
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/main.go
  cmd/seed-controller-manager/options.go
  docs/cluster-defaulting-validation.md
  docs/zz_generated.seed.yaml
  hack/run-ccm-migration-e2e-test-in-kind.sh
  pkg/controller/operator/defaults/defaults.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/operator/seed/resources/kubermatic/seed-controller-manager.go
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/seed-controller-manager/monitoring/monitoring_controller.go
  pkg/controller/seed-controller-manager/monitoring/resources.go
  pkg/crd/kubermatic/v1/common.go
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/crd/kubermatic/v1/datacenter_test.go
  pkg/defaulting/cluster.go
  pkg/handler/common/cluster.go
  pkg/handler/routes_v1.go
  pkg/handler/routing.go
  pkg/handler/test/hack/hack.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/routing.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/configuration.go
  pkg/provider/types.go
  pkg/resources/cluster/cluster.go
  pkg/resources/data.go
  pkg/resources/resources.go
  pkg/test/e2e/api/credentials_test.go
  pkg/test/e2e/ccm-migration/ccm_migration_test.go
  pkg/test/e2e/ccm-migration/cluster.go
  pkg/test/e2e/mla/mla_test.go
  pkg/test/e2e/nodeport-proxy/deployer.go
  pkg/test/helper.go
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
  pkg/webhook/cluster/validation/validation.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8486 Periodic sync of old CRD types to new
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/common.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/datacenter_test.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/install/crdmigration/clones.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#8487 Fix missing feature gates for validation in api
  cmd/kubermatic-api/main.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#8484 Add changelog for KKP 2.18.4
  CHANGELOG.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#8485 Fix for Kubesystem network policiies
  pkg/controller/user-cluster-controller-manager/resources/resources/metrics-server/networkpolicy.go
  pkg/resources/usercluster/deployment.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8480 Add ApplicationInstallation CRD
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/apis/apps.kubermatic/v1/register.go
  pkg/apis/apps.kubermatic/v1/zz_generated.deepcopy.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#8483 CNI version API
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/defaulting/cluster.go
  pkg/handler/v2/cniversion/cniversion.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/cniversion/cniversion_client.go
  pkg/test/e2e/utils/apiclient/client/cniversion/list_versions_by_c_n_i_plugin_parameters.go
  pkg/test/e2e/utils/apiclient/client/cniversion/list_versions_by_c_n_i_plugin_responses.go
  pkg/test/e2e/utils/apiclient/client/kubermatic_kubernetes_platform_api_client.go
  pkg/test/e2e/utils/apiclient/client/project/list_c_n_i_plugin_versions_for_cluster_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/list_c_n_i_plugin_versions_for_cluster_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/utils/apiclient/models/c_n_i_versions.go
  pkg/validation/cluster.go
  pkg/version/cni/version.go
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#8500 Fix forgotten to regenerate CRD
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8469 Add support for switching between OpenVPN and Konnectivity
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/clusterrolebinding.go
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/deletion.go
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/serviceaccount.go
  pkg/controller/user-cluster-controller-manager/resources/resources/metrics-server/deletion.go
  pkg/controller/user-cluster-controller-manager/resources/resources/openvpn/deletion.go
  pkg/resources/apiserver/networkpolicy.go
  pkg/resources/dns/deletion.go
  pkg/resources/konnectivity/deletion.go
  pkg/resources/metrics-server/deletion.go
  pkg/resources/openvpn/deletion.go
  pkg/resources/resources.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8504 move gke functionality to provider gke package
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/handler/common/provider/gcp.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/external_cluster/upgrade.go
  pkg/handler/v2/provider/gcp.go
  pkg/provider/cloud/gcp/provider.go
  pkg/provider/cloud/gke/provider.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#8494 fix listing security groups
  cmd/kubermatic-api/swagger.json
  pkg/handler/v1/provider/aws.go
  pkg/provider/cloud/aws/api.go
  pkg/test/e2e/utils/apiclient/client/aws/list_a_w_s_security_groups_parameters.go
  pkg/test/e2e/utils/apiclient/client/aws/list_a_w_s_subnets_parameters.go
  pkg/test/e2e/utils/apiclient/client/aws/list_a_w_s_v_p_c_s_parameters.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#8511 fix cni versions model
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/test/e2e/utils/apiclient/models/c_n_i_versions.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8507 fix mla namespace component labels set
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/namespace.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#8508 Add aks clusterspec
  pkg/handler/v2/external_cluster/external_cluster.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#8512 Backupdestinations delete API
  cmd/kubermatic-api/swagger.json
  pkg/handler/routes_v1_admin.go
  pkg/handler/v1/admin/backupdestination.go
  pkg/handler/v1/admin/backupdestination_test.go
  pkg/test/e2e/utils/apiclient/client/admin/admin_client.go
  pkg/test/e2e/utils/apiclient/client/admin/delete_backup_destination_parameters.go
  pkg/test/e2e/utils/apiclient/client/admin/delete_backup_destination_responses.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#8516 Allow ebpf proxy mode only if Konnectivity is enabled
  pkg/validation/cluster.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#8518 Fix rbac for kubevirt-csi-driver-operator
  addons/csi/kubevirt/csi-driver-operator.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, sig/virtualization

#8515 add events for external cluster
  cmd/kubermatic-api/main.go
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/handler/v2/external_cluster/node.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8451 Add EventRateLimit to allowed admission plugins
  pkg/handler/common/cluster.go
  pkg/handler/v1/admission-plugin/admission_plugin.go
  pkg/handler/v1/admission-plugin/admission_plugin_test.go
  pkg/resources/cluster/cluster.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#8505 Vsphere ccm csi
  addons/csi/vsphere/csiController-rbac.yaml
  addons/csi/vsphere/csiController.yaml
  addons/csi/vsphere/csiNode-ds.yaml
  addons/csi/vsphere/csiNode-rbac.yaml
  addons/csi/vsphere/driver.yaml
  addons/csi/vsphere/vsphere-csi-driver.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/defaults/defaults.go
  pkg/resources/cloudcontroller/deployment.go
  pkg/resources/cloudcontroller/vsphere.go
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-vsphere-cloud-controller-manager-externalCloudProvider.yaml
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#8519 Fix an issue with user NPE during lastSeen update
  pkg/handler/middleware/middleware.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#8523 Support for OSM in KKP
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/install/crdmigration/clones.go
  pkg/resources/cluster/cluster.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/machinecontroller/webhook.go
  pkg/test/e2e/utils/apiclient/models/cluster_spec.go
  pkg/validation/cluster.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd, sig/crd/synced

#8529 Refactor AKS and EKS methods
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/handler/common/provider/aks.go
  pkg/handler/common/provider/aws.go
  pkg/handler/common/provider/azure.go
  pkg/handler/common/provider/eks.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/upgrade.go
  pkg/handler/v2/provider/aks.go
  pkg/handler/v2/provider/aws.go
  pkg/handler/v2/provider/azure.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/cloud/aks/provider.go
  pkg/provider/cloud/aws/api.go
  pkg/provider/cloud/azure/provider.go
  pkg/provider/cloud/eks/provider.go
  pkg/provider/cloud/gke/provider.go
  pkg/resources/credentials.go
  pkg/test/e2e/utils/apiclient/client/kubermatic_kubernetes_platform_api_client.go
  pkg/test/e2e/utils/apiclient/client/regions/list_a_w_s_regions_parameters.go
  pkg/test/e2e/utils/apiclient/client/regions/list_a_w_s_regions_responses.go
  pkg/test/e2e/utils/apiclient/client/regions/regions_client.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#8527 Enhance CNI versioning & webhooks
  pkg/addon/template.go
  pkg/validation/cluster.go
  pkg/version/cni/version.go
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes

#8534 Vsphere csi fix
  addons/csi/vsphere/vsphere-csi-driver.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#8521 handle kubeconfig error status
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/node.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8528 deploy OSM CRDs using kubermatic operator
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_operatingsystemconfig.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_operatingsystemprofile.yaml
  pkg/features/features.go
  pkg/install/crdmigration/setup.go
  pkg/install/stack/kubermatic-master/certmanager.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/util/crd.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8538 Enhance CNI/networking addons handling
  addons/kube-proxy/clusterrolebinding.yaml
  addons/kube-proxy/configmap.yaml
  addons/kube-proxy/daemonset.yaml
  addons/kube-proxy/serviceaccount.yaml
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#8541 Fix GetAllowedCNIPluginVersions handling
  pkg/version/cni/version.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#8544 check cluster status to get upgrade endpoints
  pkg/handler/v2/external_cluster/upgrade.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8530 bump konnectivity version to v0.0.27
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/deployment.go
  pkg/resources/konnectivity/sidecar.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#8545 Disable network policies for kube-system
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8548 Add Hubble addon
  addons/cilium/cilium.yaml
  addons/hubble/hubble.yaml
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/accessible-addons.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/defaults/defaults.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#8525 validate zone_suffixes is not empty
  pkg/resources/cloudconfig/configmap.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#8503 Add webhooks for validating OSC and OSP
  cmd/seed-controller-manager/main.go
  go.mod
  go.sum
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/operator/seed/resources/kubermatic/admission.go
  pkg/install/crdmigration/shutdown.go
  pkg/webhook/operatingsystemmanager/operatingsystemconfig/validation/validation.go
  pkg/webhook/operatingsystemmanager/operatingsystemconfig/validation/validation_test.go
  pkg/webhook/operatingsystemmanager/operatingsystemprofile/validation/validation.go
  pkg/webhook/operatingsystemmanager/operatingsystemprofile/validation/validation_test.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8550 fix get gke upgrades
  pkg/provider/cloud/gke/provider.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#8352 Add ProviderName to CloudSpec, so we can have it as a printer column
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/crd-clusters.yaml
  cmd/kubermatic-api/swagger.json
  pkg/crd/kubermatic/v1/cluster.go
  pkg/defaulting/cluster.go
  pkg/kubernetes/helper.go
  pkg/test/e2e/utils/apiclient/models/cloud_spec.go
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
  pkg/webhook/cluster/mutation/mutation_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8533 enable auto backups/restore for multiple backups destinations
  pkg/controller/operator/seed/resources/kubermatic/kubermatic.go
  pkg/controller/operator/seed/resources/kubermatic/seed-controller-manager.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#8554 Fix creation of ClusterRole in cert-manager chart
  charts/cert-manager/Chart.yaml
  charts/cert-manager/templates/cert-manager-rbac.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#8392 Use upstream helm chart for cert-manager as a dependency
  charts/cert-manager/Chart.yaml
  charts/cert-manager/requirements.lock
  charts/cert-manager/templates/cainjector-deployment.yaml
  charts/cert-manager/templates/cainjector-rbac.yaml
  charts/cert-manager/templates/cainjector-serviceaccount.yaml
  charts/cert-manager/templates/cert-manager-deployment.yaml
  charts/cert-manager/templates/cert-manager-rbac.yaml
  charts/cert-manager/templates/cert-manager-serviceaccount.yaml
  charts/cert-manager/templates/clusterissuer.yaml
  charts/cert-manager/templates/webhook-deployment.yaml
  charts/cert-manager/templates/webhook-mutating-webhook.yaml
  charts/cert-manager/templates/webhook-rbac.yaml
  charts/cert-manager/templates/webhook-serviceaccount.yaml
  charts/cert-manager/templates/webhook-validating-webhook.yaml
  charts/cert-manager/test/certificate.yaml
  charts/cert-manager/test/default.yaml
  charts/cert-manager/test/default.yaml.out
  charts/cert-manager/test/test-certmanager.sh
  charts/cert-manager/test/test-render.sh
  charts/cert-manager/test/test-values.yaml
  charts/cert-manager/test/test.sh
  charts/cert-manager/values.yaml
  cmd/kubermatic-installer/cmd_deploy.go
  hack/ci/deploy.sh
  pkg/install/stack/kubermatic-master/certmanager.go
  pkg/install/stack/kubermatic-master/nginxingress.go
  pkg/install/stack/types.go
Labels: size/XXL, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/cluster-management, sig/app-management

#8555 Change cert-manager's upgrade procedure
  pkg/install/stack/kubermatic-master/certmanager.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management
