Repository kubermatic/kubermatic, pull requests merged in 2021-10, with the labels that each got.

#7927 Add configurable root_url for grafana
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/config/grafana.ini
  charts/monitoring/grafana/values.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#7930 [release/v2.18] Add configurable root_url for grafana (#7927)
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/config/grafana.ini
  charts/monitoring/grafana/values.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#7896 Fixed issue where EtcdBackupConfigs ID was equal to its name
  pkg/handler/test/helper.go
  pkg/handler/v2/etcdbackupconfig/etcdbackupconfig.go
  pkg/handler/v2/etcdbackupconfig/etcdbackupconfig_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/api

#7880 Add competitive landscape overview to platform extension proposal
  docs/proposals/platform-extensions.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#7935 CaBundle for csi
  addons/csi/openstack/controllerplugin.yaml
  addons/csi/openstack/nodeplugin.yaml
  addons/csi/vsphere/csiAdmissionWebhook.yaml
  addons/csi/vsphere/csiController.yaml
  addons/csi/vsphere/csiNode-ds.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management

#8116 fix api client usage
  cmd/seed-controller-manager/main.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8117 Sync pkg/crd/kubermatic/v1 APIs to pkg/apis/kubermatic/v1
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/cluster_templates.go
  pkg/apis/kubermatic/v1/constraint.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/etcd_backup_config.go
  pkg/apis/kubermatic/v1/etcd_restore.go
  pkg/apis/kubermatic/v1/external_cluster.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/apis/kubermatic/v1/user.go
  pkg/install/crdmigration/clones.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd
