Repository kubermatic/kubermatic, pull requests merged in 2021-08, with the labels that each got.

#7432 Fix OIDC params endpoint
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/routes_v2.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, size/XS

#7254 Ensure non-colliding pprof ports when running locally
  hack/run-master-controller-manager.sh
  hack/run-operator.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#7443 add extra args support to prometheus chart
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/templates/statefulset.yaml
  charts/monitoring/prometheus/values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/app-management, size/S

#7456 Remove non-existing field from kube-proxy configmap
  addons/kube-proxy/configmap.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/app-management, size/XS

#7458 use API time model
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/etcdbackupconfig/etcdbackupconfig.go
  pkg/handler/v2/etcdrestore/etcdrestore.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/api, size/L

#7459 prevent kubevirt kubeconfig from confusing the conformance tester
  cmd/conformance-tests/main.go
  hack/ci/run-conformance-tests.sh
  hack/run-conformance-tests.sh
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#7444 [promtail] kubelet log capturing and kubernetes event capturing
  charts/logging/promtail/Chart.yaml
  charts/logging/promtail/templates/daemonset.yaml
  charts/logging/promtail/values.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management

#7463 fix run_if_changed trigger for pre-kubermatic-ccm-migration-e2e
  .prow.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#7465 bump go-swagger to v0.27.0
  go.mod
  go.sum
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes

#7474 Revert "[promtail] kubelet log capturing and kubernetes event capturing"
  charts/logging/promtail/Chart.yaml
  charts/logging/promtail/templates/daemonset.yaml
  charts/logging/promtail/values.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management

#7439 update karma to 0.89
  charts/monitoring/karma/Chart.yaml
  charts/monitoring/karma/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#7438 update Alertmanager to 0.22.2
  charts/monitoring/alertmanager/Chart.yaml
  charts/monitoring/alertmanager/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#7440 Fix cluster list endpoint and improve error codes
  pkg/handler/common/cluster.go
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/provider/conversions.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/api

#7445 Stop assigning availability set unconditionally
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/api/v1/types_test.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/provider/cloud/azure/provider.go
  pkg/resources/machine/common.go
  pkg/test/e2e/utils/apiclient/models/azure_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/azure_node_spec.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#7441 update to kube-state-metrics 2.1.1
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/dashboards/kubernetes/pods.json
  charts/monitoring/grafana/dashboards/kubernetes/resources-cluster.json
  charts/monitoring/grafana/dashboards/kubernetes/resources-namespace.json
  charts/monitoring/grafana/dashboards/kubernetes/resources-pod.json
  charts/monitoring/kube-state-metrics/Chart.yaml
  charts/monitoring/kube-state-metrics/values.yaml
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/rules/general-cadvisor.yaml
  charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/src/general/cadvisor.yaml
  charts/monitoring/prometheus/rules/src/general/kube-state-metrics.yaml
  pkg/resources/kubestatemetrics/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.17.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.18.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.19.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.17.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.18.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.17.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.18.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.17.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.18.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.17.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.18.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.17.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.18.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kube-state-metrics.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#7478 update e2e tests to kind 0.11 with k8s 1.21
  .prow.yaml
  Makefile
  hack/ci/setup-kind-cluster.sh
  hack/run-ccm-migration-e2e-test-in-kind.sh
  hack/run-expose-strategy-e2e-test-in-kind.sh
  hack/run-nodeport-proxy-e2e-test-in-kind.sh
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#7425 Fix prometheus chart to allow flux2 post-render
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/templates/role.yaml
  charts/monitoring/prometheus/templates/rolebinding.yaml
Labels: size/S, needs-ok-to-test, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#7466 keep user-defined tolerations on the node-local-dns DaemonSet
  pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/deamonset.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#7484 [release/v2.17] respect cluster pause flag in usercluster-controller-manager (#7470)
  cmd/user-cluster-controller-manager/main.go
  pkg/controller/user-cluster-controller-manager/cluster-role-labeler/cluster_role_labeler.go
  pkg/controller/user-cluster-controller-manager/cluster-role-labeler/cluster_role_labeler_test.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller_test.go
  pkg/controller/user-cluster-controller-manager/flatcar/flatcar_controller.go
  pkg/controller/user-cluster-controller-manager/owner-binding-creator/owner_binding_creator.go
  pkg/controller/user-cluster-controller-manager/owner-binding-creator/owner_binding_creator_test.go
  pkg/controller/user-cluster-controller-manager/pause.go
  pkg/controller/user-cluster-controller-manager/rbac/controller.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/role-cloner/role_cloner.go
  pkg/controller/user-cluster-controller-manager/role-cloner/role_cloner_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/security

#7219 Mount gocache when building user-ssh-keys-agent image
  cmd/user-ssh-keys-agent/Dockerfile
  cmd/user-ssh-keys-agent/Makefile
  hack/ci/setup-kubermatic-in-kind.sh
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#7487 add changelog for 2.17.3
  CHANGELOG.md
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes

#7482 fix flaky RBAC test
  pkg/handler/common/binding.go
  pkg/test/e2e/api/cluster_rbac_test.go
  pkg/test/e2e/utils/client.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#7410 Add strictArp IPVS setting for kube-proxy to Cluster API
  addons/kube-proxy/configmap.yaml
  cmd/image-loader/addons.go
  cmd/image-loader/main.go
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.addondata.go.txt
  pkg/addon/template.go
  pkg/addon/template_test.go
  pkg/addon/testdata/cluster-kubernetes-aws.yaml
  pkg/addon/testdata/cluster-kubernetes-do.yaml
  pkg/addon/testdata/cluster-openshift-vsphere.yaml
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/resources/data.go
  pkg/resources/resources.go
  pkg/test/e2e/utils/apiclient/models/cluster_networking_config.go
  pkg/test/e2e/utils/apiclient/models/ip_v_s_configuration.go
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, sig/networking

#7494 update Dex to 2.30.0, add 1.22 compatibility
  charts/oauth/Chart.yaml
  charts/oauth/templates/cluster-role-binding.yaml
  charts/oauth/templates/cluster-role.yaml
  charts/oauth/templates/ingress.yaml
  charts/oauth/templates/pdb.yaml
  charts/oauth/values.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, kind/chore

#7497 Revert "update Dex to 2.30.0, add 1.22 compatibility"
  charts/oauth/Chart.yaml
  charts/oauth/templates/cluster-role-binding.yaml
  charts/oauth/templates/cluster-role.yaml
  charts/oauth/templates/ingress.yaml
  charts/oauth/templates/pdb.yaml
  charts/oauth/values.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management

#7495 remove usage of deprecated API versions in Helm charts
  charts/iap/Chart.yaml
  charts/iap/templates/ingresses.yaml
  charts/iap/templates/pdbs.yaml
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/templates/rbac.yaml
  charts/logging/promtail/Chart.yaml
  charts/logging/promtail/templates/clusterrole.yaml
  charts/logging/promtail/templates/clusterrolebinding.yaml
  charts/monitoring/alertmanager/Chart.yaml
  charts/monitoring/alertmanager/templates/migration.yaml
  charts/monitoring/alertmanager/templates/pdb.yaml
  charts/monitoring/alertmanager/templates/statefulset.yaml
  charts/monitoring/alertmanager/values.yaml
  charts/monitoring/blackbox-exporter/Chart.yaml
  charts/monitoring/blackbox-exporter/templates/deployment.yaml
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/templates/pdb.yaml
  charts/monitoring/kube-state-metrics/Chart.yaml
  charts/monitoring/kube-state-metrics/templates/cluster-role-binding.yaml
  charts/monitoring/kube-state-metrics/templates/deployment.yaml
  charts/monitoring/kube-state-metrics/templates/role-binding.yaml
  charts/monitoring/kube-state-metrics/templates/role.yaml
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/templates/migration.yaml
  charts/monitoring/prometheus/templates/statefulset.yaml
  charts/monitoring/prometheus/templates/thanos-query-deployment.yaml
  charts/monitoring/prometheus/templates/thanos-store-deployment.yaml
  charts/monitoring/prometheus/values.yaml
  charts/oauth/Chart.yaml
  charts/oauth/templates/cluster-role-binding.yaml
  charts/oauth/templates/cluster-role.yaml
  charts/oauth/templates/ingress.yaml
  charts/oauth/templates/pdb.yaml
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, kind/chore

#7496 Update Velero to 1.6.3
  charts/backup/velero/Chart.yaml
  charts/backup/velero/crd/backups.yaml
  charts/backup/velero/crd/backupstoragelocations.yaml
  charts/backup/velero/crd/deletebackuprequests.yaml
  charts/backup/velero/crd/downloadrequests.yaml
  charts/backup/velero/crd/podvolumebackups.yaml
  charts/backup/velero/crd/podvolumerestores.yaml
  charts/backup/velero/crd/resticrepositories.yaml
  charts/backup/velero/crd/restores.yaml
  charts/backup/velero/crd/schedules.yaml
  charts/backup/velero/crd/serverstatusrequests.yaml
  charts/backup/velero/crd/volumesnapshotlocations.yaml
  charts/backup/velero/values.yaml
  hack/update-velero-crds.sh
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore

#7498 fix Ingress in oauth chart
  charts/oauth/Chart.yaml
  charts/oauth/templates/ingress.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#7493 Add MLASettings to addon ClusterData
  docs/zz_generated.addondata.go.txt
  pkg/addon/template.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#7500 fix typo in iap chart
  charts/iap/Chart.yaml
  charts/iap/templates/pdbs.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#7252 default component settings configuration
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/main.go
  cmd/seed-controller-manager/options.go
  cmd/seed-controller-manager/wrappers_ce.go
  cmd/seed-controller-manager/wrappers_ee.go
  docs/zz_generated.seed.yaml
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/defaulting/cluster.go
  pkg/ee/cmd/seed-controller-manager/wrappers.go
  pkg/ee/provider/datacenter.go
  pkg/provider/datacenter.go
  pkg/resources/etcd/statefulset.go
  pkg/test/e2e/ccm-migration/cluster.go
  pkg/test/e2e/etcd-launcher/etcd_test.go
  pkg/test/e2e/expose-strategy/cluster.go
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
Labels: size/L, ok-to-test, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#7502 Expose assignAvailabilitySet field from Azure in the API
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/test/e2e/utils/apiclient/models/public_azure_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/public_cloud_spec.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#7501 change cluster template instance endpoints
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/cluster_template_instance.go
  pkg/test/e2e/api/cluster_rbac_test.go
  pkg/test/e2e/api/cluster_template_test.go
  pkg/test/e2e/utils/apiclient/client/project/get_cluster_template_instance_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/get_cluster_template_instance_responses.go
  pkg/test/e2e/utils/apiclient/client/project/list_cluster_template_instances_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/list_cluster_template_instances_responses.go
  pkg/test/e2e/utils/apiclient/client/project/patch_cluster_template_instance_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/patch_cluster_template_instance_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/utils/client.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#7437 Update Prometheus to 2.29.1
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/values.yaml
  hack/ci/verify-user-cluster-prometheus-configs.sh
  pkg/resources/prometheus/statefulset.go
  pkg/resources/test/fixtures/statefulset-aws-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.19.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.19.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.19.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.19.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.17.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.18.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.19.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.19.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.20.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.21.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.17.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.18.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.18.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.19.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.19.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.20.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.21.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.21.0-prometheus.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore

#7447 Add Annotations to type ObjectMeta
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/common/machine.go
  pkg/handler/v1/common/event_test.go
  pkg/handler/v1/node/node_test.go
  pkg/handler/v2/machine/machine_test.go
  pkg/resources/machine/machinedeployment.go
  pkg/test/e2e/utils/apiclient/models/addon.go
  pkg/test/e2e/utils/apiclient/models/addon_config.go
  pkg/test/e2e/utils/apiclient/models/cluster.go
  pkg/test/e2e/utils/apiclient/models/cluster_role.go
  pkg/test/e2e/utils/apiclient/models/event.go
  pkg/test/e2e/utils/apiclient/models/node.go
  pkg/test/e2e/utils/apiclient/models/node_deployment.go
  pkg/test/e2e/utils/apiclient/models/object_meta.go
  pkg/test/e2e/utils/apiclient/models/project.go
  pkg/test/e2e/utils/apiclient/models/public_service_account_token.go
  pkg/test/e2e/utils/apiclient/models/role.go
  pkg/test/e2e/utils/apiclient/models/service_account.go
  pkg/test/e2e/utils/apiclient/models/service_account_token.go
  pkg/test/e2e/utils/apiclient/models/ssh_key.go
  pkg/test/e2e/utils/apiclient/models/user.go
Labels: size/L, ok-to-test, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#7433 Etcdrestore delete api
  cmd/kubermatic-api/swagger.json
  pkg/handler/test/fake_provider.go
  pkg/handler/v2/etcdrestore/etcdrestore.go
  pkg/handler/v2/etcdrestore/etcdrestore_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/etcdrestore.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/etcdrestore/delete_etcd_restore_parameters.go
  pkg/test/e2e/utils/apiclient/client/etcdrestore/delete_etcd_restore_responses.go
  pkg/test/e2e/utils/apiclient/client/etcdrestore/etcdrestore_client.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#7479 Allow Custom Scrape Configs for User Cluster MLA Prometheus
  cmd/user-cluster-controller-manager/main.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/configmap.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#7506 [promtail] kubelet log capturing and kubernetes event capturing
  charts/logging/promtail/Chart.yaml
  charts/logging/promtail/templates/daemonset.yaml
  charts/logging/promtail/values.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management

#7503 Add a sidecar container to reload user cluster Prometheus configuration
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/promtail/daemonset.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management

#7513 Add kube-state-metrics addon
  addons/kube-state-metrics/deployment.yaml
  addons/kube-state-metrics/rbac.yaml
  addons/kube-state-metrics/scrape-config.yaml
  addons/kube-state-metrics/service.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#7512 Extend CCM migration E2E tests to cleanup MachineDeployments and wait for resources to be deleted
  pkg/test/e2e/ccm-migration/ccm_migration_test.go
  pkg/test/e2e/ccm-migration/cluster.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#7511 Add support of Kubernetes 1.20 and 1.21 in cluster-autoscaler addon
  addons/cluster-autoscaler/cluster-autoscaler.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#7514 Integrate node-exporter addon with user cluster MLA
  addons/node-exporter/scrape-config.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management

#7396 Apiserver network policies
  codegen/reconcile/main.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/resources/apiserver/networkpolicy.go
  pkg/resources/reconciling/zz_generated_reconcile.go
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#7517 remove webhooks when preparing a ginkgo conformance test
  cmd/conformance-tests/cleanup.go
  cmd/conformance-tests/runner.go
  pkg/provider/datacenter.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#7521 [release/v2.16] Add support of Kubernetes 1.20 in cluster-autoscaler addon
  addons/cluster-autoscaler/cluster-autoscaler.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#7522 display cluster details for cluster template list endpoint
  pkg/handler/test/helper.go
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#7462 Update to controller-runtime 0.9.6 and k8s 1.21.3
  cmd/image-loader/main.go
  cmd/kubermatic-api/swagger.json
  cmd/seed-controller-manager/main.go
  docs/zz_generated.kubermaticConfiguration.yaml
  docs/zz_generated.seed.yaml
  go.mod
  go.sum
  pkg/controller/master-controller-manager/external-cluster/cluster_controller_test.go
  pkg/controller/master-controller-manager/master-constraint-template-controller/controller_test.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller_test.go
  pkg/controller/seed-controller-manager/constraint-template-controller/controller_test.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller_test.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/controller/seed-controller-manager/mla/alertmanager_controller_test.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/org_user_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller_test.go
  pkg/controller/shared/seed-controller-lifecycle/seed_controller_lifecycle.go
  pkg/controller/user-cluster-controller-manager/flatcar/resources/update_agent.go
  pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/deamonset.go
  pkg/controller/user-cluster-controller-manager/resources/resources/usersshkeys/daemonset.go
  pkg/controller/user-cluster-controller-manager/role-cloner/role_cloner_test.go
  pkg/ee/allowed-registry-controller/reconcile.go
  pkg/ee/allowed-registry-controller/reconcile_test.go
  pkg/handler/test/helper.go
  pkg/metrics/client.go
  pkg/test/e2e/opa/opa_test.go
  pkg/test/e2e/utils/apiclient/models/by_pod_status.go
  pkg/test/e2e/utils/apiclient/models/label_selector.go
  pkg/test/e2e/utils/apiclient/models/validation.go
  pkg/test/e2e/utils/kubernetes.go
  pkg/webhook/cluster/mutation/mutation_test.go
  pkg/webhook/cluster/validation/validation_test.go
  pkg/webhook/seed/handler_test.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, kind/chore

#7519 change vault domain to kubermatic.com
  hack/ci/deploy-ci-kubermatic-io.sh
  hack/ci/deploy-dev-asia.sh
  hack/ci/deploy-dev.sh
  hack/ci/deploy-offline.sh
  hack/ci/deploy-run-2-lab-alpha.sh
  hack/ci/deploy-run-lab-stable.sh
  hack/ci/run-conformance-tests.sh
  hack/ci/run-offline-test.sh
  hack/run-api.sh
  hack/run-conformance-tests.sh
  hack/run-master-controller-manager.sh
  hack/run-operator.sh
  hack/run-seed-controller-manager.sh
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#7510 Remove Gatekeeper from default accessible addon list
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/accessible-addons.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#7530 do not let gocache grow over time
  hack/ci/upload-gocache.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore

#7523 Update node-exporter to v1.2.2
  addons/node-exporter/daemonset.yaml
  charts/monitoring/node-exporter/Chart.yaml
  charts/monitoring/node-exporter/values.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore

#7528 Upgrade CRDs to apiextensions/v1
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/crd-addon-configs.yaml
  charts/kubermatic-operator/crd/crd-addons.yaml
  charts/kubermatic-operator/crd/crd-admission-plugins.yaml
  charts/kubermatic-operator/crd/crd-alertmanagers.yaml
  charts/kubermatic-operator/crd/crd-allowed-registries.yaml
  charts/kubermatic-operator/crd/crd-cluster-template-instances.yaml
  charts/kubermatic-operator/crd/crd-cluster-templates.yaml
  charts/kubermatic-operator/crd/crd-clusters.yaml
  charts/kubermatic-operator/crd/crd-constraint-templates.yaml
  charts/kubermatic-operator/crd/crd-constraints.yaml
  charts/kubermatic-operator/crd/crd-datacenter.yaml
  charts/kubermatic-operator/crd/crd-etcd-backup-configs.yaml
  charts/kubermatic-operator/crd/crd-etcd-restores.yaml
  charts/kubermatic-operator/crd/crd-external-clusters.yaml
  charts/kubermatic-operator/crd/crd-kubermatic-configuration.yaml
  charts/kubermatic-operator/crd/crd-kubermatic-settings.yaml
  charts/kubermatic-operator/crd/crd-presets.yaml
  charts/kubermatic-operator/crd/crd-projects.yaml
  charts/kubermatic-operator/crd/crd-rulegroups.yaml
  charts/kubermatic-operator/crd/crd-ssh-keys.yaml
  charts/kubermatic-operator/crd/crd-user-project-binding.yaml
  charts/kubermatic-operator/crd/crd-users.yaml
  charts/kubermatic-operator/crd/crd-vpa.yaml
  charts/kubermatic/Chart.yaml
  charts/kubermatic/crd/crd-alertmanagers.yaml
  charts/kubermatic/crd/crd-allowed-registries.yaml
  charts/kubermatic/crd/crd-cluster-template-instances.yaml
  charts/kubermatic/crd/crd-cluster-templates.yaml
  charts/kubermatic/crd/crd-clusters.yaml
  charts/kubermatic/crd/crd-etcd-backup-configs.yaml
  charts/kubermatic/crd/crd-external-clusters.yaml
  charts/kubermatic/crd/crd-projects.yaml
  charts/kubermatic/crd/crd-rulegroups.yaml
  charts/kubermatic/crd/crd-ssh-keys.yaml
  charts/kubermatic/crd/crd-user-project-binding.yaml
  charts/kubermatic/crd/crd-users.yaml
  charts/kubermatic/crd/crd-vpa.yaml
  cmd/user-cluster-controller-manager/main.go
  codegen/reconcile/main.go
  hack/ci/deploy.sh
  hack/ci/github-release.sh
  hack/verify-boilerplate.sh
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/crds.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/removal.go
  pkg/controller/user-cluster-controller-manager/resources/resources/machine-controller/crds.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/resources/reconciling/zz_generated_reconcile.go
  pkg/resources/resources.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore

#7524 Remove kubermatic from user cluster MLA name prefix
  pkg/resources/resources.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#7532 [release/v2.16] Remove Gatekeeper from the default accessible addon list
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/accessible-addons.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#7533 [release/v2.17] Remove Gatekeeper from the default accessible addon list
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/accessible-addons.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#7529 improve test-helm-charts.sh for batch jobs
  hack/ci/test-helm-charts.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#7545 Lower scrape interval for user cluster Prometheus, do not scrape apiserver
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/configmap.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#7515 fix flaky user cluster RBAC test
  pkg/test/e2e/api/cluster_rbac_test.go
  pkg/test/e2e/utils/client.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#7531 remove Loodse as Helm chart maintainer
  charts/backup/velero/Chart.yaml
  charts/cert-manager/Chart.yaml
  charts/iap/Chart.yaml
  charts/kubermatic-operator/Chart.yaml
  charts/logging/loki/Chart.yaml
  charts/logging/promtail/Chart.yaml
  charts/minio/Chart.yaml
  charts/monitoring/alertmanager/Chart.yaml
  charts/monitoring/blackbox-exporter/Chart.yaml
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/helm-exporter/Chart.yaml
  charts/monitoring/karma/Chart.yaml
  charts/monitoring/kube-state-metrics/Chart.yaml
  charts/monitoring/node-exporter/Chart.yaml
  charts/monitoring/prometheus/Chart.yaml
  charts/nginx-ingress-controller/Chart.yaml
  charts/nodeport-proxy/Chart.yaml
  charts/oauth/Chart.yaml
  charts/s3-exporter/Chart.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management

#7536 change cluster template controller, skip scale functionality
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#7550 Add design proposal for platform extensions
  docs/proposals/images/platform-extension-implementation-helm-manager.png
  docs/proposals/platform-extension-implementation-helm-manager.md
  docs/proposals/platform-extensions.md
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes

#7560 update nginx-ingress-controller to 0.49.0
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, kind/chore

#7562 update Minio to RELEASE.2021-08-20T18-32-01Z
  charts/minio/Chart.yaml
  charts/minio/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, kind/chore

#7563 update cert-manager to 1.5.2
  charts/cert-manager/Chart.yaml
  charts/cert-manager/crd/cert-manager.crds.yaml
  charts/cert-manager/templates/cainjector-rbac.yaml
  charts/cert-manager/templates/cert-manager-rbac.yaml
  charts/cert-manager/templates/webhook-rbac.yaml
  charts/cert-manager/test/test.sh
  charts/cert-manager/values.yaml
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore

#7561 update Grafana to 8.1.2
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/values.yaml
  hack/images/grafana-plugins/Dockerfile
  hack/images/grafana-plugins/release.sh
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, kind/chore

#7565 remove unused deploy-ci-kubermatic-io.sh
  hack/ci/README.md
  hack/ci/deploy-ci-kubermatic-io.sh
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#7557 Watch network policies in seed kubernetes controller
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#7553 Add telemetry Helm chart
  charts/telemetry/Chart.yaml
  charts/telemetry/templates/cronjob.yaml
  charts/telemetry/templates/kubermatic-role.yaml
  charts/telemetry/templates/kubermatic_role_binding.yml
  charts/telemetry/templates/kubernetes-role.yaml
  charts/telemetry/templates/kubernetes_role_binding.yml
  charts/telemetry/templates/secret.yaml
  charts/telemetry/templates/serviceaccount.yaml
  charts/telemetry/values.yaml
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#7568 Make Helm 3 available in kubermatic/util image
  .prow.yaml
  hack/images/util/Dockerfile
  hack/images/util/release.sh
  hack/lib.sh
  pkg/controller/master-controller-manager/seed-proxy/resources.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#7566 use Helm 3 for logging/monitoring deployment
  hack/ci/deploy-dev-asia.sh
  hack/ci/deploy-dev.sh
  hack/ci/deploy-offline.sh
  hack/ci/deploy-run-2-lab-alpha.sh
  hack/ci/deploy-run-lab-stable.sh
  hack/ci/deploy.sh
  hack/ci/run-conformance-tests.sh
  hack/lib.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#7572 remove ancient unused test files
  charts/kubermatic.example.ce.yaml
  charts/kubermatic.example.ee.yaml
  charts/seed.example.yaml
  charts/test/admission-webhooks/admissionvalidator-svc.yaml
  charts/test/admission-webhooks/create-secrets.sh
  charts/test/admission-webhooks/master-admission-config.yaml
  charts/test/autoscaler-scaleup.yaml
  charts/test/busybox.yaml
  charts/test/guestbook-full-example.yaml
  charts/test/storage-aws.yaml
  charts/test/storage-azure.yaml
  charts/test/storage-test.yaml
  hack/ci/github-release.sh
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore

#7554 Add kube-state-metrics into default accessible addons
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/accessible-addons.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#7575 Rename MlaAlertmanagerDomain to MlaAlertmanagerPrefix
  cmd/kubermatic-api/swagger.json
  pkg/crd/kubermatic/v1/settings.go
  pkg/handler/v1/admin/settings_test.go
  pkg/test/e2e/utils/apiclient/models/setting_spec.go
  pkg/test/e2e/utils/client.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#7597 update clusterrole for kube-state-metrics
  pkg/controller/user-cluster-controller-manager/resources/resources/kube-state-metrics/clusterrole.go
Labels: lgtm, approved

#7601 Metering support in api
  cmd/kubermatic-api/swagger.json
  pkg/ee/metering/handler.go
  pkg/handler/routes_v1_admin.go
  pkg/handler/v1/admin/seed.go
  pkg/handler/v1/admin/wrappers_ce.go
  pkg/handler/v1/admin/wrappers_ee.go
  pkg/test/e2e/utils/apiclient/client/admin/admin_client.go
  pkg/test/e2e/utils/apiclient/client/admin/create_or_update_metering_configurations_parameters.go
  pkg/test/e2e/utils/apiclient/client/admin/create_or_update_metering_configurations_responses.go
  pkg/test/e2e/utils/apiclient/client/admin/update_or_create_metering_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/admin/update_or_create_metering_credentials_responses.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#7611 EtcdBackupConfig API improvements
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/test/fake_wrapper.go
  pkg/handler/test/helper.go
  pkg/handler/v2/etcdbackupconfig/etcdbackupconfig.go
  pkg/handler/v2/etcdbackupconfig/etcdbackupconfig_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/etcdbackupconfig/delete_etcd_backup_config_parameters.go
  pkg/test/e2e/utils/apiclient/client/etcdbackupconfig/delete_etcd_backup_config_responses.go
  pkg/test/e2e/utils/apiclient/client/etcdbackupconfig/etcdbackupconfig_client.go
  pkg/test/e2e/utils/apiclient/client/etcdbackupconfig/get_etcd_backup_config_parameters.go
  pkg/test/e2e/utils/apiclient/client/etcdbackupconfig/get_etcd_backup_config_responses.go
  pkg/test/e2e/utils/apiclient/client/etcdbackupconfig/patch_etcd_backup_config_parameters.go
  pkg/test/e2e/utils/apiclient/client/etcdbackupconfig/patch_etcd_backup_config_responses.go
  pkg/test/e2e/utils/apiclient/models/etcd_backup_config.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#7558 Sync KubermaticConfiguration into seed clusters
  cmd/master-controller-manager/controllers.go
  cmd/master-controller-manager/main.go
  cmd/nodeport-proxy/Makefile
  codegen/reconcile/main.go
  pkg/controller/master-controller-manager/seed-sync/controller.go
  pkg/controller/master-controller-manager/seed-sync/reconciler.go
  pkg/controller/master-controller-manager/seed-sync/reconciler_test.go
  pkg/controller/master-controller-manager/seed-sync/resources.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/seed/controller.go
  pkg/controller/operator/seed/reconciler.go
  pkg/crd/equality/semantic.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#7607 extend cluster template for SSH keys
  pkg/crd/kubermatic/v1/cluster_templates.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#7612 Updating metering tool
  cmd/kubermatic-api/swagger.json
  pkg/ee/metering/cronjob.go
  pkg/ee/metering/deployment.go
  pkg/handler/routes_v1_admin.go
  pkg/test/e2e/utils/apiclient/client/admin/admin_client.go
  pkg/test/e2e/utils/apiclient/client/admin/create_or_update_metering_configurations_responses.go
  pkg/test/e2e/utils/apiclient/client/admin/update_or_create_metering_credentials_responses.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#7518 Metering list exports endpoint
  cmd/kubermatic-api/swagger.json
  go.mod
  go.sum
  pkg/api/v1/types.go
  pkg/ee/metering/handler.go
  pkg/ee/metering/report_handler.go
  pkg/handler/routes_v1_admin.go
  pkg/handler/v1/admin/metering.go
  pkg/handler/v1/admin/seed.go
  pkg/handler/v1/admin/wrappers_ce.go
  pkg/handler/v1/admin/wrappers_ee.go
  pkg/handler/v1/metering/metering.go
  pkg/test/e2e/utils/apiclient/client/admin/admin_client.go
  pkg/test/e2e/utils/apiclient/client/admin/create_or_update_metering_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/admin/create_or_update_metering_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/admin/update_or_create_metering_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/admin/update_or_create_metering_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/kubermatic_api_client.go
  pkg/test/e2e/utils/apiclient/client/metering/get_metering_report_parameters.go
  pkg/test/e2e/utils/apiclient/client/metering/get_metering_report_responses.go
  pkg/test/e2e/utils/apiclient/client/metering/list_metering_reports_parameters.go
  pkg/test/e2e/utils/apiclient/client/metering/list_metering_reports_responses.go
  pkg/test/e2e/utils/apiclient/client/metering/metering_client.go
  pkg/test/e2e/utils/apiclient/models/metering_report.go
  pkg/test/e2e/utils/apiclient/models/report_url.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#7614 disable flaky check for RBAC test
  pkg/test/e2e/api/cluster_rbac_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#7586 Extract kubeadm-configmap addon from kubelet-configmap addon
  addons/kubeadm-configmap/kubeadm-configmap.yaml
  addons/kubelet-configmap/kubelet-configmap.yaml
  charts/kubermatic/Chart.yaml
  charts/kubermatic/static/master/kubernetes-addons.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/defaults.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#7624 Update DigitalOcean Go dependencies
  go.mod
  go.sum
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#7571 update kube-state-metrics to 2.2.0
  charts/monitoring/kube-state-metrics/Chart.yaml
  charts/monitoring/kube-state-metrics/templates/cluster-role.yaml
  charts/monitoring/kube-state-metrics/values.yaml
  pkg/resources/kubestatemetrics/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.19.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.19.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.19.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.19.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.19.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.19.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kube-state-metrics.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore

#7605 delete grafana dashboards with configmaps
  go.mod
  go.sum
  pkg/controller/seed-controller-manager/mla/dashboard_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/dashboard_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/grafana.go
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/org_user_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller_test.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#7616 add SSH keys for cluster template API
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/project/create_cluster_template_responses.go
  pkg/test/e2e/utils/apiclient/models/cluster_template.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#7627 Update OpenStack Go dependency
  go.mod
  go.sum
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#7628 Update Packet Go dependency
  go.mod
  go.sum
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes
