Repository kubermatic/kubermatic, pull requests merged in 2022-11, with the labels that each got.

#11267 Fix: DNAT controller iptables-restore call blocking for big user clusters
  pkg/controller/kubeletdnat-controller/controller.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#11271 remove unneeded and outdated addon testdata
  pkg/addon/template_test.go
  pkg/addon/testdata/cluster-kubernetes-aws.yaml
  pkg/addon/testdata/cluster-kubernetes-do.yaml
  pkg/install/images/images_test.go
Labels: kind/cleanup, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#11272 AWS: Option to disable IAM reconciliation
  hack/run-ccm-migration-e2e-test-in-kind.sh
  pkg/apis/kubermatic/v1/cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/provider/cloud/aws/provider.go
  pkg/validation/cluster.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/tbd

#11274 move common error helper to pkg/util/errors
  pkg/ee/metering/report_config_handler.go
  pkg/handler/v1/common/error.go
  pkg/provider/kubernetes/external_cluster.go
  pkg/util/errors/errors.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api, docs/none

#11280 [release/v2.21] AWS: Option to disable IAM reconciliation
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/provider/cloud/aws/provider.go
  pkg/test/e2e/utils/apiclient/models/a_w_s_cloud_spec.go
  pkg/validation/cluster.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#11031 user MLA: Enable alert-management with Grafana
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/resources.go
Labels: kind/feature, size/L, ok-to-test, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#11259 External Cluster(EKS): Support for assume role
  pkg/api/v2/types.go
  pkg/apis/kubermatic/v1/external_cluster.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/provider/cloud/eks/provider.go
  pkg/resources/credentials.go
  pkg/resources/resources.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, docs/none

#11287 bump k8s-dns-node-cache to 1.22.13
  pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/deamonset.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#11195 Handle APIServerAllowedIPRanges in front-loadbalancer service
  pkg/resources/nodeportproxy/nodeportproxy.go
  pkg/validation/cluster.go
Labels: kind/feature, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#11282 Patch metering to version 1.0.1
  pkg/ee/metering/reconcile.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, docs/tbd

#11283 Restructure remaining constants from pkg/handler/
  cmd/alertmanager-authorization-server/main_test.go
  go.mod
  pkg/apis/kubermatic/v1/cluster_templates.go
  pkg/apis/kubermatic/v1/user.go
  pkg/controller/master-controller-manager/application-definition-synchronizer/controller_test.go
  pkg/controller/master-controller-manager/cluster-template-synchronizer/controller_test.go
  pkg/controller/master-controller-manager/master-constraint-controller/controller_test.go
  pkg/controller/master-controller-manager/master-constraint-template-controller/controller_test.go
  pkg/controller/master-controller-manager/preset-synchronizer/controller_test.go
  pkg/controller/master-controller-manager/project-synchronizer/controller_test.go
  pkg/controller/master-controller-manager/serviceaccount-projectbinding-controller/controller.go
  pkg/controller/master-controller-manager/serviceaccount-projectbinding-controller/controller_test.go
  pkg/controller/master-controller-manager/user-project-binding-synchronizer/controller_test.go
  pkg/controller/master-controller-manager/user-synchronizer/controller_test.go
  pkg/controller/seed-controller-manager/application-secret-cluster-controller/controller_integration_test.go
  pkg/controller/seed-controller-manager/backup/backup_controller_test.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller_test.go
  pkg/controller/seed-controller-manager/constraint-controller/controller_test.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller_test.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller_test.go
  pkg/controller/seed-controller-manager/mla/rulegroup_sync_controller_test.go
  pkg/controller/seed-controller-manager/preset-controller/controller_test.go
  pkg/controller/user-cluster-controller-manager/cluster-role-labeler/controller.go
  pkg/controller/user-cluster-controller-manager/cluster-role-labeler/controller_test.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller_test.go
  pkg/controller/user-cluster-controller-manager/owner-binding-creator/controller.go
  pkg/controller/user-cluster-controller-manager/owner-binding-creator/controller_test.go
  pkg/controller/user-cluster-controller-manager/role-cloner-controller/controller.go
  pkg/controller/user-cluster-controller-manager/role-cloner-controller/controller_test.go
  pkg/controller/user-cluster-controller-manager/types.go
  pkg/ee/constraint-controller/util_test.go
  pkg/ee/constraint-template-controller/util_test.go
  pkg/ee/group-project-binding/sync-controller/controller_test.go
  pkg/ee/metering/const.go
  pkg/ee/metering/handler.go
  pkg/ee/metering/reconcile.go
  pkg/ee/metering/report_config_handler.go
  pkg/ee/metering/report_handler.go
  pkg/ee/resource-quota/label-owner-controller/controller_test.go
  pkg/ee/resource-quota/master-controller/controller_test.go
  pkg/ee/resource-quota/resource-quota-synchronizer/synchronizer_test.go
  pkg/ee/resource-usage-controller/controller_test.go
  pkg/ee/validation/machine/resourcequota_test.go
  pkg/handler/OWNERS
  pkg/handler/common/architecture.go
  pkg/handler/common/role.go
  pkg/handler/middleware/middleware.go
  pkg/handler/v1/label/label.go
  pkg/provider/cloud/eks/provider.go
  pkg/provider/cloud/openstack/provider_test.go
  pkg/provider/kubernetes/cluster_template_instance.go
  pkg/provider/kubernetes/credentials.go
  pkg/provider/kubernetes/sa.go
  pkg/resources/test/load_files_test.go
  pkg/test/constraints.go
  pkg/test/e2e/mla/mla_test.go
  pkg/test/generator/objects.go
  pkg/validation/user.go
Labels: kind/cleanup, size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, docs/none

#11290 Fix arguments in usercluster-mla deployment
  hack/ci/deploy.sh
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#11279 Consolidate cloud provider code
  .golangci.yml
  pkg/ee/validation/machine/providers.go
  pkg/ee/validation/machine/resourcequota.go
  pkg/handler/common/provider/alibaba.go
  pkg/handler/common/provider/azure.go
  pkg/handler/common/provider/digitalocean.go
  pkg/handler/common/provider/gcp.go
  pkg/handler/common/provider/hetzner.go
  pkg/handler/common/provider/kubevirt.go
  pkg/handler/common/provider/openstack.go
  pkg/handler/common/provider/packet.go
  pkg/provider/cloud/alibaba/provider.go
  pkg/provider/cloud/aws/data/aws.go
  pkg/provider/cloud/aws/data/doc.go
  pkg/provider/cloud/azure/client.go
  pkg/provider/cloud/azure/provider.go
  pkg/provider/cloud/azure/utils.go
  pkg/provider/cloud/digitalocean/provider.go
  pkg/provider/cloud/gcp/provider.go
  pkg/provider/cloud/hetzner/provider.go
  pkg/provider/cloud/kubevirt/vm_preset.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/packet/provider.go
  pkg/provider/types.go
Labels: kind/cleanup, size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, docs/none

#11294 MLA dev: don't deploy IAP on seed asia
  hack/ci/deploy.sh
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#11276 Upgrade to Go 1.19.3
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, docs/none

#11298 Support for OpenStack server groups
  pkg/api/v1/types.go
  pkg/api/v1/types_test.go
  pkg/resources/machine/common.go
Labels: kind/feature, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, sig/api, docs/none

#11291 MLA: Fixes to default values in charts
  charts/mla/consul/values.yaml
  charts/mla/cortex/test/config.yaml.out
  charts/mla/cortex/test/default.yaml.out
  charts/mla/cortex/values.yaml
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#11289 Adds ValidateUserDelete to validation webhook
  cmd/kubermatic-webhook/main.go
  pkg/apis/kubermatic/v1/helper/helper.go
  pkg/apis/kubermatic/v1/helper/user.go
  pkg/validation/user.go
  pkg/webhook/user/validation/validation.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/tbd

#11310 Add Delete operation in user validationwebhook
  pkg/controller/operator/master/resources/kubermatic/webhooks.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#11300 do not require go-openapi just to handle aggregate errors
  .wwhrd.yml
  go.mod
  go.sum
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller.go
Labels: kind/cleanup, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#11309 Refactor nodeport-proxy tests to remove Ginkgo dependency
  hack/run-nodeport-proxy-e2e-test-in-kind.sh
  pkg/controller/operator/seed/resources/nodeportproxy/test/helper.go
  pkg/test/e2e/nodeport-proxy/deployer.go
  pkg/test/e2e/nodeport-proxy/images.go
  pkg/test/e2e/nodeport-proxy/network.go
  pkg/test/e2e/nodeport-proxy/nodeport_proxy.go
  pkg/test/e2e/nodeport-proxy/nodeport_proxy_suite_test.go
  pkg/test/e2e/nodeport-proxy/nodeport_proxy_test.go
  pkg/test/e2e/nodeport-proxy/services.go
  pkg/test/e2e/nodeport-proxy/utils.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#11313 Add externalclusters in kubermaticwebhook clusterrole
  pkg/controller/operator/common/webhook.go
  pkg/validation/user.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#11312 Remove unused types from api/v1 and api/v2
  pkg/api/v1/types.go
  pkg/api/v1/types_test.go
  pkg/api/v2/types.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller_test.go
  pkg/provider/cloud/fake/provider.go
  pkg/resources/cluster/cluster.go
  pkg/test/generator/objects.go
Labels: kind/cleanup, size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, docs/none

#11317 Support for configuring dashboard notification settings
  pkg/apis/kubermatic/v1/settings.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
Labels: kind/feature, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#11296 Allow for range / prefix exclusions in IPAMPool
  cmd/kubermatic-webhook/main.go
  pkg/apis/kubermatic/v1/ipam_pool.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/seed-controller-manager/ipam/controller.go
  pkg/controller/seed-controller-manager/ipam/controller_test.go
  pkg/controller/seed-controller-manager/ipam/range_allocation.go
  pkg/crd/k8c.io/kubermatic.k8c.io_ipampools.yaml
  pkg/test/e2e/ipam/ipam_test.go
  pkg/webhook/ipampool/validation/helper.go
  pkg/webhook/ipampool/validation/validation.go
  pkg/webhook/ipampool/validation/validation_test.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/tbd

#11299 Remove Cluster.Status.CloudProviderRevision
  pkg/apis/kubermatic/v1/cluster.go
  pkg/controller/seed-controller-manager/cloud/cloud_controller.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/provider/cloud/azure/provider.go
  pkg/provider/cloud/openstack/provider.go
Labels: kind/cleanup, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#11311 Switch to upstream Nutanix Go client
  .wwhrd.yml
  go.mod
  go.sum
  pkg/provider/cloud/nutanix/api.go
  pkg/provider/cloud/nutanix/client.go
  pkg/provider/cloud/nutanix/provider.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#11308 fix for duplicate entries in front-loadbalancer
  pkg/resources/nodeportproxy/nodeportproxy.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#11323 [release/v2.20] Use optimistic locking when managing finalizer `kubermatic.k8c.io/cleanup-usersshkeys-cluster-ids`
  pkg/controller/master-controller-manager/usersshkeyssynchronizer/controller.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#11322 Fix for cluster with MLA not being terminated after project deletion
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, docs/none

#11327 fix AllowedRegistry ConstraintTemplate OpenAPI schema
  pkg/ee/allowed-registry-controller/reconcile.go
  pkg/ee/allowed-registry-controller/reconcile_test.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, docs/none

#11293 [release/v2.21] Update metering
  pkg/ee/metering/reconcile.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes

#11338 OpenStack: Option to enforce custom disk in KubermaticSettings
  pkg/apis/kubermatic/v1/settings.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#11301 use our existing diff package in MLA tests
  go.mod
  pkg/controller/seed-controller-manager/mla/org_grafana_controller_test.go
Labels: kind/cleanup, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, docs/none

#11340 Add support for Kubernetes 1.25.4, 1.24.8, and 1.23.14
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, docs/none

#11341 [release/v2.21] Add support for Kubernetes 1.24.8, 1.23.14, and 1.22.16
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/defaults/defaults.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#11315 Remove overwriteCloudConfigSpec from vSphere MDs
  pkg/resources/machine/machinedeployment.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#11344 Revert "Add support for Kubernetes 1.25.4, 1.24.8, and 1.23.14 (#11340)"
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: approved, size/M, release-note-none, dco-signoff: yes, docs/none

#11342 [release/v2.20] Add support for Kubernetes 1.23.14 and 1.22.16
  .prow.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/addon/template_test.go
  pkg/controller/operator/defaults/defaults.go
  pkg/controller/seed-controller-manager/backup/backup_controller_test.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller_test.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#11326 Add changelogs for 2.21.3, 2.20.10 and 2.19.12 (November releases)
  docs/changelogs/CHANGELOG-2.19.md
  docs/changelogs/CHANGELOG-2.20.md
  docs/changelogs/CHANGELOG-2.21.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#11345 Add support for Kubernetes 1.25.4, 1.24.8, and 1.23.14
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: kind/feature, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#11324 pass expected number of pods to egress validator
  pkg/test/dualstack/dualstack_test.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, docs/none

#11346 fix typos in dualstack e2e tests
  .prow/ccm-migrations.yaml
  .prow/provider-aws.yaml
  hack/ci/setup-kubermatic-in-kind.sh
Labels: kind/cleanup, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#11353 Add proposal for CNI Management via Applications Infra
  docs/proposals/cni-mgmt-via-applications.md
Labels: size/L, lgtm, approved, release-note-none, kind/design, dco-signoff: yes, docs/none

#11362 Actually make enableWebTerminal an optional field
  pkg/apis/kubermatic/v1/settings.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#11359 Use string Version type for ApplicationInstallation CRD
  codegen/example-yaml/main.go
  pkg/api/v1/types.go
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/apis/apps.kubermatic/v1/zz_generated.deepcopy.go
  pkg/applications/installer_test.go
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller_test.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_integration_test.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_test.go
  pkg/validation/application_installation.go
  pkg/validation/application_installation_test.go
  pkg/webhook/application/applicationinstallation/validation/validation_test.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, docs/none

#11363 Stop creating vsphere tags categories unconditionally
  pkg/apis/kubermatic/v1/cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/provider/cloud/vsphere/category.go
  pkg/provider/cloud/vsphere/provider.go
Labels: lgtm, approved, size/M, kind/design, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#11368 [release/v2.21] Increase test timeout to 20m
  hack/run-tests.sh
Labels: kind/cleanup, kind/failing-test, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, cherry-pick-approved

#11230 update-alerts
  charts/monitoring/prometheus/rules/general-cadvisor.yaml
  charts/monitoring/prometheus/rules/general-kube-apiserver.yaml
  charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/src/general/blackbox-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/cadvisor.yaml
  charts/monitoring/prometheus/rules/src/general/kube-apiserver.yaml
  charts/monitoring/prometheus/rules/src/general/kube-state-metrics.yaml
Labels: kind/bug, kind/cleanup, ok-to-test, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management, docs/none

#11360 Pass cluster name to KubeVirt CCM
  pkg/resources/cloudcontroller.go
  pkg/webhook/cluster/mutation/mutator_test.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#11382 Disable promtail sidecar to set fs.inotify.max_user_instances
  charts/logging/promtail/test/default.yaml.out
  charts/logging/promtail/test/kubermatic.example.ce.yaml.out
  charts/logging/promtail/test/kubermatic.example.ee.yaml.out
  charts/logging/promtail/values.yaml
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, docs/none

#11373 Fix PSP and PDB resources in addons `pod-security-policy`, `aws-node-termination-handler` and `aws-ebs-csi-driver`
  addons/Makefile
  addons/aws-node-termination-handler/aws-node-termination-handler.yaml
  addons/csi/aws-ebs/driver.yaml
  addons/pod-security-policy/psp-privileged.yaml
  addons/pod-security-policy/rbac-kube-system.yaml
  addons/values-aws-node-termination-handler.yaml
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, docs/none

#11397 Revert "Stop creating vsphere tags categories unconditionally"
  pkg/apis/kubermatic/v1/cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/provider/cloud/vsphere/category.go
  pkg/provider/cloud/vsphere/provider.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#11380 Check error directly instead of calling isNotFound(err) in Azure provider
  pkg/provider/cloud/azure/availability_set.go
  pkg/provider/cloud/azure/resource_group.go
  pkg/provider/cloud/azure/route_table.go
  pkg/provider/cloud/azure/security_group.go
  pkg/provider/cloud/azure/subnet.go
  pkg/provider/cloud/azure/vnet.go
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#11266 assign public ip to node in azure cluster jig
  .prow/dualstack.yaml
  pkg/test/e2e/jig/cluster.go
  pkg/test/e2e/jig/machine.go
  pkg/test/e2e/jig/project.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#11398 KubeVirt remove Flavor handling
  codegen/reconcile/main.go
  pkg/ee/validation/machine/providers.go
  pkg/provider/cloud/kubevirt/manifests/manifests.go
  pkg/provider/cloud/kubevirt/manifests/manifests_test.go
  pkg/provider/cloud/kubevirt/manifests/presets/kubermatic-standard.yaml
  pkg/provider/cloud/kubevirt/manifests/test/presets/invalid-standard.yaml
  pkg/provider/cloud/kubevirt/manifests/test/presets/standard-1.yaml
  pkg/provider/cloud/kubevirt/manifests/test/presets/standard-2.yaml
  pkg/provider/cloud/kubevirt/provider.go
  pkg/provider/cloud/kubevirt/vm_preset.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: kind/cleanup, size/L, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/cluster-management, docs/tbd

#11370 KubeVirt split CSI driver deployment between user and infra cluster
  addons/csi/kubevirt/csi-driver-operator.yaml
  docs/zz_generated.addondata.go.txt
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/ee/validation/machine/providers.go
  pkg/install/images/images.go
  pkg/provider/cloud/kubevirt/csi.go
  pkg/provider/cloud/kubevirt/helper.go
  pkg/provider/cloud/kubevirt/provider.go
  pkg/provider/kubernetes/credentials.go
  pkg/resources/cloudconfig/cloudconfig.go
  pkg/resources/cloudconfig/cloudconfig_test.go
  pkg/resources/cloudconfig/secret.go
  pkg/resources/credentials.go
  pkg/resources/csi/configmap.go
  pkg/resources/csi/deployment.go
  pkg/resources/csi/kubevirt/configmap.go
  pkg/resources/csi/kubevirt/deployment.go
  pkg/resources/csi/kubevirt/rbac.go
  pkg/resources/csi/kubevirt/secret.go
  pkg/resources/csi/nutanix/secret.go
  pkg/resources/csi/rbac.go
  pkg/resources/csi/secret.go
  pkg/resources/csi/vmwareclouddirector/config.go
  pkg/resources/csi/vmwareclouddirector/config_test.go
  pkg/resources/csi/vmwareclouddirector/secret.go
  pkg/resources/csi/vsphere/config.go
  pkg/resources/csi/vsphere/secret.go
  pkg/resources/data.go
  pkg/resources/operatingsystemmanager/deployment.go
  pkg/resources/resources.go
  pkg/validation/cluster.go
Labels: kind/feature, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, sig/virtualization, docs/none

#11388 Update kubeone pod imagetag
  pkg/controller/master-controller-manager/kubeone/controller.go
  pkg/resources/resources.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#11389 Fix externalcluster kubeconfig not fetched
  pkg/provider/cloud/eks/provider.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#11387 Replace UserCluster Prometheus with Grafana Agent
  cmd/user-cluster-controller-manager/main.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/monitoring-agent/clusterrole.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/monitoring-agent/clusterrolebinding.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/monitoring-agent/configmap.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/monitoring-agent/deletion.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/monitoring-agent/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/monitoring-agent/legacy.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/monitoring-agent/secret.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/monitoring-agent/serviceaccount.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/configmap.go
  pkg/resources/resources.go
Labels: kind/feature, size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/tbd

#11412 bump cert-manager to 1.10.1
  charts/cert-manager/Chart.yaml
  charts/cert-manager/test/default.yaml.out
  go.mod
  go.sum
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#11422 [release/v2.19] Remove `pre-kubermatic-ccm-migration-e2e` prow job
  .prow.yaml
Labels: kind/cleanup, kind/failing-test, lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#11421 [release/v2.19] bump Dex to 2.35.3 (#11413)
  charts/oauth/Chart.yaml
  charts/oauth/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, kind/chore, cherry-pick-approved

#11416 [release/v2.21] bump nginx-ingress to 1.5.1 (#11415)
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, cherry-pick-approved

#11411 Default tag category from seed
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/provider/cloud/vsphere/provider.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#11424 Remove support for Thanos in Prometheus Helm chart
  charts/monitoring/grafana/dashboards/monitoring/thanos-compact.json
  charts/monitoring/grafana/dashboards/monitoring/thanos-overview.json
  charts/monitoring/grafana/dashboards/monitoring/thanos-query.json
  charts/monitoring/grafana/dashboards/monitoring/thanos-sidecar.json
  charts/monitoring/grafana/dashboards/monitoring/thanos-store.json
  charts/monitoring/grafana/values.yaml
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/config/prometheus.yaml
  charts/monitoring/prometheus/config/scraping/thanos-sidecar.yaml
  charts/monitoring/prometheus/rules/general-thanos.yaml
  charts/monitoring/prometheus/rules/src/general/thanos.yaml
  charts/monitoring/prometheus/templates/statefulset.yaml
  charts/monitoring/prometheus/templates/thanos-compact-deployment.yaml
  charts/monitoring/prometheus/templates/thanos-query-deployment.yaml
  charts/monitoring/prometheus/templates/thanos-query-service.yaml
  charts/monitoring/prometheus/templates/thanos-secret.yaml
  charts/monitoring/prometheus/templates/thanos-store-deployment.yaml
  charts/monitoring/prometheus/templates/thanos-store-service.yaml
  charts/monitoring/prometheus/templates/thanos-ui-deployment.yaml
  charts/monitoring/prometheus/templates/thanos-ui-service.yaml
  charts/monitoring/prometheus/values.yaml
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/deprecation, docs/tbd

#11381 Adding TunnelingAgentIP to ClusterNetworkingConfig
  pkg/apis/kubermatic/v1/cluster.go
  pkg/controller/seed-controller-manager/kubernetes/address.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/resources/resources.go
  pkg/test/e2e/expose-strategy/tunneling_test.go
  pkg/validation/cluster.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#11425 update node_exporter to 1.4.0
  charts/monitoring/node-exporter/Chart.yaml
  charts/monitoring/node-exporter/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#11423 update Prometheus to 2.40.2
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/values.yaml
  pkg/resources/prometheus/statefulset.go
  pkg/resources/test/fixtures/statefulset-aws-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.25.0-prometheus.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/none

#11417 [release/v2.20] bump nginx-ingress to 1.5.1 (#11415)
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/requirements.lock
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, cherry-pick-approved

#11367 [release/v2.19] Switch vcenter datastore used for CI
  cmd/conformance-tests/scenarios_vsphere.go
  hack/ci/run-conformance-tests.sh
  hack/ci/testdata/seed.yaml
  hack/ci/testdata/seed_backup.yaml
  hack/run-conformance-tests.sh
  pkg/provider/cloud/vsphere/ca_test.go
  pkg/provider/cloud/vsphere/folder_test.go
  pkg/provider/cloud/vsphere/integration_test.go
  pkg/provider/cloud/vsphere/network_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#11430 KubeVirt cleanup Flavor and PodAffinityPreset
  pkg/resources/machine/common.go
Labels: kind/cleanup, release-note-action-required, lgtm, approved, size/XS, dco-signoff: yes, sig/cluster-management, docs/provided

#11406 [release/v2.19] Update to etcd 3.5.6
  go.mod
  go.sum
  pkg/resources/etcd/statefulset.go
  pkg/resources/test/fixtures/cronjob-aws-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.22.1-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.22.1-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-etcd.yaml
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#11434 monitoring: rename etcd metrics graduated by v3.4.0
  charts/monitoring/grafana/dashboards/kubernetes/etcd-overview.json
  charts/monitoring/grafana/dashboards/kubernetes/etcd.json
  pkg/resources/prometheus/configmap-rules.go
  pkg/resources/test/fixtures/configmap-aws-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-aws-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-aws-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-aws-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-gcp-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-gcp-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-gcp-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.25.0-prometheus.yaml
Labels: kind/bug, size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none, backport-needed

#11438 [release/v2.21] monitoring: rename etcd metrics graduated by v3.4.0
  charts/monitoring/grafana/dashboards/kubernetes/etcd-overview.json
  charts/monitoring/grafana/dashboards/kubernetes/etcd.json
  pkg/resources/prometheus/configmap-rules.go
  pkg/resources/test/fixtures/configmap-aws-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.24.0-prometheus.yaml
Labels: kind/bug, size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, cherry-pick-approved

#11439 [release/v2.20] monitoring: rename etcd metrics graduated by v3.4.0
  charts/monitoring/grafana/dashboards/kubernetes/etcd-overview.json
  charts/monitoring/grafana/dashboards/kubernetes/etcd.json
  pkg/resources/prometheus/configmap-rules.go
  pkg/resources/test/fixtures/configmap-aws-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.20.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.21.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.20.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.21.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.23.5-prometheus.yaml
Labels: kind/bug, size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, cherry-pick-approved

#11440 [release/v2.19] monitoring: rename etcd metrics graduated by v3.4.0
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/dashboards/kubernetes/etcd-overview.json
  charts/monitoring/grafana/dashboards/kubernetes/etcd.json
  pkg/resources/prometheus/configmap-rules.go
  pkg/resources/test/fixtures/configmap-aws-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.20.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.21.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.20.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.21.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-prometheus.yaml
Labels: kind/bug, size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, cherry-pick-approved

#11443 Fix for tunnelingAgentIP default spec
  pkg/defaulting/cluster.go
  pkg/defaulting/cluster_test.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, docs/none

#11447 Respect pause checker for externalclusters
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/controller/master-controller-manager/kubeone/controller.go
  pkg/provider/kubernetes/external_cluster.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/api, docs/tbd

#11437 Fix kubeone namespace cleanup
  pkg/controller/master-controller-manager/kubeone/controller.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#11441 Kubevirt fix wrong HostPort in the csi-driver
  pkg/resources/csi/kubevirt/deployment.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, sig/virtualization, docs/none

#11390 Application test refactoring
  go.mod
  pkg/applications/helmclient/client_integration_test.go
  pkg/applications/helmclient/client_test.go
  pkg/applications/providers/template/helm_integration_test.go
  pkg/applications/providers/template/suite_test.go
  pkg/applications/test/doc.go
  pkg/applications/test/helm.go
  pkg/applications/test/kubernetes.go
Labels: kind/cleanup, size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, docs/none

#11459 Set ownership for kubevirt provider to sig-virt
  pkg/provider/cloud/kubevirt/OWNERS
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#11427 Bump Go dependencies
  go.mod
  go.sum
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, docs/none

#11454 Update OpenStack Cinder CSI to v1.24.5 and v1.25.3
  addons/csi/openstack/controllerplugin.yaml
  addons/csi/openstack/nodeplugin.yaml
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#11402 Add event monitoring dashboard
  charts/monitoring/grafana/dashboards/kubermatic/event-monitoring.json
  hack/fmt-grafana-dashboard.sh
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/tbd

#11465 Fix metrics scraping configmap prefix for addons
  addons/kube-state-metrics/scrape-config.yaml
  addons/node-exporter/scrape-config.yaml
Labels: kind/cleanup, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, docs/none

#11468 Update Developer Certificate of Origin
  CONTRIBUTING.md
  DCO
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none

#11473 skip vsphere tests if $VSPHERE_E2E_DISABLED is not empty
  hack/ci/run-conformance-tests.sh
  hack/ci/run-dualstack-e2e-test.sh
  hack/run-integration-tests.sh
Labels: size/S, kind/flake, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#11469 KubeVirt: activate storage tests
  cmd/conformance-tester/pkg/tests/storage.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, docs/none

#11414 Manage Cilium CNI via Applications infra
  cmd/seed-controller-manager/controllers.go
  codegen/reconcile/main.go
  pkg/addon/template_test.go
  pkg/apis/apps.kubermatic/v1/types.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/common.go
  pkg/cni/OWNERS
  pkg/cni/cilium.go
  pkg/cni/doc.go
  pkg/cni/version.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/seed-controller-manager/addon/addon_controller_test.go
  pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller.go
  pkg/controller/seed-controller-manager/cni-application-installation-controller/OWNERS
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller_test.go
  pkg/controller/seed-controller-manager/cni-application-installation-controller/doc.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/defaulting/cluster.go
  pkg/install/images/images.go
  pkg/resources/reconciling/zz_generated_reconcile.go
  pkg/resources/test/load_files_test.go
  pkg/test/e2e/cilium/cilium_test.go
  pkg/test/generator/objects.go
  pkg/validation/cluster.go
  pkg/webhook/cluster/mutation/mutator.go
  pkg/webhook/cluster/mutation/mutator_test.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: kind/feature, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/tbd

#11467 applications: add option to force reconciliation even if crd has not changed
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/apis/apps.kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/validation/application_installation.go
  pkg/validation/application_installation_test.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, docs/tbd

#11471 Fix resource definitions for MLA monitoring and logging agent
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/logging-agent/daemonset.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/monitoring-agent/configmap.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, docs/none
