Repository kubermatic/kubermatic, pull requests merged in 2022-10, with the labels that each got.

#11070 Added new alerts for kubernetes-storage
  charts/monitoring/prometheus/rules/general-kube-kubelet.yaml
  charts/monitoring/prometheus/rules/src/general/kube-kubelet.yaml
Labels: size/L, ok-to-test, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, docs/none

#11115 add EtcdLauncherNotEnabled phase to etcd restore
  pkg/apis/kubermatic/v1/etcd_restore.go
  pkg/controller/seed-controller-manager/etcdrestore/etcd_restore_controller.go
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdrestores.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/tbd

#11127 Add changelog entries for v2.19.10 and v2.20.8
  docs/changelogs/CHANGELOG-2.19.md
  docs/changelogs/CHANGELOG-2.20.md
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, docs/none

#11131 bump Dex to 2.35.1
  charts/oauth/Chart.yaml
  charts/oauth/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#11132 update to nginx-ingress 1.4.0
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#11121 adds groups in OIDC kubeconfig
  pkg/handler/common/kubeconfig.go
Labels: kind/feature, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/api, docs/none

#11129 Generate CE/EE example YAMLs separately
  codegen/example-yaml/main.go
  docs/docs_ce.go
  docs/docs_ee.go
  docs/zz_generated.applicationDefinition.ce.yaml
  docs/zz_generated.applicationDefinition.ee.yaml
  docs/zz_generated.applicationInstallation.ce.yaml
  docs/zz_generated.applicationInstallation.ee.yaml
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  hack/ci/update-docs.sh
  hack/update-docs.sh
Labels: kind/bug, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#11135 Do not require addons flags in `kubermatic-installer mirror-images`
  cmd/kubermatic-installer/cmd_mirror_images.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#11139 Revert "bump Dex to 2.35.1 (#11131)"
  charts/oauth/Chart.yaml
  charts/oauth/values.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#11140 Set PriorityClassName of konnectivity-agent & openvpn-client to system-cluster-critical
  addons/openvpn/openvpn-client-dep.yaml
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/deployment.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#11146 fix --config not being validated in mirror-images command
  cmd/kubermatic-installer/cmd_mirror_images.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#11148 Re-enable k8s dashboard and add konnectivity images to `mirror-images`
  cmd/kubermatic-installer/cmd_mirror_images.go
  pkg/install/images/images.go
  pkg/install/images/images_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, kind/regression, docs/none

#11100 Add `.spec.projects` to `Preset` to bind presets to specific projects
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/preset.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/handler/common/cluster.go
  pkg/handler/v1/presets/credentials.go
  pkg/handler/v1/provider/alibaba.go
  pkg/handler/v1/provider/anexia.go
  pkg/handler/v1/provider/aws.go
  pkg/handler/v1/provider/azure.go
  pkg/handler/v1/provider/digitalocean.go
  pkg/handler/v1/provider/gcp.go
  pkg/handler/v1/provider/hetzner.go
  pkg/handler/v1/provider/openstack.go
  pkg/handler/v1/provider/packet.go
  pkg/handler/v1/provider/vsphere.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/preset/preset.go
  pkg/handler/v2/provider/azure.go
  pkg/handler/v2/provider/kubevirt.go
  pkg/handler/v2/provider/nutanix.go
  pkg/handler/v2/provider/vmwareclouddirector.go
  pkg/handler/v2/provider/vsphere.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/preset.go
  pkg/provider/kubernetes/preset_test.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/preset/list_project_presets_parameters.go
  pkg/test/e2e/utils/apiclient/client/preset/list_project_presets_responses.go
  pkg/test/e2e/utils/apiclient/client/preset/list_project_provider_presets_parameters.go
  pkg/test/e2e/utils/apiclient/client/preset/list_project_provider_presets_responses.go
  pkg/test/e2e/utils/apiclient/client/preset/preset_client.go
  pkg/test/e2e/utils/apiclient/models/preset_spec.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, docs/none

#11124 Handle web terminal connection errors inside websocket tunnel
  pkg/handler/routes_v1_websocket.go
  pkg/handler/websocket/terminal.go
Labels: kind/feature, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api, docs/none

#11157 Allow changing cluster expose strategy if explicitly labeled
  pkg/validation/cluster.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, docs/provided

#11142 Adding APIServerAllowedIPRanges to cluster API
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/resources/cluster/cluster.go
  pkg/test/e2e/utils/apiclient/models/cluster_spec.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/networking, docs/none

#11128 validate that admins do not accidentally change the KKP edition during updates
  cmd/kubermatic-installer/cmd_deploy.go
  pkg/install/stack/kubermatic-master/validation.go
  pkg/install/stack/types.go
  pkg/util/edition/types.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#11156 Add project-aware cloud provider endpoints for GKE
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/gke/gke_client.go
  pkg/test/e2e/utils/apiclient/client/gke/list_project_g_k_e_disk_types_parameters.go
  pkg/test/e2e/utils/apiclient/client/gke/list_project_g_k_e_disk_types_responses.go
  pkg/test/e2e/utils/apiclient/client/gke/list_project_g_k_e_images_parameters.go
  pkg/test/e2e/utils/apiclient/client/gke/list_project_g_k_e_images_responses.go
  pkg/test/e2e/utils/apiclient/client/gke/list_project_g_k_e_versions_parameters.go
  pkg/test/e2e/utils/apiclient/client/gke/list_project_g_k_e_versions_responses.go
  pkg/test/e2e/utils/apiclient/client/gke/list_project_g_k_e_vm_sizes_parameters.go
  pkg/test/e2e/utils/apiclient/client/gke/list_project_g_k_e_vm_sizes_responses.go
  pkg/test/e2e/utils/apiclient/client/gke/list_project_g_k_e_zones_parameters.go
  pkg/test/e2e/utils/apiclient/client/gke/list_project_g_k_e_zones_responses.go
  pkg/test/e2e/utils/apiclient/client/gke/validate_project_g_k_e_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/gke/validate_project_g_k_e_credentials_responses.go
Labels: kind/feature, kind/api-change, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/api, docs/none

#11181 Bump swagger spec version to 2.22
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/swagger.json
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/api, docs/none

#11150 [release/v2.21] Re-enable k8s dashboard and add konnectivity images to `mirror-images` (#11148)
  cmd/kubermatic-installer/cmd_mirror_images.go
  pkg/install/images/images.go
  pkg/install/images/images_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, kind/regression

#11185 fix preset CRD not being synced to seed clusters
  hack/update-codegen.sh
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#11184 remove metrics-server addon
  addons/metrics-server/auth-delegator.yaml
  addons/metrics-server/auth-reader.yaml
  addons/metrics-server/metrics-apiservice.yaml
  addons/metrics-server/metrics-server-deployment.yaml
  addons/metrics-server/metrics-server-service.yaml
  addons/metrics-server/resource-reader.yaml
Labels: kind/cleanup, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#11192 Don't fetch MLA charts during the deployment jobs
  hack/ci/fetch-chart-dependencies.sh
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#11120 api: add endpoint to handle k8s service account in cluster and download associated kubeconfigs
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/common/binding.go
  pkg/handler/common/kubeconfig.go
  pkg/handler/test/helper.go
  pkg/handler/v2/cluster/binding_test.go
  pkg/handler/v2/cluster/kubeconfig.go
  pkg/handler/v2/cluster/kubeconfig_test.go
  pkg/handler/v2/cluster/serviceaccount.go
  pkg/handler/v2/cluster/serviceaccount_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/project/create_cluster_service_account_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/create_cluster_service_account_responses.go
  pkg/test/e2e/utils/apiclient/client/project/delete_cluster_service_account_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/delete_cluster_service_account_responses.go
  pkg/test/e2e/utils/apiclient/client/project/get_cluster_service_account_kubeconfig_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/get_cluster_service_account_kubeconfig_responses.go
  pkg/test/e2e/utils/apiclient/client/project/list_cluster_service_account_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/list_cluster_service_account_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/utils/apiclient/models/cluster_service_account.go
Labels: kind/feature, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/api, docs/tbd

#11190 Fix Seed-Proxy ServiceAccount token not being generated
  pkg/controller/master-controller-manager/seed-proxy/controller.go
  pkg/controller/master-controller-manager/seed-proxy/reconciler.go
  pkg/controller/master-controller-manager/seed-proxy/resources.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, kind/regression, docs/none

#11197 fix convert-kubeconfig command not generating a SA token
  cmd/kubermatic-installer/cmd_convert_kubeconfig.go
  pkg/controller/master-controller-manager/seed-proxy/resources.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#11198 Simplify expose-strategy tests
  pkg/test/e2e/expose-strategy/client.go
  pkg/test/e2e/expose-strategy/tunneling_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#11196 [release/v2.20] Fix Seed-Proxy ServiceAccount token not being generated (#11190)
  pkg/controller/master-controller-manager/seed-proxy/controller.go
  pkg/controller/master-controller-manager/seed-proxy/reconciler.go
  pkg/controller/master-controller-manager/seed-proxy/resources.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#11205 adjust to the dashboard's new primary branch name
  hack/ci/canary-github-release.sh
  hack/ci/deploy-offline.sh
  hack/ci/push-images.sh
  hack/run-operator.sh
Labels: kind/cleanup, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#11133 Update tests to kind 0.16
  .prow/api.yaml
  .prow/ccm-migrations.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  charts/mla/minio-lifecycle-mgr/templates/lifecycle-mgr-cronjob.yaml
  hack/ci/setup-kind-cluster.sh
  hack/ci/setup-kubermatic-mla-in-kind.sh
  hack/update-codegen.sh
  hack/update-swagger.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/none

#11207 Fix image references in MLA helm charts and add metrics-scraper image to `mirror-images`
  charts/logging/promtail/test/default.yaml.out
  charts/logging/promtail/test/kubermatic.example.ce.yaml.out
  charts/logging/promtail/test/kubermatic.example.ee.yaml.out
  charts/logging/promtail/values.yaml
  charts/mla/alertmanager-proxy/test/default.yaml.out
  charts/mla/alertmanager-proxy/values.yaml
  charts/mla/consul/test/config.yaml.out
  charts/mla/consul/test/default.yaml.out
  charts/mla/consul/values.yaml
  charts/mla/grafana/README.md
  charts/mla/grafana/test/config.yaml.out
  charts/mla/grafana/test/default.yaml.out
  charts/mla/grafana/values.yaml
  charts/mla/loki-distributed/test/config.yaml.out
  charts/mla/loki-distributed/test/default.yaml.out
  charts/mla/loki-distributed/values.yaml
  charts/mla/minio-lifecycle-mgr/templates/lifecycle-mgr-cronjob.yaml
  charts/mla/minio-lifecycle-mgr/test/config.yaml.out
  charts/mla/minio-lifecycle-mgr/test/default.yaml.out
  charts/mla/minio/values.yaml
  pkg/controller/user-cluster-controller-manager/resources/resources/envoy-agent/daemonset.go
  pkg/install/images/images.go
Labels: kind/bug, kind/cleanup, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, kind/regression, docs/none

#11208 [release/v2.21] Add missing image for metrics-scraper to `pkg/install/images` (#11207)
  pkg/install/images/images.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#11210 ensure the KKP Docker image contains our CRDs
  hack/ci/push-images.sh
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#11213 Properly check condition array length for GKE status before accessing it
  pkg/provider/cloud/gke/provider.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, backport-needed

#11218 Add changelog entries for October 2022 patch releases
  docs/changelogs/CHANGELOG-2.19.md
  docs/changelogs/CHANGELOG-2.20.md
  docs/changelogs/CHANGELOG-2.21.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none, sig/release

#11211 Switch AWS account for E2E tests
  .prow/ccm-migrations.yaml
  .prow/features.yaml
  .prow/provider-aws.yaml
  hack/ci/run-cilium-e2e-test.sh
  hack/ci/run-dualstack-e2e-test.sh
  hack/ci/run-konnectivity-e2e-test.sh
  hack/run-conformance-tests.sh
  pkg/test/dualstack/README.md
  pkg/test/dualstack/cloud_providers.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#11219 [release/v2.21] Switch AWS account for E2E tests (#11211)
  .prow/features.yaml
  .prow/provider-aws.yaml
  hack/ci/run-cilium-e2e-test.sh
  hack/ci/run-dualstack-e2e-test.sh
  hack/ci/run-konnectivity-e2e-test.sh
  hack/run-conformance-tests.sh
  pkg/test/dualstack/README.md
  pkg/test/dualstack/cloud_providers.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore

#11220 [release/v2.20] Switch AWS account for E2E tests (#11211)
  .prow.yaml
  hack/run-conformance-tests.sh
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore

#11223 Use AWS spot instances in E2E tests
  cmd/conformance-tester/pkg/scenarios/aws.go
  pkg/test/dualstack/cloud_providers.go
  pkg/test/e2e/ccm-migration/providers/aws.go
  pkg/test/e2e/cilium/cilium_test.go
  pkg/test/e2e/jig/machine.go
  pkg/test/e2e/jig/presets.go
  pkg/test/e2e/konnectivity/konnectivity_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, docs/none

#11204 Add annotation to pause any resource updates
  docs/dev-getting-started.md
  pkg/resources/reconciling/ensure.go
  pkg/resources/reconciling/ensure_test.go
Labels: kind/feature, size/L, ok-to-test, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/tbd

#11226 Remove redundant E2E jigging code in CCM Migration tests
  hack/ci/run-cilium-e2e-test.sh
  hack/ci/run-etcd-launcher-tests.sh
  hack/ci/run-ipam-e2e-tests.sh
  hack/ci/run-konnectivity-e2e-test.sh
  hack/ci/run-mla-e2e-tests.sh
  hack/ci/run-opa-e2e-tests.sh
  hack/run-ccm-migration-e2e-test-in-kind.sh
  hack/run-expose-strategy-e2e-test-in-kind.sh
  pkg/test/e2e/ccm-migration/ccm_migration_test.go
  pkg/test/e2e/ccm-migration/cluster.go
  pkg/test/e2e/ccm-migration/providers/aws.go
  pkg/test/e2e/ccm-migration/providers/azure.go
  pkg/test/e2e/ccm-migration/providers/cluster.go
  pkg/test/e2e/ccm-migration/providers/openstack.go
  pkg/test/e2e/ccm-migration/providers/scenario.go
  pkg/test/e2e/ccm-migration/providers/vsphere.go
  pkg/test/e2e/ccm-migration/utils/const.go
  pkg/test/e2e/ccm-migration/utils/helpers.go
  pkg/test/e2e/cilium/cilium_test.go
  pkg/test/e2e/etcd-launcher/etcd_test.go
  pkg/test/e2e/expose-strategy/tunneling_test.go
  pkg/test/e2e/ipam/ipam_test.go
  pkg/test/e2e/jig/credentials.go
  pkg/test/e2e/jig/flags.go
  pkg/test/e2e/jig/machine.go
  pkg/test/e2e/jig/presets.go
  pkg/test/e2e/konnectivity/konnectivity_test.go
  pkg/test/e2e/mla/mla_test.go
  pkg/test/e2e/opa/opa_test.go
Labels: kind/cleanup, size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#11233 Fixe rendering error of the metallb addon causing missing L2Advertisement
  addons/metallb/01_address-pools.yaml
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/none

#11238 Include MLA charts in release packages
  hack/ci/github-release.sh
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#11239 [release/v2.21] remove docker image digests in addons
  addons/cilium/cilium_v1.11.yaml
  addons/cilium/cilium_v1.12.yaml
  addons/hubble/hubble_v1.11.yaml
  addons/hubble/hubble_v1.12.yaml
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management

#11049 Add Kubernetes 1.25
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  Dockerfile
  addons/azure-cloud-node-manager/cloud-node-manager.yaml
  addons/cluster-autoscaler/cluster-autoscaler.yaml
  addons/csi/digitalocean/csi-driver.yaml
  addons/csi/hetzner/hcloud-csi-1.6.0.yaml
  addons/csi/nutanix/csi-driver.yaml
  addons/csi/openstack/controllerplugin.yaml
  addons/csi/openstack/nodeplugin.yaml
  addons/csi/vsphere/vsphere-csi-driver.yaml
  cmd/conformance-tester/pkg/util/ginkgo.go
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
  pkg/resources/cloudcontroller/aws.go
  pkg/resources/cloudcontroller/azure.go
  pkg/resources/cloudcontroller/openstack.go
  pkg/resources/cloudcontroller/util.go
  pkg/resources/cloudcontroller/vsphere.go
  pkg/resources/kubernetes-dashboard/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.22.1-aws-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-aws-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-aws-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-openstack-cloud-controller-manager-externalCloudProvider.yaml
  pkg/util/kubectl/kubectl.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, docs/none

#11241 [release/v2.19] Add RBAC role creation that was accidentally removed in #11117
  pkg/controller/master-controller-manager/rbac/sync_resource.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/regression

#11243 Add feature flag to enable/disable the Web Terminal for the user clusters
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/settings.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  pkg/handler/test/helper.go
  pkg/handler/v1/admin/settings_test.go
  pkg/provider/kubernetes/settings.go
  pkg/test/e2e/utils/apiclient/models/setting_spec.go
Labels: kind/feature, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, docs/tbd

#11236 Fix panic in cluster webhook
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, docs/none

#11202 Refactor KubeVirt cloud provider - part 1
  pkg/ee/validation/machine/providers.go
  pkg/handler/common/provider/kubevirt.go
  pkg/handler/common/provider/kubevirt_test.go
  pkg/handler/v2/provider/kubevirt_test.go
  pkg/provider/cloud/kubevirt/client.go
  pkg/provider/cloud/kubevirt/client_test.go
  pkg/provider/cloud/kubevirt/csi.go
  pkg/provider/cloud/kubevirt/data_volume.go
  pkg/provider/cloud/kubevirt/manifests/manifests.go
  pkg/provider/cloud/kubevirt/manifests/preferences/sockets-advantage.yaml
  pkg/provider/cloud/kubevirt/namespace.go
  pkg/provider/cloud/kubevirt/network_policy.go
  pkg/provider/cloud/kubevirt/provider.go
  pkg/provider/cloud/kubevirt/storage_class.go
  pkg/provider/cloud/kubevirt/vm_instancetype.go
  pkg/provider/cloud/kubevirt/vm_preference.go
  pkg/provider/cloud/kubevirt/vm_preset.go
  pkg/resources/cloudcontroller/kubevirt.go
Labels: kind/cleanup, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, docs/none

#11242 use Go 1.19 build image for dualstack tests
  .prow/dualstack.yaml
  .prow/features.yaml
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, docs/none

#11249 Upgrade KubeVirt CCM to v0.4.0 and kubevirt.io/api to v0.58.0
  go.mod
  go.sum
  pkg/resources/cloudcontroller/kubevirt.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#11251 Don't update version of mla-secrets chart automatically
  hack/lib.sh
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#11254 Make the Web Terminal feature flag optional in the configuration
  pkg/apis/kubermatic/v1/settings.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, sig/api, docs/none

#11253 Fix validation of block-type secrets in mla-iap configuration
  pkg/install/stack/usercluster-mla/validation.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#11229 Deploy KKP API based on the dashboard Docker image
  .prow/api.yaml
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  hack/ci/setup-kubermatic-in-kind.sh
  pkg/controller/operator/master/resources/kubermatic/api.go
  pkg/controller/operator/master/resources/kubermatic/ui.go
  pkg/defaulting/configuration.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#11247 [release/v2.21] Fix panic in cluster webhook (#11236)
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
  pkg/webhook/cluster/validation/validation_test.go
  pkg/webhook/clustertemplate/validation/validation_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes
