Repository kubermatic/kubermatic, pull requests merged in 2022-09, with the labels that each got.

#10892 remove 2.21->2.22 migration code
  cmd/kubermatic-installer/cmd_deploy.go
  pkg/controller/operator/master/resources/kubermatic/master-controller-manager.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/seed-controller-manager/update-controller/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/util/applications.go
  pkg/install/stack/kubermatic-master/migrations.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/stack/kubermatic-seed/migrations.go
  pkg/install/stack/kubermatic-seed/stack.go
  pkg/install/stack/types.go
  pkg/install/util/crd.go
  pkg/install/util/migrations.go
  pkg/resources/resources.go
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
Labels: kind/cleanup, size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10816 Anexia: allow extended disk configuration in AnexiaNodeSpec
  .prow/provider-anexia.yaml
  cmd/conformance-tester/pkg/scenarios/anexia.go
  cmd/conformance-tester/pkg/scenarios/base.go
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/api/v1/types_test.go
  pkg/machine/convert.go
  pkg/resources/machine/common.go
  pkg/test/e2e/utils/apiclient/models/anexia_disk_config.go
  pkg/test/e2e/utils/apiclient/models/anexia_node_spec.go
Labels: kind/bug, kind/feature, size/L, kind/api-change, ok-to-test, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10889 Add report types to metering schedule configuration
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/ee/metering/report_config_handler.go
  pkg/ee/metering/report_config_handler_test.go
  pkg/handler/routes_v1_admin.go
  pkg/handler/v1/admin/metering.go
  pkg/handler/v1/admin/wrappers_ce.go
  pkg/handler/v1/admin/wrappers_ee.go
  pkg/test/e2e/utils/apiclient/client/admin/admin_client.go
  pkg/test/e2e/utils/apiclient/client/admin/create_metering_report_configuration_responses.go
  pkg/test/e2e/utils/apiclient/client/admin/update_metering_report_configuration_responses.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/api

#10908 Explicitly create KubeVirt service accounts token if not found
  pkg/provider/cloud/kubevirt/csi.go
  pkg/provider/cloud/kubevirt/data_volume.go
  pkg/provider/cloud/kubevirt/helper.go
  pkg/provider/cloud/kubevirt/reconciler.go
  pkg/provider/kubernetes/credentials.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10899 remove Go dependency on metallb
  go.mod
  go.sum
  pkg/test/e2e/ipam/ipam_test.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note-none, dco-signoff: yes

#10910 Add Default to Subnet list API Endpoint response
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/apis/kubermatic/v1/external_cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  pkg/handler/common/provider/eks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_cluster_roles_responses.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_cluster_role.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_cluster_role_list.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_cluster_roles_list.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_subnet.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10918 Fix vSphere integration and e2e tests
  hack/ci/testdata/seed.yaml
  pkg/provider/cloud/vsphere/network_test.go
Labels: kind/bug, size/S, kind/failing-test, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10907 Check KKP and seed versions in installer to prevent minor version skips
  pkg/install/stack/kubermatic-master/validation.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#10888 Remove Region from EKS Preset
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/preset.go
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/test/e2e/utils/apiclient/models/e_k_s.go
Labels: kind/feature, kind/api-change, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10894 validate length of EAR encryption key
  pkg/controller/seed-controller-manager/encryption-at-rest-controller/controller.go
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10920 fix installer version check
  pkg/install/stack/kubermatic-master/validation.go
  pkg/version/kubermatic/versions.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10926 [release/v2.21] Fix vSphere integration and e2e tests
  hack/ci/testdata/seed.yaml
  pkg/provider/cloud/vsphere/network_test.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10919 Add location to aksCloudSpec
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_cluster_spec.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10916 [release/v2.21] Anexia: allow extended disk configuration in AnexiaNodeSpec
  .prow/provider-anexia.yaml
  cmd/conformance-tester/pkg/scenarios/anexia.go
  cmd/conformance-tester/pkg/scenarios/base.go
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/api/v1/types_test.go
  pkg/machine/convert.go
  pkg/resources/machine/common.go
  pkg/test/e2e/utils/apiclient/models/anexia_disk_config.go
  pkg/test/e2e/utils/apiclient/models/anexia_node_spec.go
Labels: kind/bug, kind/feature, size/L, kind/api-change, ok-to-test, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10932 Don't attempt to manage membership if etcd cluster was not initialised before
  cmd/etcd-launcher/main.go
  pkg/test/e2e/etcd-launcher/etcd_test.go
  pkg/test/e2e/jig/cluster.go
  pkg/test/e2e/jig/presets.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/regression

#10913 Enhance AKS external cluster status information
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/provider/cloud/aks/provider.go
  pkg/resources/resources.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_cluster_status.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_m_d_phase.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_power_state.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_provisioning_state.go
  pkg/test/e2e/utils/apiclient/models/external_cluster_m_d_phase.go
  pkg/test/e2e/utils/apiclient/models/external_cluster_status.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10930 Fix listing external clusters
  pkg/api/v2/types.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#10935 Enable EtcdLauncher feature gate on CI KubermaticConfigurations
  hack/ci/testdata/kubermatic.yaml
  hack/ci/testdata/kubermatic_dualstack.yaml
  hack/ci/testdata/kubermatic_headless.yaml
  hack/ci/testdata/kubermatic_konnectivity.yaml
  hack/ci/testdata/kubermatic_mla.yaml
Labels: kind/cleanup, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10937 Prefer InternalIP for Hetzner dual-stack clusters
  pkg/resources/apiserver/deployment.go
  pkg/resources/metrics-server/deployment.go
  pkg/resources/resources.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#10934 use vcenter internal address
  hack/ci/testdata/seed.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10947 Add location to getcluster if crd doesnt has location
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/common/provider/aks.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_cluster.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10939 List EKS worker node roles
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/common/provider/eks.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/eks/eks_client.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_node_roles_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_node_roles_responses.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_node_role.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_node_role_list.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#10948 Fix OSM migration on external Seed clusters
  pkg/controller/operator/seed/reconciler.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#10927 [release/v2.20] Fix vSphere integration and e2e tests
  cmd/conformance-tests/scenarios_vsphere.go
  hack/ci/testdata/seed.yaml
  hack/ci/testdata/seed_backup.yaml
  pkg/provider/cloud/vsphere/network_test.go
  pkg/test/e2e/ccm-migration/ccm_migration_test.go
  pkg/test/e2e/ccm-migration/cluster.go
Labels: kind/bug, kind/failing-test, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10938 Enhance treatment of missing credential privilege for AKS external cluster
  go.mod
  go.sum
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/provider/cloud/aks/provider.go
Labels: kind/feature, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10953 Fix for panic when creating dc on nil map
  pkg/handler/v1/dc/datacenter.go
  pkg/handler/v1/dc/datacenter_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/api

#10952 Update Cilium 1.12 to v1.12.1
  addons/Makefile
  addons/cilium/cilium_v1.12.yaml
  addons/hubble/hubble_v1.12.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#10951 Fix webhook on seed-only clusters
  pkg/controller/master-controller-manager/seed-sync/reconciler.go
  pkg/controller/master-controller-manager/seed-sync/reconciler_test.go
  pkg/controller/master-controller-manager/seed-sync/resources.go
  pkg/controller/operator/seed-init/reconciler.go
  pkg/provider/kubernetes/seed.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10955 update Go dependencies
  .wwhrd.yml
  go.mod
  go.sum
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore

#10959 [release/v2.20] Fix webhook on seed-only clusters (#10951)
  pkg/controller/master-controller-manager/seed-sync/reconciler.go
  pkg/controller/master-controller-manager/seed-sync/reconciler_test.go
  pkg/controller/master-controller-manager/seed-sync/resources.go
  pkg/provider/seed.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#10950 Helm client integration tests
  pkg/applications/helmclient/client_integration_test.go
  pkg/applications/helmclient/client_test.go
  pkg/applications/helmclient/testdata/examplechart-v2/values.yaml
Labels: kind/cleanup, lgtm, approved, release-note-none, dco-signoff: yes

#10961 update to envoyproxy go-control-plane 0.10.3
  go.mod
  go.sum
  pkg/controller/nodeport-proxy/envoymanager/controller_test.go
  pkg/controller/nodeport-proxy/envoymanager/resources.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore

#10968 Fix Openstack getTenant issue with ErrEndpointNotFound
  pkg/provider/cloud/openstack/helper.go
  pkg/provider/cloud/openstack/helper_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#10981 [release/v2.21] vCenter change
  hack/ci/testdata/seed.yaml
  pkg/provider/cloud/vsphere/ca_test.go
  pkg/provider/cloud/vsphere/folder_test.go
  pkg/provider/cloud/vsphere/integration_test.go
  pkg/test/e2e/ccm-migration/ccm_migration_test.go
  pkg/test/e2e/ccm-migration/providers/vsphere.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10984 seed-proxy: increase memory limit from 32Mi to 64Mi
  pkg/controller/master-controller-manager/seed-proxy/resources.go
Labels: kind/feature, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#10983 [release/v2.21] fix spellcheck findings
  addons/cilium/cilium_v1.11.yaml
  addons/cilium/cilium_v1.12.yaml
  charts/monitoring/prometheus/rules/general-kube-kubelet.yaml
  charts/monitoring/prometheus/rules/src/general/kube-kubelet.yaml
  cmd/conformance-tester/pkg/clients/client_api.go
  cmd/conformance-tester/pkg/clients/client_kube.go
  docs/README.md
  docs/dev-getting-started.md
  docs/proposals/integrate-upstream-machineset-and-machinedeployment-controllers.md
  docs/proposals/kubermatic-installer.md
  pkg/apis/kubermatic/v1/addon.go
  pkg/apis/kubermatic/v1/user.go
  pkg/applications/installer_test.go
  pkg/applications/providers/util/util.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/suite_test.go
  pkg/crd/k8c.io/kubermatic.k8c.io_addons.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_users.yaml
  pkg/provider/seed_test.go
  pkg/provider/types.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#10960 Allow removal of specific datacenter IPAM Pool
  cmd/kubermatic-webhook/main.go
  pkg/controller/seed-controller-manager/ipam/controller.go
  pkg/controller/seed-controller-manager/ipam/controller_test.go
  pkg/test/e2e/ipam/ipam_test.go
  pkg/webhook/ipampool/validation/validation.go
  pkg/webhook/ipampool/validation/validation_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10986 [release/v2.20] Add Kubernetes 1.22.14, 1.23.11 (#10985)
  .prow.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/addon/template_test.go
  pkg/controller/operator/defaults/defaults.go
  pkg/controller/seed-controller-manager/backup/backup_controller_test.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller_test.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, kind/chore

#10987 [release/v2.19] Add Kubernetes 1.22.14 (#10985)
  .prow.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/addon/template_test.go
  pkg/controller/operator/defaults/defaults.go
  pkg/controller/seed-controller-manager/backup/backup_controller_test.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller_test.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, kind/chore

#10989 Add kind/chore to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/cleanup, lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10957 Update to controller-runtime 0.13.0
  cmd/conformance-tester/pkg/tests/metrics.go
  cmd/kubermatic-api/swagger.json
  go.mod
  go.sum
  pkg/controller/master-controller-manager/kubeone/controller.go
  pkg/controller/operator/seed-init/reconciler.go
  pkg/controller/seed-controller-manager/backup/backup_controller.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller.go
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/controller/seed-controller-manager/seedresourcesuptodatecondition/seedresourcesuptodatecondition_controller_test.go
  pkg/install/util/kubernetes.go
  pkg/test/e2e/jig/cluster.go
  pkg/test/e2e/konnectivity/konnectivity_test.go
  pkg/test/e2e/nodeport-proxy/services.go
  pkg/test/e2e/utils/apiclient/models/object_reference.go
  pkg/test/e2e/utils/apiclient/models/policy_rule.go
  pkg/test/e2e/utils/apiclient/models/quantity.go
  pkg/test/e2e/utils/apiclient/models/raw_extension.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, kind/chore

#10985 Add Kubernetes 1.22.14, 1.23.11 and 1.24.5
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/defaulting/configuration.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/api, kind/chore

#10922 Migrate AWS and EKS providers to AWS SDK v2 for Go
  cmd/conformance-tester/pkg/scenarios/aws.go
  cmd/kubermatic-api/swagger.json
  go.mod
  go.sum
  pkg/api/v2/types.go
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/handler/common/provider/aws.go
  pkg/handler/common/provider/eks.go
  pkg/handler/v1/provider/aws.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/node.go
  pkg/provider/cloud/aws/api.go
  pkg/provider/cloud/aws/client.go
  pkg/provider/cloud/aws/client_test.go
  pkg/provider/cloud/aws/instance_profile.go
  pkg/provider/cloud/aws/instance_profile_test.go
  pkg/provider/cloud/aws/migrate_ownership.go
  pkg/provider/cloud/aws/migrate_ownership_test.go
  pkg/provider/cloud/aws/provider.go
  pkg/provider/cloud/aws/provider_test.go
  pkg/provider/cloud/aws/role.go
  pkg/provider/cloud/aws/role_test.go
  pkg/provider/cloud/aws/route_table.go
  pkg/provider/cloud/aws/route_table_test.go
  pkg/provider/cloud/aws/security_group.go
  pkg/provider/cloud/aws/security_group_test.go
  pkg/provider/cloud/aws/tags.go
  pkg/provider/cloud/aws/tags_test.go
  pkg/provider/cloud/aws/util.go
  pkg/provider/cloud/aws/util_test.go
  pkg/provider/cloud/aws/vpc.go
  pkg/provider/cloud/aws/vpc_test.go
  pkg/provider/cloud/eks/authenticator/arn.go
  pkg/provider/cloud/eks/authenticator/token.go
  pkg/provider/cloud/eks/provider.go
  pkg/provider/kubernetes/credentials.go
  pkg/resources/machine/common.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_machine_deployment_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_nodegroup_scaling_config.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10993 Filter eks sizes based on architecture
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/common/architecture.go
  pkg/handler/common/provider/eks.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/cloud/eks/provider.go
  pkg/test/e2e/utils/apiclient/client/eks/eks_client.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_cluster_roles_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_instance_types_no_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_regions_parameters.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_instance_type.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_machine_deployment_cloud_spec.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10992 Remove proxy url from nutanix e2e flags
  .prow/provider-nutanix.yaml
  hack/ci/run-conformance-tests.sh
Labels: kind/cleanup, kind/failing-test, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10996 add cri pipeline_stage to promtail config
  charts/logging/promtail/values.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#10975 Fix externalcluster swagger and endpoint
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/provider/eks.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/eks/eks_client.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_node_roles_no_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_node_roles_no_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_node_roles_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_node_roles_responses.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_disk_types_parameters.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#10979 [release/v2.20] vCenter change
  hack/ci/testdata/seed.yaml
  pkg/provider/cloud/vsphere/ca_test.go
  pkg/provider/cloud/vsphere/folder_test.go
  pkg/provider/cloud/vsphere/integration_test.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#11010 fix: make cri a list item
  charts/logging/promtail/values.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#11013 Upgrade to cilium v1.12.2 and v1.11.9
  addons/Makefile
  addons/cilium/cilium_v1.11.yaml
  addons/cilium/cilium_v1.12.yaml
  addons/hubble/hubble_v1.11.yaml
  addons/hubble/hubble_v1.12.yaml
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management

#11007 Support for Ubuntu 22.04
  cmd/conformance-tester/pkg/scenarios/kubevirt.go
  hack/ci/testdata/seed.yaml
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller.yaml
  pkg/test/dualstack/cloud_providers.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#11027 Bump Kubernetes versions
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/defaulting/configuration.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, kind/chore

#11022 Bump Openstack CCM to 1.23.4 for k8s 1.23
  pkg/resources/cloudcontroller/openstack.go
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-openstack-cloud-controller-manager-externalCloudProvider.yaml
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#11028 [release/v2.20] Bump Kubernetes versions (#11027)
  .prow.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/addon/template_test.go
  pkg/controller/operator/defaults/defaults.go
  pkg/controller/seed-controller-manager/backup/backup_controller_test.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller_test.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, kind/chore

#11029 [release/v2.19] Bump Kubernetes versions (#11027)
  .prow.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/addon/template_test.go
  pkg/controller/operator/defaults/defaults.go
  pkg/controller/seed-controller-manager/backup/backup_controller_test.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller_test.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, kind/chore, sig/crd

#11037 [release/v2.20] Bump Openstack CCM to 1.23.4 for k8s 1.23
  pkg/resources/cloudcontroller/openstack.go
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-openstack-cloud-controller-manager-externalCloudProvider.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#11042 add changelogs for 2.19.9, 2.20.7, 2.21.1
  docs/changelogs/CHANGELOG-2.19.md
  docs/changelogs/CHANGELOG-2.20.md
  docs/changelogs/CHANGELOG-2.21.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore

#11048 Use unordered comparison of vsphere networks
  go.mod
  go.sum
  pkg/provider/cloud/vsphere/network_test.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore

#10997 more info to run user-cluster-controller-manager locally
  README.md
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes

#11025 Use go:embed for presets and reconcile VirtualMachine instancetype and preference
  codegen/reconcile/main.go
  hack/update-codegen.sh
  pkg/handler/common/provider/kubevirt.go
  pkg/provider/cloud/kubevirt/instancetype.go
  pkg/provider/cloud/kubevirt/manifests/instancetypes/standard-2.yaml
  pkg/provider/cloud/kubevirt/manifests/instancetypes/standard-4.yaml
  pkg/provider/cloud/kubevirt/manifests/instancetypes/standard-8.yaml
  pkg/provider/cloud/kubevirt/manifests/manifests.go
  pkg/provider/cloud/kubevirt/manifests/manifests_test.go
  pkg/provider/cloud/kubevirt/manifests/preferences/sockets-advantage.yaml
  pkg/provider/cloud/kubevirt/manifests/presets/kubermatic-standard.yaml
  pkg/provider/cloud/kubevirt/manifests/test/instancetypes/invalid-standard.yaml
  pkg/provider/cloud/kubevirt/manifests/test/instancetypes/standard-1.yaml
  pkg/provider/cloud/kubevirt/manifests/test/preferences/invalid-standard.yaml
  pkg/provider/cloud/kubevirt/manifests/test/preferences/standard-1.yaml
  pkg/provider/cloud/kubevirt/manifests/test/presets/invalid-standard.yaml
  pkg/provider/cloud/kubevirt/manifests/test/presets/standard-1.yaml
  pkg/provider/cloud/kubevirt/manifests/test/presets/standard-2.yaml
  pkg/provider/cloud/kubevirt/preference.go
  pkg/provider/cloud/kubevirt/preset.go
  pkg/provider/cloud/kubevirt/provider.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/virtualization

#11053 change select for lokiloader to app=k8c-events-lokiloader
  charts/logging/promtail/values.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#11052 [release/v2.21] use unordered comparison of vsphere networks & fix flakiness documentation generation (#11048, #10985)
  cmd/kubermatic-api/swagger.json
  codegen/example-yaml/main.go
  docs/zz_generated.applicationInstallation.yaml
  go.mod
  go.sum
  pkg/api/v2/types.go
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/apis/apps.kubermatic/v1/zz_generated.deepcopy.go
  pkg/applications/installer_test.go
  pkg/applications/providers/template/helm_integration_test.go
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_test.go
  pkg/handler/test/helper.go
  pkg/handler/v2/application_installation/application_installation_test.go
  pkg/handler/v2/application_installation/conversion.go
  pkg/provider/cloud/vsphere/network_test.go
  pkg/validation/application_installation_test.go
  pkg/webhook/application/applicationinstallation/validation/validation_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, kind/chore

#11045 Fix STS tokens generated for EKS clusters
  pkg/provider/cloud/eks/authenticator/token.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, kind/regression

#11046 Fix wrong quota filtering when preset.spec.cpu has no quantity
  pkg/handler/common/provider/kubevirt.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/api, sig/virtualization

#11043 Fix for AKS external cluster: "delete" permission shouldn't be checked for import
  pkg/handler/v2/external_cluster/aks.go
  pkg/provider/cloud/aks/provider.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#11050 [release/v2.21] Fix Anexia disk config
  pkg/machine/convert.go
Labels: kind/bug, ok-to-test, lgtm, approved, release-note, size/XS, dco-signoff: yes

#11023 Add expiration time for the user web terminal pod
  pkg/handler/common/kubeconfig.go
  pkg/handler/routes_v1_websocket.go
  pkg/handler/websocket/terminal.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#11035 add method to handle the os patch in the Patch Machine Deployment end…
  pkg/handler/common/machine.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#11047 [release/v2.20] gracefully handle missing owner in cluster status
  cmd/user-cluster-controller-manager/main.go
  pkg/controller/user-cluster-controller-manager/owner-binding-creator/controller.go
  pkg/controller/user-cluster-controller-manager/owner-binding-creator/controller_test.go
  pkg/resources/test/fixtures/deployment-aws-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-usercluster-controller.yaml
  pkg/resources/usercluster/deployment.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#10982 Add fields to externalcluster CRD
  pkg/apis/kubermatic/v1/external_cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#11034 Anexia: update CloudControllerManager to v1.4.4
  pkg/resources/cloudcontroller/anexia.go
Labels: ok-to-test, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#11061 Fix setting exposeStrategy via KKP cluster API endpoint
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/common/cluster.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/resources/cluster/cluster.go
  pkg/test/e2e/utils/apiclient/models/cluster_spec.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#11072 [release/v2.21] Support for Ubuntu 22.04
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller.yaml
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#11082 Make externalcluster crd fields optional
  pkg/apis/kubermatic/v1/external_cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#11076 Grafana GroupProjectBinding support
  pkg/controller/seed-controller-manager/mla/grafana.go
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/org_user_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/org_user_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller_test.go
Labels: kind/feature, size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#11080 Upgrade konnectivity version to v0.0.33
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/deployment.go
  pkg/resources/konnectivity/sidecar.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#11096 enhance cluster rbac: allow to bind service account to clusterRole and Role
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/common/binding.go
  pkg/handler/test/helper.go
  pkg/handler/v2/cluster/binding.go
  pkg/handler/v2/cluster/binding_test.go
  pkg/test/e2e/utils/apiclient/models/cluster_role_user.go
  pkg/test/e2e/utils/apiclient/models/role_user.go
Labels: kind/feature, kind/api-change, size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/api, docs/tbd

#11085 KubeVirt API endpoints for instancetypes and preferences
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/common/provider/kubevirt.go
  pkg/handler/common/provider/kubevirt_test.go
  pkg/handler/v2/provider/kubevirt.go
  pkg/handler/v2/provider/kubevirt_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/kubevirt/kubevirt_client.go
  pkg/test/e2e/utils/apiclient/client/kubevirt/list_kube_virt_instancetypes_no_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/kubevirt/list_kube_virt_instancetypes_no_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/kubevirt/list_kube_virt_instancetypes_parameters.go
  pkg/test/e2e/utils/apiclient/client/kubevirt/list_kube_virt_instancetypes_responses.go
  pkg/test/e2e/utils/apiclient/client/kubevirt/list_kube_virt_preferences_no_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/kubevirt/list_kube_virt_preferences_no_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/kubevirt/list_kube_virt_preferences_parameters.go
  pkg/test/e2e/utils/apiclient/client/kubevirt/list_kube_virt_preferences_responses.go
  pkg/test/e2e/utils/apiclient/models/virtual_machine_instancetype.go
  pkg/test/e2e/utils/apiclient/models/virtual_machine_instancetype_list.go
  pkg/test/e2e/utils/apiclient/models/virtual_machine_preference.go
  pkg/test/e2e/utils/apiclient/models/virtual_machine_preference_list.go
Labels: kind/feature, kind/api-change, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/api, sig/virtualization, docs/provided

#11099 Add a temp controller which removes all UPB mla finalizers
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/upb_controller.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management, docs/none

#11104 [release/v2.20] Fix vSphere network test
  pkg/provider/cloud/vsphere/network_test.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#11105 Support for setting default OperatingSystemProfiles at the seed level
  cmd/kubermatic-api/swagger.json
  codegen/example-yaml/main.go
  docs/zz_generated.seed.yaml
  pkg/api/v1/types.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/handler/v1/dc/datacenter.go
  pkg/resources/machine/machinedeployment.go
  pkg/test/e2e/utils/apiclient/models/datacenter_spec.go
  pkg/test/e2e/utils/apiclient/models/operating_system_profile_list.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, docs/none

#11112 fix cluster webhook regression
  pkg/webhook/cluster/mutation/mutator.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/regression, docs/none

#11109 simplify vsphere network test
  go.mod
  go.sum
  pkg/provider/cloud/vsphere/network_test.go
Labels: kind/cleanup, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#11108 remove deprecated golangci linters
  .golangci.yml
Labels: kind/cleanup, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#11051 [release/v2.20] Fix Anexia disk config
  pkg/machine/convert.go
Labels: kind/bug, ok-to-test, lgtm, approved, release-note, size/XS, dco-signoff: yes

#11117 [release/v2.19] Adjust ETCD_INITIAL_CLUSTER during peer TLS migration (#9322)
  cmd/etcd-launcher/main.go
  pkg/controller/master-controller-manager/rbac/sync_resource.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#11116 [release/v2.20] Adjust ETCD_INITIAL_CLUSTER during peer TLS migration (#9322)
  cmd/etcd-launcher/main.go
  pkg/controller/master-controller-manager/rbac/sync_resource.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management
