Repository kubermatic/kubermatic, pull requests merged in 2022-06, with the labels that each got.

#9912 Validate cluster version against supported versions in webhook
  cmd/kubermatic-webhook/main.go
  hack/run-expose-strategy-e2e-test-in-kind.sh
  pkg/handler/common/cluster.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/resources/cluster/cluster.go
  pkg/test/e2e/expose-strategy/expose_strategy_suite_test.go
  pkg/test/helper.go
  pkg/validation/cluster.go
  pkg/webhook/cluster/validation/validation.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9949 Disable dualstack-e2e test trigger
  .prow/features.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#9898 updates in KubeVirtCloudSpec to inject infraStorageClass info
  addons/csi/kubevirt/csi-driver-operator.yaml
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.addondata.go.txt
  pkg/addon/template.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/handler/common/provider/kubevirt.go
  pkg/provider/cloud/kubevirt/provider.go
  pkg/provider/cloud/kubevirt/storage.go
  pkg/test/e2e/utils/apiclient/models/kubevirt_cloud_spec.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#9956 Revert "updates in KubeVirtCloudSpec to inject infraStorageClass info"
  addons/csi/kubevirt/csi-driver-operator.yaml
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.addondata.go.txt
  pkg/addon/template.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/handler/common/provider/kubevirt.go
  pkg/provider/cloud/kubevirt/provider.go
  pkg/provider/cloud/kubevirt/storage.go
  pkg/test/e2e/utils/apiclient/models/kubevirt_cloud_spec.go
Labels: size/L, lgtm, approved, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#9941 wwhrd.yml: add github.com/acomagu/bufpipe to the exeption list
  .wwhrd.yml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#9800 Add rocky linux as an os
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/controller/user-cluster-controller-manager/node-labeler/api/api.go
  pkg/machine/convert.go
  pkg/resources/machine/common.go
  pkg/resources/machine/machinedeployment.go
  pkg/test/e2e/utils/apiclient/models/operating_system_spec.go
  pkg/test/e2e/utils/apiclient/models/rocky_linux_spec.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9973 fix hack/local/run-kubermatic-kind.sh
  hack/local/run-kubermatic-kind.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#9952 update integration-test image to use Go 1.18
  .prow/tests.yaml
  hack/images/integration-tests/Dockerfile
  hack/images/integration-tests/release.sh
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#9932 Fetch kubeone error codes and message from logs
  go.mod
  go.sum
  pkg/apis/kubermatic/v1/external_cluster.go
  pkg/controller/master-controller-manager/kubeone/controller.go
  pkg/provider/kubernetes/credentials.go
  pkg/provider/kubernetes/external_cluster.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9978 [release/v2.19] adjust resources and probes for konnectivity proxy sidecar (#9911)
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  docs/zz_generated.seed.yaml
  hack/ci/setup-mla.sh
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/install/crdmigration/clones.go
  pkg/resources/konnectivity/sidecar.go
  pkg/resources/resources.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/crd

#9981 Install updated Namespace scoped ApplicationInstallation CRD on seed
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/util/applications.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9971 [release/v2.20] adjust resources and probes for konnectivity proxy sidecar (#9911)
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  docs/zz_generated.seed.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/resources/konnectivity/sidecar.go
  pkg/resources/resources.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/crd

#9983 make konnectivity component settings optional for backwards compatibility
  pkg/apis/kubermatic/v1/cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#9984 [release/v2.19] make konnectivity component settings optional for backwards compatibility
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/cluster.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, sig/crd

#9982 Add endpoints for VMware Cloud Director
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/v2/provider/vmwareclouddirector.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/cloud/vmwareclouddirector/client.go
  pkg/provider/cloud/vmwareclouddirector/provider.go
  pkg/test/e2e/utils/apiclient/client/kubermatic_kubernetes_platform_api_client.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_catalogs_parameters.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_catalogs_responses.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_networks_parameters.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_networks_responses.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_templates_parameters.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_templates_responses.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/vmwareclouddirector_client.go
  pkg/test/e2e/utils/apiclient/models/v_mware_cloud_director_catalog.go
  pkg/test/e2e/utils/apiclient/models/v_mware_cloud_director_catalog_list.go
  pkg/test/e2e/utils/apiclient/models/v_mware_cloud_director_network.go
  pkg/test/e2e/utils/apiclient/models/v_mware_cloud_director_network_list.go
  pkg/test/e2e/utils/apiclient/models/v_mware_cloud_director_template.go
  pkg/test/e2e/utils/apiclient/models/v_mware_cloud_director_template_list.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9935 Update Openstack CCM and CSI to 1.24.0
  addons/csi/openstack/controllerplugin-rbac.yaml
  addons/csi/openstack/controllerplugin.yaml
  addons/csi/openstack/nodeplugin.yaml
  addons/csi/openstack/snapshot-crds.yaml
  pkg/resources/cloudcontroller/openstack.go
  pkg/resources/controllermanager/deployment.go
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-openstack-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-openstack-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-openstack-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-openstack-cloud-controller-manager-externalCloudProvider.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#9749 make cluster name a valid rfc1035 label
  pkg/handler/common/cluster.go
  pkg/test/e2e/ccm-migration/providers/openstack.go
  pkg/test/e2e/ccm-migration/providers/vsphere.go
  pkg/test/e2e/expose-strategy/tunneling_test.go
  pkg/webhook/cluster/validation/validation.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9985 update patch seed endpoint
  cmd/kubermatic-api/swagger.json
  pkg/handler/routes_v1_admin.go
  pkg/handler/v1/admin/seed.go
  pkg/handler/v1/admin/seed_test.go
  pkg/test/e2e/utils/apiclient/client/admin/update_seed_responses.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/api

#10010 fix addon variables not being persisted
  pkg/apis/kubermatic/v1/addon.go
  pkg/crd/k8c.io/kubermatic.k8c.io_addons.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#9993 update cluster mutation webhook
  pkg/webhook/cluster/mutation/mutation.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10026 [release/v2.18] pin AWS AMI to prevent encountering kernel bug (#10021)
  hack/ci/testdata/seed.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10024 [release/v2.20] pin AWS AMI to prevent encountering kernel bug (#10021)
  hack/ci/testdata/seed.yaml
  hack/ci/testdata/seed_backup.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#9930 Remove telemetry uuid validation
  pkg/install/stack/kubermatic-master/validation.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10018 reduce machine-controller log verbosity
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10012 Bump operating system manager to v0.4.3
  go.mod
  go.sum
  pkg/resources/operatingsystemmanager/deployment.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10031 Add ImagePullSecret to Cluster
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/resources/machinecontroller/deployment.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#9974 update kube-state-metrics to 2.5.0
  charts/monitoring/kube-state-metrics/Chart.yaml
  charts/monitoring/kube-state-metrics/values.yaml
  pkg/resources/kubestatemetrics/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-kube-state-metrics.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#10033 web terminal image
  hack/images/web-terminal/Dockerfile
  hack/images/web-terminal/release.sh
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#9668 Move ClusterAddress to ClusterStatus
  cmd/kubermatic-api/main.go
  cmd/seed-controller-manager/main.go
  cmd/seed-controller-manager/migrations.go
  docs/zz_generated.addondata.go.txt
  pkg/addon/template.go
  pkg/addon/testdata/cluster-kubernetes-aws.yaml
  pkg/addon/testdata/cluster-kubernetes-do.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/cluster/client/client.go
  pkg/collectors/cluster.go
  pkg/controller/master-controller-manager/rbac/sync_resource_test.go
  pkg/controller/master-controller-manager/seed-status-controller/reconciler.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller_test.go
  pkg/controller/seed-controller-manager/kubernetes/address.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/resources.go
  pkg/controller/seed-controller-manager/monitoring/resources_test.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/handler/common/cluster.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v1/project/project_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/provider/kubernetes/cluster.go
  pkg/provider/kubernetes/cluster_internal_test.go
  pkg/provider/kubernetes/cluster_test.go
  pkg/provider/kubernetes/util_test.go
  pkg/resources/address/address.go
  pkg/resources/address/address_test.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/apiserver/is-running.go
  pkg/resources/apiserver/tls-serving-certificate.go
  pkg/resources/apiserver/token-users.go
  pkg/resources/certificates/root-ca.go
  pkg/resources/controllermanager/deployment.go
  pkg/resources/data.go
  pkg/resources/konnectivity/secrets.go
  pkg/resources/konnectivity/tls-cert.go
  pkg/resources/kubeconfig.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/prometheus/configmap.go
  pkg/resources/resources.go
  pkg/resources/test/load_files_test.go
  pkg/resources/usercluster/deployment.go
  pkg/validation/cluster.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#9955 retry failed dualstack e2e subtests
  pkg/test/dualstack/cloud_providers_dualstack_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#10048 [release/v2.19] Added autodownsampling so that Grafana finds data on longer range
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/templates/thanos-query-deployment.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#10036 update ingress-nginx to 1.2.1
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#10047 [release/v2.18] Added autodownsampling so that Grafana finds data on longer range
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/templates/thanos-query-deployment.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#10051 [release/v2.20] update ingress-nginx to 1.2.1 (#10036)
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/requirements.lock
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#10052 Update CA Bundle to 2022-04-26
  charts/kubermatic-operator/static/ca-bundle.pem
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/gen-api-client.sh
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/update-swagger.sh
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes

#9972 Gracefully handle new Seeds that have no CRDs yet in our webhook
  cmd/kubermatic-webhook/main.go
  pkg/webhook/seed/validation.go
  pkg/webhook/seed/validation_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#10055 Fixes token index out of range
  pkg/handler/auth/sa.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#10006 Update kubevirtCloudSpec to inject infraStorageClass info
  addons/csi/kubevirt/csi-driver-operator.yaml
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.addondata.go.txt
  pkg/addon/template.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/handler/common/provider/kubevirt.go
  pkg/provider/cloud/kubevirt/provider.go
  pkg/provider/cloud/kubevirt/storage.go
  pkg/test/e2e/utils/apiclient/models/kubevirt_cloud_spec.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#9998 Set etcd PDB allowed disruptions based on componentsOverride
  pkg/resources/etcd/pdb.go
Labels: ok-to-test, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#10019 Generate valid cluster names where a random name is generated
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
  pkg/handler/common/cluster.go
  pkg/provider/cloud/aws/util_test.go
  pkg/provider/kubernetes/cluster.go
  pkg/test/e2e/ccm-migration/providers/azure.go
  pkg/test/e2e/ccm-migration/providers/openstack.go
  pkg/test/e2e/ccm-migration/providers/vsphere.go
  pkg/util/cluster/cluster.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9826 Update to controller-runtime 0.12.1 / Kubernetes 1.24
  .golangci.yml
  cmd/alertmanager-authorization-server/main.go
  cmd/conformance-tester/pkg/clients/client_api.go
  cmd/http-prober/main.go
  cmd/kubeletdnat-controller/main.go
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/swagger.json
  cmd/kubermatic-operator/main.go
  cmd/kubermatic-webhook/main.go
  cmd/master-controller-manager/main.go
  cmd/seed-controller-manager/main.go
  cmd/user-cluster-controller-manager/main.go
  cmd/user-cluster-webhook/main.go
  cmd/user-ssh-keys-agent/main.go
  go.mod
  go.sum
  hack/verify-boilerplate.sh
  pkg/controller/master-controller-manager/rbac/test/fake/informer_factory.go
  pkg/controller/nodeport-proxy/envoymanager/resources.go
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller_test.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/provider/cloud/eks/authenticator/arn.go
  pkg/provider/cloud/eks/authenticator/token.go
  pkg/provider/cloud/eks/provider.go
  pkg/resources/data_test.go
  pkg/resources/reconciling/wrapper_test.go
  pkg/test/e2e/utils/apiclient/models/secret_reference.go
  pkg/test/e2e/utils/kubernetes.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#10029 Add Status to KubermaticConfiguration
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/apis/kubermatic/v1/configuration.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#10081 update oauth2-proxy to v7.3.0
  charts/iap/Chart.yaml
  charts/iap/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#10082 update promtail to 2.5.0
  charts/logging/promtail/Chart.yaml
  charts/logging/promtail/test/default.yaml.out
  charts/logging/promtail/test/kubermatic.example.ce.yaml.out
  charts/logging/promtail/test/kubermatic.example.ee.yaml.out
  charts/logging/promtail/values.yaml
Labels: size/L, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/app-management

#10085 update karma to v0.103, improve default configuration
  charts/monitoring/karma/Chart.yaml
  charts/monitoring/karma/values.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#10089 fix promtail configuration
  charts/logging/promtail/values.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#9954 add e2e test for dualstack clusters on openstack
  hack/ci/run-dualstack-e2e-test.sh
  hack/ci/testdata/seed.yaml
  pkg/test/dualstack/cloud_providers.go
  pkg/test/dualstack/cloud_providers_dualstack_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#10049 Add Azure CSI drivers (Azure Disk & Azure File)
  addons/azure-cloud-node-manager/cloud-node-manager.yaml
  addons/csi/azure-disk/csi-azuredisk-controller.yaml
  addons/csi/azure-disk/csi-azuredisk-driver.yaml
  addons/csi/azure-disk/csi-azuredisk-node.yaml
  addons/csi/azure-disk/rbac-csi-azuredisk-controller.yaml
  addons/csi/azure-disk/rbac-csi-azuredisk-node.yaml
  addons/csi/azure-file/csi-azurefile-controller.yaml
  addons/csi/azure-file/csi-azurefile-driver.yaml
  addons/csi/azure-file/csi-azurefile-node.yaml
  addons/csi/azure-file/rbac-csi-azurefile-controller.yaml
  addons/csi/azure-file/rbac-csi-azurefile-node.yaml
  addons/csi/azure-snapshot-controller/crd-csi-snapshot.yaml
  addons/csi/azure-snapshot-controller/csi-snapshot-controller.yaml
  addons/csi/azure-snapshot-controller/rbac-csi-snapshot-controller.yaml
  addons/default-storage-class/storage-class.yaml
  pkg/handler/common/cluster.go
  pkg/resources/data.go
  pkg/resources/test/fixtures/deployment-azure-1.23.5-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-webhook.yaml
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#10084 update blackbox-exporter to 0.21
  charts/monitoring/blackbox-exporter/Chart.yaml
  charts/monitoring/blackbox-exporter/values.yaml
Labels: release-note-action-required, lgtm, approved, size/XS, dco-signoff: yes, sig/app-management

#10086 Add External Cluster Node Events Endpoint
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/external_cluster/kubeone.go
  pkg/handler/v2/external_cluster/node.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/project/list_external_cluster_machine_deployment_events_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/list_external_cluster_machine_deployment_events_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10080 CSI driver for VMware Cloud Director
  addons/csi/vmware-cloud-director/csi-controller.yaml
  addons/csi/vmware-cloud-director/csi-driver.yaml
  addons/csi/vmware-cloud-director/csi-node.yaml
  addons/csi/vmware-cloud-director/vcloud-basic-auth.yaml
  addons/default-storage-class/storage-class.yaml
  cmd/conformance-tester/pkg/scenarios/vmware_cloud_director.go
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.addondata.go.txt
  pkg/addon/template.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/user-cluster-controller-manager/resources/cloudcontroller/configmap.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/provider/cloud/vmwareclouddirector/provider.go
  pkg/provider/cloud/vmwareclouddirector/reconcile.go
  pkg/provider/kubernetes/preset.go
  pkg/resources/cloudconfig/configmap.go
  pkg/resources/cloudconfig/vmwareclouddirector/csiconfig.go
  pkg/resources/cloudconfig/vmwareclouddirector/csiconfig_test.go
  pkg/resources/resources.go
  pkg/test/e2e/utils/apiclient/models/v_mware_cloud_director_c_s_i_config.go
  pkg/test/e2e/utils/apiclient/models/v_mware_cloud_director_cloud_spec.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#9953 Bump gopkg.in/yaml.v3 to v3.0.1
  cmd/image-loader/operator.go
  cmd/kubermatic-api/options.go
  cmd/kubermatic-webhook/options.go
  cmd/master-controller-manager/main.go
  cmd/seed-controller-manager/options.go
  go.mod
  go.sum
  pkg/controller/seed-controller-manager/mla/alertmanager_controller.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/ratelimit_cortex_controller.go
  pkg/controller/seed-controller-manager/mla/ratelimit_cortex_controller_test.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller.go
  pkg/handler/v2/alertmanager/alertmanager.go
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/handler/v2/rulegroup/request.go
  pkg/install/helm/types.go
  pkg/install/stack/kubermatic-master/validation.go
  pkg/install/util/helm.go
  pkg/resources/apiserver/admission-control.go
  pkg/resources/prometheus/configmap.go
  pkg/test/e2e/mla/mla_test.go
  pkg/test/e2e/utils/dex/helm.go
  pkg/util/yamled/document.go
  pkg/util/yamled/document_test.go
  pkg/util/yamled/helpers.go
  pkg/util/yamled/path.go
  pkg/util/yamled/path_test.go
  pkg/util/yamled/testcases/append-existing-array.yaml
  pkg/util/yamled/testcases/append-new-array.yaml
  pkg/util/yamled/testcases/document.yaml
  pkg/util/yamled/testcases/fill-complex.yaml
  pkg/util/yamled/testcases/fill-into-array.yaml
  pkg/util/yamled/testcases/remove-existing-array-item.yaml
  pkg/util/yamled/testcases/remove-nonexisting-array-item.yaml
  pkg/util/yamled/testcases/set-existing-array-item.yaml
  pkg/util/yamled/testcases/set-existing-root-key.yaml
  pkg/util/yamled/testcases/set-new-array-item.yaml
  pkg/util/yamled/testcases/set-new-far-array-item.yaml
  pkg/util/yamled/testcases/set-new-root-key.yaml
  pkg/util/yamled/testcases/set-new-sub-key.yaml
  pkg/util/yamled/util.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#10067 update openstack external snapshotter to version 5.0
  addons/csi/openstack/snapshot-controller.yaml
  addons/csi/openstack/snapshot-webhook.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management, kind/chore

#10007 Add validation webhook for ClusterTemplates
  cmd/kubermatic-webhook/main.go
  pkg/validation/clustertemplate.go
  pkg/webhook/clustertemplate/validation/validation.go
  pkg/webhook/clustertemplate/validation/validation_test.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes

#10028 IPAM seed-level controller
  cmd/seed-controller-manager/controllers.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/ipam_allocation.go
  pkg/apis/kubermatic/v1/ipam_pool.go
  pkg/apis/kubermatic/v1/register.go
  pkg/controller/seed-controller-manager/ipam/controller.go
  pkg/controller/seed-controller-manager/ipam/controller_test.go
  pkg/controller/seed-controller-manager/ipam/doc.go
  pkg/controller/seed-controller-manager/ipam/helper.go
  pkg/controller/seed-controller-manager/ipam/helper_test.go
  pkg/controller/seed-controller-manager/ipam/prefix_allocation.go
  pkg/controller/seed-controller-manager/ipam/range_allocation.go
  pkg/crd/k8c.io/kubermatic.k8c.io_ipamallocations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipampools.yaml
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10098 Fix IPAM/dual-stack with Azure external CCM
  pkg/resources/cloudcontroller/azure.go
  pkg/resources/test/fixtures/deployment-azure-1.21.0-azure-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-azure-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-azure-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-azure-cloud-controller-manager-externalCloudProvider.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10070 Resource usage controller
  cmd/user-cluster-controller-manager/main.go
  cmd/user-cluster-controller-manager/wrappers_ce.go
  cmd/user-cluster-controller-manager/wrappers_ee.go
  pkg/apis/kubermatic/v1/resource_quota.go
  pkg/ee/resource-usage-controller/controller.go
  pkg/ee/resource-usage-controller/controller_test.go
  pkg/ee/validation/machine/providers.go
  pkg/ee/validation/machine/resourcequota.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#10096 Bump minor Go dependencies
  go.mod
  go.sum
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_addonconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_addons.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_admissionplugins.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_alertmanagers.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_allowedregistries.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplateinstances.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_constraints.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_constrainttemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdbackupconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdrestores.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipamallocations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipampools.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_mlaadminsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_projects.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_resourcequotas.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_rulegroups.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_userprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_users.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_usersshkeys.yaml
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes

#10110 try more than 2 commits when finding a gocache
  .prow/ccm-migrations.yaml
  hack/ci/download-gocache.sh
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#9771 wwhrd.yml: add github.com/yvasiyarov/go-metrics and github.com/bugsnag/osext to the exception list
  .wwhrd.yml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10072 Add OIDC support to the K8S Dashboard integration
  cmd/kubermatic-api/main.go
  pkg/handler/auth/oidc.go
  pkg/handler/routes_v1.go
  pkg/handler/test/fake_auth.go
  pkg/handler/test/hack/hack.go
  pkg/handler/v1/kubernetes-dashboard/dashboard.go
  pkg/handler/v2/kubernetes-dashboard/dashboard.go
  pkg/handler/v2/kubernetes-dashboard/director.go
  pkg/handler/v2/kubernetes-dashboard/handler.go
  pkg/handler/v2/kubernetes-dashboard/login.go
  pkg/handler/v2/kubernetes-dashboard/proxy.go
  pkg/handler/v2/kubernetes-dashboard/request.go
  pkg/handler/v2/kubernetes-dashboard/response.go
  pkg/handler/v2/routes_v2.go
  pkg/resources/kubernetes-dashboard/deployment.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#10114 fix panic in installer
  pkg/install/util/crd.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10117 Fix KubeVirt e2e tests Image Http Server
  cmd/conformance-tester/pkg/scenarios/kubevirt.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10111 Make expose-strategy e2e tests headless
  .prow/features.yaml
  hack/run-expose-strategy-e2e-test-in-kind.sh
  pkg/test/e2e/expose-strategy/cluster.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#10102 add endpoint for OIDC kubeconfig secret for WEB terminal
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/swagger.json
  pkg/handler/auth/oidc.go
  pkg/handler/common/kubeconfig.go
  pkg/handler/test/fake_auth.go
  pkg/handler/test/hack/hack.go
  pkg/handler/v2/kubernetes-dashboard/login.go
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/webterminal/webterminal.go
  pkg/handler/v2/webterminal/webterminal_test.go
  pkg/test/e2e/utils/apiclient/client/operations/create_o_id_c_kubeconfig_secret_parameters.go
  pkg/test/e2e/utils/apiclient/client/operations/create_o_id_c_kubeconfig_secret_responses.go
  pkg/test/e2e/utils/apiclient/client/operations/operations_client.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#10113 Define ClusterRole for Kubermatic API
  cmd/kubermatic-api/main.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/master/resources/kubermatic/api.go
  pkg/controller/operator/master/resources/kubermatic/common.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10118 Update list feature gates endpoint to include OperatingSystemManager
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/provider/kubernetes/featuregates.go
  pkg/test/e2e/utils/apiclient/models/feature_gates.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10119 update default list of supported k8s versions
  .prow/api.yaml
  .prow/ccm-migrations.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  Dockerfile
  docs/zz_generated.kubermaticConfiguration.yaml
  hack/images/web-terminal/Dockerfile
  hack/run-expose-strategy-e2e-test-in-kind.sh
  pkg/controller/operator/defaults/defaults.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10120 use the new web-terminal Docker image
  hack/images/web-terminal/Dockerfile
  hack/images/web-terminal/release.sh
  pkg/resources/test/fixtures/deployment-aws-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-web-terminal.yaml
  pkg/resources/web-terminal/deployment.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10128 changelog for 2.19.6
  CHANGELOG.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10127 Cleanup expose-strategy tests
  hack/run-expose-strategy-e2e-test-in-kind.sh
  pkg/test/e2e/expose-strategy/expose_strategy_suite_test.go
  pkg/test/e2e/expose-strategy/tunneling_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes

#10109 Add E2E tests for IPAM controller
  .prow/features.yaml
  hack/ci/README.md
  hack/ci/run-ipam-e2e-tests.sh
  pkg/test/e2e/ipam/ipam_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10134 Support Containerd registry configs in OSM deployment
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.seed.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/resources/operatingsystemmanager/deployment.go
  pkg/test/e2e/utils/apiclient/models/container_runtime_containerd.go
  pkg/test/e2e/utils/apiclient/models/containerd_registry.go
  pkg/test/e2e/utils/apiclient/models/node_settings.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#10124 Resource quota syncer
  cmd/master-controller-manager/controllers.go
  cmd/master-controller-manager/wrappers_ce.go
  cmd/master-controller-manager/wrappers_ee.go
  codegen/reconcile/main.go
  pkg/api/v1/types.go
  pkg/ee/resource-quota/resource-quota-syncer/syncer.go
  pkg/ee/resource-quota/resource-quota-syncer/syncer_test.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10139 fix ResourceQuota namespace not being properly set in reconcile
  pkg/ee/resource-quota/resource-quota-syncer/syncer.go
  pkg/ee/resource-quota/resource-quota-syncer/syncer_test.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10133 log cluster ID instead of human readable name
  pkg/controller/seed-controller-manager/constraint-controller/controller.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10146 add changelog for 2.20.4
  CHANGELOG.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10145 Reduce triggers for CCM migration prow jobs
  .prow/ccm-migrations.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10151 fix MLA controllers racing reconciliations
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#10149 Anexia: update CloudControllerManager to v1.4.2
  pkg/resources/cloudcontroller/anexia.go
Labels: ok-to-test, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#10129 Move `image-loader` functionality to installer subcommand `mirror-images`
  Dockerfile
  cmd/image-loader/README.md
  cmd/image-loader/operator.go
  cmd/kubermatic-installer/cmd_convert_kubeconfig.go
  cmd/kubermatic-installer/cmd_deploy.go
  cmd/kubermatic-installer/cmd_mirror_images.go
  cmd/kubermatic-installer/cmd_print.go
  cmd/kubermatic-installer/cmd_version.go
  cmd/kubermatic-installer/main_ce.go
  cmd/kubermatic-installer/main_ee.go
  hack/ci/deploy-offline.sh
  hack/ci/github-release.sh
  hack/ci/run-offline-test.sh
  pkg/install/images/addons.go
  pkg/install/images/docker/docker.go
  pkg/install/images/helm.go
  pkg/install/images/images.go
  pkg/install/images/images_test.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#10037 Add dual-stack support for Hetzner
  hack/ci/run-dualstack-e2e-test.sh
  pkg/handler/v1/dc/datacenter.go
  pkg/resources/cloudcontroller/hetzner.go
  pkg/test/dualstack/cloud_providers.go
  pkg/test/dualstack/cloud_providers_dualstack_test.go
  pkg/test/dualstack/dualstack_test.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10108 Add resourcequota validation webhook
  cmd/kubermatic-webhook/main.go
  pkg/ee/validation/resourcequota/resourcequota.go
  pkg/ee/validation/resourcequota/resourcequota_test.go
  pkg/webhook/resourcequota/validation/validation.go
  pkg/webhook/resourcequota/validation/wrappers_ce.go
  pkg/webhook/resourcequota/validation/wrappers_ee.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10159 add resource quota validation webhook
  pkg/controller/operator/common/resources.go
  pkg/controller/operator/master/resources/kubermatic/webhooks.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10132 update Websocket endpoint for the Web terminal
  pkg/cluster/client/client.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/handler/routes_v1_websocket.go
  pkg/handler/test/helper.go
  pkg/handler/v1/project/project_test.go
  pkg/handler/websocket/terminal.go
  pkg/provider/kubernetes/cluster.go
  pkg/provider/kubernetes/cluster_internal_test.go
  pkg/provider/types.go
  pkg/resources/web-terminal/deployment.go
  pkg/test/e2e/api/util.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10163 Use sync-forever mode in Konnectivity agent to support apiserver scaling
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/deployment.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10173 make project controller less noisy
  pkg/controller/seed-controller-manager/project/controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10143 Improve etcd backup filenames
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller_test.go
  pkg/storeuploader/storeuploader.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#10169 fix: Support for disabling kubernetes-dashboard
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/defaulting/cluster.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/install/images/images.go
  pkg/resources/cluster/cluster.go
  pkg/resources/test/fixtures/deployment-aws-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-kubernetes-dashboard.yaml
  pkg/webhook/cluster/mutation/mutation_test.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10172 create cluster namespace first, then update ClusterStatus
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/controller/seed-controller-manager/kubernetes/pending.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10126 Add quota to RBAC controller
  pkg/apis/kubermatic/v1/resource_quota.go
  pkg/controller/master-controller-manager/rbac/mapper.go
  pkg/controller/master-controller-manager/rbac/rbac_controller_aggregator.go
  pkg/controller/master-controller-manager/rbac/sync_resource_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10181 fix %w placeholder in log statement
  pkg/controller/seed-controller-manager/mla/grafana.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#10160 Resource quota calculation controllers
  cmd/master-controller-manager/controllers.go
  cmd/master-controller-manager/wrappers_ce.go
  cmd/master-controller-manager/wrappers_ee.go
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/wrappers_ce.go
  cmd/seed-controller-manager/wrappers_ee.go
  pkg/ee/resource-quota/master-controller/controller.go
  pkg/ee/resource-quota/master-controller/controller_test.go
  pkg/ee/resource-quota/master-controller/doc.go
  pkg/ee/resource-quota/seed-controller/controller.go
  pkg/ee/resource-quota/seed-controller/controller_test.go
  pkg/ee/resource-quota/seed-controller/doc.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#10184 fix nil pointer for resourcequota localusage
  pkg/ee/resource-quota/master-controller/controller.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10186 Fix seed resource quota calculation
  pkg/ee/resource-quota/seed-controller/controller.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10158 Add `GroupProjectBinding` CRD
  pkg/apis/kubermatic/v1/group_project_binding.go
  pkg/apis/kubermatic/v1/register.go
  pkg/apis/kubermatic/v1/user_project_binding.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_groupprojectbindings.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#10182 Introduce pkg/util/wait to provide better timeout feedback
  cmd/conformance-tester/main.go
  cmd/conformance-tester/pkg/runner/runner.go
  cmd/conformance-tester/pkg/runner/waiters.go
  cmd/conformance-tester/pkg/tests/conformance.go
  cmd/conformance-tester/pkg/tests/loadbalancer.go
  cmd/conformance-tester/pkg/tests/metrics.go
  cmd/conformance-tester/pkg/tests/storage.go
  pkg/test/e2e/utils/dex/client.go
  pkg/util/wait/wait.go
  pkg/util/wait/wait_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes

#10150 Remove last remnants of the redundant User.ID field
  hack/ci/run-api-e2e.sh
  hack/ci/run-etcd-launcher-tests.sh
  hack/ci/run-ipam-e2e-tests.sh
  hack/ci/run-mla-e2e-tests.sh
  hack/ci/run-opa-e2e-tests.sh
  hack/ci/testdata/oauth_values.yaml
  hack/local/README.md
  hack/local/run-api-e2e.sh
  hack/local/run-kubermatic-kind.sh
  pkg/handler/middleware/middleware.go
  pkg/handler/routes_v1_websocket.go
  pkg/handler/test/helper.go
  pkg/provider/kubernetes/sa.go
  pkg/provider/kubernetes/sa_test.go
  pkg/provider/kubernetes/user.go
  pkg/provider/kubernetes/util_test.go
  pkg/provider/types.go
  pkg/test/e2e/api/sa_test.go
  pkg/test/e2e/api/user_test.go
  pkg/test/e2e/mla/mla_test.go
  pkg/test/e2e/utils/oidc.go
  pkg/util/hash/user.go
  pkg/validation/user.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10193 update Minio to RELEASE.2022-06-25T15-50-16Z
  charts/minio/Chart.yaml
  charts/minio/test/values.example.ce.yaml.out
  charts/minio/test/values.example.ee.yaml.out
  charts/minio/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#10192 update Velero to 1.9.0
  charts/backup/velero/Chart.yaml
  charts/backup/velero/crd/backups.yaml
  charts/backup/velero/crd/backupstoragelocations.yaml
  charts/backup/velero/crd/deletebackuprequests.yaml
  charts/backup/velero/crd/downloadrequests.yaml
  charts/backup/velero/crd/podvolumebackups.yaml
  charts/backup/velero/crd/podvolumerestores.yaml
  charts/backup/velero/crd/resticrepositories.yaml
  charts/backup/velero/crd/restores.yaml
  charts/backup/velero/crd/schedules.yaml
  charts/backup/velero/crd/serverstatusrequests.yaml
  charts/backup/velero/crd/volumesnapshotlocations.yaml
  charts/backup/velero/values.yaml
  hack/update-velero-crds.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#10197 Remove dependency on cilium/pkg
  go.mod
  go.sum
  pkg/test/e2e/cilium/cilium_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes

#10195 Update Grafana to 9.0.1
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#9986 Add proposal for the Web terminal
  docs/proposals/web-terminal.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10213 fixed RQ webhooks scope and some mutation logic
  pkg/controller/operator/master/resources/kubermatic/webhooks.go
  pkg/ee/mutation/resourcequota/mutation.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10214 fixed swagger gen for resource quotas
  cmd/kubermatic-api/swagger.json
  pkg/ee/resource-quota/handler.go
  pkg/ee/resource-quota/handler_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/kubermatic_kubernetes_platform_api_client.go
  pkg/test/e2e/utils/apiclient/client/resource_quota/create_resource_quota_parameters.go
  pkg/test/e2e/utils/apiclient/client/resource_quota/create_resource_quota_responses.go
  pkg/test/e2e/utils/apiclient/client/resource_quota/delete_resource_quota_parameters.go
  pkg/test/e2e/utils/apiclient/client/resource_quota/delete_resource_quota_responses.go
  pkg/test/e2e/utils/apiclient/client/resource_quota/get_resource_quota_parameters.go
  pkg/test/e2e/utils/apiclient/client/resource_quota/get_resource_quota_responses.go
  pkg/test/e2e/utils/apiclient/client/resource_quota/list_resource_quotas_parameters.go
  pkg/test/e2e/utils/apiclient/client/resource_quota/list_resource_quotas_responses.go
  pkg/test/e2e/utils/apiclient/client/resource_quota/patch_resource_quota_parameters.go
  pkg/test/e2e/utils/apiclient/client/resource_quota/patch_resource_quota_responses.go
  pkg/test/e2e/utils/apiclient/client/resource_quota/resource_quota_client.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10219 Use batch/v1 API instead of batch/v1beta1 for CronJobs
  charts/telemetry/templates/cronjob.yaml
  codegen/reconcile/main.go
  pkg/controller/operator/seed/reconciler_ee_test.go
  pkg/controller/seed-controller-manager/backup/backup_controller.go
  pkg/controller/seed-controller-manager/backup/backup_controller_test.go
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/ee/metering/cronjob.go
  pkg/ee/metering/reconcile.go
  pkg/install/images/images.go
  pkg/resources/etcd/cronjob.go
  pkg/resources/reconciling/wrapper.go
  pkg/resources/reconciling/wrapper_test.go
  pkg/resources/reconciling/zz_generated_reconcile.go
  pkg/resources/test/load_files_test.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#10216 Include OSM and kubernetes-dashboard in health status
  cmd/kubermatic-api/swagger.json
  hack/run-user-cluster-controller-manager.sh
  pkg/api/v1/types.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/seed-controller-manager/kubernetes/health.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/handler/common/cluster.go
  pkg/test/e2e/utils/apiclient/models/cluster_health.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10217 VMware Cloud Director: add endpoint to list storage profiles
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/v2/provider/vmwareclouddirector.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/cloud/vmwareclouddirector/provider.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_storage_profiles_parameters.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_storage_profiles_responses.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/vmwareclouddirector_client.go
  pkg/test/e2e/utils/apiclient/models/v_mware_cloud_director_storage_profile.go
  pkg/test/e2e/utils/apiclient/models/v_mware_cloud_director_storage_profile_list.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api
