Repository kubermatic/kubermatic, pull requests merged in 2022-07, with the labels that each got.

#10191 Add controllers to reconcile `GroupProjectBindings`
  cmd/master-controller-manager/wrappers_ee.go
  cmd/seed-controller-manager/wrappers_ee.go
  codegen/reconcile/main.go
  pkg/api/v1/types.go
  pkg/apis/kubermatic/v1/group_project_binding.go
  pkg/controller/master-controller-manager/rbac/mapper.go
  pkg/controller/master-controller-manager/rbac/sync_project.go
  pkg/controller/master-controller-manager/rbac/sync_project_test.go
  pkg/controller/master-controller-manager/rbac/sync_resource.go
  pkg/controller/master-controller-manager/rbac/sync_resource_test.go
  pkg/controller/util/predicate/predicate.go
  pkg/ee/group-project-binding/controller/controller.go
  pkg/ee/group-project-binding/controller/doc.go
  pkg/ee/group-project-binding/controller/prune.go
  pkg/ee/group-project-binding/controller/reconciler.go
  pkg/ee/group-project-binding/controller/reconciler_test.go
  pkg/ee/group-project-binding/controller/resources.go
  pkg/ee/group-project-binding/doc.go
  pkg/ee/group-project-binding/sync-controller/controller.go
  pkg/ee/group-project-binding/sync-controller/controller_test.go
  pkg/ee/group-project-binding/sync-controller/doc.go
  pkg/ee/group-project-binding/sync-controller/resources.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, ee

#10224 add missing setup for resource quota mutating webhook
  cmd/kubermatic-webhook/main.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10226 fix resource quota mutation path
  pkg/webhook/resourcequota/mutation/mutation.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10230 Fix listing resourcequotas in validation webhook
  pkg/ee/validation/resourcequota/resourcequota.go
  pkg/ee/validation/resourcequota/resourcequota_test.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10228 prevent sending empty patches
  pkg/controller/master-controller-manager/project-synchronizer/controller.go
  pkg/controller/master-controller-manager/user-synchronizer/controller.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management

#10171 Update Kubermatic Community Slack links
  README.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10233 vcd: use lowercase for provider name
  .prow/provider-vmware-cloud-director.yaml
  addons/csi/vmware-cloud-director/csi-controller.yaml
  addons/csi/vmware-cloud-director/csi-driver.yaml
  addons/csi/vmware-cloud-director/csi-node.yaml
  addons/csi/vmware-cloud-director/vcloud-basic-auth.yaml
  addons/default-storage-class/storage-class.yaml
  cmd/conformance-tester/pkg/scenarios/interface.go
  cmd/conformance-tester/pkg/scenarios/vmware_cloud_director.go
  cmd/conformance-tester/pkg/types/options.go
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.seed.yaml
  hack/ci/run-conformance-tests.sh
  hack/ci/testdata/seed.yaml
  pkg/api/v1/types.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/handler/v1/presets/credentials.go
  pkg/handler/v1/presets/credentials_test.go
  pkg/test/e2e/utils/apiclient/models/cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/datacenter_spec.go
  pkg/test/e2e/utils/apiclient/models/node_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/preset_spec.go
  pkg/test/e2e/utils/apiclient/models/public_cloud_spec.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#10232 update status properly in resource quota controllers
  pkg/apis/kubermatic/v1/helper/helper.go
  pkg/ee/resource-quota/master-controller/controller.go
  pkg/ee/resource-quota/seed-controller/controller.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10161 Webhook for IPAMPool validation + cleanup logic for IPAMPool deletion
  .prow/features.yaml
  cmd/kubermatic-webhook/main.go
  pkg/apis/kubermatic/v1/ipam_pool.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/operator/seed/resources/kubermatic/webhooks.go
  pkg/controller/seed-controller-manager/ipam/controller.go
  pkg/controller/seed-controller-manager/ipam/controller_test.go
  pkg/crd/k8c.io/kubermatic.k8c.io_ipampools.yaml
  pkg/test/e2e/ipam/ipam_test.go
  pkg/webhook/ipampool/validation/validation.go
  pkg/webhook/ipampool/validation/validation_test.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10227 fix NotFound detection in user-project-binding controller
  pkg/controller/master-controller-manager/user-project-binding/controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, sig/app-management

#10237 Add pause field in kubeone cluster
  pkg/apis/kubermatic/v1/external_cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10140 Configurable audit logging sink
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/audit_logging.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/resources/apiserver/audit.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/resources.go
  pkg/test/e2e/utils/apiclient/models/audit_logging_settings.go
  pkg/test/e2e/utils/apiclient/models/audit_sidecar_configuration.go
  pkg/test/e2e/utils/apiclient/models/audit_sidecar_settings.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10248 get rid of the term 'customer'
  addons/README.md
  cmd/kubermatic-webhook/options.go
  cmd/seed-controller-manager/options.go
  docs/proposals/cloud-cost-exporter.md
  docs/proposals/container-registry-credentials-per-usercluster.md
  docs/proposals/encryption-at-rest.md
  docs/proposals/etcd-backup.md
  docs/proposals/integrate-upstream-machineset-and-machinedeployment-controllers.md
  docs/proposals/introduce-apps.md
  docs/proposals/kubelb.md
  docs/proposals/kubevirt-node-placement.md
  docs/proposals/kubevirt-production-proposal.md
  docs/proposals/machine-controller.md
  docs/proposals/offline-mode.md
  docs/proposals/openshift-ingress.md
  docs/proposals/user-cluster-mla.md
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/apis/kubermatic/v1/configuration.go
  pkg/controller/operator/seed/resources/nodeportproxy/service.go
  pkg/controller/user-cluster-controller-manager/ipam/README.md
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/handler/common/cluster.go
  pkg/handler/common/kubeconfig.go
  pkg/handler/common/machine.go
  pkg/handler/common/role.go
  pkg/handler/common/upgrade.go
  pkg/handler/routes_v1_websocket.go
  pkg/handler/v1/cluster/role.go
  pkg/handler/v1/common/common.go
  pkg/provider/kubernetes/cluster.go
  pkg/provider/types.go
  pkg/test/e2e/cilium/cilium_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#10250 vcd: vapp should not be required for node spec
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/machine/convert.go
  pkg/resources/machine/common.go
  pkg/test/e2e/utils/apiclient/models/ip_allocation_mode.go
  pkg/test/e2e/utils/apiclient/models/v_mware_cloud_director_node_spec.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10251 fixing rbacs rules for ipampools webhook
  pkg/controller/operator/common/webhook.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10244 Fixing seed client for IPAMPool webhook
  cmd/kubermatic-webhook/main.go
  pkg/webhook/ipampool/validation/validation.go
  pkg/webhook/ipampool/validation/validation_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#10252 [release/v2.20] Override operating system manager deployment image r…
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  cmd/image-loader/main.go
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/apis/kubermatic/v1/configuration.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/resources/data.go
  pkg/resources/operatingsystemmanager/deployment.go
  pkg/resources/operatingsystemmanager/rbac.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/crd

#10254 Fix nil pointer exception when cloud-init-settings secret annotations isn't initialised
  pkg/controller/user-cluster-controller-manager/resources/resources/cloudinitsettings/secret.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10256 [release/v2.20] remove telemetry uuid validation (#9930)
  pkg/install/stack/kubermatic-master/validation.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10198 Update Go dependencies
  cmd/kubermatic-api/swagger.json
  codegen/example-yaml/main.go
  go.mod
  go.sum
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_addonconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_addons.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_admissionplugins.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_alertmanagers.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_allowedregistries.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplateinstances.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_constraints.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_constrainttemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdbackupconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdrestores.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_groupprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipamallocations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipampools.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_mlaadminsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_projects.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_resourcequotas.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_rulegroups.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_userprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_users.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_usersshkeys.yaml
  pkg/handler/v2/gatekeeperconfig/gatekeeperconfig_test.go
  pkg/test/e2e/utils/apiclient/models/constraint_template_status.go
  pkg/util/yaml/print.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10240 Fix fetching credentials in machine validation webhook
  pkg/ee/validation/machine/providers.go
  pkg/ee/validation/machine/resourcequota.go
  pkg/resources/test/fixtures/deployment-aws-1.22.1-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-usercluster-webhook.yaml
  pkg/resources/usercluster-webhook/deployment.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10101 Create network policies to isolate KubeVirt Vms
  pkg/provider/cloud/kubevirt/networkpolicy.go
  pkg/provider/cloud/kubevirt/provider.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10271 Upgrade Canal 3.21 to v3.21.5
  addons/canal/canal_v3.21.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#10268 Add cluster specific API endpoints for VMware Cloud Director
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/handler/v2/provider/vmwareclouddirector.go
  pkg/handler/v2/routes_v2.go
  pkg/machine/convert.go
  pkg/provider/cloud/vmwareclouddirector/client.go
  pkg/provider/cloud/vmwareclouddirector/helper.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_catalogs_no_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_catalogs_no_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_networks_no_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_networks_no_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_storage_profiles_no_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_storage_profiles_no_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_templates_no_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_templates_no_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/list_v_mware_cloud_director_templates_parameters.go
  pkg/test/e2e/utils/apiclient/client/vmwareclouddirector/vmwareclouddirector_client.go
  pkg/test/e2e/utils/apiclient/models/v_mware_cloud_director_cloud_spec.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9977 Application: git source
  cmd/user-cluster-controller-manager/main.go
  go.mod
  go.sum
  hack/run-user-cluster-controller-manager.sh
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/applications/installer.go
  pkg/applications/providers/doc.go
  pkg/applications/providers/source/git.go
  pkg/applications/providers/source/git_test.go
  pkg/applications/providers/types.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/resources/resources.go
  pkg/resources/test/fixtures/deployment-aws-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-usercluster-controller.yaml
  pkg/resources/usercluster/deployment.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#10280 Adding webhook validation to avoid too big IPAM pools for range allocation type
  pkg/webhook/ipampool/validation/validation.go
  pkg/webhook/ipampool/validation/validation_test.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10279 fix panic in cluster validation
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#10281 Add project-id label to groupprojectbindings
  pkg/ee/group-project-binding/controller/reconciler.go
  pkg/kubernetes/helper.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10265 API support for GroupProjectBinding resources
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/options.go
  cmd/kubermatic-api/swagger.json
  cmd/kubermatic-api/wrappers_ce.go
  cmd/kubermatic-api/wrappers_ee.go
  pkg/api/v2/types.go
  pkg/ee/cmd/kubermatic-api/wrappers.go
  pkg/ee/group-project-binding/handler/handler.go
  pkg/ee/group-project-binding/handler/handler_test.go
  pkg/ee/group-project-binding/provider/provider.go
  pkg/handler/routing.go
  pkg/handler/test/hack/hack.go
  pkg/handler/test/helper.go
  pkg/handler/test/wrappers_ce.go
  pkg/handler/test/wrappers_ee.go
  pkg/handler/v1/common/request.go
  pkg/handler/v2/group-project-binding/groupprojectbinding.go
  pkg/handler/v2/group-project-binding/wrappers_ce.go
  pkg/handler/v2/group-project-binding/wrappers_ee.go
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/routing.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/project/get_group_project_binding_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/get_group_project_binding_responses.go
  pkg/test/e2e/utils/apiclient/client/project/list_group_project_binding_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/list_group_project_binding_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/utils/apiclient/models/group_project_binding.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10289 Add support for Canal CNI v3.23
  addons/canal/canal_v3.23.yaml
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/version/cni/version.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, sig/api

#10292 fix OSM RBAC reconciling
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/operating-system-manager/role.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10293 fix issue with RQ synchronizing where status was not synced properly
  pkg/ee/resource-quota/resource-quota-synchronizer/synchronizer.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10288 List gke zones
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/provider/gcp.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/cloud/gke/provider.go
  pkg/test/e2e/utils/apiclient/client/gke/gke_client.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_zones_parameters.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_zones_responses.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10231 Add Providers resource quota
  pkg/ee/validation/machine/providers.go
  pkg/handler/common/provider/alibaba.go
  pkg/handler/common/provider/digitalocean.go
  pkg/handler/common/provider/hetzner.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10229 Adding API endpoints for managing IPAMPools
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/options.go
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/controller/seed-controller-manager/ipam/controller.go
  pkg/controller/seed-controller-manager/ipam/controller_test.go
  pkg/controller/seed-controller-manager/ipam/prefix_allocation.go
  pkg/controller/seed-controller-manager/ipam/range_allocation.go
  pkg/handler/middleware/middleware.go
  pkg/handler/routing.go
  pkg/handler/test/hack/hack.go
  pkg/handler/test/helper.go
  pkg/handler/v2/ipampool/ipampool.go
  pkg/handler/v2/ipampool/ipampool_test.go
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/routing.go
  pkg/provider/kubernetes/ipampool.go
  pkg/provider/kubernetes/ipampool_test.go
  pkg/provider/seed.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/ipampool/create_ip_a_m_pool_parameters.go
  pkg/test/e2e/utils/apiclient/client/ipampool/create_ip_a_m_pool_responses.go
  pkg/test/e2e/utils/apiclient/client/ipampool/delete_ip_a_m_pool_parameters.go
  pkg/test/e2e/utils/apiclient/client/ipampool/delete_ip_a_m_pool_responses.go
  pkg/test/e2e/utils/apiclient/client/ipampool/get_ip_a_m_pool_parameters.go
  pkg/test/e2e/utils/apiclient/client/ipampool/get_ip_a_m_pool_responses.go
  pkg/test/e2e/utils/apiclient/client/ipampool/ipampool_client.go
  pkg/test/e2e/utils/apiclient/client/ipampool/list_ip_a_m_pools_parameters.go
  pkg/test/e2e/utils/apiclient/client/ipampool/list_ip_a_m_pools_responses.go
  pkg/test/e2e/utils/apiclient/client/ipampool/patch_ip_a_m_pool_parameters.go
  pkg/test/e2e/utils/apiclient/client/ipampool/patch_ip_a_m_pool_responses.go
  pkg/test/e2e/utils/apiclient/client/kubermatic_kubernetes_platform_api_client.go
  pkg/test/e2e/utils/apiclient/models/ip_a_m_pool.go
  pkg/test/e2e/utils/apiclient/models/ip_a_m_pool_allocation_type.go
  pkg/test/e2e/utils/apiclient/models/ip_a_m_pool_datacenter_settings.go
  pkg/test/e2e/utils/apiclient/models/subnet_c_id_r.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10296 Fix automatic Canal version upgrade for clusters with k8s 1.23+
  pkg/validation/cluster.go
  pkg/version/cni/version.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes

#10303 API endpoints for GroupProjectBinding resources
  cmd/kubermatic-api/swagger.json
  pkg/ee/group-project-binding/handler/handler.go
  pkg/ee/group-project-binding/handler/handler_test.go
  pkg/handler/test/helper.go
  pkg/handler/v2/group-project-binding/groupprojectbinding.go
  pkg/handler/v2/group-project-binding/wrappers_ce.go
  pkg/handler/v2/group-project-binding/wrappers_ee.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/project/create_group_project_binding_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/create_group_project_binding_responses.go
  pkg/test/e2e/utils/apiclient/client/project/delete_group_project_binding_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/delete_group_project_binding_responses.go
  pkg/test/e2e/utils/apiclient/client/project/patch_group_project_binding_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/patch_group_project_binding_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/utils/apiclient/models/group_project_binding_body.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#10305 Use quay.io registry for Canal images, bump Canal v3.20 version to v3.20.5
  addons/canal/canal_v3.20.yaml
  addons/canal/canal_v3.21.yaml
  addons/canal/canal_v3.22.yaml
  addons/canal/canal_v3.23.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#10308 [release/v2.20] Fix automatic Canal version upgrade for clusters with k8s 1.23+
  pkg/validation/cluster.go
  pkg/version/cni/version.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes

#10313 [release/v2.20] Use quay.io registry for Canal images, bump Canal v3.20 version to v3.20.5
  addons/canal/canal_v3.20.yaml
  addons/canal/canal_v3.21.yaml
  addons/canal/canal_v3.22.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#10314 [release/v2.19] Use quay.io registry for Canal images, bump Canal v3.20 version to v3.20.5
  addons/canal/canal_v3.20.yaml
  addons/canal/canal_v3.21.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#10235 KKP API OIDC group support
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/apis/kubermatic/v1/user.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_users.yaml
  pkg/ee/group-project-binding/provider/provider.go
  pkg/ee/resource-quota/provider.go
  pkg/handler/common/kubeconfig.go
  pkg/handler/middleware/middleware.go
  pkg/handler/v1/project/project.go
  pkg/provider/conversions_test.go
  pkg/provider/kubernetes/alertmanager_test.go
  pkg/provider/kubernetes/cluster.go
  pkg/provider/kubernetes/cluster_template.go
  pkg/provider/kubernetes/cluster_test.go
  pkg/provider/kubernetes/constraint_test.go
  pkg/provider/kubernetes/member.go
  pkg/provider/kubernetes/member_test.go
  pkg/provider/kubernetes/mla_admin_setting_test.go
  pkg/provider/kubernetes/rulegroup_test.go
  pkg/provider/kubernetes/sa_test.go
  pkg/provider/kubernetes/sa_token_test.go
  pkg/provider/kubernetes/user.go
  pkg/provider/kubernetes/util.go
  pkg/provider/kubernetes/util_test.go
  pkg/provider/types.go
  pkg/provider/userinfo.go
  pkg/test/e2e/utils/apiclient/models/user.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10285 Validation webhook for GroupProjectBinding resource
  cmd/kubermatic-webhook/main.go
  pkg/apis/kubermatic/v1/group_project_binding.go
  pkg/controller/operator/common/resources.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/master/resources/kubermatic/webhooks.go
  pkg/crd/k8c.io/kubermatic.k8c.io_groupprojectbindings.yaml
  pkg/ee/validation/groupprojectbinding/groupprojectbinding.go
  pkg/ee/validation/groupprojectbinding/groupprojectbinding_test.go
  pkg/webhook/groupprojectbinding/validation/validation.go
  pkg/webhook/groupprojectbinding/validation/wrappers_ce.go
  pkg/webhook/groupprojectbinding/validation/wrappers_ee.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10311 Resourcequotas to cluster scope
  pkg/apis/kubermatic/v1/resource_quota.go
  pkg/controller/operator/common/webhook.go
  pkg/controller/operator/master/resources/kubermatic/webhooks.go
  pkg/crd/k8c.io/kubermatic.k8c.io_resourcequotas.yaml
  pkg/ee/mutation/resourcequota/mutation_test.go
  pkg/ee/resource-quota/handler_test.go
  pkg/ee/resource-quota/master-controller/controller.go
  pkg/ee/resource-quota/master-controller/controller_test.go
  pkg/ee/resource-quota/provider.go
  pkg/ee/resource-quota/provider_test.go
  pkg/ee/resource-quota/resource-quota-synchronizer/synchronizer.go
  pkg/ee/resource-quota/resource-quota-synchronizer/synchronizer_test.go
  pkg/ee/resource-quota/seed-controller/controller.go
  pkg/ee/resource-quota/seed-controller/controller_test.go
  pkg/ee/validation/resourcequota/resourcequota.go
  pkg/ee/validation/resourcequota/resourcequota_test.go
  pkg/resources/usercluster-webhook/rbac.go
  pkg/webhook/machine/validation/wrappers_ee.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10300 Packet resources calculation for quota
  pkg/ee/validation/machine/providers.go
  pkg/handler/common/provider/packet.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10321 improve naming of user printable columns
  pkg/apis/kubermatic/v1/user.go
  pkg/crd/k8c.io/kubermatic.k8c.io_users.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10322 Update versions of user cluster MLA components
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/promtail/daemonset.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#10326 Dual-stack e2e: test host network IPs for Azure
  pkg/test/dualstack/cloud_providers_dualstack_test.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10328 Support equinixmetal metros
  cmd/kubermatic-api/swagger.json
  codegen/example-yaml/main.go
  docs/zz_generated.seed.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/resources/machine/common.go
  pkg/test/e2e/utils/apiclient/models/datacenter_spec_packet.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10304 Adding datacenter-level "IPv6 enabled" switch for OpenStack
  cmd/kubermatic-api/swagger.json
  codegen/example-yaml/main.go
  docs/zz_generated.seed.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/handler/v1/dc/datacenter.go
  pkg/test/e2e/utils/apiclient/models/datacenter_spec_openstack.go
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
  pkg/webhook/cluster/validation/validation_test.go
  pkg/webhook/clustertemplate/validation/validation_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10333 Fix osm roles and rolebindings
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/operating-system-manager/role.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10196 Update EquinixMetal testing machines and location
  cmd/conformance-tester/pkg/scenarios/packet.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10338 Anexia: fix args for conformance tests
  .prow/provider-anexia.yaml
  hack/run-conformance-tests.sh
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10337 Adding "ip version" information to OpenStack subnets listing endpoints
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/common/provider/openstack.go
  pkg/handler/v1/provider/openstack_test.go
  pkg/test/e2e/utils/apiclient/models/openstack_subnet.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10325 Fix log levels
  pkg/controller/master-controller-manager/application-definition-synchronizer/controller.go
  pkg/controller/master-controller-manager/application-secret-synchronizer/controller.go
  pkg/controller/master-controller-manager/cluster-template-synchronizer/controller.go
  pkg/controller/master-controller-manager/master-constraint-template-controller/controller.go
  pkg/controller/master-controller-manager/preset-synchronizer/controller.go
  pkg/controller/master-controller-manager/project-synchronizer/controller.go
  pkg/controller/master-controller-manager/seed-sync/reconciler.go
  pkg/controller/master-controller-manager/serviceaccount-projectbinding-controller/controller.go
  pkg/controller/master-controller-manager/user-project-binding-synchronizer/controller.go
  pkg/controller/master-controller-manager/user-synchronizer/controller.go
  pkg/controller/master-controller-manager/usersshkey-project-ownership/controller.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/seed-controller-manager/backup/backup_controller.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
  pkg/controller/seed-controller-manager/constraint-controller/controller.go
  pkg/controller/seed-controller-manager/constraint-template-controller/controller.go
  pkg/controller/seed-controller-manager/etcdrestore/etcd_restore_controller.go
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/seed-controller-manager/mla/rulegroup_sync_controller.go
  pkg/controller/seed-controller-manager/preset-controller/controller.go
  pkg/controller/user-cluster-controller-manager/ipam/ipam_controller.go
  pkg/ee/allowed-registry-controller/reconcile.go
  pkg/ee/group-project-binding/sync-controller/controller.go
  pkg/ee/resource-quota/master-controller/controller.go
  pkg/ee/resource-quota/seed-controller/controller.go
  pkg/kubernetes/helper.go
  pkg/webhook/addon/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/mlaadminsetting/mutation/mutation.go
  pkg/webhook/usersshkey/mutation/mutation.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#10266 Make writing e2e tests less repetitive
  .prow/features.yaml
  hack/ci/run-cilium-e2e-test.sh
  hack/ci/run-etcd-launcher-tests.sh
  hack/ci/run-konnectivity-e2e-test.sh
  hack/ci/run-mla-e2e-tests.sh
  hack/ci/run-opa-e2e-tests.sh
  hack/ci/setup-kubermatic-backups-in-kind.sh
  hack/ci/setup-kubermatic-mla-in-kind.sh
  hack/ci/testdata/kubermatic_backup.yaml
  hack/ci/testdata/kubermatic_konnectivity.yaml
  hack/ci/testdata/kubermatic_mla.yaml
  hack/ci/testdata/seed_backup.yaml
  hack/run-expose-strategy-e2e-test-in-kind.sh
  pkg/apis/kubermatic/v1/cluster.go
  pkg/resources/health.go
  pkg/test/e2e/cilium/cilium_test.go
  pkg/test/e2e/etcd-launcher/etcd_test.go
  pkg/test/e2e/expose-strategy/agent.go
  pkg/test/e2e/expose-strategy/cluster.go
  pkg/test/e2e/expose-strategy/tunneling_test.go
  pkg/test/e2e/jig/cluster.go
  pkg/test/e2e/jig/flags.go
  pkg/test/e2e/jig/flags_ce.go
  pkg/test/e2e/jig/flags_ee.go
  pkg/test/e2e/jig/machine.go
  pkg/test/e2e/jig/presets.go
  pkg/test/e2e/jig/project.go
  pkg/test/e2e/konnectivity/konnectivity_test.go
  pkg/test/e2e/mla/mla_test.go
  pkg/test/e2e/opa/opa_test.go
  pkg/test/e2e/utils/client.go
  pkg/test/e2e/utils/kubernetes.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10319 update resourcequota rbacs after switch to cluster scope
  pkg/controller/master-controller-manager/rbac/mapper.go
  pkg/controller/master-controller-manager/rbac/mapper_test.go
  pkg/controller/master-controller-manager/rbac/sync_resource_test.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10339 Refactor conformance/CCM tests to use the KKP datacenters
  .prow/ccm-migrations.yaml
  cmd/conformance-tester/main.go
  cmd/conformance-tester/pkg/scenarios/alibaba.go
  cmd/conformance-tester/pkg/scenarios/anexia.go
  cmd/conformance-tester/pkg/scenarios/aws.go
  cmd/conformance-tester/pkg/scenarios/azure.go
  cmd/conformance-tester/pkg/scenarios/digitalocean.go
  cmd/conformance-tester/pkg/scenarios/gcp.go
  cmd/conformance-tester/pkg/scenarios/hetzner.go
  cmd/conformance-tester/pkg/scenarios/interface.go
  cmd/conformance-tester/pkg/scenarios/kubevirt.go
  cmd/conformance-tester/pkg/scenarios/nutanix.go
  cmd/conformance-tester/pkg/scenarios/openstack.go
  cmd/conformance-tester/pkg/scenarios/packet.go
  cmd/conformance-tester/pkg/scenarios/vmware_cloud_director.go
  cmd/conformance-tester/pkg/scenarios/vsphere.go
  cmd/conformance-tester/pkg/types/secrets.go
  hack/ci/run-conformance-tests.sh
  hack/ci/testdata/seed.yaml
  hack/run-ccm-migration-e2e-test-in-kind.sh
  hack/run-conformance-tests.sh
  pkg/provider/cloud/vsphere/folder_test.go
  pkg/provider/cloud/vsphere/network_test.go
  pkg/test/e2e/api/dc_test.go
  pkg/test/e2e/ccm-migration/ccm_migration_test.go
  pkg/test/e2e/ccm-migration/providers/azure.go
  pkg/test/e2e/ccm-migration/providers/cluster.go
  pkg/test/e2e/ccm-migration/providers/openstack.go
  pkg/test/e2e/ccm-migration/providers/vsphere.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10346 [release/v2.20] update to new vSphere setup
  cmd/conformance-tests/scenarios_vsphere.go
  hack/ci/run-conformance-tests.sh
  hack/ci/testdata/seed.yaml
  hack/ci/testdata/seed_backup.yaml
  hack/run-conformance-tests.sh
  pkg/provider/cloud/vsphere/folder_test.go
  pkg/provider/cloud/vsphere/network_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10349 fix controller names
  pkg/controller/master-controller-manager/user-project-binding-synchronizer/controller.go
  pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller.go
  pkg/controller/seed-controller-manager/constraint-template-controller/controller.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller.go
  pkg/controller/user-cluster-controller-manager/flatcar/flatcar_controller.go
  pkg/controller/user-cluster-controller-manager/ipam/ipam_controller.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#10203 Bump vSphere CPI to 1.23.1 (for k8s 1.23.x) and 1.24.0 (for k8s 1.24.x)
  pkg/resources/cloudcontroller/azure.go
  pkg/resources/cloudcontroller/openstack.go
  pkg/resources/cloudcontroller/util.go
  pkg/resources/cloudcontroller/vsphere.go
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-vsphere-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#10348 Add `--skip-dependencies` flag to kubermatic-installer
  cmd/kubermatic-installer/cmd_deploy.go
  pkg/install/stack/kubermatic-master/certmanager.go
  pkg/install/stack/kubermatic-master/nginxingress.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/stack/kubermatic-seed/stack.go
  pkg/install/stack/types.go
  pkg/install/util/helm.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#10350 [release/v2.19] update to new vSphere setup (#10346)
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  cmd/conformance-tests/scenarios_vsphere.go
  hack/ci/run-conformance-tests.sh
  hack/ci/testdata/seed.yaml
  hack/ci/testdata/seed_backup.yaml
  hack/run-conformance-tests.sh
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/provider/cloud/vsphere/folder_test.go
  pkg/provider/cloud/vsphere/network_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#10344 Enable dual-stack for BYO, Equnix Metal & DigitalOcean cloud providers
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/handler/v1/admin/seed_test.go
  pkg/handler/v1/dc/datacenter_test.go
  pkg/test/e2e/api/dc_test.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10356 fix vmware cloud director storage calculation
  pkg/ee/validation/machine/providers.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10341 Add api endpoint for listing ApplicationDefinitions
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/options.go
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/handler/routing.go
  pkg/handler/test/fake_wrapper.go
  pkg/handler/test/hack/hack.go
  pkg/handler/test/helper.go
  pkg/handler/v2/application_definition/application_definition.go
  pkg/handler/v2/application_definition/application_definition_test.go
  pkg/handler/v2/application_definition/request.go
  pkg/handler/v2/routes_v2.go
  pkg/handler/v2/routing.go
  pkg/provider/kubernetes/application_definition.go
  pkg/provider/kubernetes/application_definition_test.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/applications/applications_client.go
  pkg/test/e2e/utils/apiclient/client/applications/list_application_definitions_parameters.go
  pkg/test/e2e/utils/apiclient/client/applications/list_application_definitions_responses.go
  pkg/test/e2e/utils/apiclient/models/application_constraints.go
  pkg/test/e2e/utils/apiclient/models/application_definition.go
  pkg/test/e2e/utils/apiclient/models/application_definition_spec.go
  pkg/test/e2e/utils/apiclient/models/application_source.go
  pkg/test/e2e/utils/apiclient/models/application_template.go
  pkg/test/e2e/utils/apiclient/models/application_version.go
  pkg/test/e2e/utils/apiclient/models/form_field.go
  pkg/test/e2e/utils/apiclient/models/form_field_type.go
  pkg/test/e2e/utils/apiclient/models/git_auth_method.go
  pkg/test/e2e/utils/apiclient/models/git_credentials.go
  pkg/test/e2e/utils/apiclient/models/git_reference.go
  pkg/test/e2e/utils/apiclient/models/git_source.go
  pkg/test/e2e/utils/apiclient/models/helm_credentials.go
  pkg/test/e2e/utils/apiclient/models/helm_source.go
  pkg/test/e2e/utils/apiclient/models/local_object_reference.go
  pkg/test/e2e/utils/apiclient/models/secret_key_selector.go
  pkg/test/e2e/utils/apiclient/models/template_method.go
  pkg/test/e2e/utils/apiclient/models/version_constraints.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, sig/api

#10324 add providerName to externalclusters, add webhook to default it
  cmd/kubermatic-webhook/main.go
  pkg/apis/kubermatic/v1/external_cluster.go
  pkg/controller/operator/common/resources.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/master/resources/kubermatic/webhooks.go
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  pkg/defaulting/externalcluster.go
  pkg/provider/types.go
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/validation/validation.go
  pkg/webhook/clustertemplate/validation/validation.go
  pkg/webhook/externalcluster/mutation/mutation.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10332 ResourceQuota API improvements
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/apis/kubermatic/v1/resource_quota.go
  pkg/ee/mutation/resourcequota/mutation.go
  pkg/ee/mutation/resourcequota/mutation_test.go
  pkg/ee/resource-quota/handler.go
  pkg/ee/resource-quota/handler_test.go
  pkg/ee/resource-quota/provider.go
  pkg/ee/resource-quota/provider_test.go
  pkg/kubernetes/helper.go
  pkg/test/e2e/utils/apiclient/models/resource_quota.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10360 fix JSONPath in ExternalCluster CRD
  pkg/apis/kubermatic/v1/external_cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10354 update machine-controller CRD columns to match upstream
  pkg/controller/user-cluster-controller-manager/resources/resources/machine-controller/crds.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#10358 Modify project list endpoint to consult GroupProjectBindings
  pkg/handler/test/helper.go
  pkg/handler/v1/project/project.go
  pkg/handler/v1/project/project_test.go
  pkg/provider/kubernetes/member.go
  pkg/provider/types.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10364 Add extra volumes and volume mounts to oauth chart
  charts/oauth/templates/deployment.yaml
  charts/oauth/values.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#10359 Block Cluster object from being deleted before the namespace is gone
  cmd/seed-controller-manager/main.go
  pkg/api/v1/types.go
  pkg/clusterdeletion/constraints.go
  pkg/clusterdeletion/deletion.go
  pkg/clusterdeletion/deletion_test.go
  pkg/clusterdeletion/etcdbackupconfig.go
  pkg/clusterdeletion/lb.go
  pkg/clusterdeletion/namespace.go
  pkg/clusterdeletion/node.go
  pkg/clusterdeletion/secret.go
  pkg/clusterdeletion/volumes.go
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller.go
  pkg/controller/seed-controller-manager/auto-update-controller/controller.go
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/kubernetes/helper.go
  pkg/kubernetes/helpers_test.go
  pkg/provider/cloud/aws/provider.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10329 set env credentials in userclustercontroller
  pkg/resources/data.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/machinecontroller/webhook.go
  pkg/resources/test/fixtures/deployment-aws-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-usercluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-usercluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-usercluster-webhook.yaml
  pkg/resources/usercluster-webhook/deployment.go
  pkg/resources/usercluster/deployment.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10371 Dual-stack e2e: test host network IPs for DigitalOcean, OpenStack
  hack/ci/testdata/kubermatic_dualstack.yaml
  hack/ci/testdata/seed.yaml
  pkg/test/dualstack/cloud_providers_dualstack_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10382 remove NamespaceName from ClusterStatus during deletion
  pkg/clusterdeletion/namespace.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10369 Give api-user permissions on apps.kubermatic
  pkg/controller/operator/master/resources/kubermatic/api.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10383 [dev] add worker-name controller
  cmd/seed-controller-manager/controllers.go
  hack/ci/testdata/kubermatic.yaml
  pkg/controller/seed-controller-manager/cluster-stuck-controller/controller.go
  pkg/controller/seed-controller-manager/cluster-stuck-controller/doc.go
  pkg/features/features.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10377 Group support for external user
  pkg/api/v1/types.go
  pkg/handler/v1/common/common.go
  pkg/handler/v1/project/project.go
  pkg/handler/v1/user/user.go
  pkg/handler/v2/user/user.go
  pkg/handler/websocket/user.go
  pkg/provider/kubernetes/member.go
  pkg/provider/types.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10347 Add Equnix Metal dualstack e2e tests
  hack/ci/run-dualstack-e2e-test.sh
  pkg/test/dualstack/cloud_providers.go
  pkg/test/dualstack/cloud_providers_dualstack_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10385 ipam-controller: Skip clusters in deletion process
  pkg/controller/seed-controller-manager/ipam/controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10392 improve cluster cleanup resource handling
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10389 fix update controller
  pkg/controller/seed-controller-manager/update-controller/controller.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10401 [release/v2.19] bump machine-controller version
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#10395 Update Go dependencies / Update VPA to 0.11
  go.mod
  go.sum
  pkg/version/kubermatic/versions.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes

#10397 Fix operations on GroupProjectBindings
  pkg/handler/middleware/middleware.go
  pkg/provider/kubernetes/member.go
  pkg/provider/types.go
  pkg/provider/userinfo.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#10398 do not log client-side errors in KKP API
  pkg/handler/handler.go
  pkg/handler/routing.go
  pkg/handler/v2/routing.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#10400 Extend Get MachineDeployment upgrades for EKS clusters
  pkg/handler/common/provider/aks.go
  pkg/handler/v2/external_cluster/upgrade.go
  pkg/provider/cloud/aks/provider.go
  pkg/provider/cloud/eks/provider.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10402 update externalcluster response
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/external_cluster/kubeone.go
  pkg/handler/v2/external_cluster/node.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/cloud/aks/provider.go
  pkg/provider/cloud/eks/provider.go
  pkg/provider/cloud/gke/provider.go
  pkg/resources/resources.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_cluster_spec.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_cluster_spec.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_kubernetes_network_config_response.go
  pkg/test/e2e/utils/apiclient/models/external_cluster_m_d_status.go
  pkg/test/e2e/utils/apiclient/models/external_cluster_machine_deployment.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_cluster_spec.go
  pkg/test/e2e/utils/apiclient/models/vpc_config_request.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10387 [release/v2.20] Add `--skip-dependencies` flag to kubermatic-installer
  cmd/kubermatic-installer/cmd_deploy.go
  pkg/install/stack/kubermatic-master/certmanager.go
  pkg/install/stack/kubermatic-master/nginxingress.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/stack/kubermatic-seed/stack.go
  pkg/install/stack/types.go
  pkg/install/util/helm.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#10396 update Prometheus to 2.37
  charts/monitoring/blackbox-exporter/Chart.yaml
  charts/monitoring/blackbox-exporter/values.yaml
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/values.yaml
  hack/update-prometheus-rules.sh
  hack/verify-prometheus-rules.sh
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/prometheus/deployment.go
  pkg/resources/prometheus/statefulset.go
  pkg/resources/test/fixtures/statefulset-aws-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.24.0-prometheus.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#10417 Clarify message of cleanup events
  pkg/clusterdeletion/constraints.go
  pkg/clusterdeletion/etcdbackupconfig.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10410 [release/v2.19] Improve etcd backup filenames (#10143)
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller_test.go
  pkg/storeuploader/storeuploader.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#10421 add changelogs for 2.20.5 and 2.19.7 (2.18.11 has no release-notes)
  CHANGELOG.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#10393 Adding datacenter-level "IPv6 enabled" switch for VSphere
  cmd/kubermatic-api/swagger.json
  codegen/example-yaml/main.go
  docs/zz_generated.seed.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/test/e2e/utils/apiclient/models/datacenter_spec_v_sphere.go
  pkg/validation/cluster_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10403 Fix nil pointer return in resource validation when Openstack app credentials are used
  pkg/ee/validation/machine/providers.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10416 Update to Go 1.18.4
  .prow/api.yaml
  .prow/ccm-migrations.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/gen-api-client.sh
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/update-swagger.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes

#10375 CSI driver for DigitalOcean
  addons/csi/digitalocean/csi-driver.yaml
  addons/csi/digitalocean/snapshot-controller.yaml
  addons/csi/digitalocean/snapshot-crds.yaml
  addons/csi/digitalocean/snapshot-webhook.yaml
  addons/csi/vsphere/snapshot-crds.yaml
  addons/default-storage-class/snapshot-class.yaml
  addons/default-storage-class/storage-class.yaml
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#10419 Create AppInstall Namespace if It Does Not Exist
  pkg/handler/v2/application_installation/application_installation.go
  pkg/handler/v2/application_installation/application_installation_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#10424 Add dual-stack support for vSphere user clusters
  go.mod
  go.sum
  pkg/resources/cloudconfig/configmap.go
  pkg/resources/cloudcontroller/vsphere.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#10412 added rq machine validating webhook configuration to reconciling
  cmd/user-cluster-webhook/main.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/machine/webhook.go
  pkg/resources/resources.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10430 hack/local/run-kubermatic-kind.sh: add missiing osm variable replacement in kubermatic config
  hack/local/run-kubermatic-kind.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10422 Rename External Cluster MDStatus to Phase
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/external_cluster/upgrade.go
  pkg/test/e2e/utils/apiclient/models/external_cluster_m_d_phase.go
  pkg/test/e2e/utils/apiclient/models/external_cluster_machine_deployment.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10380 Set cluster-isolation network policy type explicitly
  pkg/provider/cloud/kubevirt/networkpolicy.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10435 Increase TestDeleteClusterBeforeIsUp timeout to five minutes
  pkg/test/e2e/utils/client.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10423 Openstack: Fix inconsistent casing for floatingIPPool in cloud spec
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/test/e2e/utils/apiclient/models/public_openstack_cloud_spec.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/api

#10436 fix nil pointer in front loadbalancer creator
  pkg/resources/nodeportproxy/nodeportproxy.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#10370 refactor master-constraint-template-synchronizer to use seed-lifecycle-controller
  cmd/master-controller-manager/controllers.go
  pkg/controller/kubeletdnat-controller/controller.go
  pkg/controller/master-controller-manager/application-definition-synchronizer/controller.go
  pkg/controller/master-controller-manager/application-secret-synchronizer/controller.go
  pkg/controller/master-controller-manager/cluster-template-synchronizer/controller.go
  pkg/controller/master-controller-manager/master-constraint-controller/controller.go
  pkg/controller/master-controller-manager/master-constraint-template-controller/controller.go
  pkg/controller/master-controller-manager/master-constraint-template-controller/controller_test.go
  pkg/controller/master-controller-manager/preset-synchronizer/controller.go
  pkg/controller/master-controller-manager/project-label-synchronizer/project_label_synchronizer.go
  pkg/controller/master-controller-manager/project-synchronizer/controller.go
  pkg/controller/master-controller-manager/user-project-binding-synchronizer/controller.go
  pkg/controller/master-controller-manager/user-synchronizer/controller.go
  pkg/controller/master-controller-manager/usersshkey-synchronizer/controller.go
  pkg/kubernetes/helper.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#10431 Introduce role priorities
  pkg/api/v1/types.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10433 Remove human-readable name label from ResourceQuotas
  pkg/apis/kubermatic/v1/resource_quota.go
  pkg/ee/mutation/resourcequota/mutation.go
  pkg/ee/mutation/resourcequota/mutation_test.go
  pkg/ee/resource-quota/handler.go
  pkg/ee/resource-quota/handler_test.go
  pkg/ee/resource-quota/provider_test.go
  pkg/handler/v2/resource_quota/resourequota.go
  pkg/handler/v2/resource_quota/wrappers_ce.go
  pkg/handler/v2/resource_quota/wrappers_ee.go
  pkg/handler/v2/routes_v2.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10445 improve finalizer handling in cloud providers
  pkg/provider/cloud/kubevirt/namespace.go
  pkg/provider/cloud/kubevirt/provider.go
  pkg/provider/cloud/nutanix/provider.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10384 Adding validations for GCP dual-stack network
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/common/provider/gcp.go
  pkg/handler/v1/provider/gcp.go
  pkg/provider/cloud/gcp/provider.go
  pkg/test/e2e/utils/apiclient/models/g_c_p_subnetwork.go
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10434 Add support for Cilium CNI & Hubble v1.12
  addons/Makefile
  addons/cilium/cilium_v1.11.yaml
  addons/cilium/cilium_v1.12.yaml
  addons/hubble/_footer.txt
  addons/hubble/_header.txt
  addons/hubble/hubble_v1.11.yaml
  addons/hubble/hubble_v1.12.yaml
  pkg/version/cni/version.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#10441 update nginx to 1.3.0
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#10442 migrate scripts to yq4
  charts/backup/velero/crd/backups.yaml
  charts/backup/velero/crd/backupstoragelocations.yaml
  charts/backup/velero/crd/deletebackuprequests.yaml
  charts/backup/velero/crd/downloadrequests.yaml
  charts/backup/velero/crd/podvolumebackups.yaml
  charts/backup/velero/crd/podvolumerestores.yaml
  charts/backup/velero/crd/resticrepositories.yaml
  charts/backup/velero/crd/restores.yaml
  charts/backup/velero/crd/schedules.yaml
  charts/backup/velero/crd/serverstatusrequests.yaml
  charts/backup/velero/crd/volumesnapshotlocations.yaml
  charts/monitoring/prometheus/rules/general-blackbox-exporter.yaml
  charts/monitoring/prometheus/rules/general-cadvisor.yaml
  charts/monitoring/prometheus/rules/general-cert-manager.yaml
  charts/monitoring/prometheus/rules/general-helm-exporter.yaml
  charts/monitoring/prometheus/rules/general-kube-apiserver.yaml
  charts/monitoring/prometheus/rules/general-kube-kubelet.yaml
  charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/general-node-exporter.yaml
  charts/monitoring/prometheus/rules/general-prometheus.yaml
  charts/monitoring/prometheus/rules/general-thanos.yaml
  charts/monitoring/prometheus/rules/general-velero.yaml
  charts/monitoring/prometheus/rules/general-vertical-pod-autoscaler.yaml
  charts/monitoring/prometheus/rules/kubermatic-master-kubermatic.yaml
  charts/monitoring/prometheus/rules/kubermatic-seed-kubermatic.yaml
  charts/monitoring/prometheus/rules/managed-kube-controller-manager.yaml
  charts/monitoring/prometheus/rules/managed-kube-scheduler.yaml
  charts/monitoring/prometheus/rules/src/general/cadvisor.yaml
  charts/monitoring/prometheus/rules/usercluster-mla-cortex.yaml
  charts/monitoring/prometheus/rules/usercluster-mla-loki-distributed.yaml
  hack/ci/deploy.sh
  hack/ci/fetch-chart-dependencies.sh
  hack/ci/github-release.sh
  hack/ci/setup-mla.sh
  hack/ci/verify-user-cluster-prometheus-configs.sh
  hack/lib.sh
  hack/run-user-cluster-controller-manager.sh
  hack/test-chart-rendering.sh
  hack/update-cert-manager-crds.sh
  hack/update-prometheus-rules.sh
  hack/update-velero-crds.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#10455 fix deployment
  hack/ci/deploy.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10456 Fix for cluster admission webhook (GCP dual-stack validation)
  pkg/validation/cluster.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10458 update cert-manager to 1.9.0
  charts/cert-manager/Chart.yaml
  charts/cert-manager/crd/cert-manager.crds.yaml
  charts/cert-manager/test/default.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#10460 remove bogus securityContext default config for cert-manager
  charts/cert-manager/values.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#10394 Make logging a bit more consistent
  cmd/kubermatic-api/main.go
  cmd/kubermatic-webhook/main.go
  cmd/master-controller-manager/main.go
  cmd/seed-controller-manager/main.go
  cmd/user-cluster-controller-manager/main.go
  cmd/user-cluster-webhook/main.go
  cmd/user-ssh-keys-agent/main.go
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller.go
  pkg/controller/seed-controller-manager/auto-update-controller/controller.go
  pkg/controller/seed-controller-manager/backup/backup_controller.go
  pkg/controller/seed-controller-manager/cloud/cloud_controller.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
  pkg/controller/seed-controller-manager/constraint-controller/controller.go
  pkg/controller/seed-controller-manager/constraint-template-controller/controller.go
  pkg/controller/seed-controller-manager/encryption-at-rest-controller/controller.go
  pkg/controller/seed-controller-manager/pvwatcher/pvwatcher_controller.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go
  pkg/controller/user-cluster-controller-manager/ccm-csi-migrator/controller.go
  pkg/controller/user-cluster-controller-manager/cluster-role-labeler/controller.go
  pkg/controller/user-cluster-controller-manager/cluster-role-labeler/controller_test.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller.go
  pkg/controller/user-cluster-controller-manager/flatcar/controller.go
  pkg/controller/user-cluster-controller-manager/ipam/controller.go
  pkg/controller/user-cluster-controller-manager/ipam/controller_test.go
  pkg/controller/user-cluster-controller-manager/node-labeler/controller.go
  pkg/controller/user-cluster-controller-manager/node-labeler/controller_test.go
  pkg/controller/user-cluster-controller-manager/node-version-controller/controller.go
  pkg/controller/user-cluster-controller-manager/owner-binding-creator/controller.go
  pkg/controller/user-cluster-controller-manager/role-cloner-controller/controller.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#9992 Return EKS error message instead of full error
  pkg/handler/v2/external_cluster/eks.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#10459 fix a lot of typos
  CHANGELOG.md
  Makefile
  cmd/conformance-tester/pkg/clients/client_api.go
  cmd/conformance-tester/pkg/metrics/metrics.go
  cmd/etcd-launcher/main.go
  cmd/user-cluster-controller-manager/ipam.go
  docs/proposals/cluster-dns.md
  docs/proposals/etcd-backup.md
  docs/proposals/offline-mode.md
  docs/proposals/user-cluster-mla.md
  docs/proposals/user-management.md
  docs/proposals/whitelisted-registries.md
  pkg/addon/testdata/cluster-kubernetes-aws.yaml
  pkg/addon/testdata/cluster-kubernetes-do.yaml
  pkg/api/v1/types_test.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/helper/helper.go
  pkg/applications/helmclient/client.go
  pkg/applications/helmclient/client_test.go
  pkg/applications/providers/source/git_test.go
  pkg/applications/providers/template/helm_test.go
  pkg/controller/seed-controller-manager/cloud/cloud_controller.go
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller.go
  pkg/controller/seed-controller-manager/kubernetes/resources_test.go
  pkg/controller/seed-controller-manager/seedresourcesuptodatecondition/seedresourcesuptodatecondition_controller_test.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_integration_test.go
  pkg/controller/user-cluster-controller-manager/resources/resources/applications/crds.go
  pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/deamonset.go
  pkg/handler/common/machine.go
  pkg/handler/middleware/middleware.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v1/node/node_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/gatekeeperconfig/gatekeeperconfig.go
  pkg/handler/v2/machine/machine_test.go
  pkg/install/stack/kubermatic-master/validation.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/vsphere/provider_test.go
  pkg/provider/kubernetes/application_definition.go
  pkg/resources/certificates/triple/triple.go
  pkg/resources/resources.go
  pkg/test/e2e/jig/cluster.go
  pkg/test/e2e/jig/flags.go
  pkg/test/e2e/opa/opa_test.go
  pkg/validation/applicationdefinition_test.go
  pkg/webhook/application/applicationinstallation/validation/validation_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#10474 kkp-application-secret-synchronizer controller: fix synchronization
  pkg/controller/master-controller-manager/application-secret-synchronizer/controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#10465 application: move template method to spec level
  cmd/kubermatic-api/swagger.json
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/applications/installer.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_integration_test.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_test.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/handler/test/helper.go
  pkg/test/e2e/utils/apiclient/models/application_definition_spec.go
  pkg/test/e2e/utils/apiclient/models/application_template.go
  pkg/validation/applicationdefinition.go
  pkg/validation/applicationdefinition_test.go
  pkg/validation/applicationinstallation.go
  pkg/validation/applicationinstallation_test.go
  pkg/webhook/application/applicationdefinition/validation/validation.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, sig/api

#10472 wait for MC webhook before creating initial MD
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller_test.go
  pkg/log/zap.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10473 allow users to not specify .spec.pause for Clusters
  pkg/apis/kubermatic/v1/cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#10374 Expose ApplicationInstallation status in api
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/handler/test/helper.go
  pkg/handler/v2/application_installation/application_installation.go
  pkg/handler/v2/application_installation/application_installation_test.go
  pkg/test/e2e/utils/apiclient/models/application_installation.go
  pkg/test/e2e/utils/apiclient/models/application_installation_condition.go
  pkg/test/e2e/utils/apiclient/models/application_installation_status.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, sig/api

#10447 Add dual-stack e2e tests for vsphere
  hack/ci/run-dualstack-e2e-test.sh
  hack/ci/testdata/kubermatic_dualstack.yaml
  hack/ci/testdata/seed.yaml
  pkg/test/dualstack/cloud_providers.go
  pkg/test/dualstack/cloud_providers_dualstack_test.go
  pkg/test/dualstack/dualstack_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10476 Move ResourceQuota mutation to controller
  cmd/kubermatic-webhook/main.go
  cmd/master-controller-manager/wrappers_ee.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/master/resources/kubermatic/webhooks.go
  pkg/ee/mutation/resourcequota/mutation.go
  pkg/ee/mutation/resourcequota/mutation_test.go
  pkg/ee/resource-quota/label-owner-controller/controller.go
  pkg/ee/resource-quota/label-owner-controller/controller_test.go
  pkg/ee/resource-quota/resource-quota-synchronizer/synchronizer.go
  pkg/webhook/resourcequota/mutation/mutation.go
  pkg/webhook/resourcequota/mutation/wrappers_ce.go
  pkg/webhook/resourcequota/mutation/wrappers_ee.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10499 Update Canal version to v3.22.4
  addons/canal/canal_v3.22.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#10491 Update canal to version 3.21.6
  addons/canal/canal_v3.21.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#10505 Cloud Credential Controller
  cmd/seed-controller-manager/controllers.go
  pkg/controller/seed-controller-manager/cluster-credentials-controller/controller.go
  pkg/controller/seed-controller-manager/cluster-credentials-controller/doc.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller_test.go
  pkg/handler/common/cluster.go
  pkg/resources/credentials.go
  pkg/resources/resources.go
  pkg/test/e2e/jig/cluster.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10507 Anexia: update CloudControllerManager to v1.4.3
  pkg/resources/cloudcontroller/anexia.go
Labels: ok-to-test, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#10496 gitSource: when cloning from a commit, the branch of the commit must be specified
  cmd/kubermatic-api/swagger.json
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/applications/providers/source/git.go
  pkg/applications/providers/source/git_test.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/test/e2e/utils/apiclient/models/git_reference.go
  pkg/validation/applicationdefinition.go
  pkg/validation/applicationdefinition_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, sig/api

#10500 bump supported Kubernetes versions
  .prow/api.yaml
  .prow/ccm-migrations.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  cmd/conformance-tester/pkg/types/options.go
  docs/zz_generated.kubermaticConfiguration.yaml
  hack/ci/run-conformance-tests.sh
  hack/lib.sh
  hack/run-expose-strategy-e2e-test-in-kind.sh
  pkg/addon/template_test.go
  pkg/controller/operator/defaults/defaults.go
  pkg/controller/seed-controller-manager/backup/backup_controller_test.go
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller_test.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller_test.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/handler/test/fake_provider.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v1/cluster/upgrade_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/cluster/upgrade_test.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/handler/v2/feature_gates/feature_gates_test.go
  pkg/handler/v2/version/version_test.go
  pkg/test/e2e/ccm-migration/ccm_migration_test.go
  pkg/test/e2e/expose-strategy/client.go
  pkg/test/e2e/jig/flags.go
  pkg/test/helper.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10508 Add controller to synchronize custom OSPs to user-cluster namespaces
  cmd/seed-controller-manager/controllers.go
  codegen/reconcile/main.go
  pkg/controller/seed-controller-manager/operating-system-profile-synchronizer/controller.go
  pkg/controller/seed-controller-manager/operating-system-profile-synchronizer/controller_test.go
  pkg/controller/seed-controller-manager/operating-system-profile-synchronizer/doc.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10510 Return Decoded AKS error
  pkg/handler/common/provider/aks.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/provider/cloud/aks/provider.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10498 setup dualstack smoketest with azure+(canal, cilium)
  .prow/features.yaml
  hack/ci/run-dualstack-e2e-test.sh
  pkg/test/dualstack/cloud_providers.go
  pkg/test/dualstack/cloud_providers_dualstack_test.go
  pkg/test/dualstack/dualstack_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10516 bring back support for 1.22.5 to allow for smooth KKP upgrades
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/defaults/defaults.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10518 update cert-manager to 1.9.1
  charts/cert-manager/Chart.yaml
  charts/cert-manager/test/default.yaml.out
  go.mod
  go.sum
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#10426 Add MetalLB addon integrated with multi-cluster IPAM.
  addons/Makefile
  addons/metallb/00_metallb.yaml
  addons/metallb/01_address-pools.yaml
  addons/metallb/_header.txt
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/defaults/defaults.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#10497 Update kubevirt-csi-driver-operator version
  addons/csi/kubevirt/csi-driver-operator.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#10425 Remove finalizers handling from api handler
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/controller/master-controller-manager/external-cluster/cluster_controller_test.go
  pkg/controller/master-controller-manager/kubeone/controller.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/external_cluster/kubeone.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10531 Update canal patch version to v3.23.3
  addons/canal/canal_v3.23.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management

#10315 e2e test for OIDC group support
  cmd/conformance-tester/pkg/clients/client_api.go
  hack/ci/run-api-e2e.sh
  hack/ci/testdata/openldap.yaml
  pkg/test/e2e/api/group_test.go
  pkg/test/e2e/utils/client.go
  pkg/test/e2e/utils/dex/client.go
  pkg/test/e2e/utils/oidc.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10428 sync applicationSecret from kubermatic namespace to clusterNamespace
  cmd/seed-controller-manager/controllers.go
  pkg/controller/master-controller-manager/application-secret-synchronizer/controller.go
  pkg/controller/seed-controller-manager/application-secret-cluster-controller/OWNERS
  pkg/controller/seed-controller-manager/application-secret-cluster-controller/controller.go
  pkg/controller/seed-controller-manager/application-secret-cluster-controller/controller_integration_test.go
  pkg/controller/seed-controller-manager/application-secret-cluster-controller/doc.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#10536 Fix finalizers getting overwritten by cloud & cluster credentials controller
  pkg/controller/seed-controller-manager/cloud/cloud_controller.go
  pkg/controller/seed-controller-manager/cluster-credentials-controller/controller.go
  pkg/kubernetes/helper.go
  pkg/provider/cloud/aws/util_test.go
  pkg/provider/cloud/azure/utils_test.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/openstack/provider_test.go
  pkg/provider/types.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#10511 List GKE versions api endpoint
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/provider/aks.go
  pkg/handler/v2/provider/gcp.go
  pkg/handler/v2/routes_v2.go
  pkg/resources/resources.go
  pkg/test/e2e/utils/apiclient/client/gke/gke_client.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_versions_parameters.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_versions_responses.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10542 fix RELEASES_TO_TEST not being optional enough
  hack/ci/run-conformance-tests.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10543 [release/v2.20] use optimistic locking when finalizers are involved (#10536)
  pkg/controller/seed-controller-manager/cloud/cloud_controller.go
  pkg/provider/cloud/aws/util_test.go
  pkg/provider/cloud/azure/utils_test.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/openstack/provider_test.go
  pkg/provider/types.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management
