Repository kubermatic/kubermatic, pull requests merged in 2022-01, with the labels that each got.

#8559 upgrade etcd to 3.5.1 for Kubernetes 1.22+
  go.mod
  go.sum
  pkg/resources/etcd/statefulset.go
  pkg/resources/test/fixtures/cronjob-aws-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.22.1-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.22.1-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-etcd.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#8561 fix nil aks upgrades
  pkg/handler/common/provider/aks.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8560 fix nodeport proxy e2e test
  .prow.yaml
  pkg/test/e2e/nodeport-proxy/deployer.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#8563 [release/v2.18] Upgrade etcd to 3.5.1 for Kubernetes 1.22+
  pkg/resources/etcd/statefulset.go
  pkg/resources/test/fixtures/cronjob-aws-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.22.1-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.22.1-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-etcd.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#8543 support provisioning for external cluster controller
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/provider/cloud/aks/provider.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#8568 do not take ownership of CA bundle created by our Helm chart
  pkg/controller/operator/common/util.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8567 update etcd launcher e2e test with multiple backups
  hack/ci/testdata/backup_s3_creds.yaml
  hack/ci/testdata/seed_backup.yaml
  pkg/test/e2e/etcd-launcher/etcd_test.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8569 fix nil pointer exception
  pkg/defaulting/cluster.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8552 Improve CRD handling in Installer
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/crd-operatingsystemconfigs.yaml
  charts/kubermatic-operator/crd/crd-operatingsystemprofiles.yaml
  charts/kubermatic-operator/crd/k8c.io/operatingsystemmanager.k8c.io_operatingsystemconfig.yaml
  charts/kubermatic-operator/crd/k8c.io/operatingsystemmanager.k8c.io_operatingsystemprofile.yaml
  hack/ci/setup-kubermatic-in-kind.sh
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/install/crdmigration/setup.go
  pkg/install/stack/kubermatic-master/certmanager.go
  pkg/install/stack/kubermatic-master/nginxingress.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/stack/kubermatic-seed/stack.go
  pkg/install/stack/types.go
  pkg/install/util/crd.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8570 Bump operating-system-manager to v0.3.2
  pkg/resources/operatingsystemmanager/deployment.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#8574 Improve Readme
  README.md
  docs/kkp-logo.png
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#8577 fix typo in readme
  README.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8573 Update CRDs for OSM in kubermatic-operator
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/operatingsystemmanager.k8c.io_operatingsystemconfig.yaml
  charts/kubermatic-operator/crd/k8c.io/operatingsystemmanager.k8c.io_operatingsystemprofile.yaml
  pkg/resources/environment.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#8581 Fix seed deployment
  hack/ci/deploy-dev-asia.sh
  hack/ci/github-release.sh
  hack/ci/push-images.sh
  hack/ci/run-offline-test.sh
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#8571 Another round of CRD sync
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/install/crdmigration/clones.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#8565 Remove unused code
  cmd/seed-controller-manager/controllers.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/seed-controller-manager/rancher/client/client.go
  pkg/controller/seed-controller-manager/rancher/client/cluster.go
  pkg/controller/seed-controller-manager/rancher/client/types.go
  pkg/controller/seed-controller-manager/rancher/client/user.go
  pkg/controller/seed-controller-manager/rancher/controller.go
  pkg/controller/seed-controller-manager/rancher/doc.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/resources/rancherserver/service.go
  pkg/resources/rancherserver/statefulset.go
  pkg/resources/resources.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#8572 fix aks eks cluster statuses
  pkg/api/v2/types.go
  pkg/handler/common/provider/aks.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/provider/cloud/aks/provider.go
  pkg/provider/cloud/eks/provider.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#8614 improve status handling for external cluster
  pkg/handler/v2/external_cluster/external_cluster.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8590 Bump machine-controller to v1.41.0
  .codespell.exclude
  cmd/kubermatic-api/swagger.json
  go.mod
  go.sum
  pkg/controller/user-cluster-controller-manager/ccm-csi-migrator/controller.go
  pkg/machine/convert.go
  pkg/resources/machine/common.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
  pkg/test/e2e/utils/apiclient/models/client_passthrough_devices.go
  pkg/test/e2e/utils/apiclient/models/port.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#8625 Fix external cluster kubeconfig status check
  pkg/handler/v2/external_cluster/external_cluster.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#8629 Add .helmignore to cert-manager Helm chart.
  charts/cert-manager/.helmignore
  charts/cert-manager/Chart.yaml
  charts/cert-manager/requirements.lock
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#8615 fix missing imagePullSecret on k8s dashboard, fix leftover hardcoded registries
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  cmd/master-controller-manager/controllers.go
  cmd/master-controller-manager/main.go
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/apis/kubermatic/v1/configuration.go
  pkg/controller/master-controller-manager/seed-proxy/controller.go
  pkg/controller/master-controller-manager/seed-proxy/reconciler.go
  pkg/controller/master-controller-manager/seed-proxy/resources.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/operator/seed/resources/metering/wrappers_ce.go
  pkg/controller/operator/seed/resources/metering/wrappers_ee.go
  pkg/crd/operator/v1alpha1/configuration.go
  pkg/ee/metering/cronjob.go
  pkg/ee/metering/deployment.go
  pkg/ee/metering/handler.go
  pkg/ee/metering/reconcile.go
  pkg/ee/metering/report_handler.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/kubernetes-dashboard/deployment.go
  pkg/resources/nodeportproxy/nodeportproxy.go
  pkg/resources/test/fixtures/deployment-aws-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kubernetes-dashboard.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/crd

#8613 Add worker-cluster-kubeconfig flag for machine-controller webhooks
  cmd/http-prober/main.go
  pkg/controller/operator/seed/resources/kubermatic/admission.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/machinecontroller/rbac.go
  pkg/resources/machinecontroller/webhook.go
  pkg/resources/operatingsystemmanager/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8630 add requeue for aks cluster
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/handler/v2/external_cluster/external_cluster.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#8671 fix bad metering Docker image
  pkg/ee/metering/reconcile.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8672 Prevent KKP PDBs from blocking node rotations
  pkg/controller/operator/master/resources/kubermatic/api.go
  pkg/controller/operator/master/resources/kubermatic/master-controller-manager.go
  pkg/controller/operator/master/resources/kubermatic/ui.go
  pkg/controller/operator/seed/resources/kubermatic/seed-controller-manager.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8674 Improve GitHub issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/issue_template.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#8673 Remove metering Deployment/CronJob when feature is disabled
  pkg/controller/operator/seed/reconciler.go
  pkg/ee/metering/reconcile.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#8683 Recocile aks irrespective of state
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#8685 fix typo in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8693 Bump machine-controller and operating-system-manager
  go.mod
  go.sum
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/operatingsystemmanager/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8697 Remove schema from Alertmanager CRD (alertmanagers.kubermatic.k8s.io)
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/crd-alertmanagers.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#8699 Revert "bump konnectivity version to v0.0.27"
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/deployment.go
  pkg/resources/konnectivity/sidecar.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#8688 Sync generated OpenAPI v3
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#8711 fix custom external cluster state
  pkg/handler/v2/external_cluster/external_cluster.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#8710 fix MLA logging health status
  pkg/controller/user-cluster-controller-manager/resources/controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#8628 Fix default etcd backups for multiple backup destinations
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/install/crdmigration/clones.go
  pkg/resources/etcd/backupconfig.go
  pkg/resources/test/load_files_test.go
  pkg/test/e2e/utils/apiclient/models/etcd_backup_restore.go
  pkg/webhook/seed/validator.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8670 Check usercluster compatibility prior to KKP upgrades
  cmd/kubermatic-installer/cmd_deploy.go
  pkg/install/stack/common/validation.go
  pkg/install/stack/kubermatic-master/nginxingress.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/stack/kubermatic-master/validation.go
  pkg/install/stack/kubermatic-master/validation_test.go
  pkg/install/stack/kubermatic-seed/stack.go
  pkg/install/stack/kubermatic-seed/validation.go
  pkg/install/stack/types.go
  pkg/install/util/crd.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8722 fix allowed registry parameters
  pkg/ee/allowed-registry-controller/reconcile.go
  pkg/ee/allowed-registry-controller/reconcile_test.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#8725 Update Grafana dashboards
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/dashboards/go/processes.json
  charts/monitoring/grafana/dashboards/kubermatic/machine-controller.json
  charts/monitoring/grafana/dashboards/kubermatic/user-clusters.json
  charts/monitoring/grafana/dashboards/kubernetes/kubelets-overview.json
  charts/monitoring/grafana/dashboards/kubernetes/kubelets.json
  pkg/resources/prometheus/configmap-rules.go
  pkg/resources/test/fixtures/configmap-aws-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.20.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.21.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.20.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.21.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-prometheus.yaml
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#8687 Fix metric names for MinIO Grafana dashboard
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/dashboards/minio/overview.json
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#8726 check if client can retrieve some data for connected cluster
  pkg/handler/v2/external_cluster/external_cluster.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#8730 Fix Konnectivity agent authentication with apiserver network polices
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/apiserver/networkpolicy.go
  pkg/resources/konnectivity/deletion.go
  pkg/resources/resources.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8729 Fix reconciling using recreate strategy
  .github/PULL_REQUEST_TEMPLATE.md
  pkg/resources/reconciling/ensure.go
  pkg/resources/reconciling/ensure_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#8448 Nutanix cloud provider support
  .golangci.yml
  .prow.yaml
  .wwhrd.yml
  cmd/conformance-tests/main.go
  cmd/conformance-tests/runner.go
  cmd/conformance-tests/scenarios_nutanix.go
  cmd/example-yaml-generator/main.go
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.addondata.go.txt
  docs/zz_generated.seed.yaml
  go.mod
  go.sum
  hack/ci/run-conformance-tests.sh
  hack/ci/setup-kubermatic-in-kind.sh
  hack/ci/testdata/seed.yaml
  pkg/api/v1/types.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/datacenter.go
  pkg/crd/kubermatic/v1/preset.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/handler/v1/presets/credentials.go
  pkg/handler/v1/presets/credentials_test.go
  pkg/handler/v1/provider/nutanix.go
  pkg/machine/convert.go
  pkg/provider/cloud/nutanix/client.go
  pkg/provider/cloud/nutanix/provider.go
  pkg/provider/cloud/provider.go
  pkg/provider/kubernetes/credentials.go
  pkg/provider/kubernetes/preset.go
  pkg/provider/types.go
  pkg/resources/credentials.go
  pkg/resources/machine/common.go
  pkg/resources/machine/machinedeployment.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/resources.go
  pkg/test/e2e/utils/apiclient/models/cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/node_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/nutanix_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/nutanix_node_spec.go
  pkg/test/e2e/utils/apiclient/models/public_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/public_nutanix_cloud_spec.go
  pkg/validation/cluster.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8731 Update machine-controller to v1.42.0
  go.mod
  go.sum
  pkg/machine/convert.go
  pkg/resources/machine/common.go
  pkg/resources/machine/common_test.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8733 CRD sync
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/install/crdmigration/clones.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#8721 Update osm version
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/operatingsystemmanager.k8c.io_operatingsystemprofile.yaml
  pkg/resources/operatingsystemmanager/deployment.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#8735 allow to enable debug logging of the usercluster-ctrl-mgr
  pkg/crd/kubermatic/v1/cluster.go
  pkg/resources/usercluster/deployment.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, sig/crd

#8738 Fix reconcile loop for vSphere CSI ValidatingWebhookConfiguration
  cmd/seed-controller-manager/main.go
  cmd/user-cluster-controller-manager/main.go
  pkg/controller/user-cluster-controller-manager/resources/resources/csi-migration/webhook.go
  pkg/resources/reconciling/ensure.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#8740 [release/v2.18] Fix reconcile loop for vSphere CSI ValidatingWebhookConfiguration (#8738)
  cmd/seed-controller-manager/main.go
  cmd/user-cluster-controller-manager/main.go
  pkg/controller/user-cluster-controller-manager/resources/resources/csi-migration/webhook.go
  pkg/resources/reconciling/ensure.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#8714 Improve nginx-ingress helm chart upgrade process.
  pkg/install/stack/kubermatic-master/nginxingress.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#8743 add 2.18.5 changelog
  CHANGELOG.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#8727 Remove Alert KubeAPILatencyHIGH from AlertManager.
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/rules/general-kube-apiserver.yaml
  charts/monitoring/prometheus/rules/src/general/kube-apiserver.yaml
Labels: ok-to-test, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management

#8749 fix use of removed kube-state-metrics metrics
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/dashboards/kubernetes/pods.json
  charts/monitoring/grafana/dashboards/kubernetes/resources-cluster.json
  charts/monitoring/grafana/dashboards/kubernetes/resources-namespace.json
  charts/monitoring/grafana/dashboards/kubernetes/resources-pod.json
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management

#8752 [release/v2.18] fix use of removed kube-state-metrics metrics (#8749)
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/dashboards/kubernetes/pods.json
  charts/monitoring/grafana/dashboards/kubernetes/resources-cluster.json
  charts/monitoring/grafana/dashboards/kubernetes/resources-namespace.json
  charts/monitoring/grafana/dashboards/kubernetes/resources-pod.json
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management

#8750 Autogenerate CRDs reference in docs/master
  hack/ci/update-docs.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#8744 use owner references to cleanup seed-level RBAC instead of manual work
  pkg/api/v1/types.go
  pkg/clusterdeletion/clusterrolebindings.go
  pkg/clusterdeletion/deletion.go
  pkg/controller/seed-controller-manager/kubernetes/pending.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/resources/usercluster/rbac.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#8754 download gocache when running nodeport e2e tests
  hack/run-nodeport-proxy-e2e-test-in-kind.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8755 Update Cluster objects when Azure resources are found after retries
  pkg/provider/cloud/azure/availability_set.go
  pkg/provider/cloud/azure/provider.go
  pkg/provider/cloud/azure/resource_group.go
  pkg/provider/cloud/azure/route_table.go
  pkg/provider/cloud/azure/security_group.go
  pkg/provider/cloud/azure/subnet.go
  pkg/provider/cloud/azure/vnet.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8757 Bump machine controller to 1.42.1
  go.mod
  go.sum
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes

#8760 make error message more readable
  pkg/controller/seed-controller-manager/mla/user_grafana_controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#8765 Improve logo in readme
  README.md
  docs/kkp-logo-dark.png
  docs/kkp-logo.png
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8681 fix vsphere periodic tests failure
  .prow.yaml
  addons/csi/vsphere/vsphere-csi-driver.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#8747 [release/v2.18] add prometheus scraping if minio is running with TLS (#8467)
  charts/minio/Chart.yaml
  charts/minio/values.yaml
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/config/scraping/minio.yaml
  charts/monitoring/prometheus/config/scraping/pods.yaml
  charts/monitoring/prometheus/values.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management

#8769 Fix vsphere csi driver update immutability
  addons/csi/vsphere/vsphere-csi-driver.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#8773 add request validation for metering configuration
  pkg/ee/metering/handler.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8762 Fix Konnectivity/OpenVPN switching with Tunneling expose strategy
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/envoy-agent/configmap.go
  pkg/controller/user-cluster-controller-manager/resources/resources/envoy-agent/daemonset.go
  pkg/resources/resources.go
  pkg/test/e2e/expose-strategy/agent.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#8776 CRD sync
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/install/crdmigration/clones.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd, sig/crd/synced

#8616 update changelog with version v2.19
  CHANGELOG.md
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes

#8774 use ca-bundle in vsphere csi driver
  addons/csi/vsphere/vsphere-csi-driver.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#8787 OpenAPI schema fixes
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  charts/kubermatic-operator/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_addonconfigs.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_addons.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_admissionplugins.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_alertmanagers.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_constraints.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_constrainttemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_etcdbackupconfigs.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_etcdrestores.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_userprojectbindings.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_users.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_usersshkeys.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/datacenter.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#8777 Merge mandatory verify Prow jobs into one job
  .prow.yaml
  hack/ci/verify.sh
  hack/lib.sh
  pkg/resources/prometheus/configmap-rules.go
  pkg/resources/test/fixtures/configmap-aws-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.20.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.21.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.20.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.21.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-prometheus.yaml
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management
