Repository kubermatic/kubermatic, pull requests merged in 2022-02, with the labels that each got.

#8822 Make hack/update-docs.sh work on macOS
  hack/update-docs.sh
Labels: priority/low, size/S, lgtm, approved, release-note-none, dco-signoff: yes

#8831 Add name to rulegroup spec
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/test/helper.go
  pkg/handler/v2/rulegroup/rulegroup.go
  pkg/handler/v2/rulegroup_admin/rulegroup.go
  pkg/test/e2e/utils/apiclient/models/rule_group.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8825 Extend helm script used in CI for automated testing
  hack/test-chart-rendering.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8780 change debug level for external cluster
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#8815 added a resource restore check to etcd backup e2e tests
  pkg/test/e2e/etcd-launcher/etcd_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#8841 temporarily disable vsphere integration tests
  hack/run-integration-tests.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8830 remove unused pkg/leaderelection
  pkg/leaderelection/leaderelection.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes

#8788 apiserver network policy: allow all egress DNS traffic from apiserver
  pkg/resources/apiserver/networkpolicy.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8782 Drop unused test values from cert-manager
  charts/cert-manager/test/default.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#8821 Fix auto upgrade from 1.19 to 1.20
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/apis/kubermatic/v1/configuration.go
  pkg/controller/operator/defaults/defaults.go
  pkg/crd/operator/v1alpha1/configuration.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/crd

#8736 Add API endpoints for Nutanix cloud resources
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/handler/common/provider/nutanix.go
  pkg/handler/v1/provider/nutanix.go
  pkg/handler/v2/provider/nutanix.go
  pkg/handler/v2/provider/nutanix_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/cloud/nutanix/api.go
  pkg/provider/cloud/nutanix/client.go
  pkg/resources/machine/common.go
  pkg/test/e2e/utils/apiclient/client/kubermatic_kubernetes_platform_api_client.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_nutanix_clusters_parameters.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_nutanix_clusters_responses.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_nutanix_projects_parameters.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_nutanix_projects_responses.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_nutanix_subnets_no_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_nutanix_subnets_no_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_nutanix_subnets_parameters.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_nutanix_subnets_responses.go
  pkg/test/e2e/utils/apiclient/client/nutanix/nutanix_client.go
  pkg/test/e2e/utils/apiclient/models/nutanix_cluster.go
  pkg/test/e2e/utils/apiclient/models/nutanix_cluster_list.go
  pkg/test/e2e/utils/apiclient/models/nutanix_project.go
  pkg/test/e2e/utils/apiclient/models/nutanix_project_list.go
  pkg/test/e2e/utils/apiclient/models/nutanix_subnet.go
  pkg/test/e2e/utils/apiclient/models/nutanix_subnet_list.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8850 [release/v2.19] Fix auto upgrade from 1.19 to 1.20 (cherry-pick of #8821)
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/apis/kubermatic/v1/configuration.go
  pkg/controller/operator/defaults/defaults.go
  pkg/crd/operator/v1alpha1/configuration.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/crd

#8858 fix seed-controller not being able to create usercluster ClusterRoleBinding
  pkg/controller/seed-controller-manager/kubernetes/resources.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#8845 save more UIDs during CRD migration
  pkg/install/crdmigration/clones.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#8855 Fix Azure cloud spec defaulting and required fields
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/provider/cloud/azure/provider.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#8829 Ensure CNI
  cmd/image-loader/main.go
  pkg/addon/template.go
  pkg/addon/template_test.go
  pkg/addon/testdata/cluster-kubernetes-aws.yaml
  pkg/addon/testdata/cluster-kubernetes-do.yaml
  pkg/controller/seed-controller-manager/addon/addon_controller_test.go
  pkg/handler/common/cluster.go
  pkg/handler/test/helper.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/install/crdmigration/clones.go
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/networking

#8862 extend verify-codegen to cover CRDs
  hack/verify-codegen.sh
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#8848 Configure docker registry for docker-in-docker and kind
  .prow.yaml
  hack/ci/setup-kind-cluster.sh
  hack/ci/setup-kubermatic-mla-in-kind.sh
  hack/ci/setup-mla.sh
  hack/lib.sh
  hack/local/run-kubermatic-kind.sh
  hack/run-ccm-migration-e2e-test-in-kind.sh
  hack/run-expose-strategy-e2e-test-in-kind.sh
  hack/run-integration-tests.sh
  hack/run-nodeport-proxy-e2e-test-in-kind.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8866 make shutdown command wait for pods to be gone
  pkg/install/crdmigration/shutdown.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#8876 update integration test binaries to 1.23.3
  .prow.yaml
  hack/images/integration-tests/Dockerfile
  hack/images/integration-tests/release.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8880 bring back Age column for Clusters
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/apis/kubermatic/v1/cluster.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, sig/crd

#8751 update kube-state-metrics to 2.3.0
  pkg/resources/kubestatemetrics/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kube-state-metrics.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#8879 fix AWS cloud provider cleanup sometimes getting stuck when cleaning up tags
  pkg/provider/cloud/aws/tags.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8556 use embedded upstream CRDs for gatekeeper CRD installation
  hack/verify-boilerplate.sh
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/crds.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/static/assign-customresourcedefinition.yaml
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/static/assignmetadata-customresourcedefinition.yaml
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/static/config-customresourcedefinition.yaml
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/static/constraintpodstatus-customresourcedefinition.yaml
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/static/constrainttemplate-customresourcedefinition.yaml
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/static/constrainttemplatepodstatus-customresourcedefinition.yaml
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/static/mutatorpodstatus-customresourcedefinition.yaml
  pkg/resources/reconciling/compare.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8867 Expose Nutanix datacenter spec
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/v1/dc/datacenter.go
  pkg/test/e2e/utils/apiclient/models/datacenter_spec.go
  pkg/test/e2e/utils/apiclient/models/datacenter_spec_nutanix.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8872 Consider Hetzner network set by cluster spec
  pkg/resources/cloudcontroller/util.go
  pkg/resources/machine/common.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8894 fix finalizer names
  pkg/api/v1/types.go
  pkg/clusterdeletion/deletion.go
  pkg/controller/master-controller-manager/rbac/sync_project.go
  pkg/controller/master-controller-manager/rbac/sync_project_test.go
  pkg/controller/master-controller-manager/seed-sync/controller.go
  pkg/controller/master-controller-manager/usersshkeyssynchronizer/controller.go
  pkg/controller/seed-controller-manager/backup/backup_controller.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller.go
  pkg/controller/seed-controller-manager/etcdrestore/etcd_restore_controller.go
  pkg/controller/seed-controller-manager/mla/alertmanager_controller.go
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller.go
  pkg/handler/test/helper.go
  pkg/handler/v1/project/project_test.go
  pkg/provider/cloud/aws/provider.go
  pkg/provider/cloud/azure/provider.go
  pkg/provider/cloud/gcp/provider.go
  pkg/provider/cloud/nutanix/provider.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/vsphere/provider.go
  pkg/provider/kubernetes/util_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#8873 Change required fields on Nutanix preset spec
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/apis/kubermatic/v1/preset.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#8843 Do not run ICMP rules addition in Azure if we do not own the NSG
  pkg/provider/cloud/azure/provider.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#8884 Extend endpoint to Create native AKS cluster
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_cluster_spec.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_machine_deployment_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/agent_pool_basics.go
  pkg/test/e2e/utils/apiclient/models/agent_pool_optional_settings.go
  pkg/test/e2e/utils/apiclient/models/agent_pool_upgrade_settings.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#8902 [release/v2.20] Change required fields on Nutanix preset spec (cherry-pick of #8873)
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/apis/kubermatic/v1/preset.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#8900 Update Multus to v3.8.1, enable Multus auto-configuration
  addons/multus/daemonset.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management

#8852 [release/v2.18] apiserver network policy: allow all egress DNS traffic from apiserver
  pkg/resources/apiserver/networkpolicy.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8901 Added endpoints for deleting preset's provider and provider itself.
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/preset/preset.go
  pkg/handler/v2/preset/preset_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/preset.go
  pkg/test/e2e/utils/apiclient/client/preset/delete_preset_parameters.go
  pkg/test/e2e/utils/apiclient/client/preset/delete_preset_provider_parameters.go
  pkg/test/e2e/utils/apiclient/client/preset/delete_preset_provider_responses.go
  pkg/test/e2e/utils/apiclient/client/preset/delete_preset_responses.go
  pkg/test/e2e/utils/apiclient/client/preset/delete_provider_preset_parameters.go
  pkg/test/e2e/utils/apiclient/client/preset/delete_provider_preset_responses.go
  pkg/test/e2e/utils/apiclient/client/preset/preset_client.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8881 update envoymanager for changes in go-control-plane lib api
  go.mod
  go.sum
  pkg/controller/nodeport-proxy/envoymanager/controller.go
  pkg/controller/nodeport-proxy/envoymanager/resources.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#8859 Override resource requirements for nodeport-proxy for user clusters
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  docs/zz_generated.seed.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/resources/nodeportproxy/nodeportproxy.go
  pkg/resources/resources.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/crd

#8908 Add deletionTimestamp support for core objects to API
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/api/v2/types.go
  pkg/handler/v1/common/conversion.go
  pkg/handler/v1/serviceaccount/sa.go
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/etcdrestore/etcdrestore.go
  pkg/test/e2e/utils/apiclient/models/cluster_template.go
  pkg/test/e2e/utils/apiclient/models/etcd_restore.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8910 Dropping presetsFile & dynamicPresets flags from kubermatic-api
  cmd/kubermatic-api/main.go
  cmd/kubermatic-api/options.go
  hack/run-api.sh
  pkg/controller/operator/master/resources/kubermatic/api.go
  pkg/handler/test/helper.go
  pkg/provider/kubernetes/preset.go
  pkg/provider/kubernetes/preset_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#8914 Use correct header 'NutanixProxyURL' for swagger generation
  cmd/kubermatic-api/swagger.json
  pkg/handler/v2/provider/nutanix.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_nutanix_clusters_parameters.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_nutanix_projects_parameters.go
  pkg/test/e2e/utils/apiclient/client/nutanix/list_nutanix_subnets_parameters.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8920 add error handling for the token verifiers
  pkg/handler/auth/error.go
  pkg/handler/auth/oidc.go
  pkg/handler/auth/plugin.go
  pkg/handler/auth/sa.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#8916 Increase metering image version
  pkg/ee/metering/deployment.go
  pkg/ee/metering/reconcile.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8883 Extend endpoint to Create native EKS cluster
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_cluster_spec.go
  pkg/test/e2e/utils/apiclient/models/vpc_config_request.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8924 Set constraint parameters to schemaless
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_constraints.yaml
  pkg/apis/kubermatic/v1/constraint.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#8915 Make Cilium non-exclusive CNI for compatibility with Multus
  addons/cilium/cilium.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#8931 Wait for 'quorum' before checking backup in etcd-launcher restore test
  pkg/test/e2e/etcd-launcher/etcd_test.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8939 [release/v2.20] Constraints schemaless parameters
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_constraints.yaml
  pkg/apis/kubermatic/v1/constraint.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#8851 Update example values and KKPConfig to respect OIDC settings
  charts/kubermatic.example.ce.yaml
  charts/kubermatic.example.ee.yaml
  charts/values.example.ce.yaml
  charts/values.example.ee.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management

#8943 remove accidentally added user.spec.lastSeen field
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_users.yaml
  pkg/apis/kubermatic/v1/user.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, sig/crd

#8936 Add isDefault flag to the RuleGroup API
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_rulegroups.yaml
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/apis/kubermatic/v1/rulegroup.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller_test.go
  pkg/handler/test/helper.go
  pkg/handler/v2/rulegroup/request.go
  pkg/handler/v2/rulegroup/rulegroup.go
  pkg/handler/v2/rulegroup/rulegroup_test.go
  pkg/handler/v2/rulegroup_admin/rulegroup.go
  pkg/handler/v2/rulegroup_admin/rulegroup_test.go
  pkg/provider/kubernetes/rulegroup_test.go
  pkg/test/e2e/utils/apiclient/models/rule_group.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, sig/crd

#8877 Use KKP version for Helm chart versions
  charts/backup/velero/Chart.yaml
  charts/cert-manager/Chart.yaml
  charts/cert-manager/test/default.yaml.out
  charts/iap/Chart.yaml
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/values.yaml
  charts/logging/loki/Chart.yaml
  charts/logging/promtail/Chart.yaml
  charts/logging/promtail/test/default.yaml.out
  charts/logging/promtail/test/kubermatic.example.ce.yaml.out
  charts/logging/promtail/test/kubermatic.example.ee.yaml.out
  charts/minio/Chart.yaml
  charts/monitoring/alertmanager/Chart.yaml
  charts/monitoring/blackbox-exporter/Chart.yaml
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/helm-exporter/Chart.yaml
  charts/monitoring/karma/Chart.yaml
  charts/monitoring/kube-state-metrics/Chart.yaml
  charts/monitoring/node-exporter/Chart.yaml
  charts/monitoring/prometheus/Chart.yaml
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
  charts/oauth/Chart.yaml
  charts/s3-exporter/Chart.yaml
  charts/telemetry/Chart.yaml
  hack/ci/README.md
  hack/ci/deploy.sh
  hack/ci/github-release.sh
  hack/ci/push-images.sh
  hack/ci/run-offline-test.sh
  hack/ci/test-helm-charts.sh
  hack/ci/verify-chart-versions.sh
  hack/ci/verify.sh
  hack/lib.sh
  hack/verify-spelling.sh
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#8839 retrieve of etcd backup secret by name fix
  pkg/handler/v2/backupcredentials/backupcredentials.go
  pkg/provider/kubernetes/backupcredentials.go
  pkg/provider/types.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#8954 fix panic in installer
  pkg/install/helm/cli.go
  pkg/install/helm/cli_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8761 Document Go templating for custom Prometheus rules/scape configs
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  codegen/example-yaml/README.md
  codegen/example-yaml/main.go
  codegen/godoc/main.go
  docs/zz_generated.kubermaticConfiguration.yaml
  docs/zz_generated.prometheusdata.go.txt
  docs/zz_generated.seed.yaml
  hack/ci/update-docs.sh
  hack/update-docs.sh
  pkg/apis/kubermatic/v1/configuration.go
  pkg/resources/prometheus/configmap.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#8959 Use metering image with updated KKP dependencies (v2.20.0-alpha.0)
  pkg/ee/metering/reconcile.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#8746 make k8s dashboard version depend on usercluster version
  pkg/resources/kubernetes-dashboard/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kubernetes-dashboard.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kubernetes-dashboard-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kubernetes-dashboard.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#8745 Update flatcar controller to support removal of resources
  pkg/controller/user-cluster-controller-manager/flatcar/flatcar_controller.go
  pkg/controller/user-cluster-controller-manager/flatcar/resources/delete.go
  pkg/controller/user-cluster-controller-manager/flatcar/resources/update_operator.go
  pkg/controller/util/predicate/predicate.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8957 remove unused testdata
  hack/ci/testdata/crdmigration/master/00-namespaces.yaml
  hack/ci/testdata/crdmigration/master/01-setup.yaml
  hack/ci/testdata/crdmigration/master/02-user.yaml
  hack/ci/testdata/crdmigration/master/03-project.yaml
  hack/ci/testdata/crdmigration/master/04-project-contents.yaml
  hack/ci/testdata/crdmigration/master/07-misc.yaml
  hack/ci/testdata/crdmigration/seed/00-namespaces.yaml
  hack/ci/testdata/crdmigration/seed/01-setup.yaml
  hack/ci/testdata/crdmigration/seed/02-user.yaml
  hack/ci/testdata/crdmigration/seed/03-project.yaml
  hack/ci/testdata/crdmigration/seed/04-project-contents.yaml
  hack/ci/testdata/crdmigration/seed/05-cluster.yaml
  hack/ci/testdata/crdmigration/seed/06-cluster-contents.yaml
  hack/run-crd-migration-in-kind.sh
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8775 Bump kube-state-metrics and VPA to new image location
  charts/kubermatic/Chart.yaml
  charts/kubermatic/templates/vpa-updater-deployment.yaml
  charts/monitoring/kube-state-metrics/values.yaml
  cmd/node-resource-documenter/documenter_test.go
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/common/vpa/updater.go
  pkg/controller/operator/defaults/defaults.go
  pkg/version/kubermatic/versions.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#8896 Add endpoints for EKS resources for cluster creation
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/common/provider/eks.go
  pkg/handler/v2/provider/aws.go
  pkg/handler/v2/provider/eks.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/cloud/aws/api.go
  pkg/test/e2e/utils/apiclient/client/eks/eks_client.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_regions_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_regions_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_security_groups_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_security_groups_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_subnets_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_subnets_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_v_p_c_s_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_v_p_c_s_responses.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_regions.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_security_group_id.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_security_group_id_list.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_subnet_id.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_subnet_id_list.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_v_p_c.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_v_p_c_list.go
  pkg/test/e2e/utils/apiclient/models/regions.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#8934 GET AKS external cluster and machine deployment details
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/node.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_cluster_spec.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_machine_deployment_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_network_profile.go
  pkg/test/e2e/utils/apiclient/models/agent_pool_basics.go
  pkg/test/e2e/utils/apiclient/models/agent_pool_config.go
  pkg/test/e2e/utils/apiclient/models/nodegroup_scaling_config.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#8869 Make MLA/OPA settings in KubermaticSettings optional
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  pkg/apis/kubermatic/v1/settings.go
  pkg/handler/v1/admin/settings_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8975 do not reconcile MLA in clusters with no external name yet
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#8961 Remove some deprecated fields from new CRD types
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.seed.yaml
  hack/ci/testdata/seed.yaml
  hack/ci/testdata/seed_backup.yaml
  pkg/api/v1/types_test.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/handler/v1/provider/vsphere_test.go
  pkg/resources/cloudconfig/configmap.go
  pkg/resources/machine/common.go
  pkg/resources/test/fixtures/configmap-vsphere-1.20.0-cloud-config-csi-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.20.0-cloud-config-csi.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.21.0-cloud-config-csi-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.21.0-cloud-config-csi.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-cloud-config-csi-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-cloud-config-csi.yaml
  pkg/resources/test/load_files_test.go
  pkg/test/e2e/utils/apiclient/models/a_w_s_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/datacenter_spec_v_sphere.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8981 change github.com/docker/distribution to github.com/distribution/distribution/v3
  go.mod
  go.sum
  pkg/controller/operator/defaults/defaults.go
  pkg/docker/docker.go
  pkg/resources/data.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#8929 Only clean up Nutanix project category value if no resources present
  pkg/provider/cloud/nutanix/provider.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#8938 Upgrade loki and promtail to latest versions
  charts/logging/loki/Chart.yaml
  charts/logging/loki/requirements.lock
  charts/logging/loki/test/default.yaml.out
  charts/logging/loki/test/values.example.ce.yaml.out
  charts/logging/loki/test/values.example.ee.yaml.out
  charts/logging/promtail/Chart.yaml
  charts/logging/promtail/charts/promtail-3.11.0.tgz
  charts/logging/promtail/requirements.lock
  charts/logging/promtail/test/default.yaml.out
  charts/logging/promtail/test/kubermatic.example.ce.yaml.out
  charts/logging/promtail/test/kubermatic.example.ee.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#8987 Update RBAC and PodSecurityContext for VPA
  pkg/controller/operator/common/vpa/admissionctrl.go
  pkg/controller/operator/common/vpa/rbac.go
  pkg/controller/operator/common/vpa/recommender.go
  pkg/controller/operator/common/vpa/updater.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#8992 update usercluster Prometheus to 2.33.3, allow more CPU time
  pkg/resources/prometheus/statefulset.go
  pkg/resources/test/fixtures/statefulset-aws-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.20.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.21.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.20.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.20.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.21.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-prometheus.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#8993 Bring back vSphere cluster field and make it required
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.seed.yaml
  hack/ci/testdata/seed.yaml
  hack/ci/testdata/seed_backup.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/handler/v1/provider/vsphere_test.go
  pkg/resources/cloudconfig/configmap.go
  pkg/resources/machine/common.go
  pkg/resources/test/fixtures/configmap-vsphere-1.20.0-cloud-config-csi-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.20.0-cloud-config-csi.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.21.0-cloud-config-csi-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.21.0-cloud-config-csi.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-cloud-config-csi-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-cloud-config-csi.yaml
  pkg/resources/test/load_files_test.go
  pkg/test/e2e/utils/apiclient/models/datacenter_spec_v_sphere.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8990 Update nutanix-client-go to include category query fix
  go.mod
  go.sum
  pkg/provider/cloud/nutanix/api.go
  pkg/provider/cloud/nutanix/client.go
  pkg/provider/cloud/nutanix/provider.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#9009 [release/v2.20] Update nutanix-client-go to include category query fix (cherry-pick of #8990)
  go.mod
  go.sum
  pkg/provider/cloud/nutanix/api.go
  pkg/provider/cloud/nutanix/client.go
  pkg/provider/cloud/nutanix/provider.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#9016 Fix resource overrides and use resource values in naming for nodeport-proxy
  pkg/resources/nodeportproxy/nodeportproxy.go
  pkg/resources/resources.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9000 use minio/v7 consistently and get rid of minio/v6
  cmd/etcd-launcher/main.go
  cmd/s3-exporter/main.go
  cmd/s3-storeuploader/main.go
  go.mod
  go.sum
  pkg/controller/seed-controller-manager/etcdrestore/etcd_restore_controller.go
  pkg/exporters/s3/exporter.go
  pkg/resources/resources.go
  pkg/storeuploader/storeuploader.go
  pkg/storeuploader/storeuploader_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9018 [release/v2.19] Override resource requirements for nodeport-proxy for user clusters
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  docs/zz_generated.seed.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/install/crdmigration/clones.go
  pkg/resources/nodeportproxy/nodeportproxy.go
  pkg/resources/resources.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/crd

#8989 Use Hetzner instead of Digitalocean for e2e tests
  .prow.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.seed.yaml
  hack/ci/run-api-e2e.sh
  hack/ci/run-etcd-launcher-tests.sh
  hack/ci/run-mla-e2e-tests.sh
  hack/ci/run-opa-e2e-tests.sh
  hack/ci/testdata/seed.yaml
  hack/ci/testdata/seed_backup.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/test/e2e/api/cluster_template_test.go
  pkg/test/e2e/api/credentials_test.go
  pkg/test/e2e/api/dc_test.go
  pkg/test/e2e/api/hetzner_test.go
  pkg/test/e2e/etcd-launcher/etcd_test.go
  pkg/test/e2e/mla/mla_test.go
  pkg/test/e2e/opa/opa_test.go
  pkg/test/e2e/utils/apiclient/models/datacenter_spec_hetzner.go
  pkg/test/e2e/utils/client.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#8994 Use retry for adding/removing finalizers
  cmd/kubermatic-installer/cmd_deploy.go
  pkg/clusterdeletion/clusterrolebindings.go
  pkg/clusterdeletion/constraints.go
  pkg/clusterdeletion/deletion.go
  pkg/clusterdeletion/etcdbackupconfig.go
  pkg/clusterdeletion/node.go
  pkg/clusterdeletion/secret.go
  pkg/controller/master-controller-manager/cluster-template-synchronizer/controller.go
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/controller/master-controller-manager/master-constraint-controller/controller.go
  pkg/controller/master-controller-manager/master-constraint-template-controller/controller.go
  pkg/controller/master-controller-manager/project-synchronizer/controller.go
  pkg/controller/master-controller-manager/rbac/sync_project.go
  pkg/controller/master-controller-manager/seed-sync/reconciler.go
  pkg/controller/master-controller-manager/user-project-binding-synchronizer/controller.go
  pkg/controller/master-controller-manager/user-project-binding/user_project_binding_controller.go
  pkg/controller/master-controller-manager/user-synchronizer/controller.go
  pkg/controller/master-controller-manager/usersshkeyssynchronizer/controller.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/controller/seed-controller-manager/backup/backup_controller.go
  pkg/controller/seed-controller-manager/constraint-template-controller/controller.go
  pkg/controller/seed-controller-manager/etcdrestore/etcd_restore_controller.go
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/seed-controller-manager/mla/alertmanager_controller.go
  pkg/controller/seed-controller-manager/mla/dashboard_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/org_user_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/ratelimit_cortex_controller.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller.go
  pkg/controller/seed-controller-manager/mla/rulegroup_sync_controller.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/wrappers_ce.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/wrappers_ee.go
  pkg/controller/user-cluster-controller-manager/role-cloner/role_cloner.go
  pkg/ee/allowed-registry-controller/reconcile.go
  pkg/kubernetes/helper.go
  pkg/resources/kubeconfig.go
  pkg/resources/kubeconfig_test.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#9025 ensure the old webhook volume is removed from the master-ctrl-mgr
  pkg/controller/operator/master/resources/kubermatic/master-controller-manager.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#9026 Fix missing ClusterRole to give webhook access to clustertemplates
  pkg/controller/operator/common/webhook.go
  pkg/controller/operator/master/reconciler.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#9028 [release/v2.18] Override resource requirements for nodeport-proxy for user clusters
  docs/zz_generated.seed.yaml
  pkg/crd/kubermatic/v1/cluster.go
  pkg/crd/kubermatic/v1/zz_generated.deepcopy.go
  pkg/resources/nodeportproxy/nodeportproxy.go
  pkg/resources/resources.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#9015 [release/v2.20] Override resource requirements for nodeport-proxy for user clusters
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  docs/zz_generated.seed.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/kubermatic/v1/cluster.go
  pkg/install/crdmigration/clones.go
  pkg/resources/nodeportproxy/nodeportproxy.go
  pkg/resources/resources.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, sig/crd

#9029 Make container names canonical in loki and promtail
  charts/logging/loki/test/default.yaml.out
  charts/logging/loki/test/values.example.ce.yaml.out
  charts/logging/loki/test/values.example.ee.yaml.out
  charts/logging/loki/values.yaml
  charts/logging/promtail/test/default.yaml.out
  charts/logging/promtail/test/kubermatic.example.ce.yaml.out
  charts/logging/promtail/test/kubermatic.example.ee.yaml.out
  charts/logging/promtail/values.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#9031 [release/v2.19] Make container names canonical in loki and promtail
  charts/logging/loki/Chart.yaml
  charts/logging/loki/test/default.yaml.out
  charts/logging/loki/test/values.example.ce.yaml.out
  charts/logging/loki/test/values.example.ee.yaml.out
  charts/logging/loki/values.yaml
  charts/logging/promtail/Chart.yaml
  charts/logging/promtail/test/default.yaml.out
  charts/logging/promtail/test/kubermatic.example.ce.yaml.out
  charts/logging/promtail/test/kubermatic.example.ee.yaml.out
  charts/logging/promtail/values.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#8976 Create eks nodepool
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/node.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_nodegroup_scaling_config.go
  pkg/test/e2e/utils/apiclient/models/agent_pool_basics.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_machine_deployment_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_nodegroup_scaling_config.go
  pkg/test/e2e/utils/apiclient/models/external_cluster_machine_deployment_cloud_spec.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#9001 Refactor usercluster-controller-manager's RBAC controller
  cmd/conformance-tests/usercluster_controller_tests.go
  cmd/user-cluster-controller-manager/main.go
  pkg/controller/user-cluster-controller-manager/rbac/controller.go
  pkg/controller/user-cluster-controller-manager/rbac/mapper.go
  pkg/controller/user-cluster-controller-manager/rbac/matcher.go
  pkg/controller/user-cluster-controller-manager/rbac/matcher_test.go
  pkg/controller/user-cluster-controller-manager/rbac/reconciler.go
  pkg/controller/user-cluster-controller-manager/rbac/reconciler_test.go
  pkg/controller/user-cluster-controller-manager/rbac/resources.go
  pkg/controller/user-cluster-controller-manager/rbac/resources_test.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#8999 GET EKS external cluster details
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/external_cluster.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#9036 disable konnectivity e2e test
  .prow.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#9038 [release/v2.19] Update helm Chart.yaml apiVersions to v2
  charts/cert-manager/Chart.yaml
  charts/logging/loki/Chart.yaml
  charts/logging/promtail/Chart.yaml
  charts/nginx-ingress-controller/Chart.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#9032 Add changelog for v2.18.6 and v2.19.1
  CHANGELOG.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#9017 bump Minio, fix deprecated env vars
  charts/minio/.helmignore
  charts/minio/Chart.yaml
  charts/minio/templates/deployment.yaml
  charts/minio/test/test.sh
  charts/minio/test/values.example.ce.yaml
  charts/minio/test/values.example.ce.yaml.out
  charts/minio/test/values.example.ee.yaml
  charts/minio/test/values.example.ee.yaml.out
  charts/minio/values.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#8956 Do not use dot imports for blackbox testing
  pkg/api/v1/time_test.go
  pkg/api/v1/types_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#9034 Update list feature gates endpoint to include OIDCKubeCfgEndpoint
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/provider/kubernetes/featuregates.go
  pkg/test/e2e/utils/apiclient/models/feature_gates.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/api

#9045 Fix applying incomplete resource requirements
  pkg/resources/resources.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#9051 add credential validation for Hetzner and Equinixmetal
  pkg/provider/cloud/hetzner/provider.go
  pkg/provider/cloud/packet/provider.go
  pkg/provider/kubernetes/credentials.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9060 Restore correct labels on nodeport-proxy-envoy Deployment
  pkg/resources/nodeportproxy/nodeportproxy.go
Labels: release-note-action-required, lgtm, approved, size/XS, dco-signoff: yes, sig/cluster-management

#9056 Implement Provider Reconciling for KubeVirt
  pkg/provider/cloud/kubevirt/provider.go
  pkg/provider/cloud/kubevirt/reconciler.go
  pkg/provider/cloud/kubevirt/storage.go
  pkg/provider/kubernetes/credentials.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9042 Deploy volume snapshot crd's for openstack
  addons/csi/openstack/snapshot-crds.yaml
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#9084 re-enable vsphere integration tests
  cmd/conformance-tests/main.go
  cmd/conformance-tests/scenarios_vsphere.go
  hack/ci/run-conformance-tests.sh
  hack/ci/testdata/seed.yaml
  hack/ci/testdata/seed_backup.yaml
  hack/run-conformance-tests.sh
  hack/run-integration-tests.sh
  pkg/provider/cloud/vsphere/folder_test.go
  pkg/provider/cloud/vsphere/network_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#9098 Fix bugs in cluster-template-controller introduced in k8c.io migration
  pkg/api/v1/types.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9092 Update CHANGELOG.md with v2.19.2 and v2.18.7
  CHANGELOG.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#9054 Fix missing features and bugs for nutanix csi
  addons/csi/nutanix/snapshot-controller.yaml
  addons/default-storage-class/storage-class.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  cmd/conformance-tests/runner.go
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.addondata.go.txt
  pkg/addon/template.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/user-cluster-controller-manager/resources/resources/csi/secret.go
  pkg/resources/cloudconfig/configmap.go
  pkg/resources/resources.go
  pkg/test/e2e/utils/apiclient/models/nutanix_c_s_i_config.go
Labels: size/L, priority/critical-urgent, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, sig/crd

#8925 Add endpoints for AKS resources
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/common/provider/aks.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/external_cluster/upgrade.go
  pkg/handler/v2/provider/aks.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/aks/aks_client.go
  pkg/test/e2e/utils/apiclient/client/aks/list_a_k_s_node_pool_modes_parameters.go
  pkg/test/e2e/utils/apiclient/client/aks/list_a_k_s_node_pool_modes_responses.go
  pkg/test/e2e/utils/apiclient/client/aks/list_a_k_s_node_versions_no_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/aks/list_a_k_s_node_versions_no_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/aks/list_a_k_s_vm_sizes_no_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/aks/list_a_k_s_vm_sizes_no_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/aks/list_a_k_s_vm_sizes_parameters.go
  pkg/test/e2e/utils/apiclient/client/aks/list_a_k_s_vm_sizes_responses.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_node_pool_modes.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_vm_size.go
  pkg/test/e2e/utils/apiclient/models/a_k_s_vm_size_list.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#9103 Add support for dual-stack pods & services CIDR
  addons/cilium/cilium.yaml
  addons/kube-proxy/configmap.yaml
  pkg/addon/template.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/controllermanager/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.20.0-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-controller-manager.yaml
  pkg/resources/test/load_files_test.go
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#9106 [release/v2.18] re-enable vsphere integration tests (#9084)
  cmd/conformance-tests/main.go
  cmd/conformance-tests/scenarios_vsphere.go
  hack/ci/run-conformance-tests.sh
  hack/ci/testdata/seed.yaml
  hack/run-conformance-tests.sh
  pkg/provider/cloud/vsphere/folder_test.go
  pkg/provider/cloud/vsphere/network_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#8864 import and export cluster templates
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/project/export_cluster_template_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/export_cluster_template_responses.go
  pkg/test/e2e/utils/apiclient/client/project/import_cluster_template_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/import_cluster_template_responses.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/utils/apiclient/models/cluster_template.go
  pkg/test/e2e/utils/apiclient/models/cluster_template_info.go
  pkg/test/e2e/utils/apiclient/models/cluster_template_node_deployment.go
  pkg/test/e2e/utils/client.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#9105 [release/v2.18] Fix LB expose strategy for LBs with external DNS names instead of IPs (#7933)
  pkg/controller/seed-controller-manager/kubernetes/pending.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/resources/address/address.go
  pkg/resources/address/address_test.go
  pkg/resources/nodeportproxy/nodeportproxy.go
  pkg/resources/test/fixtures/service-aws-1.19.0-front-loadbalancer.yaml
  pkg/resources/test/fixtures/service-aws-1.20.0-front-loadbalancer.yaml
  pkg/resources/test/fixtures/service-aws-1.21.0-front-loadbalancer.yaml
  pkg/resources/test/fixtures/service-aws-1.22.1-front-loadbalancer.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9099 machinecontroller env namespace
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9110 :tada: :partying_face: Remove legacy kubermatic Helm chart :partying_face: :tada:
  charts/kubermatic/Chart.yaml
  charts/kubermatic/OWNERS
  charts/kubermatic/migrate/migrate-kubermatic-chart.sh
  charts/kubermatic/static/ca-bundle.pem
  charts/kubermatic/static/cleanup-container.yaml
  charts/kubermatic/static/delete-container.yaml
  charts/kubermatic/static/master/accessible-addons.yaml
  charts/kubermatic/static/master/kubernetes-addons.yaml
  charts/kubermatic/static/master/provider-incompatibilities.yaml
  charts/kubermatic/static/master/ui-config.json
  charts/kubermatic/static/master/updates.yaml
  charts/kubermatic/static/master/versions.yaml
  charts/kubermatic/static/store-container-new.yaml
  charts/kubermatic/static/store-container.yaml
  charts/kubermatic/templates/backup-container-configmap.yaml
  charts/kubermatic/templates/backup-s3-settings-configmap.yaml
  charts/kubermatic/templates/ca-bundle.yaml
  charts/kubermatic/templates/cluster-role-binding.yaml
  charts/kubermatic/templates/clusterns-prometheus-rules-configmap.yaml
  charts/kubermatic/templates/clusterns-prometheus-scraping-configs-configmap.yaml
  charts/kubermatic/templates/credentials-yaml-secret.yaml
  charts/kubermatic/templates/datacenter-yaml-secret.yaml
  charts/kubermatic/templates/dex-ca-secret.yaml
  charts/kubermatic/templates/dockercfg-secret.yaml
  charts/kubermatic/templates/hook-migration-crd-check.yaml
  charts/kubermatic/templates/ingress.yaml
  charts/kubermatic/templates/kubeconfig-secret.yaml
  charts/kubermatic/templates/kubermatic-api-dep.yaml
  charts/kubermatic/templates/kubermatic-api-service.yaml
  charts/kubermatic/templates/kubermatic-controller-manager-dep.yaml
  charts/kubermatic/templates/kubermatic-controller-manager-service.yaml
  charts/kubermatic/templates/kubermatic-ui-dep.yaml
  charts/kubermatic/templates/kubermatic-ui-service.yaml
  charts/kubermatic/templates/master-controller-manager-dep.yaml
  charts/kubermatic/templates/master-files-secret.yaml
  charts/kubermatic/templates/seed-validating-webhook.yaml
  charts/kubermatic/templates/serviceaccount.yaml
  charts/kubermatic/templates/ui-config-configmap.yaml
  charts/kubermatic/templates/vpa-admission-controller-deployment.yaml
  charts/kubermatic/templates/vpa-rbac.yaml
  charts/kubermatic/templates/vpa-recommender-deployment.yaml
  charts/kubermatic/templates/vpa-tls.yaml
  charts/kubermatic/templates/vpa-updater-deployment.yaml
  charts/kubermatic/values.yaml
  cmd/s3-exporter/README.md
  codegen/kubermatic_operator/main.go
  docs/adding-kubernetes-versions.md
  hack/README.md
  hack/ci/verify.sh
  hack/update-kubermatic-chart.sh
  hack/verify-kubermatic-chart.sh
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9122 ensure new Cluster objects from templates appear in the cache before proceeding
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#9114 Remove experimental notice for Nutanix
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/test/e2e/utils/apiclient/models/datacenter_spec_nutanix.go
  pkg/test/e2e/utils/apiclient/models/nutanix_cloud_spec.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#9131 Fix CRD migration oversights
  cmd/kubermatic-installer/cmd_shutdown.go
  pkg/install/crdmigration/clones.go
  pkg/install/crdmigration/preflight.go
  pkg/install/crdmigration/shutdown.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9137 fix GetCLusterConfig typo
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/provider/cloud/aks/provider.go
  pkg/provider/cloud/gke/provider.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, sig/api

#9128 update kubevirt cloud controller manager version
  pkg/resources/cloudcontroller/kubevirt.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#9134 Use klog in fewer places
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v2/cluster/cluster.go
  pkg/kubernetes/helper.go
  pkg/provider/cloud/openstack/provider.go
  pkg/resources/data.go
  pkg/resources/kubeconfig.go
  pkg/resources/kubeconfig_test.go
  pkg/resources/reconciling/ensure.go
  pkg/resources/resources.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9061 Use cluster name as cluster-id in cloud-config for vSphere
  pkg/resources/cloudconfig/configmap.go
  pkg/resources/test/fixtures/configmap-vsphere-1.20.0-cloud-config-csi-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.20.0-cloud-config-csi.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.21.0-cloud-config-csi-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.21.0-cloud-config-csi.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-cloud-config-csi-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-cloud-config-csi.yaml
  pkg/util/kubectl/kubectl.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9138 make operator actually respect the worker-name label
  hack/ci/testdata/seed.yaml
  hack/ci/testdata/seed_backup.yaml
  hack/run-ccm-migration-e2e-test-in-kind.sh
  hack/run-expose-strategy-e2e-test-in-kind.sh
  pkg/controller/operator/master/controller.go
  pkg/controller/operator/seed/controller.go
  pkg/controller/operator/seed/reconciler.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#9002 Add endpoint for EKS resources
  cmd/kubermatic-api/swagger.json
  go.mod
  go.sum
  pkg/api/v2/types.go
  pkg/handler/common/provider/eks.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/provider/eks.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/cloud/aws/api.go
  pkg/test/e2e/utils/apiclient/client/eks/eks_client.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_a_m_i_types_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_a_m_i_types_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_capacity_types_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_capacity_types_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_instance_types_no_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_instance_types_no_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_regions_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_security_groups_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_subnets_no_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_subnets_no_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_subnets_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_v_p_c_s_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_v_p_cs_no_credentials_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_v_p_cs_no_credentials_responses.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_a_m_i_types.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_capacity_types.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_cluster_list.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_instance_types.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_regions.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9135 use dynamic client for kubevirt resources, remove typed client
  pkg/handler/common/provider/kubevirt.go
  pkg/handler/v2/provider/kubevirt_test.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/clientset.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/doc.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/fake/clientset_generated.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/fake/doc.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/fake/register.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/scheme/doc.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/scheme/register.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/core_client.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/doc.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/fake/doc.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/fake/fake_core_client.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/fake/fake_kubevirt.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/fake/fake_virtualmachine.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/fake/fake_virtualmachineinstance.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/fake/fake_virtualmachineinstancemigration.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/fake/fake_virtualmachineinstancepreset.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/fake/fake_virtualmachineinstancereplicaset.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/generated_expansion.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/kubevirt.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/virtualmachine.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/virtualmachineinstance.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/virtualmachineinstancemigration.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/virtualmachineinstancepreset.go
  pkg/provider/cloud/kubevirt/kubevirtcli/client/versioned/typed/core/v1/virtualmachineinstancereplicaset.go
  pkg/provider/cloud/kubevirt/provider.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9129 Create dedicated namespace in KubeVirt infra cluster
  pkg/provider/cloud/kubevirt/namespace.go
  pkg/provider/cloud/kubevirt/provider.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9149 Use sigs.k8s.io/yaml for KubermaticConfiguration unmarshalling in cmd/image-loader
  cmd/image-loader/operator.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#9037 use yaml.UnmarshalStrict
  cmd/image-loader/operator.go
  cmd/kubermatic-api/options.go
  cmd/kubermatic-webhook/options.go
  cmd/master-controller-manager/main.go
  cmd/node-resource-documenter/documenter.go
  cmd/seed-controller-manager/options.go
  pkg/addon/template_test.go
  pkg/addon/testdata/cluster-kubernetes-aws.yaml
  pkg/addon/testdata/cluster-kubernetes-do.yaml
  pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller.go
  pkg/controller/seed-controller-manager/mla/alertmanager_controller.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/ratelimit_cortex_controller.go
  pkg/controller/seed-controller-manager/mla/ratelimit_cortex_controller_test.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller.go
  pkg/controller/user-cluster-controller-manager/resources/resources/gatekeeper/crds.go
  pkg/handler/v2/alertmanager/alertmanager.go
  pkg/handler/v2/rulegroup/request.go
  pkg/test/e2e/mla/mla_test.go
  pkg/util/yamled/document.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#9143 sync ApplicationDefinition from master to seed clusters
  cmd/master-controller-manager/controllers.go
  codegen/reconcile/main.go
  pkg/apis/apps.kubermatic/v1/types.go
  pkg/controller/master-controller-manager/application-definition-synchronizer/OWNERS
  pkg/controller/master-controller-manager/application-definition-synchronizer/controller.go
  pkg/controller/master-controller-manager/application-definition-synchronizer/controller_test.go
  pkg/controller/master-controller-manager/application-definition-synchronizer/doc.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#9123 do not attempt to reconcile Gatekeeper contraints if cluster is not yet healthy
  pkg/apis/kubermatic/v1/cluster.go
  pkg/controller/seed-controller-manager/constraint-template-controller/controller.go
  pkg/controller/seed-controller-manager/constraint-template-controller/controller_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/crd

#9150 do not log the same message in the initial-md-controller ad infinitum
  cmd/seed-controller-manager/main.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management
