Repository kubermatic/kubermatic, pull requests merged in 2022-05, with the labels that each got.

#9719 refactor: ensure controller names comply with our convention
  cmd/master-controller-manager/main.go
  cmd/seed-controller-manager/main.go
  pkg/controller/master-controller-manager/application-definition-synchronizer/controller.go
  pkg/controller/master-controller-manager/cluster-template-synchronizer/controller.go
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/controller/master-controller-manager/kubeone/controller.go
  pkg/controller/master-controller-manager/master-constraint-controller/controller.go
  pkg/controller/master-controller-manager/master-constraint-template-controller/controller.go
  pkg/controller/master-controller-manager/project-label-synchronizer/project_label_synchronizer.go
  pkg/controller/master-controller-manager/project-synchronizer/controller.go
  pkg/controller/master-controller-manager/seed-proxy/controller.go
  pkg/controller/master-controller-manager/seed-sync/controller.go
  pkg/controller/master-controller-manager/user-synchronizer/controller.go
  pkg/controller/operator/master/controller.go
  pkg/controller/operator/seed/controller.go
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/controller/seed-controller-manager/backup/backup_controller.go
  pkg/controller/seed-controller-manager/cloud/cloud_controller.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
  pkg/controller/seed-controller-manager/constraint-controller/controller.go
  pkg/controller/seed-controller-manager/constraint-template-controller/controller.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller.go
  pkg/controller/seed-controller-manager/etcdrestore/etcd_restore_controller.go
  pkg/controller/seed-controller-manager/monitoring/monitoring_controller.go
  pkg/controller/seed-controller-manager/pvwatcher/pvwatcher_controller.go
  pkg/controller/seed-controller-manager/seedresourcesuptodatecondition/seedresourcesuptodatecondition_controller.go
  pkg/controller/shared/seed-controller-lifecycle/seed_controller_lifecycle.go
  pkg/controller/user-cluster-controller-manager/ccm-csi-migrator/controller.go
  pkg/controller/user-cluster-controller-manager/cluster-role-labeler/cluster_role_labeler.go
  pkg/controller/user-cluster-controller-manager/flatcar/flatcar_controller.go
  pkg/controller/user-cluster-controller-manager/node-labeler/node_labeleler.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/ee/allowed-registry-controller/controller.go
Labels: ¯\_(ツ)_/¯, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, kind/chore

#9717 Add validations for backup destination names in seed
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/handler/v1/admin/seed.go
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/webhook/seed/validation.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9732 make conformance tests a tiny bit more robust
  cmd/conformance-tester/pkg/runner/runner.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#9733 fix cluster mutating with none Cni
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
Labels: kind/bug, lgtm, approved, release-note, dco-signoff: yes

#9734 auto-detect default namespaces/webhooks when cleaning up in-between conformance tests
  cmd/conformance-tester/pkg/tests/conformance.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes

#9737 Fix none cni mutation release 2.20
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes

#9741 [release/v2.20] update telemetry to 0.2.0 (#9740)
  charts/telemetry/Chart.yaml
  charts/telemetry/templates/cronjob.yaml
  charts/telemetry/templates/kubermatic-role.yaml
  charts/telemetry/values.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management

#9744 Make sure that kubelet-configmap(s) are up-to-date after updating KKP
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/defaults/defaults.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#9706 Introduce SeedStatus
  cmd/master-controller-manager/controllers.go
  cmd/master-controller-manager/main.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/helper/helper.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/master-controller-manager/seed-status-controller/controller.go
  pkg/controller/master-controller-manager/seed-status-controller/doc.go
  pkg/controller/master-controller-manager/seed-status-controller/reconciler.go
  pkg/controller/master-controller-manager/seed-sync/reconciler.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/shared/seed-controller-lifecycle/seed_controller_lifecycle.go
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9436 Re-enable AWS Storage Tests
  cmd/conformance-tester/pkg/runner/waiters.go
  cmd/conformance-tester/pkg/tests/storage.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#9743 Add e2e Tests for Telemetry
  charts/telemetry/Chart.yaml
  charts/telemetry/templates/cronjob.yaml
  charts/telemetry/values.yaml
  cmd/conformance-tester/pkg/runner/runner.go
  cmd/conformance-tester/pkg/tests/telemetry.go
  hack/ci/setup-kubermatic-in-kind.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#9716 update aws-node-termination-handler addon
  .gitignore
  addons/Makefile
  addons/aws-node-termination-handler/_footer.txt
  addons/aws-node-termination-handler/_header.txt
  addons/aws-node-termination-handler/aws-node-termination-handler.yaml
  addons/values-aws-node-termination-handler.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#9260 Add proposal for container registry credential handling on user clusters
  docs/proposals/container-registry-credentials-per-usercluster.md
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes

#9708 Get kubeone machinedeployments and nodes
  pkg/handler/v2/external_cluster/kubeone.go
  pkg/handler/v2/external_cluster/node.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#9704 Update to machine-controller v1.49.0 (quay.io image)
  go.mod
  go.sum
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/machinecontroller/webhook.go
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9710 Scale kubeone machinedeployment replicas
  pkg/handler/v2/external_cluster/kubeone.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#9773 [release/v2.20] fix S3 exporter (#9769)
  charts/s3-exporter/Chart.yaml
  charts/s3-exporter/values.yaml
  hack/publish-s3-exporter.sh
  pkg/exporters/s3/exporter.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#9720 Including "machine deployment count" to list cluster v2 route
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/common/cluster.go
  pkg/handler/v1/cluster/cluster.go
  pkg/handler/v1/common/request.go
  pkg/handler/v2/cluster/cluster.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/project/list_clusters_v2_parameters.go
  pkg/test/e2e/utils/apiclient/client/project/project_client.go
  pkg/test/e2e/utils/apiclient/models/cluster.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#9752 Move kubeone cluster status from spec to status
  pkg/apis/kubermatic/v1/external_cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/master-controller-manager/kubeone/controller.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/kubeone.go
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9623 Extend KubeOne controller to migrate kubeone cluster to containerd
  pkg/controller/master-controller-manager/kubeone/controller.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/kubeone.go
  pkg/kubernetes/helper.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9780 update Helm in our Docker image to 3.8.1
  Dockerfile
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes

#9746 show konnectivity health in extended cluster health
  pkg/apis/kubermatic/v1/cluster.go
  pkg/controller/seed-controller-manager/kubernetes/health.go
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9781 update kubermatic/util image, include yq4
  charts/minio/test/values.example.ce.yaml.out
  charts/minio/test/values.example.ee.yaml.out
  charts/minio/values.yaml
  charts/monitoring/grafana/values.yaml
  charts/monitoring/karma/values.yaml
  charts/monitoring/prometheus/values.yaml
  hack/ci/testdata/minio_bucket_job.yaml
  hack/images/util/Dockerfile
  hack/images/util/release.sh
  hack/lib.sh
  pkg/controller/master-controller-manager/seed-proxy/resources.go
  pkg/resources/test/fixtures/deployment-aws-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-web-terminal.yaml
  pkg/resources/web-terminal/deployment.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#9765 Duplicate S3 collector and make it run inside the seed-ctrl-mgr
  cmd/seed-controller-manager/main.go
  pkg/collectors/clusterbackup.go
  pkg/collectors/s3.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9747 Make CRDs more accessible
  docs/cluster-defaulting-validation.md
  hack/lib.sh
  hack/update-codegen.sh
  hack/verify-boilerplate.sh
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/suite_test.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/applications/crds.go
  pkg/crd/fs.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_addonconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_addons.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_admissionplugins.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_alertmanagers.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_allowedregistries.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplateinstances.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_constraints.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_constrainttemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdbackupconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdrestores.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_mlaadminsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_projects.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_rulegroups.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_userprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_users.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_usersshkeys.yaml
  pkg/resources/resources.go
  pkg/validation/applicationdefinition.go
  pkg/validation/openapi/openapi.go
  pkg/validation/openapi/openapi_test.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#9791 Extending API E2E tests to check machine deployment count value
  pkg/test/e2e/api/hetzner_test.go
  pkg/test/e2e/api/kubevirt_test.go
  pkg/test/e2e/api/util.go
  pkg/test/e2e/utils/client.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#9750 Update vsphere csi/ccm to support k8s 1.23
  .prow/provider-vsphere.yaml
  addons/csi/vsphere/csi-migration-webhook.yaml
  addons/csi/vsphere/snapshot-controller.yaml
  addons/csi/vsphere/snapshot-crds.yaml
  addons/csi/vsphere/snapshot-webhook.yaml
  addons/csi/vsphere/vsphere-csi-driver.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/defaults/defaults.go
  pkg/resources/cloudcontroller/vsphere.go
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-vsphere-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-vsphere-cloud-controller-manager-externalCloudProvider.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#9796 Fix nil pointer dereference in kubeone controller
  pkg/controller/master-controller-manager/kubeone/controller.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9739 Alerts: fix CPU and Memory overcommit alerts
  charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/src/general/kube-state-metrics.yaml
Labels: ok-to-test, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management

#9797 improve cluster deletion
  pkg/handler/common/cluster.go
  pkg/provider/kubernetes/cluster.go
  pkg/provider/types.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#9795 Update e2e tests to kind 0.13 (with k8s 1.24)
  .prow/api.yaml
  .prow/ccm-migrations.yaml
  .prow/features.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  charts/monitoring/prometheus/rules/general-kube-kubelet.yaml
  charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/general-node-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/kube-kubelet.yaml
  charts/monitoring/prometheus/rules/src/general/kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/src/general/node-exporter.yaml
  hack/ci/setup-kind-cluster.sh
  hack/update-prometheus-rules.sh
  hack/verify-licenses.sh
  hack/verify-prometheus-rules.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#9715 Resource quota webhook providers - AWS, GCP, Azure, KubeVirt, vSphere, Openstack
  cmd/user-cluster-webhook/main.go
  cmd/user-cluster-webhook/options.go
  pkg/ee/validation/machine/providers.go
  pkg/ee/validation/machine/resourcequota.go
  pkg/ee/validation/machine/resourcequota_test.go
  pkg/handler/common/provider/aws.go
  pkg/handler/common/provider/azure.go
  pkg/handler/common/provider/gcp.go
  pkg/handler/common/provider/kubevirt.go
  pkg/handler/common/provider/openstack.go
  pkg/resources/test/fixtures/deployment-aws-1.21.0-user-cluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-user-cluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-user-cluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-user-cluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-user-cluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-user-cluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-user-cluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-user-cluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-user-cluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-user-cluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-user-cluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-user-cluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-user-cluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-user-cluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-user-cluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-user-cluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-user-cluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-user-cluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-user-cluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-user-cluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-user-cluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-user-cluster-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-user-cluster-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-user-cluster-webhook.yaml
  pkg/resources/user-cluster-webhook/deployment.go
  pkg/webhook/machine/validation/validation.go
  pkg/webhook/machine/validation/wrappers_ce.go
  pkg/webhook/machine/validation/wrappers_ee.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9790 Update Go dependencies
  go.mod
  go.sum
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes

#9806 update kubevirt prow preset
  .prow/provider-kubevirt.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#9805 update to Go 1.18.2
  .prow/api.yaml
  .prow/ccm-migrations.yaml
  .prow/features.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes

#9803 enable nosprintfhostport linter
  .golangci.yml
  .prow/tests.yaml
  cmd/conformance-tester/pkg/tests/loadbalancer.go
  cmd/etcd-launcher/main.go
  pkg/resources/address/address.go
  pkg/resources/address/address_test.go
  pkg/test/e2e/cilium/cilium_test.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9787 Extend metering report configuration with retention parameter
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.seed.yaml
  pkg/api/v1/types.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/operator/seed/reconciler_test.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/ee/metering/cronjob.go
  pkg/ee/metering/reconcile.go
  pkg/ee/metering/report_config_handler.go
  pkg/ee/metering/report_config_handler_test.go
  pkg/test/e2e/utils/apiclient/client/admin/create_metering_report_configuration_responses.go
  pkg/test/e2e/utils/apiclient/client/admin/update_metering_report_configuration_responses.go
  pkg/test/e2e/utils/apiclient/models/metering_report_configuration.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9817 fix health konnectivity/apiserver status infinite toggle
  pkg/controller/seed-controller-manager/kubernetes/health.go
Labels: lgtm, approved

#9335 Update Anexia CCM
  pkg/resources/cloudcontroller/anexia.go
Labels: size/S, ok-to-test, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9807 Add audit logging to presets for Cluster API & Gatekeeper resources
  pkg/resources/apiserver/audit.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9561 Add e2e tests for Anexia
  .prow/provider-anexia.yaml
  cmd/conformance-tester/pkg/scenarios/anexia.go
  cmd/conformance-tester/pkg/scenarios/interface.go
  cmd/conformance-tester/pkg/types/secrets.go
  hack/ci/run-conformance-tests.sh
  hack/ci/setup-kubermatic-in-kind.sh
  hack/ci/testdata/seed.yaml
  hack/run-conformance-tests.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9825 bump machine-controller to v1.50.0
  go.mod
  go.sum
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9809 Endpoint for openstack subnet pools
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/common/provider/openstack.go
  pkg/handler/v1/provider/openstack.go
  pkg/handler/v2/provider/openstack.go
  pkg/handler/v2/provider/openstack_fixtures_test.go
  pkg/handler/v2/provider/openstack_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/cloud/openstack/provider.go
  pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_subnet_pools_parameters.go
  pkg/test/e2e/utils/apiclient/client/openstack/list_openstack_subnet_pools_responses.go
  pkg/test/e2e/utils/apiclient/client/openstack/openstack_client.go
  pkg/test/e2e/utils/apiclient/models/openstack_subnet_pool.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9829 add logging conventions and simplify documentation
  docs/logging.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#9810 Add ResourceQuota CRD
  pkg/apis/kubermatic/v1/resource_quota.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_resourcequotas.yaml
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9823 Use k8c.io/kubermatic/v2/pkg/semver for some version comparisons
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/controller/seed-controller-manager/addon/addon_controller_test.go
  pkg/resources/cloudcontroller/openstack.go
  pkg/resources/cloudcontroller/vsphere.go
  pkg/util/kubectl/kubectl.go
  pkg/util/kubectl/kubectl_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#9802 add e2e for cluster terminal
  pkg/test/e2e/api/hetzner_test.go
  pkg/test/e2e/api/kubevirt_test.go
  pkg/test/e2e/api/util.go
  pkg/test/e2e/utils/client.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#9751 add e2e test for dualstack clusters on azure
  .golangci.yml
  .prow/features.yaml
  hack/ci/run-dualstack-e2e-test.sh
  hack/ci/testdata/kubermatic_dualstack.yaml
  pkg/test/dualstack/azure_dualstack_test.go
  pkg/test/dualstack/dualstack_test.go
  pkg/test/dualstack/egress-validator-4.yaml
  pkg/test/dualstack/egress-validator-6.yaml
  pkg/test/e2e/utils/client.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#9828 removed buggy log sync
  cmd/conformance-tester/main.go
  cmd/image-loader/main.go
  cmd/kubermatic-api/main.go
  cmd/kubermatic-operator/main.go
  cmd/kubermatic-webhook/main.go
  cmd/master-controller-manager/main.go
  cmd/nodeport-proxy/envoy-manager/main.go
  cmd/nodeport-proxy/lb-updater/main.go
  cmd/s3-exporter/main.go
  cmd/s3-storeuploader/main.go
  cmd/seed-controller-manager/main.go
  cmd/user-cluster-webhook/main.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9831 Add cluster-autoscaler version for Kubernetes 1.24
  addons/cluster-autoscaler/cluster-autoscaler.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/clusterautoscaler/clusterautoscaler.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#9830 applicationInstallation crd: change .spec.values type from byte to object
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/apis/apps.kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller.go
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller_test.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#9838 Fix deleting seeds
  pkg/controller/master-controller-manager/seed-sync/reconciler.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#9837 Update VPA to 0.10.0
  cmd/seed-controller-manager/main.go
  codegen/reconcile/main.go
  go.mod
  go.sum
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/controller/seed-controller-manager/monitoring/monitoring_controller.go
  pkg/resources/dns/deletion.go
  pkg/resources/metrics-server/deletion.go
  pkg/resources/openvpn/deletion.go
  pkg/resources/reconciling/zz_generated_reconcile.go
  pkg/resources/vpa.go
  pkg/version/kubermatic/versions.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#9844 do not reconcile the ClusterAPI Cluster CRD into userclusters anymore
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/machine-controller/crds.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#9851 helm/cli: don't swallow error in BuildChartDependencies
  pkg/install/helm/cli.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9843 run tagliatelle against all APIs
  .golangci.apis.yml
  .golangci.yml
  Makefile
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#9835 Extending provider datacenter endpoint to return if IPv6 is enabled for it
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/v1/admin/seed_test.go
  pkg/handler/v1/dc/datacenter.go
  pkg/handler/v1/dc/datacenter_test.go
  pkg/test/e2e/utils/apiclient/models/datacenter_spec.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#9850 update node-local-dns cache to 1.21.1
  pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/deamonset.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#9860 [release/v2.20] Fix kubevirt e2e scenarios
  cmd/conformance-tests/scenarios_kubevirt.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#9854 set the security context for the WEB terminal Pod
  pkg/resources/test/fixtures/deployment-aws-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-web-terminal.yaml
  pkg/resources/web-terminal/deployment.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9857 Cluster resource usage
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#9867 check for cloud provider mismatch between node and datacenter
  pkg/resources/machine/machinedeployment.go
  pkg/resources/machine/machinedeployment_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#9870 update tests to kind 0.14
  .prow/api.yaml
  .prow/ccm-migrations.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes

#9808 add quota filter for Kubevirt VMIPresets
  pkg/ee/validation/machine/providers.go
  pkg/handler/common/provider/kubevirt.go
  pkg/handler/v2/provider/kubevirt.go
  pkg/handler/v2/provider/kubevirt_test.go
  pkg/handler/v2/routes_v2.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#9871 Load more images in image-loader
  cmd/image-loader/main.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes

#9852 refactor dualstack tester; add tests for GCP, AWS
  hack/ci/run-dualstack-e2e-test.sh
  pkg/test/dualstack/cloudProviders.go
  pkg/test/dualstack/cloudProviders_dualstack_test.go
  pkg/test/dualstack/dualstack_test.go
  pkg/test/dualstack/egress-validator-daemonset.yaml
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9748 Automatically manage KKP CRDs on seed clusters
  Makefile
  cmd/kubermatic-installer/cmd_deploy.go
  cmd/kubermatic-operator/main.go
  hack/ci/deploy.sh
  hack/ci/github-release.sh
  hack/ci/setup-kubermatic-backups-in-kind.sh
  hack/ci/setup-kubermatic-in-kind.sh
  hack/ci/setup-kubermatic-mla-in-kind.sh
  hack/lib.sh
  hack/local/run-kubermatic-kind.sh
  hack/run-expose-strategy-e2e-test-in-kind.sh
  pkg/controller/operator/common/resources.go
  pkg/controller/operator/seed/controller.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/operator/seed/reconciler_ce_test.go
  pkg/controller/operator/seed/reconciler_ee_test.go
  pkg/controller/operator/seed/reconciler_test.go
  pkg/install/stack/kubermatic-master/certmanager.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/stack/kubermatic-seed/stack.go
  pkg/install/stack/types.go
  pkg/install/util/crd.go
  pkg/util/cli/hello.go
  pkg/version/kubermatic/versions.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9876 Let helm call invoked by installer evaluate env
  pkg/install/helm/cli.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#9866 Considering network config from seed default template for network defaults endpoint
  cmd/kubermatic-api/swagger.json
  pkg/defaulting/cluster.go
  pkg/defaulting/cluster_test.go
  pkg/handler/v2/networkdefaults/networkdefaults.go
  pkg/handler/v2/networkdefaults/networkdefaults_test.go
  pkg/handler/v2/networkdefaults/networkdefaults_unit_test.go
  pkg/handler/v2/routes_v2.go
  pkg/resources/resources.go
  pkg/test/e2e/utils/apiclient/client/networkdefaults/get_network_defaults_parameters.go
  pkg/test/e2e/utils/apiclient/client/networkdefaults/get_network_defaults_responses.go
  pkg/test/e2e/utils/apiclient/client/networkdefaults/networkdefaults_client.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9865 Fix credential reference for cluster template
  pkg/handler/v2/cluster_template/cluster_template.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/api

#9885 Allow upgrading from k8s 1.23 to 1.24
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/defaults/defaults.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#9884 [release/v2.20] Bump Kubernetes patch versions for 1.21.12, 1.22.9 and 1.23.6
  .prow.yaml
  docs/zz_generated.kubermaticConfiguration.yaml
  go.mod
  go.sum
  pkg/controller/operator/defaults/defaults.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9883 Bump Kubernetes patch versions for 1.21.12, 1.22.9 and 1.23.6
  .prow/api.yaml
  .prow/ccm-migrations.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  Dockerfile
  docs/zz_generated.kubermaticConfiguration.yaml
  go.mod
  go.sum
  pkg/controller/operator/defaults/defaults.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9208 Proposal for resource quotas
  docs/proposals/resource-quotas.md
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes

#9714 Add ApplicationSecret synchronization between master and seed
  cmd/master-controller-manager/controllers.go
  pkg/controller/master-controller-manager/application-secret-synchronizer/OWNERS
  pkg/controller/master-controller-manager/application-secret-synchronizer/controller.go
  pkg/controller/master-controller-manager/application-secret-synchronizer/controller_test.go
  pkg/controller/master-controller-manager/application-secret-synchronizer/doc.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9886 Refactor kubeone controller to ensure kubeconfig reference in kubeone cluster
  pkg/controller/master-controller-manager/kubeone/controller.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9900 Makes telemetry uuid optional and generates if not provided
  charts/telemetry/templates/secret.yaml
  charts/telemetry/values.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#9889 CoreDNS deployment: configurable number of replicas + anti-affinity rules
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/core-dns/deployment.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/test/e2e/utils/apiclient/models/cluster_networking_config.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9913 make dualstack e2e tests optional
  .prow/features.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#9917 Make Nutanix e2e optional
  .prow/provider-nutanix.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#9902 add storage for the WEB terminal Pod
  pkg/handler/routes_v1_websocket.go
  pkg/handler/websocket/terminal.go
  pkg/resources/test/fixtures/deployment-aws-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-web-terminal.yaml
  pkg/resources/web-terminal/deployment.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9868 Fail update validation for unsupported cloud spec changes
  pkg/provider/cloud/aws/provider.go
  pkg/provider/cloud/azure/provider.go
  pkg/provider/cloud/nutanix/provider.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/vsphere/provider.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9894 Ignore conflicting operation on bucket lifecycle update
  pkg/ee/metering/reconcile.go
  pkg/ee/metering/report_config_handler.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#9910 Adding CRDs for IPAMPool and IPAMAllocation
  pkg/apis/kubermatic/v1/ipam_allocation.go
  pkg/apis/kubermatic/v1/ipam_pool.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_ipamallocations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipampools.yaml
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9891 ApplicationDefinition: add missing validation check and field for git
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/apis/apps.kubermatic/v1/types.go
  pkg/apis/apps.kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_test.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/validation/applicationdefinition.go
  pkg/validation/applicationdefinition_test.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#9909 Add delete propagation policy while removing metering cron jobs
  pkg/ee/metering/handler.go
  pkg/ee/metering/reconcile.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#9892 Block dynamic kubelet config for NodeDeployments with Kubernetes 1.24 and higher
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/handler/v1/node/node_test.go
  pkg/handler/v2/machine/machine_test.go
  pkg/resources/machine/machinedeployment.go
  pkg/test/e2e/utils/apiclient/models/node_deployment_spec.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9928 customize BASH prompt for the WEB terminal
  pkg/resources/test/fixtures/deployment-aws-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-web-terminal.yaml
  pkg/resources/web-terminal/deployment.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#9926 extend the user settings for new flag
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/user.go
  pkg/crd/k8c.io/kubermatic.k8c.io_users.yaml
  pkg/test/e2e/utils/apiclient/models/user_settings.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9934 Minor refactoring for CI
  hack/ci/setup-kind-cluster.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#9936 Add comments to ComponentSettings fields
  docs/zz_generated.seed.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#9940 add changelog for 2.20.3
  CHANGELOG.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes
