Repository kubermatic/kubermatic, pull requests merged in 2022-04, with the labels that each got.

#9509 add sig-app-mgmt ownership for apps.kubermatic
  pkg/apis/apps.kubermatic/OWNERS
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9473 Fix context handling
  pkg/controller/operator/common/webhook.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/master/resources/kubermatic/webhooks.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/operator/seed/resources/kubermatic/webhooks.go
  pkg/test/clusterexposer/controller/controller.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#9418 install applicationInstallation CRD into user-cluster
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/applications/crds.go
  pkg/resources/resources.go
  pkg/validation/openapi/openapi.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#9448 KubeOne container-runtime migrate endpoint
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/kubeone.go
  pkg/resources/resources.go
  pkg/test/e2e/utils/apiclient/client/project/patch_external_cluster_parameters.go
  pkg/test/e2e/utils/apiclient/models/kube_one_spec.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9519 simplify code
  pkg/validation/cluster.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#9524 [release/v2.16] Synchronize OWNERS_ALIASES file with Github teams
  OWNERS_ALIASES
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#9525 [release/v2.17] Synchronize OWNERS_ALIASES file with Github teams
  OWNERS_ALIASES
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#9526 [release/v2.18] Synchronize OWNERS_ALIASES file with Github teams
  OWNERS_ALIASES
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#9527 [release/v2.19] Synchronize OWNERS_ALIASES file with Github teams
  OWNERS_ALIASES
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#9528 [release/v2.20] Synchronize OWNERS_ALIASES file with Github teams
  OWNERS_ALIASES
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#9478 Add preset sync controller
  cmd/master-controller-manager/controllers.go
  codegen/reconcile/main.go
  pkg/api/v1/types.go
  pkg/controller/master-controller-manager/preset-synchronizer/OWNERS
  pkg/controller/master-controller-manager/preset-synchronizer/controller.go
  pkg/controller/master-controller-manager/preset-synchronizer/controller_test.go
  pkg/controller/master-controller-manager/preset-synchronizer/doc.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9515 add a connection between preset and cluster template
  pkg/handler/v2/cluster_template/cluster_template.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#9516 Make UserProjectBinding the canonical source of project membership
  pkg/apis/kubermatic/v1/project.go
  pkg/controller/master-controller-manager/rbac/sync_project.go
  pkg/controller/master-controller-manager/rbac/sync_project_test.go
  pkg/controller/master-controller-manager/rbac/sync_resource_test.go
  pkg/controller/master-controller-manager/rbac/test/helper.go
  pkg/controller/master-controller-manager/serviceaccount-projectbinding-controller/controller_test.go
  pkg/controller/master-controller-manager/user-project-binding/controller_test.go
  pkg/handler/test/fake_provider.go
  pkg/handler/test/helper.go
  pkg/handler/v1/project/project.go
  pkg/handler/v1/project/project_test.go
  pkg/provider/kubernetes/project.go
  pkg/provider/kubernetes/project_test.go
  pkg/provider/kubernetes/util_test.go
  pkg/provider/types.go
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_projects.yaml
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9522 "Implement" ReconcilingCloudProvider interface for bringyourown provider
  pkg/provider/cloud/bringyourown/provider.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#9523 Synchronize OWNERS_ALIASES file with Github teams
  OWNERS_ALIASES
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#9469 Machine controller health check extended
  pkg/controller/seed-controller-manager/kubernetes/health.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#9483 Adding endpoints for seed's metering report configurations
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/ee/metering/report_config_handler.go
  pkg/ee/metering/report_config_handler_test.go
  pkg/handler/routes_v1_admin.go
  pkg/handler/v1/admin/metering.go
  pkg/handler/v1/admin/wrappers_ce.go
  pkg/handler/v1/admin/wrappers_ee.go
  pkg/test/e2e/utils/apiclient/client/admin/admin_client.go
  pkg/test/e2e/utils/apiclient/client/admin/create_metering_report_configuration_parameters.go
  pkg/test/e2e/utils/apiclient/client/admin/create_metering_report_configuration_responses.go
  pkg/test/e2e/utils/apiclient/client/admin/delete_metering_report_configuration_parameters.go
  pkg/test/e2e/utils/apiclient/client/admin/delete_metering_report_configuration_responses.go
  pkg/test/e2e/utils/apiclient/client/admin/get_metering_report_configuration_parameters.go
  pkg/test/e2e/utils/apiclient/client/admin/get_metering_report_configuration_responses.go
  pkg/test/e2e/utils/apiclient/client/admin/list_metering_report_configurations_parameters.go
  pkg/test/e2e/utils/apiclient/client/admin/list_metering_report_configurations_responses.go
  pkg/test/e2e/utils/apiclient/client/admin/update_metering_report_configuration_parameters.go
  pkg/test/e2e/utils/apiclient/client/admin/update_metering_report_configuration_responses.go
  pkg/test/e2e/utils/apiclient/models/metering_report_configuration.go
  pkg/validation/metering.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#9530 copy CRDs into the operator chart during release
  .gitignore
  charts/kubermatic-operator/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  charts/kubermatic-operator/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_addonconfigs.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_addons.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_admissionplugins.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_alertmanagers.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_allowedregistries.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplateinstances.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_constraints.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_constrainttemplates.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_etcdbackupconfigs.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_etcdrestores.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_mlaadminsettings.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_projects.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_rulegroups.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_userprojectbindings.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_users.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_usersshkeys.yaml
  charts/kubermatic-operator/crd/k8c.io/operatingsystemmanager.k8c.io_operatingsystemconfig.yaml
  charts/kubermatic-operator/crd/k8c.io/operatingsystemmanager.k8c.io_operatingsystemprofile.yaml
  hack/ci/deploy.sh
  hack/ci/github-release.sh
  hack/ci/setup-kubermatic-backups-in-kind.sh
  hack/ci/setup-kubermatic-in-kind.sh
  hack/ci/setup-kubermatic-mla-in-kind.sh
  hack/lib.sh
  hack/local/run-kubermatic-kind.sh
  hack/run-expose-strategy-e2e-test-in-kind.sh
  hack/update-codegen.sh
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9322 Adjust ETCD_INITIAL_CLUSTER during peer TLS migration
  cmd/etcd-launcher/main.go
  pkg/controller/master-controller-manager/rbac/sync_resource.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#9364 Domain is not required when using application credentials
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/openstack/provider_test.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-externalCloudProvider.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#9533 Add metering report config name validation
  pkg/ee/metering/report_config_handler.go
  pkg/ee/metering/report_config_handler_test.go
  pkg/handler/v1/admin/metering.go
  pkg/validation/metering.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#9535 Resolve race condition in metering report configuration tests
  pkg/ee/metering/report_config_handler_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#9538 improve CRDs, mark more fields as optional and improve documentation
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/cluster_templates.go
  pkg/apis/kubermatic/v1/sshkeys.go
  pkg/apis/kubermatic/v1/user.go
  pkg/apis/kubermatic/v1/user_project_binding.go
  pkg/controller/master-controller-manager/rbac/sync_project_test.go
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_userprojectbindings.yaml
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_users.yaml
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_usersshkeys.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#9540 Update operating-system-manager to v0.4.2
  go.mod
  go.sum
  pkg/resources/operatingsystemmanager/deployment.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#9327 extend vSphere provider for default tag category
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/cluster.go
  pkg/provider/cloud/vsphere/category.go
  pkg/provider/cloud/vsphere/client.go
  pkg/provider/cloud/vsphere/provider.go
  pkg/test/e2e/utils/apiclient/models/v_sphere_cloud_spec.go
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#9479 skip kubeone-namespace in rbac generation
  pkg/controller/master-controller-manager/rbac/mapper.go
  pkg/resources/resources.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, sig/api

#9543 Group metering reports for a given configuration
  cmd/kubermatic-api/swagger.json
  pkg/ee/metering/cronjob.go
  pkg/ee/metering/report_handler.go
  pkg/test/e2e/utils/apiclient/client/metering/get_metering_report_parameters.go
  pkg/test/e2e/utils/apiclient/client/metering/list_metering_reports_parameters.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#9518 Addition of missing images to image-loader
  cmd/image-loader/main.go
  cmd/image-loader/main_test.go
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/cluster.go
  pkg/provider/types.go
  pkg/provider/types_test.go
  pkg/resources/credentials.go
  pkg/test/e2e/utils/apiclient/models/kubevirt_cloud_spec.go
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9541 Add GitOps-based e2e test
  .prow.yaml
  cmd/conformance-tester/main.go
  cmd/conformance-tester/pkg/clients/client.go
  cmd/conformance-tester/pkg/clients/client_api.go
  cmd/conformance-tester/pkg/clients/client_kube.go
  cmd/conformance-tester/pkg/runner/runner.go
  cmd/conformance-tester/pkg/scenarios/alibaba.go
  cmd/conformance-tester/pkg/scenarios/aws.go
  cmd/conformance-tester/pkg/scenarios/azure.go
  cmd/conformance-tester/pkg/scenarios/digitalocean.go
  cmd/conformance-tester/pkg/scenarios/gcp.go
  cmd/conformance-tester/pkg/scenarios/hetzner.go
  cmd/conformance-tester/pkg/scenarios/interface.go
  cmd/conformance-tester/pkg/scenarios/kubevirt.go
  cmd/conformance-tester/pkg/scenarios/nutanix.go
  cmd/conformance-tester/pkg/scenarios/openstack.go
  cmd/conformance-tester/pkg/scenarios/os.go
  cmd/conformance-tester/pkg/scenarios/packet.go
  cmd/conformance-tester/pkg/scenarios/vsphere.go
  cmd/conformance-tester/pkg/types/options.go
  hack/ci/run-conformance-tests.sh
  hack/ci/run-e2e-tests.sh
  hack/ci/testdata/kubermatic_headless.yaml
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9500 Application controller skeleton
  cmd/user-cluster-controller-manager/main.go
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/OWNERS
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_test.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/doc.go
  pkg/resources/usercluster/rbac.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#9511 Support for disabling kubernetes-dashboard
  cmd/kubermatic-api/swagger.json
  hack/run-user-cluster-controller-manager.sh
  pkg/api/v1/types.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/kubernetes-dashboard/deletion.go
  pkg/handler/common/cluster.go
  pkg/handler/v1/cluster/cluster_test.go
  pkg/handler/v2/cluster/cluster_test.go
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
  pkg/resources/cluster/cluster.go
  pkg/resources/kubernetes-dashboard/deletion.go
  pkg/test/e2e/utils/apiclient/models/cluster_spec.go
  pkg/test/e2e/utils/apiclient/models/kubernetes_dashboard.go
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9551 Call BuildChartDependencies for each chart in image-loader
  cmd/image-loader/helm.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes

#9552 Skip ipv6 in DNAT controller
  addons/openvpn/openvpn-client-dep.yaml
  pkg/controller/kubeletdnat-controller/controller.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#9532 Dual Stack support for OpenStack
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/cluster.go
  pkg/provider/cloud/openstack/helper.go
  pkg/provider/cloud/openstack/internal/testing/fixtures.go
  pkg/provider/cloud/openstack/internal/testing/simulator.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/openstack/provider_test.go
  pkg/test/e2e/utils/apiclient/models/openstack_cloud_spec.go
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9553 Fix potential race in cleanup of Azure resources
  pkg/provider/cloud/azure/availability_set.go
  pkg/provider/cloud/azure/resource_group.go
  pkg/provider/cloud/azure/route_table.go
  pkg/provider/cloud/azure/security_group.go
  pkg/provider/cloud/azure/subnet.go
  pkg/provider/cloud/azure/vnet.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#9556 move S3 collector into the collectors package
  cmd/s3-exporter/main.go
  pkg/collectors/s3.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#9544 Add HeadlessInstallation feature gate to disable API/UI/Ingress
  docs/zz_generated.kubermaticConfiguration.yaml
  hack/ci/testdata/kubermatic_headless.yaml
  pkg/apis/kubermatic/v1/configuration.go
  pkg/controller/operator/master/reconciler.go
  pkg/features/features.go
  pkg/install/stack/kubermatic-master/certmanager.go
  pkg/install/stack/kubermatic-master/nginxingress.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/stack/kubermatic-master/validation.go
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9558 Upgrade to klog/v2
  cmd/kubeletdnat-controller/main.go
  cmd/kubermatic-api/main.go
  cmd/kubermatic-operator/main.go
  cmd/kubermatic-webhook/options.go
  cmd/master-controller-manager/controllers.go
  cmd/master-controller-manager/main.go
  cmd/seed-controller-manager/main.go
  cmd/user-cluster-controller-manager/main.go
  go.mod
  pkg/controller/master-controller-manager/rbac/rbac_controller_aggregator.go
  pkg/controller/master-controller-manager/rbac/rbac_project_controller.go
  pkg/controller/master-controller-manager/rbac/rbac_resource_controller.go
  pkg/controller/master-controller-manager/rbac/sync_project.go
  pkg/controller/master-controller-manager/rbac/sync_project_test.go
  pkg/controller/master-controller-manager/rbac/sync_resource.go
  pkg/controller/master-controller-manager/rbac/sync_resource_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9557 Enable the vsphereCSIClusterID feature flag when running the CCM/CSI migration
  pkg/handler/common/cluster.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/api

#9569 Add omitempty json tags to optional IPv6 OpenStack cloud spec options
  pkg/apis/kubermatic/v1/cluster.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#9574 telemetry does not need access to pre-2.20 API groups anymore
  charts/telemetry/templates/kubermatic-role.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#9508 add validation for ApplicationDefinitions
  pkg/validation/application_definition.go
  pkg/validation/application_definition_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes

#9575 update Dex to 2.31.1
  charts/oauth/Chart.yaml
  charts/oauth/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#9576 clarify stacking child validation
  docs/cluster-defaulting-validation.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#9563 Kubermatic API: skipping unreachable seeds instead of returning error to user
  pkg/provider/kubernetes/cluster.go
  pkg/provider/kubernetes/etcdbackupconfig.go
  pkg/provider/kubernetes/etcdrestore.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#9567 [release/v2.20] Addition of missing images to image-loader (#9518)
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  cmd/image-loader/main.go
  cmd/image-loader/main_test.go
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/cluster.go
  pkg/install/crdmigration/clones.go
  pkg/provider/types.go
  pkg/provider/types_test.go
  pkg/resources/credentials.go
  pkg/test/e2e/utils/apiclient/models/kubevirt_cloud_spec.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#9566 Improve CRDs with better type/field descriptions
  cmd/kubermatic-api/swagger.json
  pkg/addon/template.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/common.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/test/e2e/utils/apiclient/models/audit_logging_settings.go
  pkg/test/e2e/utils/apiclient/models/audit_policy_preset.go
  pkg/test/e2e/utils/apiclient/models/azure_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/c_n_i_plugin_settings.go
  pkg/test/e2e/utils/apiclient/models/c_n_i_plugin_type.go
  pkg/test/e2e/utils/apiclient/models/cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/event_rate_limit_config.go
  pkg/test/e2e/utils/apiclient/models/expose_strategy.go
  pkg/test/e2e/utils/apiclient/models/kubernetes_dashboard.go
  pkg/test/e2e/utils/apiclient/models/l_b_s_k_u.go
  pkg/test/e2e/utils/apiclient/models/o_p_a_integration_settings.go
  pkg/test/e2e/utils/apiclient/models/update_window.go
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9568 Add API support for vSphere tags
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/machine/convert.go
  pkg/resources/machine/common.go
  pkg/test/e2e/utils/apiclient/models/v_sphere_node_spec.go
  pkg/test/e2e/utils/apiclient/models/v_sphere_tag.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9585 fix expired JWT token
  pkg/handler/test/helper.go
  pkg/provider/kubernetes/user_test.go
  pkg/provider/kubernetes/util_test.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#9572 make node-resource-documenter work again, move it to codegen/
  cmd/image-loader/addons.go
  cmd/node-resource-documenter/README.md
  cmd/node-resource-documenter/buffer.go
  cmd/node-resource-documenter/buffer_test.go
  cmd/node-resource-documenter/documenter.go
  cmd/node-resource-documenter/documenter_test.go
  cmd/node-resource-documenter/main.go
  codegen/addon-resources/README.md
  codegen/addon-resources/main.go
  hack/ci/update-docs.sh
  pkg/addon/template.go
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/controller/seed-controller-manager/addon/addon_controller_test.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9571 Add options to specify multiple IP ranges from which access to NodePort services is allowed
  cmd/kubermatic-api/swagger.json
  pkg/addon/template.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/utils.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/defaulting/cluster.go
  pkg/provider/cloud/aws/security_group.go
  pkg/provider/cloud/aws/security_group_test.go
  pkg/provider/cloud/azure/security_group.go
  pkg/provider/cloud/azure/subnet.go
  pkg/provider/cloud/azure/vnet.go
  pkg/provider/cloud/gcp/firewall_rules.go
  pkg/provider/cloud/openstack/helper.go
  pkg/provider/cloud/openstack/provider.go
  pkg/resources/controllermanager/deployment.go
  pkg/resources/resources.go
  pkg/test/e2e/utils/apiclient/models/a_w_s_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/azure_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/g_c_p_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/openstack_cloud_spec.go
  pkg/util/network/network.go
  pkg/util/network/network_test.go
  pkg/validation/cluster.go
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9588 applications installation controller: reconcile target namespace
  cmd/user-cluster-controller-manager/main.go
  pkg/applications/installer.go
  pkg/applications/installer_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes

#9599 [release/v2.18] fix expired JWT token (#9585)
  pkg/handler/test/helper.go
  pkg/provider/kubernetes/user_test.go
  pkg/provider/kubernetes/util_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#9589 prow: fix label for sig/app-management in OWNERS files
  pkg/applications/OWNERS
  pkg/controller/master-controller-manager/application-definition-synchronizer/OWNERS
  pkg/controller/master-controller-manager/cluster-template-synchronizer/OWNERS
  pkg/controller/master-controller-manager/project-synchronizer/OWNERS
  pkg/controller/master-controller-manager/user-project-binding-synchronizer/OWNERS
  pkg/controller/master-controller-manager/user-synchronizer/OWNERS
  pkg/controller/user-cluster-controller-manager/application-installation-controller/OWNERS
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#9598 [release/v2.19] fix expired JWT token (#9585)
  pkg/handler/test/helper.go
  pkg/provider/kubernetes/user_test.go
  pkg/provider/kubernetes/util_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#9595 [release/v2.20] ensure new Cluster objects from templates appear in the cache before proceeding (#9122)
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#9447 Extend kubeone controller to upgrade cluster
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/api/v2/types.go
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/controller/master-controller-manager/kubeone/controller.go
  pkg/controller/master-controller-manager/rbac/mapper.go
  pkg/handler/common/kubeconfig.go
  pkg/handler/common/upgrade.go
  pkg/handler/v2/external_cluster/kubeone.go
  pkg/handler/v2/external_cluster/upgrade.go
  pkg/provider/kubernetes/credentials.go
  pkg/resources/resources.go
  pkg/test/e2e/utils/apiclient/models/kube_one_open_stack_cloud_spec.go
  pkg/version/manager.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9592 fix NodeFilesystem alert rules
  charts/monitoring/prometheus/rules/general-node-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/node-exporter.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management

#9587 Upgrade kubeone machine deployment kubernetes version
  pkg/handler/v2/external_cluster/kubeone.go
  pkg/handler/v2/external_cluster/node.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/api

#9604 Update to etcd 3.5.3 for Kubernetes 1.22+
  go.mod
  go.sum
  pkg/resources/etcd/statefulset.go
  pkg/resources/test/fixtures/cronjob-aws-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-aws-1.23.5-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.23.5-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.23.5-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.23.5-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.22.1-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.23.5-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.23.5-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.22.1-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.23.5-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.23.5-etcd-defragger.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-apiserver.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.23.5-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.23.5-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.23.5-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.23.5-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.23.5-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.23.5-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.23.5-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.23.5-etcd.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9596 add preset stats endpoint
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v1/project/project.go
  pkg/handler/v2/cluster_template/cluster_template.go
  pkg/handler/v2/preset/preset.go
  pkg/handler/v2/preset/preset_test.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/cluster.go
  pkg/provider/kubernetes/cluster_template.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/preset/get_preset_stats_parameters.go
  pkg/test/e2e/utils/apiclient/client/preset/get_preset_stats_responses.go
  pkg/test/e2e/utils/apiclient/client/preset/preset_client.go
  pkg/test/e2e/utils/apiclient/models/preset_stats.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/api

#9586 allowing arbitrary name for the cluster + adding length validation
  pkg/handler/common/cluster.go
  pkg/resources/machine/machinedeployment.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#9591 Update to Go 1.18.1
  .prow.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes

#9582 Add encryption-at-rest fields and validation to kubermaticv1.Cluster CRD
  docs/proposals/encryption-at-rest.md
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/validation/cluster.go
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/validation/openapi/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9627 do not use DOCKER_CONFIG env var to prevent conflicts with Helm
  hack/ci/deploy-dev-asia.sh
  hack/ci/deploy-dev.sh
  hack/ci/deploy.sh
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9621 Allow for longer-running conformance tests
  hack/ci/run-conformance-tests.sh
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9628 Fix for handling of exclude-distribution flag in conformance tests
  cmd/conformance-tester/pkg/types/options.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#9606 [release/v2.20] Update to etcd 3.5.3 for Kubernetes 1.22+
  go.mod
  go.sum
  pkg/resources/etcd/statefulset.go
  pkg/resources/test/fixtures/cronjob-aws-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.22.1-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.22.1-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-etcd.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9593 wait for new cluster objects to appear in cache before attempting to …
  cmd/conformance-tester/pkg/clients/client_kube.go
  pkg/provider/kubernetes/cluster.go
  pkg/resources/reconciling/ensure.go
  pkg/test/e2e/ccm-migration/cluster.go
  pkg/test/e2e/ccm-migration/providers/cluster.go
  pkg/test/e2e/expose-strategy/cluster.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9610 [release/v2.19] Update to etcd 3.5.3 for Kubernetes 1.22+
  go.mod
  go.sum
  pkg/resources/etcd/statefulset.go
  pkg/resources/test/fixtures/cronjob-aws-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.22.1-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.22.1-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-etcd.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9611 [release/v2.18] Update to etcd 3.5.3 for Kubernetes 1.22+
  pkg/resources/etcd/statefulset.go
  pkg/resources/test/fixtures/cronjob-aws-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.22.1-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.22.1-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-apiserver-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-etcd.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#9632 [release/v2.19] fix NodeFilesystem alert rules (#9592)
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/rules/general-node-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/node-exporter.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management

#9644 Update nginx to 1.1.3
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/requirements.lock
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#9635 cleanup usersshkey synchronizer code a bit
  cmd/master-controller-manager/controllers.go
  pkg/controller/master-controller-manager/usersshkey-synchronizer/controller.go
  pkg/controller/master-controller-manager/usersshkey-synchronizer/controller_test.go
  pkg/controller/master-controller-manager/usersshkey-synchronizer/doc.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#9638 Update blackbox-exporter to 0.20.0
  charts/monitoring/blackbox-exporter/Chart.yaml
  charts/monitoring/blackbox-exporter/templates/deployment.yaml
  charts/monitoring/blackbox-exporter/values.yaml
Labels: size/S, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/app-management

#9640 Update node-exporter to 1.3.1
  charts/monitoring/node-exporter/Chart.yaml
  charts/monitoring/node-exporter/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#9636 Update Alertmanager to 0.24.0
  charts/monitoring/alertmanager/Chart.yaml
  charts/monitoring/alertmanager/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#9642 Update Helm-Exporter to 1.2.2
  charts/monitoring/helm-exporter/Chart.yaml
  charts/monitoring/helm-exporter/templates/deployment.yaml
  charts/monitoring/helm-exporter/templates/rbac.yaml
  charts/monitoring/helm-exporter/templates/serviceaccount.yaml
  charts/monitoring/helm-exporter/values.yaml
  charts/monitoring/prometheus/rules/src/general/helm-exporter.yaml
Labels: size/L, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/app-management

#9646 Update oauth2-proxy to 7.2.1
  charts/iap/Chart.yaml
  charts/iap/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#9633 fail etcd restore if etcdLauncher feature not enabled on cluster
  pkg/controller/seed-controller-manager/etcdrestore/etcd_restore_controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#9653 Bump machine-controller to v1.47.0
  docs/zz_generated.seed.yaml
  go.mod
  go.sum
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9649 Include take on KubeApps
  docs/proposals/introduce-apps.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#9641 Update Prometheus to 2.34.0
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/values.yaml
  hack/update-prometheus-rules.sh
  hack/verify-prometheus-rules.sh
  pkg/resources/prometheus/statefulset.go
  pkg/resources/test/fixtures/statefulset-aws-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.21.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.21.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.21.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.23.5-prometheus.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#9662 Add support for prometheus.io/scheme annotation in Prometheus chart
  charts/monitoring/prometheus/config/scraping/pods.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#9601 Add validating webhooks for ApplicationDefinition and ApplicationInstallation
  cmd/kubermatic-webhook/main.go
  cmd/seed-controller-manager/main.go
  cmd/user-cluster-webhook/README.md
  cmd/user-cluster-webhook/main.go
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/applications/installer_test.go
  pkg/controller/operator/common/resources.go
  pkg/controller/operator/common/webhook.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_integration_test.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_test.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/suite_test.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/applications/webhook.go
  pkg/resources/resources.go
  pkg/resources/user-cluster-webhook/deployment.go
  pkg/resources/user-cluster-webhook/rbac.go
  pkg/resources/user-cluster-webhook/service.go
  pkg/resources/webhook/rbac.go
  pkg/validation/applicationdefinition.go
  pkg/validation/applicationdefinition_test.go
  pkg/validation/applicationinstallation.go
  pkg/validation/applicationinstallation_test.go
  pkg/validation/openapi/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/webhook/application/applicationdefinition/validation/validation.go
  pkg/webhook/application/applicationinstallation/validation/validation.go
  pkg/webhook/application/applicationinstallation/validation/validation_test.go
  pkg/webhook/operatingsystemmanager/operatingsystemconfig/validation/validation.go
  pkg/webhook/operatingsystemmanager/operatingsystemprofile/validation/validation.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#9648 Update Loki & promtail to 2.5
  charts/logging/loki/.helmignore
  charts/logging/loki/Chart.yaml
  charts/logging/loki/requirements.lock
  charts/logging/loki/test/default.yaml.out
  charts/logging/loki/test/values.example.ce.yaml.out
  charts/logging/loki/test/values.example.ee.yaml.out
  charts/logging/promtail/.helmignore
  charts/logging/promtail/Chart.yaml
  charts/logging/promtail/charts/promtail-3.11.0.tgz
  charts/logging/promtail/requirements.lock
  charts/logging/promtail/test/default.yaml.out
  charts/logging/promtail/test/kubermatic.example.ce.yaml.out
  charts/logging/promtail/test/kubermatic.example.ee.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#9645 Update cert-manager to 1.8
  charts/cert-manager/Chart.yaml
  charts/cert-manager/crd/cert-manager.crds.yaml
  charts/cert-manager/requirements.lock
  charts/cert-manager/test/default.yaml.out
  charts/cert-manager/test/test-certmanager.sh
  cmd/kubermatic-installer/cmd_deploy.go
  go.mod
  go.sum
  hack/update-cert-manager-crds.sh
  pkg/controller/operator/defaults/defaults.go
  pkg/controller/operator/master/resources/kubermatic/common.go
  pkg/install/stack/kubermatic-master/certmanager.go
Labels: size/XXL, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/cluster-management, sig/app-management

#9647 update kube-state-metrics to 2.4.2
  charts/monitoring/kube-state-metrics/Chart.yaml
  charts/monitoring/kube-state-metrics/values.yaml
  pkg/resources/kubestatemetrics/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-kube-state-metrics.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management

#9643 Update Velero to 1.8.1
  charts/backup/velero/Chart.yaml
  charts/backup/velero/crd/backups.yaml
  charts/backup/velero/crd/backupstoragelocations.yaml
  charts/backup/velero/crd/deletebackuprequests.yaml
  charts/backup/velero/crd/downloadrequests.yaml
  charts/backup/velero/crd/podvolumebackups.yaml
  charts/backup/velero/crd/podvolumerestores.yaml
  charts/backup/velero/crd/resticrepositories.yaml
  charts/backup/velero/crd/restores.yaml
  charts/backup/velero/crd/schedules.yaml
  charts/backup/velero/crd/serverstatusrequests.yaml
  charts/backup/velero/crd/volumesnapshotlocations.yaml
  charts/backup/velero/templates/deployment.yaml
  charts/backup/velero/values.yaml
  hack/update-velero-crds.sh
Labels: size/L, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/app-management

#9667 Fetch dependencies for MLA charts before installing them
  hack/ci/setup-mla.sh
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9674 Don't set '--kubelet-certificate-authority' for 'bring-your-own' user clusters
  pkg/resources/apiserver/deployment.go
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-apiserver.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-apiserver.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9631 [release/v2.18] fix NodeFilesystem alert rules (#9592)
  charts/monitoring/prometheus/Chart.yaml
  charts/monitoring/prometheus/rules/general-node-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/node-exporter.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management

#9651 Add websocket endpoint for terminal
  pkg/handler/middleware/middleware.go
  pkg/handler/routes_v1_websocket.go
  pkg/handler/websocket/terminal.go
  pkg/watcher/types.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#9685 update nginx-ingress to 1.2.0
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#9684 Add ByAnnotation method for predicate utils
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller.go
  pkg/controller/seed-controller-manager/initial-application-installation-controller/doc.go
  pkg/controller/seed-controller-manager/initialmachinedeployment/controller.go
  pkg/controller/util/predicate/predicate.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#9693 revert promtail update
  charts/logging/promtail/.helmignore
  charts/logging/promtail/Chart.yaml
  charts/logging/promtail/test/default.yaml.out
  charts/logging/promtail/test/kubermatic.example.ce.yaml.out
  charts/logging/promtail/test/kubermatic.example.ee.yaml.out
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#9691 remove unused variable from Makefile
  Makefile
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#9600 Recover from PVC deletion in etcd-launcher
  cmd/etcd-launcher/main.go
  pkg/test/e2e/etcd-launcher/etcd_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes

#9679 Do not tag "replicas" field required by swagger as `omitempty`
  pkg/api/v1/types.go
  pkg/handler/v2/cluster_template/cluster_template_test.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/api

#9689 Add changelogs for 2.18.10, 2.19.5 and 2.20.2
  CHANGELOG.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#9690 refactor: remove --debug flag from cortex installation in setup-mla script
  hack/ci/setup-mla.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#9579 Add kubeconfig validation before creating secret
  pkg/handler/test/fake_provider.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/provider/kubernetes/external_cluster.go
  pkg/provider/kubernetes/external_cluster_test.go
  pkg/provider/types.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#9698 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#9650 Machine resource quota webhook
  cmd/user-cluster-webhook/main.go
  pkg/controller/user-cluster-controller-manager/resources/resources/machine/webhook.go
  pkg/ee/validation/machine/fake.go
  pkg/ee/validation/machine/resourcequota.go
  pkg/ee/validation/machine/resourcequota_test.go
  pkg/resources/resources.go
  pkg/webhook/machine/validation/validation.go
  pkg/webhook/machine/validation/wrappers_ce.go
  pkg/webhook/machine/validation/wrappers_ee.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9696 add deployment for WEB terminal tools
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/resources.go
  pkg/resources/test/fixtures/deployment-aws-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-web-terminal.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-web-terminal-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-web-terminal.yaml
  pkg/resources/web-terminal/deployment.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9695 Bump machine-controller to v1.48.0
  go.mod
  go.sum
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#9677 Split Prowjobs for easier maintenance / support Go generics
  .prow.yaml
  .prow/api.yaml
  .prow/ccm-migrations.yaml
  .prow/features.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes

#9701 update golang images used for various scripts
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/gen-api-client.sh
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/update-swagger.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#9699 Introduce configuration_name param to the metering report delete endpoint
  cmd/kubermatic-api/swagger.json
  pkg/ee/metering/report_handler.go
  pkg/test/e2e/utils/apiclient/client/metering/delete_metering_report_parameters.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#9700 KubeVirt cluster update flow: reconcile VirtualMachineInstancePreset
  cmd/conformance-tester/pkg/scenarios/kubevirt.go
  pkg/handler/common/provider/kubevirt.go
  pkg/handler/v2/provider/kubevirt.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/api

#9666 pass ip family info in machine deployment
  pkg/resources/machine/machinedeployment.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#9712 Excluding metering reports from being fetched at the metering pod init
  pkg/ee/metering/deployment.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#9682 update cloud provider dependencies
  go.mod
  go.sum
  pkg/handler/common/provider/anexia.go
  pkg/provider/cloud/anexia/provider.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#9722 Enable leader election for kubermatic-operator chart by default
  charts/kubermatic-operator/templates/deployment.yaml
  charts/kubermatic-operator/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes

#9723 Add ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/config.yml
  hack/verify-boilerplate.sh
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#9730 Add dual-stack support for Canal CNI
  addons/canal/canal_v3.22.yaml
  pkg/validation/cluster.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management

#9727 add make target to render the hubble addon
  addons/Makefile
  addons/hubble/_footer.txt
  addons/hubble/_header.txt
  addons/hubble/hubble.yaml
  addons/values-hubble.yaml
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management
