Repository kubermatic/kubermatic, pull requests merged in 2022-08, with the labels that each got.

#10583 Simplify metallb addon: render only one IPAddressPool for IPAMPool "metallb"
  addons/metallb/01_address-pools.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#10607 Use correct finalizer for cleaning up cluster template credentials
  pkg/controller/master-controller-manager/cluster-template-synchronizer/controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#10604 Remove enforcing of cloud-init for flatcar on AWS
  pkg/resources/machine/common.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#10626 [release/v2.19] Update machine-controller to v1.42.7
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#10592 Add EKS, AKS version and upgrade endpoint
  cmd/kubermatic-api/swagger.json
  pkg/handler/common/provider/aks.go
  pkg/handler/test/fake_provider.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/upgrade.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/cloud/aks/provider.go
  pkg/provider/cloud/eks/provider.go
  pkg/provider/kubernetes/external_cluster.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/client/aks/aks_client.go
  pkg/test/e2e/utils/apiclient/client/aks/list_a_k_s_versions_parameters.go
  pkg/test/e2e/utils/apiclient/client/aks/list_a_k_s_versions_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/eks_client.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_versions_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_versions_responses.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10584 add deletionTimestamp to AppInstall api output
  pkg/handler/v2/application_installation/conversion.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#10591 Check metallb addon in user cluster for IPAM e2e tests
  go.mod
  go.sum
  hack/ci/run-ipam-e2e-tests.sh
  pkg/test/e2e/cilium/cilium_test.go
  pkg/test/e2e/ipam/ipam_test.go
  pkg/test/e2e/jig/cluster.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10605 Add project_info, project_labels and cluster_labels metrics
  cmd/master-controller-manager/main.go
  cmd/seed-controller-manager/main.go
  pkg/collectors/cluster.go
  pkg/collectors/project.go
  pkg/collectors/util.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes

#10634 fix _labels metrics
  pkg/collectors/cluster.go
  pkg/collectors/project.go
  pkg/collectors/util.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#10606 AddonConfig Disable/Enable KKP auto assign IPAddressPool
  .prow/features.yaml
  addons/metallb/01_address-pools.yaml
Labels: kind/bug, priority/high, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#10631 Add comments to default k8s versions
  pkg/controller/operator/defaults/defaults.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10603 Scrape kubelet resources metrics endpoint by default for user clusters
  cmd/conformance-tester/pkg/tests/metrics.go
  pkg/resources/prometheus/configmap.go
  pkg/resources/test/fixtures/configmap-aws-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.22.1-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.23.5-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.23.5-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.24.0-prometheus.yaml
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#10630 Dual-stack e2e tests: Do not pin CNI versions
  pkg/test/dualstack/cloud_providers.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10601 use equal filename for apps
  pkg/validation/application_definition.go
  pkg/validation/application_definition_test.go
  pkg/validation/application_installation.go
  pkg/validation/application_installation_test.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10643 make rbac resources controller not reconcile deleted objects
  pkg/controller/master-controller-manager/rbac/rbac_resource_controller.go
  pkg/controller/master-controller-manager/rbac/sync_resource.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10651 add changelog for 2.19.8
  CHANGELOG.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10649 [release/v2.20] [EE] fix reconcile loop in allowed-registry controller (#10644)
  pkg/ee/allowed-registry-controller/reconcile.go
  pkg/ee/allowed-registry-controller/reconcile_test.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#10653 [release/v2.20] Update ec2-instances-info to 067009cd38ea
  go.mod
  go.sum
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes

#10652 [release/v2.20] fix etcdbackup controller constantly updating the EtcdBackup status (#10650)
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management

#10658 add changelog for 2.20.6
  CHANGELOG.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10577 Inject BUILD_ID and test name into cluster names again
  .prow/ccm-migrations.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  cmd/conformance-tester/pkg/runner/runner.go
  cmd/etcd-launcher/main.go
  hack/ci/run-conformance-tests.sh
  pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller.go
  pkg/controller/seed-controller-manager/cluster-credentials-controller/controller.go
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/controller/seed-controller-manager/mla/alertmanager_controller.go
  pkg/controller/seed-controller-manager/pvwatcher/pvwatcher_controller.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/util/util.go
  pkg/provider/kubernetes/util.go
  pkg/resources/credentials.go
  pkg/resources/etcd/statefulset.go
  pkg/resources/etcd/statefulset_test.go
  pkg/resources/etcd/testdata/etcd-command-with-launcher.golden.sh
  pkg/test/e2e/cilium/cilium_test.go
  pkg/test/e2e/etcd-launcher/etcd_test.go
  pkg/test/e2e/expose-strategy/tunneling_test.go
  pkg/test/e2e/ipam/ipam_test.go
  pkg/test/e2e/jig/cluster.go
  pkg/test/e2e/jig/flags.go
  pkg/test/e2e/jig/presets.go
  pkg/test/e2e/konnectivity/konnectivity_test.go
  pkg/test/e2e/mla/mla_test.go
  pkg/test/e2e/opa/opa_test.go
  pkg/validation/cluster.go
  pkg/webhook/addon/mutation/mutation.go
  pkg/webhook/cluster/validation/validation.go
  pkg/webhook/mlaadminsetting/mutation/mutation.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#10627 Use reconciling framework to manage the credentials secret
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/provider/kubernetes/credentials.go
  pkg/provider/kubernetes/external_cluster.go
  pkg/provider/kubernetes/external_cluster_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10641 handle conflicts in cluster/project labels
  pkg/collectors/cluster.go
  pkg/collectors/project.go
  pkg/collectors/util.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#10671 fix log line in MLA controller
  pkg/controller/seed-controller-manager/mla/alertmanager_controller.go
  pkg/controller/seed-controller-manager/mla/cleanup_controller.go
  pkg/controller/seed-controller-manager/mla/dashboard_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/org_user_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/ratelimit_cortex_controller.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller.go
  pkg/controller/seed-controller-manager/mla/rulegroup_sync_controller.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#10595 event handling for 404 and 403 errorcodes
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/external_cluster/node.go
  pkg/handler/v2/external_cluster/upgrade.go
  pkg/provider/cloud/aks/provider.go
  pkg/provider/cloud/eks/provider.go
  pkg/provider/cloud/gke/provider.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10660 applicationInstallationController: fix infinite reconciling loop
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#10683 Add support for amazon linux 2
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/controller/user-cluster-controller-manager/node-labeler/api/api.go
  pkg/machine/convert.go
  pkg/resources/machine/common.go
  pkg/resources/machine/machinedeployment.go
  pkg/test/e2e/jig/machine.go
  pkg/test/e2e/utils/apiclient/models/amazon_linux_spec.go
  pkg/test/e2e/utils/apiclient/models/operating_system_spec.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10672 fix apiserer typo
  pkg/controller/seed-controller-manager/update-controller/controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10682 applicationInstallationController: update status.HelmRelease even if an error occurred
  pkg/applications/fake/fake_installer.go
  pkg/applications/installer.go
  pkg/applications/providers/template/helm.go
  pkg/applications/providers/util/util.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#10688 fix missing Registry overwrite in Canal 3.23 addon
  addons/canal/canal_v3.23.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#10680 Update docs URL to use new pattern
  charts/monitoring/prometheus/rules/general-blackbox-exporter.yaml
  charts/monitoring/prometheus/rules/general-cadvisor.yaml
  charts/monitoring/prometheus/rules/general-cert-manager.yaml
  charts/monitoring/prometheus/rules/general-helm-exporter.yaml
  charts/monitoring/prometheus/rules/general-kube-apiserver.yaml
  charts/monitoring/prometheus/rules/general-kube-kubelet.yaml
  charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/general-node-exporter.yaml
  charts/monitoring/prometheus/rules/general-prometheus.yaml
  charts/monitoring/prometheus/rules/general-thanos.yaml
  charts/monitoring/prometheus/rules/general-velero.yaml
  charts/monitoring/prometheus/rules/kubermatic-master-kubermatic.yaml
  charts/monitoring/prometheus/rules/kubermatic-seed-kubermatic.yaml
  charts/monitoring/prometheus/rules/managed-kube-controller-manager.yaml
  charts/monitoring/prometheus/rules/managed-kube-scheduler.yaml
  charts/monitoring/prometheus/rules/src/general/blackbox-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/cadvisor.yaml
  charts/monitoring/prometheus/rules/src/general/cert-manager.yaml
  charts/monitoring/prometheus/rules/src/general/helm-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/kube-apiserver.yaml
  charts/monitoring/prometheus/rules/src/general/kube-kubelet.yaml
  charts/monitoring/prometheus/rules/src/general/kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/src/general/node-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/prometheus.yaml
  charts/monitoring/prometheus/rules/src/general/thanos.yaml
  charts/monitoring/prometheus/rules/src/general/velero.yaml
  charts/monitoring/prometheus/rules/src/kubermatic-master/kubermatic.yaml
  charts/monitoring/prometheus/rules/src/kubermatic-seed/kubermatic.yaml
  charts/monitoring/prometheus/rules/src/managed/kube-controller-manager.yaml
  charts/monitoring/prometheus/rules/src/managed/kube-scheduler.yaml
  charts/monitoring/prometheus/rules/src/usercluster-mla/cortex.yaml
  charts/monitoring/prometheus/rules/src/usercluster-mla/loki-distributed.yaml
  charts/monitoring/prometheus/rules/usercluster-mla-cortex.yaml
  charts/monitoring/prometheus/rules/usercluster-mla-loki-distributed.yaml
  charts/values.example.ce.yaml
  charts/values.example.ee.yaml
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#10687 fix kc-status controller flipping the variables
  pkg/controller/master-controller-manager/kc-status-controller/controller.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10625 Add projectId suffix to binding subjects
  pkg/ee/group-project-binding/controller/reconciler_test.go
  pkg/ee/group-project-binding/controller/resources.go
  pkg/provider/kubernetes/member.go
  pkg/provider/kubernetes/util_test.go
  pkg/provider/types.go
  pkg/provider/userinfo.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#10689 pull konnectivity images only if not present
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/deployment.go
  pkg/resources/konnectivity/sidecar.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10662 Applications fix panic in HelmClient.DonwloadChart when version is empty or non semver
  pkg/applications/helmclient/client.go
  pkg/applications/helmclient/client_test.go
  pkg/applications/helmclient/testdata/examplechart-v2/.helmignore
  pkg/applications/helmclient/testdata/examplechart-v2/Chart.yaml
  pkg/applications/helmclient/testdata/examplechart-v2/templates/configmap.yaml
  pkg/applications/helmclient/testdata/examplechart-v2/values.yaml
  pkg/applications/providers/source/helm.go
  pkg/applications/providers/template/helm.go
  pkg/applications/providers/util/util.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management

#10675 Unified PR template update
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes

#10694 installer: add missing migration of applicationInstallation crd
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/util/crd.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10703 Use reconciling framework for addons
  codegen/reconcile/main.go
  pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: kind/cleanup, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10715 allow to remove the unused UID in addon cluster references
  pkg/webhook/addon/mutation/mutation.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10717 Allow proxy mode change by CNI migration
  pkg/validation/cluster.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10714 Include OS and supported cloud provider names in response for listing OperatingSystemProfiles
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/v2/operatingsystemprofile/operatingsystemprofile.go
  pkg/handler/v2/operatingsystemprofile/operatingsystemprofile_test.go
  pkg/test/e2e/utils/apiclient/models/operating_system_profile.go
Labels: kind/feature, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10720 Upgrade gimps to 0.5.0
  hack/verify-import-order.sh
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10708 delete minor unreachable code caused by t.Fatal
  pkg/controller/master-controller-manager/rbac/sync_project_test.go
Labels: kind/cleanup, ok-to-test, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10709 Allow passing optional features to conformance-tester and delete project
  cmd/conformance-tester/main.go
  cmd/conformance-tester/pkg/clients/client.go
  cmd/conformance-tester/pkg/clients/client_api.go
  cmd/conformance-tester/pkg/clients/client_kube.go
  cmd/conformance-tester/pkg/runner/runner.go
  cmd/conformance-tester/pkg/scenarios/base.go
  cmd/conformance-tester/pkg/scenarios/generator.go
  cmd/conformance-tester/pkg/types/options.go
Labels: kind/feature, size/L, lgtm, approved, release-note-none, dco-signoff: yes

#10736 fix external cluster metrics for clusters without CloudSpec
  pkg/collectors/external_cluster.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10731 expose KubeVirt Pre-Allocated Data Volume in the cluster API
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/test/e2e/utils/apiclient/models/public_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/public_kubevirt_cloud_spec.go
Labels: kind/feature, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10738 Fix CRD version comparison in KKP Operator
  pkg/controller/operator/common/resources.go
  pkg/controller/operator/common/resources_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10737 prevent accidental invalid config files in installer
  cmd/kubermatic-installer/shared.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management

#10723 KubeVirt Fix DataVolume usage at cluster creation time
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/resources/machine/common.go
  pkg/resources/machine/common_test.go
  pkg/resources/machine/machinedeployment.go
  pkg/test/e2e/utils/apiclient/models/kubevirt_node_spec.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, sig/virtualization

#10741 Add setup_mode=kube for ubuntu KubeVirt tests
  .prow/provider-kubevirt.yaml
Labels: kind/bug, kind/failing-test, lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10691 applicationDefinition: remove .spec.versions[].template.constraints
  cmd/kubermatic-api/swagger.json
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/apis/apps.kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/master-controller-manager/application-definition-synchronizer/controller_test.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_integration_test.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_test.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/test/e2e/utils/apiclient/models/application_constraints.go
  pkg/test/e2e/utils/apiclient/models/application_version.go
  pkg/test/e2e/utils/apiclient/models/version_constraints.go
  pkg/validation/application_definition.go
  pkg/validation/application_definition_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, sig/api

#10749 fix gimps download
  hack/verify-import-order.sh
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10754 fix NPE for external clusters
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#10758 update e2e test logic to handle secrets that are not pre-base64-encoded
  cmd/conformance-tester/pkg/scenarios/google.go
  cmd/conformance-tester/pkg/scenarios/kubevirt.go
  cmd/conformance-tester/pkg/types/secrets.go
  pkg/test/dualstack/cloud_providers.go
  pkg/test/helper.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note-none, dco-signoff: yes

#10760 [release/v2.20] update e2e test logic to handle secrets that are not pre-base64-encoded (#10758)
  cmd/conformance-tests/main.go
  cmd/conformance-tests/scenarios_gcp.go
  cmd/conformance-tests/scenarios_kubevirt.go
  pkg/test/helper.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note-none, dco-signoff: yes

#10761 [release/v2.19] update e2e test logic to handle secrets that are not pre-base64-encoded (#10758)
  cmd/conformance-tests/main.go
  cmd/conformance-tests/scenarios_gcp.go
  cmd/conformance-tests/scenarios_kubevirt.go
  pkg/test/helper.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note-none, dco-signoff: yes

#10702 improve event handling in external cluster controller, use reconciling framework for kubeconfig secrets
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/controller/master-controller-manager/external-cluster/cluster_controller_test.go
Labels: kind/cleanup, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10707 Use reconciling framework in more places
  pkg/controller/master-controller-manager/kubeone/controller.go
  pkg/handler/v1/admin/seed_test.go
  pkg/provider/kubernetes/seed.go
Labels: kind/cleanup, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10763 Allow rendering dual-stack IPAddressPool in metallb addon
  addons/metallb/01_address-pools.yaml
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#10764 Fix GCE tests
  cmd/kubermatic-api/swagger.json
  hack/ci/run-api-e2e.sh
  hack/ci/run-conformance-tests.sh
  hack/ci/run-dualstack-e2e-test.sh
  hack/lib.sh
  hack/local/run-api-e2e.sh
  hack/run-conformance-tests.sh
  pkg/apis/kubermatic/v1/cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/test/e2e/utils/apiclient/models/g_c_p_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/kubevirt_cloud_spec.go
  pkg/test/helper.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10751 Add EnableIngressHostname and IngressHostnameSuffix options to Openstack cloud spec
  .golangci.yml
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/resources/cloudconfig/configmap.go
  pkg/resources/cloudconfig/openstack/cloudconfig.go
  pkg/test/e2e/utils/apiclient/models/openstack_cloud_spec.go
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10753 Ship default AddonConfigs with KKP
  codegen/reconcile/main.go
  pkg/controller/operator/master/controller.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/master/resources/kubermatic/addonconfigs.go
  pkg/controller/operator/master/resources/kubermatic/static/kube-state-metrics.svg
  pkg/controller/operator/master/resources/kubermatic/static/kubeflow.svg
  pkg/controller/operator/master/resources/kubermatic/static/kubevirt.svg
  pkg/controller/operator/master/resources/kubermatic/static/multus.svg
  pkg/controller/operator/master/resources/kubermatic/static/node-exporter.svg
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: kind/feature, size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#10756 Use rfc1035 for metering report name validation
  pkg/ee/metering/report_config_handler.go
  pkg/ee/metering/report_config_handler_test.go
  pkg/validation/metering.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10767 add retries to cleanup project/cluster in dualstack e2e test
  pkg/test/dualstack/cloud_providers_dualstack_test.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10730 Allow admin user to list project's group bindings
  pkg/ee/group-project-binding/provider/provider.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10744 Add GKE endpoints for sizes and disktypes
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/common/provider/eks.go
  pkg/handler/common/provider/gcp.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/cloud/gke/provider.go
  pkg/test/e2e/utils/apiclient/client/eks/eks_client.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_security_groups_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_subnets_no_credentials_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_subnets_responses.go
  pkg/test/e2e/utils/apiclient/client/gke/gke_client.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_disk_types_parameters.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_disk_types_responses.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_vm_sizes_parameters.go
  pkg/test/e2e/utils/apiclient/client/gke/list_g_k_e_vm_sizes_responses.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_security_group.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_security_group_id.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_security_group_id_list.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_security_group_list.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_subnet.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_subnet_id.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_subnet_id_list.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_subnet_list.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_disk_type.go
  pkg/test/e2e/utils/apiclient/models/g_k_e_disk_type_list.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10729 Add ClusterRole for listing namespaces in RBAC addon
  addons/rbac/list-namespaces.yaml
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management

#10774 Stabilize API e2e Tests
  pkg/test/e2e/api/util.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note-none, dco-signoff: yes

#10762 Introduce ExternalClusterBringYourOwnProvider, make CloudSpec non-nil
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/apis/kubermatic/v1/external_cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/collectors/external_cluster.go
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/controller/master-controller-manager/external-cluster/cluster_controller_test.go
  pkg/controller/master-controller-manager/kubeone/controller.go
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  pkg/defaulting/externalcluster.go
  pkg/handler/common/provider/aks.go
  pkg/handler/common/provider/eks.go
  pkg/handler/v2/external_cluster/aks.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/handler/v2/external_cluster/gke.go
  pkg/handler/v2/external_cluster/kubeone.go
  pkg/handler/v2/external_cluster/node.go
  pkg/install/stack/kubermatic-master/migrations.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/provider/cloud/gke/provider.go
  pkg/provider/types.go
  pkg/test/e2e/utils/apiclient/models/bring_your_own_spec.go
  pkg/test/e2e/utils/apiclient/models/external_cluster_cloud_spec.go
Labels: kind/cleanup, size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10721 Update metering to version 1.0
  cmd/kubermatic-api/swagger.json
  docs/zz_generated.seed.yaml
  hack/ci/testdata/seed.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/operator/seed/reconciler_ee_test.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/ee/metering/cronjob.go
  pkg/ee/metering/deployment.go
  pkg/ee/metering/handler.go
  pkg/ee/metering/prometheus/clusterole.go
  pkg/ee/metering/prometheus/clusterrolebinding.go
  pkg/ee/metering/prometheus/configmap.go
  pkg/ee/metering/prometheus/reconcile.go
  pkg/ee/metering/prometheus/serviceaccount.go
  pkg/ee/metering/prometheus/sts.go
  pkg/ee/metering/prometheus/svc.go
  pkg/ee/metering/pvc.go
  pkg/ee/metering/reconcile.go
  pkg/test/e2e/utils/apiclient/models/metering_configuration.go
  pkg/test/e2e/utils/apiclient/models/metering_report_configuration.go
  pkg/validation/metering.go
Labels: kind/feature, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api

#10779 Fix metering prometheus pvc volume usage
  pkg/ee/metering/prometheus/sts.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10777 Add AddonConfig for Hubble
  pkg/controller/operator/master/resources/kubermatic/addonconfigs.go
  pkg/controller/operator/master/resources/kubermatic/static/hubble.png
Labels: kind/feature, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10780 Add update as a verb to OSM role
  pkg/controller/user-cluster-controller-manager/resources/resources/operating-system-manager/role.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10784 Remove report prefix from metering listing in api
  pkg/ee/metering/report_handler.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10771 Disable vsphere improved-csi-idempotency
  addons/csi/vsphere/vsphere-csi-driver.yaml
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#10783 Rollback kubeconfig base64 encoding for KubeVirt functional tests
  cmd/conformance-tester/pkg/scenarios/kubevirt.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10775 fix kubevirt resource quota with vmipreset
  pkg/ee/validation/machine/providers.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10790 [release/v2.20] Fix image registry address for KubeVirt CI tests
  cmd/conformance-tests/scenarios_kubevirt.go
Labels: kind/cleanup, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#10789 [release/v2.19] Fix image registry address for KubeVirt CI tests
  cmd/conformance-tests/scenarios_kubevirt.go
Labels: kind/cleanup, lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10797 temporarily make installer setup CRDs again
  pkg/controller/master-controller-manager/seed-sync/reconciler.go
  pkg/install/stack/kubermatic-seed/stack.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10791 Fix metering reconcile
  hack/ci/setup-kubermatic-in-kind.sh
  hack/ci/testdata/metering_s3_creds.yaml
  hack/ci/testdata/seed.yaml
  pkg/ee/metering/prometheus/sts.go
  pkg/ee/metering/prometheus/svc.go
  pkg/ee/metering/reconcile.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10776 change smoketest to use AWS+ubuntu
  .prow/features.yaml
  hack/ci/run-dualstack-e2e-test.sh
  pkg/test/dualstack/cloud_providers_dualstack_test.go
  pkg/test/dualstack/dualstack_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10799 Metering: use reconciling framework, use seedsGetter more consistently
  pkg/ee/metering/handler.go
  pkg/ee/metering/reconcile.go
  pkg/ee/metering/report_config_handler.go
  pkg/ee/metering/report_handler.go
  pkg/handler/routes_v1_admin.go
  pkg/handler/v1/admin/metering.go
  pkg/handler/v1/admin/wrappers_ce.go
  pkg/handler/v1/admin/wrappers_ee.go
Labels: kind/cleanup, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10798 Update seed configs for vSphere DC
  hack/ci/testdata/seed.yaml
Labels: kind/failing-test, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10794 applicationDefinition: add defaultValues
  cmd/kubermatic-api/swagger.json
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/apis/apps.kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_integration_test.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_test.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/test/e2e/utils/apiclient/models/application_definition_spec.go
  pkg/test/e2e/utils/apiclient/models/application_template.go
  pkg/test/e2e/utils/apiclient/models/form_field.go
  pkg/test/e2e/utils/apiclient/models/form_field_type.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, sig/api

#10802 fix timing for OSM upgrade during KKP upgrade
  pkg/controller/operator/seed/reconciler.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10801 Set correct prefix for report listing
  pkg/ee/metering/report_handler.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10803 don't spam misleading errors during upgrade
  pkg/controller/seed-controller-manager/update-controller/controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10800 Check that backup destination has credentials set
  pkg/collectors/clusterbackup.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10805 Allow admin management to GroupProjectBindings
  pkg/ee/group-project-binding/handler/handler.go
  pkg/ee/group-project-binding/handler/handler_test.go
  pkg/ee/group-project-binding/provider/provider.go
Labels: kind/bug, size/L, lgtm, approved, release-note-none, dco-signoff: yes

#10806 Bug fix for custom and aks cluster
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
  pkg/handler/v2/external_cluster/external_cluster.go
  pkg/handler/v2/external_cluster/external_cluster_test.go
  pkg/handler/v2/external_cluster/upgrade.go
  pkg/provider/cloud/aks/provider.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10810 fix externalcluster deletion bug
  pkg/controller/master-controller-manager/external-cluster/cluster_controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/api

#10809 Skip IPv6 node addresses in DNAT controller
  pkg/controller/kubeletdnat-controller/controller.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10793 [release/v2.19] Disable vsphere improved-csi-idempotency
  addons/csi/vsphere/vsphere-csi-driver.yaml
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#10792 [release/v2.20] Disable vsphere improved-csi-idempotency
  addons/csi/vsphere/vsphere-csi-driver.yaml
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management

#10765 [release/v2.20] Fix GCE tests (#10764)
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  cmd/kubermatic-api/swagger.json
  hack/ci/run-api-e2e.sh
  hack/ci/run-conformance-tests.sh
  hack/lib.sh
  hack/local/run-api-e2e.sh
  hack/run-conformance-tests.sh
  pkg/apis/kubermatic/v1/cluster.go
  pkg/test/e2e/utils/apiclient/models/g_c_p_cloud_spec.go
  pkg/test/e2e/utils/apiclient/models/kubevirt_cloud_spec.go
  pkg/test/helper.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#10766 [release/v2.19] Fix GCE tests (#10764)
  charts/kubermatic-operator/Chart.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  charts/kubermatic-operator/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  hack/ci/run-api-e2e.sh
  hack/ci/run-conformance-tests.sh
  hack/lib.sh
  hack/local/run-api-e2e.sh
  hack/run-conformance-tests.sh
  pkg/apis/kubermatic/v1/cluster.go
  pkg/test/helper.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api, sig/crd

#10811 sync enumerations with Go constants
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/apis/kubermatic/v1/configuration.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, sig/app-management

#10818 fix auto-update rule
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/defaults/defaults.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, kind/regression

#10678 Match public IP address SKU to load balancer SKU for Azure
  cmd/conformance-tester/pkg/scenarios/azure.go
  go.mod
  go.sum
  pkg/resources/machine/common.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#10819 Include Equinix Metal as an alias for Packet to machine resource calculation
  pkg/ee/validation/machine/providers.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10820 Delete cluster webhook before running migrations for OSM
  pkg/controller/operator/seed/reconciler.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10822 Add NetworkPolicy from UserCluster apiserver to the webhook
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/apiserver/networkpolicy.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10824 installer: add missing migration of applicationDefinition
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/util/migrations.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10781 Do not install gimps. Only tell the user to install it.
  hack/verify-import-order.sh
Labels: kind/feature, size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10826 changed failure policy for machine validating webhook to fail
  pkg/controller/user-cluster-controller-manager/resources/resources/machine/webhook.go
Labels: kind/bug, kind/cleanup, lgtm, approved, release-note-none

#10827 Rename usercluster-webhook network policy
  pkg/resources/apiserver/networkpolicy.go
  pkg/resources/resources.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10821 Fix AWS node-termination-handler addon upgrade
  pkg/controller/operator/master/resources/kubermatic/common.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/resources/resources.go
  pkg/webhook/cluster/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutation_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/regression

#10823 Add unit tests to ensure configured versions are coherent
  pkg/controller/operator/defaults/defaults_integration_test.go
  pkg/controller/operator/defaults/defaults_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10828 fixed disk storage calculation for vSphere
  pkg/ee/validation/machine/providers.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10835 Fix API response for rockylinux OS
  cmd/conformance-tester/pkg/scenarios/base.go
  cmd/kubermatic-api/swagger.json
  pkg/api/v1/types.go
  pkg/test/dualstack/cloud_providers.go
  pkg/test/e2e/utils/apiclient/models/operating_system_spec.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#10830 Correctly match Rocky Linux image for node OS label
  pkg/controller/user-cluster-controller-manager/node-labeler/api/api.go
  pkg/controller/user-cluster-controller-manager/node-labeler/controller.go
  pkg/controller/user-cluster-controller-manager/node-labeler/controller_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10832 Allow admins to interact with application installations
  pkg/handler/v2/application_installation/application_installation.go
  pkg/handler/v2/routes_v2.go
  pkg/provider/kubernetes/cluster.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#10807 add user-cluster rbac for applicationinstallations
  pkg/controller/user-cluster-controller-manager/rbac/resources.go
  pkg/controller/user-cluster-controller-manager/rbac/resources_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management

#10838 Lowered default node count setting
  pkg/handler/v1/admin/settings_test.go
  pkg/provider/kubernetes/settings.go
  pkg/test/e2e/api/settings_test.go
Labels: kind/cleanup, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/api

#10848 Fix for Equinix Metal cloud provider resource usage memory calculation
  pkg/ee/validation/machine/providers.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10855 include rarecase for gke ReleaseChannel
  pkg/provider/cloud/gke/provider.go
  pkg/resources/resources.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10857 Fix zero defaulting issue for ResourceQuotas
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/ee/resource-quota/handler.go
  pkg/ee/resource-quota/handler_test.go
  pkg/handler/v2/resource_quota/resourequota.go
  pkg/handler/v2/resource_quota/wrappers_ce.go
  pkg/handler/v2/resource_quota/wrappers_ee.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/resource_quota/put_resource_quota_parameters.go
  pkg/test/e2e/utils/apiclient/client/resource_quota/put_resource_quota_responses.go
  pkg/test/e2e/utils/apiclient/client/resource_quota/resource_quota_client.go
Labels: kind/bug, size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10858 application: gitSource, avoid confusing message if git remote is using file protocol
  pkg/applications/providers/source/git.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#10859 fix redirectURI being set for whole kubermatic-api instead of being used dynamically
  pkg/handler/auth/oidc.go
  pkg/handler/common/kubeconfig.go
  pkg/handler/test/fake_auth.go
  pkg/handler/v2/kubernetes-dashboard/login.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api

#10862 log only name of encryption key
  pkg/validation/cluster.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10863 Update application crd documentation
  cmd/kubermatic-api/swagger.json
  codegen/example-yaml/main.go
  docs/zz_generated.applicationDefinition.yaml
  docs/zz_generated.applicationInstallation.yaml
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/test/e2e/utils/apiclient/models/application_definition_spec.go
  pkg/test/e2e/utils/apiclient/models/application_version.go
  pkg/test/e2e/utils/apiclient/models/git_source.go
  pkg/test/e2e/utils/apiclient/models/helm_source.go
Labels: kind/documentation, size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, sig/api

#10865 Remove unused resource quota patch
  cmd/kubermatic-api/swagger.json
  pkg/ee/resource-quota/handler.go
  pkg/ee/resource-quota/handler_test.go
  pkg/handler/v2/resource_quota/wrappers_ce.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/resource_quota/patch_resource_quota_parameters.go
  pkg/test/e2e/utils/apiclient/client/resource_quota/patch_resource_quota_responses.go
  pkg/test/e2e/utils/apiclient/client/resource_quota/resource_quota_client.go
Labels: kind/bug, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10870 fix resource quota controller equality checks
  pkg/ee/resource-quota/master-controller/controller.go
  pkg/ee/resource-quota/seed-controller/controller.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes

#10868 applications: add crd example to docs repository
  hack/ci/update-docs.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10864 Remove placeholder message from encryptionConfiguration
  pkg/apis/kubermatic/v1/cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
Labels: kind/cleanup, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management

#10878 Add semVer validation for AppDefs
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management

#10880 Re-add Azure CSI migration flags removed in CCM migration PR
  pkg/resources/data.go
  pkg/resources/test/fixtures/deployment-azure-1.23.5-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-apiserver.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-controller-manager.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-operating-system-manager.yaml
Labels: kind/bug, size/S, priority/critical-urgent, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/regression

#10879 Add more doc comments for CRDs
  cmd/kubermatic-api/swagger.json
  pkg/apis/kubermatic/v1/addon.go
  pkg/apis/kubermatic/v1/addon_config.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/apis/kubermatic/v1/project.go
  pkg/apis/kubermatic/v1/settings.go
  pkg/apis/kubermatic/v1/sshkeys.go
  pkg/apis/kubermatic/v1/user.go
  pkg/apis/kubermatic/v1/user_project_binding.go
  pkg/crd/k8c.io/kubermatic.k8c.io_addonconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_addons.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_projects.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_userprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_users.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_usersshkeys.yaml
  pkg/test/e2e/utils/apiclient/models/a_k_s.go
  pkg/test/e2e/utils/apiclient/models/a_w_s.go
  pkg/test/e2e/utils/apiclient/models/alibaba.go
  pkg/test/e2e/utils/apiclient/models/anexia.go
  pkg/test/e2e/utils/apiclient/models/azure.go
  pkg/test/e2e/utils/apiclient/models/cleanup_options.go
  pkg/test/e2e/utils/apiclient/models/digitalocean.go
  pkg/test/e2e/utils/apiclient/models/e_k_s.go
  pkg/test/e2e/utils/apiclient/models/fake.go
  pkg/test/e2e/utils/apiclient/models/g_c_p.go
  pkg/test/e2e/utils/apiclient/models/g_k_e.go
  pkg/test/e2e/utils/apiclient/models/hetzner.go
  pkg/test/e2e/utils/apiclient/models/kubevirt.go
  pkg/test/e2e/utils/apiclient/models/nutanix.go
  pkg/test/e2e/utils/apiclient/models/openstack.go
  pkg/test/e2e/utils/apiclient/models/packet.go
  pkg/test/e2e/utils/apiclient/models/preset_spec.go
  pkg/test/e2e/utils/apiclient/models/provider_preset.go
  pkg/test/e2e/utils/apiclient/models/setting_spec.go
  pkg/test/e2e/utils/apiclient/models/v_mware_cloud_director.go
  pkg/test/e2e/utils/apiclient/models/v_sphere.go
Labels: kind/documentation, size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/api

#10849 KubeVirt: do not reconcile the namespace if the name is empty
  pkg/provider/cloud/kubevirt/provider.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, sig/virtualization

#10725 Add changelog for 2.21.0
  CHANGELOG.md
  docs/changelogs/CHANGELOG-2.10.md
  docs/changelogs/CHANGELOG-2.11.md
  docs/changelogs/CHANGELOG-2.12.md
  docs/changelogs/CHANGELOG-2.13.md
  docs/changelogs/CHANGELOG-2.14.md
  docs/changelogs/CHANGELOG-2.15.md
  docs/changelogs/CHANGELOG-2.16.md
  docs/changelogs/CHANGELOG-2.17.md
  docs/changelogs/CHANGELOG-2.18.md
  docs/changelogs/CHANGELOG-2.19.md
  docs/changelogs/CHANGELOG-2.20.md
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.6.md
  docs/changelogs/CHANGELOG-2.7.md
  docs/changelogs/CHANGELOG-2.8.md
  docs/changelogs/CHANGELOG-2.9.md
  docs/changelogs/README.md
Labels: kind/documentation, size/XXL, lgtm, approved, release-note-none, dco-signoff: yes

#10795 Improve Seed cluster initialization, add ClusterInitialized condition
  cmd/kubermatic-operator/main.go
  hack/ci/setup-kubermatic-backups-in-kind.sh
  hack/ci/setup-kubermatic-in-kind.sh
  hack/ci/setup-kubermatic-mla-in-kind.sh
  hack/lib.sh
  hack/local/run-kubermatic-kind.sh
  hack/run-expose-strategy-e2e-test-in-kind.sh
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/controller/master-controller-manager/seed-proxy/reconciler.go
  pkg/controller/master-controller-manager/seed-status-controller/reconciler.go
  pkg/controller/master-controller-manager/seed-sync/reconciler.go
  pkg/controller/operator/defaults/defaults.go
  pkg/controller/operator/master/controller.go
  pkg/controller/operator/seed-init/controller.go
  pkg/controller/operator/seed-init/doc.go
  pkg/controller/operator/seed-init/reconciler.go
  pkg/controller/operator/seed/controller.go
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/operator/seed/reconciler_test.go
  pkg/controller/shared/seed-controller-lifecycle/seed_controller_lifecycle.go
  pkg/install/stack/kubermatic-seed/stack.go
  pkg/provider/configuration.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#10887 Remove legacy metering cleanup
  pkg/ee/metering/reconcile.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note-none, dco-signoff: yes

#10808 replace deprecated topology-zone label
  pkg/resources/antiaffinity.go
  pkg/resources/resources.go
Labels: kind/cleanup, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/deprecation

#10812 add info that release notes are being used for Changelog
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/documentation, lgtm, approved, release-note-none, size/XS, dco-signoff: yes

#10895 Fix flakiness documentation generation
  cmd/kubermatic-api/swagger.json
  codegen/example-yaml/main.go
  docs/zz_generated.applicationInstallation.yaml
  pkg/api/v2/types.go
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/apis/apps.kubermatic/v1/zz_generated.deepcopy.go
  pkg/applications/installer_test.go
  pkg/applications/providers/template/helm_integration_test.go
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_test.go
  pkg/handler/test/helper.go
  pkg/handler/v2/application_installation/application_installation_test.go
  pkg/handler/v2/application_installation/conversion.go
  pkg/validation/application_installation_test.go
  pkg/webhook/application/applicationinstallation/validation/validation_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api

#10700 Update supported operating systems for dualstack
  .prow/features.yaml
  hack/ci/run-dualstack-e2e-test.sh
  hack/ci/testdata/seed.yaml
  pkg/test/dualstack/cloud_providers.go
  pkg/test/dualstack/cloud_providers_dualstack_test.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#10778 List eks cluster service roles
  cmd/kubermatic-api/swagger.json
  pkg/api/v2/types.go
  pkg/handler/common/provider/eks.go
  pkg/handler/v2/external_cluster/eks.go
  pkg/handler/v2/routes_v2.go
  pkg/test/e2e/utils/apiclient/client/eks/eks_client.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_cluster_roles_parameters.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_cluster_roles_responses.go
  pkg/test/e2e/utils/apiclient/client/eks/list_e_k_s_regions_responses.go
  pkg/test/e2e/utils/apiclient/client/packet/list_packet_sizes_no_credentials_v2_responses.go
  pkg/test/e2e/utils/apiclient/client/vsphere/list_v_sphere_datastores_responses.go
  pkg/test/e2e/utils/apiclient/models/e_k_s_cluster_roles_list.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/api

#10904 use Nuremburg datacenter for Hetzner-based e2e tests
  hack/ci/run-ipam-e2e-tests.sh
  hack/ci/run-mla-e2e-tests.sh
  hack/ci/run-opa-e2e-tests.sh
  pkg/test/e2e/api/hetzner_test.go
Labels: size/S, kind/failing-test, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management

#10903 Do not install all CRDs into all cluster kinds
  hack/update-codegen.sh
  pkg/controller/operator/seed-init/reconciler.go
  pkg/controller/operator/seed/reconciler.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_addonconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_addons.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_admissionplugins.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_alertmanagers.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_allowedregistries.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplateinstances.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_constraints.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_constrainttemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdbackupconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdrestores.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_groupprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipamallocations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipampools.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_mlaadminsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_projects.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_resourcequotas.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_rulegroups.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_userprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_users.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_usersshkeys.yaml
  pkg/install/stack/kubermatic-master/certmanager.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/util/crd.go
  pkg/util/crd/crd.go
Labels: kind/bug, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management
