Repository kubermatic/kubermatic, pull requests merged in 2023-07, with the labels that each got.

#12432 addons controller: hetzner CSI: redeploy CSIDriver to allow upgrade from v2.22 to v2.23
  pkg/controller/seed-controller-manager/addon/addon_controller.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none, backport-needed

#12438 Document 2.23 release regressions
  docs/changelogs/CHANGELOG-2.23.md
Labels: kind/documentation, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#12435 Bump kubectl and helm
  Dockerfile
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none

#12441 Add available OS properties to kubermatic settings
  pkg/apis/kubermatic/v1/settings.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
Labels: kind/feature, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#12442 Bump Go dependencies
  cmd/kubermatic-installer/cmd_local.go
  go.mod
  go.sum
  pkg/controller/user-cluster-controller-manager/kubevirt-vmi-eviction/controller.go
  pkg/kubernetes/helper.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/virtualization, kind/chore, docs/none

#12443 Update cert-manager to 1.12.2
  charts/cert-manager/Chart.yaml
  charts/cert-manager/crd/cert-manager.crds.yaml
  charts/cert-manager/test/default.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12444 Support attaching multiple networks with vSphere VMs
  go.mod
  go.sum
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/machine/provider/vsphere.go
  pkg/validation/cluster.go
Labels: kind/feature, release-note-action-required, lgtm, approved, size/M, dco-signoff: yes, sig/cluster-management, docs/none

#12454 [release/v2.23] Bump kubectl/helm binary and add .trivyignore file
  .trivyignore
  Dockerfile
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved

#12456 [release/v2.22] Bump kubectl/helm binary and add .trivyignore file
  .trivyignore
  Dockerfile
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#12455 add trivy ignorefile
  .trivyignore
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#12457 [release/v2.21] Bump kubectl/helm binary and add .trivyignore file
  .trivyignore
  Dockerfile
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#12458 [release/v2.23] Support attaching multiple networks with vSphere VMs
  go.mod
  go.sum
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/machine/provider/vsphere.go
  pkg/validation/cluster.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management

#12425 Added optional thanos sidecar in Prometheus to ease integration of external Thanos in the stack
  charts/monitoring/prometheus/templates/statefulset.yaml
  charts/monitoring/prometheus/values.yaml
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/regression, docs/provided

#12470 charts/local-kubevirt: bump to v1.0.0
  charts/local-kubevirt/Chart.yaml
  charts/local-kubevirt/crds/customresourcedefinition-kubevirts.kubevirt.io.yaml
  charts/local-kubevirt/templates/clusterrole-kubevirt-operator.yaml
  charts/local-kubevirt/templates/deployment-virt-operator.yaml
  charts/local-kubevirt/update.bash
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12472 Support for configuring IPFamilies and IPFamilyPolicy for nodeport-proxy
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/operator/seed/resources/nodeportproxy/service.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12463 Add Permission Generator Tool for AWS
  codegen/permission-generator/README.md
  codegen/permission-generator/ast.go
  codegen/permission-generator/aws.go
  codegen/permission-generator/config.go
  codegen/permission-generator/defaultmapper.yml
  codegen/permission-generator/doc/operating_principle.drawio
  codegen/permission-generator/doc/operating_principle.png
  codegen/permission-generator/example_test.go
  codegen/permission-generator/main.go
  codegen/permission-generator/policycreator.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, docs/none

#12462 Add support for creating snapshots from `etcd-launcher`
  cmd/etcd-launcher/cmd_defrag.go
  cmd/etcd-launcher/cmd_is_running.go
  cmd/etcd-launcher/cmd_run.go
  cmd/etcd-launcher/cmd_snapshot.go
  cmd/etcd-launcher/main.go
  cmd/etcd-launcher/pkg/etcd/cluster.go
  cmd/seed-controller-manager/controllers.go
  hack/ci/run-etcd-launcher-tests.sh
  pkg/collectors/clusterbackup.go
  pkg/controller/master-controller-manager/rbac/mapper.go
  pkg/controller/master-controller-manager/rbac/sync_resource.go
  pkg/controller/master-controller-manager/rbac/sync_resource_test.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller_test.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/data.go
  pkg/resources/etcd/backup/jobs.go
  pkg/resources/etcd/backup/utils.go
  pkg/resources/etcd/serviceaccount.go
Labels: kind/feature, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12453 Update etcd to 3.5.9
  go.mod
  go.sum
  pkg/resources/etcd/statefulset.go
  pkg/resources/etcd/statefulset_test.go
  pkg/resources/etcd/testdata/etcd-command-no-migration.golden.sh
  pkg/resources/etcd/testdata/etcd-command-with-corruption-flags.golden.sh
  pkg/resources/etcd/testdata/etcd-command-with-migration.golden.sh
  pkg/resources/test/fixtures/statefulset-aws-1.24.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.24.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.25.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.25.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.26.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.26.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.27.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.27.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.24.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.24.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.25.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.25.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.26.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.26.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.27.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.27.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.24.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.25.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.26.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.27.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.24.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.24.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.25.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.25.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.26.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.26.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.27.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.27.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.24.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.25.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.26.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.27.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.24.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.24.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.25.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.25.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.26.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.26.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.27.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.27.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vcd-1.24.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vcd-1.25.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vcd-1.26.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vcd-1.27.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.24.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.24.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.25.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.25.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.26.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.26.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.27.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.27.0-etcd.yaml
  pkg/test/e2e/etcd-launcher/etcd_test.go
Labels: kind/feature, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#12474 Propagate datastore cluster for vSphere to cloud-config
  pkg/resources/cloudconfig/cloudconfig.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#12475 Add trivy presubmit
  .prow/tests.yaml
  hack/README.md
  hack/ci/README.md
  hack/ci/deploy-dev-asia.sh
  hack/ci/deploy-dev.sh
  hack/ci/deploy-offline.sh
  hack/ci/deploy-run-2-lab-alpha.sh
  hack/ci/deploy-run-lab-stable.sh
  hack/ci/push-images.sh
  hack/ci/release-images.sh
  hack/ci/run-offline-test.sh
  hack/ci/trivy-scan.sh
  hack/release-images.sh
Labels: kind/feature, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#12479 Bump Cilium CNI to 1.13.4, mark 1.13.0 as deprecated
  pkg/cni/cilium/cilium-mirror-chart.sh
  pkg/cni/cilium/cilium.go
  pkg/cni/version.go
  pkg/test/e2e/cilium/cilium_test.go
  pkg/test/e2e/nodeport-proxy/nodeport_proxy.go
  pkg/test/e2e/nodeport-proxy/nodeport_proxy_test.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/networking, kind/chore, docs/none

#12482 [release/v2.23] Add trivy presubmit (#12475)
  .prow/tests.yaml
  hack/ci/push-images.sh
  hack/ci/trivy-scan.sh
  hack/release-docker-images.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12478 [release/v2.23] Bump github.com/cilium/cilium to 1.13.4
  Dockerfile
  cmd/alertmanager-authorization-server/Dockerfile
  cmd/http-prober/Dockerfile
  cmd/kubeletdnat-controller/Dockerfile
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/nodeport-proxy/Dockerfile
  cmd/s3-exporter/Dockerfile
  cmd/s3-storeuploader/Dockerfile
  cmd/user-ssh-keys-agent/Dockerfile
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  go.mod
  go.sum
  hack/images/util/Dockerfile
  pkg/cni/cilium/cilium-mirror-chart.sh
  pkg/cni/cilium/cilium.go
  pkg/cni/version.go
  pkg/test/e2e/cilium/cilium_test.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, sig/networking, kind/chore, cherry-pick-approved

#12483 [release/v2.22] Add trivy presubmit (#12475)
  .prow/tests.yaml
  hack/ci/push-images.sh
  hack/ci/trivy-scan.sh
  hack/release-docker-images.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12485 raise test timeouts to make CI jobs more stable
  .golangci.yml
  hack/run-tests.sh
Labels: kind/flake, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#12486 [release/v2.22] bump Go dependencies to fix CVEs
  .trivyignore
  Dockerfile
  go.mod
  go.sum
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#12484 [release/v2.21] Add trivy presubmit (#12475)
  .prow/tests.yaml
  .trivyignore
  hack/ci/push-images.sh
  hack/ci/trivy-scan.sh
  hack/release-docker-images.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12473 Remove legacy backup controller and s3-storeuploader
  cmd/s3-storeuploader/Dockerfile
  cmd/s3-storeuploader/README.md
  cmd/s3-storeuploader/main.go
  cmd/seed-controller-manager/controllers.go
  cmd/seed-controller-manager/options.go
  codegen/example-yaml/main.go
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/configuration.go
  pkg/controller/seed-controller-manager/backup/backup_controller.go
  pkg/controller/seed-controller-manager/backup/backup_controller_test.go
  pkg/controller/seed-controller-manager/backup/doc.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/defaulting/configuration.go
  pkg/defaulting/seed.go
Labels: kind/cleanup, kind/api-change, size/XXL, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/cluster-management, docs/tbd

#12487 upgrade go-git to v5.8.0
  go.mod
  go.sum
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, docs/none

#12477 Add Minio compatibility check to the installer
  cmd/conformance-tester/main.go
  cmd/kubermatic-installer/cmd_deploy.go
  pkg/install/stack/kubermatic-seed/validation.go
  pkg/install/stack/types.go
  pkg/test/dualstack/cloud_providers_dualstack_test.go
  pkg/test/e2e/ccm-migration/ccm_migration_test.go
  pkg/test/e2e/etcd-launcher/etcd_test.go
  pkg/test/e2e/expose-strategy/tunneling_test.go
  pkg/test/e2e/ipam/ipam_test.go
  pkg/test/e2e/mla/mla_test.go
  pkg/test/e2e/nodeport-proxy/nodeport_proxy_test.go
  pkg/test/e2e/opa/opa_test.go
  pkg/test/e2e/utils/kubernetes.go
  pkg/util/podexec/exec.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/regression, kind/deprecation, docs/tbd

#12493 [release/v2.23] Add Minio compatibility check to the installer (#12477)
  cmd/conformance-tester/main.go
  cmd/kubermatic-installer/cmd_deploy.go
  pkg/install/stack/kubermatic-seed/validation.go
  pkg/install/stack/types.go
  pkg/test/dualstack/cloud_providers_dualstack_test.go
  pkg/test/e2e/ccm-migration/ccm_migration_test.go
  pkg/test/e2e/etcd-launcher/etcd_test.go
  pkg/test/e2e/expose-strategy/tunneling_test.go
  pkg/test/e2e/ipam/ipam_test.go
  pkg/test/e2e/mla/mla_test.go
  pkg/test/e2e/nodeport-proxy/nodeport_proxy_test.go
  pkg/test/e2e/opa/opa_test.go
  pkg/test/e2e/utils/kubernetes.go
  pkg/util/podexec/exec.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/regression, kind/deprecation, cherry-pick-approved

#12491 [release/v2.21] Update changelogs for July patch releases
  CHANGELOG.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#12496 fix dev deployment
  hack/release-images.sh
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#12498 [release/v2.21] update machine-controller to v1.54.8
  CHANGELOG.md
  go.mod
  go.sum
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, cherry-pick-approved

#12503 [release/v2.22] Update to Go 1.19.11
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved

#12489 [release/v2.23] Update changelogs for July patch releases
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved

#12488 Update changelogs for July patch releases
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, docs/none

#12504 [release/v2.22] update changelogs for 2.21.11 / 2.22.5
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.22.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#12507 MLA: fix config reloader for monitoring and logging agents
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/logging-agent/daemonset.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/monitoring-agent/deployment.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, docs/none

#12505 Fix support for using IPv6 backed nodeport-proxy service
  pkg/resources/address/address.go
  pkg/resources/address/address_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none, backport-needed

#12511 [release/v2.23] Fix support for using IPv6 backed nodeport-proxy service
  pkg/resources/address/address.go
  pkg/resources/address/address_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12513 Use latest kubeVersion as helm parameter when rendering charts in mirror-images
  cmd/kubermatic-installer/cmd_mirror_images.go
  pkg/install/helm/cli.go
  pkg/install/helm/interface.go
  pkg/install/images/application_definitions.go
  pkg/install/images/helm.go
  pkg/install/images/images_test.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12516 upgrade metrics-server to v0.6.4
  pkg/controller/user-cluster-controller-manager/resources/resources/metrics-server/deployment.go
  pkg/resources/metrics-server/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.24.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.25.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.25.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.26.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.26.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.27.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.27.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.25.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.25.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.26.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.26.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.27.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.27.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.25.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.26.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.27.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.25.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.25.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.26.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.26.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.27.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.27.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.24.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.25.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.26.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.27.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.25.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.25.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.26.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.26.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.27.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.27.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vcd-1.24.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vcd-1.25.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vcd-1.26.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vcd-1.27.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.25.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.25.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.26.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.26.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.27.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.27.0-metrics-server.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#12495 add version-reporter tool to collect third party dependency versions from the codebase
  cmd/conformance-tester/pkg/types/options.go
  codegen/version-reporter/README.md
  codegen/version-reporter/main.go
  codegen/version-reporter/pkg/config/config.go
  codegen/version-reporter/pkg/output/json.go
  codegen/version-reporter/pkg/output/table.go
  codegen/version-reporter/pkg/reader/goconst.go
  codegen/version-reporter/pkg/reader/gofunc.go
  codegen/version-reporter/pkg/reader/helm.go
  codegen/version-reporter/pkg/reader/reader.go
  codegen/version-reporter/pkg/reader/yaml.go
  go.mod
  go.sum
  hack/ci/verify.sh
  hack/versions-gen.sh
  hack/versions.yaml
  pkg/controller/user-cluster-controller-manager/resources/resources/core-dns/deployment.go
  pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/deamonset.go
  pkg/ee/metering/prometheus/sts.go
  pkg/ee/metering/reconcile.go
  pkg/resources/cloudcontroller/anexia.go
  pkg/resources/cloudcontroller/aws.go
  pkg/resources/cloudcontroller/azure.go
  pkg/resources/cloudcontroller/openstack.go
  pkg/resources/cloudcontroller/vsphere.go
  pkg/resources/csi/kubevirt/deployment.go
  pkg/resources/dns/dns.go
  pkg/resources/kubernetes-dashboard/deployment.go
  pkg/resources/openvpn/deployment.go
  pkg/version/helpers.go
Labels: priority/low, kind/documentation, size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#12520 mla: remove docker-related selector in some charts in kubernetes overview
  charts/mla/grafana/files/kubernetes-overview.json
  charts/mla/grafana/test/config.yaml.out
  charts/mla/grafana/test/default.yaml.out
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, docs/none

#12518 [release/v2.23] upgrade go-git to v5.8.0
  go.mod
  go.sum
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, cherry-pick-approved

#12519 [release/v2.22] upgrade go-git to v5.8.0
  go.mod
  go.sum
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, cherry-pick-approved
