Repository kubermatic/kubermatic, pull requests merged in 2023-08, with the labels that each got.

#12532 update metering prometheus to new lts version
  pkg/ee/metering/prometheus/sts.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, docs/none

#12537 Add user-cluster envoy-agent DaemonSet to list of mirrored images
  pkg/install/images/images.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#12541 [release/v2.21] Add user-cluster envoy-agent DaemonSet to list of mirrored images
  pkg/install/images/images.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12549 [release/v2.23] Mark all canal CRDs with preserveUnknownFields: false
  addons/canal/canal_v3.19.yaml
  addons/canal/canal_v3.20.yaml
  addons/canal/canal_v3.21.yaml
  addons/canal/canal_v3.22.yaml
  addons/canal/canal_v3.23.yaml
  addons/canal/canal_v3.24.yaml
  addons/canal/canal_v3.25.yaml
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved

#12547 [release/v2.21] Mark all canal CRDs with preserveUnknownFields: false
  addons/canal/canal_v3.19.yaml
  addons/canal/canal_v3.20.yaml
  addons/canal/canal_v3.21.yaml
  addons/canal/canal_v3.22.yaml
  addons/canal/canal_v3.23.yaml
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved

#12548 [release/v2.22] Mark all canal CRDs with preserveUnknownFields: false
  addons/canal/canal_v3.19.yaml
  addons/canal/canal_v3.20.yaml
  addons/canal/canal_v3.21.yaml
  addons/canal/canal_v3.22.yaml
  addons/canal/canal_v3.23.yaml
  addons/canal/canal_v3.24.yaml
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved

#12545 bump metering version to v1.1.0
  pkg/ee/metering/reconcile.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, docs/provided

#12546 [release/v2.23] Bump metering to v1.0.4 and prometheus to v2.37.9
  pkg/ee/metering/prometheus/sts.go
  pkg/ee/metering/reconcile.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#12544 support monthly metering report generaion
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/ee/metering/cronjob.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12551 Adapt kube-state-metrics scraping to new label
  charts/monitoring/prometheus/config/scraping/kube-state-metrics.yaml
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/provided

#12556 fix master-ctrl-mgr not reconciling RBAC for seeds
  pkg/controller/master-controller-manager/rbac/rbac_resource_controller.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#12557 Fix reconcile loop for seed-proxy on Kubernetes 1.27
  .golangci.apis.yml
  .golangci.yml
  pkg/controller/master-controller-manager/seed-proxy/resources.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12565 cloud/azure: simplify Azure NSG by removing rules duplicating built-in defaults
  pkg/provider/cloud/azure/security_group.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12566 [release/v2.23] Fix reconcile loop for seed-proxy on Kubernetes 1.27 (#12557)
  .golangci.apis.yml
  .golangci.yml
  pkg/controller/master-controller-manager/seed-proxy/resources.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12567 [release/v2.22] Fix reconcile loop for seed-proxy on Kubernetes 1.27 (#12557)
  .golangci.apis.yml
  .golangci.yml
  pkg/controller/master-controller-manager/seed-proxy/resources.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12514 Provide CA bundle to Helm/Git operations in applications
  cmd/user-cluster-controller-manager/main.go
  pkg/applications/helmclient/client.go
  pkg/applications/helmclient/client_integration_test.go
  pkg/applications/helmclient/client_test.go
  pkg/applications/installer.go
  pkg/applications/providers/source/git.go
  pkg/applications/providers/source/helm.go
  pkg/applications/providers/template/helm.go
  pkg/applications/providers/types.go
  pkg/install/images/application_definitions.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#12569 Add NetworkPolicy for accessing the Seed Kubernetes API
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/apiserver/networkpolicy.go
  pkg/resources/resources.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, kind/regression, docs/none

#12572 bump telemetry-agent to 0.4.1
  charts/telemetry/Chart.yaml
  charts/telemetry/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12561 add cilium v1.14 and canal v3.26
  addons/canal/canal_v3.26.yaml
  addons/cilium/cilium_v1.11.yaml
  addons/cilium/cilium_v1.12.yaml
  addons/hubble/hubble_v1.11.yaml
  addons/hubble/hubble_v1.12.yaml
  pkg/cni/cilium/cilium-mirror-chart.sh
  pkg/cni/cilium/cilium.go
  pkg/cni/cilium/cilium_test.go
  pkg/cni/version.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, sig/networking, kind/chore, docs/none

#12534 installer: local command reference KubeVirt images from quay
  cmd/kubermatic-installer/cmd_local.go
  cmd/kubermatic-installer/local_kind_resources.go
  go.mod
Labels: kind/cleanup, kubermatic-installer, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12581 vSphere: support for propagating cluster tags to folders
  pkg/provider/cloud/vsphere/folder.go
  pkg/provider/cloud/vsphere/folder_test.go
  pkg/provider/cloud/vsphere/provider.go
  pkg/provider/cloud/vsphere/tags.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12584 [release/v2.23] August patch release
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved

#12582 [release/v2.21] August patch release
  CHANGELOG.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#12579 update list of supported k8s releases for EKS/AKS
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, kind/chore, docs/none

#12592 remove unused kubelet configmap for <= 1.23
  addons/kubelet-configmap/kubelet-configmap.yaml
Labels: kind/cleanup, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, docs/none

#12589 Fix defaulting for node ports allowed IP ranges
  pkg/provider/cloud/aws/provider.go
  pkg/provider/cloud/azure/provider.go
  pkg/provider/cloud/gcp/provider.go
  pkg/provider/cloud/openstack/provider.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none, backport-needed

#12597 add missing cluster-autoscaler release for Kubernetes 1.27
  addons/cluster-autoscaler/cluster-autoscaler.yaml
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/none

#12585 Update changelogs with August patch releases
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, docs/none

#12588 [release/v2.23] installer: local command reference KubeVirt images from quay
  cmd/kubermatic-installer/cmd_local.go
  cmd/kubermatic-installer/local_kind_resources.go
  go.mod
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12533 Fixed several Prometheus record and alert rules
  charts/monitoring/prometheus/rules/general-kube-kubelet.yaml
  charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/kubermatic-seed-kubermatic.yaml
  charts/monitoring/prometheus/rules/src/general/kube-kubelet.yaml
  charts/monitoring/prometheus/rules/src/general/kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/src/kubermatic-seed/kubermatic.yaml
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#12602 set Logger during CCM e2e tests to prevent needless panic
  pkg/test/e2e/ccm-migration/ccm_migration_test.go
Labels: kind/cleanup, size/S, lgtm, approved, release-note-none, dco-signoff: yes, docs/none

#12603 Add support for Cilium 1.13.6 and deprecate older 1.13 releases
  pkg/cni/cilium/cilium.go
  pkg/cni/version.go
Labels: kind/cleanup, kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/networking, docs/none

#12605 installer: update KubeVirt CDI for local installer from 1.56.0 to 1.57.0
  charts/local-kubevirt/crds/customresourcedefinition-cdis.cdi.kubevirt.io.yaml
  charts/local-kubevirt/templates/clusterrole-cdi-operator-cluster.yaml
  charts/local-kubevirt/templates/configmap-cdi-operator-leader-election-helper.yaml
  charts/local-kubevirt/templates/deployment-cdi-operator.yaml
Labels: kind/cleanup, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#12604 Update Vertical Pod Autoscaler (VPA) to 0.14.0
  codegen/version-reporter/pkg/reader/gofunc.go
  go.mod
  go.sum
  hack/ci/testdata/kubermatic.yaml
  hack/versions.yaml
  pkg/controller/operator/common/vpa/admissionctrl.go
  pkg/controller/operator/common/vpa/rbac.go
  pkg/controller/operator/common/vpa/recommender.go
  pkg/controller/operator/common/vpa/updater.go
  pkg/crd/k8s.io/autoscaling.k8s.io_verticalpodautoscalercheckpoints.yaml
  pkg/crd/k8s.io/autoscaling.k8s.io_verticalpodautoscalers.yaml
  pkg/version/kubermatic/versions.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none, backport-needed

#12608 Add dex frontend issuer to configmap
  charts/oauth/templates/configmap.yaml
  charts/oauth/test/default.yaml.out
  charts/oauth/test/image-pull-secret.yaml.out
  charts/oauth/test/theme-with-overwrites.yaml.out
  charts/oauth/test/values.example.ce.yaml.out
  charts/oauth/test/values.example.ee.yaml.out
  charts/oauth/values.yaml
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#12614 MLA: Update grafana dashboard schemas
  charts/mla/grafana/files/kkp-kubernetes-nodes-overview.json
  charts/mla/grafana/files/kkp-kubernetes-nodes.json
  charts/mla/grafana/files/kkp-kubernetes-statefulsets.json
  charts/mla/grafana/test/config.yaml.out
  charts/mla/grafana/test/default.yaml.out
Labels: kind/bug, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none
