Repository kubermatic/kubermatic, pull requests merged in 2023-02, with the labels that each got.

#11797 [release/v2.19] Update MC to v1.42.9 and OSM to v0.3.10
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/operatingsystemmanager/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.20.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.21.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved, do-not-merge/code-freeze

#11799 [release/v2.19] Update changelog for 2.19.15
  CHANGELOG.md
Labels: kind/documentation, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, cherry-pick-approved, do-not-merge/code-freeze

#11800 [release/v2.20] Add changelog for 2.20.13
  CHANGELOG.md
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved, do-not-merge/code-freeze

#11798 Add changelog for 2.20.13 and 2.19.15
  docs/changelogs/CHANGELOG-2.19.md
  docs/changelogs/CHANGELOG-2.20.md
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#11801 Update changelogs to be more accurate of container/docker changes
  docs/changelogs/CHANGELOG-2.19.md
  docs/changelogs/CHANGELOG-2.20.md
Labels: kind/documentation, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none, code-freeze-approved

#11818 Fix OpenStack tenant fields migration
  pkg/provider/kubernetes/credentials.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/api, docs/none, code-freeze-approved

#11830 [release/v2.21] KubeVirt set storage.deleteAfterCompletion=false annotation on DV
  pkg/provider/cloud/kubevirt/data_volume.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, sig/virtualization, cherry-pick-approved, do-not-merge/code-freeze

#11837 Fix RBAC issue for OSM migration
  pkg/resources/usercluster/rbac.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11836 Add "PodSecurityPolicy" admission plugin validation for Cluster webhook
  pkg/validation/cluster.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, docs/provided, code-freeze-approved

#11843 Fix invalid project dereference in user grafana controller
  pkg/controller/seed-controller-manager/mla/user_grafana_controller.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#11845 Ensure that tunneling-agent-ip is always passed to the usercluster-controller
  pkg/controller/seed-controller-manager/kubernetes/address.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/address/address.go
  pkg/resources/address/address_test.go
  pkg/resources/data.go
  pkg/resources/usercluster/deployment.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11844 KubeVirt fix ccmClusterName feature for migrated clusters
  pkg/webhook/cluster/mutation/mutator.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, docs/none, code-freeze-approved

#11841 Fix KubeVirt client schema creation
  pkg/provider/cloud/kubevirt/client.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/virtualization, docs/none, cherry-pick-approved, code-freeze-approved

#11846 Unblock reconciliation loop if default backup destination is not set
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/collectors/clusterbackup.go
  pkg/controller/seed-controller-manager/backup/backup_controller.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller.go
  pkg/controller/seed-controller-manager/etcdrestore/etcd_restore_controller.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11852 Fix APIServerAllowedIPRanges support on AWS
  pkg/resources/nodeportproxy/nodeportproxy.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11853 [release/v2.21] Persist annotations when upgrading a cluster
  pkg/handler/common/cluster.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/api, cherry-pick-approved, code-freeze-approved

#11848 Adjust KubeVirt image repo
  cmd/conformance-tester/pkg/scenarios/kubevirt.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none, code-freeze-approved

#11854 [release/v2.21] Unblock etcd backup/restore reconciliation
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/collectors/clusterbackup.go
  pkg/controller/seed-controller-manager/backup/backup_controller.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller.go
  pkg/controller/seed-controller-manager/etcdrestore/etcd_restore_controller.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved, do-not-merge/code-freeze

#11859 Add support for Kubernetes v1.24.10, v1.25.6, and v1.26.1
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  hack/images/util/Dockerfile
  hack/images/web-terminal/Dockerfile
  pkg/defaulting/configuration.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, docs/none, code-freeze-approved

#11865 Fix removal of IPs from cluster ApiServerAllowedIPRanges
  pkg/resources/nodeportproxy/nodeportproxy.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11866 Default correct feature flag for etcd-launcher
  cmd/etcd-launcher/Makefile
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  hack/run-expose-strategy-e2e-test-in-kind.sh
  pkg/defaulting/configuration.go
Labels: kind/bug, kind/cleanup, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#11871 applications: don't reuse values when upgrading
  pkg/applications/helmclient/client.go
  pkg/applications/helmclient/client_integration_test.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#11868 Update image tag for web-terminal
  hack/images/web-terminal/release.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#11862 Add option to conformance-tester to run cluster updates
  cmd/conformance-tester/README.md
  cmd/conformance-tester/main.go
  cmd/conformance-tester/pkg/runner/result.go
  cmd/conformance-tester/pkg/runner/runner.go
  cmd/conformance-tester/pkg/types/options.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#11874 add --skip-seed-validation flag to installer
  cmd/kubermatic-installer/cmd_deploy.go
  pkg/install/stack/kubermatic-master/validation.go
  pkg/install/stack/types.go
  pkg/util/flagopts/set_flag.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11877 Fix typo in ApplicationInstallation conditions
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#11878 [release/2.21] Update CHANGELOG.md
  CHANGELOG.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved, do-not-merge/code-freeze

#11888 applicationInstallation is in deleting, don't check that applicationDefinition exists.
  pkg/defaulting/application_installation_test.go
  pkg/validation/application_installation.go
  pkg/validation/application_installation_test.go
  pkg/webhook/application/applicationinstallation/validation/validation.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, docs/none, code-freeze-approved

#11889 wait cni addon is uninstalled before install cni application
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/networking, docs/none, code-freeze-approved

#11861 Fix 2.22 MLA Upgrade issues
  cmd/kubermatic-installer/cmd_deploy.go
  pkg/install/stack/usercluster-mla/stack.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11886 Remove scripts for web-terminal
  hack/images/web-terminal/Dockerfile
  hack/images/web-terminal/release.sh
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#11897 [release/v2.21] Update machine-controller to v1.54.5
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller.yaml
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved, do-not-merge/code-freeze

#11894 use strenv instead of env to set imagePullSecret to deploy dev
  hack/ci/deploy.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11891 Hotfix: Provider name validation for provider incompatibility matrix
  pkg/apis/kubermatic/v1/configuration.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/defaulting/configuration.go
  pkg/version/manager.go
  pkg/version/manager_test.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11887 applications: add EnableDns options
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/applications/helmclient/client.go
  pkg/applications/helmclient/client_integration_test.go
  pkg/applications/helmclient/client_test.go
  pkg/applications/helmclient/testdata/examplechart-v2/templates/configmap.yaml
  pkg/applications/helmclient/testdata/examplechart/templates/configmap.yaml
  pkg/applications/providers/template/helm.go
  pkg/applications/providers/template/helm_integration_test.go
  pkg/applications/providers/template/helm_test.go
  pkg/applications/test/helm.go
  pkg/applications/test/kubernetes.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
Labels: size/L, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/app-management, docs/provided, code-freeze-approved

#11898 [Release/2.21] Hotfix: Provider name validation for provider incompatibility matrix
  pkg/apis/kubermatic/v1/configuration.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/handler/v1/cluster/upgrade_test.go
  pkg/handler/v2/cluster/upgrade_test.go
  pkg/handler/v2/version/version_test.go
  pkg/version/manager.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, docs/none, cherry-pick-approved, do-not-merge/code-freeze

#11904 fix k8s feature gates not depending on the correct cluster version
  pkg/resources/apiserver/deployment.go
  pkg/resources/controllermanager/deployment.go
  pkg/resources/data.go
  pkg/resources/data_test.go
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/machinecontroller/webhook.go
  pkg/resources/operatingsystemmanager/deployment.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11892 Update k8s version defaults
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, docs/tbd, code-freeze-approved

#11893 allow empty values file in the installer
  cmd/kubermatic-installer/shared.go
  pkg/install/helm/cli.go
  pkg/install/stack/kubermatic-master/validation.go
  pkg/install/stack/kubermatic-seed/validation.go
  pkg/install/util/helm.go
  pkg/util/yamled/document.go
  pkg/util/yamled/document_test.go
  pkg/util/yamled/helpers.go
  pkg/util/yamled/testcases/empty-document.yaml
  pkg/util/yamled/testcases/nonempty-document.yaml
  pkg/util/yamled/testcases/set-new-root-key-empty-document.yaml
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11903 Fix synchronisation for default resource quotas
  pkg/ee/resource-quota/default-quota-controller/controller.go
  pkg/ee/resource-quota/default-quota-controller/controller_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#11899 fully deploy vsphere csi webhook for migrated clusters
  pkg/addon/template.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, docs/none, code-freeze-approved

#11905 Enable Konnectivity by default on conformance-tester
  cmd/conformance-tester/pkg/types/options.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#11915 Updating telemetry charts with latest image
  charts/telemetry/Chart.yaml
  charts/telemetry/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/tbd, code-freeze-approved

#11906 Watch User to sync UserProjectBinding
  cmd/master-controller-manager/controllers.go
  pkg/controller/master-controller-manager/user-project-binding/controller.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11907 Refactoring for default quota generation
  pkg/apis/kubermatic/v1/resource_quota.go
  pkg/apis/kubermatic/v1/settings.go
  pkg/ee/resource-quota/default-quota-controller/controller.go
  pkg/ee/validation/resourcequota/resourcequota.go
  pkg/webhook/resourcequota/validation/validation.go
  pkg/webhook/resourcequota/validation/wrappers_ce.go
  pkg/webhook/resourcequota/validation/wrappers_ee.go
Labels: kind/bug, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11921 Load default dashboards into MLA grafana instance
  charts/mla/grafana/files/kkp-kubernetes.json
  charts/mla/grafana/files/kubernetes-overview.json
  charts/mla/grafana/templates/kkp-kubernetes.yaml
  charts/mla/grafana/templates/kubernetes-overview.yaml
  charts/mla/grafana/test/config.yaml.out
  charts/mla/grafana/test/default.yaml.out
  charts/mla/grafana/values.yaml
Labels: kind/bug, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#11924 Split MLA json dashboards into dedicated files
  charts/mla/grafana/files/kkp-kubernetes-nodes-overview.json
  charts/mla/grafana/files/kkp-kubernetes-nodes.json
  charts/mla/grafana/files/kkp-kubernetes-pods.json
  charts/mla/grafana/files/kkp-kubernetes-statefulsets.json
  charts/mla/grafana/files/kkp-kubernetes.json
  charts/mla/grafana/templates/kkp-kubernetes.yaml
  charts/mla/grafana/test/config.yaml.out
  charts/mla/grafana/test/default.yaml.out
Labels: kind/bug, size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#11919 vSphere tags finalizer fixes
  pkg/provider/cloud/vsphere/folder.go
  pkg/provider/cloud/vsphere/provider.go
  pkg/provider/cloud/vsphere/tags.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11929 Use non-atomic Helm deployment for CNI
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/networking, docs/none, code-freeze-approved

#11928 Hotfix: defaulting and validation for tag category
  pkg/apis/kubermatic/v1/cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/provider/cloud/vsphere/provider.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11927 applications: limits the number of retries only if deployOptions.Helm.atomic=true
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#11914 Update KubeOne image to the latest commit image
  go.mod
  go.sum
  pkg/resources/resources.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11931 Update to Go 1.19.6
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
Labels: kind/cleanup, size/L, lgtm, approved, release-note, dco-signoff: yes, docs/none, code-freeze-approved

#11932 Include tunneling agent IP in apiserver's TLS cert SAN
  pkg/resources/apiserver/tls-serving-certificate.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, backport-needed, code-freeze-approved

#11935 Fix cluster access issue while cluster is upgrading
  pkg/controller/master-controller-manager/kubeone/controller.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11936 Fix KubeOne Status Update from Upgrade to Running before Upgrade completion
  pkg/controller/master-controller-manager/kubeone/controller.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11939 Add upgrade incomptability for OpenStack with in-tree provider
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/apis/kubermatic/v1/configuration.go
  pkg/controller/seed-controller-manager/update-controller/controller.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/defaulting/configuration.go
  pkg/resources/data.go
  pkg/version/version_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/tbd, code-freeze-approved

#11949 Fix queries in Kubermatic / User Cluster dashboard
  charts/monitoring/grafana/dashboards/kubermatic/user-clusters.json
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#11951 Add vSphere incompatibility for the in-tree provider with Kubernetes 1.25 or higher
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
  pkg/version/version_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, docs/tbd, code-freeze-approved

#11953 Update kubeone image to the latest commit image
  go.mod
  go.sum
  pkg/resources/resources.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#11815 Add KKP 2.22.0 changelog
  docs/changelogs/CHANGELOG-2.22.md
Labels: size/L, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#11913 [release/v2.19] fully deploy vsphere csi webhook for migrated clusters
  pkg/addon/template.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, cherry-pick-approved

#11912 [release/v2.21] fully deploy vsphere csi webhook for migrated clusters
  pkg/addon/template.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, cherry-pick-approved

#11911 [release/v2.20] fully deploy vsphere csi webhook for migrated clusters
  pkg/addon/template.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, cherry-pick-approved

#11933 [release/v2.21] Include tunneling agent IP in apiserver's TLS cert SAN
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/apiserver/tls-serving-certificate.go
  pkg/resources/data.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#11947 fix wrong labels in cluster/project metrics
  pkg/collectors/cluster.go
  pkg/collectors/cluster_test.go
  pkg/collectors/project.go
  pkg/collectors/util.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, docs/none, backport-needed

#11943 [EE] fix worker-name handling in resource-quota controller
  pkg/ee/resource-quota/seed-controller/controller.go
  pkg/ee/resource-quota/seed-controller/controller_test.go
  pkg/ee/resource-quota/seed-controller/doc.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, docs/none

#11955 update Go dependencies
  .wwhrd.yml
  go.mod
  go.sum
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_addonconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_addons.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_admissionplugins.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_alertmanagers.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_allowedregistries.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplateinstances.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_constraints.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_constrainttemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdbackupconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdrestores.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_groupprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipamallocations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipampools.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_mlaadminsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_projects.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_resourcequotas.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_rulegroups.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_userprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_users.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_usersshkeys.yaml
  pkg/provider/cloud/aws/data/aws.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#11923 Upgrade Anexia CCM to v1.5.2
  .prow/provider-anexia.yaml
  pkg/resources/cloudcontroller/anexia.go
Labels: kind/cleanup, ok-to-test, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#11950 Add share cluster flag to kubermatic settings
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/apis/kubermatic/v1/settings.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  pkg/defaulting/configuration.go
Labels: kind/feature, size/S, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/cluster-management, docs/tbd
