Repository kubermatic/kubermatic, pull requests merged in 2023-06, with the labels that each got.

#12330 Rename ClusterRole file in charts/local-kubevirt to fix Go module
  charts/local-kubevirt/templates/clusterrole-kubevirt.io-operator.yaml
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, kind/regression, docs/none

#12302 Add monitoing and dashboard for envoy-agent and nodeport-proxy
  charts/monitoring/grafana/dashboards/kubermatic/nodeport-proxy.json
  cmd/user-cluster-controller-manager/main.go
  pkg/controller/user-cluster-controller-manager/resources/resources/envoy-agent/configmap.go
  pkg/controller/user-cluster-controller-manager/resources/resources/envoy-agent/daemonset.go
  pkg/resources/prometheus/configmap-rules.go
  pkg/resources/prometheus/configmap.go
  pkg/resources/test/fixtures/configmap-aws-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-aws-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-aws-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.26.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-aws-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.27.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-aws-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.26.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.27.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.26.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.27.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-gcp-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-gcp-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-gcp-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-gcp-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.26.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.27.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.26.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.27.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.27.0-prometheus.yaml
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#12335 Update local-kubevirt chart to v1.0.0-beta.0
  charts/local-kubevirt/Chart.yaml
  charts/local-kubevirt/crds/customresourcedefinition-kubevirts.kubevirt.io.yaml
  charts/local-kubevirt/templates/deployment-virt-operator.yaml
  charts/local-kubevirt/update.bash
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#12339 update kubevirt storage class
  cmd/conformance-tester/pkg/scenarios/kubevirt.go
  cmd/conformance-tester/pkg/tests/storage.go
  codegen/example-yaml/main.go
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  hack/ci/testdata/seed.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#12343 Include local-kubevirt chart in release
  hack/ci/github-release.sh
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#12347 deprecate canal 3.22 and alter auto update
  pkg/cni/version.go
  pkg/mutation/cluster/mutation.go
  pkg/webhook/cluster/mutation/mutator_test.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/networking, kind/chore, docs/none, code-freeze-approved

#12329 switch to egress based network policies for kubervirt provider
  hack/ci/run-conformance-tests.sh
  hack/ci/testdata/seed.yaml
  pkg/provider/cloud/kubevirt/network_policy.go
  pkg/provider/cloud/kubevirt/provider.go
Labels: size/L, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/cluster-management, sig/networking, sig/virtualization, docs/tbd

#12361 Update Golang version to 1.20.5
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/images/integration-tests/Dockerfile
  hack/images/integration-tests/release.sh
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#12363 Update integration test image
  .prow/tests.yaml
  hack/images/integration-tests/Dockerfile
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#12360 [release/v2.22] alter canal cni auto update
  pkg/webhook/cluster/mutation/mutator.go
  pkg/webhook/cluster/mutation/mutator_test.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved, code-freeze-approved

#12346 [release/v2.21] use internal kubeconfig reconciler to generate konnectivity-server's kubeconfig
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/apiserver/networkpolicy.go
  pkg/resources/konnectivity/deletion.go
  pkg/resources/konnectivity/secrets.go
  pkg/resources/resources.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved, do-not-merge/code-freeze

#12364 Update KubeOne dependency and image to latest version
  go.mod
  go.sum
  pkg/resources/resources.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none, code-freeze-approved

#12370 Use root disk size while calculating resource quota for Openstack
  pkg/ee/validation/machine/providers.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, docs/none, code-freeze-approved

#12371 Fix VCD CSI credentials secret for Kubernetes v1.24
  addons/csi/vmware-cloud-director/vcloud-basic-auth.yaml
  pkg/resources/data.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none, code-freeze-approved

#12372 Fix Azure CCM
  pkg/resources/cloudcontroller/azure.go
  pkg/resources/test/fixtures/deployment-azure-1.24.0-azure-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.25.0-azure-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.26.0-azure-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.27.0-azure-cloud-controller-manager-externalCloudProvider.yaml
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#12376 [release/v2.21] Add Kubernetes 1.24.15
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/defaults/defaults.go
Labels: kind/feature, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, cherry-pick-approved, do-not-merge/code-freeze

#12385 only set the apiserver allow rule after address is available
  pkg/provider/cloud/kubevirt/network_policy.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/virtualization, docs/none, code-freeze-approved

#12391 [release/v2.21] Bump machine-controller to v1.54.7
  go.mod
  go.sum
  pkg/resources/machinecontroller/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-webhook-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-machine-controller.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, cherry-pick-approved, code-freeze-approved

#12396 fix possible npe if vsphere cloud spec is nil
  pkg/provider/cloud/vsphere/provider.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#12386 [release/v2.21] Update changelog with v2.21.10
  CHANGELOG.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved, code-freeze-approved

#12387 [release/v2.22] Update changelogs with patch release: v2.22.4 & v2.21.10
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.22.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved, code-freeze-approved

#12388 Update changelogs with June patch release
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.22.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#12393 Fix multi arch builds
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/ci/push-images.sh
  hack/ci/run-user-ssh-key-agent-tests.sh
  hack/release-docker-images.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#12397 Allow antiAffinity values to be merged when needed
  pkg/controller/operator/seed/resources/nodeportproxy/deployments.go
  pkg/resources/antiaffinity.go
  pkg/resources/antiaffinity_test.go
  pkg/resources/etcd/statefulset.go
  pkg/resources/nodeportproxy/nodeportproxy.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#12399 [release/v2.22] Replace buildah with buildx (#12393)
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/ci/push-images.sh
  hack/ci/run-user-ssh-key-agent-tests.sh
  hack/lib.sh
  hack/release-docker-images.sh
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/regression, cherry-pick-approved, do-not-merge/code-freeze

#12400 use bookworm-based build image
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, kind/regression, docs/none, code-freeze-approved

#12403 force canal update at k8s 1.25
  pkg/mutation/cluster/mutation.go
  pkg/webhook/cluster/mutation/mutator_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, docs/none, code-freeze-approved

#12404 VCD: mark apiToken as an optional secret mount
  pkg/resources/data.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#12402 installer: disable network policies in local kubevirt seed
  cmd/kubermatic-installer/local_kind_resources.go
Labels: kind/bug, kubermatic-installer, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#12405 installer: local command usability improvements
  cmd/kubermatic-installer/cmd_local.go
Labels: kind/cleanup, kubermatic-installer, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#12411 nginx-ingress-controller: set memory limits to 1Gi
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
  charts/nginx-ingress-controller/values.yaml
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none, code-freeze-approved

#12416 fix always true if statement in kubevirt network policies
  pkg/provider/cloud/kubevirt/network_policy.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/virtualization, docs/none, code-freeze-approved

#12417 Add aws k8s >=1.27 in-tree cloud provider incompatibility
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, docs/provided, code-freeze-approved

#12408 Add changelog for KKP 2.23.0
  docs/changelogs/CHANGELOG-2.23.md
Labels: size/L, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#12412 fix Blackbox exporter scraping
  charts/monitoring/prometheus/values.yaml
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/none, do-not-merge/code-freeze

#12414 Allow to specific RHEL subscription details in conformance-tester
  cmd/conformance-tester/pkg/runner/runner.go
  cmd/conformance-tester/pkg/scenarios/alibaba.go
  cmd/conformance-tester/pkg/scenarios/anexia.go
  cmd/conformance-tester/pkg/scenarios/aws.go
  cmd/conformance-tester/pkg/scenarios/azure.go
  cmd/conformance-tester/pkg/scenarios/base.go
  cmd/conformance-tester/pkg/scenarios/digitalocean.go
  cmd/conformance-tester/pkg/scenarios/google.go
  cmd/conformance-tester/pkg/scenarios/hetzner.go
  cmd/conformance-tester/pkg/scenarios/kubevirt.go
  cmd/conformance-tester/pkg/scenarios/nutanix.go
  cmd/conformance-tester/pkg/scenarios/openstack.go
  cmd/conformance-tester/pkg/scenarios/packet.go
  cmd/conformance-tester/pkg/scenarios/vmware_cloud_director.go
  cmd/conformance-tester/pkg/scenarios/vsphere.go
  cmd/conformance-tester/pkg/types/secrets.go
  pkg/machine/operatingsystem/builders.go
Labels: kind/feature, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#12427 Replace irate with rate for node cpu usage graphs
  charts/mla/grafana/files/kkp-kubernetes-nodes-overview.json
  charts/mla/grafana/files/kkp-kubernetes-nodes.json
  charts/mla/grafana/test/config.yaml.out
  charts/mla/grafana/test/default.yaml.out
  charts/monitoring/grafana/dashboards/kubernetes/nodes-overview.json
  charts/monitoring/grafana/dashboards/kubernetes/nodes.json
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, docs/none
