Repository kubermatic/kubermatic, pull requests merged in 2023-03, with the labels that each got.

#11965 update cert-manager to 0.11
  charts/cert-manager/Chart.yaml
  charts/cert-manager/test/default.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#11964 Disable RHEL in Cilium dualstack e2e test
  pkg/test/dualstack/cloud_providers_dualstack_test.go
Labels: kind/failing-test, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#11970 [release/v2.21] fix wrong labels in cluster/project metrics
  pkg/collectors/cluster.go
  pkg/collectors/cluster_test.go
  pkg/collectors/project.go
  pkg/collectors/util.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, cherry-pick-approved

#11971 Do not use trace log level for the envoy-agent
  pkg/controller/user-cluster-controller-manager/resources/resources/envoy-agent/daemonset.go
Labels: kind/cleanup, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#11962 only reconcile KKP managed folders in vSphere
  pkg/provider/cloud/vsphere/folder.go
  pkg/provider/cloud/vsphere/provider.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none, backport-needed

#11966 Update Velero to 1.10.1
  charts/backup/velero/Chart.yaml
  charts/backup/velero/crd/backuprepositories.yaml
  charts/backup/velero/crd/backups.yaml
  charts/backup/velero/crd/backupstoragelocations.yaml
  charts/backup/velero/crd/deletebackuprequests.yaml
  charts/backup/velero/crd/downloadrequests.yaml
  charts/backup/velero/crd/podvolumebackups.yaml
  charts/backup/velero/crd/podvolumerestores.yaml
  charts/backup/velero/crd/restores.yaml
  charts/backup/velero/crd/schedules.yaml
  charts/backup/velero/crd/serverstatusrequests.yaml
  charts/backup/velero/crd/volumesnapshotlocations.yaml
  charts/backup/velero/templates/daemonset.yaml
  charts/backup/velero/values.yaml
  hack/update-velero-crds.sh
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/provided

#11972 remove toleration from kubevirt csi as its deployed in seed cluster
  pkg/resources/csi/kubevirt/deployment.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#11959 federate node kube_node_info to metering prometheus
  pkg/ee/metering/prometheus/configmap.go
  pkg/ee/metering/prometheus/reconcile.go
Labels: kind/bug, kind/feature, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#11979 propagate ca bundle to metering cron jobs
  pkg/ee/metering/cronjob.go
  pkg/ee/metering/reconcile.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, docs/none

#11976 [release/v2.21] Set proper NodePort range in Cilium config
  addons/cilium/cilium_v1.11.yaml
  addons/cilium/cilium_v1.12.yaml
  docs/zz_generated.addondata.go.txt
  pkg/addon/template.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, cherry-pick-approved

#11982 bump Digitalocean CCM to 0.1.42
  pkg/resources/cloudcontroller/digitalocean.go
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-digitalocean-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.25.0-digitalocean-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.26.0-digitalocean-cloud-controller-manager-externalCloudProvider.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#11890 Output machine-readable test results in conformance-tester
  cmd/conformance-tester/main.go
  cmd/conformance-tester/pkg/runner/result.go
  cmd/conformance-tester/pkg/runner/runner.go
  cmd/conformance-tester/pkg/scenarios/alibaba.go
  cmd/conformance-tester/pkg/scenarios/anexia.go
  cmd/conformance-tester/pkg/scenarios/aws.go
  cmd/conformance-tester/pkg/scenarios/azure.go
  cmd/conformance-tester/pkg/scenarios/base.go
  cmd/conformance-tester/pkg/scenarios/digitalocean.go
  cmd/conformance-tester/pkg/scenarios/generator.go
  cmd/conformance-tester/pkg/scenarios/google.go
  cmd/conformance-tester/pkg/scenarios/hetzner.go
  cmd/conformance-tester/pkg/scenarios/kubevirt.go
  cmd/conformance-tester/pkg/scenarios/nutanix.go
  cmd/conformance-tester/pkg/scenarios/openstack.go
  cmd/conformance-tester/pkg/scenarios/packet.go
  cmd/conformance-tester/pkg/scenarios/vmware_cloud_director.go
  cmd/conformance-tester/pkg/scenarios/vsphere.go
  cmd/conformance-tester/pkg/types/options.go
  hack/ci/run-conformance-tests.sh
Labels: kind/feature, size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#11968 Update HCloud CSI/CCM
  addons/csi/hetzner/hcloud-csi.yaml
  pkg/resources/cloudcontroller/hetzner.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/none

#11977 [release/v2.20] Set proper NodePort range in Cilium config
  addons/cilium/cilium.yaml
  docs/zz_generated.addondata.go.txt
  pkg/addon/template.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, cherry-pick-approved

#11988 Remove trailing whitespace from custom scraping configuration
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/monitoring-agent/configmap.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/none, backport-needed

#11990 Generate a token for hack/run-user-cluster-controller-manager.sh
  hack/run-user-cluster-controller-manager.sh
Labels: kind/cleanup, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#11981 [release/v2.21] Remove promtail sidecar from user cluster MLA that sets `fs.inotify.max_user_instances`
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/promtail/daemonset.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved

#11996 Validate version by checking for provider incompatibilities properly
  pkg/apis/kubermatic/v1/cluster.go
  pkg/controller/seed-controller-manager/update-controller/controller.go
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12003 fix conformance-tester always succeeding
  cmd/conformance-tester/main.go
  cmd/conformance-tester/pkg/runner/result.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, docs/none

#12005 Test vSphere CCM migration on Kubernetes 1.24
  .prow/ccm-migrations.yaml
Labels: kind/failing-test, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#11984 bump node-exporter to 1.5.0
  addons/node-exporter/daemonset.yaml
  addons/node-exporter/networkpolicy.yaml
  charts/monitoring/node-exporter/Chart.yaml
  charts/monitoring/node-exporter/templates/daemonset.yaml
  charts/monitoring/node-exporter/values.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#11987 Update kube-state-metrics to 2.8.1
  addons/kube-state-metrics/deployment.yaml
  addons/kube-state-metrics/networkpolicy.yaml
  addons/kube-state-metrics/rbac.yaml
  charts/monitoring/kube-state-metrics/Chart.yaml
  charts/monitoring/kube-state-metrics/templates/deployment.yaml
  charts/monitoring/kube-state-metrics/values.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12007 Use Alpine Linux 3.17 for container images
  Dockerfile
  addons/Dockerfile
  cmd/alertmanager-authorization-server/Dockerfile
  cmd/http-prober/Dockerfile
  cmd/kubeletdnat-controller/Dockerfile
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/nodeport-proxy/Dockerfile
  cmd/s3-exporter/Dockerfile
  cmd/s3-storeuploader/Dockerfile
  cmd/user-ssh-keys-agent/Dockerfile
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/images/grafana-plugins/Dockerfile
  hack/images/util/Dockerfile
Labels: kind/cleanup, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, docs/none

#11989 Update to Go 1.20.2
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/conformance-tester/pkg/util/ginkgo.go
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/images/integration-tests/Dockerfile
  hack/images/integration-tests/release.sh
  hack/lib.sh
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller.go
  pkg/controller/seed-controller-manager/initial-machinedeployment-controller/controller.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/install/helm/cli.go
  pkg/provider/cloud/nutanix/client.go
  pkg/resources/resources_test.go
  pkg/util/wait/wait.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#12013 Update Grafana to 9.4.3
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/values.yaml
  hack/images/grafana-plugins/Dockerfile
  hack/images/grafana-plugins/release.sh
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12025 produce vx.y-latest container images for non-tagged revisions in release branches
  hack/ci/push-images.sh
Labels: kind/failing-test, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#12026 do not use Hetzner for feature e2e tests anymore
  .prow/features.yaml
  hack/ci/run-cilium-e2e-test.sh
  hack/ci/run-ipam-e2e-tests.sh
  hack/ci/run-konnectivity-e2e-test.sh
  hack/ci/run-mla-e2e-tests.sh
  hack/ci/run-opa-e2e-tests.sh
  pkg/test/e2e/ipam/ipam_test.go
  pkg/test/e2e/mla/mla_test.go
  pkg/test/e2e/opa/opa_test.go
Labels: kind/flake, kind/failing-test, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#12017 add short names for application crds
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
Labels: kind/feature, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/none

#12012 Improve StorageClass creation in installer
  addons/default-storage-class/storage-class.yaml
  cmd/user-ssh-keys-agent/Makefile
  pkg/install/stack/common/storageclass.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/stack/kubermatic-seed/stack.go
Labels: size/L, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#12011 [release/v2.21] Allow updating of clusterNetwork.proxyMode via the KKP API
  pkg/handler/common/cluster.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/api, cherry-pick-approved

#12030 Fix client default context for user clusters
  pkg/cluster/client/client.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#12029 Enable Loki compactor retention and rotation
  charts/logging/loki/values.yaml
Labels: kind/feature, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/none

#12032 [release/v2.21] propagate ca bundle to metering cron job
  pkg/ee/metering/cronjob.go
  pkg/ee/metering/reconcile.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, cherry-pick-approved

#12035 bump metering to version 1.0.3
  pkg/ee/metering/reconcile.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, docs/none

#12038 [release/v2.21] bump metering to version 1.0.3
  pkg/ee/metering/reconcile.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, sig/virtualization, cherry-pick-approved

#12039 [release/v2.20] Update CHANGELOG.md
  CHANGELOG.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#12040 [release/v2.21] Update CHANGELOG.md
  CHANGELOG.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved

#12033 fix flakiness on Helm integration tests
  pkg/applications/test/helm.go
Labels: kind/flake, kind/failing-test, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management, docs/none

#12050 [Release/v2.21] Update OSM to v1.1.3
  pkg/resources/operatingsystemmanager/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.22.1-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-operating-system-manager.yaml
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12048 Dex Visual Login Changes
  charts/oauth/theme/bg.svg
Labels: size/L, lgtm, approved, release-note-none, kind/design, dco-signoff: yes, sig/app-management, docs/none

#12041 [release/v2.22] Update changelogs
  docs/changelogs/CHANGELOG-2.20.md
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.22.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved

#12053 [release/v2.21] Updating changelog after latest fix
  CHANGELOG.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#12042 Patch release - update changelog files
  docs/changelogs/CHANGELOG-2.20.md
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.22.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, docs/none

#12056 Support for specifying dockerTagSuffix for UI/API images
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/apis/kubermatic/v1/configuration.go
  pkg/controller/operator/master/resources/kubermatic/api.go
  pkg/controller/operator/master/resources/kubermatic/ui.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
Labels: customer-request, kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12055 Remove heapster addon and last RBAC traces
  addons/heapster/heapster-controller.yaml
  addons/heapster/heapster-rbac.yaml
  addons/heapster/heapster-service.yaml
  pkg/controller/user-cluster-controller-manager/resources/resources/kubernetes-dashboard/role.go
Labels: kind/cleanup, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#12034 Fix dashboard CPU utilisation graphs for multi-core nodes
  charts/mla/grafana/files/kkp-kubernetes-nodes-overview.json
  charts/monitoring/grafana/dashboards/kubernetes/nodes-overview.json
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/none, backport-needed

#12067 Pull proxy-agent image from registry.k8s.io
  cmd/conformance-tester/pkg/tests/images.go
  cmd/conformance-tester/pkg/tests/usercluster_controller.go
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/deployment.go
  pkg/resources/konnectivity/sidecar.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none, backport-needed

#12069 [release/v2.21] Pull proxy-agent image from registry.k8s.io and backport tests for no k8s.gcr.io images
  cmd/conformance-tester/pkg/runner/runner.go
  cmd/conformance-tester/pkg/tests/images.go
  cmd/conformance-tester/pkg/tests/usercluster_controller.go
  cmd/conformance-tester/pkg/types/tests.go
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/deployment.go
  pkg/resources/konnectivity/sidecar.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12004 RFC: Proposal for Dehydration feature
  docs/proposals/dehydration.md
Labels: size/L, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#12081 [release/v2.20] Fix dashboard CPU utilisation graphs for multi-core systems
  charts/monitoring/grafana/dashboards/kubernetes/nodes-overview.json
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, cherry-pick-approved

#12091 Update GitHub SSH RSA key
  hack/lib.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none

#12089 Fix usercluster manager oom
  pkg/applications/helmclient/client.go
  pkg/applications/helmclient/client_integration_test.go
  pkg/applications/test/kubernetes.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#12100 Test all Helm charts regardless of their change status
  charts/logging/loki/test/default.yaml.out
  charts/logging/loki/test/values.example.ce.yaml.out
  charts/logging/loki/test/values.example.ee.yaml.out
  charts/minio/test/values.example.ce.yaml.out
  charts/minio/test/values.example.ee.yaml.out
  charts/mla/grafana/test/config.yaml.out
  charts/mla/grafana/test/default.yaml.out
  charts/oauth/test/default.yaml.out
  charts/oauth/test/values.example.ce.yaml.out
  charts/oauth/test/values.example.ee.yaml.out
  hack/ci/test-helm-charts.sh
Labels: kind/cleanup, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#12106 [release/v2.20] Update MLA to v0.2.6
  hack/ci/setup-mla.sh
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, cherry-pick-approved

#12103 Support for configuring additional volumes for the UI
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  hack/ci/testdata/seed.yaml
  pkg/apis/kubermatic/v1/configuration.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/operator/master/resources/kubermatic/ui.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
Labels: kind/bug, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/tbd, backport-needed

#12107 [release/v2.22] Support for configuring additional volumes for the UI
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/apis/kubermatic/v1/configuration.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/operator/master/resources/kubermatic/ui.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
Labels: kind/bug, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12110 Move mutation code for clusters into its own package
  pkg/mutation/cluster/mutation.go
  pkg/mutation/mutation.go
  pkg/webhook/cluster/mutation/mutator.go
Labels: kind/cleanup, size/L, lgtm, approved, release-note-none, dco-signoff: yes, docs/none

#12102 Update kube-state-metrics to v2.8.2
  charts/monitoring/kube-state-metrics/Chart.yaml
  charts/monitoring/kube-state-metrics/templates/cluster-role-binding.yaml
  charts/monitoring/kube-state-metrics/templates/cluster-role.yaml
  charts/monitoring/kube-state-metrics/templates/deployment.yaml
  charts/monitoring/kube-state-metrics/templates/role.yaml
  charts/monitoring/kube-state-metrics/templates/service-account.yaml
  charts/monitoring/kube-state-metrics/templates/service.yaml
  charts/monitoring/kube-state-metrics/values.yaml
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12096 Update VMware Cloud Director CSI driver
  addons/csi/vmware-cloud-director/csi-controller.yaml
  addons/csi/vmware-cloud-director/csi-node.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12112 Correct reference to image pull secret in iap chart
  charts/iap/templates/deployments.yaml
Labels: kind/cleanup, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, docs/none

#12113 remove nodemigration code
  pkg/controller/master-controller-manager/cluster-template-synchronizer/controller.go
  pkg/controller/seed-controller-manager/initial-machinedeployment-controller/controller.go
  pkg/controller/shared/nodedeployment-migration/api/types.go
  pkg/controller/shared/nodedeployment-migration/machine/common.go
  pkg/controller/shared/nodedeployment-migration/machine/machinedeployment.go
  pkg/controller/shared/nodedeployment-migration/machinedeployment.json
  pkg/controller/shared/nodedeployment-migration/migrate.go
  pkg/controller/shared/nodedeployment-migration/migrate_test.go
  pkg/controller/shared/nodedeployment-migration/nodedeployment.json
Labels: kind/cleanup, size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none
