Repository kubermatic/kubermatic, pull requests merged in 2023-05, with the labels that each got.

#12212 Upgrade Anexia CCM to v1.5.4
  pkg/resources/cloudcontroller/anexia.go
Labels: kind/cleanup, kind/feature, ok-to-test, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#12195 Recover from Grafana data loss
  pkg/controller/seed-controller-manager/mla/dashboard_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/dashboard_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/grafana.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none, backport-needed

#12211 Add component override for usercluster-controller
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/resources/resources.go
  pkg/resources/usercluster/deployment.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12220 [release/v2.21] recover from Grafana data loss (#12195)
  pkg/controller/seed-controller-manager/mla/dashboard_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/dashboard_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/grafana.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller_test.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved

#12214 [release/v2.21] Upgrade Anexia CCM to v1.5.4
  pkg/resources/cloudcontroller/anexia.go
Labels: ok-to-test, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12221 set metering output prefix to seed name
  pkg/controller/operator/seed/resources/metering/wrappers_ce.go
  pkg/controller/operator/seed/resources/metering/wrappers_ee.go
  pkg/ee/metering/cronjob.go
  pkg/ee/metering/reconcile.go
  pkg/install/images/images.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12217 [User-mla]Added a filter which allows blackbox exporter to query without authz filter for health endpoint
  charts/mla/alertmanager-proxy/templates/proxy-configmap.yaml
  charts/mla/alertmanager-proxy/test/default.yaml.out
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management, kind/chore, docs/provided

#12194 Add kubermatic_seed_* Prometheus metrics on the master cluster
  charts/monitoring/prometheus/rules/kubermatic-master-kubermatic.yaml
  charts/monitoring/prometheus/rules/src/kubermatic-master/kubermatic.yaml
  cmd/master-controller-manager/main.go
  pkg/collectors/seed.go
  pkg/controller/master-controller-manager/seed-status-controller/reconciler.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#12225 update to kube-state-metrics 2.8.2
  addons/kube-state-metrics/deployment.yaml
  pkg/resources/kubestatemetrics/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.24.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.25.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.25.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-aws-1.26.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.26.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.25.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.25.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-azure-1.26.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.26.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.25.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.26.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.25.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.25.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.26.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.26.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.24.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.25.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.26.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.25.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.25.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.26.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.26.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.25.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.25.0-kube-state-metrics.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.26.0-kube-state-metrics-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.26.0-kube-state-metrics.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/none

#12226 bump kube-rbac-proxy to 0.14.1
  addons/node-exporter/daemonset.yaml
  charts/monitoring/node-exporter/values.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12227 Bump AWS CCM/CSI
  addons/Makefile
  addons/csi/aws-ebs/driver.yaml
  pkg/resources/cloudcontroller/aws.go
  pkg/resources/test/fixtures/deployment-aws-1.26.0-aws-cloud-controller-manager-externalCloudProvider.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/none

#12229 Bump vSphere CCM/CSI
  addons/csi/vsphere/csi-migration-webhook.yaml
  addons/csi/vsphere/csi-snapshot-validatingwebhook.yaml
  addons/csi/vsphere/setup-snapshot-controller.yaml
  addons/csi/vsphere/vsphere-csi-driver.yaml
  pkg/resources/cloudcontroller/vsphere.go
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.25.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.26.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#12222 Bump Azure CCM/CSI
  addons/azure-cloud-node-manager/cloud-node-manager.yaml
  addons/csi/azure-disk/csi-azuredisk-controller.yaml
  addons/csi/azure-disk/csi-azuredisk-driver.yaml
  addons/csi/azure-disk/csi-azuredisk-node.yaml
  addons/csi/azure-file/csi-azurefile-controller.yaml
  addons/csi/azure-file/csi-azurefile-driver.yaml
  addons/csi/azure-file/csi-azurefile-node.yaml
  pkg/resources/cloudcontroller/azure.go
  pkg/resources/test/fixtures/deployment-azure-1.24.0-azure-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.25.0-azure-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.26.0-azure-cloud-controller-manager-externalCloudProvider.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/none

#12243 Update cert-manager to 1.11.1
  charts/cert-manager/Chart.yaml
  charts/cert-manager/test/default.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12228 Bump Openstack CCM/CSI
  .prow/provider-openstack.yaml
  addons/csi/openstack/controllerplugin-rbac.yaml
  addons/csi/openstack/controllerplugin.yaml
  addons/csi/openstack/nodeplugin.yaml
  pkg/resources/cloudcontroller/openstack.go
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-openstack-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.25.0-openstack-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.26.0-openstack-cloud-controller-manager-externalCloudProvider.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/none

#12242 Update oauth2-proxy to 7.4.0
  charts/iap/Chart.yaml
  charts/iap/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12247 [release/v2.21] fix usercluster manager oom (#12090)
  pkg/applications/helmclient/client.go
  pkg/applications/helmclient/client_test.go
  pkg/applications/test/kubernetes.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved

#12238 bump configmap-reload to 0.8.0
  charts/monitoring/alertmanager/values.yaml
  charts/monitoring/prometheus/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12239 Update helm-exporter to 1.2.5
  charts/monitoring/helm-exporter/Chart.yaml
  charts/monitoring/helm-exporter/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12237 Bump Alertmanager to 0.25.0
  charts/monitoring/alertmanager/Chart.yaml
  charts/monitoring/alertmanager/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12233 Bump Dex to 2.36.0
  charts/oauth/Chart.yaml
  charts/oauth/test/default.yaml.out
  charts/oauth/test/image-pull-secret.yaml.out
  charts/oauth/test/values.example.ce.yaml.out
  charts/oauth/test/values.example.ee.yaml.out
  charts/oauth/values.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12235 update blackbox-exporter to 0.23.0
  charts/monitoring/blackbox-exporter/Chart.yaml
  charts/monitoring/blackbox-exporter/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12236 bump Karma to 0.114
  charts/monitoring/karma/Chart.yaml
  charts/monitoring/karma/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12245 update k8s-dns-node-cache to 1.22.20
  pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/deamonset.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#12234 bump nginx-ingress-controller to 1.7.1
  charts/nginx-ingress-controller/Chart.lock
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12240 Update Grafana to 9.5.1
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/grafana/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12241 update Minio to RELEASE.2023-05-04T21-44-30Z, change to quay.io
  charts/minio/Chart.yaml
  charts/minio/test/image-pull-secret.yaml.out
  charts/minio/test/values.example.ce.yaml.out
  charts/minio/test/values.example.ee.yaml.out
  charts/minio/values.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12261 openstack: don't override input for floating IP for default MD from Cluster
  pkg/machine/provider/openstack.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, backport-needed

#12269 Fix cilium v1.12 and v1.13
  addons/cilium/cilium_v1.11.yaml
  addons/cilium/cilium_v1.12.yaml
  addons/hubble/hubble_v1.11.yaml
  addons/hubble/hubble_v1.12.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/networking, docs/none

#12275 New alert NodeTimeDrift
  charts/monitoring/prometheus/rules/general-node-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/node-exporter.yaml
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#12273 [release/v2.20] Update cilium to v1.11 to latest patch
  addons/cilium/cilium.yaml
  addons/hubble/hubble.yaml
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved

#12283 [release/v2.22] Install all CRDs on master (for now)
  hack/update-codegen.sh
  pkg/crd/k8c.io/kubermatic.k8c.io_addons.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_alertmanagers.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplateinstances.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdbackupconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdrestores.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_mlaadminsettings.yaml
  pkg/crd/k8c.io/operatingsystemmanager.k8c.io_customoperatingsystemprofiles.yaml
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, kind/regression, cherry-pick-approved

#12286 [release/v2.20] Update changelogs
  CHANGELOG.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, cherry-pick-approved

#12284 [release/v2.22] Update changelogs
  docs/changelogs/CHANGELOG-2.20.md
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.22.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#12291 [release/v2.21] Update changelogs
  CHANGELOG.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, cherry-pick-approved

#12280 remove auto-update rule for 1.23->1.24
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, kind/deprecation, docs/none

#12293 fix path traversal in mirror-images command
  pkg/install/images/images.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#12295 [release/v2.22] Update changelog with latest securit patch
  docs/changelogs/CHANGELOG-2.22.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, cherry-pick-approved

#12296 Update changelogs after May patch release
  docs/changelogs/CHANGELOG-2.20.md
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.22.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#12306 Use eu-west-1 for AWS E2E tests
  cmd/conformance-tester/README.md
  hack/ci/run-conformance-tests.sh
  hack/ci/run-dualstack-e2e-test.sh
  hack/ci/testdata/seed.yaml
  hack/run-ccm-migration-e2e-test-in-kind.sh
  hack/run-conformance-tests.sh
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none, backport-needed

#12311 [release/v2.22] Use eu-west-1 for AWS E2E tests
  cmd/conformance-tester/README.md
  hack/ci/run-conformance-tests.sh
  hack/ci/run-dualstack-e2e-test.sh
  hack/ci/testdata/seed.yaml
  hack/run-ccm-migration-e2e-test-in-kind.sh
  hack/run-conformance-tests.sh
Labels: size/S, kind/failing-test, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12297 Add canal 3.25 support
  addons/canal/canal_v3.25.yaml
  pkg/cni/version.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, sig/networking, docs/none

#12303 Set successful job limit for etcd-defragger to 1
  pkg/resources/etcd/cronjob.go
  pkg/resources/test/fixtures/cronjob-aws-1.24.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-aws-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-aws-1.25.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-aws-1.25.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-aws-1.26.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-aws-1.26.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-aws-1.27.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-aws-1.27.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.24.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.25.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.25.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.26.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.26.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.27.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.27.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.25.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.26.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.27.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.24.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.25.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.25.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.26.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.26.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.27.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.27.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-gcp-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-gcp-1.25.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-gcp-1.26.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-gcp-1.27.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.24.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.25.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.25.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.26.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.26.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.27.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.27.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.24.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.25.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.25.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.26.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.26.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.27.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.27.0-etcd-defragger.yaml
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none, backport-needed

#12216 kubermatic-installer: local command
  charts/local-kubevirt/Chart.yaml
  charts/local-kubevirt/crds/customresourcedefinition-cdis.cdi.kubevirt.io.yaml
  charts/local-kubevirt/crds/customresourcedefinition-kubevirts.kubevirt.io.yaml
  charts/local-kubevirt/templates/cdi-cr.yaml
  charts/local-kubevirt/templates/clusterrole-cdi-operator-cluster.yaml
  charts/local-kubevirt/templates/clusterrole-kubevirt-operator.yaml
  charts/local-kubevirt/templates/clusterrole-kubevirt.io:operator.yaml
  charts/local-kubevirt/templates/clusterrolebinding-cdi-operator.yaml
  charts/local-kubevirt/templates/clusterrolebinding-kubevirt-operator.yaml
  charts/local-kubevirt/templates/configmap-cdi-operator-leader-election-helper.yaml
  charts/local-kubevirt/templates/deployment-cdi-operator.yaml
  charts/local-kubevirt/templates/deployment-virt-operator.yaml
  charts/local-kubevirt/templates/kubevirt-cr.yaml
  charts/local-kubevirt/templates/namespace-cdi.yaml
  charts/local-kubevirt/templates/namespace-kubevirt.yaml
  charts/local-kubevirt/templates/priorityclass-kubevirt-cluster-critical.yaml
  charts/local-kubevirt/templates/role-cdi-operator.yaml
  charts/local-kubevirt/templates/role-kubevirt-operator.yaml
  charts/local-kubevirt/templates/rolebinding-cdi-operator.yaml
  charts/local-kubevirt/templates/rolebinding-kubevirt-operator-rolebinding.yaml
  charts/local-kubevirt/templates/serviceaccount-cdi-operator.yaml
  charts/local-kubevirt/templates/serviceaccount-kubevirt-operator.yaml
  charts/local-kubevirt/update.bash
  charts/local-kubevirt/values.yaml
  charts/oauth/templates/ingress.yaml
  cmd/kubermatic-installer/cmd_local.go
  cmd/kubermatic-installer/local_kind_resources.go
  cmd/kubermatic-installer/main_ce.go
  go.mod
  go.sum
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#12305 Limit EtcdDatabaseHighFragmentationRatio alert to 100MB+
  pkg/resources/prometheus/configmap-rules.go
  pkg/resources/test/fixtures/configmap-aws-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-aws-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-aws-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.26.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-aws-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.27.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-aws-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.26.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.27.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.26.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.27.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-gcp-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-gcp-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-gcp-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-gcp-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.26.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.27.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.26.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.27.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.27.0-prometheus.yaml
Labels: kind/feature, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none, backport-needed

#12318 [release/v2.22] Limit etcdDatabaseHighFragmentationRatio to 100MB+
  pkg/resources/prometheus/configmap-rules.go
  pkg/resources/test/fixtures/configmap-aws-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-aws-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-aws-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-aws-1.26.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-aws-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-azure-1.26.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-azure-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-bringyourown-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.26.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-digitalocean-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-gcp-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-gcp-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-gcp-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.26.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-openstack-1.26.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.24.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.24.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.25.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.25.0-prometheus.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.26.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/configmap-vsphere-1.26.0-prometheus.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12312 [release/v2.21] Use eu-west-1 for AWS E2E tests
  hack/ci/run-cilium-e2e-test.sh
  hack/ci/run-conformance-tests.sh
  hack/ci/run-konnectivity-e2e-test.sh
  hack/ci/testdata/seed.yaml
  hack/run-conformance-tests.sh
  pkg/test/dualstack/cloud_providers.go
  pkg/test/e2e/api/dc_test.go
Labels: size/S, kind/failing-test, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12308 [release/v2.22] OSM Migration: Remove redundant Webhooks from seed
  pkg/controller/operator/seed/reconciler.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12319 [release/v2.21] Set succesful limit for defragger job to 1
  pkg/resources/etcd/cronjob.go
  pkg/resources/test/fixtures/cronjob-aws-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-aws-1.23.5-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-aws-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.22.1-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.23.5-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.23.5-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.24.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.23.5-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.23.5-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.22.1-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.23.5-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.23.5-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.24.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.22.1-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.22.1-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.23.5-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.23.5-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.24.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.24.0-etcd-defragger.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12317 [release/v2.22] Set succesful limit for defragger job to 1
  pkg/resources/etcd/cronjob.go
  pkg/resources/test/fixtures/cronjob-aws-1.24.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-aws-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-aws-1.25.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-aws-1.25.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-aws-1.26.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-aws-1.26.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.24.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.25.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.25.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.26.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-azure-1.26.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.25.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-bringyourown-1.26.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.24.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.25.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.25.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.26.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-digitalocean-1.26.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-gcp-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-gcp-1.25.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-gcp-1.26.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.24.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.25.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.25.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.26.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-openstack-1.26.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.24.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.24.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.25.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.25.0-etcd-defragger.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.26.0-etcd-defragger-externalCloudProvider.yaml
  pkg/resources/test/fixtures/cronjob-vsphere-1.26.0-etcd-defragger.yaml
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12320 Bump Cilium CNI Application to 1.13.3
  go.mod
  go.sum
  pkg/cni/cilium/cilium-mirror-chart.sh
  pkg/cni/cilium/cilium.go
  pkg/cni/version.go
  pkg/validation/cluster_test.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/networking, docs/none

#12313 Make etcd anti-affinity configurable via component override
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/resources/antiaffinity.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/controllermanager/deployment.go
  pkg/resources/dns/dns.go
  pkg/resources/etcd/statefulset.go
  pkg/resources/kubernetes-dashboard/deployment.go
  pkg/resources/metrics-server/deployment.go
  pkg/resources/nodeportproxy/nodeportproxy.go
  pkg/resources/scheduler/deployment.go
Labels: kind/feature, size/L, kind/api-change, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12314 Increase metrics server write timeout
  pkg/metrics/server/server.go
Labels: kind/bug, ok-to-test, lgtm, approved, release-note, size/XS, dco-signoff: yes, docs/none
