Repository kubermatic/kubermatic, pull requests merged in 2023-12, with the labels that each got.

#12869 Roll-up dependabot PRs
  go.mod
  go.sum
Labels: kind/cleanup, lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, docs/none

#12854 Fixing the values.yaml structure for cert-manager chart to match upstream chart configuration
  charts/cert-manager/test/override-controller-test.yaml
  charts/cert-manager/test/override-controller-test.yaml.out
  charts/cert-manager/values.yaml
Labels: kind/bug, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#12872 Fixed the ClusterRole resources for VPA 0.14
  pkg/controller/operator/common/vpa/rbac.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none, backport-needed

#12861 Use JoinPath to construct vSphere url
  pkg/provider/cloud/vsphere/client.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#12886 Create CiliumNetworkPolicies for apiserver when feature gate is set
  .wwhrd.yml
  go.mod
  go.sum
  hack/reconciling.yaml
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/features/features.go
  pkg/resources/apiserver/networkpolicy.go
  pkg/resources/reconciling/zz_generated_reconcile.go
  pkg/resources/resources.go
Labels: kind/bug, kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/tbd

#12887 Adjust the memory requests/limits for VerticalPodAutoscaler components
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, docs/none

#12892 Revert "Create CiliumNetworkPolicies for apiserver when feature gate is set"
  .wwhrd.yml
  go.mod
  go.sum
  hack/reconciling.yaml
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/features/features.go
  pkg/resources/apiserver/networkpolicy.go
  pkg/resources/reconciling/zz_generated_reconcile.go
  pkg/resources/resources.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#12897 Update to Go 1.21.5
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  go.mod
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none

#12898 [release/v2.24] Update to Go 1.21.5
  .golangci.yml
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  charts/monitoring/grafana/dashboards/kubernetes/kubelets-overview.json
  charts/monitoring/grafana/dashboards/kubernetes/kubelets.json
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
  pkg/cni/cilium/cilium.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, sig/networking, kind/chore, cherry-pick-approved

#12900 [release/v2.23] Update to Go 1.20.12
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved

#12878 cinder csi: allow topology support customization
  addons/csi/openstack/controllerplugin.yaml
  cmd/conformance-tester/pkg/clients/client_kube.go
  docs/zz_generated.addondata.go.txt
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/addon/types.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/provider/cloud/openstack/provider.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#12907 Merge sig-virtualization to sig-cluster-management
  OWNERS
  OWNERS_ALIASES
  pkg/controller/user-cluster-controller-manager/kubevirt-vmi-eviction/OWNERS
  pkg/provider/cloud/kubevirt/OWNERS
Labels: kind/cleanup, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/virtualization, docs/none

#12909 Upgrade Anexia CCM to v1.5.5
  pkg/resources/cloudcontroller/anexia.go
Labels: kind/bug, kind/cleanup, ok-to-test, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#12911 [release/v2.24] Upgrade Anexia CCM to v1.5.5
  pkg/resources/cloudcontroller/anexia.go
Labels: kind/bug, kind/cleanup, ok-to-test, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12910 [release/v2.23] Upgrade Anexia CCM to v1.5.5
  pkg/resources/cloudcontroller/anexia.go
Labels: kind/bug, kind/cleanup, ok-to-test, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12901 Fix generated Velero CRDs
  hack/update-velero-crds.sh
  pkg/ee/cluster-backup/resources/user-cluster/static/backuprepositories.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/backups.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/backupstoragelocations.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/datadownloads.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/datauploads.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/deletebackuprequests.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/downloadrequests.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/podvolumebackups.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/podvolumerestores.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/restores.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/schedules.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/serverstatusrequests.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/volumesnapshotlocations.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, docs/none

#12917 [release/v2.22] Add changelog for v2.22.11
  docs/changelogs/CHANGELOG-2.22.md
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved

#12918 [release/v2.23] Add changelog for v2.23.9
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#12919 [release/v2.24] Add changelog for v2.24.1
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#12912 Add release notes for December patch releases
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none
