Repository kubermatic/kubermatic, pull requests merged in 2023-04, with the labels that each got.

#12120 Bump csi external-snapshot webhook server image to v6.0.1
  addons/csi/openstack/snapshot-webhook.yaml
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/none, backport-needed

#12125 Upgrade Anexia CCM to v1.5.3
  pkg/resources/cloudcontroller/anexia.go
Labels: kind/cleanup, kind/feature, ok-to-test, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#12119 [release/v2.22] Install CRDs needed on standalone Seed when provisioning Seeds
  hack/update-codegen.sh
  hack/verify-boilerplate.sh
  pkg/crd/fs.go
  pkg/crd/k8c.io/kubermatic.k8c.io_groupprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipamallocations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipampools.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_resourcequotas.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_usersshkeys.yaml
  pkg/crd/k8s.io/autoscaling.k8s.io_verticalpodautoscalercheckpoints.yaml
  pkg/crd/k8s.io/autoscaling.k8s.io_verticalpodautoscalers.yaml
Labels: kind/bug, size/XL, lgtm, approved, release-note, dco-signoff: yes, kind/regression, cherry-pick-approved

#12131 clear config finalizer in init seed
  pkg/controller/operator/seed-init/reconciler.go
  pkg/controller/shared/seed-controller-lifecycle/seed_controller_lifecycle.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#12132 [release/v2.21] Upgrade Anexia CCM to v1.5.3
  pkg/resources/cloudcontroller/anexia.go
Labels: kind/cleanup, kind/feature, needs-ok-to-test, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12137 explicitly remove finalizer on kubermatic configuration reconciler
  pkg/controller/master-controller-manager/seed-sync/resources.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#12133 [release/v2.22] Upgrade Anexia CCM to v1.5.3
  pkg/resources/cloudcontroller/anexia.go
Labels: kind/cleanup, kind/feature, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12140 installer: mla: fix flags for skipping minio-related components
  pkg/install/stack/usercluster-mla/stack.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none, backport-needed

#12144 Mirror metering images for EE in kubermatic-installer
  pkg/controller/operator/seed/resources/metering/wrappers_ce.go
  pkg/controller/operator/seed/resources/metering/wrappers_ee.go
  pkg/ee/metering/cronjob.go
  pkg/ee/metering/reconcile.go
  pkg/install/images/images.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12143 [release/v2.22] Docker suffix bump after golang 1.19.8 patch
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved

#12147 VCD: fix API credential validation for clusters
  pkg/provider/cloud/vmwareclouddirector/provider.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#12130 Mirror etcd-launcher and gatekeeper images in kubermatic-installer
  pkg/install/images/images.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#12139 Explicitly unset SA for metering CronJob
  pkg/ee/metering/cronjob.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, docs/none

#12142 Docker suffix bump after golang 1.20.3 patch
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none

#12152 Configuration for enabling/enforcing upgrades for machine deployments through UI
  pkg/apis/kubermatic/v1/settings.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
Labels: customer-request, kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12114 Update helm/kubetl binary and remove locksmith dep
  Dockerfile
  go.mod
  go.sum
  pkg/apis/kubermatic/v1/cluster.go
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#12149 deploy user-mla iap on dev
  hack/ci/deploy.sh
Labels: kind/cleanup, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#12153 allow patch version upgrades for cni
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, docs/none

#12163 [release/v2.21] Add changelog for 2.21.8
  CHANGELOG.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#12170 Deploy iap only when configured in values
  hack/ci/deploy.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#12166 [release/v2.22] Include Kubernetes patch releases for April 2023
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved

#12165 Include Kubernetes patch releases for April 2023
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none

#12167 [release/v2.21] Include Kubernetes 1.24.13 (April 2023 patch release)
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/defaults/defaults.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, cherry-pick-approved

#12175 Add setting to disable Changelog popup in KKP dashboard
  pkg/apis/kubermatic/v1/settings.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
Labels: customer-request, kind/feature, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#12177 Sync RuleGroup CRD to Seeds
  hack/update-codegen.sh
  pkg/crd/k8c.io/kubermatic.k8c.io_rulegroups.yaml
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/regression, docs/none

#12178 [release/v2.22] Sync RuleGroup CRD to Seeds
  hack/update-codegen.sh
  pkg/crd/k8c.io/kubermatic.k8c.io_rulegroups.yaml
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/regression, cherry-pick-approved

#12060 RFC: Proposal for Cluster Mesh
  docs/proposals/cluster-mesh.md
Labels: size/L, kind/documentation, lgtm, approved, release-note-none, kind/design, dco-signoff: yes, docs/none

#12182 fix MLA constantly upserting Grafana datasources
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none, backport-needed

#12082 Add option to disable default network policies in KubeVirt cluster
  codegen/example-yaml/main.go
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/provider/cloud/kubevirt/provider.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/virtualization, docs/tbd

#12184 [release/v2.22] Align versions of monitoring addons and charts
  addons/kube-state-metrics/deployment.yaml
  addons/node-exporter/daemonset.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved

#12187 Improve error messages in rbac-controller's project sync
  pkg/controller/master-controller-manager/rbac/sync_project.go
Labels: kind/cleanup, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#12190 Use serializable etcd health endpoint
  pkg/resources/etcd/statefulset.go
  pkg/resources/test/fixtures/statefulset-aws-1.24.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.24.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.25.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.25.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.26.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.26.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.24.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.24.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.25.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.25.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.26.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.26.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.24.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.25.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.26.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.24.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.24.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.25.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.25.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.26.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.26.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.24.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.25.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.26.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.24.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.24.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.25.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.25.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.26.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.26.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.24.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.24.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.25.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.25.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.26.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.26.0-etcd.yaml
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12179 [KKP3] Refactor MLA e2e tests
  .prow/features.yaml
  cmd/kubermatic-installer/cmd_deploy.go
  hack/ci/run-mla-e2e-tests.sh
  hack/ci/setup-kubermatic-mla-in-kind.sh
  pkg/controller/seed-controller-manager/mla-controller/grafana/client.go
  pkg/controller/seed-controller-manager/mla-controller/grafana/fake.go
  pkg/controller/seed-controller-manager/mla-controller/mla.go
  pkg/controller/seed-controller-manager/mla-controller/reconciler_alertmanager.go
  pkg/controller/seed-controller-manager/mla-controller/reconciler_cleanup.go
  pkg/controller/seed-controller-manager/mla-controller/reconciler_cortex_ratelimit.go
  pkg/controller/seed-controller-manager/mla-controller/reconciler_grafana_dashboard.go
  pkg/controller/seed-controller-manager/mla-controller/reconciler_grafana_datasource.go
  pkg/controller/seed-controller-manager/mla-controller/reconciler_grafana_org.go
  pkg/controller/seed-controller-manager/mla-controller/reconciler_grafana_user.go
  pkg/controller/seed-controller-manager/mla-controller/reconciler_grafana_user_test.go
  pkg/controller/seed-controller-manager/mla-controller/reconciler_rulegroup.go
  pkg/controller/seed-controller-manager/mla-controller/reconciler_rulegroup_sync.go
  pkg/test/e2e/mla/mla_test.go
Labels: kind/cleanup, size/XL, kind/failing-test, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management

#12198 Add option to restrict project deletion to admin
  pkg/apis/kubermatic/v1/settings.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12199 Bump Cilium CNI Application to 1.13.2
  pkg/cni/cilium/cilium-mirror-chart.sh
  pkg/cni/cilium/cilium.go
  pkg/cni/version.go
  pkg/validation/cluster_test.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/networking, docs/none

#12201 addons: openstack: SA for CSI snapshot webhook
  addons/csi/openstack/snapshot-webhook.yaml
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none
