Repository kubermatic/kubermatic, pull requests merged in 2023-11, with the labels that each got.

#12806 [release/v2.23] Fix invalid YAML for charts/mla/minio values
  charts/mla/minio/values.yaml
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved, do-not-merge/code-freeze

#12816 Use regex for hostnames in seed MLA dashboard "Resource Usage per Namespace"
  charts/monitoring/grafana/dashboards/kubernetes/node-namespaces.json
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#12817 [release/v2.22] charts/mla/grafana: use correct `job=node-exporter` label on CPU queries
  charts/mla/grafana/files/kkp-kubernetes-nodes-overview.json
  charts/mla/grafana/test/config.yaml.out
  charts/mla/grafana/test/default.yaml.out
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved, do-not-merge/code-freeze

#12813 Migrate vSphere `CSIDriver` resource on upgrade to match upstream
  pkg/controller/seed-controller-manager/addon/addon_controller.go
Labels: kind/bug, kind/cleanup, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, kind/regression, docs/none, code-freeze-approved

#12822 bump metering to v1.1.1
  pkg/ee/metering/reconcile.go
Labels: release-note-action-required, lgtm, approved, size/XS, dco-signoff: yes, kind/chore, docs/provided, code-freeze-approved

#12823 [release/v2.23] bump metering to v1.0.5
  pkg/ee/metering/reconcile.go
Labels: release-note-action-required, lgtm, approved, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved, do-not-merge/code-freeze

#12824 [release/v2.22] bump metering to v1.0.5
  pkg/ee/metering/reconcile.go
Labels: release-note-action-required, lgtm, approved, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved, do-not-merge/code-freeze

#12829 Properly format components table generated from `hack/ci/update-docs.sh`
  hack/ci/update-docs.sh
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#12833 [release/v2.22] Fix queries for hostnames
  charts/monitoring/grafana/dashboards/kubernetes/node-namespaces.json
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, cherry-pick-approved, do-not-merge/code-freeze

#12830 fix: Add exclusions to immutable values validation in Cilium
  pkg/cni/cilium/cilium.go
  pkg/cni/cilium/cilium_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/networking, docs/none, code-freeze-approved

#12839 Document requirement that folder structure needs to exist
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#12841 Remove deprecated setting in cilium application
  pkg/cni/cilium/cilium.go
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/networking, docs/none, code-freeze-approved

#12835 [release/v2.21] Update changelog for v2.21.15
  CHANGELOG.md
Labels: kind/documentation, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, cherry-pick-approved, do-not-merge/code-freeze

#12836 [release/v2.22] Update changelog for v2.22.10
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.22.md
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved, do-not-merge/code-freeze

#12845 Add 2.23.8 changelog
  docs/changelogs/CHANGELOG-2.23.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none, code-freeze-approved

#12844 [release/v2.23] Add 2.23.8 changelog
  docs/changelogs/CHANGELOG-2.23.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, cherry-pick-approved, do-not-merge/code-freeze

#12758 Add changelog for 2.24.0
  docs/changelogs/CHANGELOG-2.24.md
Labels: size/L, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#12847 charts: bump local-kubevirt to v1.1.0
  charts/local-kubevirt/Chart.yaml
  charts/local-kubevirt/crds/customresourcedefinition-kubevirts.kubevirt.io.yaml
  charts/local-kubevirt/templates/clusterrole-kubevirt-operator.yaml
  charts/local-kubevirt/templates/deployment-virt-operator.yaml
  charts/local-kubevirt/templates/role-kubevirt-operator.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12849 application-catalog: make the default application yaml files not exeutable
  pkg/ee/default-application-catalog/applicationdefinitions/cert-manager-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/falco-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/kube-vip-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/metallb-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/nginx-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/trivy-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/trivy-operator-app.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none

#12421 Use vSphere infraManagement user creds if defined
  pkg/resources/credentials.go
  pkg/resources/credentials_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12843 Make metering retention configurable
  codegen/example-yaml/main.go
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  hack/ci/testdata/seed.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/defaulting/seed.go
  pkg/ee/metering/prometheus/sts.go
  pkg/validation/metering.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12850 charts: bump local-kubevirt cdi to 1.58.0
  charts/local-kubevirt/crds/customresourcedefinition-cdis.cdi.kubevirt.io.yaml
  charts/local-kubevirt/templates/clusterrole-cdi-operator-cluster.yaml
  charts/local-kubevirt/templates/deployment-cdi-operator.yaml
  charts/local-kubevirt/templates/role-cdi-operator.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12684 Improve addon rendering/testing performance
  cmd/kubermatic-installer/cmd_mirror_images.go
  cmd/seed-controller-manager/controllers.go
  codegen/addon-resources/main.go
  pkg/addon/addon.go
  pkg/addon/types.go
  pkg/addon/types_test.go
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/controller/seed-controller-manager/addon/addon_controller_test.go
  pkg/install/images/addons.go
  pkg/install/images/images.go
  pkg/install/images/images_test.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/networking, docs/none

#12827 Deploy velero into user clusters.
  .golangci.yml
  cmd/seed-controller-manager/main.go
  cmd/seed-controller-manager/wrappers_ee.go
  go.mod
  go.sum
  hack/reconciling.yaml
  hack/update-velero-crds.sh
  hack/verify-boilerplate.sh
  hack/versions.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/ee/cluster-backup/controller.go
  pkg/ee/cluster-backup/doc.go
  pkg/ee/cluster-backup/resources/seed-cluster/deployment.go
  pkg/ee/cluster-backup/resources/seed-cluster/secret.go
  pkg/ee/cluster-backup/resources/user-cluster/cluster-backup.go
  pkg/ee/cluster-backup/resources/user-cluster/crds.go
  pkg/ee/cluster-backup/resources/user-cluster/static/backuprepositories.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/backups.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/backupstoragelocations.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/datadownloads.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/datauploads.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/deletebackuprequests.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/downloadrequests.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/podvolumebackups.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/podvolumerestores.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/restores.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/schedules.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/serverstatusrequests.yaml
  pkg/ee/cluster-backup/resources/user-cluster/static/volumesnapshotlocations.yaml
  pkg/resources/data.go
  pkg/resources/reconciling/zz_generated_reconcile.go
  pkg/resources/resources.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/tbd

#12756 [User-MLA] Dropped unused metrics and reduce label dimentions for many high cardinality metrics
  addons/kube-state-metrics/scrape-config.yaml
  addons/node-exporter/scrape-config.yaml
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/monitoring-agent/configmap.go
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/monitoring-agent/deployment.go
Labels: kind/feature, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12838 Add NodeSelector to EtcdStatefulSetSettings
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/resources/etcd/statefulset.go
Labels: kind/feature, kind/api-change, ok-to-test, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12818 improve logging in installer
  pkg/ee/default-application-catalog/application_catalog.go
  pkg/install/stack/kubermatic-master/certmanager.go
  pkg/install/stack/kubermatic-master/nginxingress.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/stack/kubermatic-seed/stack.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#12865 update to k8c.io/reconciler 0.5, ctrl-runtime 0.16.3
  go.mod
  go.sum
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, docs/none

#12868 fix mirror-images command in installer
  cmd/kubermatic-installer/cmd_mirror_images.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none
