Repository kubermatic/kubermatic, pull requests merged in 2023-10, with the labels that each got.

#12663 Added Missing Description to the CRDs Spec
  pkg/apis/kubermatic/v1/addon.go
  pkg/apis/kubermatic/v1/addon_config.go
  pkg/apis/kubermatic/v1/admission_plugin.go
  pkg/apis/kubermatic/v1/alertmanager.go
  pkg/apis/kubermatic/v1/allowed_registry.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/cluster_template_instance.go
  pkg/apis/kubermatic/v1/cluster_templates.go
  pkg/apis/kubermatic/v1/constraint.go
  pkg/apis/kubermatic/v1/constraint_template.go
  pkg/crd/k8c.io/kubermatic.k8c.io_addonconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_admissionplugins.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_alertmanagers.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_allowedregistries.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplateinstances.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_constraints.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_constrainttemplates.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/provided

#12658 [release/v2.21] [vsphere] do not validate the DC's default datastore if the cluster has a custom one (#12655)
  pkg/provider/cloud/vsphere/provider.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12679 Option to disable admin kubeconfig endpoint
  pkg/apis/kubermatic/v1/settings.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
Labels: kind/feature, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#12667 KubeLB CCM integration
  cmd/seed-controller-manager/wrappers_ee.go
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/ee/kubelb/cleanup.go
  pkg/ee/kubelb/controller.go
  pkg/ee/kubelb/doc.go
  pkg/ee/kubelb/resources/kubelb-cluster/deletion.go
  pkg/ee/kubelb/resources/kubelb-cluster/namespace.go
  pkg/ee/kubelb/resources/kubelb-cluster/rbac.go
  pkg/ee/kubelb/resources/kubelb-cluster/secret.go
  pkg/ee/kubelb/resources/seed-cluster/deletion.go
  pkg/ee/kubelb/resources/seed-cluster/deployment.go
  pkg/ee/kubelb/resources/seed-cluster/rbac.go
  pkg/ee/kubelb/resources/seed-cluster/volumes.go
  pkg/ee/kubelb/resources/user-cluster/deletion.go
  pkg/ee/kubelb/resources/user-cluster/role.go
  pkg/ee/kubelb/resources/user-cluster/rolebinding.go
  pkg/resources/resources.go
Labels: kind/feature, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, ee, docs/none

#12685 Enhancements for KubeLB
  cmd/seed-controller-manager/wrappers_ee.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/seed-controller-manager/kubernetes/health.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/defaulting/cluster.go
  pkg/ee/kubelb/resources/seed-cluster/deletion.go
  pkg/ee/kubelb/resources/seed-cluster/deployment.go
  pkg/resources/resources.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12686 Remove Zenhub guide
  README.md
  Zenhub.md
Labels: kind/cleanup, size/S, lgtm, approved, release-note-none, dco-signoff: yes, docs/none

#12682 [release/v2.22] Option to disable admin kubeconfig endpoint
  pkg/apis/kubermatic/v1/settings.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
Labels: kind/feature, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12688 Update API docs for kubelb
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  hack/update-docs.sh
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/validation/cluster.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#12693 Update KubeLB to latest image
  pkg/ee/kubelb/resources/kubelb-cluster/namespace.go
  pkg/ee/kubelb/resources/seed-cluster/deployment.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, docs/none

#12699 Fix spelling across code base, ignore third-party CRDs
  charts/mla/mla-secrets/values.yaml
  charts/values.example.mla.yaml
  cmd/kubermatic-installer/cmd_mirror_images.go
  cmd/user-cluster-webhook/README.md
  docs/proposals/cni-mgmt-via-applications.md
  docs/proposals/kubevirt-node-placement.md
  docs/proposals/platform-extensions.md
  docs/proposals/user-cluster-controller.md
  docs/proposals/user-cluster-mla.md
  hack/run-expose-strategy-e2e-test-in-kind.sh
  hack/run-seed-controller-manager.sh
  hack/verify-spelling.sh
  pkg/apis/kubermatic/v1/cluster.go
  pkg/applications/providers/template/helm_integration_test.go
  pkg/cni/doc.go
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
  pkg/controller/seed-controller-manager/cni-application-installation-controller/doc.go
  pkg/defaulting/cluster.go
  pkg/provider/cloud/aws/client_test.go
  pkg/provider/cloud/aws/util_test.go
  pkg/provider/cloud/eks/provider.go
  pkg/provider/cloud/gke/provider.go
  pkg/resources/apiserver/deployment.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/networking, docs/none

#12670 Add support for cilium version 1.13.7 & 1.14.2, deprecate 1.13.6 & 1.14.1
  pkg/cni/cilium/cilium-mirror-chart.sh
  pkg/cni/cilium/cilium.go
  pkg/cni/version.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/networking, docs/none

#12668 Add basePath configuration option for vSphere clusters and presets
  .prow/provider-vsphere.yaml
  cmd/conformance-tester/pkg/scenarios/generator.go
  cmd/conformance-tester/pkg/scenarios/vsphere.go
  hack/ci/run-conformance-tests.sh
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/provider/cloud/vsphere/provider.go
  pkg/provider/cloud/vsphere/utils.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/tbd

#12691 OpenVPN deprecation: add notes to related CRD fields
  cmd/conformance-tester/pkg/clients/client_kube.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller.go
  pkg/controller/seed-controller-manager/kubernetes/health.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/seed-controller-manager/monitoring/resources.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/install/images/images.go
  pkg/resources/reconciling/zz_generated_reconcile.go
  pkg/test/e2e/jig/cluster.go
  pkg/validation/cluster.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/provided

#12694 Update curl to 8.4.0 in charts/mla/grafana and util image
  charts/mla/grafana/test/config.yaml.out
  charts/mla/grafana/test/default.yaml.out
  charts/mla/grafana/values.yaml
  hack/images/util/Dockerfile
  hack/images/util/release.sh
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12712 Update to nginx-ingress-controller v1.9.3
  charts/nginx-ingress-controller/Chart.lock
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
  charts/nginx-ingress-controller/values.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#12707 [release/v2.21] Update OSM container image to v1.1.4
  hack/ci/testdata/seed.yaml
  pkg/resources/operatingsystemmanager/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.22.1-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-aws-1.23.5-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-aws-1.24.0-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.22.1-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.23.5-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.24.0-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.22.1-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.23.5-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.24.0-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.22.1-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.23.5-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.24.0-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.22.1-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.23.5-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.24.0-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.22.1-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.23.5-operating-system-manager.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-operating-system-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-operating-system-manager.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, cherry-pick-approved

#12692 Update memory limit of kube-state-metrics to 600Mi
  addons/kube-state-metrics/deployment.yaml
Labels: kind/bug, ok-to-test, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/none

#12713 Fix RBAC for KubeLB
  pkg/ee/kubelb/controller.go
  pkg/ee/kubelb/resources/kubelb-cluster/rbac.go
  pkg/ee/kubelb/resources/user-cluster/role.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, docs/none

#12695 [release/v2.23] Support for cilium version 1.13.7, deprecate 1.13.6
  pkg/cni/cilium/cilium-mirror-chart.sh
  pkg/cni/cilium/cilium.go
  pkg/cni/version.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/networking, cherry-pick-approved

#12680 Added missing description to the KKP CRDs Specs
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/alertmanager.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/etcd_backup_config.go
  pkg/apis/kubermatic/v1/etcd_restore.go
  pkg/apis/kubermatic/v1/external_cluster.go
  pkg/apis/kubermatic/v1/group_project_binding.go
  pkg/apis/kubermatic/v1/ipam_pool.go
  pkg/apis/kubermatic/v1/mla_admin_settings.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/apis/kubermatic/v1/project.go
  pkg/apis/kubermatic/v1/resource_quota.go
  pkg/apis/kubermatic/v1/settings.go
  pkg/apis/kubermatic/v1/user.go
  pkg/apis/kubermatic/v1/user_project_binding.go
  pkg/crd/k8c.io/kubermatic.k8c.io_alertmanagers.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdbackupconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdrestores.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_groupprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipampools.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_mlaadminsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_projects.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_resourcequotas.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_userprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_users.yaml
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/provided

#12715 Support to configure node address type for kubelb
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/ee/kubelb/controller.go
  pkg/ee/kubelb/resources/seed-cluster/deployment.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12716 Verify that Hetzner found server type before using reference
  pkg/provider/cloud/hetzner/provider.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12723 [release/v2.21] Fix spelling across code base, ignore third-party CRDs
  cmd/user-cluster-webhook/README.md
  docs/proposals/kubevirt-node-placement.md
  docs/proposals/platform-extensions.md
  docs/proposals/user-cluster-controller.md
  docs/proposals/user-cluster-mla.md
  hack/ci/push-images.sh
  hack/run-expose-strategy-e2e-test-in-kind.sh
  hack/run-seed-controller-manager.sh
  hack/verify-spelling.sh
  pkg/apis/kubermatic/v1/cluster.go
  pkg/applications/providers/template/helm.go
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
  pkg/defaulting/cluster.go
  pkg/handler/v1/user/user_test.go
  pkg/handler/v2/constraint/constraint.go
  pkg/provider/cloud/aws/client_test.go
  pkg/provider/cloud/aws/util_test.go
  pkg/provider/cloud/eks/provider.go
  pkg/provider/cloud/gke/provider.go
  pkg/resources/apiserver/deployment.go
  pkg/test/e2e/utils/oidc.go
  pkg/validation/application_definition_test.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, cherry-pick-approved

#12721 kubelb: match ports for probes and metrics
  pkg/ee/kubelb/resources/seed-cluster/deployment.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#12725 kubelb: dedicated status condition on cluster
  pkg/apis/kubermatic/v1/cluster.go
  pkg/ee/kubelb/controller.go
Labels: kind/cleanup, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#12714 [release/v2.23] Update to nginx-ingress-controller v1.9.3 (#12712)
  charts/nginx-ingress-controller/Chart.lock
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
  charts/nginx-ingress-controller/values.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, cherry-pick-approved

#12726 Update to `quay.io/kubermatic/util:2.3.1`
  charts/minio/test/enable-ingress.yaml.out
  charts/minio/test/image-pull-secret.yaml.out
  charts/minio/test/values.example.ce.yaml.out
  charts/minio/test/values.example.ee.yaml.out
  charts/minio/values.yaml
  charts/monitoring/grafana/values.yaml
  charts/monitoring/karma/values.yaml
  charts/monitoring/prometheus/values.yaml
  hack/ci/testdata/minio_bucket_job.yaml
  hack/images/util/Dockerfile
  hack/lib.sh
  pkg/controller/master-controller-manager/seed-proxy/resources.go
  pkg/resources/encryption/job.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/none

#12729 [release/v2.21] October changelog update
  CHANGELOG.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved

#12733 [release/v2.23] Update to `quay.io/kubermatic/util:2.3.1`
  charts/minio/test/image-pull-secret.yaml.out
  charts/minio/test/values.example.ce.yaml.out
  charts/minio/test/values.example.ee.yaml.out
  charts/minio/values.yaml
  charts/monitoring/grafana/values.yaml
  charts/monitoring/karma/values.yaml
  charts/monitoring/prometheus/values.yaml
  hack/ci/testdata/minio_bucket_job.yaml
  hack/lib.sh
  pkg/controller/master-controller-manager/seed-proxy/resources.go
  pkg/resources/encryption/job.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, cherry-pick-approved, do-not-merge/code-freeze

#12734 Update kubelb image to v1.0.0-beta.0
  pkg/ee/kubelb/resources/seed-cluster/deployment.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#12731 [release/v2.23] Update changelogs for october patch releases
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved, do-not-merge/code-freeze

#12732 Update changelogs for october patch releases.
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#12735 [release/v2.23] Added missing description to the KKP CRDs Specs (#12680)
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/alertmanager.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/etcd_backup_config.go
  pkg/apis/kubermatic/v1/etcd_restore.go
  pkg/apis/kubermatic/v1/external_cluster.go
  pkg/apis/kubermatic/v1/group_project_binding.go
  pkg/apis/kubermatic/v1/ipam_pool.go
  pkg/apis/kubermatic/v1/mla_admin_settings.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/apis/kubermatic/v1/project.go
  pkg/apis/kubermatic/v1/resource_quota.go
  pkg/apis/kubermatic/v1/settings.go
  pkg/apis/kubermatic/v1/user.go
  pkg/apis/kubermatic/v1/user_project_binding.go
  pkg/crd/k8c.io/kubermatic.k8c.io_alertmanagers.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdbackupconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdrestores.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_groupprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipampools.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_mlaadminsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_projects.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_resourcequotas.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_userprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_users.yaml
Labels: kind/documentation, size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12751 handle more recent RHEL OSImage values in node-labeller controller
  pkg/controller/user-cluster-controller-manager/node-labeler/api/api.go
  pkg/controller/user-cluster-controller-manager/node-labeler/controller_test.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#12739 [release/v2.23] fix Digitalocean CSI addon failing to render
  addons/csi/digitalocean/csi-driver.yaml
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, cherry-pick-approved

#12760 Limit user-ssh-keys-agent cache to specific resource (again)
  pkg/controller/usersshkeysagent/usersshkeys_controller.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, kind/regression, docs/none, code-freeze-approved

#12764 stop throttling KKP controllers
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, docs/none, code-freeze-approved

#12765 Update velero's helm chart apiversion to v2
  charts/backup/velero/Chart.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, kind/chore, docs/none, code-freeze-approved

#12762 [release/v2.23] Bump Cillium version to 1.13.8
  pkg/cni/cilium/cilium-mirror-chart.sh
  pkg/cni/cilium/cilium.go
  pkg/cni/version.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/networking, kind/chore, cherry-pick-approved, do-not-merge/code-freeze

#12753 [release/v2.22] Add support for cilium 1.13.8, deprecate 1.13.0
  pkg/cni/cilium/cilium-mirror-chart.sh
  pkg/cni/cilium/cilium.go
  pkg/cni/version.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/networking, cherry-pick-approved, do-not-merge/code-freeze

#12767 [release/v2.21] Bump Cillium version to 1.12.15
  addons/cilium/cilium_v1.12.yaml
  addons/hubble/hubble_v1.12.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, sig/networking, kind/chore, docs/none, cherry-pick-approved, do-not-merge/code-freeze

#12771 [release/v2.21] stop throttling KKP controllers (#12764)
  docs/zz_generated.kubermaticConfiguration.yaml
  pkg/controller/operator/defaults/defaults.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved, do-not-merge/code-freeze

#12768 fix error message in conformance-tester
  cmd/conformance-tester/main.go
  cmd/conformance-tester/pkg/runner/result.go
  cmd/conformance-tester/pkg/runner/runner.go
  cmd/conformance-tester/pkg/scenarios/alibaba.go
  cmd/conformance-tester/pkg/scenarios/anexia.go
  cmd/conformance-tester/pkg/scenarios/aws.go
  cmd/conformance-tester/pkg/scenarios/azure.go
  cmd/conformance-tester/pkg/scenarios/base.go
  cmd/conformance-tester/pkg/scenarios/digitalocean.go
  cmd/conformance-tester/pkg/scenarios/generator.go
  cmd/conformance-tester/pkg/scenarios/google.go
  cmd/conformance-tester/pkg/scenarios/hetzner.go
  cmd/conformance-tester/pkg/scenarios/kubevirt.go
  cmd/conformance-tester/pkg/scenarios/nutanix.go
  cmd/conformance-tester/pkg/scenarios/openstack.go
  cmd/conformance-tester/pkg/scenarios/packet.go
  cmd/conformance-tester/pkg/scenarios/vmware_cloud_director.go
  cmd/conformance-tester/pkg/scenarios/vsphere.go
  cmd/conformance-tester/pkg/types/options.go
Labels: kind/cleanup, size/L, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#12777 [release/v2.22] Changelog update
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.22.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved, do-not-merge/code-freeze

#12778 [release/v2.21] Update changelogs
  CHANGELOG.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved, do-not-merge/code-freeze

#12776 [release/v2.23] Update changelogs
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved, code-freeze-approved

#12761 Bump Cillium version to 1.13.8 and 1.14.3
  pkg/cni/cilium/cilium-mirror-chart.sh
  pkg/cni/cilium/cilium.go
  pkg/cni/version.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/networking, kind/chore, docs/none, code-freeze-approved

#12738 Fix random failures for application installation controller integration tests
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_integration_test.go
Labels: kind/failing-test, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, docs/provided, code-freeze-approved

#12763 prevent empty error messages in logs
  pkg/ee/resource-quota/master-controller/controller.go
  pkg/ee/resource-quota/seed-controller/controller.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none, code-freeze-approved

#12775 Changelog update for October out-of-band patch releases
  docs/changelogs/CHANGELOG-2.21.md
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#12781 Downgrade VCD CSI driver to v1.3.2
  addons/csi/vmware-cloud-director/csi-controller.yaml
  addons/csi/vmware-cloud-director/csi-driver.yaml
  addons/csi/vmware-cloud-director/csi-node.yaml
  addons/csi/vmware-cloud-director/vcloud-basic-auth.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, kind/chore, docs/none, code-freeze-approved

#12786 Update kubelb CCM image to v0.4.0
  pkg/ee/kubelb/resources/seed-cluster/deployment.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#12785 kubelb: datacenter kubeconfig should have precedence over seed kubeconfig
  pkg/ee/kubelb/controller.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#12783 fix panic in addon controller
  pkg/controller/seed-controller-manager/addon/addon_controller.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#12791 Extend project-synchronizer to sync labels
  pkg/controller/master-controller-manager/project-synchronizer/controller_test.go
  pkg/controller/master-controller-manager/project-synchronizer/resources.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, docs/none, backport-needed, code-freeze-approved

#12793 [release/v2.22] Extend project-synchronizer to sync labels
  pkg/controller/master-controller-manager/project-synchronizer/controller_test.go
  pkg/controller/master-controller-manager/project-synchronizer/resources.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved, do-not-merge/code-freeze

#12792 [release/v2.23] Extend project-synchronizer to sync labels
  pkg/controller/master-controller-manager/project-synchronizer/controller_test.go
  pkg/controller/master-controller-manager/project-synchronizer/resources.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved, do-not-merge/code-freeze

#12794 [release/v2.21] Extend project-synchronizer to sync labels
  pkg/controller/master-controller-manager/project-synchronizer/controller_test.go
  pkg/controller/master-controller-manager/project-synchronizer/resources.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved, do-not-merge/code-freeze

#12789 update list of k8s versions on EKS
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#12796 make default catalog installation idempotent
  cmd/kubermatic-installer/main_ee.go
  pkg/ee/default-application-catalog/application_catalog.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/provided, code-freeze-approved

#12795 bump google.golang.org/grpc
  go.mod
  go.sum
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#12798 Revert CA bundle for apps
  cmd/user-cluster-controller-manager/main.go
  pkg/applications/helmclient/client.go
  pkg/applications/helmclient/client_integration_test.go
  pkg/applications/helmclient/client_test.go
  pkg/applications/installer.go
  pkg/applications/providers/source/git.go
  pkg/applications/providers/source/helm.go
  pkg/applications/providers/template/helm.go
  pkg/applications/providers/types.go
  pkg/install/images/application_definitions.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/regression, docs/none, code-freeze-approved
