Repository kubermatic/kubermatic, pull requests merged in 2023-09, with the labels that each got.

#12611 [release/v2.23] Update Vertical Pod Autoscaler (VPA) to 0.14.0 (#12604)
  go.mod
  go.sum
  hack/ci/testdata/kubermatic.yaml
  pkg/controller/operator/common/vpa/admissionctrl.go
  pkg/controller/operator/common/vpa/rbac.go
  pkg/controller/operator/common/vpa/recommender.go
  pkg/controller/operator/common/vpa/updater.go
  pkg/crd/k8s.io/autoscaling.k8s.io_verticalpodautoscalercheckpoints.yaml
  pkg/crd/k8s.io/autoscaling.k8s.io_verticalpodautoscalers.yaml
  pkg/version/kubermatic/versions.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, cherry-pick-approved

#12612 [release/v2.22] Update Vertical Pod Autoscaler (VPA) to 0.14.0 (#12604)
  go.mod
  go.sum
  hack/ci/testdata/kubermatic.yaml
  pkg/controller/operator/common/vpa/admissionctrl.go
  pkg/controller/operator/common/vpa/rbac.go
  pkg/controller/operator/common/vpa/recommender.go
  pkg/controller/operator/common/vpa/updater.go
  pkg/crd/k8s.io/autoscaling.k8s.io_verticalpodautoscalercheckpoints.yaml
  pkg/crd/k8s.io/autoscaling.k8s.io_verticalpodautoscalers.yaml
  pkg/version/kubermatic/versions.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, cherry-pick-approved

#12624 [release/v2.22] Remove dynamic configuration logic from MachineDeployment generation
  pkg/controller/shared/nodedeployment-migration/machine/machinedeployment.go
Labels: kind/bug, customer-request, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12626 Fix Grafana dashboards in MLA and improve e2e/errors around it
  .prow/features.yaml
  charts/mla/grafana/files/kkp-kubernetes-nodes-overview.json
  charts/mla/grafana/files/kkp-kubernetes-nodes.json
  charts/mla/grafana/files/kkp-kubernetes-pods.json
  charts/mla/grafana/files/kkp-kubernetes-statefulsets.json
  charts/mla/grafana/files/kubernetes-overview.json
  charts/mla/grafana/test/config.yaml.out
  charts/mla/grafana/test/default.yaml.out
  go.mod
  go.sum
  pkg/controller/seed-controller-manager/mla/grafana.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller.go
  pkg/test/e2e/mla/mla_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, kind/regression, docs/none

#12423 Allow to modify allocation range in IPAMPool when exhausted
  hack/reconciling.yaml
  pkg/controller/seed-controller-manager/ipam/controller.go
  pkg/controller/seed-controller-manager/ipam/controller_test.go
  pkg/controller/seed-controller-manager/ipam/prefix_allocation.go
  pkg/controller/seed-controller-manager/ipam/range_allocation.go
  pkg/resources/reconciling/zz_generated_reconcile.go
  pkg/webhook/ipampool/validation/validation.go
  pkg/webhook/ipampool/validation/validation_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/networking, docs/tbd

#12600 make Digitalocean CCM version depend on the cluster version
  codegen/version-reporter/pkg/reader/gofunc.go
  hack/versions.yaml
  pkg/resources/cloudcontroller/digitalocean.go
  pkg/resources/test/fixtures/deployment-digitalocean-1.25.0-digitalocean-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.26.0-digitalocean-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.27.0-digitalocean-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.28.0-digitalocean-cloud-controller-manager-externalCloudProvider.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#12627 [release/v2.23] Fix Grafana dashboards in MLA and improve e2e/errors around it
  .prow/features.yaml
  charts/mla/grafana/files/kkp-kubernetes-nodes-overview.json
  charts/mla/grafana/files/kkp-kubernetes-nodes.json
  charts/mla/grafana/files/kkp-kubernetes-pods.json
  charts/mla/grafana/files/kkp-kubernetes-statefulsets.json
  charts/mla/grafana/files/kubernetes-overview.json
  charts/mla/grafana/test/config.yaml.out
  charts/mla/grafana/test/default.yaml.out
  go.mod
  go.sum
  pkg/controller/seed-controller-manager/mla/grafana.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller.go
  pkg/test/e2e/mla/mla_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, kind/chore, cherry-pick-approved

#12609 update to controller-runtime 0.16.1
  cmd/kubeletdnat-controller/main.go
  cmd/kubermatic-installer/cmd_convert_kubeconfig.go
  cmd/kubermatic-installer/cmd_deploy.go
  cmd/kubermatic-installer/cmd_local.go
  cmd/kubermatic-operator/main.go
  cmd/kubermatic-webhook/main.go
  cmd/master-controller-manager/main.go
  cmd/nodeport-proxy/envoy-manager/main.go
  cmd/nodeport-proxy/lb-updater/main.go
  cmd/seed-controller-manager/main.go
  cmd/user-cluster-controller-manager/main.go
  cmd/user-cluster-webhook/main.go
  cmd/user-ssh-keys-agent/main.go
  go.mod
  go.sum
  pkg/controller/nodeport-proxy/envoymanager/controller.go
  pkg/controller/shared/seed-controller-lifecycle/seed_controller_lifecycle.go
  pkg/controller/usersshkeysagent/usersshkeys_controller.go
  pkg/test/clusterexposer/cmd/main.go
  pkg/validation/openapi/openapi.go
  pkg/validation/openapi/openapi_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#12613 Extend kubermatic-installer mirror-images command with tarball export feature
  cmd/kubermatic-installer/cmd_mirror_images.go
  pkg/install/images/images.go
  pkg/install/images/images_test.go
  pkg/install/images/testdata/valid-archive.tar.gz
Labels: kind/feature, size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/tbd

#12636 Update to Go 1.21.1
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
Labels: kind/cleanup, size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none

#12635 [release/v2.23] Add support for Cilium 1.13.6 and deprecate older 1.13 releases
  pkg/cni/cilium/cilium.go
  pkg/cni/version.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/networking, cherry-pick-approved

#12637 [release/v2.23] installer: change kubevirt VM images back to http for local command
  cmd/kubermatic-installer/local_kind_resources.go
Labels: kind/cleanup, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#12640 Bump d3fk/s3cmd image to latest hash of `arch-stable` image
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: kind/cleanup, size/S, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none, backport-needed

#12643 [release/v2.22] Update to Go 1.19.12
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  hack/update-codegen.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: kind/cleanup, size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved

#12638 Add September 2023 Kubernetes patch releases
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none

#12639 [release/v2.23] Add September 2023 Kubernetes patch releases
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved

#12642 [release/v2.23] Update to Go 1.20.8
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: kind/cleanup, size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved

#12644 [release/v2.23] Bump d3fk/s3cmd image to latest hash of `arch-stable` image
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: kind/cleanup, lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#12621 Disable CSI drivers installation on cluster where it's already turned on
  pkg/apis/kubermatic/v1/cluster.go
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/validation/cluster.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/tbd

#12648 Support for configuring OIDC username and group prefix for user clusters
  pkg/apis/kubermatic/v1/cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/resources/apiserver/deployment.go
Labels: customer-request, kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12651 Update the CE E2E provisioning test to k8s 1.27
  .prow/provider-aws.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none

#12653 [release/v2.22] Add changelog for v2.22.7
  docs/changelogs/CHANGELOG-2.22.md
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved

#12654 [release/v2.23] Add changelog for v2.23.3
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#12652 Add changelogs for September 2023 patch releases
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#12659 [release/v2.23] Remove Cilium 1.14.1 unintentionally added to list of supported CNI versions
  pkg/cni/version.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/networking, kind/regression, cherry-pick-approved

#12665 Add release notes for v2.23.4
  docs/changelogs/CHANGELOG-2.23.md
Labels: kind/documentation, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#12623 Add default AppCatalog to kubermatic-installer
  cmd/kubermatic-installer/cmd_deploy.go
  cmd/kubermatic-installer/main_ce.go
  cmd/kubermatic-installer/main_ee.go
  go.mod
  pkg/ee/default-application-catalog/application_catalog.go
  pkg/ee/default-application-catalog/applicationdefinitions/argocd-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/cert-manager-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/falco-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/flux2-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/kube-vip-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/metallb-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/nginx-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/trivy-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/trivy-operator-app.yaml
  pkg/ee/default-application-catalog/embed.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/stack/kubermatic-master/stack_ce.go
  pkg/install/stack/kubermatic-master/stack_ee.go
  pkg/install/stack/types.go
Labels: kind/feature, size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none
