Repository kubermatic/kubermatic, pull requests merged in 2024-09, with the labels that each got.

#13655 Avoid Changing User Cluster External IP
  pkg/resources/address/address.go
  pkg/resources/address/address_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#13657 Avoid referring to documentation against main/development branch
  charts/monitoring/prometheus/rules/general-blackbox-exporter.yaml
  charts/monitoring/prometheus/rules/general-cert-manager.yaml
  charts/monitoring/prometheus/rules/general-helm-exporter.yaml
  charts/monitoring/prometheus/rules/general-kube-apiserver.yaml
  charts/monitoring/prometheus/rules/general-kube-kubelet.yaml
  charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/general-node-exporter.yaml
  charts/monitoring/prometheus/rules/general-prometheus.yaml
  charts/monitoring/prometheus/rules/general-velero.yaml
  charts/monitoring/prometheus/rules/kubermatic-master-kubermatic.yaml
  charts/monitoring/prometheus/rules/kubermatic-seed-kubermatic.yaml
  charts/monitoring/prometheus/rules/managed-kube-controller-manager.yaml
  charts/monitoring/prometheus/rules/managed-kube-scheduler.yaml
  charts/monitoring/prometheus/rules/src/general/blackbox-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/cert-manager.yaml
  charts/monitoring/prometheus/rules/src/general/helm-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/kube-apiserver.yaml
  charts/monitoring/prometheus/rules/src/general/kube-kubelet.yaml
  charts/monitoring/prometheus/rules/src/general/kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/src/general/node-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/prometheus.yaml
  charts/monitoring/prometheus/rules/src/general/velero.yaml
  charts/monitoring/prometheus/rules/src/kubermatic-master/kubermatic.yaml
  charts/monitoring/prometheus/rules/src/kubermatic-seed/kubermatic.yaml
  charts/monitoring/prometheus/rules/src/managed/kube-controller-manager.yaml
  charts/monitoring/prometheus/rules/src/managed/kube-scheduler.yaml
  charts/monitoring/prometheus/rules/src/usercluster-mla/cortex.yaml
  charts/monitoring/prometheus/rules/src/usercluster-mla/loki-distributed.yaml
  charts/monitoring/prometheus/rules/usercluster-mla-cortex.yaml
  charts/monitoring/prometheus/rules/usercluster-mla-loki-distributed.yaml
  charts/monitoring/prometheus/test/default.yaml.out
  charts/monitoring/prometheus/test/values.example.ce.yaml.out
  charts/monitoring/prometheus/test/values.example.ee.yaml.out
  charts/values.example.ce.yaml
  charts/values.example.ee.yaml
  hack/verify-prometheus-rules.sh
  pkg/resources/credentials_test.go
  pkg/test/dualstack/README.md
Labels: kind/bug, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#13659 Migration from machine-controller userdata to OSM
  cmd/seed-controller-manager/controllers.go
  pkg/apis/kubermatic/v1/cluster.go
  pkg/controller/seed-controller-manager/operating-system-manager-migrator/controller.go
  pkg/controller/seed-controller-manager/operating-system-manager-migrator/doc.go
Labels: kind/feature, size/L, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/cluster-management, docs/none

#13599 Update kube-state-metrics addon to v2.13.0
  addons/kube-state-metrics/Makefile
  addons/kube-state-metrics/_header.txt
  addons/kube-state-metrics/customizations.patch
  addons/kube-state-metrics/deployment.yaml
  addons/kube-state-metrics/helm-values
  addons/kube-state-metrics/kube-state-metrics.yaml
  addons/kube-state-metrics/networkpolicy.yaml
  addons/kube-state-metrics/rbac.yaml
  addons/kube-state-metrics/scrape-config.yaml
  addons/kube-state-metrics/service.yaml
  pkg/controller/seed-controller-manager/addon/migrations/kube-state-metrics.go
  pkg/controller/seed-controller-manager/addon/migrations/migrations.go
  pkg/test/addon/upgrade_test.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/none

#13665 update integration tests to Kube 1.31
  .prow/tests.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none

#13651 Revert custom annotations
  pkg/apis/kubermatic/v1/cluster_templates.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/master-controller-manager/cluster-template-synchronizer/controller.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/test/generator/objects.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#13656 Support Openstack Config Drive
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/machine/provider/openstack.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13668 Annotation settings for dashboard
  pkg/apis/kubermatic/v1/settings.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/ui, docs/tbd

#13663 fix OpenStack provider reconciling multiple security groups
  go.mod
  pkg/apis/kubermatic/v1/cluster.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/openstack/provider_test.go
  pkg/provider/cloud/openstack/security_group.go
Labels: kind/cleanup, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#13695 [release/v2.24] Fix missing image rewrites (#13435)
  cmd/master-controller-manager/controllers.go
  cmd/master-controller-manager/main.go
  pkg/controller/master-controller-manager/kubeone/controller.go
  pkg/controller/operator/master/resources/kubermatic/master-controller-manager.go
  pkg/resources/csi/kubevirt/deployment.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved, code-freeze-approved

#13690 [release/v2.25] Avoid referring to documentation against main/development branch (#13657)
  charts/monitoring/prometheus/rules/general-blackbox-exporter.yaml
  charts/monitoring/prometheus/rules/general-cert-manager.yaml
  charts/monitoring/prometheus/rules/general-helm-exporter.yaml
  charts/monitoring/prometheus/rules/general-kube-apiserver.yaml
  charts/monitoring/prometheus/rules/general-kube-kubelet.yaml
  charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/general-node-exporter.yaml
  charts/monitoring/prometheus/rules/general-prometheus.yaml
  charts/monitoring/prometheus/rules/general-velero.yaml
  charts/monitoring/prometheus/rules/kubermatic-master-kubermatic.yaml
  charts/monitoring/prometheus/rules/kubermatic-seed-kubermatic.yaml
  charts/monitoring/prometheus/rules/managed-kube-controller-manager.yaml
  charts/monitoring/prometheus/rules/managed-kube-scheduler.yaml
  charts/monitoring/prometheus/rules/src/general/blackbox-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/cert-manager.yaml
  charts/monitoring/prometheus/rules/src/general/helm-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/kube-apiserver.yaml
  charts/monitoring/prometheus/rules/src/general/kube-kubelet.yaml
  charts/monitoring/prometheus/rules/src/general/kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/src/general/node-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/prometheus.yaml
  charts/monitoring/prometheus/rules/src/general/velero.yaml
  charts/monitoring/prometheus/rules/src/kubermatic-master/kubermatic.yaml
  charts/monitoring/prometheus/rules/src/kubermatic-seed/kubermatic.yaml
  charts/monitoring/prometheus/rules/src/managed/kube-controller-manager.yaml
  charts/monitoring/prometheus/rules/src/managed/kube-scheduler.yaml
  charts/monitoring/prometheus/rules/src/usercluster-mla/cortex.yaml
  charts/monitoring/prometheus/rules/src/usercluster-mla/loki-distributed.yaml
  charts/monitoring/prometheus/rules/usercluster-mla-cortex.yaml
  charts/monitoring/prometheus/rules/usercluster-mla-loki-distributed.yaml
  charts/values.example.ce.yaml
  charts/values.example.ee.yaml
  hack/verify-prometheus-rules.sh
  pkg/resources/credentials_test.go
  pkg/test/dualstack/README.md
Labels: kind/bug, size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, cherry-pick-approved, code-freeze-approved

#13693 [release/v2.24] skip DNS check in the KKP installer when using the local command (#13620)
  cmd/kubermatic-installer/cmd_deploy.go
  cmd/kubermatic-installer/cmd_local.go
  pkg/install/stack/kubermatic-master/stack.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved, code-freeze-approved

#13692 [release/v2.25] skip DNS check in the KKP installer when using the local command (#13620)
  cmd/kubermatic-installer/cmd_deploy.go
  cmd/kubermatic-installer/cmd_local.go
  pkg/install/stack/kubermatic-master/stack.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved, code-freeze-approved

#13696 Fix reconcilition error for apiserver-external service for non ClusterIP service type.
  pkg/resources/apiserver/service.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, kind/regression, docs/none, code-freeze-approved

#13691 [release/v2.24] Avoid referring to documentation against main/development branch (#13657)
  charts/monitoring/prometheus/rules/general-blackbox-exporter.yaml
  charts/monitoring/prometheus/rules/general-cert-manager.yaml
  charts/monitoring/prometheus/rules/general-helm-exporter.yaml
  charts/monitoring/prometheus/rules/general-kube-apiserver.yaml
  charts/monitoring/prometheus/rules/general-kube-kubelet.yaml
  charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/general-node-exporter.yaml
  charts/monitoring/prometheus/rules/general-prometheus.yaml
  charts/monitoring/prometheus/rules/general-velero.yaml
  charts/monitoring/prometheus/rules/kubermatic-master-kubermatic.yaml
  charts/monitoring/prometheus/rules/kubermatic-seed-kubermatic.yaml
  charts/monitoring/prometheus/rules/managed-kube-controller-manager.yaml
  charts/monitoring/prometheus/rules/managed-kube-scheduler.yaml
  charts/monitoring/prometheus/rules/src/general/blackbox-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/cert-manager.yaml
  charts/monitoring/prometheus/rules/src/general/helm-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/kube-apiserver.yaml
  charts/monitoring/prometheus/rules/src/general/kube-kubelet.yaml
  charts/monitoring/prometheus/rules/src/general/kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/src/general/node-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/prometheus.yaml
  charts/monitoring/prometheus/rules/src/general/velero.yaml
  charts/monitoring/prometheus/rules/src/kubermatic-master/kubermatic.yaml
  charts/monitoring/prometheus/rules/src/kubermatic-seed/kubermatic.yaml
  charts/monitoring/prometheus/rules/src/managed/kube-controller-manager.yaml
  charts/monitoring/prometheus/rules/src/managed/kube-scheduler.yaml
  charts/monitoring/prometheus/rules/src/usercluster-mla/cortex.yaml
  charts/monitoring/prometheus/rules/src/usercluster-mla/loki-distributed.yaml
  charts/monitoring/prometheus/rules/usercluster-mla-cortex.yaml
  charts/monitoring/prometheus/rules/usercluster-mla-loki-distributed.yaml
  charts/values.example.ce.yaml
  charts/values.example.ee.yaml
  hack/verify-prometheus-rules.sh
  pkg/resources/credentials_test.go
  pkg/test/dualstack/README.md
Labels: kind/bug, size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, cherry-pick-approved, code-freeze-approved

#13672 Add an option to enable customizing preset
  pkg/apis/kubermatic/v1/preset.go
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13700 mark CentOS as no longer supported on digitalocean
  cmd/conformance-tester/pkg/scenarios/digitalocean.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#13706 Upgrade VCD CSI Driver to v1.6.0
  addons/csi/vmware-cloud-director/csi-controller.yaml
  addons/csi/vmware-cloud-director/csi-driver.yaml
  addons/csi/vmware-cloud-director/csi-node.yaml
  addons/csi/vmware-cloud-director/vcloud-basic-auth.yaml
  addons/default-storage-class/storage-class.yaml
  pkg/resources/cloudconfig/vmwareclouddirector/config.go
  pkg/resources/csi/vmwareclouddirector/deployment.go
  pkg/resources/test/fixtures/deployment-vcd-1.27.0-csi-controller.yaml
  pkg/resources/test/fixtures/deployment-vcd-1.28.0-csi-controller.yaml
  pkg/resources/test/fixtures/deployment-vcd-1.29.0-csi-controller.yaml
  pkg/resources/test/fixtures/deployment-vcd-1.30.0-csi-controller.yaml
  pkg/resources/test/fixtures/deployment-vcd-1.31.0-csi-controller.yaml
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none, code-freeze-approved

#13707 Fix a typo in KubermaticSettings
  pkg/apis/kubermatic/v1/preset.go
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none, code-freeze-approved

#13712 Upgrade KubeLB to v1.1.1
  pkg/ee/kubelb/resources/seed-cluster/deployment.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#13711 bump to Go 1.23.1
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#13702 [release/v2.25] Use ValuesBlock in Cilium (#13276)
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/apis/apps.kubermatic/v1/application_definition_test.go
  pkg/apis/apps.kubermatic/v1/empty.go
  pkg/cni/cilium/cilium.go
  pkg/cni/cilium/cilium_test.go
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller_test.go
  pkg/validation/application_installation.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, sig/networking, cherry-pick-approved, code-freeze-approved

#13716 Allow setting the value for ingressClassName in IAP
  charts/iap/templates/ingresses.yaml
  charts/iap/test/values.custom-tls-secret.yaml
  charts/iap/test/values.example.yaml
  charts/iap/values.yaml
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#13721 [release/v2.25] Fix vSphere CCM/CSI Images (#13720)
  addons/csi/vsphere/csi-migration-webhook.yaml
  addons/csi/vsphere/vsphere-csi-driver.yaml
  pkg/resources/cloudcontroller/vsphere.go
  pkg/resources/test/fixtures/deployment-vsphere-1.27.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.28.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.29.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/regression, cherry-pick-approved, code-freeze-approved

#13722 [release/v2.24] Fix vSphere CCM/CSI Images (#13720)
  addons/csi/vsphere/csi-migration-webhook.yaml
  addons/csi/vsphere/vsphere-csi-driver.yaml
  pkg/resources/cloudcontroller/vsphere.go
  pkg/resources/test/fixtures/deployment-vsphere-1.26.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.27.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.28.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/regression, cherry-pick-approved, code-freeze-approved

#13724 [release/v2.23] Fix vSphere CCM/CSI Images (#13720)
  addons/csi/vsphere/csi-migration-webhook.yaml
  addons/csi/vsphere/vsphere-csi-driver.yaml
  pkg/resources/cloudcontroller/vsphere.go
  pkg/resources/test/fixtures/deployment-vsphere-1.24.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.25.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.26.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.27.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/regression, cherry-pick-approved, code-freeze-approved

#13729 [release/v2.25] add 2.23.19, 2.24.13, 2.25.9 changelog
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
  docs/changelogs/CHANGELOG-2.25.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved, code-freeze-approved

#13728 [release/v2.24] add 2.23.19, 2.24.13 changelog
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved, code-freeze-approved

#13720 Fix vSphere CCM/CSI Images
  addons/csi/vsphere/csi-migration-webhook.yaml
  addons/csi/vsphere/vsphere-csi-driver.yaml
  hack/ci/testdata/seed.yaml
  pkg/resources/cloudcontroller/vsphere.go
  pkg/resources/test/fixtures/deployment-vsphere-1.28.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.29.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.30.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.31.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/regression, docs/none, code-freeze-approved

#13730 add 2.23.19, 2.24.13, 2.25.9 changelogs
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
  docs/changelogs/CHANGELOG-2.25.md
Labels: lgtm, approved, size/M, release-note-none, kind/chore, docs/none, code-freeze-approved

#13725 migrate to newer sample app image in e2e tests
  cmd/conformance-tester/pkg/tests/loadbalancer.go
  cmd/conformance-tester/pkg/tests/metrics.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#13709 fix automatic version updates
  pkg/validation/cluster_test.go
  pkg/version/manager.go
  pkg/version/manager_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, docs/provided, code-freeze-approved

#13736 Reset .spec.values when migrating existing ApplicationInstallations
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/networking, kind/regression, docs/none, code-freeze-approved

#13739 remove RegistryGCR constant
  cmd/conformance-tester/pkg/tests/images.go
  cmd/conformance-tester/pkg/tests/usercluster_controller.go
  pkg/resources/resources.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none, code-freeze-approved

#13738 [release/v2.25] add 2.25.10 changelog
  docs/changelogs/CHANGELOG-2.25.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved, code-freeze-approved

#13741 fix resetting Application values to an empty value
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/networking, docs/none, code-freeze-approved

#13748 [release/v2.25] add 2.25.11 changelog
  docs/changelogs/CHANGELOG-2.25.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved, code-freeze-approved

#13743 Fix deletion for ApplicationInstallations
  pkg/webhook/application/applicationinstallation/validation/validation.go
  pkg/webhook/application/applicationinstallation/validation/validation_test.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none, code-freeze-approved

#13747 Add removal notice for values and defaultValues in ApplicationInstallation and ApplicationDefinition
  docs/zz_generated.applicationInstallation.ce.yaml
  docs/zz_generated.applicationInstallation.ee.yaml
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none, code-freeze-approved

#13746 Initial applications should be deployed in the specified namespace instead of kube-system
  pkg/api/v1/types.go
  pkg/controller/seed-controller-manager/default-application-controller/controller.go
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller.go
  pkg/webhook/application/applicationinstallation/validation/validation.go
Labels: kind/bug, release-note-action-required, lgtm, approved, size/M, dco-signoff: yes, sig/cluster-management, sig/api, docs/none, code-freeze-approved

#13764 Add initial-cni annotation to hidden annotations for UI
  pkg/apis/kubermatic/v1/settings.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none, code-freeze-approved

#13767 make SIG Apps the code owner of the default app catalog
  pkg/ee/default-application-catalog/OWNERS
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#13766 provide default Helm values for nvidia GPU operator to prevent name length issues
  pkg/ee/default-application-catalog/applicationdefinitions/nvidia-gpu-operator-app.yaml
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, docs/none, code-freeze-approved

#13769 remove leftover default cilium addon
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#13768 Add kv-infra-namespace flag to usercluster-controller
  cmd/user-cluster-controller-manager/main.go
  pkg/resources/usercluster/deployment.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#13776 fix config format confusion in IAP Helm chart
  charts/iap/templates/configmaps.yaml
  charts/iap/templates/deployments.yaml
  charts/iap/test/values.custom-tls-secret.yaml.out
  charts/iap/test/values.example.yaml.out
  charts/iap/values.yaml
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#13777 fix: typo issue in kube-state-metric addon
  addons/kube-state-metrics/helm-values
  addons/kube-state-metrics/kube-state-metrics.yaml
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, kind/chore, kind/regression, docs/none, code-freeze-approved
