Repository kubermatic/kubermatic, pull requests merged in 2024-10, with the labels that each got.

#13781 mla: grafana statefulset dashboard fix
  charts/mla/grafana/files/kkp-kubernetes-statefulsets.json
  charts/mla/grafana/test/config.yaml.out
  charts/mla/grafana/test/default.yaml.out
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#13773 Add Kubernetes v1.31.1, v1.30.5, v1.29.9, v1.28.14
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#13780 Tweak configuration of the kube-state-metrics v2.13.0 addon
  addons/kube-state-metrics/helm-values
  addons/kube-state-metrics/kube-state-metrics.yaml
  addons/kube-state-metrics/mla-rolebinding.yaml
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#13787 fix dev deploy script not creating the iap namespace
  hack/ci/deploy.sh
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#13779 Fix typos
  charts/mla/grafana/README.md
  docs/proposals/offline-mode.md
  docs/proposals/user-cluster-rbac.md
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/controller/master-controller-manager/rbac/sync_project_test.go
  pkg/controller/seed-controller-manager/application-secret-cluster-controller/controller.go
  pkg/controller/seed-controller-manager/kubernetes/resources_integration_test.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
Labels: kind/cleanup, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none, code-freeze-approved

#13735 use dl.k8s.io for downloading kubectl
  Dockerfile
  cmd/conformance-tester/Dockerfile
  hack/images/util/Dockerfile
  hack/images/util/settings.sh
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, docs/none

#13762 fix KKP version check for CRD upgrades when using commit-based images
  pkg/controller/operator/common/resources.go
  pkg/controller/operator/common/resources_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13788 Update oauth2-proxy to 7.7.0
  charts/iap/Chart.yaml
  charts/iap/test/values.custom-tls-secret.yaml.out
  charts/iap/test/values.example.yaml.out
  charts/iap/values.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13789 Update to Go 1.23.2
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none

#13791 Add kubevirt provider network
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13790 [release/v2.25] Update to Go 1.22.8
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved

#13794 [release/v2.25] Update oauth2-proxy to 7.7.0 (#13788) / fix TOML/YAML (#13776)
  charts/iap/Chart.yaml
  charts/iap/templates/configmaps.yaml
  charts/iap/templates/deployments.yaml
  charts/iap/test/values.custom-tls-secret.yaml.out
  charts/iap/test/values.example.yaml.out
  charts/iap/values.yaml
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved

#13763 do not tag container images with the git hash when building a tagged release
  hack/ci/release-images.sh
Labels: kind/api-change, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13804 always clone maps when ensuring labels
  pkg/kubernetes/helper.go
  pkg/resources/reconciling/modifier/related_revisions.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#13806 Set Env credentials for baremetal provider
  pkg/resources/data.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#13809 Upgrade KubeLB to v1.1.2
  go.mod
  go.sum
  pkg/ee/kubelb/resources/seed-cluster/deployment.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, docs/none

#13812 Revert "feat: append front-load-balancer allowlist source ranges with cluster pod and service CIDR (#13579)
  pkg/resources/data.go
  pkg/resources/nodeportproxy/nodeportproxy.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13713 Changelog for KKP Minor release 2.26.0
  docs/changelogs/CHANGELOG-2.26.md
Labels: size/L, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, docs/none

#13821 Support KubeVirt VolumeBindingMode for Tenant Cluster
  addons/csi/kubevirt/csi-driver-operator.yaml
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#13822 Bump KubeVirt csi-driver-operator to Latest Commit
  addons/csi/kubevirt/csi-driver-operator.yaml
Labels: kind/feature, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/none

#13823 Fix command given in example files
  charts/values.example.ce.yaml
  charts/values.example.ee.yaml
Labels: size/S, kind/documentation, ok-to-test, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, docs/provided

#13705 initial proposal for argocd-based KKP apps helm chart
  charts/gitops/kkp-argocd-apps/.helmignore
  charts/gitops/kkp-argocd-apps/Chart.yaml
  charts/gitops/kkp-argocd-apps/README.md
  charts/gitops/kkp-argocd-apps/proposed-dir-structure/Makefile
  charts/gitops/kkp-argocd-apps/proposed-dir-structure/dev/seed1/.gitkeep
  charts/gitops/kkp-argocd-apps/proposed-dir-structure/dev/seed2/.gitkeep
  charts/gitops/kkp-argocd-apps/proposed-dir-structure/prod/seed1/.gitkeep
  charts/gitops/kkp-argocd-apps/proposed-dir-structure/prod/seed2/.gitkeep
  charts/gitops/kkp-argocd-apps/templates/_helpers.tpl
  charts/gitops/kkp-argocd-apps/templates/argocd-apps-backup.yaml
  charts/gitops/kkp-argocd-apps/templates/argocd-apps-kkp-core.yaml
  charts/gitops/kkp-argocd-apps/templates/argocd-apps-logging.yaml
  charts/gitops/kkp-argocd-apps/templates/argocd-apps-monitoring.yaml
  charts/gitops/kkp-argocd-apps/templates/argocd-apps-storage.yaml
  charts/gitops/kkp-argocd-apps/templates/argocd-apps-usermla.yaml
  charts/gitops/kkp-argocd-apps/values.yaml
Labels: kind/feature, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/provided

#13827 Upgrade kubevirt csi operator
  addons/csi/kubevirt/csi-driver-operator.yaml
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#13828 Fixed upgrade link in Changelog 2.26
  docs/changelogs/CHANGELOG-2.26.md
Labels: kind/documentation, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#13820 use defaultValuesBlock for default app catalog
  pkg/ee/default-application-catalog/applicationdefinitions/argocd-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/cert-manager-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/falco-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/flux2-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/k8sgpt-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/kube-vip-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/kubevirt.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/metallb-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/nginx-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/nvidia-gpu-operator-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/trivy-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/trivy-operator-app.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13786 [release/v2.24] fix config format confusion in IAP Helm chart (#13776)
  charts/iap/templates/configmaps.yaml
  charts/iap/templates/deployments.yaml
  charts/iap/values.yaml
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved

#13508 update AWS EBS CSI addon
  addons/Makefile
  addons/csi/aws-ebs/Makefile
  addons/csi/aws-ebs/_header.txt
  addons/csi/aws-ebs/driver.yaml
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/none

#13833 Bump KubeVirt CSI Driver Operator
  addons/csi/kubevirt/csi-driver-operator.yaml
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none
