Repository kubermatic/kubermatic, pull requests merged in 2024-12, with the labels that each got.

#13914 Update dev-getting-started.md
  docs/dev-getting-started.md
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, docs/none

#13916 add default namespace spec to appdef crd
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/apis/apps.kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management, docs/none

#13920 Remove redundant storage classes from OpenStack CSI addon
  addons/csi/openstack/driver.yaml
  addons/csi/openstack/helm-values
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#13923 Expand the description of KubeletDown alert.
  charts/monitoring/prometheus/rules/general-kube-kubelet.yaml
  charts/monitoring/prometheus/rules/src/general/kube-kubelet.yaml
  charts/monitoring/prometheus/test/default.yaml.out
  charts/monitoring/prometheus/test/values.example.ce.yaml.out
  charts/monitoring/prometheus/test/values.example.ee.yaml.out
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, docs/none

#13926 fix changelog links
  docs/changelogs/CHANGELOG-2.24.md
  docs/changelogs/CHANGELOG-2.25.md
  docs/changelogs/CHANGELOG-2.26.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#13928 [release/v2.25] fix changelog links (#13926)
  docs/changelogs/CHANGELOG-2.24.md
  docs/changelogs/CHANGELOG-2.25.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, cherry-pick-approved

#13929 [release/v2.24] fix changelog links (#13926)
  docs/changelogs/CHANGELOG-2.24.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, cherry-pick-approved

#13931 Add Announcements Feature to CRD and Track Read Announcements
  pkg/apis/kubermatic/v1/settings.go
  pkg/apis/kubermatic/v1/user.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_users.yaml
Labels: kind/feature, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none
