Repository kubermatic/kubermatic, pull requests merged in 2024-04, with the labels that each got.

#13232 Fixed typo error in the 2.25 changelog
  docs/changelogs/CHANGELOG-2.25.md
Labels: kind/documentation, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#13234 Update release notes for 2.25 - add breaking change about mla minio
  docs/changelogs/CHANGELOG-2.25.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#13222 Update MLA Envoy to 1.29.2, improve alertmanager-proxy Helm Chart
  charts/mla/alertmanager-proxy/Chart.yaml
  charts/mla/alertmanager-proxy/templates/authzserver-deployment.yaml
  charts/mla/alertmanager-proxy/templates/authzserver-service.yaml
  charts/mla/alertmanager-proxy/templates/proxy-configmap.yaml
  charts/mla/alertmanager-proxy/templates/proxy-deployment.yaml
  charts/mla/alertmanager-proxy/test/default.yaml.out
  charts/mla/alertmanager-proxy/values.yaml
Labels: kind/cleanup, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13191 Add openstack reconcile cluster function
  pkg/provider/cloud/openstack/helper.go
  pkg/provider/cloud/openstack/internal/testing/fixtures.go
  pkg/provider/cloud/openstack/internal/testing/simulator.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/openstack/provider_test.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13228 chore: improve exclusion check in CNI immutable values validation
  pkg/cni/cilium/cilium.go
  pkg/cni/cilium/cilium_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/networking, kind/chore, docs/none

#13229 chore: remove deprecated cilium and hubble addons
  addons/Makefile
  addons/cilium/cilium_v1.11.yaml
  addons/cilium/cilium_v1.12.yaml
  addons/hubble/_extras.txt
  addons/hubble/_footer.txt
  addons/hubble/hubble_v1.11.yaml
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/controller/operator/master/resources/kubermatic/addonconfigs.go
  pkg/controller/operator/master/resources/kubermatic/static/hubble.png
  pkg/defaulting/configuration.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/deprecation, docs/none

#13242 [release/v2.25] Bump Cilium to 1.13.14 and 1.14.9
  pkg/cni/cilium/cilium-mirror-chart.sh
  pkg/cni/cilium/cilium.go
  pkg/cni/version.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/networking, kind/chore, cherry-pick-approved

#13241 Introduce Cilium 1.15 and bump older to 1.13.14 and 1.14.9
  pkg/cni/cilium/cilium-mirror-chart.sh
  pkg/cni/cilium/cilium.go
  pkg/cni/version.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/networking, docs/none

#13121 Compare applications helm charts before running helm upgrade
  pkg/applications/helmclient/client.go
  pkg/applications/helmclient/client_integration_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#13247 [release/v2.24] Bump to Go 1.21.9
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved

#13248 Bump to Go 1.22.2
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none, backport-needed

#13245 [release/v2.25] upgrade Canal to 3.27.3 (#13239)
  addons/canal/canal_v3.27.yaml
  pkg/cni/version.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, sig/networking, kind/chore, cherry-pick-approved

#13246 [release/v2.24] upgrade Canal to 3.27.3 (#13239)
  addons/canal/canal_v3.27.yaml
  pkg/cni/version.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, sig/networking, kind/chore, cherry-pick-approved

#13244 Bump Helm dependency to 3.14.3
  Dockerfile
  go.mod
  go.sum
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none

#13253 Use plain HTTP for OCI tests in Helm client
  pkg/applications/helmclient/client.go
  pkg/applications/helmclient/client_integration_test.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, kind/regression, docs/none

#13252 fix addon controller reconciling too frequently
  pkg/addon/types.go
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/webhook/addon/mutation/mutation.go
  pkg/webhook/addon/mutation/mutation_test.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13259 check addons during conformance only after nodes are ready
  cmd/conformance-tester/pkg/runner/runner.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#13250 Fix changes to immutable RBAC in Azure CSI
  pkg/controller/seed-controller-manager/addon/addon_controller.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none, backport-needed

#13268 use plain semver versions for Helm charts
  charts/backup/velero/Chart.yaml
  charts/cert-manager/Chart.yaml
  charts/iap/Chart.yaml
  charts/kubermatic-operator/Chart.yaml
  charts/logging/loki/Chart.yaml
  charts/logging/promtail/Chart.yaml
  charts/minio/Chart.yaml
  charts/mla/alertmanager-proxy/Chart.yaml
  charts/mla/consul/Chart.yaml
  charts/mla/cortex/Chart.yaml
  charts/mla/grafana/Chart.yaml
  charts/mla/loki-distributed/Chart.yaml
  charts/mla/minio-lifecycle-mgr/Chart.yaml
  charts/mla/minio/Chart.yaml
  charts/monitoring/alertmanager/Chart.yaml
  charts/monitoring/blackbox-exporter/Chart.yaml
  charts/monitoring/grafana/Chart.yaml
  charts/monitoring/helm-exporter/Chart.yaml
  charts/monitoring/karma/Chart.yaml
  charts/monitoring/kube-state-metrics/Chart.yaml
  charts/monitoring/node-exporter/Chart.yaml
  charts/monitoring/prometheus/Chart.yaml
  charts/nginx-ingress-controller/Chart.yaml
  charts/oauth/Chart.yaml
  charts/s3-exporter/Chart.yaml
  charts/telemetry/Chart.yaml
  hack/ci/deploy.sh
  hack/ci/github-release.sh
  hack/ci/release-images.sh
  hack/ci/run-offline-test.sh
  hack/lib.sh
Labels: kind/bug, kind/cleanup, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#13265 update configmap-reloader to 0.12.0
  charts/monitoring/alertmanager/values.yaml
  charts/monitoring/prometheus/templates/statefulset.yaml
  charts/monitoring/prometheus/values.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13269 update to nginx-ingress-controller 1.10.0
  charts/nginx-ingress-controller/Chart.lock
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
Labels: release-note-action-required, size/XL, lgtm, approved, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13273 update cert-manager to v1.14.4
  charts/cert-manager/Chart.lock
  charts/cert-manager/Chart.yaml
  charts/cert-manager/crd/cert-manager.crds.yaml
  charts/cert-manager/test/default.yaml.out
  charts/cert-manager/test/override-controller-test.yaml.out
Labels: release-note-action-required, size/XL, lgtm, approved, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13285 Add ability to override OSM resources
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/user-cluster-controller-manager/resources/resources/operating-system-manager/role.go
  pkg/controller/user-cluster-controller-manager/resources/resources/operating-system-manager/rolebinding.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/resources/operatingsystemmanager/deployment.go
  pkg/resources/operatingsystemmanager/webhook.go
  pkg/resources/resources.go
Labels: kind/feature, size/L, kind/api-change, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13287 [release/v2.24] Add ability to override OSM resources
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/user-cluster-controller-manager/resources/resources/operating-system-manager/role.go
  pkg/controller/user-cluster-controller-manager/resources/resources/operating-system-manager/rolebinding.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/resources/operatingsystemmanager/deployment.go
  pkg/resources/operatingsystemmanager/webhook.go
  pkg/resources/resources.go
Labels: kind/feature, size/L, kind/api-change, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#13270 update Dex to 2.39.1
  charts/oauth/Chart.yaml
  charts/oauth/templates/cluster-role-binding.yaml
  charts/oauth/templates/deployment.yaml
  charts/oauth/templates/rbac.yaml
  charts/oauth/test/default.yaml.out
  charts/oauth/test/image-pull-secret.yaml.out
  charts/oauth/test/ingress-annotations.yaml.out
  charts/oauth/test/theme-with-overwrites.yaml.out
  charts/oauth/test/values.example.ce.yaml.out
  charts/oauth/test/values.example.ee.yaml.out
  charts/oauth/values.yaml
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13281 Bump Loki/Promtail to 2.9.x
  charts/logging/loki/Chart.lock
  charts/logging/loki/Chart.yaml
  charts/logging/loki/test/default.yaml
  charts/logging/loki/test/default.yaml.out
  charts/logging/loki/test/values.example.ce.yaml.out
  charts/logging/loki/test/values.example.ee.yaml.out
  charts/logging/loki/values.yaml
  charts/logging/promtail/Chart.lock
  charts/logging/promtail/Chart.yaml
  charts/logging/promtail/test/default.yaml.out
  charts/logging/promtail/test/kubermatic.example.ce.yaml.out
  charts/logging/promtail/test/kubermatic.example.ee.yaml.out
  charts/logging/promtail/values.yaml
Labels: kind/api-change, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13290 Render Helm manifests to map instead of a string
  pkg/applications/helmclient/client.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13267 fix Grafana appVersion typo
  charts/monitoring/grafana/Chart.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, docs/none

#13271 update oauth2-proxy to 7.6.0
  charts/iap/Chart.yaml
  charts/iap/templates/deployments.yaml
  charts/iap/test/values.custom-tls-secret.yaml.out
  charts/iap/test/values.example.yaml.out
  charts/iap/values.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13295 Split helper into multiple files
  pkg/provider/cloud/openstack/helper.go
  pkg/provider/cloud/openstack/network.go
  pkg/provider/cloud/openstack/routers.go
  pkg/provider/cloud/openstack/security_group.go
  pkg/provider/cloud/openstack/subnets.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#13296 Fix Loki upgrade
  charts/logging/loki/test/default.yaml.out
  charts/logging/loki/test/values.example.ce.yaml.out
  charts/logging/loki/test/values.example.ee.yaml.out
  charts/logging/loki/values.yaml
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, docs/tbd

#13302 [release/v2.25] Addon upgrade integration tests (#13256)
  .prow/tests.yaml
  hack/ci/run-addons-integration-test.sh
  hack/verify-boilerplate.sh
  pkg/test/addon/data/cluster-aws.yaml
  pkg/test/addon/data/cluster-azure.yaml
  pkg/test/addon/data/cluster-digitalocean.yaml
  pkg/test/addon/data/cluster-gcp.yaml
  pkg/test/addon/data/cluster-hetzner.yaml
  pkg/test/addon/data/cluster-kubevirt.yaml
  pkg/test/addon/data/cluster-nutanix.yaml
  pkg/test/addon/data/cluster-openstack.yaml
  pkg/test/addon/data/cluster-vmwareclouddirector.yaml
  pkg/test/addon/data/cluster-vsphere.yaml
  pkg/test/addon/matrix.go
  pkg/test/addon/setup_test.go
  pkg/test/addon/upgrade_test.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#13304 keep Loki PVCs when STS is deleted
  charts/logging/loki/test/default.yaml.out
  charts/logging/loki/test/values.example.ce.yaml.out
  charts/logging/loki/test/values.example.ee.yaml.out
  charts/logging/loki/values.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management, docs/tbd

#13261 add dynamic base id to envoy agent on user cluster
  pkg/controller/user-cluster-controller-manager/resources/resources/envoy-agent/daemonset.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#13298 [release/v2.25] Add Kubernetes patch releases 1.27.13, 1.28.9, 1.29.4
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved

#13299 [release/v2.24] Add Kubernetes patch releases 1.27.13, 1.28.9
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#13308 [release/v2.23] Upgrade Canal to 3.27
  addons/canal/canal_v3.27.yaml
  pkg/cni/version.go
Labels: kind/feature, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, sig/networking, kind/chore, cherry-pick-approved

#13297 Add Kubernetes patch releases 1.27.13, 1.28.9, 1.29.4
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none

#13300 [release/v2.23] Add Kubernetes patch release 1.27.13
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#13301 Applications: discover if a release is stuck and rollback if necessary
  pkg/applications/fake/fake_installer.go
  pkg/applications/helmclient/client.go
  pkg/applications/installer.go
  pkg/applications/providers/template/helm.go
  pkg/applications/providers/types.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#13303 fix the creation of network more than one time
  pkg/provider/cloud/openstack/network.go
  pkg/provider/cloud/openstack/provider.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#13306 bump usercluster/metering Prometheus to 2.51.1
  pkg/ee/metering/prometheus/sts.go
  pkg/resources/prometheus/statefulset.go
  pkg/resources/test/fixtures/statefulset-aws-1.27.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.28.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.28.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.29.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.29.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.27.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.28.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.28.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.29.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.29.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.28.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.29.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.27.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.28.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.28.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.29.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.29.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-edge-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-edge-1.28.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-edge-1.29.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.27.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.28.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.28.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.29.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.29.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.27.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.28.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.28.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.29.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.29.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vcd-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vcd-1.28.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vcd-1.29.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.27.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.27.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.28.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.28.0-prometheus.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.29.0-prometheus-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.29.0-prometheus.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#13293 [release/v2.24]Add changelogs for KKP Apr 2024 patch releases
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#13292 [release/v2.25]Add changelogs for KKP Apr 2024 patch releases
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
  docs/changelogs/CHANGELOG-2.25.md
Labels: size/L, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved

#13294 [release/v2.23] Add changelog for KKP Apr 2024 patch release
  docs/changelogs/CHANGELOG-2.23.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#13274 Allow custom tag & tag-suffix for kubermatic API image
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/apis/kubermatic/v1/configuration.go
  pkg/controller/operator/master/resources/kubermatic/api.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
Labels: kind/feature, kind/api-change, release-note-action-required, lgtm, approved, size/M, dco-signoff: yes, sig/cluster-management, docs/none

#13312 Sync changelogs for KKP Apr 2024 patch releases
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
  docs/changelogs/CHANGELOG-2.25.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#13323 Extend web terminal options for dashboard
  pkg/apis/kubermatic/v1/settings.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
Labels: kind/feature, size/L, kind/api-change, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/cluster-management, docs/tbd

#13331 Display name for applications
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/argocd-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/cert-manager-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/falco-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/flux2-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/k8sgpt-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/kube-vip-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/kubevirt.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/metallb-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/nginx-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/nvidia-gpu-operator-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/trivy-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/trivy-operator-app.yaml
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#13328 Change Azure load balancer SKU default value to Standard
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/provider/cloud/azure/provider.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13335 [release/v2.25] Add CSIDrivers for DigitalOcean and Azure File in Kubernetes 1.29
  addons/csi/azure-file/csi-azurefile-driver.yaml
  addons/csi/digitalocean/csi-driver.yaml
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, cherry-pick-approved

#13333 Enable local command for Enterprise Edition
  cmd/kubermatic-installer/main_ee.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/tbd

#13336 Improve helm repository prefix handling for system applications
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/apis/kubermatic/v1/configuration.go
  pkg/cni/cilium/cilium.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/defaulting/configuration.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/networking, docs/none

#13343 [release/v2.23] Improve helm repository prefix handling for system applications
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/apis/kubermatic/v1/configuration.go
  pkg/cni/cilium/cilium.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/defaulting/configuration.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/networking, cherry-pick-approved

#13334 delete mislabeled Azure CCM deployment to allow upgrades to succeed
  pkg/controller/seed-controller-manager/kubernetes/resources.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/provided

#13351 [release/v2.23] add changelog for 2.23.14
  docs/changelogs/CHANGELOG-2.23.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved

#13352 [release/v2.24] add changelog for 2.23.14, 2.24.7
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#13353 [release/v2.25] add changelog for 2.23.14, 2.24.7, 2.25.2
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
  docs/changelogs/CHANGELOG-2.25.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#13355 Add an option to enable etcd backups in k8c settings
  pkg/apis/kubermatic/v1/settings.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
Labels: kind/feature, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#13361 [release/v2.23] add 2.23.15 changelog
  docs/changelogs/CHANGELOG-2.23.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved

#13363 [release/v2.25] add 2.23.15, 2.24.8, 2.25.3 changelogs
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
  docs/changelogs/CHANGELOG-2.25.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved

#13364 add 2.23.15, 2.24.8, 2.25.3 changelogs
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
  docs/changelogs/CHANGELOG-2.25.md
  hack/ci/github-release.sh
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none
