Repository kubermatic/kubermatic, pull requests merged in 2024-03, with the labels that each got.

#13135 Set up OIDC network policy with different ingress controllers
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/apis/kubermatic/v1/configuration.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/resources/apiserver/networkpolicy.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/networking, docs/tbd, code-freeze-approved

#13118 Updated the velero node-agent configuration
  charts/backup/velero/templates/daemonset.yaml
  charts/backup/velero/values.yaml
Labels: release-note-action-required, lgtm, approved, size/M, dco-signoff: yes, sig/app-management, kind/chore, docs/none, code-freeze-approved

#13149 Revert "Remove node resources dashboard and recording rules (#12950)"
  charts/monitoring/prometheus/rules/general-node-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/node-exporter.yaml
Labels: kind/bug, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#13109 Build correct path to files to prevent duplications
  pkg/controller/user-cluster-controller-manager/resources/resources/mla/logging-agent/secret.go
Labels: ok-to-test, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#13147 Add NVIDIA GPU operator as bundled App
  pkg/ee/default-application-catalog/applicationdefinitions/nvidia-gpu-operator-app.yaml
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, docs/tbd, code-freeze-approved

#13123 Update master/seed monitoring dashboards
  charts/monitoring/grafana/dashboards/kubermatic/machine-controller.json
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#13150 fix app descriptions
  pkg/ee/cluster-backup/resources/user-cluster/node_agent.go
  pkg/ee/default-application-catalog/applicationdefinitions/k8sgpt-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/trivy-operator-app.yaml
Labels: kind/cleanup, size/S, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#13151 fix: exclude test folders from chart archive
  hack/ci/github-release.sh
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#13148 Fix AWS CCM upgrade
  pkg/controller/seed-controller-manager/cloud/cloud_controller.go
  pkg/provider/cloud/aws/provider.go
  pkg/provider/cloud/aws/provider_test.go
  pkg/provider/cloud/azure/provider.go
  pkg/provider/cloud/bringyourown/provider.go
  pkg/provider/cloud/edge/provider.go
  pkg/provider/cloud/gcp/provider.go
  pkg/provider/cloud/kubevirt/provider.go
  pkg/provider/cloud/nutanix/provider.go
  pkg/provider/cloud/vmwareclouddirector/provider.go
  pkg/provider/cloud/vsphere/provider.go
  pkg/provider/types.go
Labels: kind/bug, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#13156 add VMWare Cloud Provider Disk Size Nil handle
  pkg/ee/validation/machine/providers.go
  pkg/ee/validation/machine/providers_test.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#13159 Update example base domain to kkp.example.com
  charts/kubermatic.example.ce.yaml
  charts/kubermatic.example.ee.yaml
  charts/oauth/test/values.example.ce.yaml.out
  charts/oauth/test/values.example.ee.yaml.out
  charts/values.example.ce.yaml
  charts/values.example.ee.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management, kind/chore, docs/provided, code-freeze-approved

#13162 Conformance Tester: add flatcar to supported OS list for GCP and VCD
  .prow/provider-gcp.yaml
  .prow/provider-vmware-cloud-director.yaml
  cmd/conformance-tester/pkg/scenarios/google.go
  cmd/conformance-tester/pkg/scenarios/vmware_cloud_director.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#13164 [release/v2.24] Bump to Go 1.21.8
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved, code-freeze-approved

#13165 [release/v2.23] Bump to Go 1.20.13
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved, code-freeze-approved

#13167 do not try to load cloud-config if CSI is disabled
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#13160 improve IPv6 compatibility in etcd-launcher
  cmd/etcd-launcher/pkg/etcd/cmd.go
  cmd/kubermatic-installer/cmd_local.go
  pkg/applications/providers/template/helm.go
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller_test.go
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller_test.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller.go
  pkg/controller/user-cluster-controller-manager/constraint-syncer/controller_test.go
  pkg/test/e2e/cilium/cilium_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/networking, docs/none, code-freeze-approved

#13161 raise memory limit for envoy-agent DaemonSet
  pkg/controller/user-cluster-controller-manager/resources/resources/envoy-agent/daemonset.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#13169 Upgrade to KubeLB CCM v0.7.0
  pkg/ee/kubelb/resources/seed-cluster/deployment.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#13172 Use canal as a default cni for edge
  pkg/defaulting/cluster.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#13171 correctly identify defaulted values fields in AppInstalls
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/apis/apps.kubermatic/v1/application_installation_test.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#13174 Add RBAC rules for CBSL
  pkg/apis/kubermatic/v1/cluster_backup.go
  pkg/controller/master-controller-manager/rbac/mapper.go
  pkg/controller/master-controller-manager/rbac/mapper_test.go
  pkg/controller/master-controller-manager/rbac/rbac_controller_aggregator.go
Labels: kind/bug, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#13176 add version labels to deployments managed by controllers
  pkg/controller/operator/common/util.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/seed/reconciler.go
Labels: kind/cleanup, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#13173 [release/v2.24] Azure CCM upgrade for KKP 2.24
  pkg/resources/cloudcontroller/azure.go
  pkg/resources/test/fixtures/deployment-azure-1.28.0-azure-cloud-controller-manager-externalCloudProvider.yaml
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, cherry-pick-approved, code-freeze-approved

#13177 Fix missing new fields in AppDefs during KKP upgrades
  pkg/ee/default-application-catalog/application_catalog.go
  pkg/install/util/deployment.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#13179 Fix CBSL reconcile issues
  pkg/ee/cluster-backup/controller.go
  pkg/ee/cluster-backup/storage-location/controller.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#13050 Prepared changelog for KKP 2.25.0 release
  docs/changelogs/CHANGELOG-2.25.md
Labels: size/L, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#13183 [release/v2.24] do not try to load cloud-config if CSI is disabled (#13167)
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#13186 Bump all Go dependencies
  .golangci.yml
  .wwhrd.yml
  go.mod
  go.sum
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_addonconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_addons.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_admissionplugins.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_alertmanagers.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_allowedregistries.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusterbackupstoragelocations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplateinstances.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_constraints.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_constrainttemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdbackupconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdrestores.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_groupprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipamallocations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipampools.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_mlaadminsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_projects.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_resourcequotas.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_rulegroups.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_userprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_users.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_usersshkeys.yaml
  pkg/defaulting/cluster.go
  pkg/defaulting/configuration.go
  pkg/kubernetes/helper.go
  pkg/provider/cloud/vmwareclouddirector/provider.go
  pkg/provider/cloud/vsphere/folder.go
  pkg/resources/registry/registry.go
  pkg/validation/openapi/openapi_test.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/networking, kind/chore, docs/none

#13192 Add velero and kubeLB images to the list of mirrored images
  pkg/install/images/images.go
  pkg/install/images/wrappers_ce.go
  pkg/install/images/wrappers_ee.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13198 [release/v2.24] Add kubeLB images to the list of mirrored images
  pkg/install/images/images.go
  pkg/install/images/wrappers_ce.go
  pkg/install/images/wrappers_ee.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#13202 fix cluster-autoscaler addon
  addons/Makefile
  addons/cluster-autoscaler/cluster-autoscaler.yaml
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, docs/none

#13189 Add script to build and push KKP utility images
  .prow/tests.yaml
  cmd/alertmanager-authorization-server/Dockerfile
  cmd/alertmanager-authorization-server/settings.sh
  cmd/http-prober/Dockerfile
  cmd/http-prober/release.sh
  cmd/http-prober/settings.sh
  cmd/s3-exporter/Dockerfile
  cmd/s3-exporter/settings.sh
  hack/images/grafana-plugins/Dockerfile
  hack/images/grafana-plugins/release.sh
  hack/images/grafana-plugins/settings.sh
  hack/images/integration-tests/Dockerfile
  hack/images/integration-tests/release.sh
  hack/images/integration-tests/settings.sh
  hack/images/release.sh
  hack/images/startup-script/Dockerfile
  hack/images/startup-script/release.sh
  hack/images/startup-script/settings.sh
  hack/images/util/Dockerfile
  hack/images/util/settings.sh
  hack/lib.sh
  hack/publish-s3-exporter.sh
  hack/release-alertmanager-authorization-server-image.sh
  hack/release-utility-images.sh
  hack/verify-boilerplate.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#13201 add changelogs for 2.23.12, 2.24.5, 2.25.1
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
  docs/changelogs/CHANGELOG-2.25.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#13194 add new `kubermatic_cluster_owner` metric
  pkg/collectors/cluster.go
  pkg/collectors/cluster_test.go
  pkg/collectors/clusterbackup.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, docs/none

#13209 do not resync all caches every 2 seconds
  pkg/controller/shared/seed-controller-lifecycle/seed_controller_lifecycle.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#13211 change versioning scheme for integration-tests image
  hack/images/integration-tests/settings.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#13212 remove deploy scripts for long-gone environments
  hack/README.md
  hack/changelog-gen.sh
  hack/ci/README.md
  hack/ci/deploy-dev-asia.sh
  hack/ci/deploy-offline.sh
  hack/ci/deploy-run-2-lab-alpha.sh
  hack/ci/deploy-run-lab-stable.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#13213 Cleanup ancient TODOs
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/upb_controller.go
  pkg/controller/user-cluster-controller-manager/resources/controller.go
  pkg/resources/certificates/client-certificate.go
  pkg/resources/etcd/tls-serving-certificate.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/none

#13217 [release/v2.23] do not resync all caches every 2 seconds (#13209)
  pkg/controller/shared/seed-controller-lifecycle/seed_controller_lifecycle.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#13200 put metering- prefix in front of cronjob names
  codegen/example-yaml/main.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/operator/seed/reconciler_ee_test.go
  pkg/controller/operator/seed/reconciler_test.go
  pkg/controller/operator/seed/resources/metering/wrappers_ce.go
  pkg/controller/operator/seed/resources/metering/wrappers_ee.go
  pkg/ee/metering/cronjob.go
  pkg/ee/metering/prometheus/sts.go
  pkg/ee/metering/reconcile.go
  pkg/install/images/images.go
  pkg/webhook/seed/validation_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13218 do not let status updates trigger constant updates on CBSLs
  pkg/ee/cluster-backup/storage-location/controller.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, docs/none

#13187 Bump kubermatic/util to Alpine 3.19
  hack/images/util/Dockerfile
  hack/images/util/settings.sh
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#13221 improve logging in MLA auth proxy
  cmd/alertmanager-authorization-server/Dockerfile
  cmd/alertmanager-authorization-server/main.go
  cmd/alertmanager-authorization-server/main_test.go
  cmd/alertmanager-authorization-server/settings.sh
Labels: kind/cleanup, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, docs/none

#13223 Update Grafana to 10.4, refresh dashboards
  charts/monitoring/grafana/dashboards/go/processes-deployments.json
  charts/monitoring/grafana/dashboards/go/processes.json
  charts/monitoring/grafana/dashboards/kubermatic/controller-manager.json
  charts/monitoring/grafana/dashboards/kubermatic/controller-runtime.json
  charts/monitoring/grafana/dashboards/kubermatic/event-monitoring.json
  charts/monitoring/grafana/dashboards/kubermatic/machine-controller.json
  charts/monitoring/grafana/dashboards/kubermatic/nodeport-proxy.json
  charts/monitoring/grafana/dashboards/kubermatic/user-clusters.json
  charts/monitoring/grafana/dashboards/kubernetes/etcd-objects.json
  charts/monitoring/grafana/dashboards/kubernetes/etcd-overview.json
  charts/monitoring/grafana/dashboards/kubernetes/etcd.json
  charts/monitoring/grafana/dashboards/kubernetes/kubelets-overview.json
  charts/monitoring/grafana/dashboards/kubernetes/kubelets.json
  charts/monitoring/grafana/dashboards/kubernetes/node-namespaces.json
  charts/monitoring/grafana/dashboards/kubernetes/nodes-overview.json
  charts/monitoring/grafana/dashboards/kubernetes/nodes.json
  charts/monitoring/grafana/dashboards/kubernetes/pods.json
  charts/monitoring/grafana/dashboards/kubernetes/resources-cluster.json
  charts/monitoring/grafana/dashboards/kubernetes/resources-namespace.json
  charts/monitoring/grafana/dashboards/kubernetes/resources-pod.json
  charts/monitoring/grafana/dashboards/kubernetes/statefulset.json
  charts/monitoring/grafana/dashboards/kubernetes/volumes.json
  charts/monitoring/grafana/dashboards/minio/overview.json
  charts/monitoring/grafana/dashboards/mla/mla-components.json
  charts/monitoring/grafana/dashboards/monitoring/blackbox-exporter.json
  charts/monitoring/grafana/dashboards/monitoring/prometheus.json
  charts/monitoring/grafana/dashboards/nginx-ingress-controller/overview.json
  charts/monitoring/grafana/dashboards/prometheus-exporter/overview.json
  charts/monitoring/grafana/provisioning/dashboards/prometheus-exporter.yaml
  charts/monitoring/grafana/templates/deployment.yaml
  charts/monitoring/grafana/values.yaml
  hack/images/grafana-plugins/Dockerfile
  hack/images/grafana-plugins/settings.sh
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13224 fix nonroot usage of distroless
  cmd/alertmanager-authorization-server/Dockerfile
  cmd/alertmanager-authorization-server/settings.sh
  cmd/s3-exporter/Dockerfile
  cmd/s3-exporter/settings.sh
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, kind/regression, docs/none

#13226 Let S3-exporter run as nonroot
  charts/s3-exporter/templates/deployment.yaml
  charts/s3-exporter/values.yaml
Labels: kind/cleanup, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, docs/none

#13185 Bump to Metering 1.2.1
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/ee/metering/cronjob.go
  pkg/ee/metering/prometheus/sts.go
  pkg/ee/metering/reconcile.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13199 set release tag for minio/mc
  charts/mla/minio-lifecycle-mgr/test/config.yaml.out
  charts/mla/minio-lifecycle-mgr/test/default.yaml.out
  charts/mla/minio-lifecycle-mgr/test/image-pull-secret.yaml.out
  charts/mla/minio-lifecycle-mgr/values.yaml
Labels: kind/feature, size/S, ok-to-test, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none
