Repository kubermatic/kubermatic, pull requests merged in 2024-08, with the labels that each got.

#13562 Support for configuring API server service type
  .golangci.yml
  docs/zz_generated.addondata.go.txt
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/resources/address/address.go
  pkg/resources/address/address_test.go
  pkg/resources/apiserver/service.go
  pkg/resources/apiserver/service_test.go
  pkg/resources/apiserver/tls-serving-certificate.go
  pkg/resources/data.go
Labels: customer-request, kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/tbd

#13555 Update docker and x/net dependencies
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  go.mod
  go.sum
  hack/images/integration-tests/settings.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, docs/none

#13556 [release/v2.25] Bump Go version from 1.22.1 to 1.22.5
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved

#13557 [release/v2.24] Bump Go version from 1.21.9 to 1.21.12
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved

#13524 Refactor addon migrations
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/controller/seed-controller-manager/addon/migrations/csi-azure.go
  pkg/controller/seed-controller-manager/addon/migrations/csi-hetzner.go
  pkg/controller/seed-controller-manager/addon/migrations/csi-vsphere.go
  pkg/controller/seed-controller-manager/addon/migrations/migrations.go
  pkg/test/addon/setup_test.go
  pkg/test/addon/upgrade_test.go
Labels: kind/cleanup, size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#13473 Update Velero to v1.14.0
  .wwhrd.yml
  charts/backup/velero/Chart.yaml
  charts/backup/velero/test/default.yaml.out
  charts/backup/velero/test/values.example.ce.yaml.out
  charts/backup/velero/test/values.example.ee.yaml.out
  charts/backup/velero/values.yaml
  go.mod
  go.sum
  pkg/ee/cluster-backup/resources/user-cluster/cluster_backup.go
  pkg/ee/cluster-backup/resources/user-cluster/node_agent.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13436 Webhook backend for user cluster audit logs
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/audit_logging.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/defaulting/cluster.go
  pkg/resources/apiserver/audit.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/resources.go
Labels: kind/feature, size/L, kind/api-change, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/tbd

#13533 Allow eBPF proxy mode when cni is none
  pkg/validation/cluster.go
Labels: kind/feature, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#13569 Deduplicate alerts in alertmanager
  charts/monitoring/prometheus/config/prometheus.yaml
  charts/monitoring/prometheus/test/default.yaml.out
  charts/monitoring/prometheus/test/values.example.ce.yaml.out
  charts/monitoring/prometheus/test/values.example.ee.yaml.out
  charts/monitoring/prometheus/values.yaml
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#13572 Fix: Update Vsphere Integration Test
  .prow/provider-vsphere.yaml
  cmd/conformance-tester/pkg/scenarios/vsphere.go
  hack/ci/testdata/seed.yaml
  pkg/provider/cloud/vsphere/integration_test.go
  pkg/provider/cloud/vsphere/network_test.go
  pkg/test/addon/data/cluster-vsphere.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#13567 Add more description for OpenStack
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#13576 [release/v2.25] Fix vsphere integration test issue
  .prow/provider-vsphere.yaml
  cmd/conformance-tester/pkg/scenarios/vsphere.go
  hack/ci/testdata/seed.yaml
  pkg/provider/cloud/vsphere/integration_test.go
  pkg/provider/cloud/vsphere/network_test.go
  pkg/test/addon/data/cluster-vsphere.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#13575 [release/v2.24]Fix vsphere integration test issue
  .prow/provider-vsphere.yaml
  cmd/conformance-tester/pkg/scenarios/vsphere.go
  hack/ci/testdata/seed.yaml
  pkg/provider/cloud/vsphere/integration_test.go
  pkg/provider/cloud/vsphere/network_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#13581 fix Dockerfile syntax warning
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none

#13577 [release/v2.23] Fix vsphere integration test issue
  .prow/provider-vsphere.yaml
  cmd/conformance-tester/pkg/scenarios/vsphere.go
  hack/ci/testdata/seed.yaml
  pkg/provider/cloud/vsphere/integration_test.go
  pkg/provider/cloud/vsphere/network_test.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#13585 fix KubermaticConfiguration getting deleted when a shared Seed is deleted
  pkg/controller/master-controller-manager/seed-sync/reconciler.go
  pkg/controller/master-controller-manager/seed-sync/reconciler_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13586 Update Baremetal Preset validation
  pkg/apis/kubermatic/v1/preset.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#13579 feat: add seed cluster podCIDR to front-load-balancer allowlist
  pkg/resources/data.go
  pkg/resources/nodeportproxy/nodeportproxy.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/tbd, needs-release-testing

#13587 Update to Go 1.23
  .golangci.apis.yml
  .golangci.yml
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/conformance-tester/pkg/scenarios/generator.go
  cmd/conformance-tester/pkg/tests/images.go
  cmd/conformance-tester/pkg/tests/securitycontext.go
  cmd/conformance-tester/pkg/tests/usercluster_controller.go
  cmd/etcd-launcher/pkg/etcd/cluster.go
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  codegen/example-yaml/main.go
  codegen/godoc/main.go
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
  pkg/api/v1/time.go
  pkg/apis/kubermatic/v1/datacenter_test.go
  pkg/controller/master-controller-manager/rbac/sync_project_test.go
  pkg/controller/operator/master/resources/kubermatic/api.go
  pkg/controller/operator/master/resources/kubermatic/master-controller-manager.go
  pkg/controller/operator/master/resources/kubermatic/ui.go
  pkg/controller/operator/seed/resources/kubermatic/seed-controller-manager.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller_test.go
  pkg/controller/seed-controller-manager/ipam/range_allocation.go
  pkg/controller/user-cluster-controller-manager/node-labeler/controller_test.go
  pkg/provider/cloud/gke/provider.go
  pkg/provider/cloud/vmwareclouddirector/helper.go
  pkg/provider/cloud/vsphere/provider_test.go
  pkg/resources/etcd/etcdservices.go
  pkg/resources/etcd/statefulset.go
  pkg/resources/etcd/tls-serving-certificate.go
  pkg/resources/vpa.go
  pkg/test/dualstack/dualstack_test.go
  pkg/test/e2e/cilium/cilium_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, kind/chore, docs/none

#13495 bump AWS CCM
  pkg/resources/cloudcontroller/aws.go
  pkg/resources/test/fixtures/deployment-aws-1.27.0-aws-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.28.0-aws-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.29.0-aws-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.30.0-aws-cloud-controller-manager-externalCloudProvider.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#13514 migrate azure-disk and azure-file CSI addons to upstream
  addons/csi/azure-disk/Kustomization
  addons/csi/azure-disk/Makefile
  addons/csi/azure-disk/_footer.txt
  addons/csi/azure-disk/_header.txt
  addons/csi/azure-disk/csi-azuredisk-controller.yaml
  addons/csi/azure-disk/csi-azuredisk-node.yaml
  addons/csi/azure-disk/driver.yaml
  addons/csi/azure-disk/rbac-csi-azuredisk-controller.yaml
  addons/csi/azure-disk/rbac-csi-azuredisk-node.yaml
  addons/csi/azure-file/Kustomization
  addons/csi/azure-file/Makefile
  addons/csi/azure-file/_footer.txt
  addons/csi/azure-file/_header.txt
  addons/csi/azure-file/csi-azurefile-controller.yaml
  addons/csi/azure-file/csi-azurefile-node.yaml
  addons/csi/azure-file/driver.yaml
  addons/csi/azure-file/rbac-csi-azurefile-controller.yaml
  addons/csi/azure-file/rbac-csi-azurefile-node.yaml
  addons/templatify.sh
  codegen/addon-templatifier/.gitignore
  codegen/addon-templatifier/README.md
  codegen/addon-templatifier/main.go
  pkg/controller/seed-controller-manager/addon/migrations/csi-azure-helm.go
  pkg/controller/seed-controller-manager/addon/migrations/csi-azure-rbac.go
  pkg/controller/seed-controller-manager/addon/migrations/csi-hetzner.go
  pkg/controller/seed-controller-manager/addon/migrations/csi-vsphere.go
  pkg/controller/seed-controller-manager/addon/migrations/migrations.go
  pkg/test/addon/upgrade_test.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, kind/deprecation, docs/none

#13552 Add single namespace mode for KubeVirt provider
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/machine/provider/kubevirt.go
  pkg/provider/cloud/kubevirt/network_policy.go
  pkg/provider/cloud/kubevirt/provider.go
  pkg/resources/cloudconfig/cloudconfig.go
  pkg/resources/csi/kubevirt/configmap.go
  pkg/resources/csi/kubevirt/deployment.go
  pkg/resources/csi/kubevirt/secret.go
  pkg/resources/data.go
  pkg/resources/resources.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13600 update nginx-ingress to 1.11.2
  charts/nginx-ingress-controller/Chart.lock
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13574 Make lb-method & lb-provider configurable for openstack provider
  .prow/provider-openstack.yaml
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/resources/cloudconfig/cloudconfig.go
  pkg/resources/cloudconfig/openstack/cloudconfig.go
Labels: kind/feature, size/L, kind/api-change, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13605 [release/v2.24] drop replica label from alerts
  charts/monitoring/prometheus/config/prometheus.yaml
  charts/monitoring/prometheus/values.yaml
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, cherry-pick-approved

#13606 [release/v2.23] drop replica label from alerts
  charts/monitoring/prometheus/config/prometheus.yaml
  charts/monitoring/prometheus/values.yaml
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, cherry-pick-approved

#13601 [release/v2.25] update nginx-ingress to 1.10.4 (#13600)
  charts/nginx-ingress-controller/Chart.lock
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, cherry-pick-approved

#13607 [release/v2.23] Add changelog for v2.23.18
  docs/changelogs/CHANGELOG-2.23.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved

#13609 [release/v2.25] Add changelog v2.23.18 v2.24.12 v2.25.8
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
  docs/changelogs/CHANGELOG-2.25.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#13608 [release/v2.24] Add changelogs for 2.23.18, 2.24.12
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#13612 [release/v2.25] update dashboard changelog
  docs/changelogs/CHANGELOG-2.25.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, cherry-pick-approved

#13610 add changelog v2.23.18 v2.24.12 v2.25.8
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
  docs/changelogs/CHANGELOG-2.25.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#13613 Fix machine deployment creation in baremetal provider
  pkg/machine/helpers.go
  pkg/machine/provider/baremetal.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#13614 Setup generic namespace for KubeVirt namespaced mode
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/machine/provider/kubevirt.go
  pkg/provider/cloud/kubevirt/provider.go
  pkg/resources/cloudconfig/cloudconfig.go
  pkg/resources/csi/kubevirt/configmap.go
  pkg/resources/csi/kubevirt/deployment.go
  pkg/resources/csi/kubevirt/secret.go
  pkg/resources/data.go
  pkg/resources/resources.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13598 fully automate cluster-autoscaler addon maintenance
  addons/Makefile
  addons/cluster-autoscaler/Makefile
  addons/cluster-autoscaler/_header.txt
  addons/cluster-autoscaler/cluster-autoscaler.yaml
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13620 skip DNS check in the KKP installer when using the local command
  cmd/kubermatic-installer/cmd_deploy.go
  cmd/kubermatic-installer/cmd_local.go
  pkg/install/stack/kubermatic-master/stack.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13603 Update MC/OSM, migrate/cleanup cloud-config code
  docs/zz_generated.applicationDefinition.ce.yaml
  docs/zz_generated.applicationDefinition.ee.yaml
  go.mod
  go.sum
  pkg/controller/user-cluster-controller-manager/ccm-csi-migrator/controller.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_alertmanagers.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusterbackupstoragelocations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  pkg/resources/cloudconfig/aws/cloudconfig.go
  pkg/resources/cloudconfig/aws/cloudconfig_test.go
  pkg/resources/cloudconfig/azure/cloudconfig.go
  pkg/resources/cloudconfig/cloudconfig.go
  pkg/resources/cloudconfig/cloudconfig_test.go
  pkg/resources/cloudconfig/gcp/cloudconfig.go
  pkg/resources/cloudconfig/gcp/cloudconfig_test.go
  pkg/resources/cloudconfig/ini/quote.go
  pkg/resources/cloudconfig/ini/quote_test.go
  pkg/resources/cloudconfig/ini/writer.go
  pkg/resources/cloudconfig/kubevirt/cloudconfig.go
  pkg/resources/cloudconfig/openstack/cloudconfig.go
  pkg/resources/cloudconfig/secret.go
  pkg/resources/cloudconfig/vmwareclouddirector/config.go
  pkg/resources/cloudconfig/vmwareclouddirector/config_test.go
  pkg/resources/cloudconfig/vsphere/cloudconfig.go
  pkg/resources/cloudconfig/vsphere/cloudconfig_test.go
  pkg/resources/csi/vmwareclouddirector/config.go
  pkg/resources/csi/vmwareclouddirector/secret.go
  pkg/resources/csi/vsphere/config.go
  pkg/resources/csi/vsphere/secret.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#13625 Update Canal addon to v3.27.4 and v3.28.1
  addons/canal/canal_v3.27.yaml
  addons/canal/canal_v3.28.yaml
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none, backport-needed

#13626 fix: remove kubevirt-cluster finalizers during cluster clean-up in namespaced mode
  pkg/provider/cloud/kubevirt/provider.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#13624 Add cloud-credentials secret for Baremetal provider
  pkg/provider/kubernetes/credentials.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/api, docs/none

#13630 Fix doc generation for DNSPolicy
  pkg/apis/kubermatic/v1/datacenter.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#13635 Block ns cleanup on kv provider untill etcdbackups cleanup
  pkg/provider/cloud/kubevirt/provider.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13632 [release/v2.25] Update Canal addon to v3.27.4
  addons/canal/canal_v3.27.yaml
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, cherry-pick-approved

#13633 [release/v2.24] Update Canal addon to v3.27.4
  addons/canal/canal_v3.27.yaml
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, cherry-pick-approved

#13634 [release/v2.23] Update Canal addon to v3.27.4
  addons/canal/canal_v3.27.yaml
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, cherry-pick-approved

#13628 [release/v2.25] Make lb-method & lb-provider configurable for openstack provider (#13574)
  .prow/provider-openstack.yaml
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/resources/cloudconfig/cloudconfig.go
  pkg/resources/cloudconfig/openstack/cloudconfig.go
Labels: kind/feature, kind/api-change, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#13502 cluster-template: add custom cluster annotations
  pkg/apis/kubermatic/v1/cluster_templates.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/controller/master-controller-manager/cluster-template-synchronizer/controller.go
  pkg/controller/seed-controller-manager/cluster-template-controller/controller.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/test/generator/objects.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#13621 update to controller-runtime 0.19
  cmd/master-controller-manager/controllers.go
  docs/proposals/constraint-template-filter.md
  go.mod
  go.sum
  pkg/controller/kubeletdnat-controller/controller.go
  pkg/controller/master-controller-manager/master-constraint-template-controller/controller_test.go
  pkg/controller/master-controller-manager/project-label-synchronizer/project_label_synchronizer.go
  pkg/controller/master-controller-manager/rbac/rbac_project_controller.go
  pkg/controller/master-controller-manager/rbac/rbac_resource_controller.go
  pkg/controller/seed-controller-manager/constraint-controller/controller.go
  pkg/controller/seed-controller-manager/constraint-template-controller/controller_test.go
  pkg/controller/seed-controller-manager/mla/alertmanager_controller.go
  pkg/controller/seed-controller-manager/mla/cleanup_controller.go
  pkg/controller/seed-controller-manager/mla/dashboard_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/datasource_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/mla.go
  pkg/controller/seed-controller-manager/mla/org_grafana_controller.go
  pkg/controller/seed-controller-manager/mla/ratelimit_cortex_controller.go
  pkg/controller/seed-controller-manager/mla/rulegroup_controller.go
  pkg/controller/seed-controller-manager/mla/rulegroup_sync_controller.go
  pkg/controller/seed-controller-manager/mla/user_grafana_controller.go
  pkg/controller/shared/seed-controller-lifecycle/seed_controller_lifecycle.go
  pkg/controller/util/util.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_addonconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_addons.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_admissionplugins.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_alertmanagers.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_allowedregistries.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusterbackupstoragelocations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplateinstances.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_constraints.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_constrainttemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdbackupconfigs.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_etcdrestores.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_groupprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipamallocations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_ipampools.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_mlaadminsettings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_projects.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_resourcequotas.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_rulegroups.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_userprojectbindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_users.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_usersshkeys.yaml
  pkg/ee/allowed-registry-controller/reconcile.go
  pkg/ee/allowed-registry-controller/reconcile_test.go
  pkg/metrics/runtime.go
  pkg/test/e2e/opa/constraint_template.yaml
  pkg/test/generator/objects.go
Labels: kind/api-change, size/XXL, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/none

#13636 Fix Azure CSI addon
  .prow/provider-azure.yaml
  addons/csi/azure-disk/Makefile
  addons/csi/azure-disk/customizations.patch
  addons/csi/azure-disk/driver.yaml
  addons/csi/azure-file/Makefile
  addons/csi/azure-file/customizations.patch
  addons/csi/azure-file/driver.yaml
  pkg/addon/addon.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, docs/none

#13647 use newer hetzner server types in e2e tests
  cmd/conformance-tester/pkg/scenarios/hetzner.go
  pkg/controller/seed-controller-manager/initial-machinedeployment-controller/controller_test.go
  pkg/test/e2e/jig/presets.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#13650 use Ubuntu for Digitalocean e2e tests
  .prow/provider-digitalocean.yaml
Labels: size/L, kind/failing-test, lgtm, approved, release-note-none, dco-signoff: yes, docs/none

#13645 Remove deprecated linter exportloopref
  .golangci.yml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none

#13629 add kubermatic to packngo User-Agent
  pkg/provider/cloud/packet/provider.go
Labels: ok-to-test, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/provided

#13652 Refactor packngo User-Agent configuration
  pkg/provider/cloud/packet/provider.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#13591 bump integration-tests image to Kube 1.31
  hack/images/integration-tests/Dockerfile
  hack/images/integration-tests/settings.sh
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, docs/none
