Repository kubermatic/kubermatic, pull requests merged in 2024-02, with the labels that each got.

#13010 Add velero node-agent for Cluster Backup integration
  hack/versions.yaml
  pkg/ee/cluster-backup/controller.go
  pkg/ee/cluster-backup/resources/user-cluster/cluster_backup.go
  pkg/ee/cluster-backup/resources/user-cluster/deployment.go
  pkg/ee/cluster-backup/resources/user-cluster/node_agent.go
  pkg/ee/cluster-backup/resources/user-cluster/secret.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, docs/tbd

#12997 fix: check for cilium system application in initial application controller
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller.go
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller_test.go
  pkg/test/e2e/cilium/cilium_test.go
  pkg/test/e2e/cilium/testdata/test-app-def.yaml
  pkg/test/e2e/jig/cluster.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/networking, docs/tbd

#13020 VCD: Move CSI controller to seed cluster
  .prow/provider-vmware-cloud-director.yaml
  addons/csi/vmware-cloud-director/csi-controller.yaml
  hack/versions.yaml
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/ee/validation/machine/providers.go
  pkg/install/images/images.go
  pkg/resources/csi/deployment.go
  pkg/resources/csi/rbac.go
  pkg/resources/csi/vmwareclouddirector/deployment.go
  pkg/resources/csi/vmwareclouddirector/rbac.go
  pkg/resources/csi/vmwareclouddirector/secret.go
  pkg/resources/resources.go
  pkg/resources/test/fixtures/deployment-vcd-1.26.0-csi-controller.yaml
  pkg/resources/test/fixtures/deployment-vcd-1.27.0-csi-controller.yaml
  pkg/resources/test/fixtures/deployment-vcd-1.28.0-csi-controller.yaml
  pkg/resources/test/fixtures/deployment-vcd-1.29.0-csi-controller.yaml
  pkg/resources/test/load_files_test.go
Labels: priority/high, customer-request, kind/feature, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#13023 Upgrade KubeLB CCM image to v0.5.0
  pkg/ee/kubelb/resources/seed-cluster/deployment.go
Labels: kind/feature, lgtm, approved, release-note, size/XS, dco-signoff: yes, docs/none

#13011 [release/v2.22] bump metering to v1.0.6
  pkg/ee/metering/reconcile.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#13012 [release/v2.23] bump metering to v1.0.6
  pkg/ee/metering/reconcile.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#13025 Add K8sGpt as Default Application
  pkg/ee/default-application-catalog/applicationdefinitions/k8sgpt-app.yaml
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, docs/tbd

#13019 Add DocumentationURL and SourceURL
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#13028 [release/v2.24] fix panic if no KubeVirt DNS config was set (#12933)
  codegen/example-yaml/main.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/provider/cloud/kubevirt/network_policy.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/virtualization, cherry-pick-approved

#13043 Add provider incompatibility for in-tree providers with Kubernetes >= 1.29
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#13045 Ensure that seed level resources for CSI driver are removed
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/csi/deletion.go
  pkg/resources/csi/kubevirt/deletion.go
  pkg/resources/csi/nutanix/deletion.go
  pkg/resources/csi/vmwareclouddirector/deletion.go
  pkg/resources/csi/vsphere/deletion.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none, backport-needed

#13044 Add logo for applications
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/tbd

#13046 Add `HasCCM` method to check if a provider comes with a CCM
  pkg/apis/kubermatic/v1/cluster.go
  pkg/controller/seed-controller-manager/update-controller/controller.go
  pkg/resources/cloudcontroller/deployment.go
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
  pkg/version/cluster/cluster.go
Labels: kind/bug, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/regression, docs/none

#13049 Fix conditions for CSI driver component deployments
  pkg/controller/seed-controller-manager/kubernetes/resources.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#13047 Update CRDs for OSM
  pkg/controller/user-cluster-controller-manager/resources/resources/operating-system-manager/static/crd-operatingsystemconfig.yaml
  pkg/controller/user-cluster-controller-manager/resources/resources/operating-system-manager/static/crd-operatingsystemprofile.yaml
  pkg/crd/k8c.io/operatingsystemmanager.k8c.io_customoperatingsystemprofiles.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#13029 [release/v2.23] fix panic if no KubeVirt DNS config was set (#12933)
  codegen/example-yaml/main.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/provider/cloud/kubevirt/network_policy.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/virtualization, cherry-pick-approved

#13048 [release/v2.24] Ensure that seed level resources for CSI driver are removed
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/csi/deletion.go
  pkg/resources/csi/kubevirt/deletion.go
  pkg/resources/csi/nutanix/deletion.go
  pkg/resources/csi/vmwareclouddirector/deletion.go
  pkg/resources/csi/vsphere/deletion.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#13055 bump telemetry client to 0.5
  charts/telemetry/Chart.yaml
  charts/telemetry/values.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13056 update metrics-server to 0.7
  pkg/controller/user-cluster-controller-manager/resources/resources/metrics-server/deployment.go
  pkg/resources/metrics-server/deployment.go
  pkg/resources/test/fixtures/deployment-aws-1.27.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.27.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.28.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.28.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-aws-1.29.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.29.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.27.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.27.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.28.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.28.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-azure-1.29.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.29.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.27.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.28.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.29.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.27.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.27.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.28.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.28.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.29.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.29.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-edge-1.27.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-edge-1.28.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-edge-1.29.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.27.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.27.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.28.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.28.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.29.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.29.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.27.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.27.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.28.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.28.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.29.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.29.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vcd-1.27.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vcd-1.28.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vcd-1.29.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.27.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.27.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.28.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.28.0-metrics-server.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.29.0-metrics-server-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.29.0-metrics-server.yaml
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#13057 update to Go 1.22
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none

#13058 Updated App definitions with the latest helm chart version for the default apps
  pkg/ee/default-application-catalog/applicationdefinitions/argocd-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/cert-manager-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/falco-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/flux2-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/metallb-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/nginx-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/trivy-operator-app.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none

#13061 Allow custom tls secret for iap ingress
  charts/iap/templates/ingresses.yaml
  charts/iap/test/test.sh
  charts/iap/test/values.custom-tls-secret.yaml
  charts/iap/test/values.custom-tls-secret.yaml.out
  charts/iap/test/values.example.yaml
  charts/iap/test/values.example.yaml.out
  charts/iap/values.yaml
Labels: kind/feature, size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#13066 Update to controller-runtime 0.17.1
  cmd/conformance-tester/pkg/tests/storage.go
  go.mod
  go.sum
  pkg/controller/master-controller-manager/rbac/sync_project_test.go
  pkg/controller/master-controller-manager/rbac/sync_resource_test.go
  pkg/controller/master-controller-manager/rbac/test/fake/informer_factory.go
  pkg/controller/seed-controller-manager/addoninstaller/addoninstaller_controller_test.go
  pkg/controller/seed-controller-manager/ipam/controller_test.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/ee/metering/prometheus/sts.go
  pkg/resources/etcd/statefulset.go
  pkg/test/generator/objects.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#12956 [mla] upgrade grafana helm chart to v7.0.21 (appVersion: 10.2.2)
  charts/mla/grafana/Chart.lock
  charts/mla/grafana/Chart.yaml
  charts/mla/grafana/test/config.yaml.out
  charts/mla/grafana/test/default.yaml.out
  charts/mla/grafana/values.yaml
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13008 [mla] upgrade minio to version RELEASE.2023-04-28T18-11-17Z
  charts/mla/minio/Chart.lock
  charts/mla/minio/Chart.yaml
  charts/mla/minio/test/config.yaml.out
  charts/mla/minio/test/default.yaml.out
  pkg/install/stack/usercluster-mla/validation.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/tbd

#13067 [mla] Add validation of new persistence configuration
  pkg/install/stack/usercluster-mla/validation.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/tbd

#13074 Skip spellcheck for applicationdefinitions manifests
  hack/verify-spelling.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#13076 Update KubeOne to v1.7.2
  go.mod
  go.sum
  pkg/resources/resources.go
Labels: kind/feature, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#13081 Use build image with kindest/node image that does not override binfmt settings
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#13077 Disable the deployment of machine controller when edge provider is used
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/test/fixtures/deployment-edge-1.27.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-edge-1.27.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-edge-1.28.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-edge-1.28.0-machine-controller.yaml
  pkg/resources/test/fixtures/deployment-edge-1.29.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/deployment-edge-1.29.0-machine-controller.yaml
  pkg/resources/test/fixtures/service-edge-1.27.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/service-edge-1.28.0-machine-controller-webhook.yaml
  pkg/resources/test/fixtures/service-edge-1.29.0-machine-controller-webhook.yaml
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#13078 Fix error check when deleting cluster backup resources.
  pkg/ee/cluster-backup/controller.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none, code-freeze-approved

#13087 [release/v2.23]Add changelogs for Feb 2024 patch releases
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved, code-freeze-approved

#13091 [release/v2.22] Change logs for patch release 2.22.13
  docs/changelogs/CHANGELOG-2.22.md
Labels: kind/documentation, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, cherry-pick-approved, code-freeze-approved

#13079 update k8s patch releases, update EKS/AKS support matrix
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#13100 Sync changelogs for KKP Patch releases February 2024
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#13075 Persist comments in Application's values fields - non breaking
  codegen/example-yaml/main.go
  docs/zz_generated.applicationInstallation.ce.yaml
  docs/zz_generated.applicationInstallation.ee.yaml
  pkg/api/v1/types.go
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/applications/providers/template/helm.go
  pkg/applications/providers/template/helm_integration_test.go
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/install/images/application_definitions.go
  pkg/validation/application_definition.go
  pkg/validation/application_definition_test.go
  pkg/validation/application_installation.go
  pkg/validation/application_installation_test.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/api, docs/tbd, code-freeze-approved

#13093 kubelb: update name of the tenant namespace
  pkg/ee/kubelb/cleanup.go
  pkg/ee/kubelb/controller.go
  pkg/ee/kubelb/resources/resources.go
  pkg/ee/kubelb/resources/seed-cluster/deployment.go
Labels: release-note-action-required, lgtm, approved, size/M, kind/design, dco-signoff: yes, docs/none, code-freeze-approved

#13106 Fixed broken tags link for Feb 2024 KKP patch releases
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
Labels: kind/documentation, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none, code-freeze-approved

#13107 Fixed broken tags link for Feb 2024 KKP patch releases
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
Labels: kind/documentation, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, cherry-pick-approved, code-freeze-approved

#13110 fix go-restful dependency
  go.mod
  go.sum
Labels: kind/cleanup, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none, code-freeze-approved

#13114 Exclude some KKP resources when Edge provider is used
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#13111 Update AppInstall validation to handle k8s apiserver defaulting
  pkg/defaulting/application_installation.go
  pkg/defaulting/application_installation_test.go
  pkg/validation/application_installation.go
  pkg/validation/application_installation_test.go
  pkg/webhook/application/applicationinstallation/mutation/mutation_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#13122 Fix logic for checking CSI driver usage
  pkg/controller/seed-controller-manager/addon/addon_controller.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#13126 [release/v2.24]Fix logic for checking CSI driver usage
  pkg/controller/seed-controller-manager/addon/addon_controller.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved, do-not-merge/code-freeze

#13129 [release/v2.24] Add changelog for v2.24.4
  docs/changelogs/CHANGELOG-2.24.md
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved, do-not-merge/code-freeze

#13130 Sync Out-of-band patch release changelog v2.24.4
  docs/changelogs/CHANGELOG-2.24.md
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#13116 Fix DefaultValues Wording
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
Labels: kind/documentation, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#13134 Update KubeLB to v0.6.0-rc.0
  pkg/ee/kubelb/controller.go
  pkg/ee/kubelb/resources/seed-cluster/deployment.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#13131 Fix an error in GetParsedValues when working with k8s-apiserver defaulting
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/apis/apps.kubermatic/v1/application_installation_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#13139 Override hubble-ui images if overwriteRegistry is set
  pkg/cni/cilium/cilium.go
  pkg/cni/cilium/cilium_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/networking, docs/none, code-freeze-approved

#13138 [mla] fix minio values file errors
  charts/mla/minio/Chart.yaml
  charts/mla/minio/test/config.yaml.out
  charts/mla/minio/test/default.yaml.out
  charts/mla/minio/values.yaml
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved
