Repository kubermatic/kubermatic, pull requests merged in 2024-07, with the labels that each got.

#13479 bump integration-tests image to Go 1.22.4 / Kube 1.30
  hack/images/integration-tests/Dockerfile
  hack/images/integration-tests/settings.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none

#13406 Add insecure/HTTP flags to Helm sources in AppDefinitions
  codegen/example-yaml/main.go
  docs/zz_generated.applicationDefinition.ce.yaml
  docs/zz_generated.applicationDefinition.ee.yaml
  go.mod
  hack/run-integration-tests.sh
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/apis/apps.kubermatic/v1/zz_generated.deepcopy.go
  pkg/applications/helmclient/client.go
  pkg/applications/helmclient/client_integration_test.go
  pkg/applications/helmclient/testdata/README.md
  pkg/applications/helmclient/testdata/crt.pem
  pkg/applications/helmclient/testdata/dummy/.gitignore
  pkg/applications/helmclient/testdata/key.pem
  pkg/applications/helmclient/testdata/rootca.crt
  pkg/applications/providers/source/helm.go
  pkg/applications/providers/template/helm.go
  pkg/applications/providers/template/helm_integration_test.go
  pkg/applications/providers/util/util.go
  pkg/applications/test/helm.go
  pkg/cni/cilium/cilium.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/defaulting/application_definition_test.go
  pkg/validation/application_definition.go
  pkg/validation/application_definition_test.go
  pkg/webhook/application/applicationdefinition/mutation/mutation_test.go
Labels: kind/feature, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, sig/networking, docs/none

#13445 Disable default storage addon if csi addon is disabled
  addons/default-storage-class/snapshot-class.yaml
  addons/default-storage-class/storage-class.yaml
  docs/zz_generated.addondata.go.txt
  pkg/addon/types.go
  pkg/controller/seed-controller-manager/addon/addon_controller.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#13484 Bump Go version to 1.22.5
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none

#13485 [release/v2.25] Bump Go version to 1.22.5
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved

#13487 [release/v2.24] Bump Go version to 1.21.12
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved

#13482 allow specifying extra containerports exposure for thanos query
  charts/monitoring/prometheus/templates/service.yaml
  charts/monitoring/prometheus/values.yaml
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13491 Add Static Labels property
  pkg/apis/kubermatic/v1/settings.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
Labels: kind/feature, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#13494 update cert-manager Helm chart to 1.15.1
  charts/cert-manager/Chart.lock
  charts/cert-manager/Chart.yaml
  charts/cert-manager/test/default.yaml.out
  charts/cert-manager/test/override-controller-test.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13496 bump Azure CCM / cloud node manager
  addons/azure-cloud-node-manager/cloud-node-manager.yaml
  pkg/resources/cloudcontroller/azure.go
  pkg/resources/test/fixtures/deployment-azure-1.27.0-azure-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.28.0-azure-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.29.0-azure-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.30.0-azure-cloud-controller-manager-externalCloudProvider.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/none

#13501 Update Anexia CCM to 1.5.6
  pkg/resources/cloudcontroller/anexia.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#13500 Update Hetzner CCM to 1.20.0
  pkg/resources/cloudcontroller/hetzner.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#13497 update Digitalocean CCM
  pkg/resources/cloudcontroller/digitalocean.go
  pkg/resources/test/fixtures/deployment-digitalocean-1.27.0-digitalocean-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.28.0-digitalocean-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.29.0-digitalocean-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.30.0-digitalocean-cloud-controller-manager-externalCloudProvider.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#13504 Add canal 3.28, deprecate 3.25
  addons/canal/canal_v3.28.yaml
  pkg/cni/version.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, sig/networking, kind/chore, kind/deprecation, docs/none

#13505 restore bgpconfigurations CRD in Canal 3.27
  addons/canal/canal_v3.27.yaml
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#13498 update Openstack CCM to 1.30.0
  pkg/resources/cloudcontroller/openstack.go
  pkg/resources/test/fixtures/deployment-openstack-1.30.0-openstack-cloud-controller-manager-externalCloudProvider.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#13503 fix: add metering prometheus to mirror-images
  pkg/controller/operator/seed/resources/metering/wrappers_ce.go
  pkg/controller/operator/seed/resources/metering/wrappers_ee.go
  pkg/ee/metering/prometheus/reconcile.go
  pkg/ee/metering/prometheus/sts.go
  pkg/install/images/images.go
  pkg/install/images/wrappers_ee.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13510 Update GCP CCM
  pkg/resources/cloudcontroller/gcp.go
  pkg/resources/test/fixtures/deployment-gcp-1.29.0-gcp-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.30.0-gcp-cloud-controller-manager-externalCloudProvider.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#13507 bump cluster-autoscaler addon
  addons/Makefile
  addons/cluster-autoscaler/_header.txt
  addons/cluster-autoscaler/cluster-autoscaler.yaml
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13509 [release/v2.25] fix: add metering prometheus to mirror-images
  pkg/controller/operator/seed/resources/metering/wrappers_ce.go
  pkg/controller/operator/seed/resources/metering/wrappers_ee.go
  pkg/ee/metering/prometheus/reconcile.go
  pkg/ee/metering/prometheus/sts.go
  pkg/install/images/images.go
  pkg/install/images/wrappers_ee.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#13472 make mla-gateway Pod auto-reload nginx when certificates are renewed
  pkg/controller/seed-controller-manager/mla/resources.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/app-management, docs/none

#13515 fix VPA admission-controller PDB blocking evictions
  pkg/controller/operator/common/vpa/admissionctrl.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, backport-needed

#13517 Bump latest k8s patch versions
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none

#13506 remove Canal 3.8
  addons/canal/canal.yaml
  pkg/cni/version.go
  pkg/webhook/cluster/validation/validation_test.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, sig/networking, kind/chore, docs/none

#13529 [release/v2.23] add 2.23.17 changelog
  docs/changelogs/CHANGELOG-2.23.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved

#13530 [release/v2.24] add 2.23.17, 2.24.11 changelog
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved

#13531 [release/v2.25] add 2.23.17, 2.24.11, 2.25.7 changelog
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
  docs/changelogs/CHANGELOG-2.25.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#13516 Fix minor issues with Velero KKP chart
  charts/backup/velero/templates/daemonset.yaml
  charts/backup/velero/templates/secrets.yaml
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/none, backport-needed

#13535 add 2.23.17, 2.24.11, 2.25.7 changelog
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
  docs/changelogs/CHANGELOG-2.25.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#13276 Use ValuesBlock in Cilium
  pkg/apis/apps.kubermatic/v1/application_definition.go
  pkg/apis/apps.kubermatic/v1/application_definition_test.go
  pkg/apis/apps.kubermatic/v1/empty.go
  pkg/cni/cilium/cilium.go
  pkg/cni/cilium/cilium_test.go
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller_test.go
  pkg/validation/application_installation.go
Labels: kind/cleanup, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, sig/networking, docs/none, backport-needed

#13539 fix kind setup for non-e2e tests, do not compile clusterexposer anymore
  hack/ci/setup-kind-cluster.sh
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#13538 [release/v2.23] Fix minor issues with Velero KKP chart (#13516)
  charts/backup/velero/templates/daemonset.yaml
  charts/backup/velero/templates/secrets.yaml
  charts/cert-manager/test/test-certmanager.sh
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved

#13549 replace kubernetes.io/ingress.class annotation with ingressClassName spec field
  charts/iap/templates/ingresses.yaml
  charts/iap/test/values.custom-tls-secret.yaml.out
  charts/iap/test/values.example.yaml.out
  charts/minio/templates/ingress.yaml
  charts/minio/test/enable-ingress.yaml.out
  charts/mla/grafana/README.md
  charts/mla/minio/values.yaml
  charts/oauth/templates/ingress.yaml
  charts/oauth/test/default.yaml.out
  charts/oauth/test/image-pull-secret.yaml.out
  charts/oauth/test/ingress-annotations.yaml.out
  charts/oauth/test/theme-with-overwrites.yaml.out
  charts/oauth/test/values.example.ce.yaml.out
  charts/oauth/test/values.example.ee.yaml.out
  pkg/controller/operator/master/resources/kubermatic/common.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none
