Repository kubermatic/kubermatic, pull requests merged in 2024-01, with the labels that each got.

#12932 Update codegen to 2024 copyright
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#12863 Update Vertical Pod Autoscaler to 1.0
  charts/kubermatic-operator/crd/k8s.io/autoscaling.k8s.io_verticalpodautoscalercheckpoints.yaml
  go.mod
  go.sum
  hack/update-codegen.sh
  pkg/controller/operator/common/vpa/admissionctrl.go
  pkg/controller/operator/common/vpa/rbac.go
  pkg/controller/operator/common/vpa/recommender.go
  pkg/controller/operator/common/vpa/updater.go
  pkg/crd/k8s.io/autoscaling.k8s.io_verticalpodautoscalercheckpoints.yaml
  pkg/crd/k8s.io/autoscaling.k8s.io_verticalpodautoscalers.yaml
  pkg/test/e2e/opa/opa_test.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/none

#12851 application-catalog: add KubeVirt
  charts/local-kubevirt/templates/clusterrolebinding-cdi-operator.yaml
  charts/local-kubevirt/templates/deployment-cdi-operator.yaml
  charts/local-kubevirt/templates/namespace-cdi.yaml
  charts/local-kubevirt/templates/namespace-kubevirt.yaml
  charts/local-kubevirt/templates/role-cdi-operator.yaml
  charts/local-kubevirt/templates/rolebinding-cdi-operator.yaml
  charts/local-kubevirt/templates/serviceaccount-cdi-operator.yaml
  charts/local-kubevirt/update.sh
  charts/local-kubevirt/upload-chart.sh
  cmd/kubermatic-installer/cmd_local.go
  pkg/ee/default-application-catalog/applicationdefinitions/kubevirt.yaml
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#12864 Update cloud provider SDKs
  codegen/permission-generator/defaultmapper.yml
  go.mod
  go.sum
  hack/run-integration-tests.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#12933 Fix panic if no KubeVirt DNS config was set
  codegen/example-yaml/main.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/provider/cloud/kubevirt/network_policy.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12885 Set up kind with Cilium as CNI
  hack/ci/setup-kind-cluster.sh
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#12934 Check Ingress instead of LB Service to detect DNS settings in installer
  pkg/install/stack/kubermatic-master/stack.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12950 Remove node resources dashboard and recording rules
  charts/monitoring/grafana/dashboards/kubernetes/node-resources.json
  charts/monitoring/prometheus/rules/general-kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/general-node-exporter.yaml
  charts/monitoring/prometheus/rules/src/general/kube-state-metrics.yaml
  charts/monitoring/prometheus/rules/src/general/node-exporter.yaml
Labels: kind/bug, kind/cleanup, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#12924 Add api-server cilium network policy in seed cluster
  .wwhrd.yml
  cmd/kubermatic-operator/main.go
  go.mod
  go.sum
  hack/ci/setup-kind-cluster.sh
  hack/reconciling.yaml
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/operator/seed/resources/networkpolicy/cilium.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/networking, docs/tbd

#12935 Upgraded cortex to v1.14.1
  charts/mla/cortex/Chart.lock
  charts/mla/cortex/Chart.yaml
  charts/mla/cortex/test/config.yaml.out
  charts/mla/cortex/test/default.yaml.out
  charts/mla/cortex/values.yaml
Labels: kind/feature, size/XXL, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/app-management, docs/none

#12954 Fix envoy agent init container
  cmd/network-interface-manager/Dockerfile.multiarch
  pkg/controller/user-cluster-controller-manager/resources/resources/envoy-agent/daemonset.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#12957 node-local-dns: cleanup tolerations
  pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/deamonset.go
Labels: kind/cleanup, size/S, ok-to-test, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12962 Remove 1.25 from AKS versions (EOL on January 14th)
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, docs/none

#12964 [release/v2.23] update version matrix for EKS/AKS (#12962)
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, cherry-pick-approved

#12965 [release/v2.22] update version matrix for EKS/AKS (#12962)
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, cherry-pick-approved

#12966 [release/v2.24] Add api-server cilium network policy in seed cluster (#12924)
  .wwhrd.yml
  cmd/kubermatic-operator/main.go
  go.mod
  go.sum
  pkg/controller/operator/seed/reconciler.go
  pkg/controller/operator/seed/resources/networkpolicy/cilium.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/networking, cherry-pick-approved

#12968 Bump to Go 1.21.6
  .prow/ccm-migrations.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none

#12970 bump Konnectivity versions
  pkg/resources/konnectivity/sidecar.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#12973 charts/kubermatic-operator: ability to configure environment variables
  charts/kubermatic-operator/templates/deployment.yaml
  charts/kubermatic-operator/values.yaml
Labels: customer-request, kind/feature, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/none

#12974 Example command to generate secrets now works on macOS by default
  charts/kubermatic.example.ce.yaml
  charts/kubermatic.example.ee.yaml
Labels: kind/documentation, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/none

#12976 Enable LoadBalancer tests for OpenStack
  cmd/conformance-tester/pkg/tests/loadbalancer.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none

#12972 Implement stable order for `-node-containerd-registry-mirrors` flags in OSM Deployment
  pkg/resources/operatingsystemmanager/deployment.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#12981 Add support for Kubernetes v1.26.13, v1.27.10, v1.28.6, v1.29.1
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: kind/cleanup, size/S, lgtm, approved, release-note, dco-signoff: yes, docs/none

#12982 [release/v2.24] Add support for Kubernetes v1.26.13, v1.27.10, v1.28.6
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, cherry-pick-approved

#12984 [release/v2.22] Add support for Kubernetes v1.24.17, v1.25.16 and v1.26.13
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, cherry-pick-approved

#12983 [release/v2.23] Add support for Kubernetes v1.24.17, v1.25.16, v1.26.13 and v1.27.10
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, cherry-pick-approved

#12971 [mla] cortex: add validation for old-style values
  pkg/install/stack/usercluster-mla/validation.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/tbd

#12991 [release/v2.23] Add release notes for v2.23.10
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved

#12992 [release/v2.24] Add release notes for v2.24.2
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#12990 [release/v2.22] Add release notes for v2.22.12
  docs/changelogs/CHANGELOG-2.22.md
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved

#12977 Add changelogs for January 2024 patch releases
  docs/changelogs/CHANGELOG-2.22.md
  docs/changelogs/CHANGELOG-2.23.md
  docs/changelogs/CHANGELOG-2.24.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#12995 [release/v2.24] Bump github.com/go-git/go-git/v5 from 5.8.0 to 5.11.0 (#12930)
  go.mod
  go.sum
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, cherry-pick-approved

#12996 Support for attaching multiple networks to a vApp
  cmd/conformance-tester/pkg/scenarios/vmware_cloud_director.go
  cmd/conformance-tester/pkg/types/secrets.go
  go.mod
  hack/ci/run-conformance-tests.sh
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/preset.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/machine/provider/vmware_cloud_director.go
  pkg/provider/cloud/vmwareclouddirector/helper.go
  pkg/provider/cloud/vmwareclouddirector/provider.go
  pkg/provider/cloud/vmwareclouddirector/reconcile.go
  pkg/resources/test/load_files_test.go
  pkg/validation/cluster.go
Labels: size/L, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/cluster-management, docs/none

#12998 renamed restic command to node-agent due to velero upstream changes
  charts/backup/velero/templates/daemonset.yaml
Labels: kind/bug, size/S, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13000 Fix CCM images
  addons/azure-cloud-node-manager/cloud-node-manager.yaml
  pkg/resources/cloudcontroller/azure.go
  pkg/resources/cloudcontroller/digitalocean.go
  pkg/resources/cloudcontroller/hetzner.go
  pkg/resources/cloudcontroller/openstack.go
  pkg/resources/cloudcontroller/vsphere.go
  pkg/resources/test/fixtures/deployment-azure-1.26.0-azure-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.27.0-azure-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.28.0-azure-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.29.0-azure-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.26.0-digitalocean-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.27.0-digitalocean-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.28.0-digitalocean-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.29.0-digitalocean-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.26.0-openstack-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.27.0-openstack-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.29.0-openstack-cloud-controller-manager-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.29.0-vsphere-cloud-controller-manager-externalCloudProvider.yaml
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#13001 VMware Cloud Director: Fix preset validation
  pkg/apis/kubermatic/v1/preset.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#13002 VCD: Support for limiting IP allocation modes for UI
  pkg/apis/kubermatic/v1/settings.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
Labels: customer-request, kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13006 Change type for ipAllocationMode
  pkg/apis/kubermatic/v1/settings.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#12967 changes to upgrade user-mla loki to v2.9.2 via helm chart v0.78.0
  charts/mla/loki-distributed/Chart.lock
  charts/mla/loki-distributed/Chart.yaml
  charts/mla/loki-distributed/test/config.yaml.out
  charts/mla/loki-distributed/test/default.yaml.out
  charts/mla/loki-distributed/values.yaml
Labels: size/XXL, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13009 Check for PVs having CSI provisioner before disabling the CSI addon
  pkg/controller/seed-controller-manager/addon/addon_controller.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none
