Repository kubermatic/kubermatic, pull requests merged in 2025-08, with the labels that each got.

#14827 remove equinix metal support
  .github/ISSUE_TEMPLATE/bug-report.md
  .prow/dualstack.yaml
  .prow/provider-packet.yaml
  cmd/conformance-tester/pkg/runner/runner.go
  cmd/conformance-tester/pkg/scenarios/generator.go
  cmd/conformance-tester/pkg/scenarios/packet.go
  cmd/conformance-tester/pkg/types/providers.go
  cmd/conformance-tester/pkg/types/secrets.go
  codegen/example-yaml/main.go
  docs/zz_generated.addondata.go.txt
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  go.mod
  go.sum
  hack/ci/run-conformance-tests.sh
  hack/ci/run-dualstack-e2e-test.sh
  hack/ci/testdata/seed.yaml
  hack/run-conformance-tests.sh
  pkg/addon/types.go
  pkg/controller/master-controller-manager/kubeone/controller.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_externalclusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/ee/validation/machine/providers.go
  pkg/install/images/images.go
  pkg/machine/helpers.go
  pkg/machine/provider/equinixmetal.go
  pkg/machine/provider/equinixmetal_test.go
  pkg/provider/cloud/packet/provider.go
  pkg/provider/cloud/provider.go
  pkg/provider/kubernetes/credentials.go
  pkg/resources/credentials.go
  pkg/resources/data.go
  pkg/resources/resources.go
  pkg/test/dualstack/cloud_providers.go
  pkg/test/dualstack/cloud_providers_dualstack_test.go
  pkg/test/dualstack/dualstack_test.go
  pkg/test/e2e/jig/credentials.go
  pkg/test/e2e/jig/presets.go
  pkg/validation/cluster.go
  sdk/api/v2/types.go
  sdk/apis/kubermatic/v1/cluster.go
  sdk/apis/kubermatic/v1/configuration.go
  sdk/apis/kubermatic/v1/datacenter.go
  sdk/apis/kubermatic/v1/external_cluster.go
  sdk/apis/kubermatic/v1/helper/provider.go
  sdk/apis/kubermatic/v1/preset.go
Labels: kind/cleanup, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/api, docs/none

#14891 add option to configure non root device usage in containerd
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/resources/operatingsystemmanager/deployment.go
  pkg/resources/operatingsystemmanager/deployment_test.go
  sdk/apis/kubermatic/v1/datacenter.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14865 [release/v2.27] fix: CBSL credentials and status sync to seed for seperate master and seed cluster setup
  pkg/ee/cluster-backup/master/sync-controller/controller.go
  pkg/ee/cluster-backup/master/sync-controller/controller_test.go
  pkg/ee/cluster-backup/master/sync-controller/resources.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, cherry-pick-approved

#14879 extend authorization webhooks configuration in user clusters
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/resources/apiserver/deployment.go
  sdk/apis/kubermatic/v1/cluster.go
  sdk/apis/kubermatic/v1/zz_generated.deepcopy.go
Labels: kind/feature, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#14900 [release/v2.26] Update the Helm charts to exclude Bitnami images
  charts/backup/velero/Chart.lock
  charts/backup/velero/Chart.yaml
  charts/backup/velero/test/default.yaml.out
  charts/backup/velero/test/values.example.ce.yaml.out
  charts/backup/velero/test/values.example.ee.yaml.out
  charts/mla/cortex/Chart.lock
  charts/mla/cortex/Chart.yaml
  charts/mla/cortex/test/config.yaml.out
  charts/mla/cortex/test/default.yaml.out
  hack/test-chart-rendering.sh
  pkg/install/helm/cli.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, cherry-pick-approved

#14893 [release/v2.27] Add changelog for KKP patch releases - Aug 2025
  docs/changelogs/CHANGELOG-2.26.md
  docs/changelogs/CHANGELOG-2.27.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved

#14895 Sync KKP changelogs for Aug 2025 patch releases
  docs/changelogs/CHANGELOG-2.26.md
  docs/changelogs/CHANGELOG-2.27.md
  docs/changelogs/CHANGELOG-2.28.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, docs/none

#14905 [release/v2.26] Add changelog for KKP patch release v2.26.12
  docs/changelogs/CHANGELOG-2.26.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#14906 [release/v2.27] Add changelog for KKP patch release v2.26.12
  docs/changelogs/CHANGELOG-2.26.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#14907 [release/v2.28] Add changelog for KKP patch release v2.26.12
  docs/changelogs/CHANGELOG-2.26.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#14910 Add support for k8s patch releases v1.33.4/1.32.8/1.31.12
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none

#14911 [release/v2.27] Add support for k8s patch releases v1.32.8/1.31.12
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved

#14912 [release/v2.26] Add support for k8s patch release v1.31.12
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#14937 Delete Kubermatic Operator pull secret from CE example file
  charts/values.example.ce.yaml
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, kind/chore, docs/none
