Repository kubermatic/kubermatic, pull requests merged in 2025-06, with the labels that each got.

#14640 [release/v2.27] Bump Kubevirt CSI Driver (#14502)
  addons/csi/kubevirt/csi-driver-operator.yaml
  pkg/provider/cloud/kubevirt/csi.go
  pkg/resources/csi/kubevirt/deployment.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, cherry-pick-approved, code-freeze-approved

#14647 add delete event to appdef validating webhook configuration
  pkg/controller/operator/common/webhook.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#14649 [release/v2.25] add changelog for 2.25.18
  docs/changelogs/CHANGELOG-2.25.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved, code-freeze-approved

#14650 [release/v2.26] add changelogs for 2.25.18, 2.26.9
  docs/changelogs/CHANGELOG-2.25.md
  docs/changelogs/CHANGELOG-2.26.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved, code-freeze-approved

#14654 add health check for Kyverno controllers in cluster health status
  pkg/controller/seed-controller-manager/kubernetes/health.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/ee/kyverno/resources/seed-cluster/admission-controller/deployment.go
  pkg/ee/kyverno/resources/seed-cluster/background-controller/deployment.go
  pkg/ee/kyverno/resources/seed-cluster/cleanup-controller/deployment.go
  pkg/ee/kyverno/resources/seed-cluster/common/constants.go
  pkg/ee/kyverno/resources/seed-cluster/reports-controller/deployment.go
  sdk/apis/kubermatic/v1/cluster.go
  sdk/apis/kubermatic/v1/zz_generated.deepcopy.go
Labels: kind/feature, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#14657 Delete the deprecated oauth chart
  charts/dex/values.yaml
  charts/oauth/.helmignore
  charts/oauth/Chart.yaml
  charts/oauth/README.md
  charts/oauth/templates/_helpers.tpl
  charts/oauth/templates/configmap.yaml
  charts/oauth/templates/deployment.yaml
  charts/oauth/templates/ingress.yaml
  charts/oauth/templates/pdb.yaml
  charts/oauth/templates/rbac.yaml
  charts/oauth/templates/secrets.yaml
  charts/oauth/templates/service.yaml
  charts/oauth/templates/serviceaccount.yaml
  charts/oauth/theme/bg.svg
  charts/oauth/theme/favicon.png
  charts/oauth/theme/logo.svg
  charts/oauth/theme/styles.css
  charts/oauth/theme/ubuntu-500.woff
  charts/oauth/theme/ubuntu-500.woff2
  charts/oauth/values.yaml
  charts/values.example.ce.yaml
  charts/values.example.ee.yaml
  hack/ci/github-release.sh
  hack/verify-spelling.sh
  hack/versions.yaml
  pkg/install/stack/kubermatic-master/dex.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/stack/kubermatic-master/validation.go
Labels: kind/feature, size/XXL, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none, code-freeze-approved

#14621 add new field for kubevirt cpu assignment
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  sdk/apis/kubermatic/v1/datacenter.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#14659 Reconcile knp-agent based on cluster spec update
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/deployment.go
  pkg/install/images/images.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#14672 Fix Seed controller backup Interval arg parsing from kuberamtic cfg
  pkg/controller/operator/seed/resources/kubermatic/seed-controller-manager.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#14662 add enhancements for default policy controller and policy binding controller
  pkg/ee/default-policy-controller/controller.go
  pkg/ee/default-policy-controller/controller_test.go
  pkg/ee/policy-binding-controller/controller.go
Labels: kind/bug, size/L, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#14676 Fix OSM template data logic
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/data.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#14681 MirrorImage: Add Kyverno Images for EE
  pkg/ee/kyverno/data.go
  pkg/install/images/wrappers_ee.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#14682 Bump csi-node-driver-registrar in local-kubevirt
  charts/local-kubevirt/templates/kubevirt-csi-driver.yaml
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, kind/chore, docs/none, code-freeze-approved

#14679 KubeLB: prevent possible nil pointer exception
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#14688 Add skip-charts on KKP installer usercluster-mla
  pkg/install/stack/usercluster-mla/stack.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#14706 add test and fix bug regarding app enforce annotation
  pkg/controller/seed-controller-manager/default-application-controller/controller.go
  pkg/controller/seed-controller-manager/default-application-controller/controller_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#14704 change dex values accordingly to migration for local kind
  cmd/kubermatic-installer/cmd_local.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#14665 update to Go 1.24.4
  .prow/applications-catalog.yaml
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#14728 Skip Quota validations for cpus if vCPUs field is used
  cmd/conformance-tester/pkg/scenarios/kubevirt.go
  pkg/ee/validation/machine/providers.go
  pkg/ee/validation/machine/providers_test.go
  pkg/machine/provider/kubevirt.go
  pkg/machine/provider/kubevirt_test.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, docs/none

#14741 revert changes regarding labels in promtail chart
  charts/logging/promtail/test/default.yaml.out
  charts/logging/promtail/test/kubermatic.example.ce.yaml.out
  charts/logging/promtail/test/kubermatic.example.ee.yaml.out
  charts/logging/promtail/values.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/app-management, kind/regression, docs/none

#14667 [release/v2.27] update to Go 1.23.10
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: kind/cleanup, size/L, lgtm, approved, release-note, dco-signoff: yes, cherry-pick-approved, code-freeze-approved

#14743 Format the changelog for KKP minor release v2.28.0
  docs/changelogs/CHANGELOG-2.28.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#14505 Update new image tag for the KKP owned images
  .golangci.yml
  charts/minio/test/enable-ingress.yaml.out
  charts/minio/test/image-pull-secret.yaml.out
  charts/minio/test/values.example.ce.yaml.out
  charts/minio/test/values.example.ee.yaml.out
  charts/minio/values.yaml
  charts/monitoring/grafana/values.yaml
  charts/monitoring/karma/test/default.yaml.out
  charts/monitoring/karma/test/values.example.ce.yaml.out
  charts/monitoring/karma/test/values.example.ee.yaml.out
  charts/monitoring/karma/values.yaml
  hack/ci/testdata/minio_bucket_job.yaml
  hack/lib.sh
  pkg/controller/operator/common/resources_test.go
  pkg/controller/seed-controller-manager/kubernetes/pending_test.go
  pkg/provider/cloud/kubevirt/manifests/manifests_test.go
  pkg/resources/data_audit_test.go
  pkg/test/fake/builder.go
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/none

#14748 [release/v2.26] KubeLB: Enable kubelb for a cluster by default if it's enforced at the datacenter level
  pkg/defaulting/cluster.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, cherry-pick-approved

#14751 Suppress consent screen in IAP deployments by default
  charts/iap/templates/configmaps.yaml
  charts/iap/test/values.custom-tls-secret.yaml
  charts/iap/test/values.custom-tls-secret.yaml.out
  charts/iap/test/values.example.yaml.out
  charts/iap/values.yaml
  charts/kubermatic.example.ce.yaml
Labels: kind/cleanup, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none
