Repository kubermatic/kubermatic, pull requests merged in 2025-01, with the labels that each got.

#13948 Mark domain as optional for OpenStack preset
  pkg/apis/kubermatic/v1/preset.go
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: kind/cleanup, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#13952 [release/v2.24] Mark domain as optional field for OpenStack preset
  pkg/apis/kubermatic/v1/preset.go
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#13951 [release/v2.25] Mark domain as optional field for OpenStack preset
  pkg/apis/kubermatic/v1/preset.go
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/resources/reconciling/zz_generated_reconcile.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#13954 Download KKP Installer Charts Dependencies
  hack/lib.sh
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, docs/none

#13938 Mount synced `ca-bundle` ConfigMap into kubermatic-seed-controller-manager
  pkg/controller/operator/seed/resources/kubermatic/kubermatic.go
  pkg/controller/operator/seed/resources/kubermatic/seed-controller-manager.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#13955 [EE] fix ClusterBackupStorageLocation sync on remote seed clusters, add more tests
  pkg/ee/cluster-backup/master/sync-controller/controller.go
  pkg/ee/cluster-backup/master/sync-controller/controller_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, docs/none

#13961 bump golang.org/x/net to 0.33.0 (fixes CVE-2024-45338)
  go.mod
  go.sum
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, docs/none

#13565 make reconciling for clusters with LoadBalancer expose strategy clearer
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/resources/apiserver/tls-serving-certificate.go
  pkg/resources/data.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#13953 set rollback revision explicit to last deployed for helm releases managed by applicationinstallations
  pkg/applications/helmclient/client.go
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, docs/none

#13940 minor changes to values.yaml for velero so that default install of velero works without errors
  charts/backup/velero/test/default.yaml.out
  charts/backup/velero/test/values.example.ce.yaml.out
  charts/backup/velero/test/values.example.ee.yaml.out
  charts/backup/velero/values.yaml
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, kind/regression, docs/none

#13860 [charts/argocd] added few test for the argocd chart. added capability to specify auto-sync on/off for each object
  charts/gitops/kkp-argocd-apps/Chart.yaml
  charts/gitops/kkp-argocd-apps/README.md
  charts/gitops/kkp-argocd-apps/templates/argocd-apps-backup.yaml
  charts/gitops/kkp-argocd-apps/templates/argocd-apps-kkp-core.yaml
  charts/gitops/kkp-argocd-apps/templates/argocd-apps-logging.yaml
  charts/gitops/kkp-argocd-apps/templates/argocd-apps-monitoring.yaml
  charts/gitops/kkp-argocd-apps/templates/argocd-apps-storage.yaml
  charts/gitops/kkp-argocd-apps/templates/argocd-apps-usermla.yaml
  charts/gitops/kkp-argocd-apps/test/default.yaml
  charts/gitops/kkp-argocd-apps/test/default.yaml.out
  charts/gitops/kkp-argocd-apps/test/realworld.yaml
  charts/gitops/kkp-argocd-apps/test/realworld.yaml.out
  charts/gitops/kkp-argocd-apps/test/test.sh
  charts/gitops/kkp-argocd-apps/values.yaml
Labels: kind/feature, size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#13981 [release/v2.24] set rollback revision explicit to last deployed for helm releases managed by applicationinstallations (#13953)
  pkg/applications/helmclient/client.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved

#13980 [release/v2.25] set rollback revision explicit to last deployed for helm releases managed by applicationinstallations (#13953)
  pkg/applications/helmclient/client.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved

#13985 Disable Storage Classes Filtering
  pkg/provider/cloud/kubevirt/storage_class.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#13960 [EE] fix kubeLB cleanup not being performed when clusters are deleted
  pkg/ee/kubelb/cleanup.go
  pkg/ee/kubelb/controller.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, docs/none

#13801 Update/Automate vSphere CSI Driver addon
  .prow/provider-vsphere.yaml
  addons/csi/vsphere/Kustomization
  addons/csi/vsphere/Makefile
  addons/csi/vsphere/_footer.txt
  addons/csi/vsphere/_header.txt
  addons/csi/vsphere/driver.yaml
  addons/csi/vsphere/vsphere-csi-driver.yaml
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#13996 Bump Kubevirt CSI Driver Operator
  addons/csi/kubevirt/csi-driver-operator.yaml
Labels: kind/feature, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/none

#13997 Add Check for Pointer Nil Exception for KubeVirt NamespacedMode check
  pkg/provider/cloud/kubevirt/storage_class.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#13983 do not add InTree*Unregister feature gates to clusters on Kubernetes 1.30+
  pkg/resources/data.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#13999 [release/v2.24] Add changelog for KKP next patch release - Jan 2025
  docs/changelogs/CHANGELOG-2.24.md
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved

#14000 [release/v2.25] Add changelogs for KKP next patch releases - Jan 2025
  docs/changelogs/CHANGELOG-2.24.md
  docs/changelogs/CHANGELOG-2.25.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#14001 [release/v2.26] Add changelogs for KKP next patch releases - Jan 2025
  docs/changelogs/CHANGELOG-2.24.md
  docs/changelogs/CHANGELOG-2.25.md
  docs/changelogs/CHANGELOG-2.26.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#14007 drop Velero Kopia pods from Prometheus
  charts/backup/velero/test/default.yaml.out
  charts/backup/velero/test/values.example.ce.yaml.out
  charts/backup/velero/test/values.example.ee.yaml.out
  charts/monitoring/prometheus/config/scraping/pods.yaml
  charts/monitoring/prometheus/test/default.yaml.out
  charts/monitoring/prometheus/test/values.example.ce.yaml.out
  charts/monitoring/prometheus/test/values.example.ee.yaml.out
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#13967 fix kubevirt tenant rbac
  pkg/provider/cloud/kubevirt/csi.go
Labels: kind/bug, needs-ok-to-test, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#13945 add templating for pre defined app values
  cmd/user-cluster-controller-manager/main.go
  codegen/godoc/main.go
  docs/zz_generated.applicationdata.go.txt
  hack/ci/update-docs.sh
  pkg/applications/installer.go
  pkg/applications/providers/template/helm.go
  pkg/applications/providers/template/helm_integration_test.go
  pkg/applications/providers/template/wrappers_ce.go
  pkg/applications/providers/template/wrappers_ee.go
  pkg/applications/providers/types.go
  pkg/applications/test/kubernetes.go
  pkg/ee/applications/util.go
  pkg/ee/applications/util_test.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/tbd

#14011 bump kubevirt csi driver operator
  addons/csi/kubevirt/csi-driver-operator.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/none

#14018 [release/v2.26] Refresh changelog for KKP patch release 2.26.3
  docs/changelogs/CHANGELOG-2.26.md
Labels: kind/documentation, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, cherry-pick-approved

#14006 Sync changelogs for KKP Patch releases - Jan 2025
  docs/changelogs/CHANGELOG-2.24.md
  docs/changelogs/CHANGELOG-2.25.md
  docs/changelogs/CHANGELOG-2.26.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#14022 [release/v2.26] use OSM 1.6.1 instead of a random main branch commit.
  go.mod
  go.sum
Labels: kind/cleanup, lgtm, approved, release-note, size/XS, dco-signoff: yes, cherry-pick-approved

#14023 Read Kubevirt User Cluster Storage Classes from the Seed
  pkg/provider/cloud/kubevirt/storage_class.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#14027 [release/v2.26] add changelog for 2.26.4
  docs/changelogs/CHANGELOG-2.26.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved

#14031 Bump go-git to v5.13.1
  .prow/tests.yaml
  go.mod
  go.sum
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, docs/none

#14030 add changelog for 2.26.4
  docs/changelogs/CHANGELOG-2.26.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, docs/none

#14010 Increase flake attempts to improve kube 1.32's fragile new conformance tests
  cmd/conformance-tester/pkg/tests/conformance.go
Labels: kind/bug, kind/flake, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#14034 Fix the misleading CNI check error
  pkg/controller/seed-controller-manager/default-application-controller/controller.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14059 Bump latest patch release for supported k8s versions
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: size/S, kind/documentation, lgtm, approved, release-note, dco-signoff: yes, docs/none

#14063 include missing images for the kubermatic installer
  pkg/install/images/images.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#14064 Include the Kubevirt CSI driver ds in the local-kubevirt setup
  charts/local-kubevirt/templates/kubevirt-csi-driver.yaml
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#14066 fix application installation app namespace defaulting
  cmd/user-cluster-webhook/main.go
  codegen/example-yaml/main.go
  pkg/apis/apps.kubermatic/v1/application_installation.go
  pkg/apis/apps.kubermatic/v1/zz_generated.deepcopy.go
  pkg/applications/installer_test.go
  pkg/applications/providers/template/helm_integration_test.go
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go
  pkg/controller/seed-controller-manager/default-application-controller/controller.go
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_test.go
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationdefinitions.yaml
  pkg/crd/k8c.io/apps.kubermatic.k8c.io_applicationinstallations.yaml
  pkg/defaulting/application_installation_test.go
  pkg/validation/application_installation_test.go
  pkg/webhook/application/applicationinstallation/mutation/mutation.go
  pkg/webhook/application/applicationinstallation/mutation/mutation_test.go
  pkg/webhook/application/applicationinstallation/validation/validation_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/networking, docs/none

#14002 Add policy template and policy instance crds for Kyverno integration
  .codespell.exclude
  .wwhrd.yml
  go.mod
  go.sum
  hack/update-codegen.sh
  pkg/apis/kubermatic/v1/policy_binding.go
  pkg/apis/kubermatic/v1/policy_template.go
  pkg/apis/kubermatic/v1/register.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_policybindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_policytemplates.yaml
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14069 [release/v2.26] Bump latest patch release for supported k8s versions
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: kind/documentation, lgtm, approved, release-note, size/XS, dco-signoff: yes, cherry-pick-approved

#14072 Use ca-bundle when communicating to minio for metering
  pkg/ee/metering/reconcile.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, ee, docs/none

#14076 Add a new vmEvictionStrategy field to the KubeVirt DC
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  go.mod
  go.sum
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/machine/provider/kubevirt.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14051 Bump Canal to v3.29.1 and deprecate v3.26
  addons/canal/canal_v3.29.yaml
  pkg/cni/version.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, sig/networking, kind/chore, docs/none

#14029 Allow to set default NodePort allowed CIDR on the seed level
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/provider/cloud/aws/security_group.go
  pkg/provider/cloud/azure/security_group.go
  pkg/provider/cloud/gcp/firewall_rules.go
  pkg/provider/cloud/openstack/provider.go
  pkg/resources/resources.go
  pkg/resources/resources_test.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/tbd

#14057 move autoscaler from addons to applications
  cmd/user-cluster-controller-manager/main.go
  docs/zz_generated.applicationdata.go.txt
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller_integration_test.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/wrappers_ce.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/wrappers_ee.go
  pkg/ee/applications/util.go
  pkg/ee/applications/util_test.go
  pkg/ee/default-application-catalog/applicationdefinitions/cluster-autoscaler.yaml
  pkg/resources/usercluster/rbac.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/provided, code-freeze-approved

#14033 Fix Node Label Overwriting in Initial Machine Deployment Controller
  pkg/controller/seed-controller-manager/initial-machinedeployment-controller/machinedeployment.go
Labels: kind/bug, customer-request, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none
