Repository kubermatic/kubermatic, pull requests merged in 2025-07, with the labels that each got.

#14762 Update Prometheus Cluster Role
  charts/monitoring/prometheus/templates/clusterrole.yaml
  charts/monitoring/prometheus/test/default.yaml.out
  charts/monitoring/prometheus/test/values.example.ce.yaml.out
  charts/monitoring/prometheus/test/values.example.ee.yaml.out
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, docs/none

#14770 Use resources.BackupCABundleConfigMapName() everywhere
  pkg/controller/master-controller-manager/rbac/sync_resource.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller.go
  pkg/resources/etcd/backup/jobs.go
  pkg/resources/etcd/backup/utils.go
Labels: kind/cleanup, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#14771 Openstack: Add ability to skip router reconciliation
  pkg/kubernetes/helper.go
  pkg/provider/cloud/openstack/provider.go
  sdk/apis/kubermatic/v1/common.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/provided, backport-needed

#14783 Add k8s patch releases for 1.33/1.32/1.31/1.30
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, docs/none

#14724 Fix etcd health check failure inside etcd pod for KKP user clusters
  pkg/resources/etcd/statefulset.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14714 Fix log spam on deleted ResourceQuota objects
  pkg/ee/resource-quota/master-controller/controller.go
  pkg/ee/resource-quota/seed-controller/controller.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, docs/none, code-freeze-approved

#14809 Refactor EtcdRestore Finalizer Removal
  pkg/controller/seed-controller-manager/etcdrestore/etcd_restore_controller.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#14745 Configure registry mirrors at Cluster level
  codegen/example-yaml/main.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/resources/operatingsystemmanager/deployment.go
  pkg/resources/operatingsystemmanager/deployment_test.go
  pkg/test/generator/objects.go
  sdk/apis/kubermatic/v1/cluster.go
  sdk/apis/kubermatic/v1/datacenter.go
  sdk/apis/kubermatic/v1/zz_generated.deepcopy.go
Labels: size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/tbd

#14822 Add rules for Velero resources to allow get, list, and watch operations for users with viewer access
  pkg/controller/user-cluster-controller-manager/rbac/resources.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#14843 Add an option to restrict project modification to admins
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticsettings.yaml
  sdk/apis/kubermatic/v1/settings.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14848 add limits and timeouts to s3 client
  pkg/util/s3/client.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, docs/none

#14853 Bump Cert-manager to v1.17.4
  charts/cert-manager/Chart.lock
  charts/cert-manager/Chart.yaml
  charts/cert-manager/test/default.yaml.out
  charts/cert-manager/test/override-controller-test.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#14852 Bump Dex chart to appversion 2.42.0
  charts/dex/Chart.lock
  charts/dex/Chart.yaml
  charts/dex/test/default.yaml.out
  charts/dex/test/values.example.ce.yaml.out
  charts/dex/test/values.example.ee.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#14855 [release/v2.26] Update Helm v3.17.4
  go.mod
  go.sum
  pkg/crd/k8c.io/kubermatic.k8c.io_kubermaticconfigurations.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved
