Repository kubermatic/kubermatic, pull requests merged in 2025-04, with the labels that each got.

#14309 Change imagePullPolicy for node-local-dns in user clusters
  pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/deamonset.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#14321 Fix Dex migration documentation link
  pkg/install/stack/kubermatic-master/dex.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#14341 Add nginx-app secure version 1.12.1
  pkg/ee/default-application-catalog/applicationdefinitions/nginx-app.yaml
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/app-management, docs/none

#14336 [release/v2.25] Bump etcd to 3.5.17 in all Kubernetes releases (#14315)
  go.mod
  go.sum
  pkg/resources/etcd/statefulset.go
  pkg/resources/test/fixtures/statefulset-aws-1.27.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.27.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.28.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.28.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.29.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.29.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.27.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.27.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.28.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.28.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.29.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.29.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.27.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.28.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.29.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.27.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.27.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.28.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.28.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.29.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.29.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-edge-1.27.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-edge-1.28.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-edge-1.29.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.27.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.27.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.28.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.28.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.29.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.29.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.27.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.27.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.28.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.28.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.29.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.29.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vcd-1.27.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vcd-1.28.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vcd-1.29.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.27.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.27.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.28.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.28.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.29.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.29.0-etcd.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, cherry-pick-approved

#14346 [release/v2.25] Add changelogs for KKP Patch release v2.25.16
  docs/changelogs/CHANGELOG-2.25.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved

#14347 [release/v2.26] Add changelogs for KKP Patch releases for April 2025
  docs/changelogs/CHANGELOG-2.25.md
  docs/changelogs/CHANGELOG-2.26.md
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved

#14348 [release/v2.27] Add changelogs for KKP Patch releases for April 2025
  docs/changelogs/CHANGELOG-2.25.md
  docs/changelogs/CHANGELOG-2.26.md
  docs/changelogs/CHANGELOG-2.27.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved

#14349 Sync changelogs of KKP patch releases for April 2025
  docs/changelogs/CHANGELOG-2.25.md
  docs/changelogs/CHANGELOG-2.26.md
  docs/changelogs/CHANGELOG-2.27.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, docs/none

#14353 Update credentials.go
  pkg/provider/cloud/vsphere/credentials.go
Labels: kind/cleanup, needs-ok-to-test, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/provided

#14269 Remove Support for Multiple Security Groups in OpenStack Provider
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/provider/cloud/openstack/helper.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/openstack/provider_test.go
  pkg/provider/cloud/openstack/routers.go
  pkg/provider/cloud/openstack/security_group.go
  pkg/provider/cloud/openstack/subnets.go
  pkg/resources/test/load_files_test.go
  sdk/apis/kubermatic/v1/cluster.go
Labels: size/L, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/cluster-management, docs/none

#14159 Add support for using a proxy between KKP and the nodeport-proxy
  cmd/conformance-tester/main.go
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/cluster/client/client.go
  pkg/controller/master-controller-manager/seed-proxy/resources.go
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  sdk/apis/kubermatic/v1/datacenter.go
  sdk/apis/kubermatic/v1/zz_generated.deepcopy.go
Labels: kind/feature, size/L, ok-to-test, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14324 Download kube-test binaries on demand
  hack/ci/run-conformance-tests.sh
  hack/lib.sh
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#14302 (chore): add e2e tests for encryption-at-rest
  .prow/features.yaml
  hack/ci/run-encryption-at-rest-tests.sh
  pkg/controller/seed-controller-manager/encryption-at-rest-controller/controller.go
  pkg/controller/seed-controller-manager/encryption-at-rest-controller/encryption.go
  pkg/test/e2e/encryption-at-rest/ear_test.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#14312 E2E tests for Default Application Catalog
  .prow/applications-catalog.yaml
  hack/ci/README.md
  hack/ci/run-default-application-e2e-test.sh
  hack/ci/setup-kubermatic-in-kind.sh
  pkg/ee/default-application-catalog/applicationdefinitions/cluster-autoscaler-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/kubevirt-app.yaml
  pkg/test/e2e/defaultappcatalog/application_test.go
Labels: kind/feature, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#14364 Upgrade KubeLB CCM to latest image
  pkg/ee/kubelb/resources/seed-cluster/deployment.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none

#14372 update metering to version 1.2.2
  pkg/ee/metering/reconcile.go
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, docs/none

#14357 Upgrade process fix for kube-state-metrics
  pkg/install/stack/seed-mla/stack.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, docs/tbd

#14153 Fix the router-subnet-link cleanup issue in OpenStack
  pkg/provider/cloud/openstack/provider.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14359 Fix the auto-deletion of SG not created by KKP in Openstack
  pkg/provider/cloud/openstack/provider.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14388 Update oauth2-proxy to v7.8.2
  charts/iap/Chart.yaml
  charts/iap/test/values.custom-tls-secret.yaml.out
  charts/iap/test/values.example.yaml.out
  charts/iap/values.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#14362 (feat): Introduce support for multiple OpenStack LoadBalancerClasses
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/resources/cloudconfig/openstack/cloudconfig.go
  sdk/apis/kubermatic/v1/datacenter.go
  sdk/apis/kubermatic/v1/zz_generated.deepcopy.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14385 Bump default k8s version and patch releases
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, kind/chore, docs/none

#14360 fix: each openstack cluster reconcile its own router
  pkg/provider/cloud/openstack/provider.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14396 Fixed value for the flag use-ingress-class
  pkg/ee/kubelb/resources/seed-cluster/deployment.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, docs/none

#14400 Update Cert-manager to v1.16.5
  charts/cert-manager/Chart.lock
  charts/cert-manager/Chart.yaml
  charts/cert-manager/crd/cert-manager.crds.yaml
  charts/cert-manager/test/default.yaml.out
  charts/cert-manager/test/override-controller-test.yaml.out
  charts/cert-manager/values.yaml
Labels: size/XXL, release-note-action-required, lgtm, approved, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#14392 [release/v2.26] Update oauth2-proxy to v7.8.2
  charts/iap/Chart.yaml
  charts/iap/test/values.custom-tls-secret.yaml.out
  charts/iap/test/values.example.yaml.out
  charts/iap/values.yaml
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, cherry-pick-approved

#14414 Support MatchSubnetAndStorageLocation for KubeVirt Provider.
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  sdk/apis/kubermatic/v1/datacenter.go
  sdk/apis/kubermatic/v1/zz_generated.deepcopy.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#14380 Integrate master/seed syncer for policy templates
  .wwhrd.yml
  cmd/master-controller-manager/controllers.go
  go.mod
  go.sum
  hack/reconciling.yaml
  pkg/controller/master-controller-manager/policy-template-synchronizer/OWNERS
  pkg/controller/master-controller-manager/policy-template-synchronizer/controller.go
  pkg/controller/master-controller-manager/policy-template-synchronizer/controller_test.go
  pkg/controller/master-controller-manager/policy-template-synchronizer/doc.go
  pkg/resources/reconciling/zz_generated_reconcile.go
  sdk/apis/kubermatic/v1/policy_template.go
Labels: kind/feature, size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#14356 fix: overwriting etcd backup images
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller.go
  pkg/controller/seed-controller-manager/etcdbackup/etcd_backup_controller_test.go
  pkg/resources/data.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14409 Update k8s-dns-node-cache to 1.25.0
  pkg/controller/user-cluster-controller-manager/resources/resources/node-local-dns/deamonset.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#14395 [release/v2.26] Bump default k8s version and patch releases
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, kind/chore, cherry-pick-approved

#14417 bump etcd to 3.5.21 in all Kubernetes releases
  go.mod
  go.sum
  pkg/resources/etcd/statefulset.go
  pkg/resources/test/fixtures/statefulset-aws-1.30.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.30.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.31.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.31.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.32.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-aws-1.32.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.30.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.30.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.31.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.31.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.32.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-azure-1.32.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-baremetal-1.30.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-baremetal-1.31.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-baremetal-1.32.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.30.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.31.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-bringyourown-1.32.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.30.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.30.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.31.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.31.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.32.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-digitalocean-1.32.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-edge-1.30.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-edge-1.31.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-edge-1.32.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.30.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.30.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.31.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.31.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.32.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-gcp-1.32.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.30.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.30.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.31.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.31.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.32.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-openstack-1.32.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vcd-1.30.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vcd-1.31.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vcd-1.32.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.30.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.30.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.31.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.31.0-etcd.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.32.0-etcd-externalCloudProvider.yaml
  pkg/resources/test/fixtures/statefulset-vsphere-1.32.0-etcd.yaml
Labels: kind/bug, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none
