Repository kubermatic/kubermatic, pull requests merged in 2025-05, with the labels that each got.

#14424 (chore): Update dev-getting-started.md
  docs/dev-getting-started.md
Labels: kind/documentation, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#14367 (feat): Add configurable etcd quota backend bytes
  cmd/etcd-launcher/cmd_run.go
  cmd/etcd-launcher/pkg/etcd/cluster.go
  cmd/etcd-launcher/pkg/etcd/cmd.go
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/controller/seed-controller-manager/kubernetes/resources.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/install/images/images.go
  pkg/resources/etcd/statefulset.go
  pkg/resources/etcd/statefulset_test.go
  pkg/resources/etcd/testdata/etcd-command-with-launcher-and-quota-backend-bytes.golden.sh
  pkg/resources/etcd/testdata/etcd-command-with-launcher-and-with-corruption-flags.golden.sh
  pkg/resources/etcd/testdata/etcd-command-with-launcher.golden.sh
  pkg/resources/etcd/testdata/etcd-command-without-launcher-and-quota-backend-bytes.golden.sh
  pkg/resources/etcd/testdata/etcd-command-without-launcher-and-with-corruption-flags.golden.sh
  pkg/resources/etcd/testdata/etcd-command-without-launcher.golden.sh
  pkg/resources/resources.go
  pkg/resources/test/load_files_test.go
  sdk/apis/kubermatic/v1/cluster.go
  sdk/apis/kubermatic/v1/zz_generated.deepcopy.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14370 fix: dex chart needs secret to store large artifacts of theme
  charts/dex/templates/theme.yaml
  charts/dex/test/default.yaml.out
Labels: kind/bug, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, kind/regression, docs/provided

#14429 add cleanup of kubevirt netpols in kv infra clusters
  pkg/ee/kubevirt-network-controller/controller.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#14435 [release/v2.26] Update Cilium to 1.15.16
  go.mod
  go.sum
  pkg/cni/cilium/cilium-mirror-chart.sh
  pkg/cni/cilium/cilium.go
  pkg/cni/version.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/networking, kind/chore, cherry-pick-approved

#14434 Update Cilium to 1.15.16/1.16.9
  go.mod
  go.sum
  pkg/cni/cilium/cilium-mirror-chart.sh
  pkg/cni/cilium/cilium.go
  pkg/cni/version.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/networking, kind/chore, docs/none

#14436 [release/v2.27] Update Cilium to 1.15.16/1.16.9
  go.mod
  go.sum
  pkg/cni/cilium/cilium-mirror-chart.sh
  pkg/cni/cilium/cilium.go
  pkg/cni/version.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/networking, kind/chore, cherry-pick-approved

#14433 Add support for global viewer role for a user
  pkg/crd/k8c.io/kubermatic.k8c.io_users.yaml
  pkg/validation/user.go
  sdk/apis/kubermatic/v1/user.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/tbd

#14445 [release/v2.25] Add changelog for KKP patch release May 2025
  docs/changelogs/CHANGELOG-2.25.md
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved

#14446 [release/v2.26] Add changelogs for KKP patch releases - May 2025
  docs/changelogs/CHANGELOG-2.25.md
  docs/changelogs/CHANGELOG-2.26.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#14448 Deprecate Equinix Metal provider
  cmd/conformance-tester/pkg/runner/runner.go
  cmd/conformance-tester/pkg/scenarios/packet.go
  codegen/example-yaml/main.go
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_presets.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/install/images/images.go
  pkg/machine/helpers.go
  pkg/machine/provider/equinixmetal.go
  pkg/machine/provider/equinixmetal_test.go
  pkg/provider/cloud/packet/provider.go
  pkg/provider/cloud/provider.go
  pkg/provider/kubernetes/credentials.go
  pkg/resources/credentials.go
  pkg/resources/data.go
  pkg/test/e2e/jig/presets.go
  pkg/validation/cluster.go
  sdk/apis/kubermatic/v1/cluster.go
  sdk/apis/kubermatic/v1/datacenter.go
  sdk/apis/kubermatic/v1/helper/provider.go
  sdk/apis/kubermatic/v1/preset.go
Labels: kind/cleanup, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14447 [release/v2.27] Add changelogs for KKP patch releases - May 2025
  docs/changelogs/CHANGELOG-2.25.md
  docs/changelogs/CHANGELOG-2.26.md
  docs/changelogs/CHANGELOG-2.27.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#14450 Sync changelogs for KKP patch releases for May 2025
  docs/changelogs/CHANGELOG-2.25.md
  docs/changelogs/CHANGELOG-2.26.md
  docs/changelogs/CHANGELOG-2.27.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#14425 feat: ability to disable usersshkey feature in KKP
  cmd/master-controller-manager/controllers.go
  cmd/master-controller-manager/main.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/seed/reconciler.go
  pkg/features/features.go
  pkg/resources/data.go
  pkg/resources/test/fixtures/deployment-aws-1.30.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.30.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.31.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.31.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-aws-1.32.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-aws-1.32.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.30.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.30.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.31.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.31.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-azure-1.32.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-azure-1.32.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-baremetal-1.30.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-baremetal-1.31.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-baremetal-1.32.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.30.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.31.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-bringyourown-1.32.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.30.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.30.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.31.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.31.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.32.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-digitalocean-1.32.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-edge-1.30.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-edge-1.31.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-edge-1.32.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.30.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.30.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.31.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.31.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.32.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-gcp-1.32.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.30.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.30.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.31.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.31.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.32.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-openstack-1.32.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vcd-1.30.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vcd-1.31.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vcd-1.32.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.30.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.30.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.31.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.31.0-usercluster-controller.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.32.0-usercluster-controller-externalCloudProvider.yaml
  pkg/resources/test/fixtures/deployment-vsphere-1.32.0-usercluster-controller.yaml
  pkg/resources/usercluster/deployment.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14432 (feat): Add webhook for PolicyTemplate resource and update template and binding specs
  cmd/kubermatic-webhook/main.go
  hack/update-codegen.sh
  pkg/crd/k8c.io/kubermatic.k8c.io_policybindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_policytemplates.yaml
  pkg/validation/policy_template.go
  pkg/webhook/policytemplate/validation/validation.go
  pkg/webhook/policytemplate/validation/validation_test.go
  sdk/apis/kubermatic/v1/policy_binding.go
  sdk/apis/kubermatic/v1/policy_template.go
  sdk/apis/kubermatic/v1/zz_generated.deepcopy.go
Labels: kind/feature, size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#14437 Add environment variable support for audit logging sidecar
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/resources/apiserver/audit.go
  pkg/resources/apiserver/deployment.go
  pkg/resources/data.go
  pkg/resources/data_audit_test.go
  sdk/apis/kubermatic/v1/audit_logging.go
  sdk/apis/kubermatic/v1/zz_generated.deepcopy.go
Labels: kind/feature, size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/tbd

#14457 Fix Binding location to be in Seed in cluster namespaces
  hack/update-codegen.sh
  pkg/crd/k8c.io/kubermatic.k8c.io_policybindings.yaml
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#14459 Rename the default environment variable used in Audit Logging
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/resources/data.go
  pkg/resources/data_audit_test.go
  sdk/apis/kubermatic/v1/audit_logging.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/provided

#14462 Add ability to define the allowed IP Ranges for API server for user-cluster on Seed Level
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/resources/nodeportproxy/nodeportproxy.go
  pkg/webhook/seed/validation.go
  pkg/webhook/seed/validation_test.go
  sdk/apis/kubermatic/v1/datacenter.go
  sdk/apis/kubermatic/v1/zz_generated.deepcopy.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14465 Improve docs
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  sdk/apis/kubermatic/v1/datacenter.go
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/provided

#14464 Add Audit Logging Configuration on Seed Level
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/defaulting/cluster.go
  sdk/apis/kubermatic/v1/datacenter.go
  sdk/apis/kubermatic/v1/zz_generated.deepcopy.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/provided

#14170 [monitoring] migrate blackbox-exporter to the upstream chart
  charts/monitoring/blackbox-exporter/Chart.lock
  charts/monitoring/blackbox-exporter/Chart.yaml
  charts/monitoring/blackbox-exporter/templates/configmap.yaml
  charts/monitoring/blackbox-exporter/templates/deployment.yaml
  charts/monitoring/blackbox-exporter/templates/service.yaml
  charts/monitoring/blackbox-exporter/test/default.yaml.out
  charts/monitoring/blackbox-exporter/test/values.example.ce.yaml.out
  charts/monitoring/blackbox-exporter/test/values.example.ee.yaml.out
  charts/monitoring/blackbox-exporter/values.yaml
  pkg/install/stack/seed-mla/stack.go
Labels: release-note-action-required, size/XL, lgtm, approved, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/provided

#14467 Revert "fix: each openstack cluster reconcile its own router (#14360)"
  pkg/provider/cloud/openstack/provider.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14469 Fix missing webhook configuration for policytemplate webhook
  pkg/controller/operator/common/resources.go
  pkg/controller/operator/common/webhook.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/operator/seed/reconciler.go
Labels: kind/bug, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#14427 upgrade fluent-bit to v4.0.0
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/resources/apiserver/deployment.go
  sdk/apis/kubermatic/v1/audit_logging.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14403 Updated the versions of the applications from the default app catalog
  .prow/applications-catalog.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/aikit-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/argocd-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/cert-manager-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/cluster-autoscaler-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/falco-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/flux2-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/k8sgpt-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/k8sgpt-operator-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/nginx-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/nvidia-gpu-operator-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/trivy-app.yaml
  pkg/ee/default-application-catalog/applicationdefinitions/trivy-operator-app.yaml
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none

#14473 download envtest binaries on demand rather than baking them into a dedicated container image
  .prow/tests.yaml
  hack/ci/run-addons-integration-test.sh
  hack/images/integration-tests/Dockerfile
  hack/images/integration-tests/settings.sh
  hack/lib.sh
  hack/run-integration-tests.sh
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none

#14502 Bump Kubevirt CSI Driver
  addons/csi/kubevirt/csi-driver-operator.yaml
  pkg/provider/cloud/kubevirt/csi.go
  pkg/resources/csi/kubevirt/deployment.go
Labels: size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/none

#14468 Support shared router across user clusters in the same subnet in Openstack
  pkg/provider/cloud/openstack/helper.go
  pkg/provider/cloud/openstack/internal/testing/simulator.go
  pkg/provider/cloud/openstack/provider.go
  pkg/provider/cloud/openstack/routers.go
  pkg/provider/cloud/openstack/tags.go
  pkg/provider/cloud/openstack/tags_test.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14373 feat(cluster-backup): add tags for backup objects
  pkg/ee/cluster-backup/user-cluster/velero-controller/resources/cluster_backup.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, docs/none

#14451 verify that no accidental Go upgrades happen in release branches
  hack/README.md
  hack/ci/README.md
  hack/ci/verify-go-version.sh
  hack/ci/verify.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/regression, docs/none

#14522 Adjust KubeLB CCM kubeconfig to use API server endpoint from kubeconfig provided to KKP
  pkg/ee/kubelb/cleanup.go
  pkg/ee/kubelb/controller.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, docs/none

#14503 updates to kkp gitops to use new dex chart instead of homegrown oauth helm chart
  charts/gitops/kkp-argocd-apps/Chart.yaml
  charts/gitops/kkp-argocd-apps/templates/argocd-apps-kkp-core.yaml
  charts/gitops/kkp-argocd-apps/test/realworld.yaml
  charts/gitops/kkp-argocd-apps/test/realworld.yaml.out
  charts/gitops/kkp-argocd-apps/values.yaml
Labels: kind/feature, size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/app-management, docs/none

#14558 Enable KubeLB integration for all datacenters of a seed
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/validation/cluster.go
  pkg/validation/cluster_test.go
  pkg/validation/clustertemplate.go
  pkg/webhook/cluster/validation/validation.go
  pkg/webhook/clustertemplate/validation/validation.go
  sdk/apis/kubermatic/v1/datacenter.go
  sdk/apis/kubermatic/v1/zz_generated.deepcopy.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/provided

#14559 kubeLB: update CCM image to v1.1.4
  pkg/ee/kubelb/resources/seed-cluster/deployment.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, docs/none

#14570 rename Vault keys in dev deployment script
  hack/ci/deploy-dev.sh
Labels: kind/cleanup, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#14471 implement default-policy-controller for PolicyBindings propagation
  cmd/seed-controller-manager/wrappers_ee.go
  pkg/crd/k8c.io/kubermatic.k8c.io_policybindings.yaml
  pkg/ee/default-policy-controller/controller.go
  pkg/ee/default-policy-controller/controller_test.go
  pkg/ee/default-policy-controller/doc.go
  sdk/apis/kubermatic/v1/cluster.go
  sdk/apis/kubermatic/v1/policy_binding.go
  sdk/apis/kubermatic/v1/zz_generated.deepcopy.go
Labels: kind/feature, size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#14575 Mount correct ca-bundle configmap in webhook deployment to support custom CA bundles
  pkg/controller/operator/common/webhook.go
  pkg/controller/operator/master/resources/kubermatic/api.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#14578 only consider main version tags when building
  Makefile
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none

#14585 fix skip seed validation in installer
  cmd/kubermatic-installer/cmd_deploy.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#14591 [release/v2.25] fix skip seed validation in installer (#14585)
  cmd/kubermatic-installer/cmd_deploy.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#14584 Migrate Cilium to static ApplicationDefinition YAML
  .prow/applications-catalog.yaml
  cmd/kubermatic-installer/cmd_mirror_images.go
  codegen/godoc/main.go
  pkg/applicationdefinitions/OWNERS
  pkg/applicationdefinitions/application_catalog.go
  pkg/applicationdefinitions/embed.go
  pkg/applicationdefinitions/system-applications/cilium.yaml
  pkg/applicationdefinitions/system-applications/cluster-autoscaler.yaml
  pkg/applications/providers/template/helm.go
  pkg/applications/providers/template/util.go
  pkg/applications/providers/template/util_test.go
  pkg/applications/providers/template/wrappers_ce.go
  pkg/applications/providers/template/wrappers_ee.go
  pkg/cni/cilium/cilium.go
  pkg/cni/cilium/cilium_test.go
  pkg/controller/operator/master/reconciler.go
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go
  pkg/controller/seed-controller-manager/cni-application-installation-controller/validation.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/wrappers_ce.go
  pkg/controller/user-cluster-controller-manager/application-installation-controller/wrappers_ee.go
  pkg/defaulting/configuration.go
  pkg/install/images/application_definitions.go
  pkg/test/e2e/appdefinitions/application_definitions_test.go
  pkg/validation/application_installation.go
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/networking, docs/none

#14472 add default policy catalog to kubermatic installer
  cmd/kubermatic-installer/cmd_deploy.go
  cmd/kubermatic-installer/main_ee.go
  hack/update-policy-catalog.sh
  hack/verify-boilerplate.sh
  pkg/crd/k8c.io/kubermatic.k8c.io_policytemplates.yaml
  pkg/ee/default-policy-catalog/README.md
  pkg/ee/default-policy-catalog/embed.go
  pkg/ee/default-policy-catalog/policies/disallow-capabilities-strict.yml
  pkg/ee/default-policy-catalog/policies/disallow-capabilities.yml
  pkg/ee/default-policy-catalog/policies/disallow-host-namespaces.yml
  pkg/ee/default-policy-catalog/policies/disallow-host-path.yml
  pkg/ee/default-policy-catalog/policies/disallow-host-ports.yml
  pkg/ee/default-policy-catalog/policies/disallow-host-process.yml
  pkg/ee/default-policy-catalog/policies/disallow-privilege-escalation.yml
  pkg/ee/default-policy-catalog/policies/disallow-privileged-containers.yml
  pkg/ee/default-policy-catalog/policies/disallow-proc-mount.yml
  pkg/ee/default-policy-catalog/policies/disallow-selinux.yml
  pkg/ee/default-policy-catalog/policies/require-run-as-non-root-user.yml
  pkg/ee/default-policy-catalog/policies/require-run-as-nonroot.yml
  pkg/ee/default-policy-catalog/policies/restrict-apparmor-profiles.yml
  pkg/ee/default-policy-catalog/policies/restrict-seccomp-strict.yml
  pkg/ee/default-policy-catalog/policies/restrict-seccomp.yml
  pkg/ee/default-policy-catalog/policies/restrict-sysctls.yml
  pkg/ee/default-policy-catalog/policies/restrict-volume-types.yml
  pkg/ee/default-policy-catalog/policy_catalog.go
  pkg/install/stack/kubermatic-master/stack.go
  pkg/install/stack/kubermatic-master/stack_ce.go
  pkg/install/stack/kubermatic-master/stack_ee.go
  pkg/install/stack/types.go
  sdk/apis/kubermatic/v1/policy_template.go
Labels: kind/feature, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14579 Add nginx config to increase header size
  charts/dex/test/default.yaml.out
  charts/dex/values.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
  charts/nginx-ingress-controller/values.yaml
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, docs/none, code-freeze-approved

#14593 Fix validation for kubelb installation
  pkg/validation/cluster.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none, code-freeze-approved

#14521 Support Kubevirt Cloud Provider Load Balancer Disabling
  cmd/conformance-tester/pkg/scenarios/kubevirt.go
  cmd/conformance-tester/pkg/tests/storage.go
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  hack/ci/testdata/seed.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/resources/cloudconfig/kubevirt/cloudconfig.go
  pkg/resources/cloudcontroller/kubevirt.go
  sdk/apis/kubermatic/v1/datacenter.go
  sdk/apis/kubermatic/v1/zz_generated.deepcopy.go
Labels: kind/feature, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/provided

#14609 kubeLB: update CCM image to v1.1.5
  pkg/ee/kubelb/resources/seed-cluster/deployment.go
Labels: lgtm, approved, release-note, size/XS, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#14518 [release/v2.25] verify that no accidental Go upgrades happen in release branches (#14451)
  hack/README.md
  hack/ci/README.md
  hack/ci/verify-go-version.sh
  hack/ci/verify.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#14615 refine selector targeting logic for templates and improve coverage
  pkg/ee/default-policy-controller/controller.go
  pkg/ee/default-policy-controller/controller_test.go
Labels: size/XL, lgtm, approved, release-note-none, dco-signoff: yes, docs/none, code-freeze-approved

#14056 attempt at running argocd kkp CI script
  .prow/features.yaml
  hack/ci/run-argocd-e2e-tests.sh
Labels: kind/feature, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#14626 handle cleanup of bindings when cluster is in deletion
  pkg/ee/policy-binding-controller/controller.go
Labels: kind/bug, lgtm, approved, release-note-none, size/XS, dco-signoff: yes, docs/none, code-freeze-approved

#14624 Add helm values validation for new Dex Chart
  pkg/install/stack/kubermatic-master/validation.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved

#14623 Add mirror-system-application-charts.sh script
  cmd/kubermatic-installer/cmd_mirror_images.go
  hack/README.md
  hack/mirror-system-application-charts.sh
  pkg/applicationdefinitions/system-applications/cluster-autoscaler.yaml
  pkg/cni/cilium/cilium-mirror-chart.sh
  pkg/cni/cilium/doc.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/networking, kind/chore, docs/none, code-freeze-approved

#14630 Remove remove-oauth-release from installer
  charts/dex/values.yaml
  charts/kubermatic.example.ce.yaml
  charts/kubermatic.example.ee.yaml
  charts/values.example.ce.yaml
  charts/values.example.ee.yaml
  cmd/kubermatic-installer/cmd_deploy.go
  pkg/install/stack/kubermatic-master/dex.go
  pkg/install/stack/types.go
Labels: kind/bug, kind/cleanup, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none, code-freeze-approved

#14631 [release/v2.27] Remove remove-oauth-release from installer
  charts/dex/values.yaml
  cmd/kubermatic-installer/cmd_deploy.go
  pkg/install/stack/kubermatic-master/dex.go
  pkg/install/stack/types.go
Labels: kind/bug, kind/cleanup, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, cherry-pick-approved, code-freeze-approved

#14616 Prevent System ApplicationDefinition deletion
  pkg/applicationdefinitions/application_catalog.go
  pkg/applicationdefinitions/system-applications/cluster-autoscaler.yaml
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go
  pkg/controller/seed-controller-manager/default-application-controller/controller.go
  pkg/controller/seed-controller-manager/initial-application-installation-controller/controller.go
  pkg/validation/application_definition.go
  pkg/validation/application_definition_test.go
  pkg/validation/application_installation_test.go
  pkg/webhook/application/applicationdefinition/validation/validation.go
Labels: kind/bug, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, sig/app-management, sig/networking, docs/none, code-freeze-approved

#14635 Add `--insecure` flag to mirror-images command to bypass TLS verification
  cmd/kubermatic-installer/cmd_mirror_images.go
  pkg/install/images/images.go
  pkg/install/images/images_test.go
  pkg/install/images/integration/images_integration_test.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none, code-freeze-approved
