Repository kubermatic/kubermatic, pull requests merged in 2025-03, with the labels that each got.

#14173 Set cilium-envoy enabled to false in the application definition reconciler
  pkg/cni/cilium/cilium.go
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/networking, kind/regression, docs/tbd

#14199 Support KubeVirt Storage Class Infra Cluster Filtration
  addons/csi/kubevirt/csi-driver-operator.yaml
  pkg/apis/kubermatic/v1/datacenter.go
Labels: kind/feature, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/none

#14201 Add crds for kyverno kkp resources (prev revert)
  .codespell.exclude
  .wwhrd.yml
  go.mod
  go.sum
  hack/update-codegen.sh
  pkg/apis/kubermatic/v1/policy_binding.go
  pkg/apis/kubermatic/v1/policy_template.go
  pkg/apis/kubermatic/v1/register.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_policybindings.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_policytemplates.yaml
Labels: kind/feature, size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#14203 [release/v2.27] Set cilium-envoy enabled to false in the application definition reconciler
  pkg/cni/cilium/cilium.go
  pkg/controller/seed-controller-manager/cni-application-installation-controller/controller.go
Labels: lgtm, approved, size/M, release-note, dco-signoff: yes, sig/networking, kind/chore, kind/regression, cherry-pick-approved

#14205 (fix): Parse overrides for knp components during reconciliation
  pkg/controller/user-cluster-controller-manager/resources/reconciler.go
  pkg/controller/user-cluster-controller-manager/resources/resources/konnectivity/deployment.go
  pkg/install/images/images.go
  pkg/resources/konnectivity/sidecar.go
  pkg/resources/resources.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/tbd

#14210 Fix description for Oauth chart
  charts/oauth/README.md
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#14192 fix(release): include dex and gitops chart in ci release
  hack/ci/github-release.sh
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#14220 Add etcd backup images to the mirror-images command
  pkg/install/images/images.go
Labels: kind/bug, lgtm, approved, size/M, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14222 [release/v2.25] Add changelog for KKP patch release 2.25.14
  docs/changelogs/CHANGELOG-2.25.md
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved

#14223 [release/v2.26] Add changelogs for the KKP patch releases - March 2025
  docs/changelogs/CHANGELOG-2.25.md
  docs/changelogs/CHANGELOG-2.26.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#14225 [release/v2.27] Add changelogs for KKP Patch releases for March 2025
  docs/changelogs/CHANGELOG-2.25.md
  docs/changelogs/CHANGELOG-2.26.md
  docs/changelogs/CHANGELOG-2.27.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#14229 Add mirror registries to the Seed example
  codegen/example-yaml/main.go
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/provided

#14145 Fix for auditLogging overwritting on Cluster level
  pkg/defaulting/cluster.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, docs/none

#14189 (feat): Allow configuring Konnectivity Server and Agent channel sizes
  cmd/kubermatic-installer/cmd_deploy.go
  cmd/kubermatic-installer/cmd_mirror_images.go
  cmd/seed-controller-manager/main.go
  cmd/seed-controller-manager/options.go
  docs/zz_generated.seed.ce.yaml
  docs/zz_generated.seed.ee.yaml
  pkg/apis/kubermatic/v1/cluster.go
  pkg/apis/kubermatic/v1/datacenter.go
  pkg/apis/kubermatic/v1/utils.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/applications/providers/types.go
  pkg/controller/seed-controller-manager/addon/addon_controller.go
  pkg/controller/seed-controller-manager/initial-machinedeployment-controller/machinedeployment.go
  pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go
  pkg/crd/fs.go
  pkg/crd/k8c.io/kubermatic.k8c.io_clusters.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_clustertemplates.yaml
  pkg/crd/k8c.io/kubermatic.k8c.io_seeds.yaml
  pkg/resources/data.go
  pkg/resources/data_test.go
  pkg/resources/konnectivity/sidecar.go
  pkg/resources/konnectivity/sidecar_test.go
  pkg/resources/resources.go
Labels: size/XL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, docs/tbd

#14235 [release/v2.26] Bump go-git to v5.13.1 (#14031)
  .prow/tests.yaml
  go.mod
  go.sum
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved

#14174 Replace monitoring/kube-state-metrics chart with upstream one
  charts/monitoring/kube-state-metrics/Chart.lock
  charts/monitoring/kube-state-metrics/Chart.yaml
  charts/monitoring/kube-state-metrics/templates/cluster-role-binding.yaml
  charts/monitoring/kube-state-metrics/templates/cluster-role.yaml
  charts/monitoring/kube-state-metrics/templates/crs-configmap.yaml
  charts/monitoring/kube-state-metrics/templates/deployment.yaml
  charts/monitoring/kube-state-metrics/templates/role-binding.yaml
  charts/monitoring/kube-state-metrics/templates/role.yaml
  charts/monitoring/kube-state-metrics/templates/service-account.yaml
  charts/monitoring/kube-state-metrics/templates/service.yaml
  charts/monitoring/kube-state-metrics/test/values.custom-resource-state.yaml
  charts/monitoring/kube-state-metrics/test/values.custom-resource-state.yaml.out
  charts/monitoring/kube-state-metrics/values.yaml
  pkg/install/stack/seed-mla/stack.go
Labels: kind/feature, size/XXL, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, sig/app-management, kind/chore, docs/tbd

#14125 remove unnecessary mock objects from installer code
  pkg/install/images/images.go
Labels: kind/cleanup, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#14238 Mirror cilium-envoy image
  pkg/install/images/application_definitions.go
Labels: kind/feature, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14231 [release/v2.26] change auth handling when deploying app installation
  pkg/applications/helmclient/testdata/examplechart-git/Chart.yaml
  pkg/applications/helmclient/testdata/examplechart-git/templates/configmap.yaml
  pkg/applications/helmclient/testdata/examplechart-git/values.yaml
  pkg/applications/helmclient/testdata/examplechart-v2/.helmignore
  pkg/applications/helmclient/testdata/examplechart2/.helmignore
  pkg/applications/providers/template/helm.go
  pkg/applications/providers/template/helm_integration_test.go
  pkg/applications/providers/util/util.go
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, cherry-pick-approved

#14248 Fix getVesions from kubermatic configuration
  pkg/install/images/images.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, docs/none

#14243 fix(cluster-backup): fix issue with cluster backup storage controller
  cmd/master-controller-manager/wrappers_ee.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, docs/none

#14247 Switch to runtime.RawExtension for sdk to avoid kyverno dependency
  .codespell.exclude
  .wwhrd.yml
  go.mod
  go.sum
  pkg/apis/kubermatic/v1/policy_template.go
  pkg/apis/kubermatic/v1/zz_generated.deepcopy.go
  pkg/crd/k8c.io/kubermatic.k8c.io_policytemplates.yaml
Labels: size/XXL, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#14257 MC health status is not required for Edge provider
  pkg/apis/kubermatic/v1/cluster.go
  pkg/controller/seed-controller-manager/kubernetes/health.go
Labels: kind/bug, size/S, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/none

#14267 [release/v2.27] Workaround kube-ovn dependency issues
  go.mod
  go.sum
Labels: lgtm, approved, release-note-none, size/XS, dco-signoff: yes, kind/chore, cherry-pick-approved

#14262 Improve mirror-images experience
  cmd/kubermatic-installer/cmd_mirror_images.go
  pkg/install/images/images.go
Labels: kind/feature, size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#14251 Add mirror-binaries subcommand
  cmd/kubermatic-installer/cmd_mirror_binaries.go
  cmd/kubermatic-installer/main_ce.go
  cmd/kubermatic-installer/main_ee.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, docs/provided

#14255 [release/v2.26]: backport CBSL status fix
  cmd/master-controller-manager/wrappers_ee.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, cherry-pick-approved

#14256 [release/v2.27]: backport CBSL status fix
  cmd/master-controller-manager/wrappers_ee.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, cherry-pick-approved

#14276 [release/v2.25] bump nginx to 1.11.5
  .wwhrd.yml
  charts/nginx-ingress-controller/Chart.lock
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
  go.mod
  go.sum
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, cherry-pick-approved

#14273 bump nginx to 1.12.1
  charts/nginx-ingress-controller/Chart.lock
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, docs/none

#14274 [release/v2.27] bump nginx to 1.11.5
  charts/nginx-ingress-controller/Chart.lock
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, cherry-pick-approved

#14275 [release/v2.26] bump nginx to 1.11.5
  charts/nginx-ingress-controller/Chart.lock
  charts/nginx-ingress-controller/Chart.yaml
  charts/nginx-ingress-controller/test/default.yaml.out
  charts/nginx-ingress-controller/test/values.example.ce.yaml.out
  charts/nginx-ingress-controller/test/values.example.ee.yaml.out
Labels: size/L, lgtm, approved, release-note, dco-signoff: yes, sig/app-management, kind/chore, cherry-pick-approved

#14252 [release/v2.27] Fix getVesions from kubermatic configuration
  pkg/install/images/images.go
Labels: kind/bug, lgtm, approved, release-note, size/XS, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#14280 [release/v2.25] Add changelog for KKP patch release v2.25.15
  docs/changelogs/CHANGELOG-2.25.md
Labels: size/S, kind/documentation, lgtm, approved, release-note-none, dco-signoff: yes, cherry-pick-approved

#14284 [release/v2.27] Add changelogs for OOB KKP patch releases
  docs/changelogs/CHANGELOG-2.25.md
  docs/changelogs/CHANGELOG-2.26.md
  docs/changelogs/CHANGELOG-2.27.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, cherry-pick-approved

#14285 Sync changelogs for OOB KKP patch releases for March 2025
  docs/changelogs/CHANGELOG-2.25.md
  docs/changelogs/CHANGELOG-2.26.md
  docs/changelogs/CHANGELOG-2.27.md
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#14277 make policy binding available in master after caching rules
  hack/update-codegen.sh
  pkg/crd/k8c.io/kubermatic.k8c.io_policybindings.yaml
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#14266 Bump default k8s version and patch releases
  docs/zz_generated.kubermaticConfiguration.ce.yaml
  docs/zz_generated.kubermaticConfiguration.ee.yaml
  pkg/defaulting/configuration.go
Labels: size/S, kind/documentation, lgtm, approved, release-note, dco-signoff: yes, docs/none

#14287 change ownership of pkg/provider/kubernetes
  pkg/provider/kubernetes/OWNERS
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, sig/api, kind/chore, docs/none

#14289 [release/v2.25] Bump go-git to v5.13.1 (#14031)
  .prow/tests.yaml
  go.mod
  go.sum
Labels: size/S, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, cherry-pick-approved

#14288 allow to use the update-docs script for release branches
  hack/ci/update-docs.sh
Labels: kind/documentation, lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, docs/none

#14292 bump golang.org/x/* dependencies
  go.mod
  go.sum
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, kind/chore, docs/none

#14294 [release/v2.26] allow to use the update-docs script for release branches (#14288)
  hack/ci/update-docs.sh
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#14279 [release/v2.27] Improve mirror-images experience
  cmd/kubermatic-installer/cmd_mirror_images.go
  pkg/install/images/images.go
Labels: kind/feature, size/L, lgtm, approved, release-note, dco-signoff: yes, sig/cluster-management, cherry-pick-approved

#14300 Bump Go build image version to 1.23.7
  .prow/dualstack.yaml
  .prow/features.yaml
  .prow/provider-anexia.yaml
  .prow/provider-aws.yaml
  .prow/provider-azure.yaml
  .prow/provider-digitalocean.yaml
  .prow/provider-gcp.yaml
  .prow/provider-hetzner.yaml
  .prow/provider-kubevirt.yaml
  .prow/provider-nutanix.yaml
  .prow/provider-openstack.yaml
  .prow/provider-packet.yaml
  .prow/provider-vmware-cloud-director.yaml
  .prow/provider-vsphere.yaml
  .prow/tests.yaml
  cmd/kubeletdnat-controller/Dockerfile.multiarch
  cmd/network-interface-manager/Dockerfile.multiarch
  cmd/user-ssh-keys-agent/Dockerfile.multiarch
  hack/images/integration-tests/Dockerfile
  hack/update-codegen.sh
  hack/update-docs.sh
  hack/update-fixtures.sh
  hack/update-kubermatic-ca-bundle.sh
  hack/verify-licenses.sh
  hack/verify-spelling.sh
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, kind/chore, docs/none

#14306 provide SDK guidance
  sdk/OWNERS
  sdk/README.md
Labels: lgtm, approved, size/M, release-note-none, dco-signoff: yes, docs/none

#14310 update cloud provider SDKs
  go.mod
  go.sum
  pkg/provider/cloud/hetzner/provider.go
Labels: size/L, lgtm, approved, release-note-none, dco-signoff: yes, sig/cluster-management, kind/chore, docs/none
